### ISSUE TITLE
Merge versus concatenate issues with Sequential

### ISSUE THREAD

**Issue by alexhagen** [keras-team/keras#10215]
Hello,

I am having troubles moving over to `Concatenate` from `Merge` because of the deprecation of Merge when merging `Sequential`s.  For my application, **it would be very hard for me to use the functional API**.  In order to show this problem, I have created two virtual environments `old_keras` which uses Keras (2.1.6) installed with `pip install keras`.  I also have another virtual environment using `new_keras` which uses Keras (2.1.6) installed with `pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`.  I don't know the differences between the subversions, but they both return `2.1.6` for `keras.__version__`.

I am running two different scripts:
tm.py (try merge):
```python
import keras
from keras.layers import Dense, Merge
from keras.models import Sequential
from keras.utils.vis_utils import model_to_dot
import numpy as np

left = Sequential()
right = Sequential()
left.add(Dense(1, input_shape=(1,)))
right.add(Dense(1, input_shape=(1,)))
both = Sequential()
both.add(Merge([left, right], mode='concat'))
both.add(Dense(1))
both.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print model_to_dot(both)
both.fit([np.array([[1]]), np.array([[1]])], np.array([[1]]), batch_size=1, epochs=2, verbose=1)
```

and tc.py (try concatenate):
```python
import keras
from keras.layers import Dense, Concatenate
from keras.models import Sequential
from keras.utils.vis_utils import model_to_dot
import numpy as np

left = Sequential()
right = Sequential()
left.add(Dense(1, input_shape=(1,)))
right.add(Dense(1, input_shape=(1,)))
both = Sequential()
both.add(Concatenate([left, right]))
both.add(Dense(1))
both.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print model_to_dot(both)
both.fit([np.array([[1]]), np.array([[1]])], np.array([[1]]), batch_size=1, epochs=2, verbose=1)
```

In the `old_keras` environment, using `tm.py`, I get
```bash
(old_keras) WE35016:tmc hage581$ python tm.py
Using TensorFlow backend.
tm.py:12: UserWarning: The `Merge` layer is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  both.add(Merge([left, right], mode='concat'))
digraph G {
rankdir=TB;
concentrate=True;
node [shape=record];
4697463056 [label="dense_1_input: InputLayer"];
4697597392 [label="dense_2_input: InputLayer"];
4697462800 [label="dense_1: Dense"];
4697463568 [label="dense_2: Dense"];
4697598608 [label="merge_1: Merge"];
4697705616 [label="dense_3: Dense"];
4697463056 -> 4697462800;
4697597392 -> 4697463568;
4697462800 -> 4697598608;
4697463568 -> 4697598608;
4697598608 -> 4697705616;
}

Epoch 1/2
2018-05-16 12:43:12.713797: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
1/1 [==============================] - 0s 200ms/step - loss: 1.1921e-07 - acc: 0.0000e+00
Epoch 2/2
1/1 [==============================] - 0s 2ms/step - loss: 1.1921e-07 - acc: 0.0000e+00
```

which is the expected result.

In the `new_keras` environment, using `tc.py`, I get
```bash
(new_keras) WE35016:tmc hage581$ python tc.py
Using TensorFlow backend.
/Users/hage581/envs/new_keras/lib/python2.7/site-packages/keras/engine/sequential.py:109: UserWarning: `Sequential.model` is deprecated. `Sequential` is a subclass of `Model`, you can just use your `Sequential` instance directly.
  warnings.warn('`Sequential.model` is deprecated. '
digraph G {
rankdir=TB;
concentrate=True;
node [shape=record];
4644568976 [label="concatenate_1: Concatenate"];
4644565456 [label="dense_3: Dense"];
}

Traceback (most recent call last):
  File "tc.py", line 16, in <module>
    both.fit([np.array([[1]]), np.array([[1]])], np.array([[1]]), batch_size=1, epochs=2, verbose=1)
  File "/Users/hage581/envs/new_keras/lib/python2.7/site-packages/keras/engine/training.py", line 950, in fit
    batch_size=batch_size)
  File "/Users/hage581/envs/new_keras/lib/python2.7/site-packages/keras/engine/training.py", line 676, in _standardize_user_data
    self._set_inputs(x)
  File "/Users/hage581/envs/new_keras/lib/python2.7/site-packages/keras/engine/training.py", line 574, in _set_inputs
    assert len(inputs) == 1
AssertionError
```

It can be seen that not only do I error out because of the assertion error, but I don't even get the right network structure (only showing two nodes, not all of the nodes of each subbranch).  I have also had troubles with `keras.layers.merge.concatenate` (note the lower case *c*).  Is there a capability to do this with `Concatenate` or the like, or is Keras pushing everything towards the functional API?

**Comment by alexhagen** [comment]
Oh yes, a matrix of the versions and the scripts

|   | `old_keras` | `new_keras` |
| ------------- | ------------- | ---------|
| `tm.py` | expected result | `ImportError` |
| `tc.py` | `ValueError` | `AssertionError`, incorrect structure | 

- `ValueError: The first layer in a Sequential model must get an `input_shape` or `batch_input_shape` argument.`
- `ImportError: cannot import name Merge`
- `AssertionError`: Shown above

**Comment by johndpope** [comment]
how to migrate this code? 

```python 
from keras.layers import Input, merge
from keras.models import Model
import numpy as np

input_a = np.reshape([1, 2, 3], (1, 1, 3))
input_b = np.reshape([4, 5, 6], (1, 1, 3))

a = Input(shape=(1, 3))
b = Input(shape=(1, 3))
test = [a, b]
concat = merge(test, mode='concat', concat_axis=-1) # this breaks
dot = merge([a, b], mode='dot', dot_axes=2)
cos = merge([a, b], mode='cos', dot_axes=2)

model_concat = Model(input=[a, b], output=concat)
model_dot = Model(input=[a, b], output=dot)
model_cos = Model(input=[a, b], output=cos)

print(input_a)
print(input_b)
print(model_concat.predict([input_a, input_b]))
print(model_dot.predict([input_a, input_b]))
print(model_cos.predict([input_a, input_b]))
 python test.py
/Users/jpope/miniconda2/envs/tensorflow/lib/python3.5/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/Users/jpope/miniconda2/envs/tensorflow/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    concat = merge([a, b], mode='concat', concat_axis=-1)
TypeError: 'module' object is not callable

```

**Comment by johndpope** [comment]
https://stackoverflow.com/questions/42823627/how-to-use-merge-layer-concat-function-on-keras-2-0-0

Keras 1.2.2 code:

```python
from keras.engine import merge
m = merge([init, x], mode='sum')
Equivalent Keras 2.0.2 code:
```

```python
from keras.layers import add
m = add([init, x])
```

**Comment by Wupingyang** [comment]
I have encountered this problem now(AssertionError). Excuse me, have you solved it now?

**Comment by fzhangcode** [comment]
> from keras.layers import add m = add([init, x])

Hi, I still got the same problem. This is my code:

```    view1_model = build_mlp_net(layer_sizes1, input_size1, reg_par)
    view2_model = build_mlp_net(layer_sizes2, input_size2, reg_par)

    model = Sequential()
    # model.add(Concatenate([view1_model, view2_model]))
    # model.add(concatenate([view1_model, view2_model](axis=-1))
    model = add([view1_model, view2_model])

    model_optimizer = RMSprop(lr=learning_rate)

def build_mlp_net(layer_sizes, input_size, reg_par):
    model = Sequential()
    for l_id, ls in enumerate(layer_sizes):
        if l_id == 0:
            input_dim = input_size
        else:
            input_dim = []
        if l_id == len(layer_sizes)-1:
            activation = 'linear'
        else:
            activation = 'sigmoid'

        model.add(Dense(ls, input_dim=input_dim,
                                activation=activation,
                                kernel_regularizer=l2(reg_par)))
    return model```

I have also tried `Concatenate` and `concatenate`, `Merge` and `merge`, but all gave me the same error ```     18     model = Sequential()
---> 19     # model.add(Concatenate([view1_model, view2_model]))
     20     # model.add(concatenate([view1_model, view2_model](axis=-1))
     21     model = add([view1_model, view2_model])

NameError: name 'Merge' is not defined```

**Comment by WrathofBhuvan11** [comment]
I got a similar problem... anybody figured how to fix

**Comment by ByzanTine** [comment]
I managed to resolve the problem by taking a detour to use totally functional API rather than building layers by sequential. Using Sequential will inevitably hit "assert len(inputs) == 1".

**Comment by sohaib730** [comment]
I am getting the same problem as mentioned in tc.py with new keras. Have you found the solution?

**Comment by ms8909** [comment]
Anyone got this to work?
