### ISSUE TITLE
TensorBoard Debugger with Keras; TypeError: zip argument #1 must support iteration

### ISSUE THREAD

**Issue by Faust22** [keras-team/keras#10325]
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Is it possible to use Keras with the TensorBoard debugger? I have used the code posted under Keras within TensorBoard:

import tensorflow as tf
from tensorflow.python import debug as tf_debug
import keras

keras.backend.set_session(
    tf_debug.TensorBoardDebugWrapperSession(tf.Session(), "DESKTOP-AB123CD:6064")).
model.fit(...)

**The callbacks are generated with:**
tensorboard=TensorBoard(log_dir="logs/{}".format(time())
along wit the callbacks=[tensorboard] in model.fit()

**It is opened in command line with:**
tensorboard --logdir=logs/ --port 6006 --debugger 6064

**But, I get the following error when it runs.**

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.1.3\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2018.1.3\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2018.1.3\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2018.1.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Name/Desktop/files/CNN.py", line 139, in <module>
    CNN.add(Conv3D(50,kernel_size=(3,3,3),activation='relu',input_shape=(4,20,20,20), data_format='channels_first',kernel_initializer='glorot_uniform',name='test'))
  File "C:\Users\Name\venv\lib\site-packages\keras\models.py", line 497, in add
    layer(x)
  File "C:\Users\Name\venv\lib\site-packages\keras\engine\topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\Name\venv\lib\site-packages\keras\layers\convolutional.py", line 176, in call
    dilation_rate=self.dilation_rate)
  File "C:\Users\Name\venv\lib\site-packages\keras\backend\tensorflow_backend.py", line 3559, in conv3d
    x, tf_data_format = _preprocess_conv3d_input(x, data_format)
  File "C:\Users\Name\venv\lib\site-packages\keras\backend\tensorflow_backend.py", line 3235, in _preprocess_conv3d_input
    if not _has_nchw_support():
  File "C:\Users\Name\venv\lib\site-packages\keras\backend\tensorflow_backend.py", line 286, in _has_nchw_support
    gpus_available = len(_get_available_gpus()) > 0
  File "C:\Users\Name\venv\lib\site-packages\keras\backend\tensorflow_backend.py", line 272, in _get_available_gpus
    _LOCAL_DEVICES = get_session().list_devices()
  File "C:\Users\Name\venv\lib\site-packages\keras\backend\tensorflow_backend.py", line 195, in get_session
    for flag, v in zip(is_initialized, candidate_vars):
TypeError: zip argument #1 must support iteration

**I have tried quite a few different ways to get this to work, but it seems it may not be supported by Keras yet? **

I also get an error when initially opening up the TensorBoard link in a browser:
/[[_dataImageSrc]] not found, sending 404
/[[_imagureURL]] not found, sending 404

But this may not be related and doesn't seem to affect anything.

Thanks

**Comment by Faust22** [comment]
This turns to to be an issue with TensorBoard debugger not being supported in Windows and is not a Keras issue.
