### ISSUE TITLE
I get no attribute issue with Keras Backend

### ISSUE THREAD

**Issue by Usama-Zafar** [keras-team/keras#10352]
I am trying to implement a 2D convolutional network with keras but the issue is that I get following error:

/home/usama/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using Theano backend.
/home/usama/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Traceback (most recent call last):

  File "<ipython-input-1-6227122cd4a7>", line 1, in <module>
    runfile('/media/usama/Personal/Study/Semester 02/ML/Project/MLSoundProject/code/mlsound.py', wdir='/media/usama/Personal/Study/Semester 02/ML/Project/MLSoundProject/code')

  File "/home/usama/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/home/usama/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/media/usama/Personal/Study/Semester 02/ML/Project/MLSoundProject/code/mlsound.py", line 101, in <module>
    main()

  File "/media/usama/Personal/Study/Semester 02/ML/Project/MLSoundProject/code/mlsound.py", line 92, in main
    predictions_top3 = train.train(tr_mnn_features, tr_mnn_labels, ts_mnn_features, tr_cnn_features, tr_cnn_labels, ts_cnn_features, n_classes=len(dictionary))

  File "/media/usama/Personal/Study/Semester 02/ML/Project/MLSoundProject/code/train.py", line 42, in train
    cnn_2d_y_pred, cnn_2d_probs, cnn_2d_pred = keras_convolution_2D(tr_cnn_features, tr_cnn_labels, ts_cnn_features, n_classes, training_epochs=10)

  File "/media/usama/Personal/Study/Semester 02/ML/Project/MLSoundProject/code/train.py", line 333, in keras_convolution_2D
    K.clear_session()

AttributeError: module 'keras.backend' has no attribute 'clear_session'

The code was working initially, I recently updated my anaconda and this issue started occurring since then. I tried re-installing Keras but to no avail. Can I get a work around for this problem?

**Comment by Dref360** [comment]
You're using the theano backend which doesn't have a `clear_session`, remove it.

**Comment by Dref360** [comment]
You're using the theano backend which doesn't have a `clear_session`, remove it.

**Comment by VanitarNordic** [comment]
You can use  `conda install -c hesi_m keras ` to install **Keras-2.2.0** in accompany with **Tensorflow-1.8.0** for CPU.
