### ISSUE TITLE
Problem with Autoencoders.

### ISSUE THREAD

**Issue by Polychemy** [keras-team/keras#10383]
Hi All i'm following this post on building auto-encoders : https://github.com/keras-team/keras/issues/3923

It was originally written in keras 1, i had to port it over to keras 2.

Here is my code:

```
from keras.layers import Input, Dense, Convolution2D, MaxPooling2D, UpSampling2D, Conv2D
from keras.models import Model
from keras.preprocessing.image import ImageDataGenerator

def fixed_generator(generator):
    for batch in generator:
        yield (batch, batch)

# dimensions of our images.
img_width, img_height = 256, 256

train_data_dir = 'C:\\DATA\\Projects\\AI_Painter\\Images_download\\INPUT\\'
validation_data_dir = 'C:\\DATA\\Projects\\AI_Painter\\Images_download\\OUTPUT\\'
nb_train_samples = 200
nb_validation_samples = 50
nb_epoch = 50
batch_size = 32

input_img = Input(shape=(3, img_width, img_height))

x = Conv2D(16, (3, 3), activation='relu', padding="same")(input_img)
x = MaxPooling2D((2, 2), padding='same')(x)
x = Conv2D(8, (3, 3), activation='relu', padding='same')(x)
x = MaxPooling2D((2, 2), padding='same')(x)
x = Conv2D(8, (3, 3), activation='relu', padding='same')(x)
encoded = MaxPooling2D((2, 2), padding='same')(x)

# at this point the representation is (8, 4, 4) i.e. 128-dimensional

x = Conv2D(8, (3, 3), activation='relu', padding='same')(encoded)
x = UpSampling2D((2, 2))(x)
x = Conv2D(8, (3, 3), activation='relu', padding='same')(x)
x = UpSampling2D((2, 2))(x)
x = Conv2D(16, (3, 3), activation='relu', padding='same')(x)
x = UpSampling2D((2, 2))(x)
decoded = Conv2D(3, (3, 3), activation='sigmoid', padding='same')(x)

autoencoder = Model(input_img, decoded)
autoencoder.compile(optimizer='adadelta', loss='binary_crossentropy')

# this is the augmentation configuration we will use for training
train_datagen = ImageDataGenerator(horizontal_flip=True)

# this is the augmentation configuration we will use for testing:
# only rescaling
test_datagen = ImageDataGenerator()

train_generator = train_datagen.flow_from_directory(
        train_data_dir,
        target_size=(img_width, img_height),
        batch_size=batch_size,
        class_mode=None)

#print type(train_generator)

validation_generator = test_datagen.flow_from_directory(
        validation_data_dir,
        target_size=(img_width, img_height),
        batch_size=batch_size,
        class_mode=None)

autoencoder.fit_generator(
        fixed_generator(train_generator),
        samples_per_epoch=nb_train_samples,
        nb_epoch=nb_epoch,
        validation_data=fixed_generator(validation_generator),
        nb_val_samples=nb_validation_samples
        )

```
I get this error:

> Found 4485 images belonging to 1 classes.
> Found 4485 images belonging to 1 classes.C:/Users/Aaron/.spyder-py3/AI_AutoDraw.py:80: UserWarning: The semantics of the Keras 2 argument `steps_per_epoch` is not the same as the Keras 1 argument `samples_per_epoch`. `steps_per_epoch` is the number of batches to draw from the generator at each epoch. Basically steps_per_epoch = samples_per_epoch/batch_size. Similarly `nb_val_samples`->`validation_steps` and `val_samples`->`steps` arguments have changed. Update your method calls accordingly.
>   nb_val_samples=nb_validation_samples
> C:/Users/Aaron/.spyder-py3/AI_AutoDraw.py:80: UserWarning: Update your `fit_generator` call to the Keras 2 API: `fit_generator(<generator..., validation_data=<generator..., steps_per_epoch=200, epochs=50, validation_steps=50)`
>   nb_val_samples=nb_validation_samples
> 
> Epoch 1/50
> Traceback (most recent call last):
> 
>   File "<ipython-input-237-a795cc722d43>", line 1, in <module>
>     runfile('C:/Users/Aaron/.spyder-py3/AI_AutoDraw.py', wdir='C:/Users/Aaron/.spyder-py3')
> 
>   File "C:\Users\Aaron\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\Users\Aaron\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "C:/Users/Aaron/.spyder-py3/AI_AutoDraw.py", line 80, in <module>
>     nb_val_samples=nb_validation_samples
> 
>   File "C:\Users\Aaron\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
>     return func(*args, **kwargs)
> 
>   File "C:\Users\Aaron\Anaconda3\lib\site-packages\keras\engine\training.py", line 1840, in fit_generator
>     class_weight=class_weight)
> 
>   File "C:\Users\Aaron\Anaconda3\lib\site-packages\keras\engine\training.py", line 1559, in train_on_batch
>     check_batch_axis=True)
> 
>   File "C:\Users\Aaron\Anaconda3\lib\site-packages\keras\engine\training.py", line 1234, in _standardize_user_data
>     exception_prefix='input')
> 
>   File "C:\Users\Aaron\Anaconda3\lib\site-packages\keras\engine\training.py", line 140, in _standardize_input_data
>     str(array.shape))
> 
> **ValueError: Error when checking input: expected input_6 to have shape (None, 3, 256, 256) but got array with shape (32, 256, 256, 3)**

It seems the fit generator is generating inputs in the wrong shape. How do i reshape the data in this case?

**Comment by Polychemy** [comment]
Ok i think ive solved it by changing the inputs to:
input_img = Input(shape=(img_width, img_height,3))

It is training now. not sure about the results though.
