### ISSUE TITLE
CUB segmented reduce errorinvalid configuration argument on training Xception over multiple GPUs

### ISSUE THREAD

**Issue by vodp** [keras-team/keras#10402]
I try to train a deeplabv3 model with xception backbone on a 8-GPU aws instance p3.16x. During the first epoch, at a random step each running time, I got the runtime error `CUB segmented reduce errorinvalid configuration argument` at the `tensor_masking` layer as shown in a part of the network summary below. This layer does a very basic work: element-wise multiplication of two tensors from `reshape_3` and `mask_sigmoid`. With MobileNet V2 backbone I used to train very good on 4-GPU machines without any error. So I guess it is due to value gathering across many GPUs. Any suggestion?

```
reshape_3 (Reshape)             (None, 32, 32, 2048) 0           lambda_7[0][0]
__________________________________________________________________________________________________
mask_sigmoid (Activation)       (None, 32, 32, 1)    0           downsampling_mask[0][0]
__________________________________________________________________________________________________
tensor_masking (Multiply)       (None, 32, 32, 2048) 0           reshape_3[0][0]
                                                                 mask_sigmoid[0][0]
__________________________________________________________________________________________________
max_pooling2d_1 (MaxPooling2D)  (None, 1, 1, 2048)   0           tensor_masking[0][0]
__________________________________________________________________________________________________
batch_normalization_1 (BatchNor (None, 1, 1, 2048)   8192        max_pooling2d_1[0][0]
__________________________________________________________________________________________________
activation_82 (Activation)      (None, 1, 1, 2048)   0           batch_normalization_1[0][0]
__________________________________________________________________________________________________
flatten_1 (Flatten)             (None, 2048)         0           activation_82[0][0]
__________________________________________________________________________________________________
dropout_1 (Dropout)             (None, 2048)         0           flatten_1[0][0]
__________________________________________________________________________________________________
dense_classifier (Dense)        (None, 81)           165969      dropout_1[0][0]
__________________________________________________________________________________________________
mask_output (BilinearUpsampling (None, 512, 512, 1)  0           mucut_logits_mask[0][0]
__________________________________________________________________________________________________
label_output (Activation)       (None, 81)           0           dense_classifier[0][0]
==================================================================================================
Total params: 41,427,234
Trainable params: 166,226
Non-trainable params: 41,261,008
__________________________________________________________________________________________________
Epoch 1/5

Epoch 00001: LearningRateScheduler reducing learning rate to 0.01.
 110/3038 [>.............................] - ETA: 1:40:30 - loss: 7.1357 - mask_output_loss: 0.5988 - label_output_loss: 4.4020 - mask
_output_mean_binary_iou: 0.0785 - label_output_categorical_accuracy: 0.0136 - label_output_top_k_categorical_accuracy: 0.0659Traceback
 (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: CUB segmented reduce errorinvalid configuration argument
         [[Node: training/SGD/gradients/replica_4/mynet/tensor_masking/mul_grad/Sum_1 = Sum[T=DT_FLOAT, Tidx=DT_INT32, _class=["loc:
@training/SGD/gradients/replica_4/mynet/tensor_masking/mul_grad/Reshape_1"], keep_dims=false, _device="/job:localhost/replica:0/task
:0/device:GPU:4"](training/SGD/gradients/replica_4/mynet/tensor_masking/mul_grad/Mul_1, training/SGD/gradients/replica_4/mynet/ten
sor_masking/mul_grad/BroadcastGradientArgs:1)]] 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../mynet/train.py", line 107, in <module>
    main()
  File "../../mynet/train.py", line 102, in main
    warmup_top_then_marathon(args)
  File "/home/ubuntu/mynet/mynet/trainer.py", line 141, in warmup_top_then_marathon
    log_dir=args.log_dir)
  File "/home/ubuntu/mynet/mynet/models/mynet.py", line 132, in train
    epochs=epochs)
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 2230, in fit_generator
    class_weight=class_weight)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1883, in train_on_batch
    outputs = self.train_function(ins)
  File "/usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py", line 2482, in __call__
    **self.session_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: CUB segmented reduce errorinvalid configuration argument
         [[Node: training/SGD/gradients/replica_4/mynet/tensor_masking/mul_grad/Sum_1 = Sum[T=DT_FLOAT, Tidx=DT_INT32, _class=["loc:@training/SGD/gradients/replica_4/mynet/tensor_masking/mul_grad/Reshape_1"], keep_dims=false, _device="/job:localhost/replica:0/task:0/device:GPU:4"](training/SGD/gradients/replica_4/mynet/tensor_masking/mul_grad/Mul_1, training/SGD/gradients/replica_4/mynet/tensor_masking/mul_grad/BroadcastGradientArgs:1)]] 

Caused by op 'training/SGD/gradients/replica_4/mynet/tensor_masking/mul_grad/Sum_1', defined at:
  File "../../mynet/train.py", line 107, in <module>
    main()
  File "../../mynet/train.py", line 102, in main
    warmup_top_then_marathon(args)
  File "/home/ubuntu/mynet/mynet/trainer.py", line 141, in warmup_top_then_marathon
    log_dir=args.log_dir)
  File "/home/ubuntu/mynet/mynet/models/mynet.py", line 132, in train
    epochs=epochs)
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 2080, in fit_generator
    self._make_train_function()
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 992, in _make_train_function
    loss=self.total_loss)
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/optimizers.py", line 173, in get_updates
    grads = self.get_gradients(loss, params)
  File "/usr/local/lib/python3.5/dist-packages/keras/optimizers.py", line 78, in get_gradients
    grads = K.gradients(loss, params)
  File "/usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py", line 2519, in gradients
    return tf.gradients(loss, variables, colocate_gradients_with_ops=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py", line 494, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py", line 636, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py", line 385, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py", line 636, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_grad.py", line 880, in _MulGrad
    math_ops.reduce_sum(gen_math_ops.mul(x, grad), ry), sy))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py", line 1423, in reduce_sum
    name=name))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 8080, in _sum
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

...which was originally created as op 'replica_4/mynet/tensor_masking/mul', defined at:
  File "../../mynet/train.py", line 107, in <module>
    main()
[elided 0 identical lines from previous traceback]
  File "../../mynet/train.py", line 102, in main
    warmup_top_then_marathon(args)
  File "/home/ubuntu/mynet/mynet/trainer.py", line 61, in warmup_top_then_marathon
    num_gpus=find_num_gpus(args.num_gpus))
  File "/home/ubuntu/mynet/mynet/models/mynet.py", line 491, in __init__
    self.make_model(inputs, [mask_head, classifier_head], name='mynet')
  File "/home/ubuntu/mynet/mynet/models/mynet.py", line 69, in make_model
    self.parallel_model = multi_gpu_model(self.model, gpus=self.num_gpus)
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/multi_gpu_utils.py", line 221, in multi_gpu_model
    outputs = model(inputs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 2085, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 2250, in run_internal_graph
    output_tensors = _to_list(layer.call(computed_tensors, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/merge.py", line 155, in call
    return self._merge_function(inputs)
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/merge.py", line 271, in _merge_function
    output *= inputs[i]
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py", line 979, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py", line 1211, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 4759, in mul
    "Mul", x=x, y=y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): CUB segmented reduce errorinvalid configuration argument
         [[Node: training/SGD/gradients/replica_4/mynet/tensor_masking/mul_grad/Sum_1 = Sum[T=DT_FLOAT, Tidx=DT_INT32, _class=["loc:@training/SGD/gradients/replica_4/mynet/tensor_masking/mul_grad/Reshape_1"], keep_dims=false, _device="/job:localhost/replica:0/task:0/device:GPU:4"](training/SGD/gradients/replica_4/mynet/tensor_masking/mul_grad/Mul_1, training/SGD/gradients/replica_4/mynet/tensor_masking/mul_grad/BroadcastGradientArgs:1)]] 
```

**Comment by twinanda** [comment]
I have a code to train a segmentation network, which works well on a single-GPU setup. However, I encountered this issue when I am training the network on a multiple-GPU (2xK80) machine. The funny thing is that the first epoch was running just fine and I got this error at the beginning of the second epoch. Any ideas why?

**Comment by twinanda** [comment]
Another thing I observed is that the optimization on multi-gpu was working fine for me if I use a built-in loss function, i.e., I did classification using categorical_cross_entropy from keras, and it went smoothly. Could this be a hint of the issue?

**Comment by Taylor-Rose** [comment]
I also got the problem like @twinanda ,which runs well at first epoch but went wrong at the second or third epoch , have you got some solutions?

**Comment by Taylor-Rose** [comment]
I also got the problem like @twinanda ,which runs well at first epoch but went wrong at the second or third epoch , have you got some solutions?

**Comment by ningyanuta** [comment]
Same here, training exit at 2nd epoch.
