### ISSUE TITLE
load a fine tune CNN model

### ISSUE THREAD

**Issue by faresbs** [keras-team/keras#10497]
**I am trying to load a fine tune CNN model (vgg-16), that is pretrained on imagenet.**
`pre_model = vgg16.VGG16(include_top=False, weights='imagenet', input_tensor=None, input_shape=(224,224,3))

	#Stack pretrained model layers on the new model
	model = Sequential()
	for layer in pre_model.layers:
		model.add(layer)

	model.add(MaxPooling2D(pool_size=(5, 5), strides=(2, 2), padding='valid'))
	model.add(Flatten())
	model.add(Dense(256, activation='relu'))and  pre trained
	model.add(Dense(num_of_classes, activation='softmax'))

	# set the first n layers to non-trainable (weights will not be updated)
	for layer in model.layers[:16]:and  pre trained
		layer.trainable = False`

**After training i save the model on a .yaml file and the weights on a .hdfs file.**

`#Serialize weights to HDF5
	model.save_weights('weights/'+"cnn_weights.h5")
	
	#Serialize model to YAML
	model_yaml = model.to_yaml()

	#Save model
	with open("weights/"+"cnn_model.yaml", "w") as yaml_file:
		yaml_file.write(model_yaml)`

**Now when i try to load the weights from the hdfs file to the loaded model**

`# load YAML and create model
	yaml_file = open(path+'/cnn_model.yaml', 'r')
	loaded_model_yaml = yaml_file.read()
	yaml_file.close()
	loaded_model = model_from_yaml(loaded_model_yaml)

	# load weights into new model
	loaded_model.load_weights(path+"/cnn_weights.h5", by_name=True)
	print("Loaded model from disk")`

**It throws this error:**

`Traceback (most recent call last):
  File "model.py", line 193, in <module>
    predict(image, PATH)
  File "model.py", line 166, in predict
    loaded_model.load_weights(path+"/cnn_weights.h5", by_name=True)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/network.py", line 1177, in load_weights
    reshape=reshape)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/saving.py", line 986, in load_weights_from_hdf5_group_by_name
    reshape=reshape)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/saving.py", line 657, in preprocess_weights_for_loading
    layer_weights_shape = K.int_shape(layer.weights[0])
IndexError: list index out of range`

I am using keras 2.2 on a tensorflow backend and python 2.7.

**Comment by faresbs** [comment]
I fixed it using this method (https://gist.github.com/baraldilorenzo/07d7802847aaad0a35d3)
