### ISSUE TITLE
multi_gpu_model value error Tensor must be from same graph

### ISSUE THREAD

**Issue by ems7** [keras-team/keras#10541]
```
Traceback (most recent call last):
  File "/home/user/cluster/base/FullyConvolutional.py", line 959, in <module>
    gr.pretrainSBU(110)
  File "/home/user/cluster/base/FullyConvolutional.py", line 897, in pretrainSBU
    period=10)]) # train the new layer until no improvement occurs
  File "/home/user/software/tensorflow/lib/python2.7/site-packages/keras/engine/training.py", line 1013, in fit
    self._make_train_function()
  File "/home/user/software/tensorflow/lib/python2.7/site-packages/keras/engine/training.py", line 497, in _make_train_function
    loss=self.total_loss)
  File "/home/user/software/tensorflow/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/user/software/tensorflow/lib/python2.7/site-packages/keras/optimizers.py", line 381, in get_updates
    new_a = self.rho * a + (1. - self.rho) * K.square(g)
  File "/home/user/software/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 967, in binary_op_wrapper
    with ops.name_scope(None, op_name, [x, y]) as name:
  File "/home/user/software/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 5977, in __enter__
    g = _get_graph_from_inputs(self._values)
  File "/home/user/software/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 5637, in _get_graph_from_inputs
    _assert_same_graph(original_graph_element, graph_element)
  File "/home/user/software/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 5573, in _assert_same_graph
    original_item))
ValueError: Tensor("mul:0", shape=(3, 3, 3, 64), dtype=float32) must be from the same graph as Tensor("training/Adadelta/mul:0", shape=(3, 3, 3, 64), dtype=float32).


```
Python 2.7
Keras version 2.2.0
Tensorflow-gpu version 1.8.0
Cuda 9.0
Cudnn 7.0

Issue occurs when using keras.optimizers.Adadelta(), also occurs with SGD. I haven't tried other optimisers.

**Comment by azammemon2000** [comment]
@ems7 is your problem resolved? can you mention the solution here? I am also facing the same issue.

**Comment by rangsimanketkaew** [comment]
I'm using Keras API - TF 2.2.0 and also found the same problem.
