### ISSUE TITLE
CNN+LSTM

### ISSUE THREAD

**Issue by 13293824182** [keras-team/keras#10614]
I am currently trying to solve an issue using LRCN model which uses a combination of CNN and LSTM. I have followed issues on Github raised and was able to use the timeDistributed() for having time steps that would allow me to use LSTM after CNN. Here is the partial code where I have created the model:

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

        model = Sequential()
        # self.input_shape = (seq_length, 80, 80, 3)
        model.add(TimeDistributed(Conv2D(32, (7, 7), strides=(2, 2),
            activation='relu', padding='same'), input_shape=self.input_shape))
        model.add(TimeDistributed(Conv2D(32, (3,3),
            kernel_initializer="he_normal", activation='relu')))
        model.add(TimeDistributed(MaxPooling2D((2, 2), strides=(2, 2))))

        model.add(TimeDistributed(Conv2D(64, (3,3),
            padding='same', activation='relu')))
        model.add(TimeDistributed(Conv2D(64, (3,3),
            padding='same', activation='relu')))
        model.add(TimeDistributed(MaxPooling2D((2, 2), strides=(2, 2))))

        model.add(TimeDistributed(Conv2D(128, (3,3),
            padding='same', activation='relu')))
        model.add(TimeDistributed(Conv2D(128, (3,3),
            padding='same', activation='relu')))
        model.add(TimeDistributed(MaxPooling2D((2, 2), strides=(2, 2))))

        model.add(TimeDistributed(Conv2D(256, (3,3),
            padding='same', activation='relu')))
        model.add(TimeDistributed(Conv2D(256, (3,3),
            padding='same', activation='relu')))
        model.add(TimeDistributed(MaxPooling2D((2, 2), strides=(2, 2))))
        
        model.add(TimeDistributed(Conv2D(512, (3,3),
            padding='same', activation='relu')))
        model.add(TimeDistributed(Conv2D(512, (3,3),
            padding='same', activation='relu')))
        model.add(TimeDistributed(MaxPooling2D((2, 2), strides=(2, 2))))

        model.add(TimeDistributed(Flatten()))

        model.add(Dropout(0.5))
        model.add(LSTM(256, return_sequences=False, dropout=0.5))
        model.add(Dense(self.nb_classes, activation='softmax'))
        return model
However even following solutions provided in the other issues, I am having teh following error:
Epoch 1/1000
Traceback (most recent call last):
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/tensorflow/python/client/session.py", line                                                                     1350, in _do_call
    return fn(*args)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/tensorflow/python/client/session.py", line                                                                     1329, in _run_fn
    status, run_metadata)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py"                                                                    , line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 10485760 value                                                                    s, but the requested shape has 2621440
         [[Node: gradients/time_distributed_13/Reshape_1_grad/Reshape = _MklReshape[T=DT_FLOAT, Tshape=DT_INT3                                                                    2, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](gradients/time_distributed_14/conv                                                                    olution_grad/Conv2DBackpropInput, gradients/time_distributed_13/Reshape_1_grad/Shape, gradients/time_distribut                                                                    ed_14/convolution_grad/Conv2DBackpropInput:1, DMT/_321)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train1.py", line 117, in <module>
    main()
  File "train1.py", line 114, in main
    load_to_memory=load_to_memory, batch_size=batch_size, nb_epoch=nb_epoch)
  File "train1.py", line 88, in train
    validation_steps=40,workers=4)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 88, in wr                                                                    apper
    return func(*args, **kwargs)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/keras/models.py", line 1097, in fit_generat                                                                    or
    initial_epoch=initial_epoch)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 88, in wr                                                                    apper
    return func(*args, **kwargs)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/keras/engine/training.py", line 1876, in fi                                                                    t_generator
    class_weight=class_weight)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/keras/engine/training.py", line 1620, in tr                                                                    ain_on_batch
    outputs = self.train_function(ins)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line                                                                     2073, in __call__
    feed_dict=feed_dict)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/tensorflow/python/client/session.py", line                                                                     895, in run
    run_metadata_ptr)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/tensorflow/python/client/session.py", line                                                                     1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/tensorflow/python/client/session.py", line                                                                     1344, in _do_run
    options, run_metadata)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/tensorflow/python/client/session.py", line                                                                     1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 10485760 value                                                                    s, but the requested shape has 2621440
         [[Node: gradients/time_distributed_13/Reshape_1_grad/Reshape = _MklReshape[T=DT_FLOAT, Tshape=DT_INT3                                                                    2, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](gradients/time_distributed_14/conv                                                                    olution_grad/Conv2DBackpropInput, gradients/time_distributed_13/Reshape_1_grad/Shape, gradients/time_distribut                                                                    ed_14/convolution_grad/Conv2DBackpropInput:1, DMT/_321)]]

Caused by op 'gradients/time_distributed_13/Reshape_1_grad/Reshape', defined at:
  File "train1.py", line 117, in <module>
    main()
  File "train1.py", line 114, in main
    load_to_memory=load_to_memory, batch_size=batch_size, nb_epoch=nb_epoch)
  File "train1.py", line 88, in train
    validation_steps=40,workers=4)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 88, in wr                                                                    apper
    return func(*args, **kwargs)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/keras/models.py", line 1097, in fit_generat                                                                    or
    initial_epoch=initial_epoch)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 88, in wr                                                                    apper
    return func(*args, **kwargs)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/keras/engine/training.py", line 1774, in fi                                                                    t_generator
    self._make_train_function()
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/keras/engine/training.py", line 1001, in _m                                                                    ake_train_function
    self.total_loss)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/keras/optimizers.py", line 381, in get_upda                                                                    tes
    grads = self.get_gradients(loss, params)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/keras/optimizers.py", line 47, in get_gradi                                                                    ents
    grads = K.gradients(loss, params)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line                                                                     2108, in gradients
    return tf.gradients(loss, variables, colocate_gradients_with_ops=True)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", l                                                                    ine 609, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", l                                                                    ine 375, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", l                                                                    ine 609, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/tensorflow/python/ops/array_grad.py", line                                                                     499, in _ReshapeGrad
    return [array_ops.reshape(grad, array_ops.shape(op.inputs[0])), None]
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", li                                                                    ne 3997, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.                                                                    py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3                                                                    160, in create_op
    op_def=op_def)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1                                                                    625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

...which was originally created as op 'time_distributed_13/Reshape_1', defined at:
  File "train1.py", line 117, in <module>
    main()
[elided 0 identical lines from previous traceback]
  File "train1.py", line 114, in main
    load_to_memory=load_to_memory, batch_size=batch_size, nb_epoch=nb_epoch)
  File "train1.py", line 66, in train
    rm = ResearchModels(len(data.classes), model, seq_length, saved_model)
  File "/home/lhh/TensorFlow/emotion/models.py", line 52, in __init__
    self.model = self.lrcn()
  File "/home/lhh/TensorFlow/emotion/models.py", line 129, in lrcn
    padding='same', activation='relu')))
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/keras/models.py", line 455, in add
    output_tensor = layer(self.outputs[0])
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/keras/engine/topology.py", line 554, in __c                                                                    all__
    output = self.call(inputs, **kwargs)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/keras/layers/wrappers.py", line 139, in cal                                                                    l
    y = K.reshape(y, (-1, input_length) + output_shape[2:])
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line                                                                     1538, in reshape
    return tf.reshape(x, shape)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", li                                                                    ne 3997, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.                                                                    py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3                                                                    160, in create_op
    op_def=op_def)
  File "/home/lhh/anaconda3/envs/video/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1                                                                    625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 10485760 values, but the req                                                                    uested shape has 2621440
         [[Node: gradients/time_distributed_13/Reshape_1_grad/Reshape = _MklReshape[T=DT_FLOAT, Tshape=DT_INT3                                                                    2, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](gradients/time_distributed_14/conv                                                                    olution_grad/Conv2DBackpropInput, gradients/time_distributed_13/Reshape_1_grad/Shape, gradients/time_distribut                                                                    ed_14/convolution_grad/Conv2DBackpropInput:1, DMT/_321)]]

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by yanboliang** [comment]
@13293824182 In your code, the image will be scaled down at layer ```TimeDistributed(MaxPooling2D((2, 2), strides=(2, 2)))```. There are a bunch of such layers, so the image height and width may less than 1 at last. Could you check ```model.summary``` to verify it?
