### ISSUE TITLE
ValueError: Output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: [[[[3.30749512e-01 6.00091577e-01 4.06596988e-01]    [3.30761194e-01 6.00126684e-01 4.06620413e-01]    [3.30772936e-01 6.00161910e-01 4.06643867e-01]    ...

### ISSUE THREAD

**Issue by jetjodh** [keras-team/keras#10704]
I was using image_ocr.py from keras examples. On creating image data generator using flow_from_directory function and I am getting a ValueError. How do I go about resolving this issue?
Stack Trace:
Traceback (most recent call last):
  File "c:/Users/jetjo/Documents/PythonScripts/New folder/IIIT5K/main.py", line 208, in <module>
    train(run_name, 0, 20, 128)
  File "c:/Users/jetjo/Documents/PythonScripts/New folder/IIIT5K/main.py", line 193, in train
    epochs=stop_epoch, callbacks=[keras.callbacks.TensorBoard()], initial_epoch=start_epoch, verbose=1)
  File "C:\Users\jetjo\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\jetjo\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\jetjo\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training_generator.py", line 192, in fit_generator
    str(generator_output))
ValueError: Output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: [[[[3.30749512e-01 6.00091577e-01 4.06596988e-01]
   [3.30761194e-01 6.00126684e-01 4.06620413e-01]
   [3.30772936e-01 6.00161910e-01 4.06643867e-01]
   ...
   [2.47920394e-01 5.39839566e-01 3.47682685e-01]
   [2.47908667e-01 5.39804399e-01 3.47647578e-01]
   [2.47896954e-01 5.39769292e-01 3.47612411e-01]]

  [[3.33333343e-01 6.07843161e-01 4.11764741e-01]
   [3.33333343e-01 6.07843161e-01 4.11764741e-01]
   [3.33333343e-01 6.07843161e-01 4.11764741e-01]
   ...
   [2.47058839e-01 5.37254930e-01 3.45098048e-01]
   [2.47058839e-01 5.37254930e-01 3.45098048e-01]
   [2.47058839e-01 5.37254930e-01 3.45098048e-01]]

  [[3.33333343e-01 6.07843161e-01 4.11764741e-01]
   [3.33333343e-01 6.07843161e-01 4.11764741e-01]
   [3.33333343e-01 6.07843161e-01 4.11764741e-01]
   ...
   [2.47058839e-01 5.37254930e-01 3.45098048e-01]
   [2.47058839e-01 5.37254930e-01 3.45098048e-01]
   [2.47058839e-01 5.37254930e-01 3.45098048e-01]]

  ...

  [[3.13725501e-01 5.68627477e-01 4.03921604e-01]
   [3.13725501e-01 5.68627477e-01 4.03921604e-01]
   [3.13725501e-01 5.68627477e-01 4.03921604e-01]
   ...
   [2.43137270e-01 5.05882382e-01 3.37254912e-01]
   [2.43137270e-01 5.05882382e-01 3.37254912e-01]
   [2.43137270e-01 5.05882382e-01 3.37254912e-01]]

  [[3.13725501e-01 5.68627477e-01 4.03921604e-01]
   [3.13725501e-01 5.68627477e-01 4.03921604e-01]
   [3.13725501e-01 5.68627477e-01 4.03921604e-01]
   ...
   [2.45919645e-01 5.08664727e-01 3.40037286e-01]
   [2.45989949e-01 5.08735061e-01 3.40107590e-01]
   [2.46060237e-01 5.08805394e-01 3.40177864e-01]]

  [[3.13725501e-01 5.72752476e-01 4.05984104e-01]
   [3.13725501e-01 5.72775900e-01 4.05995786e-01]
   [3.13725501e-01 5.72799385e-01 4.06007528e-01]
   ...
   [2.65846193e-01 5.28591275e-01 3.59963834e-01]
   [2.65916497e-01 5.28661609e-01 3.60034138e-01]
   [2.65986770e-01 5.28731883e-01 3.60104412e-01]]]

 [[[0.00000000e+00 5.29411793e-01 8.03921640e-01]
   [0.00000000e+00 5.29411793e-01 8.03921640e-01]
   [0.00000000e+00 5.29411793e-01 8.03921640e-01]
   ...
   [0.00000000e+00 5.33333361e-01 8.07843208e-01]
   [0.00000000e+00 5.33333361e-01 8.07843208e-01]
   [0.00000000e+00 5.33333361e-01 8.07843208e-01]]

  [[0.00000000e+00 5.29411793e-01 8.03921640e-01]
   [0.00000000e+00 5.29411793e-01 8.03921640e-01]
   [0.00000000e+00 5.29411793e-01 8.03921640e-01]
   ...
   [0.00000000e+00 5.33333361e-01 8.07843208e-01]
   [0.00000000e+00 5.33333361e-01 8.07843208e-01]
   [0.00000000e+00 5.33333361e-01 8.07843208e-01]]

  [[0.00000000e+00 5.29411793e-01 8.03921640e-01]
   [0.00000000e+00 5.29411793e-01 8.03921640e-01]
   [0.00000000e+00 5.29411793e-01 8.03921640e-01]
   ...
   [0.00000000e+00 5.33333361e-01 8.07843208e-01]
   [0.00000000e+00 5.33333361e-01 8.07843208e-01]
   [0.00000000e+00 5.33333361e-01 8.07843208e-01]]

  ...

  [[3.92156886e-03 5.33333361e-01 7.92156935e-01]
   [3.92156886e-03 5.33333361e-01 7.92156935e-01]
   [3.92156886e-03 5.33333361e-01 7.92156935e-01]
   ...
   [0.00000000e+00 5.33333361e-01 8.00000072e-01]
   [0.00000000e+00 5.33333361e-01 8.00000072e-01]
   [0.00000000e+00 5.33333361e-01 8.00000072e-01]]

  [[3.92156886e-03 5.33333361e-01 7.92156935e-01]
   [3.92156886e-03 5.33333361e-01 7.92156935e-01]
   [3.92156886e-03 5.33333361e-01 7.92156935e-01]
   ...
   [0.00000000e+00 5.33333361e-01 8.00000072e-01]
   [0.00000000e+00 5.33333361e-01 8.00000072e-01]
   [0.00000000e+00 5.33333361e-01 8.00000072e-01]]

  [[3.92156886e-03 5.33333361e-01 7.92156935e-01]
   [3.92156886e-03 5.33333361e-01 7.92156935e-01]
   [3.92156886e-03 5.33333361e-01 7.92156935e-01]
   ...
   [0.00000000e+00 5.33333361e-01 8.00000072e-01]
   [0.00000000e+00 5.33333361e-01 8.00000072e-01]
   [0.00000000e+00 5.33333361e-01 8.00000072e-01]]]

 [[[0.00000000e+00 1.56862754e-02 1.96078438e-02]
   [0.00000000e+00 1.56862754e-02 1.96078438e-02]
   [0.00000000e+00 1.56862754e-02 1.96078438e-02]
   ...
   [0.00000000e+00 1.56862754e-02 1.56862754e-02]
   [0.00000000e+00 1.56862754e-02 1.56862754e-02]
   [0.00000000e+00 1.56862754e-02 1.56862754e-02]]

  [[0.00000000e+00 1.56862754e-02 1.96078438e-02]
   [0.00000000e+00 1.56862754e-02 1.96078438e-02]
   [0.00000000e+00 1.56862754e-02 1.96078438e-02]
   ...
   [0.00000000e+00 1.56862754e-02 1.56862754e-02]
   [0.00000000e+00 1.56862754e-02 1.56862754e-02]
   [0.00000000e+00 1.56862754e-02 1.56862754e-02]]

  [[0.00000000e+00 1.39540993e-02 1.78756695e-02]
   [0.00000000e+00 1.39302546e-02 1.78518239e-02]
   [0.00000000e+00 1.39064090e-02 1.78279784e-02]
   ...
   [0.00000000e+00 1.56862754e-02 1.56862754e-02]
   [0.00000000e+00 1.56862754e-02 1.56862754e-02]
   [0.00000000e+00 1.56862754e-02 1.56862754e-02]]

  ...

  [[3.92156886e-03 1.96078438e-02 2.35294141e-02]
   [3.92156886e-03 1.96078438e-02 2.35294141e-02]
   [3.92156886e-03 1.96078438e-02 2.35294141e-02]
   ...
   [1.06876693e-03 4.99033602e-03 1.28334733e-02]
   [9.61464015e-04 4.88303276e-03 1.27261700e-02]
   [8.54161044e-04 4.77572996e-03 1.26188677e-02]]

  [[3.92156886e-03 1.96078438e-02 2.35294141e-02]
   [3.92156886e-03 1.96078438e-02 2.35294141e-02]
   [3.92156886e-03 1.96078438e-02 2.35294141e-02]
   ...
   [0.00000000e+00 3.92156886e-03 1.17647070e-02]
   [0.00000000e+00 3.92156886e-03 1.17647070e-02]
   [0.00000000e+00 3.92156886e-03 1.17647070e-02]]

  [[3.92156886e-03 1.96078438e-02 2.35294141e-02]
   [3.92156886e-03 1.96078438e-02 2.35294141e-02]
   [3.92156886e-03 1.96078438e-02 2.35294141e-02]
   ...
   [0.00000000e+00 3.92156886e-03 1.17647070e-02]
   [0.00000000e+00 3.92156886e-03 1.17647070e-02]
   [0.00000000e+00 3.92156886e-03 1.17647070e-02]]]

 ...

 [[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00]
   ...
   [3.52941193e-02 1.17647070e-02 1.96078438e-02]
   [3.52941193e-02 1.17647070e-02 1.96078438e-02]
   [3.52941193e-02 1.17647070e-02 1.96078438e-02]]

  [[0.00000000e+00 0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00]
   ...
   [3.52941193e-02 1.17647070e-02 1.96078438e-02]
   [3.52941193e-02 1.17647070e-02 1.96078438e-02]
   [3.52941193e-02 1.17647070e-02 1.96078438e-02]]

  [[0.00000000e+00 0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00 0.00000000e+00]
   ...
   [3.52941193e-02 1.17647070e-02 1.96078438e-02]
   [3.52941193e-02 1.17647070e-02 1.96078438e-02]
   [3.52941193e-02 1.17647070e-02 1.96078438e-02]]

  ...

  [[3.52941193e-02 3.52941193e-02 3.52941193e-02]
   [3.52941193e-02 3.52941193e-02 3.52941193e-02]
   [3.52941193e-02 3.52941193e-02 3.52941193e-02]
   ...
   [1.96078438e-02 1.96078438e-02 1.96078438e-02]
   [1.96078438e-02 1.96078438e-02 1.96078438e-02]
   [1.96078438e-02 1.96078438e-02 1.96078438e-02]]

  [[3.52941193e-02 3.52941193e-02 3.52941193e-02]
   [3.52941193e-02 3.52941193e-02 3.52941193e-02]
   [3.52941193e-02 3.52941193e-02 3.52941193e-02]
   ...
   [1.96078438e-02 1.96078438e-02 1.96078438e-02]
   [1.96078438e-02 1.96078438e-02 1.96078438e-02]
   [1.96078438e-02 1.96078438e-02 1.96078438e-02]]

  [[3.52941193e-02 3.52941193e-02 3.52941193e-02]
   [3.52941193e-02 3.52941193e-02 3.52941193e-02]
   [3.52941193e-02 3.52941193e-02 3.52941193e-02]
   ...
   [1.96078438e-02 1.96078438e-02 1.96078438e-02]
   [1.96078438e-02 1.96078438e-02 1.96078438e-02]
   [1.96078438e-02 1.96078438e-02 1.96078438e-02]]]

 [[[7.90775001e-01 8.54902029e-01 8.94964218e-01]
   [8.00000072e-01 8.54902029e-01 8.98039281e-01]
   [8.00000072e-01 8.54902029e-01 8.98039281e-01]
   ...
   [8.31372619e-01 8.54902029e-01 9.17647123e-01]
   [8.28391254e-01 8.49684715e-01 9.13175166e-01]
   [8.15686345e-01 8.27451050e-01 8.94117713e-01]]

  [[7.90775001e-01 8.54902029e-01 8.94964218e-01]
   [8.00000072e-01 8.54902029e-01 8.98039281e-01]
   [8.00000072e-01 8.54902029e-01 8.98039281e-01]
   ...
   [8.31372619e-01 8.54902029e-01 9.17647123e-01]
   [8.28391254e-01 8.49684715e-01 9.13175166e-01]
   [8.15686345e-01 8.27451050e-01 8.94117713e-01]]

  [[7.90775001e-01 8.54902029e-01 8.94964218e-01]
   [8.00000072e-01 8.54902029e-01 8.98039281e-01]
   [8.00000072e-01 8.54902029e-01 8.98039281e-01]
   ...
   [8.31372619e-01 8.54902029e-01 9.17647123e-01]
   [8.28391254e-01 8.49684715e-01 9.13175166e-01]
   [8.15686345e-01 8.27451050e-01 8.94117713e-01]]

  ...

  [[7.93538809e-01 8.47594261e-01 8.89038444e-01]
   [7.84313798e-01 8.35294187e-01 8.70588303e-01]
   [7.84313798e-01 8.35294187e-01 8.70588303e-01]
   ...
   [8.19607913e-01 8.43137324e-01 8.90196145e-01]
   [8.21098506e-01 8.44627917e-01 8.91686738e-01]
   [8.27451050e-01 8.50980461e-01 8.98039281e-01]]

  [[7.93538809e-01 8.47594261e-01 8.89038444e-01]
   [7.84313798e-01 8.35294187e-01 8.70588303e-01]
   [7.84313798e-01 8.35294187e-01 8.70588303e-01]
   ...
   [8.19607913e-01 8.43137324e-01 8.90196145e-01]
   [8.21098506e-01 8.44627917e-01 8.91686738e-01]
   [8.27451050e-01 8.50980461e-01 8.98039281e-01]]

  [[7.93538809e-01 8.47594261e-01 8.89038444e-01]
   [7.84313798e-01 8.35294187e-01 8.70588303e-01]
   [7.84313798e-01 8.35294187e-01 8.70588303e-01]
   ...
   [8.19607913e-01 8.43137324e-01 8.90196145e-01]
   [8.21098506e-01 8.44627917e-01 8.91686738e-01]
   [8.27451050e-01 8.50980461e-01 8.98039281e-01]]]

 [[[5.05882382e-01 3.64705890e-01 1.21568635e-01]
   [6.39514863e-01 4.86030161e-01 1.84868246e-01]
   [8.08494091e-01 6.38342500e-01 2.20068440e-01]
   ...
   [7.41176486e-01 5.09803951e-01 0.00000000e+00]
   [7.41176486e-01 5.09803951e-01 0.00000000e+00]
   [7.41176486e-01 5.09803951e-01 0.00000000e+00]]

  [[5.05882382e-01 3.64705890e-01 1.21568635e-01]
   [6.39514863e-01 4.86030161e-01 1.84868246e-01]
   [8.08494091e-01 6.38342500e-01 2.20068440e-01]
   ...
   [7.41176486e-01 5.09803951e-01 0.00000000e+00]
   [7.41176486e-01 5.09803951e-01 0.00000000e+00]
   [7.41176486e-01 5.09803951e-01 0.00000000e+00]]

  [[5.05882382e-01 3.64705890e-01 1.21568635e-01]
   [6.39514863e-01 4.86030161e-01 1.84868246e-01]
   [8.08494091e-01 6.38342500e-01 2.20068440e-01]
   ...
   [7.41176486e-01 5.09803951e-01 0.00000000e+00]
   [7.41176486e-01 5.09803951e-01 0.00000000e+00]
   [7.41176486e-01 5.09803951e-01 0.00000000e+00]]

  ...

  [[8.15686345e-01 5.25490224e-01 5.09803966e-02]
   [8.13927948e-01 5.21973610e-01 4.04304601e-02]
   [8.22433949e-01 5.31364560e-01 3.20234820e-02]
   ...
   [7.33333349e-01 5.01960814e-01 0.00000000e+00]
   [7.33333349e-01 5.01960814e-01 0.00000000e+00]
   [7.33333349e-01 5.01960814e-01 0.00000000e+00]]

  [[8.15686345e-01 5.25490224e-01 5.09803966e-02]
   [8.13927948e-01 5.21973610e-01 4.04304601e-02]
   [8.22433949e-01 5.31364560e-01 3.20234820e-02]
   ...
   [7.33333349e-01 5.01960814e-01 0.00000000e+00]
   [7.33333349e-01 5.01960814e-01 0.00000000e+00]
   [7.33333349e-01 5.01960814e-01 0.00000000e+00]]

  [[8.15686345e-01 5.25490224e-01 5.09803966e-02]
   [8.13927948e-01 5.21973610e-01 4.04304601e-02]
   [8.22433949e-01 5.31364560e-01 3.20234820e-02]
   ...
   [7.33333349e-01 5.01960814e-01 0.00000000e+00]
   [7.33333349e-01 5.01960814e-01 0.00000000e+00]
   [7.33333349e-01 5.01960814e-01 0.00000000e+00]]]]

**Comment by xcelsiorbosi** [comment]
Issue solved here:
https://github.com/llSourcell/How_to_simulate_a_self_driving_car/issues/7

Similar issue here
https://github.com/keras-team/keras/issues/5196

**Comment by JaneLiu0617** [comment]
I have the same issue in R, have you solve it ?

**Comment by xcelsiorbosi** [comment]
If you could supply the code you are using to process the data prior to
handing it to the Keras code that would be helpful in respect to
answering/helping you.

Please supply code and review the following;

It appears that you are using lists instead of tuples. Could you convert
the data into an array (x,y,weights).

https://www.rdocumentation.org/packages/sets/versions/1.0-18/topics/tuple

The python equivalent is <dataframe>[<“column”>].values

In R try using as.tuple(x)
Or
tuple_is_ntuple(x, n)

**Comment by JaneLiu0617** [comment]
Thank you very much, and I will try. The code I used was the Keras
[ cifar10_cnn example](https://keras.rstudio.com/articles/examples/cifar10_cnn.html), I got the error at the last part code, and now I just changed "data_augmentation <- TRUE" into FALSE, and it worked, so I guess there maybe something wrong with augmentation function.

**Comment by xcelsiorbosi** [comment]
Correct, in the following code block you use a list function;


I suspect this converted the array into a list.
Please attempt to use the previously mentioned functions to convert back to
an array.
