### ISSUE TITLE
ValueError when using custom Generator

### ISSUE THREAD

**Issue by KeironO** [keras-team/keras#10758]
Hey there,
I'm having an issue using my own Data Generator in Keras.
I have written the following class:

```
class DataGenerator(Sequence):
    def __init__(self, filepaths, labels, encoded_labels, max_len=250, batch_size=32, shuffle=True, seed=None):
        self.labels = labels
        self.encoded_labels = encoded_labels
        self.filepaths = filepaths
        self.max_len = max_len
        self.batch_size = batch_size
        self.shuffle = shuffle
        self.seed = seed
        self.total_batches_seen = 0
        self.index_array = None

    def __len__(self):
        return int(np.floor(len(self.filepaths)/ self.batch_size))
    

    def _set_index_array(self):
        self.index_array = np.arange(len(self.filepaths))
        if self.shuffle:
            self.index_array = np.random.permutation(self.filepaths)

    def __getitem__(self, index):

        if self.seed is not None:
            np.random.seed(self.seed + self.total_batches_seen)

        self.total_batches_seen += 1

        if self.index_array is None:
            self._set_index_array()
        
        indexes = self.index_array[index*self.batch_size : 
        self.batch_size + (index+1)]

        X, y = self.generate(indexes)

        return X, y

    def on_epoch_end(self):
        self._set_index_array()

    def generate(self, filepaths):
        X = []
        y = []

        for fn in filepaths:
            identifier = os.path.splitext(ntpath.basename(fn))[0]
            labels =  self.labels[identifier]
            el = np.array([self.encoded_labels[i][x] for i, x in enumerate(labels.split(";"))])
            el = el[0]
            with open(fn, "rb") as infile:
                seq = pkl.load(infile)
                for index, gs in enumerate(pad_sequences(np.array(seq.generated_sequences), maxlen=self.max_len)):
                    X.append(gs)
                    y.append(el)
        X = np.array(X)
        y = np.array(y)
        return X, y
```

Which loads in a pre-created pickle object, and then reads its data before feeding back as a standard X, y output.

When I iterate through the generator, and print out the shape of both X and y I see the following:

```
(1062, 250) (1062,)
```

However, when I attempt to fit this on the following neural network:

```
        model = Sequential()
        model.add(Dense(32, input_shape=(250,)))
        model.add(Activation("relu"))
        model.add(Dropout(0.2))
        model.add(Dense(1, activation="softmax"))
        model.compile("sgd", loss="sparse_categorical_crossentropy")
```

I am greeted to the following error:

```
(venv) keiron@Pingu:~/Projects/deep-taxonomic-classifier/src$ python test.py
Using TensorFlow backend.
Epoch 1/1
Traceback (most recent call last):
  File "test.py", line 138, in <module>
    clf.fit(datagen)
  File "/home/keiron/Projects/deep-taxonomic-classifier/src/cnntaxpy/deeplearning.py", line 22, in fit
    clf.fit_generator(datagen)
  File "/home/keiron/Projects/deep-taxonomic-classifier/venv/local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/keiron/Projects/deep-taxonomic-classifier/venv/local/lib/python2.7/site-packages/keras/engine/training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/keiron/Projects/deep-taxonomic-classifier/venv/local/lib/python2.7/site-packages/keras/engine/training_generator.py", line 191, in fit_generator
    class_weight=class_weight)
  File "/home/keiron/Projects/deep-taxonomic-classifier/venv/local/lib/python2.7/site-packages/keras/engine/training.py", line 1214, in train_on_batch
    class_weight=class_weight)
  File "/home/keiron/Projects/deep-taxonomic-classifier/venv/local/lib/python2.7/site-packages/keras/engine/training.py", line 754, in _standardize_user_data
    exception_prefix='input')
  File "/home/keiron/Projects/deep-taxonomic-classifier/venv/local/lib/python2.7/site-packages/keras/engine/training_utils.py", line 136, in standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected dense_1_input to have shape (250,) but got array with shape (1,)
```

Is this because the length of X != to the batch_size, due to the prior generated data being loaded in - or have I messed up the Generator object?

Any help would be gratefully appreciated.

**Comment by lazybonesboy** [comment]
you can try this: 
 X = np.array(X).T
and then shape like this:
(250, 1062 ) (1062,)
