### ISSUE TITLE
ValueError: Dimension 1 in both shapes must be equal,

### ISSUE THREAD

**Issue by senthilv83** [keras-team/keras#10762]
2018-07-24 16:10:56.958738: I C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\35\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 1 in both shapes must be equal, but are 23 and 22 for 'Assign_2' (op: 'Assign') with input shapes: [256,23], [256,22].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Program Files/Anaconda3/Projects/Predict-next-word_Test.py", line 58, in <module>
    model.load_weights(filename)
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\models.py", line 706, in load_weights
    topology.load_weights_from_hdf5_group(f, layers)
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\engine\topology.py", line 2908, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 1992, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 573, in assign
    return state_ops.assign(self._variable, value, use_locking=use_locking)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\state_ops.py", line 276, in assign
    validate_shape=validate_shape)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 56, in assign
    use_locking=use_locking, name=name)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2958, in create_op
    set_shapes_for_outputs(ret)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2209, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2159, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension 1 in both shapes must be equal, but are 23 and 22 for 'Assign_2' (op: 'Assign') with input shapes: [256,23], [256,22].

**Comment by Dref360** [comment]
Hi!
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.

To ask questions, please see the following resources : 
* https://keras.io/
* https://keras.io/#support
* https://gitter.im/Keras-io/Lobby

Thanks!

If you think I made a mistake, please open another issue.
