### ISSUE TITLE
"to_list" not defined in multi_gpu_utils.py line 227

### ISSUE THREAD

**Issue by alex-me** [keras-team/keras#10792]
It appears that in the newly built (Fri 27 Jul 11:16:09 CEST 2018) Keras to_list() in multi_gpu_utils.py is missing its package.

Simple code that reproduces the issue:

```
from keras.models import Sequential
from keras.layers import Dense
from keras import utils
m = Sequential()
m.add( Dense( units=64, input_dim=100 ) )
m = utils.multi_gpu_model( m, gpus=6 )
```

here the error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/src/keras/utils/multi_gpu_utils.py", line 227, in multi_gpu_model
    outputs = to_list(outputs)
NameError: name 'to_list' is not defined
```

**Comment by yanboliang** [comment]
@alex-me Thanks for reporting this, I sent out a fix at #10795 .
