### ISSUE TITLE
Graph disconnected Error for multiple inputs layer

### ISSUE THREAD

**Issue by zgbkdlm** [keras-team/keras#10831]
I defined a very simple custom layer, which just output the sum of its inputs:

```python
import keras
from keras.layers import Input, Dense, Flatten
from keras import Model

class test_layer(keras.layers.Layer):
    def __init__(self, **kwargs):
        super(test_layer, self).__init__(**kwargs)

    def build(self, input_shape):
        super(test_layer, self).build(input_shape)

    def compute_output_shape(self, input_shape):
        return input_shape[2]

    def call(self, x, **kwargs):
        return x[0]+x[1]+x[2]

A = Input(shape=(100,100))
B = Input(shape=(100,100))
C = Input(shape=(100,100))

y = test_layer()([A, B, C])

model = Model(A,y)
```

The error occured, when I try to `Model` its one input to its output.

```
Traceback (most recent call last):
  File "/home/***/***/***/***.py", line 20, in <module>
    model = Model(A,y)
  File "/home/***/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/***/anaconda3/lib/python3.6/site-packages/keras/engine/network.py", line 91, in __init__
    self._init_graph_network(*args, **kwargs)
  File "/home/***/anaconda3/lib/python3.6/site-packages/keras/engine/network.py", line 235, in _init_graph_network
    self.inputs, self.outputs)
  File "/home/***/anaconda3/lib/python3.6/site-packages/keras/engine/network.py", line 1489, in _map_graph_network
    str(layers_with_complete_input))
ValueError: Graph disconnected: cannot obtain value for tensor Tensor("input_2:0", shape=(?, 100, 100), dtype=float32) at layer "input_2". The following previous layers were accessed without issue: ['input_1']
```

**Comment by Monocero** [comment]
I'm facing the same problem. Any hint?

**Comment by zhji2822** [comment]
@Monocero  Would you mind be more specific?  Thank you

**Comment by jingong** [comment]
Have you solve this problem?

**Comment by Monocero** [comment]
@zhji2822 The output y of Model depends from [A,B,C] while only A is given as input. Try substituting A with this list.
