### ISSUE TITLE
StopIteration: Unsupported BMP compression (1)

### ISSUE THREAD

**Issue by yiiplugins** [keras-team/keras#10848]
While training dataset with keras i am facing following error

`StopIteration: Unsupported BMP compression (1)`

I checked all my images, i don't have any corrupt or bmp image, all images are eithe jpg/jpeg.

```
print(keras.__version__)
2.2.2
```

```
Epoch 1/1
17/18 [===========================>..] - ETA: 0s - loss: 1.2433 - acc: 0.5616 Traceback (most recent call last):

  File "<ipython-input-3-45790852014e>", line 1, in <module>
    classifier.fit_generator(trainingData, samples_per_epoch=600, nb_epoch=1, validation_data=testingData, nb_val_samples=133)

  File "C:\Users\dell\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\dell\Anaconda3\lib\site-packages\keras\engine\training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)

  File "C:\Users\dell\Anaconda3\lib\site-packages\keras\engine\training_generator.py", line 230, in fit_generator
    workers=0)

  File "C:\Users\dell\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\dell\Anaconda3\lib\site-packages\keras\engine\training.py", line 1469, in evaluate_generator
    verbose=verbose)

  File "C:\Users\dell\Anaconda3\lib\site-packages\keras\engine\training_generator.py", line 327, in evaluate_generator
    generator_output = next(output_generator)

  File "C:\Users\dell\Anaconda3\lib\site-packages\keras\utils\data_utils.py", line 584, in get
    six.raise_from(StopIteration(e), e)

  File "<string>", line 3, in raise_from

StopIteration: Unsupported BMP compression (1)

```

**Comment by yiiplugins** [comment]
This issue resolved, when i verified all the training images using PIL image processing lib in separate python script, actually there was one corrupt picture in validation data which caused this issue.
now training working perfectly.
Thanks.
