### ISSUE TITLE
"UnboundLocalError: local variable 'x' referenced before assignment" while using load_model

### ISSUE THREAD

**Issue by srihari-humbarwadi** [keras-team/keras#10882]
```
import os
import sys
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow as tf
import keras
from keras import backend as K

config = tf.ConfigProto( device_count = {'GPU': 1 , 'CPU': 12} ) 
sess = tf.Session(config=config) 
K.set_session(sess)

attributes = ['a1', 'a2', 'a3', 'a4', 'a5']


img_height, img_width = 224, 224
_in = keras.layers.Input(shape=(img_height, img_width, 3), name='img_input')

outputs = []

for attribute in attributes:
    model = keras.models.load_model(f'models/{attribute}/xception/model.h5')
    model.name = attribute
    for layer in model.layers:
        layer.name = attribute+layer.name
    model.layers.pop(0)
    model = model(_in)
    model = keras.models.Model(_in, model)
    outputs.append(model.output)
    print('processed', attribute)
    

_out = keras.layers.concatenate(outputs)
hybrid_model = keras.models.Model(_in, _out)
hybrid_model.name = 'hybrid'
keras.utils.vis_utils.plot_model(hybrid_model, 'hybrid.png')

hybrid_model.save('hybrid.h5')

print(hybrid_model.output)
x = keras.models.load_model('hybrid.h5')

```
this is my code

package versions : 

- Keras==2.2.0
- Keras-Applications==1.0.2
- Keras-Preprocessing==1.0.1
- tensorflow-gpu==1.9.0

**Comment by srihari-humbarwadi** [comment]
error log
'''
Traceback (most recent call last):
  File "concat.py", line 58, in <module>
    x = keras.models.load_model('hybrid.h5')
  File "/home/jediyoda/.virtualenvs/py36/lib/python3.6/site-packages/keras/engine/saving.py", line 261, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/jediyoda/.virtualenvs/py36/lib/python3.6/site-packages/keras/engine/saving.py", line 335, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/jediyoda/.virtualenvs/py36/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/jediyoda/.virtualenvs/py36/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/jediyoda/.virtualenvs/py36/lib/python3.6/site-packages/keras/engine/network.py", line 1036, in from_config
    process_layer(layer_data)
  File "/home/jediyoda/.virtualenvs/py36/lib/python3.6/site-packages/keras/engine/network.py", line 1022, in process_layer
    custom_objects=custom_objects)
  File "/home/jediyoda/.virtualenvs/py36/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/jediyoda/.virtualenvs/py36/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/jediyoda/.virtualenvs/py36/lib/python3.6/site-packages/keras/engine/network.py", line 1063, in from_config
    return cls(inputs=input_tensors, outputs=output_tensors, name=name)
  File "/home/jediyoda/.virtualenvs/py36/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/jediyoda/.virtualenvs/py36/lib/python3.6/site-packages/keras/engine/network.py", line 91, in __init__
    self._init_graph_network(*args, **kwargs)
  File "/home/jediyoda/.virtualenvs/py36/lib/python3.6/site-packages/keras/engine/network.py", line 165, in _init_graph_network
    layer, node_index, tensor_index = x._keras_history
UnboundLocalError: local variable 'x' referenced before assignment
'''

**Comment by srihari-humbarwadi** [comment]
update - 
same error when using 
```Model.from_config()``` 
and 
```model_from_json()```

**Comment by jadevaibhav** [comment]
you have a list outputs after going over all attributes. I don't understand the need for concatenation after that. Also, pop() method of keras is buggy, do:
```
# ... Load pre-trained VGG16 model

model.layers.pop() # Get rid of the classification layer
model.layers.pop() # Get rid of the dropout layer
model.outputs = [model.layers[-1].output]
model.layers[-1].outbound_nodes = []
```
I am also little uncomfortable the way you have defined things here,
```
model = model(_in)
model = keras.models.Model(_in, model)
outputs.append(model.output)
print('processed', attribute)
```
use  different variables for different use, although I don't see the error in this.

**Comment by srihari-humbarwadi** [comment]
Yea i agree i could define things in a better way. 
And about the concatenation having a single output tensor is easier to export for tensorflow serving. I could jus slice the result and get the respective predictions for each attribute

**Comment by jpduarte** [comment]
any update on this? I face similar issue when trying to merge clone of the same model into a single bigger model. it works but after saving and loading it I see the same error
