### ISSUE TITLE
Using Lambda Layer Causes AttributeError

### ISSUE THREAD

**Issue by min050820** [keras-team/keras#10933]
When making a Lambda layer using keras backend functions, it throws AttributeError.

Below is my code:
```
RGB_IMAGE_SHAPE = (224, 224, 3)


def build_lambda_layer():
    import keras.backend as K
    from keras.layers import Lambda

    def f(rgb):
        rgb -= K.mean(rgb, axis=1, keepdims=True)

    def out_shape(in_shape):
        return in_shape

    return Lambda(f, output_shape=out_shape)

if __name__ == '__main__':
    from keras import Model
    from keras.layers import Input

    l = build_lambda_layer()

    rgb = Input(RGB_IMAGE_SHAPE)

    processed = l(rgb)

    m = Model(rgb, processed)
    print(m.summary())
```

And here is the stacktrace:
```
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    processed = l(rgb)
  File "/usr/lib/python3.7/site-packages/keras/engine/base_layer.py", line 497, in __call__
    arguments=user_kwargs)
  File "/usr/lib/python3.7/site-packages/keras/engine/base_layer.py", line 565, in _add_inbound_node
    output_tensors[i]._keras_shape = output_shapes[i]
AttributeError: 'NoneType' object has no attribute '_keras_shape'
```

- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [X] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
**(Not using Theano)**

- [X] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by min050820** [comment]
Sorry! I just noticed that I didn't return the tensor!
I'm closing the issue.
