### ISSUE TITLE
Scalar input mulitplication

### ISSUE THREAD

**Issue by abdelrahmanmohamed** [keras-team/keras#11113]
I want to do scalar multiplication using inputs 
Input1 is number, input 2 is 2d numpy array example 
the code below works fine but when i predict but when i use the idea in model training it fails
```
image= np.vstack(np.expand_dims(np.expand_dims(np.expand_dims(np.array([[1, 2], [1, 2]]), axis=0), axis=3), axis=0))
int_list= np.vstack(np.array([2]))

int_input= Input(shape=(1,), name='int_input')
image_Input = Input(shape=(2, 2, 1), name='image')

scalar_multiply_layer = Lambda(lambda x: x * depthInput)(imageInput)
model = Model(inputs=[image_Input, int_input], outputs=scalar_multiply_layer )
model.summary()
print(model.predict({'image': testArr, 'depth': mul}))
```
Error:
```
Traceback (most recent call last):
  File "C:\Users\abdo_\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-7552ea5fffcc>", line 1, in <module>
    runfile('C:/Users/abdo_/PycharmProjects/TGSChallenge/train.py', wdir='C:/Users/abdo_/PycharmProjects/TGSChallenge')
  File "C:\Program Files\JetBrains\PyCharm 2018.2.2\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2018.2.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/abdo_/PycharmProjects/TGSChallenge/train.py", line 93, in <module>
    epochs=epochs, batch_size=20, verbose=0,callbacks=[checkpointer])
  File "C:\Users\abdo_\Anaconda3\lib\site-packages\keras\engine\training.py", line 1037, in fit
    validation_steps=validation_steps)
  File "C:\Users\abdo_\Anaconda3\lib\site-packages\keras\engine\training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "C:\Users\abdo_\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2666, in __call__
    return self._call(inputs)
  File "C:\Users\abdo_\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2636, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\abdo_\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1382, in __call__
    run_metadata_ptr)
  File "C:\Users\abdo_\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [20,100,100,1] vs. [20,1]
	 [[Node: lambda_1/mul = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_image_0_0/_61, _arg_depth_0_1/_63)]]
	 [[Node: metrics/acc/Mean_1/_105 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1165_metrics/acc/Mean_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

**Comment by gabrieldemarmiesse** [comment]
Hello! Can you try to use a list in model.predict instead of a dictionary? Please report if it works. Thank you.

**Comment by abdelrahmanmohamed** [comment]
had to reshape the input integer into 3d array
