### ISSUE TITLE
Issue with CNTK in "neural_style_transfer.py" example

### ISSUE THREAD

**Issue by Macuyiko** [keras-team/keras#11215]
I'm trying to run the "examples/neural_style_transfer.py" script using CNTK. This results in the following error when trying to load in the model with the concatenated input tensor:

ValueError: Convolution operation requires that kernel dim 64 <= input dim 3.

```
About to throw exception 'Convolution operation requires that kernel dim 64 <= input dim 3.'
Traceback (most recent call last):
  File "neural_style_transfer.py", line 143, in <module>
    weights='imagenet', include_top=False)
  File "C:\Users\Seppe\Anaconda3\lib\site-packages\keras_applications\vgg19.py", line 116, in VGG19
    name='block1_conv1')(img_input)
  File "C:\Users\Seppe\Anaconda3\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\Seppe\Anaconda3\lib\site-packages\keras\layers\convolutional.py", line 168, in call
    dilation_rate=self.dilation_rate)
  File "C:\Users\Seppe\Anaconda3\lib\site-packages\keras\backend\cntk_backend.py", line 1526, in conv2d
    padding])
  File "C:\Users\Seppe\Anaconda3\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "C:\Users\Seppe\Anaconda3\lib\site-packages\cntk\ops\__init__.py", line 356, in convolution
    reduction_rank, groups, max_temp_mem_size_in_samples, sequential, name)
ValueError: Convolution operation requires that kernel dim 64 <= input dim 3.

[CALL STACK]
    > std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::  shared_from_this
    - std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::  shared_from_this
    - CNTK::NDMask::  MaskedCount (x2)
    - CNTK::Function::  ~Function
    - CNTK_ReleaseModel
    - RtlRunOnceExecuteOnce
    - InitOnceExecuteOnce
    - _crtInitOnceExecuteOnce
    - CNTK::Function::  InitOutputs
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - CNTK::Function::  ~Function
    - CNTK_ReleaseModel
    - RtlRunOnceExecuteOnce
    - InitOnceExecuteOnce
    - _crtInitOnceExecuteOnce
```

I'm using the latest Keras and CNTK (GPU) versions.

**Comment by tedyu** [comment]
With cntk-2.5.1 , I took a look at /opt/conda/lib/python3.6/site-packages/cntk/ops/__init__.py where I didn't find the check.

Can you tell us which cntk version you used ?

Thanks

**Comment by Macuyiko** [comment]
I'm using the latest version provided by pip, 2.6.

My init.py lists for that line:

```
@typemap
def convolution(convolution_map, operand, strides=(1,), sharing=[True],
                auto_padding=[True], sequential=False, dilation=(1,), reduction_rank=1, groups=1, max_temp_mem_size_in_samples=0, name=''):
    from cntk.cntk_py import convolution
    operand = sanitize_input(operand)
    strides, sharing, auto_padding = sanitize_convolution_args(strides, sharing, auto_padding)
    dilation = sanitize_shape(dilation)
    return convolution(convolution_map, operand, strides, sharing, auto_padding, dilation,
                       reduction_rank, groups, max_temp_mem_size_in_samples, sequential, name)
```
