### ISSUE TITLE
Exception when saving the model using latest master branch

### ISSUE THREAD

**Issue by thorstenwagner** [keras-team/keras#11269]
I just tried the latest master branch and get the following exception when the model is saved at the end of the epoch:

```
Epoch 00001: val_loss improved from inf to 0.12681, saving model to yolo_particle_latest_keras.h5
Traceback (most recent call last):
  File "/home/twagner/applications/miniconda/v3.6.5/envs/cryolo/bin/cryolo_train.py", line 11, in <module>
    sys.exit(_main_())
  File "/home/twagner/applications/miniconda/v3.6.5/envs/cryolo/lib/python2.7/site-packages/cryolo/train.py", line 288, in _main_
    overlap_patches=overlap_patches)
  File "/home/twagner/applications/miniconda/v3.6.5/envs/cryolo/lib/python2.7/site-packages/cryolo/frontend.py", line 570, in train
    use_multiprocessing=True)
  File "/home/twagner/applications/miniconda/v3.6.5/envs/cryolo/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/twagner/applications/miniconda/v3.6.5/envs/cryolo/lib/python2.7/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/twagner/applications/miniconda/v3.6.5/envs/cryolo/lib/python2.7/site-packages/keras/engine/training_generator.py", line 250, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/twagner/applications/miniconda/v3.6.5/envs/cryolo/lib/python2.7/site-packages/keras/callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/twagner/applications/miniconda/v3.6.5/envs/cryolo/lib/python2.7/site-packages/keras/callbacks.py", line 446, in on_epoch_end
    self.model.save(filepath, overwrite=True)
  File "/home/twagner/applications/miniconda/v3.6.5/envs/cryolo/lib/python2.7/site-packages/keras/engine/network.py", line 1090, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/home/twagner/applications/miniconda/v3.6.5/envs/cryolo/lib/python2.7/site-packages/keras/engine/saving.py", line 379, in save_model
    f = h5dict(filepath, mode='w')
  File "/home/twagner/applications/miniconda/v3.6.5/envs/cryolo/lib/python2.7/site-packages/keras/utils/io_utils.py", line 195, in __init__
    'Received: {}.'.format(type(path)))
TypeError: Required Group, str or dict. Received: <type 'unicode'>.
```

**Comment by gabrieldemarmiesse** [comment]
Hi,
We could work on this better if you could provide a standalone reproducible example.
Some advices:
* Don't use custom data or custom paths.
* Use random arrays or even np.ones, np.zeros.
* The example should run with Keras (and deps) alone.
* Should be Python3 compatible.
* Should not be OS specific.
* The file should reproduce the bug with **high* fidelity.
* Link to a gist would be appreciated.
* There is usually no need to make a big neural network to trigger bugs

Thanks!

**Comment by lossyrob** [comment]
I'm seeing similar behavior, keras `2.2.2` -> `2.2.3`, my callback which saves the model is causing the following error after the completion of the second epoch:

```
Details: Traceback (most recent call last):
  File "/opt/src/integration_tests/integration_tests.py", line 136, in run_test
    .run(experiment, rerun_commands=True)
  File "/opt/src/rastervision/runner/experiment_runner.py", line 178, in run
    self._run_experiment(command_dag)
  File "/opt/src/rastervision/runner/local_experiment_runner.py", line 29, in _run_experiment
    run_commands(self.tmp_dir)
  File "/opt/src/rastervision/runner/local_experiment_runner.py", line 26, in run_commands
    command.run(tmp_dir)
  File "/opt/src/rastervision/command/train_command.py", line 14, in run
    self.task.train(tmp_dir)
  File "/opt/src/rastervision/task/task.py", line 138, in train
    self.backend.train(tmp_dir)
  File "/opt/src/rastervision/backend/keras_classification/backend.py", line 239, in train
    _train(backend_config_path, pretrained_model_path, do_monitoring)
  File "/opt/src/rastervision/backend/keras_classification/commands/train.py", line 15, in _train
    trainer.train(do_monitoring)
  File "/opt/src/rastervision/backend/keras_classification/core/trainer.py", line 148, in train
    callbacks=callbacks)
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training_generator.py", line 250, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python3.5/dist-packages/keras/callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/lib/python3.5/dist-packages/keras/callbacks.py", line 457, in on_epoch_end
    self.model.save(filepath, overwrite=True)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/network.py", line 1090, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/saving.py", line 382, in save_model
    _serialize_model(model, f, include_optimizer)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/saving.py", line 78, in _serialize_model
    f['keras_version'] = str(keras_version).encode('utf8')
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/io_utils.py", line 214, in __setitem__
    'Group with name "{}" exists.'.format(attr))
KeyError: 'Cannot set attribute. Group with name "keras_version" exists.'
```

Seeing this reported elsewhere as well (https://github.com/qqwweee/keras-yolo3/issues/239)

Downgrading to 2.2.2 is a workaround for me.

**Comment by gabrieldemarmiesse** [comment]
@lossyrob could you provide a script to reproduce? It's difficult to debug otherwise.

**Comment by gabrieldemarmiesse** [comment]
#11276 is more detailed, we'll track this bug on this issue.

**Comment by EggyDream** [comment]
I am also meet this problem. 
It happen every time when I try to overwrite HDF5 data with model.save().
Currently I have no idea to deal with it.

**Comment by melamran** [comment]
I having the same problem on model.load

  File "/mnt/anaconda/lib/python2.7/site-packages/keras/engine/saving.py", line 417, in load_model
    f = h5dict(filepath, 'r')
  File "/mnt/anaconda/lib/python2.7/site-packages/keras/utils/io_utils.py", line 197, in __init__
    'Received: {}.'.format(type(path)))
TypeError: Required Group, str or dict. Received: <type 'unicode'>.

**Comment by vovo1234** [comment]
Seems like ```save_model``` and ```load_model``` method in ```keras/engine/saving.py``` now expect filepath to be a str instance, not unicode.

For  ```load_model```  a workaround would be to explicitly convert filepath:
```keras.models.load_model(str(my_model_path))```
