### ISSUE TITLE
Python sometimes does not exit when using multiprocessing=True in fit_generator

### ISSUE THREAD

**Issue by thorstenwagner** [keras-team/keras#11288]
Hi, 

I've implemented my own generator as sequence object. If I'm using it without multi processing, it works fine. Most of the times it also does the job when using multiprocessing=True (fit_generator).

However,  SOMETIMES (unfortunately not reproducible) when using multiprocessing=True, the program does not exit after the training finished. It reaches the last line (print out the time needed for training) but then does not exit. I've to kill it with ctrl + c. Most of the times, some processes are still running and tensorflow still occupies my GPU memory. I've to kill the processes then manually by kill -s 9 id .

I think it might be a problem with my generator:
https://gist.github.com/thorstenwagner/8033f43b99d1d3a1a6a31b054d91e7fc

However, I cannot nail it down to a specific line. I did my best to make it multi threading save.

I observed this problem with Keras 2.2.0, 2.2.2 and 2.2.3. I've tested tensorflow-gpu 1.8.0 and tensorflow-gpu 1.10.1 as backend. I had this problem with python 2 and with python 3.6.

Any ideas what might be problem?

Best,
Thorsten

**Comment by gabrieldemarmiesse** [comment]
We have a flaky multiprocessing test with a sequence. It might be related to what you are talking about.

**Comment by gabrieldemarmiesse** [comment]
I'll see if I can find the unit test and also the failing build.

**Comment by gabrieldemarmiesse** [comment]
https://travis-ci.org/keras-team/keras/jobs/424773817

This is one of (too many) flaky test that we have. After seeing it, it seems that the test isn't using multiprocessing. So it might be unrelated to your issue. 

Do you also have this issue with multithreading and multiple workers?

**Comment by thorstenwagner** [comment]
I just use the fit_generator method and set number of workers to the number of cores and set multiprocessing to true. How can I use multi threading instead of multiple processes?

**Comment by gabrieldemarmiesse** [comment]
If you use a number of workers superior to 1 and use multiprocessing=False, it uses multithreading (from what I remember from the code).

**Comment by thorstenwagner** [comment]
I've now activated it and so far I could not observe hanging. However, I loose a lot of performance ( 0.580ms per step instead of 0.380 ms per step).

**Comment by gabrieldemarmiesse** [comment]
Useful information to have. Multithreading is generally slower for this kind of workflow (because of the GIL if you want to dig into that). Thanks for trying. Since it's not easily reproducible, and we dont know where the issue occurs, I don't think we can do anything anytime soon. I'll keep the issue open in case we stumble upon something similar. Thanks for the report and trying multithreading.

**Comment by thorstenwagner** [comment]
@gabrieldemarmiesse 
If I ctrl+c the process I get following exception:
```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/twagner/Applications/miniconda3/envs/cryolo_python36/lib/python3.6/multiprocessing/util.py", line 262, in _run_finalizers
    finalizer()
  File "/home/twagner/Applications/miniconda3/envs/cryolo_python36/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/twagner/Applications/miniconda3/envs/cryolo_python36/lib/python3.6/multiprocessing/pool.py", line 593, in _terminate_pool
    task_handler.join()
  File "/home/twagner/Applications/miniconda3/envs/cryolo_python36/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/home/twagner/Applications/miniconda3/envs/cryolo_python36/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

```
Might the problem be connected to this issue?
https://bugs.python.org/issue29309

As keras is also using sleep here:
https://github.com/keras-team/keras/blob/f2b261bc2555773bd88cbbeda976f98e244d02c1/keras/utils/data_utils.py#L553

**Comment by dobos** [comment]
I'm getting this error intermittently when using multithreading for data generation:

(function calls to own code omitted from backtrace)

```
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/astro/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/miniconda3/envs/astro/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
...
  File "/usr/local/miniconda3/envs/astro/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/miniconda3/envs/astro/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/miniconda3/envs/astro/lib/python3.6/site-packages/keras/engine/training_generator.py", line 262, in fit_generator
    val_enqueuer.stop()
  File "/usr/local/miniconda3/envs/astro/lib/python3.6/site-packages/keras/utils/data_utils.py", line 496, in stop
    self.run_thread.join(timeout)
  File "/usr/local/miniconda3/envs/astro/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/local/miniconda3/envs/astro/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```
