### ISSUE TITLE
python3.7 and keras2.2.3 problem

### ISSUE THREAD

**Issue by fayeshine** [keras-team/keras#11300]
python3.7 and keras2.2.3 problem, this problem does not show up in keras2.2.2

```
Traceback (most recent call last):
 File "/home/wenjian/stock/src/lib.py", line 428, in guard
   yield
 File "/home/wenjian/stock/src/predict.py", line 64, in predict_single
   model, arg, scaler = get_model(version)
 File "/home/wenjian/stock/src/feature.py", line 1549, in get_model
   model = load_model(m_path)
 File "/home/wenjian/anaconda3/lib/python3.7/site-packages/keras/engine/saving.py", line 419, in load_model
   model = _deserialize_model(f, custom_objects, compile)
 File "/home/wenjian/anaconda3/lib/python3.7/site-packages/keras/engine/saving.py", line 225, in _deserialize_model
   model = model_from_config(model_config, custom_objects=custom_objects)
 File "/home/wenjian/anaconda3/lib/python3.7/site-packages/keras/engine/saving.py", line 458, in model_from_config
   return deserialize(config, custom_objects=custom_objects)
 File "/home/wenjian/anaconda3/lib/python3.7/site-packages/keras/layers/__init__.py", line 55, in deserialize
   printable_module_name='layer')
 File "/home/wenjian/anaconda3/lib/python3.7/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
   list(custom_objects.items())))
 File "/home/wenjian/anaconda3/lib/python3.7/site-packages/keras/engine/sequential.py", line 294, in from_config
   model = cls(name=name)
UnboundLocalError: local variable 'name' referenced before assignment
```

**Comment by gabrieldemarmiesse** [comment]
Can you please upgrade to keras 2.2.4 and tell us if the issue is still there?

**Comment by fayeshine** [comment]
@gabrieldemarmiesse no error this time
