### ISSUE TITLE
Unable to train with RGBA images; RGB work fine

### ISSUE THREAD

**Issue by Benz-Tracxpoint** [keras-team/keras#11309]
I have training data that are RGBA images stored as png files. When I read them in as RGB images using flow_from_directory everything runs smoothly.

But if I set the 'color_mode' argument of flow_from_directory to 'rgba', as in he documentation, I get the following error when trying to run fit_generator:

```
Epoch 1/120
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/keras/utils/data_utils.py", line 578, in get
    inputs = self.queue.get(block=True).get()
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.6/site-packages/keras/utils/data_utils.py", line 401, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "/usr/local/lib/python3.6/site-packages/keras_preprocessing/image.py", line 1296, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)
  File "/usr/local/lib/python3.6/site-packages/keras_preprocessing/image.py", line 1781, in _get_batches_of_transformed_samples
    batch_x[i] = x
ValueError: could not broadcast input array from shape (296,296,3) into shape (296,296,4)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "training_keras.py", line 326, in <module>
    train_model(MODEL_NAME,BASE_DIR,OUTPUT_DIR,GPUS,NUM_EPOCHS,BATCH_SIZE,WIDTH,HEIGHT,MODEL_TYPE,WORKERS,DATA_FRACTION,TRAIN_ALL,FIRST_LAYER,FCN_SIZE,VALIDATION_DIR)
  File "training_keras.py", line 314, in train_model
    model.fit_generator( train_generator,steps_per_epoch=(train_generator.n/(BATCH_SIZE)/DATA_FRACTION),epochs=NUM_EPOCHS,callbacks=cbks,workers=WORKERS, validation_data=validate_generator)
  File "/usr/local/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/training_generator.py", line 177, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python3.6/site-packages/keras/utils/data_utils.py", line 584, in get
    six.raise_from(StopIteration(e), e)
  File "<string>", line 3, in raise_from
StopIteration: could not broadcast input array from shape (296,296,3) into shape (296,296,4)
```
Why does this happen? 

Thanks!

**Comment by gabrieldemarmiesse** [comment]
You should open the same issue in  https://github.com/keras-team/keras-preprocessing . Thanks.
