### ISSUE TITLE
tf.Graph, multiple Keras model and model.get_weights() Error.

### ISSUE THREAD

**Issue by XMaster96** [keras-team/keras#11312]
I try to use multiple keras models simultaneously. After my understanding Keras uses at default, a global TF Graph, and if you want to run multiple models, you have to create for each a separate graph. Using with `self.Graph.as_default():` it works fine with one model, but if I create a second one, I get an error.
`self.model.predict()`, works fine on both, but if I run `self.model.get_weights()`  I get the error.

Code:
```python
class network():
       
	def __init__(self, input_len, output_len, data_len):

		self.Graph = tf.Graph()

		with self.Graph.as_default():
			self.model = Sequential()
			self.model.add(Dense(1024, batch_input_shape=(data_len, input_len)))
			self.model.add(Dense(output_len, activation='relu'))
			self.model.compile(optimizer=Adam(), loss='categorical_crossentropy')

			print(self.model.predict(np.zeros(shape=(data_len, input_len)))[-1])
			print(self.model.get_weights())

network_1 = network(5, 1, 50) # works fine.
network_2 = network(5, 1, 50) # Returns a Error.

```
 
 

Error:
```python
Traceback (most recent call last):
  File "/home/Documents/REP/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 282, in __init__
    fetch, allow_tensor=True, allow_operation=True))
  File "/home/Documents/REP/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3613, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/Documents/REP/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3692, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("dense/kernel/Read/ReadVariableOp:0", shape=(5, 1024), dtype=float32) is not an element of this graph.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Documents/REP/test.py", line 55, in <module>
    network_2 = network(5, 1, 50) # Returns a Error.
  File "/home/Documents/REP/test.py", line 52, in __init__
    print(self.model.get_weights())
  File "/home/Documents/REP/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 458, in get_weights
    return backend.batch_get_value(weights)
  File "/home/Documents/REP/venv/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 2657, in batch_get_value
    return get_session().run(tensors)
  File "/home/Documents/REP/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/Documents/REP/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
  File "/home/Documents/REP/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 427, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/home/Documents/REP/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 245, in for_fetch
    return _ListFetchMapper(fetch)
  File "/home/Documents/REP/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 352, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/home/Documents/REP/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 352, in <listcomp>
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/home/Documents/REP/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 253, in for_fetch
[0.]
    return _ElementFetchMapper(fetches, contraction_fn)
  File "/home/Documents/REP/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 289, in __init__
    'Tensor. (%s)' % (fetch, str(e)))
ValueError: Fetch argument <tf.Variable 'dense/kernel:0' shape=(5, 1024) dtype=float32> cannot be interpreted as a Tensor. (Tensor Tensor("dense/kernel/Read/ReadVariableOp:0", shape=(5, 1024), dtype=float32) is not an element of this graph.)
```

**Comment by gabrieldemarmiesse** [comment]
You don't need tf.Graph to use multiple models in the same session in keras. Just define multiple models normally and it will work.

**Comment by XMaster96** [comment]
Thank you, you are right, I believe that I had to create separate graphs because I read something like that in previous issues and on stackoverflow.
