### ISSUE TITLE
Error with using Aplication as layer

### ISSUE THREAD

**Issue by MichaelMonashev** [keras-team/keras#11329]
After upgrading Keras and Tensorflow to last version I get this error:
```
Traceback (most recent call last):
  File "train_classes_v4.py", line 643, in <module>
    _main(parser.parse_args())
  File "train_classes_v4.py", line 467, in _main
    model.add(base_model)
  File "/home/xxx/.local/lib/python3.5/site-packages/keras/engine/sequential.py", line 131, in add
    'Found: ' + str(layer))
TypeError: The added layer must be an instance of class Layer. Found: <tensorflow.python.keras.engine.training.Model object at 0x7fa419d7a5f8>

```
here is code:
```
from keras.applications.resnet50 import ResNet50
IMG_HEIGHT = 224 * 3
IMG_WIDTH = 224
DIMS = (IMG_HEIGHT, IMG_WIDTH, 3)

    base_model = ResNet50(include_top=False, input_shape=DIMS, pooling='avg')
    base_model.trainable = False

    print(base_model.summary())

    model = Sequential()
    model.add(base_model) # line 467
...
```

**Comment by MichaelMonashev** [comment]
keras-applications-1.0.6
keras-2.2.4
tensorflow-gpu-1.11.0

**Comment by Cpruce** [comment]
Same here.

keras: 2.2.2
keras-applications: 1.0.4
