### ISSUE TITLE
keras.models.load_model() met a problem.

### ISSUE THREAD

**Issue by gmt710** [keras-team/keras#11424]
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [ ] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by gmt710** [comment]
keras.models.load_model()

D:\Users\Python\python3.exe D:/pythonwork/Adversarial/Cifar10_keras_Adversarial/MisClassification.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "D:/pythonwork/Adversarial/Cifar10_keras_Adversarial/MisClassification.py", line 100, in <module>
    main()
  File "D:/pythonwork/Adversarial/Cifar10_keras_Adversarial/MisClassification.py", line 21, in main
    kmodel = load_model(weight_path)
  File "D:\Users\Python\lib\site-packages\keras\engine\saving.py", line 261, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "D:\Users\Python\lib\site-packages\keras\engine\saving.py", line 335, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "D:\Users\Python\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "D:\Users\Python\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "D:\Users\Python\lib\site-packages\keras\engine\sequential.py", line 292, in from_config
    custom_objects=custom_objects)
  File "D:\Users\Python\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "D:\Users\Python\lib\site-packages\keras\utils\generic_utils.py", line 165, in deserialize_keras_object
    ':' + function_name)
ValueError: Unknown layer:layers

**Comment by BIGBALLON** [comment]
Solved by update keras version 
check [issue 11](https://github.com/BIGBALLON/cifar-10-cnn/issues/11)
