### ISSUE TITLE
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found

### ISSUE THREAD

**Issue by hasibzunair** [keras-team/keras#11422]
Getting this error when i try to import keras in Python 3.6. Works fine in Python 2.7. Did an installation of the cxxabi file but still the issue remains.

**Comment by hasibzunair** [comment]
Another insight. 
When I run it in my Jupyter Notebook it runs fine. But when I try to run from terminal I am getting this:

`Using TensorFlow backend.
tf.estimator package not installed.
Traceback (most recent call last):
  File "t.py", line 7, in <module>
    from keras.models import Model
  File "/home/hasib/anaconda3/envs/p3.6/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/hasib/anaconda3/envs/p3.6/lib/python3.6/site-packages/keras/utils/__init__.py", line 27, in <module>
    from .multi_gpu_utils import multi_gpu_model
  File "/home/hasib/anaconda3/envs/p3.6/lib/python3.6/site-packages/keras/utils/multi_gpu_utils.py", line 7, in <module>
    from ..layers.merge import concatenate
  File "/home/hasib/anaconda3/envs/p3.6/lib/python3.6/site-packages/keras/layers/__init__.py", line 4, in <module>
    from ..engine.base_layer import Layer
  File "/home/hasib/anaconda3/envs/p3.6/lib/python3.6/site-packages/keras/engine/__init__.py", line 8, in <module>
    from .training import Model
  File "/home/hasib/anaconda3/envs/p3.6/lib/python3.6/site-packages/keras/engine/training.py", line 21, in <module>
    from . import training_arrays
  File "/home/hasib/anaconda3/envs/p3.6/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 8, in <module>
    from scipy.sparse import issparse
  File "/home/hasib/anaconda3/envs/p3.6/lib/python3.6/site-packages/scipy/sparse/__init__.py", line 229, in <module>
    from .csr import *
  File "/home/hasib/anaconda3/envs/p3.6/lib/python3.6/site-packages/scipy/sparse/csr.py", line 15, in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/hasib/anaconda3/envs/p3.6/lib/python3.6/site-packages/scipy/sparse/_sparsetools.cpython-36m-x86_64-linux-gnu.so)` 

Tested with other libs, they work okay.

**Comment by gabrieldemarmiesse** [comment]
This is likely a tensorflow installation issue. Nothing we can do about if that's the case.

**Comment by gabrieldemarmiesse** [comment]
It says tf.estimator not installed. Try to reinstall tensorflow and make sure that you can import tf.estimator.
