### ISSUE TITLE
i got this issue can someone help

### ISSUE THREAD

**Issue by sid404** [keras-team/keras#11482]

**Comment by sid404** [comment]
>> Mode : train

Preparing data in working_dir/
2018-10-25 01:12:31.688963: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Creating 3 layers of 256 units.
WARNING:tensorflow:At least two cells provided to MultiRNNCell are the same object and will share weights.
2018-10-25 01:12:34.268787: W tensorflow/python/util/util.cc:208] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Traceback (most recent call last):
  File "execute.py", line 319, in <module>
    train()
  File "execute.py", line 137, in train
    model = create_model(sess, False)
  File "execute.py", line 104, in create_model
    model = seq2seq_model.Seq2SeqModel( gConfig['enc_vocab_size'], gConfig['dec_vocab_size'], _buckets, gConfig['layer_size'], gConfig['num_layers'], gConfig['max_gradient_norm'], gConfig['batch_size'], gConfig['learning_rate'], gConfig['learning_rate_decay_factor'], forward_only=forward_only)
  File "C:\Users\LENOVO\tensorflow_chatbot-master\seq2seq_model.py", line 158, in __init__
    softmax_loss_function=softmax_loss_function)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\legacy_seq2seq\python\ops\seq2seq.py", line 1215, in model_with_buckets
    decoder_inputs[:bucket[1]])
  File "C:\Users\LENOVO\tensorflow_chatbot-master\seq2seq_model.py", line 157, in <lambda>
    lambda x, y: seq2seq_f(x, y, False),
  File "C:\Users\LENOVO\tensorflow_chatbot-master\seq2seq_model.py", line 121, in seq2seq_f
    feed_previous=do_decode)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\legacy_seq2seq\python\ops\seq2seq.py", line 857, in embedding_attention_seq2seq
    encoder_cell = copy.deepcopy(cell)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\copy.py", line 161, in deepcopy
    y = copier(memo)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\layers\base.py", line 385, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python36\lib\copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.RLock objects

**Comment by harshini-gadige** [comment]
@sid404  - Hi, we understand that your code is running into an error and could you please help us with the following. 
1) Provide a code snippet which helps to reproduce this issue from our end. 
2) Also please give a brief and clear explanation on the issue which help us to triage further. Thanks !

**Comment by harshini-gadige** [comment]
Closing as it is in "awaiting response" for more than a week. Please add comments if any, we will reopen. Thanks !

**Comment by lunasdejavu** [comment]
@harshini-gadige  did you figure out how to solve this problem?
I have the same problem with #11650 .
Can you help me please?
