### ISSUE TITLE
expected activation_49 to have shape (4,) but got array with shape (2,)

### ISSUE THREAD

**Issue by margegaj24** [keras-team/keras#11490]
Using Enhanced Data Generation
Found 3636 images belonging to 2 classes.
Found 1111 images belonging to 2 classes.
JSON Mapping for the model classes saved to  ../../Desktop/challenge/cars/json/model_class.json
Number of experiments (Epochs) :  100
2018-10-25 16:10:44.607419: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Epoch 1/100
Traceback (most recent call last):
  File "model2.py", line 7, in <module>
    model_trainer.trainModel(num_objects=4, num_experiments=100, enhance_data=True, batch_size=32, show_network_summary=True)
  File "/home/mario/.local/lib/python3.6/site-packages/imageai/Prediction/Custom/__init__.py", line 249, in trainModel
    validation_steps=int(num_test / batch_size), callbacks=[checkpoint, lr_scheduler])
  File "/home/mario/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 2065, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/mario/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 171, in fit_generator
    x, y, sample_weight=sample_weight, class_weight=class_weight)
  File "/home/mario/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1816, in train_on_batch
    x, y, sample_weight=sample_weight, class_weight=class_weight)
  File "/home/mario/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 993, in _standardize_user_data
    class_weight, batch_size)
  File "/home/mario/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1149, in _standardize_weights
    exception_prefix='target')
  File "/home/mario/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_utils.py", line 325, in standardize_input_data
    ' but got array with shape ' + str(data_shape))
ValueError: Error when checking target: expected activation_49 to have shape (4,) but got array with shape (2,)

**Comment by margegaj24** [comment]
the problem was in this line of code
`model_trainer.trainModel(num_objects=2, num_experiments=100, enhance_data=True, batch_size=32, show_network_summary=True)`
At first the num_objects param was 4 but when i changed it to 2 (because i was training my model only in two objects not 4) it worked
