### ISSUE TITLE
ValueError with Dense Layer on LSTM Network

### ISSUE THREAD

**Issue by ericbhanson** [keras-team/keras#11527]
On Python 3.6.6, Keras 2.2.4, and TensorFlow 1.11.0 I occasionally get the following ValueError when running a test script that is evaluating different variables in an LSTM network. 

"ValueError: Input 0 is incompatible with layer dense_1: expected axis -1 of input shape to have value x but got shape (y, z)"

X, y, and z are all integers; they've varied depending on the variables I'm testing. The ValueError crashes the testing script; If I restart, it proceeds from where it left off without problem. I haven't seen anything about this error when searching for it, so I thought I'd post here to see if there was a solution. Thank you for your help.

Relevant scripts:

test_harness.py (script running the testing loops): https://gist.github.com/ericbhanson/200deb15519bea99a1e117002ca47697
model.py (script with functions to create the LSTM network): https://gist.github.com/ericbhanson/f8f275f666cb31b3656d8572c35177f5

**Comment by ericbhanson** [comment]
Here's the traceback for the most recent occurrence:

```
Traceback (most recent call last):
  File "/Users/eric/PycharmProjects/Da_Ponz/da_ponz/__main__.py", line 10, in <module>
    test_harness.run_testing(logger, settings)
  File "/Users/eric/PycharmProjects/Da_Ponz/da_ponz/lstm/test_harness.py", line 102, in run_testing
    model = lstm.make_model(activation, batch_size, data, layers, stateful, units)
  File "/Users/eric/PycharmProjects/Da_Ponz/da_ponz/lstm/model.py", line 36, in make_model
    model.add(layer)
  File "/Users/eric/PycharmProjects/Da_Ponz/venv_py3-66/lib/python3.6/site-packages/keras/engine/sequential.py", line 181, in add
    output_tensor = layer(self.outputs[0])
  File "/Users/eric/PycharmProjects/Da_Ponz/venv_py3-66/lib/python3.6/site-packages/keras/engine/base_layer.py", line 440, in __call__
    self.assert_input_compatibility(inputs)
  File "/Users/eric/PycharmProjects/Da_Ponz/venv_py3-66/lib/python3.6/site-packages/keras/engine/base_layer.py", line 352, in assert_input_compatibility
    ' but got shape ' + str(x_shape))
ValueError: Input 0 is incompatible with layer dense_1: expected axis -1 of input shape to have value 2 but got shape (140, 4)
```

**Comment by ericbhanson** [comment]
I appear to have solved this by putting the activation directly on the Dense layer, rather than adding it to the model separately. Closing this for now; I'll reopen if I have additional information.
