### ISSUE TITLE
image_ocr.py running error on tf.keras

### ISSUE THREAD

**Issue by shijie001** [keras-team/keras#11621]
I try to run image_ocr.py on tf.keras.
>>> import tensorflow as tf
>>> tf.__version__
'1.11.0'
>>> tf.keras.__version__
'2.1.6-tf'
>>>

I only modify the imports to use tf.keras.

The problem is occurs in model.fit_generator().
I found next_train() and build_word_list() run in different python thread.

the next_train() is called before the build_word_list(). So the initializeation of TextImageGenerator is incorrect.

Is this example no longer cimpatible keras2 ?

import tensorflow as tf
from tensorflow.keras import backend as K
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.layers import Input, Dense, Activation
from tensorflow.keras.layers import Reshape, Lambda
from tensorflow.keras.layers import add, concatenate
from tensorflow.keras.models import Model
from tensorflow.keras.layers import GRU
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.utils import get_file

call next_train
call build_word_list
Epoch 1/20
Traceback (most recent call last):
  File "image_ocr.py", line 550, in <module>
    train(run_name, 0, 20, 128)
  File "image_ocr.py", line 545, in train
    initial_epoch=start_epoch)
  File "D:\Anaconda2\envs\tf-cpu\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2065, in fit_generator
    initial_epoch=initial_epoch)
  File "D:\Anaconda2\envs\tf-cpu\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 142, in fit_generator
    generator_output = next(output_generator)
  File "D:\Anaconda2\envs\tf-cpu\lib\site-packages\tensorflow\python\keras\utils\data_utils.py", line 824, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "D:\Anaconda2\envs\tf-cpu\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "D:\Anaconda2\envs\tf-cpu\lib\site-packages\tensorflow\python\keras\utils\data_utils.py", line 689, in _data_generator_task
    generator_output = next(self._generator)
  File "image_ocr.py", line 312, in next_train
    print(self.cur_train_index)
AttributeError: 'TextImageGenerator' object has no attribute 'cur_train_index'

**Comment by shijie001** [comment]
I found that the "workers" much be set to 0.
Did the sample code not be tested when the new version was released?

    model.fit_generator(
        generator=img_gen.next_train(),
        steps_per_epoch=(words_per_epoch - val_words) // minibatch_size,
        epochs=stop_epoch,
        validation_data=img_gen.next_val(),
        validation_steps=val_words // minibatch_size,
        callbacks=[viz_cb, img_gen],
        initial_epoch=start_epoch,
        workers=0)

**Comment by gabrieldemarmiesse** [comment]
Please open this issue in the tensorflow repo. tf.keras and keras-team/keras are two different codebases, so bugs might be different.
