### ISSUE TITLE
GPU not used when I use tf.device('/cpu:0')

### ISSUE THREAD

**Issue by kevupton** [keras-team/keras#11637]
When I run the following code,
My GPU is not used at all.

I am using 1 GPU: `GTX 1070` with the CPU, however in my task manager the gpu is not used at all.

```
def model():
        with tf.device('/cpu:0'):
            model = Sequential()
            model.add(TimeDistributed(Conv2D(32, 8, activation='relu'), input_shape=input_shape))
            model.add(TimeDistributed(Conv2D(64, 4, activation='relu')))
            model.add(TimeDistributed(Conv2D(64, 3, activation='relu')))
            model.add(TimeDistributed(Flatten()))

            # Use all traces for training
            model.add(LSTM(512,  activation='tanh'))
            model.add(Dense(action_size, activation='linear'))

        try:
            model = multi_gpu_model(model)
        except ValueError:
            pass

        adam = Adam(lr=learning_rate)
        model.compile(loss=huber_loss, optimizer=adam)
```

If I remove the 
```
        with tf.device('/cpu:0'):
```

Then my GPU gets an OOM error, in the compilation of the second model:
```
model1 = model()
model2 = model()
```

Or later on if I specify 
```
config.gpu_options.per_process_gpu_memory_fraction = 0.8
```

Especially if I was to do:
```
model1.set_weights(model2.get_weights())
```
This one will cause a major memory problem.

My first question is am I setting up the model correctly ?
And is it possible to copy the weights without overflowing my memory ? 

It seems like each model is taking up about 3gig  each.
Their input size is: `(4, 216, 43, 1)`,
Should that input size be creating 3gig models ?

**Comment by kevupton** [comment]
@vickorian Thanks for replying

If I set the following:
```
import tensorflow as tf
import keras.backend as K

    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    config.gpu_options.per_process_gpu_memory_fraction = 0.4
    sess = tf.Session(config=config)
    K.set_session(sess)
```

Then it fails on generating the first model. Why are my models so big ? Am I missing something ?is it the compilation ? 
```
Input Size (4, 216, 43, 1)
generating model 1
2018-11-15 11:13:23.977609: W tensorflow/core/common_runtime/bfc_allocator.cc:271] Allocator (GPU_0_bfc) ran out of memory trying to allocate 4.00MiB.  Current allocation summary follows.
2018-11-15 11:13:23.988322: I tensorflow/core/common_runtime/bfc_allocator.cc:610] Bin (256):   Total Chunks: 14, Chunks in use: 14. 3.5KiB allocated for chunks. 3.5KiB in use in bin. 448B client-requested in use in bin.
2018-11-15 11:13:24.000835: I tensorflow/core/common_runtime/bfc_allocator.cc:610] Bin (512):   Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-11-15 11:13:24.019066: I tensorflow/core/common_runtime/bfc_allocator.cc:610] Bin (1024):  Total Chunks: 1, Chunks in use: 1. 1.3KiB allocated for chunks. 1.3KiB in use in bin. 1.0KiB client-requested in use in bin.
2018-11-15 11:13:24.031354: I tensorflow/core/common_runtime/bfc_allocator.cc:610] Bin (2048):  Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-11-15 11:13:24.050289: I tensorflow/core/common_runtime/bfc_allocator.cc:610] Bin (4096):  Total Chunks: 1, Chunks in use: 1. 6.0KiB allocated for chunks. 6.0KiB in use in bin. 6.0KiB client-requested in use in bin.
2018-11-15 11:13:24.059387: I tensorflow/core/common_runtime/bfc_allocator.cc:610] Bin (8192):  Total Chunks: 2, Chunks in use: 2. 16.0KiB allocated for chunks. 16.0KiB in use in bin. 16.0KiB client-requested in use in bin.
2018-11-15 11:13:24.065325: I tensorflow/core/common_runtime/bfc_allocator.cc:610] Bin (16384):         Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-11-15 11:13:24.074174: I tensorflow/core/common_runtime/bfc_allocator.cc:610] Bin (32768):         Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-11-15 11:13:24.079870: I tensorflow/core/common_runtime/bfc_allocator.cc:610] Bin (65536):         Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-11-15 11:13:24.085548: I tensorflow/core/common_runtime/bfc_allocator.cc:610] Bin (131072):        Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-11-15 11:13:24.088703: I tensorflow/core/common_runtime/bfc_allocator.cc:610] Bin (262144):        Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-11-15 11:13:24.091553: I tensorflow/core/common_runtime/bfc_allocator.cc:610] Bin (524288):        Total Chunks: 1, Chunks in use: 0. 997.3KiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-11-15 11:13:24.094381: I tensorflow/core/common_runtime/bfc_allocator.cc:610] Bin (1048576):       Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-11-15 11:13:24.097110: I tensorflow/core/common_runtime/bfc_allocator.cc:610] Bin (2097152):       Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-11-15 11:13:24.101620: I tensorflow/core/common_runtime/bfc_allocator.cc:610] Bin (4194304):       Total Chunks: 1, Chunks in use: 1. 4.00MiB allocated for chunks. 4.00MiB in use in bin. 4.00MiB client-requested in use in bin.
2018-11-15 11:13:24.104578: I tensorflow/core/common_runtime/bfc_allocator.cc:610] Bin (8388608):       Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-11-15 11:13:24.107331: I tensorflow/core/common_runtime/bfc_allocator.cc:610] Bin (16777216):      Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-11-15 11:13:24.110082: I tensorflow/core/common_runtime/bfc_allocator.cc:610] Bin (33554432):      Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-11-15 11:13:24.112827: I tensorflow/core/common_runtime/bfc_allocator.cc:610] Bin (67108864):      Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-11-15 11:13:24.115747: I tensorflow/core/common_runtime/bfc_allocator.cc:610] Bin (134217728):     Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-11-15 11:13:24.118215: I tensorflow/core/common_runtime/bfc_allocator.cc:610] Bin (268435456):     Total Chunks: 1, Chunks in use: 1. 3.19GiB allocated for chunks. 3.19GiB in use in bin. 3.09GiB client-requested in use in bin.
2018-11-15 11:13:24.120689: I tensorflow/core/common_runtime/bfc_allocator.cc:626] Bin for 4.00MiB was 4.00MiB, Chunk State:
2018-11-15 11:13:24.122095: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Chunk at 0000000205400000 of size 1280
2018-11-15 11:13:24.123459: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Chunk at 0000000205400500 of size 256
2018-11-15 11:13:24.126136: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Chunk at 0000000205400600 of size 256
2018-11-15 11:13:24.127441: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Chunk at 0000000205400700 of size 256
2018-11-15 11:13:24.128741: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Chunk at 0000000205400800 of size 8192
2018-11-15 11:13:24.130158: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Chunk at 0000000205402800 of size 256
2018-11-15 11:13:24.131464: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Chunk at 0000000205402900 of size 256
2018-11-15 11:13:24.132773: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Chunk at 0000000205402A00 of size 256
2018-11-15 11:13:24.134074: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Chunk at 0000000205402B00 of size 256
2018-11-15 11:13:24.135381: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Chunk at 0000000205402C00 of size 256
2018-11-15 11:13:24.136679: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Chunk at 0000000205402D00 of size 256
2018-11-15 11:13:24.138001: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Chunk at 0000000205402E00 of size 256
2018-11-15 11:13:24.139328: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Chunk at 0000000205402F00 of size 256
2018-11-15 11:13:24.140705: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Chunk at 0000000205403000 of size 256
2018-11-15 11:13:24.142029: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Chunk at 0000000205403100 of size 256
2018-11-15 11:13:24.143344: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Chunk at 0000000205403200 of size 256
2018-11-15 11:13:24.144668: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Chunk at 0000000205403300 of size 6144
2018-11-15 11:13:24.145986: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Chunk at 0000000205404B00 of size 8192
2018-11-15 11:13:24.147303: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Free  at 0000000205406B00 of size 1021184
2018-11-15 11:13:24.148646: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Chunk at 0000000205600000 of size 4194304
2018-11-15 11:13:24.150046: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Chunk at 0000000205A00000 of size 3430730752
2018-11-15 11:13:24.151428: I tensorflow/core/common_runtime/bfc_allocator.cc:651]      Summary of in-use Chunks by size:
2018-11-15 11:13:24.152751: I tensorflow/core/common_runtime/bfc_allocator.cc:654] 14 Chunks of size 256 totalling 3.5KiB
2018-11-15 11:13:24.154060: I tensorflow/core/common_runtime/bfc_allocator.cc:654] 1 Chunks of size 1280 totalling 1.3KiB
2018-11-15 11:13:24.155388: I tensorflow/core/common_runtime/bfc_allocator.cc:654] 1 Chunks of size 6144 totalling 6.0KiB
2018-11-15 11:13:24.156701: I tensorflow/core/common_runtime/bfc_allocator.cc:654] 2 Chunks of size 8192 totalling 16.0KiB
2018-11-15 11:13:24.158018: I tensorflow/core/common_runtime/bfc_allocator.cc:654] 1 Chunks of size 4194304 totalling 4.00MiB
2018-11-15 11:13:24.159378: I tensorflow/core/common_runtime/bfc_allocator.cc:654] 1 Chunks of size 3430730752 totalling 3.19GiB
2018-11-15 11:13:24.160771: I tensorflow/core/common_runtime/bfc_allocator.cc:658] Sum Total of in-use chunks: 3.20GiB
2018-11-15 11:13:24.163618: I tensorflow/core/common_runtime/bfc_allocator.cc:660] Stats:
Limit:                  3435973836
InUse:                  3434952448
MaxInUse:               3434952448
NumAllocs:                      20
MaxAllocSize:           3430730752

2018-11-15 11:13:24.166857: W tensorflow/core/common_runtime/bfc_allocator.cc:275] *************************************************************************************************xxx
2018-11-15 11:13:24.168832: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at assign_op.h:117 : Resource exhausted: OOM when allocating tensor with shape[512,2048] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\client\session.py", line 1292, in _do_call
    return fn(*args)
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\client\session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\client\session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[512,2048] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node lstm_1/recurrent_kernel/Assign}} = Assign[T=DT_FLOAT, _grappler_relax_allocator_constraints=true, use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](lstm_1/recurrent_kernel, lstm_1/recurrent_kernel/initial_value)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ddrqn_per.py", line 283, in <module>
    agent.model = Networks.ddrqn(state_size, action_size, agent.learning_rate)
  File "F:\Projects\gloob-bot\gloob-bot-model\networks.py", line 239, in ddrqn
    model = multi_gpu_model(model)
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\keras\utils\multi_gpu_utils.py", line 147, in multi_gpu_model
    available_devices = _get_available_devices()
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\keras\utils\multi_gpu_utils.py", line 16, in _get_available_devices
    return [x.name for x in K.get_session().list_devices()]
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\keras\backend\tensorflow_backend.py", line 206, in get_session
    session.run(tf.variables_initializer(uninitialized_vars))
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\client\session.py", line 887, in run
    run_metadata_ptr)
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\client\session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\client\session.py", line 1286, in _do_run
    run_metadata)
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\client\session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[512,2048] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node lstm_1/recurrent_kernel/Assign}} = Assign[T=DT_FLOAT, _grappler_relax_allocator_constraints=true, use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](lstm_1/recurrent_kernel, lstm_1/recurrent_kernel/initial_value)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


Caused by op 'lstm_1/recurrent_kernel/Assign', defined at:
  File "ddrqn_per.py", line 283, in <module>
    agent.model = Networks.ddrqn(state_size, action_size, agent.learning_rate)
  File "F:\Projects\gloob-bot\gloob-bot-model\networks.py", line 235, in ddrqn
    model.add(LSTM(512,  activation='tanh'))
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\keras\engine\sequential.py", line 181, in add
    output_tensor = layer(self.outputs[0])
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\keras\layers\recurrent.py", line 532, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\keras\engine\base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\keras\layers\recurrent.py", line 493, in build
    self.cell.build(step_input_shape)
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\keras\layers\recurrent.py", line 1874, in build
    constraint=self.recurrent_constraint)
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\keras\engine\base_layer.py", line 252, in add_weight
    constraint=constraint)
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\keras\backend\tensorflow_backend.py", line 402, in variable
    v = tf.Variable(value, dtype=tf.as_dtype(dtype), name=name)
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\ops\variables.py", line 145, in __call__
    return cls._variable_call(*args, **kwargs)
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\ops\variables.py", line 141, in _variable_call
    aggregation=aggregation)
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\ops\variables.py", line 120, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2441, in default_variable_creator
    expected_shape=expected_shape, import_scope=import_scope)
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\ops\variables.py", line 147, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\ops\variables.py", line 1104, in __init__
    constraint=constraint)
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\ops\variables.py", line 1256, in _init_from_args
    validate_shape=validate_shape).op
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\ops\state_ops.py", line 221, in assign
    validate_shape=validate_shape)
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 65, in assign
    use_locking=use_locking, name=name)
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\framework\ops.py", line 3272, in create_op
    op_def=op_def)
  File "C:\Users\kevin\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\framework\ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[512,2048] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node lstm_1/recurrent_kernel/Assign}} = Assign[T=DT_FLOAT, _grappler_relax_allocator_constraints=true, use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](lstm_1/recurrent_kernel, lstm_1/recurrent_kernel/initial_value)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

```

**Comment by kevupton** [comment]
When I had less Idea about what was going on:  #11624

**Comment by wookayin** [comment]
I guess this has been closed due to inactivity for 2+ years. However, even in 2022 with the recent version of tensorflow (2.8.0), this **bug** still presents. 

Nothing but just a single line of `with tf.device('/cpu:0'): pass` will allocate some small portion of GPU memories, which doesn't get released. Does anyone have any idea why this happens?
