### ISSUE TITLE
TypeError: can't pickle _thread.RLock objects while saving the keras model using model.save() 

### ISSUE THREAD

**Issue by roburst2** [keras-team/keras#11650]
I want to save the network architecture of this model but getting can't pickle error. I tried some solution but not able to resolve.

_# Callbacks
callbacks = [
keras.callbacks.TensorBoard(log_dir=self.log_dir,
histogram_freq=0, write_graph=True, write_images=False),
keras.callbacks.ModelCheckpoint(self.checkpoint_path,
verbose=0, save_weights_only=False),
]

    # Add custom callbacks to the list
    if custom_callbacks:
        callbacks += custom_callbacks

    # Train
    log("\nStarting at epoch {}. LR={}\n".format(self.epoch, learning_rate))
    log("Checkpoint Path: {}".format(self.checkpoint_path))
    self.set_trainable(layers)
    self.compile(learning_rate, self.config.LEARNING_MOMENTUM)

    # Work-around for Windows: Keras fails on Windows when using
    # multiprocessing workers. See discussion here:
    # https://github.com/matterport/Mask_RCNN/issues/13#issuecomment-353124009
    if os.name is 'nt':
        workers = 0
    else:
        workers = multiprocessing.cpu_count()

    self.keras_model.fit_generator(
        train_generator,
        initial_epoch=self.epoch,
        epochs=epochs,
        steps_per_epoch=self.config.STEPS_PER_EPOCH,
        callbacks=callbacks,
        validation_data=val_generator,
        validation_steps=self.config.VALIDATION_STEPS,
        max_queue_size=100,
        workers=workers,  #old value is workers
        use_multiprocessing=True,
    )_
In network.py i replaced "return copy.deepcopy(config) " to "return config" but got new error json is not serializable.
I tried to change all lambda with a function but still getting the can't pickle error.
I tried to save the model before training, getting same error.
i tried below code as well to save the model
_model.save('mask_rcnn.h5').

with open('model_architecture_subin.json', 'w') as f:
f.write(model.to_json())_
with yaml also i tried but same issue.

logs for can't pickle _thread.RLock objects
Traceback (most recent call last):
File "custom.py", line 309, in 
train(model)
File "custom.py", line 220, in train
imgaug.augmenters.Affine(rotate=(-90, 90))
File "/home/hasmeet/nj/surface_crack_detection/mask_rcnn_solution/Final_Mask_RCNN_Sol/src/mrcnn/model.py", line 2453, in train
use_multiprocessing=True,
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
return func(*args, **kwargs)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
initial_epoch=initial_epoch)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/site-packages/keras/engine/training_generator.py", line 251, in fit_generator
callbacks.on_epoch_end(epoch, epoch_logs)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/site-packages/keras/callbacks.py", line 79, in on_epoch_end
callback.on_epoch_end(epoch, logs)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/site-packages/keras/callbacks.py", line 457, in on_epoch_end
model_json = self.model.to_json()
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/site-packages/keras/engine/network.py", line 1239, in to_json
model_config = self._updated_config()
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/site-packages/keras/engine/network.py", line 1187, in _updated_config
config = self.get_config()
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/site-packages/keras/engine/network.py", line 934, in get_config
return copy.deepcopy(config) #can't pickable error
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 150, in deepcopy
y = copier(x, memo)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 240, in _deepcopy_dict
y[deepcopy(key, memo)] = deepcopy(value, memo)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 150, in deepcopy
y = copier(x, memo)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 215, in _deepcopy_list
append(deepcopy(a, memo))
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 150, in deepcopy
y = copier(x, memo)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 240, in _deepcopy_dict
y[deepcopy(key, memo)] = deepcopy(value, memo)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 150, in deepcopy
y = copier(x, memo)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 240, in _deepcopy_dict
y[deepcopy(key, memo)] = deepcopy(value, memo)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 150, in deepcopy
y = copier(x, memo)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 220, in _deepcopy_tuple
y = [deepcopy(a, memo) for a in x]
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 220, in 
y = [deepcopy(a, memo) for a in x]
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 150, in deepcopy
y = copier(x, memo)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 220, in _deepcopy_tuple
y = [deepcopy(a, memo) for a in x]
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 220, in 
y = [deepcopy(a, memo) for a in x]
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 180, in deepcopy
y = _reconstruct(x, memo, *rv)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 280, in _reconstruct
state = deepcopy(state, memo)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 150, in deepcopy
y = copier(x, memo)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 240, in _deepcopy_dict
y[deepcopy(key, memo)] = deepcopy(value, memo)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 180, in deepcopy
y = _reconstruct(x, memo, *rv)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 280, in _reconstruct
state = deepcopy(state, memo)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 150, in deepcopy
y = copier(x, memo)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 240, in _deepcopy_dict
y[deepcopy(key, memo)] = deepcopy(value, memo)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 180, in deepcopy
y = _reconstruct(x, memo, *rv)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 280, in _reconstruct
state = deepcopy(state, memo)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 150, in deepcopy
y = copier(x, memo)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 240, in _deepcopy_dict
y[deepcopy(key, memo)] = deepcopy(value, memo)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 180, in deepcopy
y = _reconstruct(x, memo, *rv)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 280, in _reconstruct
state = deepcopy(state, memo)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 150, in deepcopy
y = copier(x, memo)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 240, in _deepcopy_dict
y[deepcopy(key, memo)] = deepcopy(value, memo)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/copy.py", line 169, in deepcopy
rv = reductor(4)
TypeError: can't pickle _thread.RLock objects

logs for Not JSON Serializable

Traceback (most recent call last):
File "custom.py", line 309, in 
train(model)
File "custom.py", line 220, in train
imgaug.augmenters.Affine(rotate=(-90, 90))
File "/home/hasmeet/nj/surface_crack_detection/mask_rcnn_solution/Final_Mask_RCNN_Sol/src/mrcnn/model.py", line 2453, in train
use_multiprocessing=True,
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
return func(*args, **kwargs)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
initial_epoch=initial_epoch)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/site-packages/keras/engine/training_generator.py", line 251, in fit_generator
callbacks.on_epoch_end(epoch, epoch_logs)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/site-packages/keras/callbacks.py", line 79, in on_epoch_end
callback.on_epoch_end(epoch, logs)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/site-packages/keras/callbacks.py", line 457, in on_epoch_end
model_json = self.model.to_json()
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/site-packages/keras/engine/network.py", line 1240, in to_json
return json.dumps(model_config, default=get_json_type, **kwargs)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/json/init.py", line 238, in dumps
**kw).encode(obj)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/json/encoder.py", line 199, in encode
chunks = self.iterencode(o, _one_shot=True)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/json/encoder.py", line 257, in iterencode
return _iterencode(o, 0)
File "/home/hasmeet/.conda/envs/ai_maskrcnn/lib/python3.6/site-packages/keras/engine/network.py", line 1237, in get_json_type
raise TypeError('Not JSON Serializable:', obj)
TypeError: ('Not JSON Serializable:', <tf.Variable 'anchors/Variable:0' shape=(1, 16368, 4) dtype=float32_ref>)

**Comment by roburst2** [comment]
Not yet @shobhitpuri

**Comment by ShujianHu** [comment]
@roburst2 Same issue here, I looked into keras.models.save_model and found it starts with json serialization, may you show the copy that why yaml also failed you?

**Comment by 95xueqian** [comment]
I have the same problems when save Mask-RCNN model ,have you solved this issue? @roburst2

**Comment by roburst2** [comment]
no @95xueqian

**Comment by lunasdejavu** [comment]
how about using the old version of keras and tensorflow? Have anyone tried it yet?
