### ISSUE TITLE
Allow rank > 2 input sparse tensor

### ISSUE THREAD

**Issue by hanayashiki** [keras-team/keras#11724]
I really cannot find a way to input **sparse** tensor with more than 2-d (in batch). In `scipy.sparse` there are really only implementations for sparse matrix but not sparse tensor (using `scipy.sparse` is also not mentioned in the document, [](https://keras.io/layers/core/#input)). I think this needs an improvement to allow rank > 2 input sparse tensors. 

I am constructing a graph network, where I need to deal with sparse adjacent matrices. To train in batch, I need to feed adjacent matrices with the shape of (sample, n, n), so it is really necessary for this kind of jobs to allow rank > 2 sparse tensors as input.

**Comment by gabrieldemarmiesse** [comment]
Please provide a simple script to reproduce. It will be easier to understand what is your use case.

**Comment by hanayashiki** [comment]
For the case:
```
import keras
from keras.layers import Input, Dense
from keras.models import Model
import numpy as np

I = Input(shape=(3, 3), name="L", sparse=True) # batch will be (batch_size, 3, 3)
m = Model(I, I)

m.predict(np.array([
    [[1, 0, 0],
    [0, 1, 0],
    [0, 0, 0]]
], dtype=np.float32))
```
and there will be errors:
```
C:\Users\Kiritsugu Emiya\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "D:/RelatedConcept/gcn-judge/play/keras_issue.py", line 13, in <module>
    ], dtype=np.float32))
  File "C:\Users\Kiritsugu Emiya\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 1839, in predict
    self._make_predict_function()
  File "C:\Users\Kiritsugu Emiya\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 1029, in _make_predict_function
    **kwargs)
  File "C:\Users\Kiritsugu Emiya\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 2499, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "C:\Users\Kiritsugu Emiya\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 2442, in __init__
    with tf.control_dependencies(self.outputs):
  File "C:\Users\Kiritsugu Emiya\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 5002, in control_dependencies
    return get_default_graph().control_dependencies(control_inputs)
  File "C:\Users\Kiritsugu Emiya\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 4541, in control_dependencies
    c = self.as_graph_element(c)
  File "C:\Users\Kiritsugu Emiya\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3488, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "C:\Users\Kiritsugu Emiya\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3577, in _as_graph_element_locked
    types_str))
TypeError: Can not convert a SparseTensor into a Tensor or Operation.
```
That's pretty fast, thank you. And if you add an `Dense` layer after "L", there will be another error.

**Comment by hanayashiki** [comment]
Maybe you are right. Whatever the problem is, keras/tf does not provide a full support for sparse tensor, which I think should at least be noted in the document. Since `Input` layer has parameter `sparse`, it is quite misleading for beginners, and they consider keras/tf's feature for sparse tensor is fully provided,

**Comment by gabrieldemarmiesse** [comment]
You can pass sparse tensors to `fit`, `evaluate`, `fit_generator`... etc. And then not specifying sparse=True in the input layer. Keras will automatically convert your tensors before feeding them to the graph. Would that work for you?

**Comment by hanayashiki** [comment]
Thank you for your suggestion. But not specifying sparse=True will cost a lot of memory to store the tensor in the GPU, is that correct? My adjacency matrix is of size N^2. Or keras will optimize the memory for me ?

**Comment by gabrieldemarmiesse** [comment]
It will indeed take more memory on the gpu. Or not. It actually depends on how sparse is your tensor. The performance sparse/non-sparse is also to take into account. Unless your tensors have a huge majority of zeros (more than 95% -ish), the operations will be slower on a sparse tensor than on a normal one.

**Comment by hanayashiki** [comment]
Thank you, I think I got the answer.
