### ISSUE TITLE
keras/examples/tensorboard_embeddings_mnist.py gives an 

### ISSUE THREAD

**Issue by adityabalu** [keras-team/keras#11757]
- [ yes] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [ yes] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [https://github.com/keras-team/keras/blob/master/examples/tensorboard_embeddings_mnist.py] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

I am using Anaconda python(3.6) for running the example code for tensorboard embedding in mnist. After training for an epoch, when the call back is called, it gives the following error. 

Epoch 1/12
60000/60000 [==============================] - 8s 139us/step - loss: 0.2665 - acc: 0.9170 - val_loss: 0.0716 - val_acc: 0.9774
2018-11-29 13:04:24.254467: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_v2_ops.cc:137 : Unknown: Failed to rename: ./logs\keras_embedding.ckpt-0.data-00000-of-00001.tempstate7943206387758954579 to: ./logs\keras_embedding.ckpt-0.data-00000-of-00001 : Access is denied.
; Input/output error
Traceback (most recent call last):
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: Failed to rename: ./logs\keras_embedding.ckpt-0.data-00000-of-00001.tempstate7943206387758954579 to: ./logs\keras_embedding.ckpt-0.data-00000-of-00001 : Access is denied.
; Input/output error
         [[{{node save/SaveV2}} = SaveV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, features_embedding/_137)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "embedding.py", line 88, in <module>
    validation_data=(x_test, y_test))
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\keras\engine\training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\keras\engine\training_arrays.py", line 217, in fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\keras\callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\keras\callbacks.py", line 981, in on_epoch_end
    epoch)
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\tensorflow\python\training\saver.py", line 1441, in save
    {self.saver_def.filename_tensor_name: checkpoint_file})
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: Failed to rename: ./logs\keras_embedding.ckpt-0.data-00000-of-00001.tempstate7943206387758954579 to: ./logs\keras_embedding.ckpt-0.data-00000-of-00001 : Access is denied.
; Input/output error
         [[node save/SaveV2 (defined at C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\keras\callbacks.py:887)  = SaveV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, features_embedding/_137)]]

Caused by op 'save/SaveV2', defined at:
  File "embedding.py", line 88, in <module>
    validation_data=(x_test, y_test))
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\keras\engine\training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\keras\engine\training_arrays.py", line 117, in fit_loop
    callbacks.set_model(callback_model)
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\keras\callbacks.py", line 54, in set_model
    callback.set_model(model)
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\keras\callbacks.py", line 887, in set_model
    self.saver = tf.train.Saver(list(embeddings_vars.values()))
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\tensorflow\python\training\saver.py", line 1102, in __init__
    self.build()
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\tensorflow\python\training\saver.py", line 1114, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\tensorflow\python\training\saver.py", line 1151, in _build
    build_save=build_save, build_restore=build_restore)
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\tensorflow\python\training\saver.py", line 792, in _build_internal
    save_tensor = self._AddSaveOps(filename_tensor, saveables)
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\tensorflow\python\training\saver.py", line 284, in _AddSaveOps
    save = self.save_op(filename_tensor, saveables)
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\tensorflow\python\training\saver.py", line 202, in save_op
    tensors)
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1690, in save_v2
    shape_and_slices=shape_and_slices, tensors=tensors, name=name)
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): Failed to rename: ./logs\keras_embedding.ckpt-0.data-00000-of-00001.tempstate7943206387758954579 to: ./logs\keras_embedding.ckpt-0.data-00000-of-00001 : Access is denied.
; Input/output error
         [[node save/SaveV2 (defined at C:\Users\abalu\AppData\Local\Continuum\anaconda3\envs\keras\lib\site-packages\keras\callbacks.py:887)  = SaveV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, features_embedding/_137)]]

I searched for the possible reasons for this to happen, I found the following few issues/discussion:
https://github.com/balancap/SSD-Tensorflow/issues/72
https://stackoverflow.com/questions/43644893/windows-tensorflow-could-not-restore-checkpoint-access-is-denied

my understanding is that, this could be something to do with the behavior in windows. I dont know what the exact issue is, I would like to contribute if someone could let me know what might be the issue. Thanks

**Comment by gabrieldemarmiesse** [comment]
This is an access denied error. This just means that you don't have the windows permissions to do something, like create or rename a file. This is unrelated to keras or tensorflow.

**Comment by adityabalu** [comment]
But I do have write access to that folder... Something else seems to be the problem
