### ISSUE TITLE
OSError: [Errno 22] Invalid argument: Problem with multiprocessing, pickler

### ISSUE THREAD

**Issue by matteobsu** [keras-team/keras#11790]
Dear keras community, I am encountering this issue on Windows 7. Anybody has an issu of what is goin on?

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\easi\lib\threading.py", line 916, in _boot
strap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\easi\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\easi\lib\site-packages\keras\utils\data_ut
ils.py", line 565, in _run
    with closing(self.executor_fn(_SHARED_SEQUENCES)) as executor:
  File "C:\ProgramData\Anaconda3\envs\easi\lib\site-packages\keras\utils\data_ut
ils.py", line 548, in <lambda>
    initargs=(seqs,))
  File "C:\ProgramData\Anaconda3\envs\easi\lib\multiprocessing\context.py", line
 119, in Pool
    context=self.get_context())
  File "C:\ProgramData\Anaconda3\envs\easi\lib\multiprocessing\pool.py", line 17
5, in __init__
    self._repopulate_pool()
  File "C:\ProgramData\Anaconda3\envs\easi\lib\multiprocessing\pool.py", line 23
6, in _repopulate_pool
    self._wrap_exception)
  File "C:\ProgramData\Anaconda3\envs\easi\lib\multiprocessing\pool.py", line 25
5, in _repopulate_pool_static
    w.start()
  File "C:\ProgramData\Anaconda3\envs\easi\lib\multiprocessing\process.py", line
 105, in start
    self._popen = self._Popen(self)
  File "C:\ProgramData\Anaconda3\envs\easi\lib\multiprocessing\context.py", line
 322, in _Popen
    return Popen(process_obj)
  File "C:\ProgramData\Anaconda3\envs\easi\lib\multiprocessing\popen_spawn_win32
.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\ProgramData\Anaconda3\envs\easi\lib\multiprocessing\reduction.py", li
ne 60, in dump
    ForkingPickler(file, protocol).dump(obj)
OSError: [Errno 22] Invalid argument

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\easi\lib\multiprocessing\spawn.py", line 1
05, in spawn_main
    exitcode = _main(fd)
  File "C:\ProgramData\Anaconda3\envs\easi\lib\multiprocessing\spawn.py", line 1
15, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by matteobsu** [comment]
I think I may have found the solution for the first error:
in line 60 of "reduction.py" I replaced

 ForkingPickler(file, protocol).dump(obj)

with

 ForkingPickler(file, protocol).**dumps**(obj)

and now I'm seeing only the EOFError: Ran out of input.

Is it something that only happens when there is not enough input data?
