### ISSUE TITLE
Running the cifar10_cnn.py example in /keras/examples/ raises a ValueError

### ISSUE THREAD

**Issue by yupm** [keras-team/keras#11874]
Fresh install of Anaconda 1.9.2
Setup Python 3.6 env
Install tensorflow-gpu==1.12.0 and keras-gpu==2.2.4 using anacondat navigator interface

Git clone https://github.com/keras-team/keras.git 

Run the cifar10_cnn.py file in /keras/examples is Spyder

```
x_train shape: (50000, 32, 32, 3)
50000 train samples
10000 test samples
Using real-time data augmentation.
Traceback (most recent call last):

  File "<ipython-input-3-8bbe9b9a8660>", line 1, in <module>
    runfile('C:/Users/Usr/Documents/Git/keras/examples/cifar10_cnn.py', wdir='C:/Users/Usr/Documents/Git/keras/examples')

  File "C:\Users\Usr\Anaconda3\envs\python36\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "C:\Users\Usr\Anaconda3\envs\python36\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Usr/Documents/Git/keras/examples/cifar10_cnn.py", line 118, in <module>
    workers=4)

  File "C:\Users\Usr\Anaconda3\envs\python36\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\	Usr\Anaconda3\envs\python36\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)

  File "C:\Users\Usr\Anaconda3\envs\python36\lib\site-packages\keras\engine\training_generator.py", line 55, in fit_generator
    raise ValueError('`steps_per_epoch=None` is only valid for a'

ValueError: `steps_per_epoch=None` is only valid for a generator based on the `keras.utils.Sequence` class. Please specify `steps_per_epoch` or use the `keras.utils.Sequence` class.
```

**Comment by Golbstein** [comment]
read the error.
set '`steps_pre_epoch = len(x_train)//batch_size`' in "fit_generator"

**Comment by gabrieldemarmiesse** [comment]
I think this issue was fixed recently. Can you try with the master branch?

**Comment by ianvonseggern1** [comment]
This still repros for me on master

**Comment by ianvonseggern1** [comment]
https://github.com/keras-team/keras/pull/12666
