### ISSUE TITLE
Loading multi_gpu_model on Windows fails with SystemError: unknown opcode

### ISSUE THREAD

**Issue by albert-92** [keras-team/keras#11870]
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [x] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

When i try to load a multi_gpu_model on windows with either `load_model` or `model_from_json` i get the following Error:

```
XXX lineno: 184, opcode: 0
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/auser/.PyCharm2018.2/config/scratches/scratch_6.py", line 6, in <module>
    model = keras.models.model_from_json(jsonString)
  File "C:\Users\auser\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\saving.py", line 492, in model_from_json
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Users\auser\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "C:\Users\auser\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\utils\generic_utils.py", line 147, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Users\auser\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\network.py", line 1029, in from_config
    process_node(layer, node_data)
  File "C:\Users\auser\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\network.py", line 988, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "C:\Users\auser\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\auser\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\layers\core.py", line 707, in call
    return self.function(inputs, **arguments)
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/multi_gpu_utils.py", line 184, in get_slice
SystemError: unknown opcode
```

In the last line of the traceback it is saying `File "/usr/local/lib/python3.5/dist-packages/keras/utils/multi_gpu_utils.py", line 184, in get_slice` which is realy strange, since i am on Windows 10 64-bit.

I tried to reproduce the error with the same model files on ubuntu 16.04 with the same keras version (2.2.4) and there everything works just fine.

So it seems to be a Windows specific error. 

Important! The model was trained and saved on a ubuntu machine. Maybe this is part of the problem.

**Comment by albert-92** [comment]
Okay i found out the issue.

The model was trained with Python 3.5, however trying to load a multi_gpu_model fails when using Python > 3.5 (3.6 in my case) to load it.

It has something to do with the lamba incompatibility between Python 3.5 and Python 3.6.

Maybe this should be fixed somehow, or at least mentioned in the docs, since it says:

> Keras is compatible with: Python 2.7-3.6.

**Comment by harshini-gadige** [comment]
Yes you are right @albert-92. Since the Python version varies between training and loading the model, it causes this issue.
