### ISSUE TITLE
Code runs fine with CPU but AttributeError with GPU

### ISSUE THREAD

**Issue by FiReTiTi** [keras-team/keras#11881]
Hi,
I wanted to train a U-net, and everything works fine on my laptop with the tensorflow CPU version. However, on the cluster with a GPU, I can create and compile it, but when I call the `fit_generator` method I get the following error:

    Traceback (most recent call last):
      File "Cluster.py", line 46, in <module>
    unet.fit_generator(gen, steps_per_epoch=gen.getStepsPerEpoch(), epochs=101)
      File "/home/exacloud/tempwork/ChangLab/Guillaume/Python/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
      File "/home/exacloud/tempwork/ChangLab/Guillaume/Python/lib/python3.5/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
      File "/home/exacloud/tempwork/ChangLab/Guillaume/Python/lib/python3.5/site-packages/keras/engine/training_generator.py", line 40, in fit_generator
    model._make_train_function()
      File "/home/exacloud/tempwork/ChangLab/Guillaume/Python/lib/python3.5/site-packages/keras/engine/training.py", line 509, in _make_train_function
    loss=self.total_loss)
      File "/home/exacloud/tempwork/ChangLab/Guillaume/Python/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
      File "/home/exacloud/tempwork/ChangLab/Guillaume/Python/lib/python3.5/site-packages/keras/optimizers.py", line 410, in get_updates
    self.updates.append(K.update(a, new_a))
      File "/home/exacloud/tempwork/ChangLab/Guillaume/Python/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 973, in update
    return tf.assign(x, new_x)
      File "/home/exacloud/tempwork/ChangLab/Guillaume/Conda/DL35/lib/python3.5/site-packages/tensorflow/python/ops/state_ops.py", line 277, in assign
    return ref.assign(value)
    AttributeError: 'Tensor' object has no attribute 'assign'

So the exact same code runs perfectly on my laptop on the cpu only version of Tensorflow, but not on the GPU one.

Any idea what the issue may be?

Thanks in advance!

**Comment by harshini-gadige** [comment]
When you are using tf.assign(a,b), 'a' should be a variable. In your example tf.assign(x, new_x), the error could be due to x being declared as a constant. Please change it to a mutable tensor(variable) and try it. 
Thanks !

**Comment by FiReTiTi** [comment]
I don't assign anything because it happens in the keras fit_generator method, and it works fine on my laptop.

**Comment by Dref360** [comment]
Hi,
We could work on this better if you could provide a standalone reproducible example.
Requirements:
* Don't use custom data or custom paths.
* Use random arrays or even np.ones, np.zeros.
* The example should run with Keras (and deps) alone.
* Should be Python3 compatible.
* Should not be OS specific.
* The file should reproduce the bug with **high* fidelity.
* Link to a gist would be appreciated.

Thanks!
Dref360

**Comment by FiReTiTi** [comment]
Mmm... I cannot reproduce the issue everytime I start the soft. I am going to investigate.
