### ISSUE TITLE
Pre-trained models don't work in float16 mode

### ISSUE THREAD

**Issue by rohit-gupta** [keras-team/keras#11989]
If you try to use the pre-trained models in float16 mode, they just don't load. I think fixing this can be useful, especially for object detection use cases.

```
import numpy as np

from keras import backend as K
from keras.applications.resnet50 import ResNet50
from keras.applications.resnet50 import preprocess_input, decode_predictions

K.set_floatx('float16')

backbone = ResNet50(include_top=False, weights='imagenet', pooling=None)
```

```
Traceback (most recent call last):
  File "retinanet.py", line 11, in <module>
    backbone = ResNet50(include_top=False, weights='imagenet', pooling=None)
  File "/path/to/python/python2.7/site-packages/keras/applications/__init__.py", line 28, in wrapper
    return base_fun(*args, **kwargs)
  File "/path/to/python/python2.7/site-packages/keras/applications/resnet50.py", line 11, in ResNet50
    return resnet50.ResNet50(*args, **kwargs)
  File "/path/to/python/python2.7/site-packages/keras_applications/resnet50.py", line 231, in ResNet50
    x = layers.BatchNormalization(axis=bn_axis, name='bn_conv1')(x)
  File "/path/to/python/python2.7/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/path/to/python/python2.7/site-packages/keras/layers/normalization.py", line 185, in call
    epsilon=self.epsilon)
  File "/path/to/python/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1864, in normalize_batch_in_training
    epsilon=epsilon)
  File "/path/to/python/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1839, in _fused_normalize_batch_in_training
    data_format=tf_data_format)
  File "/path/to/python/python2.7/site-packages/tensorflow/python/ops/nn_impl.py", line 909, in fused_batch_norm
    name=name)
  File "/path/to/python/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 3836, in fused_batch_norm_v2
    is_training=is_training, name=name)
  File "/path/to/python/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 609, in _apply_op_helper
    param_name=input_name)
  File "/path/to/python/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'scale' has DataType float16 not in list of allowed values: float32
```

**Comment by rohit-gupta** [comment]
Thought you might find this interesting @taehoonlee

**Comment by Golbstein** [comment]
it's because ResNet50 contains BatchNormalization layers, which are not supported in float16 mode unfortunately. 
To overcome this issue, either consider using a model without batchnormalization or write your own BatchNorm layer and change it in model's build function.

In my github page I shared a custom BatchNorm layer that support float16, you're welcome to pull it and use it in your project: [float_16_BatchNormalization](https://github.com/Golbstein/KerasExtras/blob/master/BN16.py)

**Comment by rohit-gupta** [comment]
@Golbstein Thanks ! Though it would be better if this is supported in http://github.com/keras-team/keras-applications as well, given half precision training is very important for many use cases.

**Comment by taehoonlee** [comment]
@rohit-gupta, What is your version of TensorFlow? The float16 for the `BatchNormalization` has been supported since TensorFlow 1.5.

**Comment by rohit-gupta** [comment]
@taehoonlee I have Tensorflow 1.10

**Comment by rohit-gupta** [comment]
@taehoonlee Thanks !

**Comment by rjpg** [comment]
Hello Iam using google colab (up to date) 

I cant use pre-trained inception with keras in float16 .... 

here is the code : 
```

from keras.applications.inception_v3 import InceptionV3
from keras.layers import Input, Dense, GlobalAveragePooling2D
from keras.models import Model
from keras import backend as K
import tensorflow as tf
from keras.optimizers import Adam
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers.convolutional import Conv2D 
from keras.layers.convolutional import AveragePooling2D, MaxPooling2D
from keras.layers.core import Activation, Dropout
from keras.layers.core import Flatten
from keras.layers.core import Dense
from keras.datasets import mnist
from keras.utils import np_utils
from keras.optimizers import SGD, RMSprop, Adam
import matplotlib.pyplot as plt
from keras.callbacks import TensorBoard
from keras.callbacks import EarlyStopping
from keras.callbacks import ReduceLROnPlateau
from keras.callbacks import ModelCheckpoint
from keras.engine.topology import Layer,InputSpec

dtype='float16'
K.set_floatx(dtype)

# default is 1e-7 which is too small for float16.  Without adjusting the epsilon, we will get NaN predictions because of divide by zero problems
K.set_epsilon(1e-4) 

# this could also be the output a different Keras model or layer
input_tensor = Input(shape=(512, 650, 3))  # this assumes K.image_data_format() == 'channels_last'

base_model = InceptionV3(input_tensor=input_tensor, weights='imagenet', include_top=False,pooling=max,classes=512)
# add a global spatial average pooling layer
x = base_model.output
x = GlobalAveragePooling2D()(x)
# let's add a fully-connected layer
x = Dense(1024, activation='relu')(x)
# and a logistic layer -- let's say we have 200 classes
predictions = Dense(5, activation='softmax')(x)

# this is the model we will train
model = Model(inputs=base_model.input, outputs=predictions)
```


and the error : ```


---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-494b27bb2539> in <module>()
     31 input_tensor = Input(shape=(512, 650, 3))  # this assumes K.image_data_format() == 'channels_last'
     32 
---> 33 base_model = InceptionV3(input_tensor=input_tensor, weights='imagenet', include_top=False,pooling=max,classes=512)
     34 # add a global spatial average pooling layer
     35 x = base_model.output

11 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py in _SatisfiesTypeConstraint(dtype, attr_def, param_name)
     58           "allowed values: %s" %
     59           (param_name, dtypes.as_dtype(dtype).name,
---> 60            ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
     61 
     62 

TypeError: Value passed to parameter 'scale' has DataType float16 not in list of allowed values: float32
```

**Comment by grofte** [comment]
Just to bump this: 

BatchNormalization might work now but LayerNormalization does not work in TF 2.1.0 with mixed precision.
