### ISSUE TITLE
invalid literal for int() with base 10: 'Participant1' 

### ISSUE THREAD

**Issue by sekti92** [keras-team/keras#12047]
`x_train.dat` contains my images and `y_train.dat` contains my label however I when I try to train it with model.fit it keeps give me an error.

How I can run the `model.compile`? Please help

```
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from pathlib import Path
import joblib
import matplotlib.pyplot as plt

# Load data set
x_train = joblib.load("x_train.dat")
y_train = joblib.load("y_train.dat")
epochs = 50

# Create a model and add layers
model = Sequential()

model.add(Flatten(input_shape=x_train.shape[1:]))
model.add(Dense(512, activation='relu', name='fc1'))
model.add(Dropout(0.3))
model.add(Dense(512, activation='relu', name='fc2'))
model.add(Dropout(0.3))
model.add(Dense(1, activation='relu', name='prediction'))

model.summary()

# compile model
# model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizers.RMSprop(lr=2e-4), metrics=['accuracy'])
model.compile(loss='categorical_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

from keras.utils import to_categorical
y_train = to_categorical(y_train)

history = model.fit(
    x_train,
    y_train,
    epochs=epochs,
    shuffle=True
)

# Save neural network structure
model_structure = model.to_json()
f = Path("model_structure.json")
f.write_text(model_structure)

# Save the model
model.save('vgg16_pretrained_2.h5')




# Check Performance
acc = history.history['acc']
val_acc = history.history['val_acc']
loss = history.history['loss']
val_loss = history.history['val_loss']

epochs = range(len(acc))

plt.plot(epochs, acc, 'b', label='Training acc')
plt.plot(epochs, val_acc, 'r', label='Validation acc')
plt.title('Training and validation accuracy')
plt.legend()

plt.figure()

plt.plot(epochs, loss, 'b', label='Training loss')
plt.plot(epochs, val_loss, 'r', label='Validation loss')
plt.title('Training and validation loss')
plt.legend()

plt.show()
```

terminal output:
```
Using TensorFlow backend.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
flatten_1 (Flatten)          (None, 25088)             0         
_________________________________________________________________
fc1 (Dense)                  (None, 512)               12845568  
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
_________________________________________________________________
fc2 (Dense)                  (None, 512)               262656    
_________________________________________________________________
dropout_2 (Dropout)          (None, 512)               0         
_________________________________________________________________
prediction (Dense)           (None, 1)                 513       
=================================================================
Total params: 13,108,737
Trainable params: 13,108,737
Non-trainable params: 0
_________________________________________________________________
Traceback (most recent call last):
  File "C:/Users/w024029h/PycharmProjects/keras_pretrained/2_training_image.py", line 29, in <module>
    y_train = to_categorical(y_train)
  File "C:\Users\w024029h\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\utils\np_utils.py", line 25, in to_categorical
    y = np.array(y, dtype='int')
ValueError: invalid literal for int() with base 10: 'Participant1'
```

**Comment by abtExp** [comment]
to_categorical requires 2 parameters, the second parameter is the number of classes. You must provide the second parameter as well.

**Comment by abtExp** [comment]
to_categorical converts integer labels to binary vectors, make sure your labels are integers, also use a softmax activation for categorical crossentropy, also, the to_categorical requires a second parameter, num_classes , 
```
to_categorical(labels, num_classes)
```
Looking at your model, I guess you want to do binary classification, in that case use sigmoid activation and binary crossentropy loss

**Comment by sekti92** [comment]
@abtExp I try your suggestion.
But did not work 
```
# Create a model and add layers
model = Sequential()

model.add(Flatten(input_shape=x_train.shape[1:]))
model.add(Dense(512, activation='relu', name='fc1'))
model.add(Dropout(0.3))
model.add(Dense(512, activation='relu', name='fc2'))
model.add(Dropout(0.3))
model.add(Dense(1, activation='sigmoid', name='prediction'))

model.summary()

# compile model
# model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizers.RMSprop(lr=2e-4), metrics=['accuracy'])
model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

from keras.utils import to_categorical
y_train = to_categorical(y_train, 12)

history = model.fit(
    x_train,
    y_train,
    epochs=epochs,
    shuffle=True
)

```

I have this error: 

> IndexError: index 12 is out of bounds for axis 1 with size 12

**Comment by abtExp** [comment]
You can't do 12 way classification with a single unit as your output layer,
Do 
```
model.add(Dense(12, activation='softmax', name='prediction'))
```
And use the categorical_crossentropy loss

**Comment by sekti92** [comment]
@abtExp i did that but this error came up

> y_train = to_categorical(y_train, 12)
>   File "C:\Users\w024029h\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\utils\np_utils.py", line 34, in to_categorical
>     categorical[np.arange(n), y] = 1
> IndexError: index 12 is out of bounds for axis 1 with size 12

**Comment by abtExp** [comment]
Can you share how the labels look like?

**Comment by sekti92** [comment]
The table Preview:

```
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
flatten_1 (Flatten)          (None, 25088)             0         
_________________________________________________________________
fc1 (Dense)                  (None, 512)               12845568  
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
_________________________________________________________________
fc2 (Dense)                  (None, 512)               262656    
_________________________________________________________________
dropout_2 (Dropout)          (None, 512)               0         
_________________________________________________________________
prediction (Dense)           (None, 12)                6156      
=================================================================
Total params: 13,114,380
Trainable params: 13,114,380
Non-trainable params: 0
```

**Comment by msymp** [comment]
@pavithrasv , the user is trying to find the errors arising from the _to_categorical_ function from keras.utils

**Comment by sekti92** [comment]
@abtExp I already change the label into int

![image](https://user-images.githubusercontent.com/14885417/52020626-eafdeb00-24e9-11e9-950b-02f8b2823fac.png)

**Comment by pavithrasv** [comment]
@sekti92 if your labels are integers, please use `sparse_categorical_crossentropy` as the loss function and remove the to_categorical conversions.

**Comment by sekti92** [comment]
@pavithrasv hi mate, already remove to_categorical and add `sparse_categorical_crossentropy ` But i got this error

> tensorflow.python.framework.errors_impl.InvalidArgumentError: Received a label value of 12 which is outside the valid range of [0, 12).  Label values: 10 10 8 1 5 9 8 11 2 4 1 8 7 7 5 7 11 2 7 5 7 5 12 7 1 2 5 2 6 1 10 1
> 	 [[Node: loss/prediction_loss/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits = SparseSoftmaxCrossEntropyWithLogits[T=DT_FLOAT, Tlabels=DT_INT64, _class=["loc:@train...s_grad/mul"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](loss/prediction_loss/Log, loss/prediction_loss/Cast)]]

**Comment by pavithrasv** [comment]
Yes.

**Comment by sekti92** [comment]
@pavithrasv there is no ID started from 0 mate. Are you kidding me?

**Comment by aashish-chaubey** [comment]
@pavithrasv I am also facing the same issue!
Did we get any solution yet?

**Comment by pavithrasv** [comment]
Sorry about the delay, can you share the code that you ran to get the above error, if possible as standalone code snippet that would help us repro the issue?

**Comment by das-ankur** [comment]
First encode all the labels using LabelEncoder then use to_categorical to represent in decode format.
`encoder = LabelEncoder()
encoder.fit(y_train)
y_train = encoder.transform(y_train)
y_test = encoder.transform(y_test)
y_train = to_categorical(y_train, num_classes=23)
y_test = to_categorical(y_test, num_classes=23)
`
