### ISSUE TITLE
AttributeError: module 'tensorflow.python.ops.losses.losses_impl' has no attribute 'ReductionV2'

### ISSUE THREAD

**Issue by leesssmile** [keras-team/keras#12118]
Would you please help in fixing my error.

I don't know how to solve this attribute error. Thanks

< Environment Spec >
Ubuntu 16.04 LTS
Keras == 2.2.4
Tensorflow-gpu == 1.12.0
tf-nightly-gpu == 1.13.0
numpy == 1.14.5

< Error message >
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from tensorflow.contrib import tensorrt as trt
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/__init__.py", line 29, in <module>
    "tensorflow_estimator.contrib.estimator"))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/tools/component_api_helper.py", line 56, in package_hook
    child_pkg = importlib.import_module(child_package_str)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/contrib/estimator/__init__.py", line 31, in <module>
    from tensorflow_estimator.contrib.estimator.python.estimator.rnn import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/contrib/estimator/python/estimator/rnn.py", line 43, in <module>
    from tensorflow_estimator.python.estimator.head import binary_class_head as binary_head_lib
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/head/binary_class_head.py", line 24, in <module>
    from tensorflow.python.keras.utils import metrics_utils
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/utils/metrics_utils.py", line 31, in <module>
    from tensorflow.python.keras.utils.losses_utils import squeeze_or_expand_dimensions
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/utils/losses_utils.py", line 144, in <module>
    weighted_losses, reduction=losses_impl.ReductionV2.SUM_OVER_BATCH_SIZE):
AttributeError: module 'tensorflow.python.ops.losses.losses_impl' has no attribute 'ReductionV2'

**Comment by AlterFalter** [comment]
I got the same error on Windows 10 during the installation process.

**Comment by sarathsairam** [comment]
AttributeError                            Traceback (most recent call last)
<ipython-input-1-41389fad42b5> in <module>()
----> 1 import tensorflow as tf

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\__init__.py in <module>()
     22 
     23 # pylint: disable=g-bad-import-order
---> 24 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     25 
     26 try:

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\__init__.py in <module>()
     53     parent_package_str='tensorflow.python',
     54     child_package_str=(
---> 55         'tensorflow_estimator.python.estimator'))
     56 del component_api_helper
     57 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\tools\component_api_helper.py in package_hook(parent_package_str, child_package_str, error_msg)
     54   parent_pkg = importlib.import_module(parent_package_str)
     55   try:
---> 56     child_pkg = importlib.import_module(child_package_str)
     57   except ImportError:
     58     if error_msg:

C:\ProgramData\Anaconda3\lib\importlib\__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_estimator\__init__.py in <module>()
      6 from __future__ import print_function as _print_function
      7 
----> 8 from tensorflow_estimator._api.v1 import estimator
      9 _names_with_underscore = []
     10 __all__ = [_s for _s in dir() if not _s.startswith('_')]

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_estimator\_api\v1\estimator\__init__.py in <module>()
      6 from __future__ import print_function as _print_function
      7 
----> 8 from tensorflow_estimator._api.v1.estimator import experimental
      9 from tensorflow_estimator._api.v1.estimator import export
     10 from tensorflow_estimator._api.v1.estimator import inputs

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_estimator\_api\v1\estimator\experimental\__init__.py in <module>()
      6 from __future__ import print_function as _print_function
      7 
----> 8 from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
      9 from tensorflow_estimator.python.estimator.canned.linear import LinearSDCA
     10 from tensorflow_estimator.python.estimator.canned.linear import linear_logit_fn_builder

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\__init__.py in <module>()
     23 from __future__ import print_function
     24 
---> 25 import tensorflow_estimator.python.estimator.estimator_lib

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\estimator_lib.py in <module>()
     20 
     21 # pylint: disable=unused-import,line-too-long,wildcard-import
---> 22 from tensorflow_estimator.python.estimator.canned.baseline import BaselineClassifier
     23 from tensorflow_estimator.python.estimator.canned.baseline import BaselineEstimator
     24 from tensorflow_estimator.python.estimator.canned.baseline import BaselineRegressor

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\canned\baseline.py in <module>()
     65 from tensorflow_estimator.python.estimator.canned import head as head_lib
     66 from tensorflow_estimator.python.estimator.canned import optimizers
---> 67 from tensorflow_estimator.python.estimator.head import head_utils
     68 from tensorflow_estimator.python.estimator.head import regression_head
     69 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\head\head_utils.py in <module>()
     21 from tensorflow.core.framework import summary_pb2
     22 from tensorflow.python.saved_model import signature_constants
---> 23 from tensorflow_estimator.python.estimator.head import binary_class_head
     24 from tensorflow_estimator.python.estimator.head import multi_class_head
     25 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\head\binary_class_head.py in <module>()
     22 from tensorflow.python.framework import ops
     23 from tensorflow.python.keras import metrics
---> 24 from tensorflow.python.keras.utils import metrics_utils
     25 from tensorflow.python.ops import array_ops
     26 from tensorflow.python.ops import control_flow_ops

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\utils\metrics_utils.py in <module>()
     29 from tensorflow.python.framework import ops
     30 from tensorflow.python.keras.utils.generic_utils import to_list
---> 31 from tensorflow.python.keras.utils.losses_utils import squeeze_or_expand_dimensions
     32 from tensorflow.python.ops import array_ops
     33 from tensorflow.python.ops import check_ops

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\utils\losses_utils.py in <module>()
    142 
    143 def _reduce_weighted_loss(
--> 144     weighted_losses, reduction=losses_impl.ReductionV2.SUM_OVER_BATCH_SIZE):
    145   """Reduces the individual weighted loss measurements."""
    146   if reduction == losses_impl.ReductionV2.NONE:

AttributeError: module 'tensorflow.python.ops.losses.losses_impl' has no attribute 'ReductionV2'

**Comment by vale910** [comment]
Same issue here

**Comment by AlterFalter** [comment]
I got around the error now with reinstalling everything, like described in this [tutorial](https://www.youtube.com/watch?v=KZFn0dvPZUQ). The error happened by me on the import:
--> import tensorflow as tf
I sadly can't really say what it was.
