### ISSUE TITLE
multigpu test_on_batch() generates wrong input shape for CuDNNLSTM

### ISSUE THREAD

**Issue by jgardin** [keras-team/keras#12295]
Hardware: 
Amazon Web Services g3.8xlarge instance 

Environment: 
Deep Learning AMI (Ubuntu) Version 21.2 (ami-0d96d570269578cd7)
using
`for TensorFlow(+Keras2) with Python3 (CUDA 9.0 and Intel MKL-DNN) ___________________________ source activate tensorflow_p36`

Reproducing script:
```
#!/usr/bin/env python
import numpy as np
import tensorflow as tf
import keras
from keras import backend as K
from keras.utils import multi_gpu_model


def return_cnn_rnn_model(
    batch_size,
    num_gpus=1.,
    lstm_filter_size=100,
    conv_filter_size=100,
    conv_kernel_size=7,
    rnn_sub_fiter_size=40,
    input_feature_dim=20,
):
    # Main toy model for variable length CNN/RNN setup
    batch_input_shape = (int(batch_size/num_gpus), None, input_feature_dim)
    #batch_input_shape = (batch_size, None, input_feature_dim)
    in_layer = keras.layers.Input(batch_shape=batch_input_shape)
    cnn_tower_1 = keras.layers.Conv1D(conv_filter_size, conv_kernel_size, padding="same")(in_layer)
    cnn_tower_1 = keras.layers.BatchNormalization()(cnn_tower_1)
    cnn_tower_1 = keras.layers.Activation('relu')(cnn_tower_1)
    #
    encode = keras.layers.CuDNNLSTM(lstm_filter_size, return_sequences=True, stateful=True)(cnn_tower_1)
    decode = keras.layers.CuDNNLSTM(lstm_filter_size, return_sequences=True, stateful=True)(encode)
    #
    cnn_tower_2 = keras.layers.Conv1D(conv_filter_size, conv_kernel_size, padding="same")(decode)
    cnn_tower_2 = keras.layers.BatchNormalization()(cnn_tower_2)
    cnn_tower_2 = keras.layers.Activation('relu')(cnn_tower_2)
    #
    sequence = keras.layers.Conv1D(1, conv_kernel_size, padding="same")(cnn_tower_2)
    sequence = keras.layers.Activation('sigmoid')(sequence)
    #
    rnn_final = keras.layers.CuDNNLSTM(1, stateful=True)(decode)
    rnn_final = keras.layers.Activation('sigmoid')(rnn_final)
    final_model = keras.models.Model(inputs=in_layer, outputs=[sequence, rnn_final])
    print(final_model.summary())
    return final_model



batch_size = 16
input_feature_dim = 20
length = 1000
adam_opt = keras.optimizers.Adam(lr=0.0001, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False)
with tf.device('/cpu:0'):
    model = return_cnn_rnn_model(batch_size=batch_size, num_gpus=2, input_feature_dim=input_feature_dim)

parallel_model = multi_gpu_model(model, gpus=2,  cpu_merge=False)
parallel_model.compile(loss='binary_crossentropy', optimizer=adam_opt, metrics=['accuracy'])

x = np.zeros((batch_size, length, input_feature_dim))
y_1 = np.zeros((batch_size, 1))
y_2 = np.zeros((batch_size, length, 1))

loss = parallel_model.train_on_batch(x, [y_2, y_1])  # This line runs okay
loss = parallel_model.test_on_batch(x, [y_2, y_1])  # This line generates an error
```

Traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/training.py", line 1256, in test_on_batch
    outputs = self.test_function(ins)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid input_h shape: [1,8,100] [1,16,100]
	 [[{{node cu_dnnlstm_1/CudnnRNN}} = CudnnRNN[T=DT_FLOAT, direction="unidirectional", dropout=0, input_mode="linear_input", is_training=true, rnn_mode="lstm", seed=87654321, seed2=0, _device="/job:localhost/replica:0/task:0/device:GPU:0"](cu_dnnlstm_1/transpose/_1251, cu_dnnlstm_1/ExpandDims/_1253, cu_dnnlstm_1/ExpandDims_1/_1255, cu_dnnlstm_1/concat_1/_1257)]]
	 [[{{node loss/activation_3_loss/Mean_3/_1313}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1464_loss/activation_3_loss/Mean_3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

What I expect to happen:
I expected `loss = parallel_model.test_on_batch(x, [y_2, y_1])` to return losses without generating a backprop gradient model update. I believe my model and inputs are correct because `loss = parallel_model.train_on_batch(x, [y_2, y_1])` generates no error message. The error seems specific to `test_on_batch`.

What actually happened:
In my understanding of the error, an incorrect shaped tensor was passed to Tensorflow

**Comment by jgardin** [comment]
To provide an update, the function `predict_on_batch()` also is not functional for the example above.
