### ISSUE TITLE
ValueError: Unknown layer:name

### ISSUE THREAD

**Issue by sheenNapoleon** [keras-team/keras#12387]
>>> tf.keras.models.load_model('images.h5')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python36\lib\site-packages
tensorflow\python\keras\_impl\keras\models.py", line 246, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python36\lib\site-packages
tensorflow\python\keras\_impl\keras\models.py", line 324, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python36\lib\site-packages
tensorflow\python\keras\_impl\keras\layers\serialization.py", line 63, in deser
alize
    printable_module_name='layer')
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python36\lib\site-packages
tensorflow\python\keras\_impl\keras\utils\generic_utils.py", line 164, in deser
alize_keras_object
    list(custom_objects.items())))
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python36\lib\site-packages
tensorflow\python\keras\_impl\keras\models.py", line 1333, in from_config
    layer = layer_module.deserialize(conf, custom_objects=custom_objects)
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python36\lib\site-packages
tensorflow\python\keras\_impl\keras\layers\serialization.py", line 63, in deser
alize
    printable_module_name='layer')
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python36\lib\site-packages
tensorflow\python\keras\_impl\keras\utils\generic_utils.py", line 184, in deser
alize_keras_object
    function_name)
ValueError: Unknown layer:name
>>> tf.keras.models.load_model()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: load_model() missing 1 required positional argument: 'filepath'
>>> tf.keras.models.load_model('images.h5')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python36\lib\site-packages
tensorflow\python\keras\_impl\keras\models.py", line 246, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python36\lib\site-packages
tensorflow\python\keras\_impl\keras\models.py", line 324, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python36\lib\site-packages
tensorflow\python\keras\_impl\keras\layers\serialization.py", line 63, in deser
alize
    printable_module_name='layer')
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python36\lib\site-packages
tensorflow\python\keras\_impl\keras\utils\generic_utils.py", line 164, in deser
alize_keras_object
    list(custom_objects.items())))
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python36\lib\site-packages
tensorflow\python\keras\_impl\keras\models.py", line 1333, in from_config
    layer = layer_module.deserialize(conf, custom_objects=custom_objects)
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python36\lib\site-packages
tensorflow\python\keras\_impl\keras\layers\serialization.py", line 63, in deser
alize
    printable_module_name='layer')
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python36\lib\site-packages
tensorflow\python\keras\_impl\keras\utils\generic_utils.py", line 184, in deser
alize_keras_object
    function_name)
ValueError: Unknown layer:name

i am using keras 2.2.4

**Comment by silvadenisaraujo** [comment]
Hi @sheenNapoleon could you please share the code you did ?

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
