### ISSUE TITLE
[1D CNN - Keras] Not sure how to feed my data into the model

### ISSUE THREAD

**Issue by Spiderixius** [keras-team/keras#12447]
**Background**
Hello all. I am new to 1D CNN's and I am trying to feed my data to a 1D CNN model. The following is my data (Sensor data from a UWB device, data is in the below gist):
```
Number of columns in the dataframe: 53 
Number of rows in the dataframe: 615
```

The last column in the dataframe is the labels for each row. The data represents the amount of people the sensor is detecting, which currently only has two labels (1 person or 2 persons) and each row in the data represents a 1 second recoding. So goal is to create a model that is capable of receiving some data and saying whether this is data for 1 or 2 persons.

**Code & Data**
The source code and data can be found at the following gist: https://gist.github.com/Spiderixius/29e82017f6094da1e5d997726e85d364 

**The error I am having:**
I get the following error:
```python
Traceback (most recent call last):
  File "/home/spider/Documents/GithubProjects/OccupancySensing_Code/src/MachineLearning/CNN_1D.py", line 151, in <module>
    verbose=1)
  File "/home/spider/PycharmProjects/PeopleCounting/venv3/lib/python3.6/site-packages/keras/engine/training.py", line 952, in fit
    batch_size=batch_size)
  File "/home/spider/PycharmProjects/PeopleCounting/venv3/lib/python3.6/site-packages/keras/engine/training.py", line 789, in _standardize_user_data
    exception_prefix='target')
  File "/home/spider/PycharmProjects/PeopleCounting/venv3/lib/python3.6/site-packages/keras/engine/training_utils.py", line 138, in standardize_input_data
    str(data_shape))
ValueError: Error when checking target: expected dense_1 to have shape (2,) but got array with shape (1,)
```
The error points to:
```python
# Enable validation to use ModelCheckpoint and EarlyStopping callbacks.
history = model_m.fit(X_train,
                      y_train,
                      batch_size=BATCH_SIZE,
                      epochs=EPOCHS,
                      callbacks=callbacks_list,
                      validation_split=0.2,
                      verbose=1)
```

**Comment by goodyduru** [comment]
This

model_m.add(Dense(2, activation='softmax'))

should be

model_m.add(Dense(1, activation='softmax'))

**Comment by Spiderixius** [comment]
Hey. I have two classes. Is the output 0 indexed?

**Comment by goodyduru** [comment]
It's not two classes, two classes would mean two columns in your y_train. Your y_train only contains 1 column. Here is how you created your y data from which your y_train was derived.

y = df.iloc[:, 52].values

That would mean 1 column. Your y_train should have a shape of (batch_size, 2) for your code to work. Currently it is (batch_size, 1).

**Comment by Spiderixius** [comment]
Aha I see. It is because I have two labels and I understood it as two classes for the output layer. Thanks goodyduru.

**Comment by goodyduru** [comment]
You are welcome @Spiderixius.
