### ISSUE TITLE
AttributeError: 'Sequential' object has no attribute 'total_loss'

### ISSUE THREAD

**Issue by TrucCodyHo** [keras-team/keras#12456]
I am using tensorflow-gpu 1.13.1 and Keras 2.2.4, both of which are up to date.  I am trying to make a binary classifier to classify files as benign or malicious, however I keep getting an error.  

Error causing code recreated in a much smaller file:
```
import numpy as np
import tensorflow as tf

def createModel():
    model = tf.keras.models.Sequential()
    model.add(tf.keras.layers.Dense(5, activation=tf.nn.relu))
    model.add(tf.keras.layers.Dense(5, activation=tf.nn.relu))
    model.add(tf.keras.layers.Dense(1, activation=tf.nn.sigmoid))
    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

def array_generator():
    yield np.array([0.1,0.2,0.3,0.4,0.5]), np.array([1])

model=createModel()
model.fit_generator(array_generator(), epochs=5, steps_per_epoch=5)
```

Error: 
```
WARNING:tensorflow:From C:\Users\Cody\AppData\Local\conda\conda\envs\emberenv\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "C:/Users/Cody/Desktop/synopsys/venv/test.py", line 18, in <module>
    model.fit_generator(array_generator(), epochs=5, steps_per_epoch=5)
  File "C:\Users\Cody\AppData\Local\conda\conda\envs\emberenv\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\Cody\AppData\Local\conda\conda\envs\emberenv\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 125, in model_iteration
    model, mode, class_weight=class_weight)
  File "C:\Users\Cody\AppData\Local\conda\conda\envs\emberenv\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 427, in _make_execution_function
    model._make_fit_function()
  File "C:\Users\Cody\AppData\Local\conda\conda\envs\emberenv\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1926, in _make_fit_function
    '_fit_function', [self.total_loss] + metrics_tensors)
AttributeError: 'Sequential' object has no attribute 'total_loss'
```

Source code (no one should need this, but it's here if you care)
```
import tensorflow as tf
import numpy as np
import ember
import random

X_train, y_train, X_test, y_test = ember.read_vectorized_features("C:\\Users\Cody\Desktop\synopsys\data\ember")
metadata_dataframe = ember.read_metadata("C:\\Users\Cody\Desktop\synopsys\data\ember")

#load training set
def loadTrainSet(X_train, y_train, number):
    x = np.split(X_train, 100)
    y = np.split(y_train, 100)
    features = tf.convert_to_tensor(x[number], dtype=tf.float32)
    labels = tf.convert_to_tensor(y[number], dtype=tf.float32)
    return features, labels

#load testing set
def loadTestSet():
    X_test_tf = tf.convert_to_tensor(X_test, np.float32)
    y_test_tf = tf.convert_to_tensor(y_test, np.float32)
    return X_test_tf, y_test_tf

#create compiled keras model
def createModel():
    model = tf.keras.models.Sequential()
    #ADD L2 REGULARIZATION LATER
    model.add(tf.keras.layers.Dense(7351, activation=tf.nn.relu))
    model.add(tf.keras.layers.Dropout(0.2))
    model.add(tf.keras.layers.Dense(4096, activation=tf.nn.relu))
    model.add(tf.keras.layers.Dropout(0.2))
    model.add(tf.keras.layers.Dense(4096, activation=tf.nn.relu))
    model.add(tf.keras.layers.Dropout(0.2))
    model.add(tf.keras.layers.Dense(4096, activation=tf.nn.relu))
    model.add(tf.keras.layers.Dropout(0.2))
    model.add(tf.keras.layers.Dense(2048, activation=tf.nn.relu))
    model.add(tf.keras.layers.Dropout(0.2))
    model.add(tf.keras.layers.Dense(2048, activation=tf.nn.relu))
    model.add(tf.keras.layers.Dropout(0.2))
    model.add(tf.keras.layers.Dense(2048, activation=tf.nn.relu))
    model.add(tf.keras.layers.Dropout(0.2))
    model.add(tf.keras.layers.Dense(1024, activation=tf.nn.relu))
    model.add(tf.keras.layers.Dropout(0.2))
    model.add(tf.keras.layers.Dense(1024, activation=tf.nn.relu))
    model.add(tf.keras.layers.Dropout(0.2))
    model.add(tf.keras.layers.Dense(1024, activation=tf.nn.relu))
    model.add(tf.keras.layers.Dropout(0.2))
    model.add(tf.keras.layers.Dense(1024, activation=tf.nn.relu))
    model.add(tf.keras.layers.Dropout(0.2))
    model.add(tf.keras.layers.Dense(1, activation=tf.nn.sigmoid))
    #adam metrhod for stochastic gradient descent
    model.compile(optimizer='adam',
                  loss='mean_squared_error',
                  metrics=['accuracy'])
    return model

def generate_arrays(features, labels, batch_size):
    print('generate worked')
    batch_features=np.zeros((batch_size, 7351), dtype=np.float32)
    batch_labels=np.zeros((batch_size, 1), dtype=np.float32)
    while True:
        for i in range(batch_size):
            print('starting to work')
            index=random.choice(900000,1)
            print('random worked', index)
            batch_features=X_train[index]
            print('features worked')
            batch_labels=y_train[index]
            print('labels worked')
        print('it all worked until here')
        yield batch_features, batch_labels

print('creating model')
model=createModel()
print('training model')
model.fit_generator(generate_arrays(X_train, y_train, 500), epochs=10, steps_per_epoch=1800, initial_epoch=0)
print('testing model')
X_test_tf, y_test_tf = loadTestSet()
model.evaluate(X_test_tf, y_test_tf)
```

I have been tearing my hair out for hours trying to figure this out.  Any help is greatly appreciated.

**Comment by ggyppsyy** [comment]
I am having the same problem on Google Colab, and it can also be recreated this way:

```
import numpy as np
import tensorflow as tf

class MyModel(tf.keras.Model):
    def __init__(self):
      super(MyModel, self).__init__(name='MyModel')
      self.dense1 = tf.keras.layers.Dense(5, activation=tf.nn.relu)
      self.dense2 = tf.keras.layers.Dense(5, activation=tf.nn.relu)
      self.dense3 = tf.keras.layers.Dense(5, activation=tf.nn.sigmoid)
      
    def call(self, inputs, training=False):
      return dense3(dense2(dense1(inputs)))

def array_generator():
    yield np.array([0.1,0.2,0.3,0.4,0.5]), np.array([1])

model=MyModel()
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit_generator(array_generator(), epochs=5, steps_per_epoch=5)

**Comment by Umraiz** [comment]
Following this issue.

**Comment by Umraiz** [comment]
import tensorflow.keras
import numpy as np
from tensorflow.keras.applications import VGG16
vgg_conv = VGG16(weights='imagenet',
                  include_top=False,
                  input_shape=(625, 512, 3))
# Freeze all the layers
for layer in vgg_conv.layers[:]:
    layer.trainable = False
# Check the trainable status of the individual layers
for layer in vgg_conv.layers:
    print(layer, layer.trainable)

from tensorflow.keras import models, layers, optimizers
#from keras import layers
#from keras import optimizers

# Create the model
model = models.Sequential()

# Add the vgg convolutional base model
model.add(vgg_conv)

# Add new layers
model.add(layers.Flatten())
model.add(layers.Dense(100, activation='relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(1  , activation='linear'))

# Show a summary of the model. Check the number of trainable parameters
model.summary()

model.compile(loss='mean_squared_error', optimizer='adam')

**Comment by ggyppsyy** [comment]
Yeah, well, if anyone was wondering what the problem with TrucCodyHo's original question was, I feel like it has to do with directly using the generator as input. You should probably use `tf.data.Dataset.from_generator`
[https://www.tensorflow.org/api_docs/python/tf/data/Dataset#from_generator](url)
The answer to this stackoverflow question is also relevant
[https://stackoverflow.com/questions/39325275/how-to-train-tensorflow-network-using-a-generator-to-produce-inputs#39331675](url)

**Comment by TrucCodyHo** [comment]
The example provided in the documentation [here ](https://www.tensorflow.org/api_docs/python/tf/keras/models/Model#fit_generator) uses the fit_generator function in the exact same way I have here, by creating a generator that yields some values from a numpy array.  Why do I need to use tf.data.Dataset.from_generator?

**Comment by ggyppsyy** [comment]
Oh, I missed that.  Well, I am no expert, but, first of all, your loss and the last layer of your model are incompatible.  For `'sparse_categorical_crossentropy'` you should have a dense layer with the number of categories and a softmax activation. If you want to use the last layer you have in the example above, you should probably use `tf.keras.losses.BinaryCrossentropy()`. 

Also, in the mini-example you give above, your generator is not creating the correctly shaped inputs and labels. The inputs should have the shape [_BATCHSIZE_, 5] for the mini-example above, and labels should similarly take into account the batch dimension.

That said, I was only able to get the mini-example working with eager execution enabled, but at least that is a start for you to do your own debugging. Also you might have better luck asking about this on StackExchange or the tensorflow github page, because from what I understand, tf.keras and the Keras library are not identical.

``````import numpy as np
import tensorflow as tf
tf.enable_eager_execution()

def createModel():
    model = tf.keras.models.Sequential()
    model.add(tf.keras.layers.Dense(5, activation=tf.nn.relu))
    model.add(tf.keras.layers.Dense(5, activation=tf.nn.relu))
    model.add(tf.keras.layers.Dense(1, activation='sigmoid'))
    model.compile(optimizer='adam',
                  loss=tf.keras.losses.BinaryCrossentropy(),
                  metrics=['accuracy'])
    return model

def array_generator():
    yield np.expand_dims(np.array([0.1,0.2,0.3,0.4,0.5]),axis=0),np.expand_dims(np.array([1]),axis=0)
    
model=createModel()
model.fit_generator(array_generator(), epochs=1, steps_per_epoch=1)

**Comment by ohnozzy** [comment]
The input shape of the first layer has to be specified.
```
import numpy as np
import tensorflow as tf

def createModel():
    model = tf.keras.models.Sequential()
    model.add(tf.keras.layers.Dense(5, input_shape=(5,), activation=tf.nn.relu))
    model.add(tf.keras.layers.Dense(5, activation=tf.nn.relu))
    model.add(tf.keras.layers.Dense(1, activation=tf.nn.sigmoid))
    model.compile(optimizer='adam',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])
    return model

def array_generator():
    yield np.array([[0.1,0.2,0.3,0.4,0.5]]), np.array([1.0])  #input shape of the example is also wrong.

model=createModel()
model.fit_generator(array_generator(), epochs=5, steps_per_epoch=5)
```

**Comment by ymodak** [comment]
Defining input shape for the first layer solves this problem. Thanks!
https://keras.io/getting-started/sequential-model-guide/#specifying-the-input-shape

**Comment by maaxnaax** [comment]
This is the only Keras Rstudio that has ever worked for me:
https://irudnyts.github.io/custom-set-up-of-keras-and-tensorflow-for-r-and-python/

It sorted out all attribute problems

**Comment by dibyacharya** [comment]
AttributeError: 'Sequential' object has no attribute 'version'

i have got this type of error ...please anyone tell me the solution
