### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_inbound_nodes'

### ISSUE THREAD

**Issue by yangchangli** [keras-team/keras#12468]
Hello,
Can anyone help me understand this error please?

sentence_input = Input(shape=(MAX_TEXT_LENGTH,), dtype='int32')
embedded_sequences = embedding_layer(sentence_input)
print("embedded_sequences_type",type(embedded_sequences))#<class 'tensorflow.python.framework.ops.Tensor'>

POS_vector_tensor = tf.convert_to_tensor(POS_vector,tf.float32)
#POS_vector_tensor = Lambda(lambda x:tf.convert_to_tensor(x, tf.float32))(POS_vector)#List(POS_vector)->tensor
print("Type_POS_vector_tensor",type(POS_vector_tensor))#<class 'tensorflow.python.framework.ops.Tensor'>
a = []
a.append(POS_vector_tensor)
a.append(embedded_sequences)
concatenate = Lambda(lambda x :K.concatenate(x,-1))(a)
print("concatenate_type",type(concatenate))#<class 'tensorflow.python.framework.ops.Tensor'>

l_lstm = Bidirectional(GRU(50, return_sequences=False))(concatenate)
preds = Dense(5, activation='softmax')(l_lstm)
model = Model(sentence_input, preds)

This code has an error below：  ErrorErrorErrorErrorErrorErrorErrorErrorErrorErrorErrorErrorErrorErrorErrorErrorErrorErrorErrorErrorError
Traceback (most recent call last):
  File "C:\Users\ycl\Desktop\sentimentanalysisLSTM+POS.py", line 264, in <module>
    model = Model(sentence_input, preds)
  File "D:\software\Anaconda\envs\tensorflow-gpu\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "D:\software\Anaconda\envs\tensorflow-gpu\lib\site-packages\keras\engine\network.py", line 93, in __init__
    self._init_graph_network(*args, **kwargs)
  File "D:\software\Anaconda\envs\tensorflow-gpu\lib\site-packages\keras\engine\network.py", line 231, in _init_graph_network
    self.inputs, self.outputs)
  File "D:\software\Anaconda\envs\tensorflow-gpu\lib\site-packages\keras\engine\network.py", line 1366, in _map_graph_network
    tensor_index=tensor_index)
  File "D:\software\Anaconda\envs\tensorflow-gpu\lib\site-packages\keras\engine\network.py", line 1353, in build_map
    node_index, tensor_index)
  File "D:\software\Anaconda\envs\tensorflow-gpu\lib\site-packages\keras\engine\network.py", line 1353, in build_map
    node_index, tensor_index)
  File "D:\software\Anaconda\envs\tensorflow-gpu\lib\site-packages\keras\engine\network.py", line 1353, in build_map
    node_index, tensor_index)
  File "D:\software\Anaconda\envs\tensorflow-gpu\lib\site-packages\keras\engine\network.py", line 1325, in build_map
    node = layer._inbound_nodes[node_index]
AttributeError: 'NoneType' object has no attribute '_inbound_nodes'
##############################
First I guess is“POS_vector_tensor = tf.convert_to_tensor(POS_vector,tf.float32)“ is worry
So ，i change it to "POS_vector_tensor = Lambda(lambda x:tf.convert_to_tensor(x, tf.float32))"
But  a worry arise
##############################
Traceback (most recent call last):
  File "D:\software\Anaconda\envs\tensorflow-gpu\lib\site-packages\keras\engine\base_layer.py", line 279, in assert_input_compatibility
    K.is_keras_tensor(x)
  File "D:\software\Anaconda\envs\tensorflow-gpu\lib\site-packages\keras\backend\tensorflow_backend.py", line 474, in is_keras_tensor
    str(type(x)) + '`. '
ValueError: Unexpectedly found an instance of type `<class 'list'>`. Expected a symbolic tensor instance.

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\ycl\Desktop\sentimentanalysisLSTM+POS.py", line 251, in <module>
    POS_vector_tensor =Lambda(lambda x:tf.convert_to_tensor(x, tf.float32))(POS_vector)#List————>tensor
  File "D:\software\Anaconda\envs\tensorflow-gpu\lib\site-packages\keras\engine\base_layer.py", line 414, in __call__
    self.assert_input_compatibility(inputs)
  File "D:\software\Anaconda\envs\tensorflow-gpu\lib\site-packages\keras\engine\base_layer.py", line 285, in assert_input_compatibility
    str(inputs) + '. All inputs to the layer '
ValueError: Layer lambda_1 was called with an input that isn't a symbolic tensor. Received type: <class 'list'>. Full input: [[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],..................................]]]
. All inputs to the layer should be tensors.

......................................................
How should I do

**Comment by yangchangli** [comment]
Help！Help！Help！Help！Help！Help！。。。。。
