### ISSUE TITLE
Loading modal weights fails when some layers were not trainable during training 

### ISSUE THREAD

**Issue by thorstenwagner** [keras-team/keras#12470]
Here is the script to reproduce the problem:
```python
from keras.utils import Sequence
from keras.layers import Conv2D, Input, MaxPooling2D, BatchNormalization, Dense, Flatten
from keras.layers.advanced_activations import LeakyReLU
from keras.models import Model
from keras.optimizers import Adam
from keras.callbacks import ModelCheckpoint
import multiprocessing
import numpy as np
import time
import os
class EasyGenerator(Sequence):

    def __init__(self,name):
        self.labels = np.random.random((100))
        self.labels[self.labels>0.5] = 1
        self.labels[self.labels<=0.5] = 0
        self.name = name

    def __len__(self):
        return 10

    def __getitem__(self, idx):
        np.random.seed(idx)
        time.sleep(1)
        x = np.random.rand(1, 50, 50, 1)
        y = self.labels[idx]
        return x,[y]


class EasyNet(object):
    def __init__(self):

        input_image = Input(shape=(50, 50,1))

        # Layer 1
        x = Conv2D(4, (3, 3), strides=(1, 1), padding='same', name='conv_1', use_bias=False)(input_image)
        x = BatchNormalization(name='norm_1')(x)
        x = LeakyReLU(alpha=0.1)(x)
        x = MaxPooling2D(pool_size=(2, 2))(x)

        # Layer 2
        x = Conv2D(8, (3, 3), strides=(1, 1), padding='same', name='conv_2', use_bias=False)(x)
        x = BatchNormalization(name='norm_2')(x)
        x = LeakyReLU(alpha=0.1)(x)
        x = MaxPooling2D(pool_size=(2, 2))(x)

        model_nested = Model(input_image, x)

        output = Flatten()(model_nested(input_image))
        output = Dense(10, activation="relu", name="denseL1")(output)
        output = Dense(1, activation='sigmoid', name='denseL2')(output)

        self.model = Model(input_image, output)
        self.model.summary()

    def train(self):
        train_generator = EasyGenerator("train")
        valid_generator = EasyGenerator("valid")

        checkpoint = ModelCheckpoint(
            "model.h5",
            monitor="loss",
            verbose=1,
            save_best_only=True,
            save_weights_only=False,
            mode="min",
            period=1,
        )

        self.model.fit_generator(generator=train_generator,
                                 validation_data=valid_generator,
                                 workers=multiprocessing.cpu_count()//2,
                                 epochs=2,
                                 callbacks=[checkpoint],
                                 max_queue_size=multiprocessing.cpu_count(),
                                 use_multiprocessing=True)

def init():
    net = EasyNet()


    if os.path.exists("model.h5"):
        print("Load model")
        net.model.load_weights("model.h5")

    for layer_index, layer in enumerate(net.model.get_layer('model_1').layers):
        if "conv" in layer.name:
            layer.trainable = False



    optimizer = Adam(lr=10 ** -4, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
    net.model.compile(optimizer=optimizer,
                      loss='binary_crossentropy')
    net.train()

def _main_():
    multiprocessing.set_start_method('spawn')
    init()


if __name__ == '__main__':
    _main_()
```

You have to run it twice. The first time it creates the model.  The second time it will try to load it to initalize the network.

I get the following exception:

```
Traceback (most recent call last):
  File "EasyNet.py", line 104, in <module>
    _main_()
  File "EasyNet.py", line 100, in _main_
    init()
  File "EasyNet.py", line 85, in init
    net.model.load_weights("model.h5")
  File "/home/twagner/Applications/miniconda3/envs/cryolo_python36/lib/python3.6/site-packages/keras/engine/network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "/home/twagner/Applications/miniconda3/envs/cryolo_python36/lib/python3.6/site-packages/keras/engine/saving.py", line 1045, in load_weights_from_hdf5_group
    reshape=reshape)
  File "/home/twagner/Applications/miniconda3/envs/cryolo_python36/lib/python3.6/site-packages/keras/engine/saving.py", line 682, in preprocess_weights_for_loading
    weights = convert_nested_model(weights)
  File "/home/twagner/Applications/miniconda3/envs/cryolo_python36/lib/python3.6/site-packages/keras/engine/saving.py", line 658, in convert_nested_model
    original_backend=original_backend))
  File "/home/twagner/Applications/miniconda3/envs/cryolo_python36/lib/python3.6/site-packages/keras/engine/saving.py", line 801, in preprocess_weights_for_loading
    weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
  File "/home/twagner/Applications/miniconda3/envs/cryolo_python36/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 575, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/home/twagner/Applications/miniconda3/envs/cryolo_python36/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: axes don't match array
```

You can work around this problem in the second run by permute the order of loading the model weights and freezing the layers in init().
Instead of
```python
    if os.path.exists("model.h5"):
        print("Load model")
        net.model.load_weights("model.h5")

    for layer_index, layer in enumerate(net.model.get_layer('model_1').layers):
        if "conv" in layer.name:
            layer.trainable = False
```

you can use
```python

    for layer_index, layer in enumerate(net.model.get_layer('model_1').layers):
        if "conv" in layer.name:
            layer.trainable = False

    if os.path.exists("model.h5"):
        print("Load model")
        net.model.load_weights("model.h5")

```

I'm using Keras 2.2.4 and tensorflow 1.10.1.

Best,
Thorsten

**Comment by thorstenwagner** [comment]
Is someone able to reproduce?

**Comment by NotF404** [comment]
hi， same problem, how do u fix it

**Comment by thorstenwagner** [comment]
With this workaround:
```
        try:
            self.model.load_weights(weight_path)

            ###############################
            # If wanted, only train the last two layers of the network.
            ###############################
            if self.fine_tune:
                for layer_index, layer in enumerate(self.model.layers):
                    if layer.name != "conv_23" and layer.name != "model_1":
                        layer.trainable = False

                for layer_index, layer in enumerate(self.model.get_layer('model_1').layers):
                    if layer.name != "conv_22":
                        layer.trainable = False
        except ValueError:
            ###############################
            # This is a workaround for a keras bug loading weights from nested models with fixed layers
            ###############################
            for layer_index, layer in enumerate(self.model.layers):
                if layer.name != "conv_23" and layer.name != "model_1":
                    layer.trainable = False

            for layer_index, layer in enumerate(self.model.get_layer('model_1').layers):
                if layer.name != "conv_22":
                    layer.trainable = False
```
