### ISSUE TITLE
Training LSMT with Multi GPU failed 

### ISSUE THREAD

**Issue by mastersg7** [keras-team/keras#12522]
I am trying to train an lstm model on multiple gpus (2). 
However I get a InvalidArgumentError. It seems not able to perform a certain operation on the second model. I dont quite undertstand the error. Is it not finding the gpu? And what is the supported kernel it is talking about?

    Traceback (most recent call last):
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
        return fn(*args)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1293, in _run_fn
        self._extend_graph()
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1354, in _extend_graph
        self._session, graph_def.SerializeToString(), status)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
        c_api.TF_GetCode(self.status.status))
    tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'training/Adam/gradients/replica_1/model_1/lstm_1/while/add_7_grad/BroadcastGradientArgs/f_acc': Could not satisfy explicit device specification '/device:GPU:1' because no supported kernel for GPU devices is available.
    Colocation Debug Info:
    Colocation group had the following types and devices:
    Tile: CPU
    Maximum: GPU CPU
    Minimum: GPU CPU
    TanhGrad: GPU CPU
    Shape: GPU CPU
    Sum: GPU CPU
    Fill: GPU CPU
    Reshape: GPU CPU
    Mul: GPU CPU
    Tanh: GPU CPU
    Const: GPU CPU
    StackPushV2: GPU CPU
    Select: GPU CPU
    StackV2: GPU CPU
    Enter: GPU CPU
    BroadcastGradientArgs: GPU CPU
    LessEqual: GPU CPU
    GreaterEqual: GPU CPU
    Add: GPU CPU
    ZerosLike: GPU CPU
    StackPopV2: GPU CPU
    AddN: GPU CPU
             [[Node: training/Adam/gradients/replica_1/model_1/lstm_1/while/add_7_grad/BroadcastGradientArgs/f_acc = StackV2[_class=["loc:@replica_1/model_1/lstm_1/while/add_7"], elem_type=DT_INT32, stack_name="", _device="/device:GPU:1"](training/Adam/gradients/replica_1/model_1/lstm_1/while/add_7_grad/BroadcastGradientArgs/f_acc/max_size)]]
    
    During handling of the above exception, another exception occurred:
    
```
    Traceback (most recent call last):
      File "tpe_predictor_lstm_insy_gpus.py", line 1013, in <module>
        filename=args.filename)
      File "tpe_predictor_lstm_insy_gpus.py", line 961, in run_train_test
        tpenn.experiment(n_repeats=1, save=True, predict_test=True, predict_train=False, post_train=True, debugging=True)
      File "tpe_predictor_lstm_insy_gpus.py", line 865, in experiment
        val=True, val_xdata=self.x_test, val_ydata=list(self.reshape_test(self.y_test))
      File "tpe_predictor_lstm_insy_gpus.py", line 299, in training
        callbacks=callbacks_list
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1705, in fit
        validation_steps=validation_steps)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1235, in _fit_loop
        outs = f(ins_batch)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2476, in __call__
        session = get_session()
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 192, in get_session
        [tf.is_variable_initialized(v) for v in candidate_vars])
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
        run_metadata_ptr)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
        feed_dict_tensor, options, run_metadata)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
        options, run_metadata)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
        raise type(e)(node_def, op, message)
    tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'training/Adam/gradients/replica_1/model_1/lstm_1/while/add_7_grad/BroadcastGradientArgs/f_acc': Could not satisfy explicit device specification '/device:GPU:1' because no supported kernel for GPU devices is available.
    Colocation Debug Info:
    Colocation group had the following types and devices:
    Tile: CPU
    Maximum: GPU CPU
    Minimum: GPU CPU
    TanhGrad: GPU CPU
    Shape: GPU CPU
    Sum: GPU CPU
    Fill: GPU CPU
    Reshape: GPU CPU
    Mul: GPU CPU
    Tanh: GPU CPU
    Const: GPU CPU
    StackPushV2: GPU CPU
    Select: GPU CPU
    StackV2: GPU CPU
    Enter: GPU CPU
    BroadcastGradientArgs: GPU CPU
    LessEqual: GPU CPU
    GreaterEqual: GPU CPU
    Add: GPU CPU
    ZerosLike: GPU CPU
    StackPopV2: GPU CPU
    AddN: GPU CPU
             [[Node: training/Adam/gradients/replica_1/model_1/lstm_1/while/add_7_grad/BroadcastGradientArgs/f_acc = StackV2[_class=["loc:@replica_1/model_1/lstm_1/while/add_7"], elem_type=DT_INT32, stack_name="", _device="/device:GPU:1"](training/Adam/gradients/replica_1/model_1/lstm_1/while/add_7_grad/BroadcastGradientArgs/f_acc/max_size)]]
    
    Caused by op 'training/Adam/gradients/replica_1/model_1/lstm_1/while/add_7_grad/BroadcastGradientArgs/f_acc', defined at:
      File "tpe_predictor_lstm_insy_gpus.py", line 1013, in <module>
        filename=args.filename)
      File "tpe_predictor_lstm_insy_gpus.py", line 961, in run_train_test
        tpenn.experiment(n_repeats=1, save=True, predict_test=True, predict_train=False, post_train=True, debugging=True)
      File "tpe_predictor_lstm_insy_gpus.py", line 865, in experiment
        val=True, val_xdata=self.x_test, val_ydata=list(self.reshape_test(self.y_test))
      File "tpe_predictor_lstm_insy_gpus.py", line 299, in training
        callbacks=callbacks_list
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1682, in fit
        self._make_train_function()
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/keras/engine/training.py", line 990, in _make_train_function
        loss=self.total_loss)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
        return func(*args, **kwargs)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/keras/optimizers.py", line 445, in get_updates
        grads = self.get_gradients(loss, params)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/keras/optimizers.py", line 78, in get_gradients
        grads = K.gradients(loss, params)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2515, in gradients
        return tf.gradients(loss, variables, colocate_gradients_with_ops=True)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 581, in gradients
        grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 353, in _MaybeCompile
        return grad_fn()  # Exit early
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 581, in <lambda>
        grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_grad.py", line 714, in _AddGrad
        rx, ry = gen_array_ops._broadcast_gradient_args(sx, sy)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 532, in _broadcast_gradient_args
        "BroadcastGradientArgs", s0=s0, s1=s1, name=name)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
        op_def=op_def)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
        op_def=op_def)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1482, in __init__
        self._control_flow_context.AddOp(self)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2188, in AddOp
        self._AddOpInternal(op)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2211, in _AddOpInternal
        real_x = self.AddValue(x)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2144, in AddValue
        real_val = grad_ctxt.grad_state.GetRealValue(val)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1012, in GetRealValue
        history_value = cur_grad_state.AddForwardAccumulator(cur_value)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 870, in AddForwardAccumulator
        name="f_acc")
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3533, in _stack_v2
        stack_name=stack_name, name=name)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
        op_def=op_def)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
        op_def=op_def)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
        self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
    
    ...which was originally created as op 'replica_1/model_1/lstm_1/while/add_7', defined at:
      File "tpe_predictor_lstm_insy_gpus.py", line 1013, in <module>
        filename=args.filename)
    [elided 0 identical lines from previous traceback]
      File "tpe_predictor_lstm_insy_gpus.py", line 961, in run_train_test
        tpenn.experiment(n_repeats=1, save=True, predict_test=True, predict_train=False, post_train=True, debugging=True)
      File "tpe_predictor_lstm_insy_gpus.py", line 852, in experiment
        compiled_network = self.compile_model(network_structure, self.mse, self.opt, summ=True)
      File "tpe_predictor_lstm_insy_gpus.py", line 263, in compile_model
        parallel_model = multi_gpu_model(model, gpus=n_gpus)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/keras/utils/multi_gpu_utils.py", line 175, in multi_gpu_model
        outputs = model(inputs)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 619, in __call__
        output = self.call(inputs, **kwargs)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 2085, in call
        output_tensors, _, _ = self.run_internal_graph(inputs, masks)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 2236, in run_internal_graph
        output_tensors = _to_list(layer.call(computed_tensor, **kwargs))
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/keras/layers/recurrent.py", line 2151, in call
        initial_state=initial_state)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/keras/layers/recurrent.py", line 608, in call
        input_length=timesteps)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2767, in rnn
        swap_memory=True)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2816, in while_loop
        result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2640, in BuildLoop
        pred, body, original_loop_vars, loop_vars, shape_invariants)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2590, in _BuildLoop
        body_result = body(*packed_vars_for_body)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2726, in _step
        tuple(constants))
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/keras/layers/recurrent.py", line 599, in step
        return self.cell.call(inputs, states, **kwargs)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/keras/layers/recurrent.py", line 1947, in call
        self.recurrent_kernel_o))
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/keras/activations.py", line 84, in hard_sigmoid
        return K.hard_sigmoid(x)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 3100, in hard_sigmoid
        x = (0.2 * x) + 0.5
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 894, in binary_op_wrapper
        return func(x, y, name=name)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 183, in add
        "Add", x=x, y=y, name=name)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
        op_def=op_def)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
        op_def=op_def)
      File "/home/nfs/msakyigyinae/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
        self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
    
    InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'training/Adam/gradients/replica_1/model_1/lstm_1/while/add_7_grad/BroadcastGradientArgs/f_acc': Could not satisfy explicit device specification '/device:GPU:1' because no supported kernel for GPU devices is available.
    Colocation Debug Info:
    Colocation group had the following types and devices:
    Tile: CPU
    Maximum: GPU CPU
    Minimum: GPU CPU
    TanhGrad: GPU CPU
    Shape: GPU CPU
    Sum: GPU CPU
    Fill: GPU CPU
    Reshape: GPU CPU
    Mul: GPU CPU
    Tanh: GPU CPU
    Const: GPU CPU
    StackPushV2: GPU CPU
    Select: GPU CPU
    StackV2: GPU CPU
    Enter: GPU CPU
    BroadcastGradientArgs: GPU CPU
    LessEqual: GPU CPU
    GreaterEqual: GPU CPU
    Add: GPU CPU
    ZerosLike: GPU CPU
    StackPopV2: GPU CPU
    AddN: GPU CPU
             [[Node: training/Adam/gradients/replica_1/model_1/lstm_1/while/add_7_grad/BroadcastGradientArgs/f_acc = StackV2[_class=["loc:@replica_1/model_1/lstm_1/while/add_7"], elem_type=DT_INT32, stack_name="", _device="/device:GPU:1"](training/Adam/gradients/replica_1/model_1/lstm_1/while/add_7_grad/BroadcastGradientArgs/f_acc/max_size)]]
```

**Comment by pusj** [comment]
Hello @mastersg7  ,

Can you add your code?
