### ISSUE TITLE
Python COM AttributeError: 'NoneType' object has no attribute 'write'

### ISSUE THREAD

**Issue by lileiNPU** [keras-team/keras#12537]
Hello everyone,
  I am new to python. I am getting an error when I call a Python-generated COM component in the VB.net language (import keras in the COM component), but when I comment out the import keras in the component, the program works fine. How can I solve this problem?

Python:
import pythoncom
#must install pipywin32
class PythonUtilities2:
    _reg_clsctx_ = pythoncom.CLSCTX_LOCAL_SERVER
    _public_methods_ = ['SplitString']
    _reg_progid_ = 'PythonDemos2.Utilities'

    #use "print (pythoncom.CreateGuid())" generate a new clsid
    #print(pythoncom.CreateGuid())
    _reg_clsid_ = '{CF48ABB5-D7F9-4BBB-9B75-3ECFFDE92A93}'

    def SplitString(self, val):
        import math
        import keras
        print(val)
        return val

if __name__=='__main__':
    print ('Registering COM server...')
    import win32com.server.register
    win32com.server.register.UseCommandLine(PythonUtilities2)

VB.net:
 Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Dim PythonUtils = CreateObject("PythonDemos2.Utilities")
        Dim response = PythonUtils.SplitString("Hello from VB")
 End Sub

ERROR:
“System.Runtime.InteropServices.COMException”类型的未经处理的异常在 Microsoft.VisualBasic.dll 中发生 

其他信息: Unexpected Python Error: Traceback (most recent call last):

  File "C:\Users\Daxika\AppData\Local\Programs\Python\Python36\lib\site-packages\win32com\server\policy.py", line 278, in _Invoke_

    return self._invoke_(dispid, lcid, wFlags, args)

  File "C:\Users\Daxika\AppData\Local\Programs\Python\Python36\lib\site-packages\win32com\server\policy.py", line 283, in _invoke_

    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)

  File "C:\Users\Daxika\AppData\Local\Programs\Python\Python36\lib\site-packages\win32com\server\policy.py", line 586, in _invokeex_

    return func(*args)

  File "N:\testCOM\python_com_2.py", line 14, in SplitString

    import keras

  File "C:\Users\Daxika\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\__init__.py", line 3, in <module>

    from . import utils

  File "C:\Users\Daxika\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\utils\__init__.py", line 6, in <module>

    from . import conv_utils

  File "C:\Users\Daxika\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\utils\conv_utils.py", line 3, in <module>

    from .. import backend as K

  File "C:\Users\Daxika\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\__init__.py", line 82, in <module>

    sys.stderr.write('Using TensorFlow backend.\n')

AttributeError: 'NoneType' object has no attribute 'write'

**Comment by epignatelli** [comment]
@lileiNPU Did you solve this?
