### ISSUE TITLE
load_model unable to detect layers in h5 file.

### ISSUE THREAD

**Issue by KKSMahesvara** [keras-team/keras#12636]
Hi, I recently started on Keras and I am trying to test the load_model code.
I read from the documentation site that model.save() is to save the entire model with layers and stuff. So, I tried to delete it and load it again. However, it does not load and gives me an error.

It says that I have no layers, however, I can visualize the file in applications like netron which confirms that it is not just a weight file and it contains the layers. 
Is this a bug or is it my configuration?

Python 3.6
Keras 2.2.4
I also tried on Keras 2.2.4-tf and if gives the same error.

The error given.
```
Traceback (most recent call last):
  File "C:/Users/donov/Documents/Python Scripts/Keras/Test_tf.py", line 69, in <module>
    keras.models.load_model('Testing.h5')
  File "C:\Users\donov\Anaconda3\envs\VRenv36\lib\site-packages\keras\engine\saving.py", line 453, in load_wrapper
    return load_function(*args, **kwargs)
  File "C:\Users\donov\Anaconda3\envs\VRenv36\lib\site-packages\keras\engine\saving.py", line 545, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "C:\Users\donov\Anaconda3\envs\VRenv36\lib\site-packages\keras\engine\saving.py", line 276, in _deserialize_model
    .format(len(layer_names), len(filtered_layers))
ValueError: You are trying to load a weight file containing 1 layers into a model with 0 layers

```

The code I written
```
import keras


################################################################################################################
# 0) Custom made Metric (Explanations given are not confirmed)

def get_lr_metric(optimizer):  # Custom Metric to get Learning Rate from optimizer name
    def lr(y_true, y_pred):    # Calculate the Learning rate from True labels & Predictions
        return optimizer.lr    # From the optimizer function
    return lr                  # Label Learning rate as lr


################################################################################################################
# 1) Load Training Data
inputsize = [256, 144, 3]  # Input size
resize = [256, 144]           # Image Resize
batchsize = 16                 # Mini Batch size
LearnRate = 0.001           # Learning rate.

datagen = keras.preprocessing.image.ImageDataGenerator(validation_split=0.1)  # Split images

train_generator = datagen.flow_from_directory('Images/Test',  # Train Directory
                                              target_size=resize,                     # Resize
                                              batch_size=batchsize,                # Mini Batch Size
                                              shuffle=True)                             # Shuffle data
for data_batch, labels_batch in train_generator:                        # Check sizes generated by train_generator
    print('data batch shape:', data_batch.shape)
    print('labels batch shape:', labels_batch.shape)
    break

##########################################################################
# 2) Layer Definition

model = keras.models.Sequential()                                           # Layer type
model.add(keras.layers.InputLayer(input_shape=inputsize))      # Input layer
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(3, activation=None))                  # Fully connected Layer
model.add(keras.layers.Softmax())                                            # Softmax

##########################################################################
# 3) Training Options

# Improvement: schedule learning rate decay
adam = keras.optimizers.Adam(lr=LearnRate,      # Learning Rate
                             beta_1=0.9,                            # Gradient Decay Rate
                             beta_2=0.999,                        # Squared Gradient Decay Rate
                             decay=0.0)                             # Learning Rate Decay

lr_metric = get_lr_metric(adam)                 # Use custom made metric

model.compile(optimizer=adam,                   # Optimiser
              loss='categorical_crossentropy',      # Calculate loss for categories
              metrics=['acc', lr_metric])                # Verbose to show

model.fit(train_generator,
          epochs=1,                             # Max Epoch
          verbose=1,                            # Show Verbose
          shuffle=True)                         # Shuffle Data

model.summary()                           # Display model summary
model.save('Testing.h5')                  # Save model
del model
keras.models.load_model('Testing.h5')
```

**Comment by acollins1331** [comment]
I'm not entirely sure why it is saying that particular error, but an error I do see is that you need to load custom objects in order to load a model where you have written custom losses or metrics and placed it in the compile function.

When you do keras.models.load_model('Testing.h5', custom_objects={'lr_metric': lr_metric}) in order for it to load properly.

See: https://github.com/keras-team/keras/issues/4871 for a smarter explanation.
