### ISSUE TITLE
ImportError: cannot import name 'HTTPError'

### ISSUE THREAD

**Issue by ZeroMaxinumXZ** [keras-team/keras#12757]
**System information**  
- Have I written custom code (as opposed to using example directory):  No.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 16.04 (Linux Mint 18)
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.12
- Keras version:   2.2.4
- Python version: Anaconda Python 3.6
- CUDA/cuDNN version:   9.2, 7.3.1 
- GPU model and memory:  2060, 6 gigs

**Describe the current behavior**  
```
Traceback (most recent call last):
  File "curiosity.py", line 1, in <module>
    from tensorflow.python.keras.layers import Conv2D, MaxPooling2D, UpSampling2D, Input
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 47, in <module>
    import numpy as np
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/numpy/__init__.py", line 187, in <module>
    from .testing import Tester
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/numpy/testing/__init__.py", line 12, in <module>
    from ._private.utils import *
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 16, in <module>
    from tempfile import mkdtemp, mkstemp
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/tempfile.py", line 45, in <module>
    from random import Random as _Random
  File "/home/ai/expeditionRL/expedition/curiosities/random.py", line 1, in <module>
    from expedition.curiosities import BaseCuriosity
  File "/home/ai/expeditionRL/expedition/curiosities/__init__.py", line 1, in <module>
    from .curiosity import BaseCuriosity
  File "/home/ai/expeditionRL/expedition/curiosities/curiosity.py", line 1, in <module>
    from tensorflow.python.keras.layers import Conv2D, MaxPooling2D, UpSampling2D, Input
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/keras/__init__.py", line 24, in <module>
    from tensorflow.python.keras import activations
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/keras/activations.py", line 24, in <module>
    from tensorflow.python.keras.utils.generic_utils import deserialize_keras_object
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/keras/utils/__init__.py", line 21, in <module>
    from tensorflow.python.keras.utils.data_utils import GeneratorEnqueuer
  File "/home/ai/anaconda3/envs/drl/lib/python3.6/site-packages/tensorflow/python/keras/utils/data_utils.py", line 38, in <module>
    from six.moves.urllib.error import HTTPError
ImportError: cannot import name 'HTTPError'
```

**Code to reproduce the issue**  

```
import keras
```

**Comment by ymodak** [comment]
This issue is not on TensorFlow/Keras end. Please take a look at [similar issue](https://stackoverflow.com/questions/31745653/importerror-no-module-named-urllib-request) raised on SO. For further questions related to '''ImportError: cannot import name 'HTTPError'''' you can try posting on [stackoverflow](https://stackoverflow.com/questions). Thanks!
