### ISSUE TITLE
Wrapping Lambda using Concatenate in TimeDistributed fails

### ISSUE THREAD

**Issue by kbattocchi** [keras-team/keras#12776]
**System information**  
- Have I written custom code (as opposed to using example directory):   **No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  **Windows 1809**
- TensorFlow backend (yes / no):  **yes**
- TensorFlow version:  **1.13.1**
- Keras version:  **2.2.4**
- Python version:  **3.6.6**
- CUDA/cuDNN version:  **N/A**
- GPU model and memory:  **N/A**

**Describe the current behavior**  

I've got a model which uses `TimeDistribute` to map a `Lambda` over a dataset, where the `Lambda` internally contains a `Concatenate`.  However, although I can compile the model fine, trying to fit fails with an `InvalidArgumentError` because of a shape mismatch, even though I'm 99.9% sure that the shapes should be fine.

**Describe the expected behavior**  

It is possible to fit the model.

**Code to reproduce the issue**  

Here's a dramatically simplified example

```python3
import keras
import numpy as np
from keras.layers import Input, Lambda, Concatenate, TimeDistributed
n_s = 4 # number of time points
d_x = 2 # width of one input
d_t = 3 # width of the other input, per time point
b = 8 # batch size

x = Input((d_x,))
ps = Input((n_s,d_t))

td = TimeDistributed(Lambda(lambda p: Concatenate()([p,x])))(ps)

m = keras.Model([x,ps], td)

m.compile('adam','mse') # compiles okay

m.fit([np.random.normal(size=(b, d_x)), 
       np.random.normal(size=(b, n_s, d_t))], 
      np.random.normal(size=(b, n_s, d_t+d_x))) # fails
```

**Other info / logs**  

Here's the traceback:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\keras\engine\training.py", line 1039, in fit
>     validation_steps=validation_steps)
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\keras\engine\training_arrays.py", line 199, in fit_loop
>     outs = f(ins_batch)
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
>     return self._call(inputs)
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
>     fetched = self._callable_fn(*array_vals)
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
>     run_metadata_ptr)
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
>     c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [32,3] vs. shape[1] = [8,2]
>          [[{{node time_distributed_1/concatenate_1/concat}}]]

It looks like for some reason one of the inputs is being reshaped in a way that it shouldn't be.

**Comment by kbattocchi** [comment]
This appears to be similar (identical?) to #7726, but hopefully the simpler repro makes it easier to track down.

In this simplified setting, it's possible to work around the issue by hoisting the `Concatenate` all the way out of the `TimeDistributed`, just using `K.identity` in the `Lambda`, and applying `RepeatVector` to the second argument before concatenating it outside (my real situation is a bit more complicated).

However, it seems like this shouldn't be necessary, and the error message is extremely unhelpful.
