### ISSUE TITLE
ValueError: Variable kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope?

### ISSUE THREAD

**Issue by praneet195** [keras-team/keras#12785]
I'm currently working on an LSTM based research problem. However, while using the RNNs in keras, as I will demonstrate below, I'm running into the above-mentioned error.

I use TF version 1.12.0 and keras 2.2.4.

This seems to work with cells like LSTMCell but fails to work with UGRNNCell.. No idea how to fix this issue.

```python
cell1=tf.contrib.rnn.UGRNNCell(64)
cell2=tf.contrib.rnn.UGRNNCell(64)
cell3=tf.contrib.rnn.UGRNNCell(64)
cell4=tf.contrib.rnn.UGRNNCell(64)
```
And this is my model:
```
model = Sequential()

model.add(RNN(cell1, input_shape=(train_X.shape[1:]),return_sequences=True))
model.add(BatchNormalization())
model.add(Dropout(0.5))

model.add(RNN(cell2,return_sequences=True))
model.add(BatchNormalization())
model.add(Dropout(0.5))

model.add(RNN(cell3, return_sequences=True))
model.add(BatchNormalization())
model.add(Dropout(0.5))

model.add(RNN(cell4,return_sequences=False))
model.add(BatchNormalization())
model.add(Dropout(0.5))

model.add(Dense(128, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))

model.add(Dense(1, activation='sigmoid'))

```

When run this is the error obtained:

```python
Traceback (most recent call last):
  File "fastcell.py", line 43, in <module>
    model.add(RNN(cell2,return_sequences=True))
  File "d:\Users\prane\Anaconda3\lib\site-packages\tensorflow\python\training\checkpointable\base.py", line 474, in _method_wrapper
    method(self, *args, **kwargs)
  File "d:\Users\prane\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py", line 175, in add
    output_tensor = layer(self.outputs[0])
  File "d:\Users\prane\Anaconda3\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 619, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "d:\Users\prane\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 757, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "d:\Users\prane\Anaconda3\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 750, in call
    input_length=timesteps)
  File "d:\Users\prane\Anaconda3\lib\site-packages\tensorflow\python\keras\backend.py", line 3201, in rnn
    outputs, _ = step_function(inputs[0], initial_states + constants)
  File "d:\Users\prane\Anaconda3\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 737, in step
    output, new_states = self.cell.call(inputs, states, **kwargs)
  File "d:\Users\prane\Anaconda3\lib\site-packages\tensorflow\contrib\rnn\python\ops\rnn_cell.py", line 1683, in call
    self._linear = _Linear(cell_inputs, 2 * self._num_units, True)
  File "d:\Users\prane\Anaconda3\lib\site-packages\tensorflow\contrib\rnn\python\ops\core_rnn_cell.py", line 99, in __init__
    initializer=kernel_initializer)
  File "d:\Users\prane\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1487, in get_variable
    aggregation=aggregation)
  File "d:\Users\prane\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1237, in get_variable
    aggregation=aggregation)
  File "d:\Users\prane\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 540, in get_variable
    aggregation=aggregation)
  File "d:\Users\prane\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 492, in _true_getter
    aggregation=aggregation)
  File "d:\Users\prane\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 861, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "d:\Users\prane\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()
  File "d:\Users\prane\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "d:\Users\prane\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
```

This results in the above error but works seamlessly and without any error when the UGRNNCell is replaced by an LSTMCell.
Any help would be appreciated.

**Comment by soulmachine** [comment]
I'm having the same error

**Comment by qlzh727** [comment]
So the issue is that the contrib UGRNNCell has been quite out of date, and was using the latest api to create its weights. we probably won't update the contrib code anymore since contrib is going away in TF 2.0. Having said that I could move the implementation of UGRNNCell to tensorflow/addons, which is a new repository for extended tf features.

Will do this in a week or two.

**Comment by AMGMNPLK** [comment]
Any solution for this?

**Comment by Sajeevan96** [comment]
Maybe using the parameter stateful=True can solve the issue.
