### ISSUE TITLE
fit_generator stuck 39999/40000 on epoch 1

### ISSUE THREAD

**Issue by AkselAllas** [keras-team/keras#12840]
Bug:

- Have I written custom code: no  
- OS Platform and Distribution: Linux Ubuntu 16.04  
- TensorFlow backend: yes 
- TensorFlow version:  
tensorflow                1.13.1            
tensorflow-base           1.13.1            
tensorflow-estimator      1.13.0                       
tensorflow-gpu            1.13.1 
- Keras version:  
keras                     2.2.4                         
keras-applications        1.0.7                        
keras-base                2.2.4                    
keras-preprocessing       1.0.9 
- Python version:  
Python 3.6.6 :: Anaconda, Inc.
- CUDA/cuDNN version:  
cudatoolkit               9.0                  
cudnn                     7.3.1   
- GPU model and memory:  
GeForce GTX 1070  8117MB

**Describe the current behavior**  
Using fit_generator, it stuck on Epoch 39999/40000 [============================>.] 
Deleting thread processes just makes them reappear
(aksel) aksel@kz:/sar/aksel/Bachelor_thesis$ ps aux | grep aksel | grep py
aksel     2168  0.0 26.1 43304288 17240280 pts/19 S+ 20:22   0:00 python generator_main.py v31 v29
aksel     4015  0.0 26.1 43304288 17240280 pts/19 S+ 20:23   0:00 python generator_main.py v31 v29
aksel     4017  0.0 26.1 43304288 17240272 pts/19 S+ 20:23   0:00 python generator_main.py v31 v29
aksel     4018  0.0 26.1 43304288 17240272 pts/19 S+ 20:23   0:00 python generator_main.py v31 v29
aksel     4019  0.0 26.1 43304288 17240280 pts/19 S+ 20:23   0:00 python generator_main.py v31 v29
aksel     4020  0.0 26.1 43304288 17240280 pts/19 S+ 20:23   0:00 python generator_main.py v31 v29
aksel     4024  0.0 26.1 43304288 17240272 pts/19 S+ 20:23   0:00 python generator_main.py v31 v29
aksel     4028  0.0 26.1 43304288 17240272 pts/19 S+ 20:23   0:00 python generator_main.py v31 v29
aksel     4157  0.0  0.0  14200  1092 pts/44   S+   20:23   0:00 grep --color=auto py
aksel    14135 39.4 26.8 43304288 17717160 pts/19 Sl+ May18 1293:03 python generator_main.py v31 v29
(aksel) aksel@kz:/sar/aksel/Bachelor_thesis$ kill -9 2168 4015 4017 4018 4019 4020 4024 4028
(aksel) aksel@kz:/sar/aksel/Bachelor_thesis$ ps aux | grep aksel | grep py
aksel     4640  0.0 26.1 43304288 17240272 pts/19 S+ 20:24   0:00 python generator_main.py v31 v29
aksel     4642  0.0 26.1 43304288 17240272 pts/19 S+ 20:24   0:00 python generator_main.py v31 v29
aksel     4643  0.0 26.1 43304288 17240280 pts/19 S+ 20:24   0:00 python generator_main.py v31 v29
aksel     4644  0.0 26.1 43304288 17240272 pts/19 S+ 20:24   0:00 python generator_main.py v31 v29
aksel     4645  0.0 26.1 43304288 17240280 pts/19 S+ 20:24   0:00 python generator_main.py v31 v29
aksel     4651  0.0 26.1 43304288 17240272 pts/19 S+ 20:24   0:00 python generator_main.py v31 v29
aksel     4660  0.0 26.1 43304288 17240280 pts/19 S+ 20:24   0:00 python generator_main.py v31 v29
aksel     4669  0.0 26.1 43304288 17240280 pts/19 S+ 20:24   0:00 python generator_main.py v31 v29
aksel     4691  0.0  0.0  14200  1012 pts/44   S+   20:24   0:00 grep --color=auto py
aksel    14135 39.4 26.8 43304288 17717160 pts/19 Sl+ May18 1293:05 python generator_main.py v31 v29

**Describe the expected behavior**  
Doesn't get stuck on either last step or validation :)
**Code to reproduce the issue** 
input data is huge: (68812800,8,8,22,5)

class_weights = np.load("class_weights.npy")
#This is a list with 28 elements, with values ranging from 1e-4 to 1e4

generator_params = {
    'dim': (8,8,5),
    'batch_size': 1, 
    'nb_classes': 28,
    'nb_channels': 22,
    'dir_path':'./Input_data/',
    'nb_tile_pixels':128*128,
    'tile_dimension':128,
    'shuffle': True
}

training_generator = data_generator(list_train, **generator_params)
validation_generator = data_generator(list_validation, **generator_params)

optimizer_params = {
    'lr':0.00001,
    'clipvalue':0.5,
}

early_stopping_params = {
    'monitor':'val_loss',
    'min_delta':0,
    'patience':10,
    'verbose':1,
    #'mode':'auto'
} 
fit_params = {
    'workers':4,
    'class_weight':class_weights,
    'max_queue_size':8,
    'epochs':1,
    'steps_per_epoch':40000,
    'use_multiprocessing':True,
    'callbacks':[EarlyStopping(**early_stopping_params)],
}

hist = s2_model.model.fit_generator(generator=training_generator,
                    validation_data=validation_generator,
                    **fit_params,
)

**Other info / logs**  
On sending CTRL+C to the process, I got the following error message:

^T^T^[[D^[[D^[[B^CProcess ForkPoolWorker-200:
Process ForkPoolWorker-195:
Process ForkPoolWorker-202:
Process ForkPoolWorker-199:
Process ForkPoolWorker-198:
Process ForkPoolWorker-201:
Process ForkPoolWorker-196:
Process ForkPoolWorker-197:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
Traceback (most recent call last):
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/queues.py", line 334, in get
    with self._rlock:
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/queues.py", line 334, in get
    with self._rlock:
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/queues.py", line 334, in get
    with self._rlock:
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/queues.py", line 334, in get
    with self._rlock:
KeyboardInterrupt
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/queues.py", line 334, in get
    with self._rlock:
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/queues.py", line 334, in get
    with self._rlock:
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/queues.py", line 334, in get
    with self._rlock:
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/queues.py", line 334, in get
    with self._rlock:
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
Traceback (most recent call last):
  File "generator_main.py", line 144, in <module>
    **fit_params,
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/site-packages/keras/engine/training_generator.py", line 234, in fit_generator
    workers=0)
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/site-packages/keras/engine/training.py", line 1472, in evaluate_generator
    verbose=verbose)
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/site-packages/keras/engine/training_generator.py", line 330, in evaluate_generator
    generator_output = next(output_generator)
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/site-packages/keras/utils/data_utils.py", line 595, in get
    inputs = self.queue.get(block=True).get()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/pool.py", line 638, in get
    self.wait(timeout)
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/pool.py", line 635, in wait
    self._event.wait(timeout)   
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/threading.py", line 295, in wait
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt
^[[D^[[D^[[D^[[C^[[D^[[D^[[D^[[D (Stopped here again, then i pressed CTRL+C again)
Traceback (most recent call last):
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/util.py", line 262, in _run_finalizers
Process ForkPoolWorker-204:
Process ForkPoolWorker-205:
Process ForkPoolWorker-203:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/queues.py", line 334, in get
    with self._rlock:
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/queues.py", line 334, in get
    with self._rlock:
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/queues.py", line 334, in get
    with self._rlock:
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
    finalizer()
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/pool.py", line 571, in _terminate_pool
    cls._help_stuff_finish(inqueue, task_handler, len(pool))
  File "/home/aksel/anaconda3/envs/aksel/lib/python3.6/multiprocessing/pool.py", line 556, in _help_stuff_finish
    inqueue._rlock.acquire()
KeyboardInterrupt

**Comment by AkselAllas** [comment]
My solution is custom callback, that stops training and saves my model by pressing CTRL+Z:

class SignalStopping(keras.callbacks.Callback):
'''Stop training when an interrupt signal (or other) was received
    # Arguments
    sig: the signal to listen to. Defaults to signal.SIGTSTP.
    doubleSignalExits: Receiving the signal twice exits the python
        process instead of waiting for this epoch to finish.
    patience: number of epochs with no improvement
        after which training will be stopped.
    verbose: verbosity mode.
'''
# SBW 2018.10.15 Since ctrl-c trapping isn't working, watch for existence of file, e.g. .\path\_StopTraining.txt.
def __init__(self, sig=signal.SIGTSTP, doubleSignalExits=False, verbose=1):
    super(SignalStopping, self).__init__()
    self.signal_received = False
    self.verbose = verbose
    self.doubleSignalExits = doubleSignalExits
    def signal_handler(sig, frame):
        self.model.stop_training = True
        #if self.signal_received and self.doubleSignalExits:
        #    if self.verbose > 0:
        #        print('') #new line to not print on current status bar. Better solution?
        #        print('Received signal to stop ' + str(sig)+' twice. Exiting..')
        #    exit(sig)
        #self.signal_received = True
        #if self.verbose > 0:
        #    print('') #new line to not print on current status bar. Better solution?
        #    print('Received signal to stop: ' + str(sig))
    signal.signal(signal.SIGTSTP, signal_handler)
    self.stopped_epoch = 0

def on_epoch_end(self, epoch, logs={}):
    if self.signal_received:
        self.stopped_epoch = epoch
        self.model.stop_training = True
        print("stop_training=true")

def on_train_end(self, logs={}):
    print("on_train_end")
    if self.stopped_epoch > 0 and self.verbose > 0:
        print('Epoch %05d: stopping due to signal' % 
(self.stopped_epoch))

And i call it with:

stop_cb = SignalStopping()
Then put it into callback list, that is passed to fit_generator.
