### ISSUE TITLE
Getting 'ProgbarLogger' object has no attribute 'log_values'`

### ISSUE THREAD

**Issue by abhinavsagar** [keras-team/keras#12853]
OS Platform and Distribution: windows 10
TensorFlow backend: yes
tensorflow 1.13.1
tensorflow-base 1.13.1
tensorflow-estimator 1.13.0
Keras version:
keras 2.2.4
keras-applications 1.0.7
keras-base 2.2.4
keras-preprocessing 1.0.9
Python version:
Python 3.6.5
No cuda
No gpu

On running the code as described [here](https://github.com/GeorgeSeif/Transfer-Learning-Suite), I am getting-
`Traceback (most recent call last):
  File "main.py", line 205, in <module>
    validation_data=validation_generator, validation_steps=1, class_weight='auto', shuffle=True, callbacks=callbacks_list)
  File "C:\Users\Win 10\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Win 10\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\Win 10\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training_generator.py", line 251, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "C:\Users\Win 10\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "C:\Users\Win 10\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\callbacks.py", line 338, in on_epoch_end
    self.progbar.update(self.seen, self.log_values)
AttributeError: 'ProgbarLogger' object has no attribute 'log_values'`

**Comment by ymodak** [comment]
Perhaps this can be a good issue to be raised on [Transfer-Learning-Suite repo](https://github.com/GeorgeSeif/Transfer-Learning-Suite/issues)
