### ISSUE TITLE
Can't pickle generator objects

### ISSUE THREAD

**Issue by RM9997** [keras-team/keras#12885]
I have a script where I'm trying to run this line of code and I get the error 'can't pickle generator objects'. I've tried with and without the 'use_multiprocessing' argument but both give me an error. I've also tried with pickle_safe but this didn't work either. [It is also advised against here](https://github.com/keras-team/keras/issues/3962). Does anyone know what my issue could be? I'm using 3.7.3.
Thanks

```python

from keras.optimizers import Adam
from keras.callbacks import EarlyStopping, TensorBoard, ModelCheckpoint, ReduceLROnPlateau
import matplotlib.pyplot as plt
from DataGenerator import generator
import datetime, os
import models
import numpy as np 
from metrics import metrics_callback, weighted_categorical_crossentropy
...
model.fit_generator(generator=train_gen,
                    steps_per_epoch=train_batches,
                    epochs=200,
                    validation_data=train_gen,
                    validation_steps = 100,
                    max_queue_size=40,
                    use_multiprocessing=True,
                    #pickle_safe=True
                    )

HERE IS THE ERROR I GET:

Epoch 1/200
Exception in thread Thread-17:
Traceback (most recent call last):
  File "C:\Users\s164286\AppData\Local\Continuum\anaconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\s164286\AppData\Local\Continuum\anaconda3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\s164286\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\utils\data_utils.py", line 666, in _run
    with closing(self.executor_fn(_SHARED_SEQUENCES)) as executor:
  File "C:\Users\s164286\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\utils\data_utils.py", line 661, in <lambda>
    initargs=(seqs, self.random_seed))
  File "C:\Users\s164286\AppData\Local\Continuum\anaconda3\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\s164286\AppData\Local\Continuum\anaconda3\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\Users\s164286\AppData\Local\Continuum\anaconda3\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\Users\s164286\AppData\Local\Continuum\anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\s164286\AppData\Local\Continuum\anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\s164286\AppData\Local\Continuum\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\s164286\AppData\Local\Continuum\anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle generator objects```

**Comment by Loverush** [comment]
Same as you.
keras-GPU 2.2.4
ternsorflow 1.13.1

**Comment by RM9997** [comment]
Maybe try downgrading/upgrading with different combinations. I didn't manage to solve it but ¯\_(ツ)_/¯ .

**Comment by sree941** [comment]
I'm also getting the same error. Can anyone help me with this please?

**Comment by rodguinea** [comment]
Me too

**Comment by jhaggle** [comment]
And I

**Comment by HsGaurav** [comment]
can someone solve this please !!!

**Comment by rodguinea** [comment]
@fchollet is this solved?

**Comment by Raa23** [comment]
I have the same issue
