### ISSUE TITLE
IndexError: list index out of range thrown by TimeFreqLSTMCell layer

### ISSUE THREAD

**Issue by MBoemo** [keras-team/keras#12895]
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 16.04
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.13.1
- Keras version:  2.2.4
- Python version:  2.7
- CUDA/cuDNN version:  n/a
- GPU model and memory:  n/a

I want to add a layer to a Keras sequential model that uses a TimeFreqLSTMCell (see https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/TimeFreqLSTMCell).  Minimum code is here: 

```python
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import RNN
from keras.layers import TimeDistributed
import numpy as np

windowSize = 10
n_features = 1
timeLength = 500

model = Sequential()
model.add(RNN(tf.contrib.rnn.TimeFreqLSTMCell(32,feature_size=windowSize), input_shape=(timeLength,n_features), return_sequences=True))
model.add(TimeDistributed(Dense(1)))
model.compile(optimizer='adam', loss='mse')
```
which throws the following error:
```shell
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    model.add(RNN(tf.contrib.rnn.TimeFreqLSTMCell(32,feature_size=5), input_shape=(timeLength,n_features), return_sequences=True))
  File ".local/lib/python2.7/site-packages/keras/engine/sequential.py", line 165, in add
    layer(x)
  File ".local/lib/python2.7/site-packages/keras/layers/recurrent.py", line 532, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File ".local/lib/python2.7/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File ".local/lib/python2.7/site-packages/keras/layers/recurrent.py", line 649, in call
    input_length=timesteps)
  File ".local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2922, in rnn
    outputs, _ = step_function(inputs[0], initial_states + constants)
  File ".local/lib/python2.7/site-packages/keras/layers/recurrent.py", line 640, in step
    return self.cell.call(inputs, states, **kwargs)
  File ".local/lib/python2.7/site-packages/tensorflow/contrib/rnn/python/ops/rnn_cell.py", line 411, in call
    actual_input_size = freq_inputs[0].get_shape().as_list()[1]
IndexError: list index out of range
```
which I've tracked down to here (https://github.com/tensorflow/tensorflow/blob/3d0ad0b7dab9c07b39e384b22c4392eee1effb10/tensorflow/contrib/rnn/python/ops/rnn_cell.py#L412).  I've looked through the documentation to try to figure out what's going on but no luck so far - hopefully this is a bug and I haven't just done something silly.

**Comment by jvishnuvardhan** [comment]
I could reproduce the issue. thanks!

**Comment by MBoemo** [comment]
Glad to hear it wasn't just me!  Thanks very much for looking into it.  Just give a shout if this is fixed in a future commit.
