### ISSUE TITLE
How to customize a loss function with a trainable parameter?

### ISSUE THREAD

**Issue by chengjianhong** [keras-team/keras#12983]
Hi, I want to customize the following loss function with a training parameter, where λ is the regularization term and w is a trainable parameter. I customize the loss layer and add the loss into my model. But, it occurs the following errors. I don't know where the wrong is and whether my this custom loss layer is right?

![custom_loss](https://user-images.githubusercontent.com/12234973/59775397-bac1b800-92e3-11e9-9b12-dc0aa5698fac.png)

1. I customize BCLoss Layer
  ```
  class BCLoss(Layer):

    def __init__(self,gamma_init='zero',lamada = 0.00005,**kwargs):
        self.gamma_init = initializations.get(gamma_init)
        self.lamada = lamada
        super(BCLoss, self).__init__(**kwargs)
    def build(self, input_shape):
        self.gamma_init = self.add_weight(name='gamma',
                                     shape=(1,),
                                     initializer='uniform',
                                     trainable=True)
        super(BCLoss,self).build(input_shape)

    def call(self, inputs, **kwargs):
        y_true, y_pred = inputs
        loss = K.mean(K.binary_crossentropy(y_true, y_pred), axis=-1) + self.lamada* K.abs(self.gamma_init)
        return loss

    def compute_output_shape(self, input_shape):
        return input_shape
```

2. add the loss into model

```
 def build_model(self):
        """
        Build the model
        Returns:
            Model : Keras model instance
        """
        img_input = layers.Input(shape=self.input_shape, name='img_input')
        y_true = layers.Input(shape=(1,),name='y_true')

        nb_channels = self.growth_rate
        # Initial convolution layer
        layer_1 = layers.Convolution2D(2 * self.growth_rate, (7, 7), strides=(2, 2),padding='same',use_bias=False,kernel_regularizer=keras.regularizers.l2(self.weight_decay))(img_input)
        average_1 = layers.AveragePooling2D((2, 2), strides=(4, 4))(layer_1)
        x = layers.BatchNormalization()(layer_1)
        x = layers.Activation('relu')(x)
        x = layers.MaxPooling2D()(x)
        # Building dense blocks
        skip_layer = [average_1]

        for block in range(self.dense_blocks - 1):
            # Add dense block
            x, nb_channels = self.dense_block(x, self.dense_layers[block], nb_channels, self.growth_rate,
                                              self.dropout_rate, self.bottleneck, self.weight_decay)
            # Add transition_block
            x_left,x_right = self.transition_layer(x, nb_channels, self.dropout_rate, self.compression, self.weight_decay)
            x = x_left
            nb_channels = int(nb_channels * self.compression)
            skip_layer.append(x_right)
        # Add last dense block without transition but for that with global average pooling
        x, nb_channels = self.dense_block(x, self.dense_layers[-1], nb_channels,
                                          self.growth_rate, self.dropout_rate, self.weight_decay,skip_layer =skip_layer)
        x = layers.BatchNormalization()(x)
        x = layers.Activation('relu')(x)
        x = layers.GlobalAveragePooling2D()(x)
        x = layers.Dropout(0.25)(x)
        y_pred = layers.Dense(self.nb_classes, activation='sigmoid')(x)
        model = keras.Model(inputs=[img_input,y_true], outputs=y_pred, name='densenet')
        loss = BCLoss()([y_true, y_pred])
        model.add_loss(loss)
        return model
```
3. compileand train the model
```
    train_generator = train_datagen.flow(x_train, y_train,batch_size=32)
    validation_generator = validation_datagen.flow(x_test, y_test, batch_size=32)

    model.compile(loss=None, optimizer=Adam(lr=0.001), metrics=['accuracy']) #binary_crossentropy
    history = model.fit_generator(train_generator,
                                  steps_per_epoch=len(y_train) / 32,
                                  epochs=500,
                                  validation_data=validation_generator,
                                  validation_steps=len(y_test) / 32,
                                  class_weight=None,
                                  callbacks=get_callbacks(model_file,
                                                          initial_learning_rate=0.001,
                                                          learning_rate_drop=0.5,
                                                          learning_rate_patience=10,
                                                          early_stopping_patience=50))
```
**4. It happens to the following error:**
```
Traceback (most recent call last):
  File "G:/Workspace/workspace_python/Lung_EGRF/train.py", line 107, in <module>
    train_model(config['training_data'],config['testing_data'], config['model_file'],config['input_shape'])
  File "G:/Workspace/workspace_python/Lung_EGRF/train.py", line 95, in train_model
    early_stopping_patience=50))
  File "D:\Anaconda3\envs\py36\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "D:\Anaconda3\envs\py36\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "D:\Anaconda3\envs\py36\lib\site-packages\keras\engine\training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "D:\Anaconda3\envs\py36\lib\site-packages\keras\engine\training.py", line 1211, in train_on_batch
    class_weight=class_weight)
  File "D:\Anaconda3\envs\py36\lib\site-packages\keras\engine\training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "D:\Anaconda3\envs\py36\lib\site-packages\keras\engine\training_utils.py", line 102, in standardize_input_data
    str(len(data)) + ' arrays: ' + str(data)[:200] + '...')
ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([[[[ 5.54686738e-03,  7.74330867e-04,  7.57289294e-04],
         [ 5.80290332e-03,  1.07769540e-03, -4.01950856e-05],
         [ 5.79935452e-03,  1.12004776e-03, -1.28079159e-03],

```

**Comment by sidml** [comment]
It's not clear to me how this was fixed.
If anyone has any suggestions, please let me know.

Following issue seem to be related:
https://github.com/keras-team/keras/issues/9608
https://github.com/keras-team/keras/issues/3638
