### ISSUE TITLE
How to define ConvLSTM2D encoder-decoder in Keras?

### ISSUE THREAD

**Issue by princefr** [keras-team/keras#12995]
I have seen examples of building an encoder-decoder network using LSTM in Keras but I want to have a ConvLSTM encoder-decoder. when I try to use the same pattern as LSTM with ConvLSTM all seems to works well until I try to specify an initial state. this exception happen .

```
Traceback (most recent call last):
  File "MobileNet_LSTM.py", line 185, in <module>
    model = build_model(input)
  File "MobileNet_LSTM.py", line 140, in build_model
    lstm_output, state_h_output, state_c_output = decoder(reshaped, initial_state=[state_h, state_c])
  File "/Users/princejackes/Library/Python/3.6/lib/python/site-packages/tensorflow/python/keras/layers/convolutional_recurrent.py", line 337, in __call__
    output = super(ConvRNN2D, self).__call__(full_input, **kwargs)
  File "/Users/princejackes/Library/Python/3.6/lib/python/site-packages/tensorflow/python/keras/layers/recurrent.py", line 616, in __call__
    self._num_constants)
  File "/Users/princejackes/Library/Python/3.6/lib/python/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2700, in _standardize_args
    assert initial_state is None and constants is None
AssertionError
```

seems like we cannot set an initial state using ConvLSTM2D decoder.
so how can we define aConvLSTM2D encoder-decoder then ?

below its a part of my code.

```
    x = _conv_block(input, 32, alpha, strides=(2, 2))
    x = _depthwise_conv_block_classification(x, 64, alpha, depth_multiplier, block_id=1)

    x = _depthwise_conv_block_classification(x, 128, alpha, depth_multiplier,
                              strides=(2, 2), block_id=2)
    x = _depthwise_conv_block_classification(x, 128, alpha, depth_multiplier, block_id=3)

    x = _depthwise_conv_block_classification(x, 256, alpha, depth_multiplier,
                              strides=(2, 2), block_id=4)
    x = _depthwise_conv_block_classification(x, 256, alpha, depth_multiplier, block_id=5)

    x = _depthwise_conv_block_classification(x, 512, alpha, depth_multiplier,
                              strides=(2, 2), block_id=6)
    x = _depthwise_conv_block_classification(x, 512, alpha, depth_multiplier, block_id=7)
    x = _depthwise_conv_block_classification(x, 512, alpha, depth_multiplier, block_id=8)
    x = _depthwise_conv_block_classification(x, 512, alpha, depth_multiplier, block_id=9)
    x = _depthwise_conv_block_classification(x, 512, alpha, depth_multiplier, block_id=10)
    conv4_3 = _depthwise_conv_block_classification(x, 512, alpha, depth_multiplier, block_id=11)
    conv4_3_norm = Conv2DNormalization(20, name='detection_conv4_3_norm')(conv4_3)

    x = _depthwise_conv_block_classification(conv4_3, 512, alpha, depth_multiplier,
                              strides=(2, 2), block_id=12)

    fc7 = _depthwise_conv_block_classification(x, 1024, alpha, depth_multiplier, block_id=13)


    shape = (1, 7, 7 ,  1024)
    reshaped = keras.layers.Reshape(target_shape=shape)(fc7)
    encoder = ConvLSTM2D(256, kernel_size=1, padding="same",  return_state=True, return_sequences=False)
    lstm_encoder, state_h, state_c = encoder(reshaped)


    decoder = ConvLSTM2D(256, kernel_size=1, padding="same",   return_state=True, return_sequences=False)
    lstm_decoder_output, state_h_output, state_c_output = decoder(reshaped, initial_state=[state_h, state_c])

    output_reshape = (7, 7, 1024)
    reshaped_out = keras.layers.Reshape(target_shape=output_reshape)(lstm_decoder_output)
```

**System information**  
- Have I written custom code (as opposed to using example directory):  
- OS Platform and Distribution:  Mac OS Mojave
- TensorFlow backend:  YES
- TensorFlow version:  2.0.0-beta0
- Keras version:  2.2.4
- Python version:  3.6
- CUDA/cuDNN version:   
- GPU model and memory:

**Comment by msaad1311** [comment]
hi, just wanted to know if we can use convlstm in encoder decoder?
