### ISSUE TITLE
model.fit : AttributeError: 'Model' object has no attribute '_compile_metrics'

### ISSUE THREAD

**Issue by CreeperLava** [keras-team/keras#13101]
**System information**  
- Have I written custom code (as opposed to using example directory): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Mint 19.3
- TensorFlow backend (yes / no): yes
- TensorFlow version: 2.0.0b1
- Keras version: 2.2.4-tf
- Python version: 3.6
- CUDA/cuDNN version: /
- GPU model and memory: GTX 940MX, 430.26

**Describe the current behavior**  
The model.fit() function throws a `AttributeError: 'Model' object has no attribute '_compile_metrics'` exception.

**Describe the expected behavior**  
It should work ?

**Code to reproduce the issue**  
```python
import numpy as np
import tensorflow as tf

input_3D = tf.keras.Input(shape=(None, None, None, 1)) # unknown width, length and depth, 1 gray channel
network_3D = tf.keras.layers.Conv3D(
    filters = 128,  # dimensionality of output space
    kernel_size = 5,  # shape of 2D convolution window (5x5)
    strides = 1,  # stride of convolution along all spatial dimensions
    padding = "same", data_format = "channels_last",  # input with shape (batch, height, width, channels)
    activation = tf.keras.layers.LeakyReLU(alpha = 0.2),  # activation function to use
    use_bias = True,
    kernel_initializer = tf.keras.initializers.TruncatedNormal(stddev = 1e-2),
    # initializer for the kernel weights matrix
    bias_initializer = 'zeros',  # initializer for the bias vector
    input_shape = (None, None, None, 1)
)(input_3D)
network_3D = tf.keras.layers.BatchNormalization(
    momentum = 0.1, # momentum + decay = 1.0
    epsilon = 1e-5,
    scale = True
)(network_3D)

model = tf.keras.Model(inputs = input_3D, outputs = network_3D)
model.loss = tf.losses.mean_squared_error
model.optimizer = tf.keras.optimizers.Adam(learning_rate = 0.002)
v = np.zeros((100,100,100,100))
l = np.zeros((100,100,100))
model.fit(v, l, epochs = 20, batch_size = 1)
```  

**Other info / logs**  
```python
Traceback (most recent call last):
  File ".../venv/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-a0cacfaacdab>", line 1, in <module>
    history = model.fit(v, l, epochs = 20, batch_size = 1)
  File ".../venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 643, in fit
    use_multiprocessing=use_multiprocessing)
  File ".../venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 632, in fit
    shuffle=shuffle)
  File ".../venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 2385, in _standardize_user_data
    metrics=self._compile_metrics,
AttributeError: 'Model' object has no attribute '_compile_metrics'
```

**Comment by jvishnuvardhan** [comment]
@CreeperLava  I think model.compile is missing
`model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate = 0.002),loss=tf.losses.mean_squared_error,metrics=['mae'])` . thanks!

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!
