### ISSUE TITLE
keras is using tensorflow backend while running thru terminal but trying to use theano while running thru pycharm console

### ISSUE THREAD

**Issue by idohi** [keras-team/keras#13205]
Description:
A. Open Anaconda prompt and run following commands:
1. `activate <my_environment_name>`
2. `set "KERAS_BACKEND=tensorflow"`
3. `python`
4. `import keras`
Output (as expected): 
`Using TensorFlow backend.`

B. Open python console thru pycharm (which use the python.exe of the environment from A. as interpreter) and run following command:
1. `import keras`
Output (failed):
```

Using Theano backend.
Traceback (most recent call last):
  File "C:\Users\Ido\AppData\Local\conda\conda\envs\py36\lib\site-packages\theano\gof\lazylinker_c.py", line 81, in <module>
    actual_version, force_compile, _need_reload))
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ido\AppData\Local\conda\conda\envs\py36\lib\site-packages\theano\gof\lazylinker_c.py", line 105, in <module>
    actual_version, force_compile, _need_reload))
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
You can find the C code in this temporary file: C:\Users\Ido\AppData\Local\Temp\theano_compilation_error_kkg8qfej
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\helpers\pydev\pydevd.py", line 2060, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\helpers\pydev\pydevd.py", line 2054, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\helpers\pydev\pydevd.py", line 1405, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\helpers\pydev\pydevd.py", line 1412, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Ido/Documents/Products/ABI_product/Codes/src/nba_py_learning/real_time_predictions.py", line 1, in <module>
    import keras
  File "C:\Users\Ido\AppData\Local\conda\conda\envs\py36\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\Ido\AppData\Local\conda\conda\envs\py36\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\Ido\AppData\Local\conda\conda\envs\py36\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\Ido\AppData\Local\conda\conda\envs\py36\lib\site-packages\keras\backend\__init__.py", line 86, in <module>
    from .theano_backend import *
  File "C:\Users\Ido\AppData\Local\conda\conda\envs\py36\lib\site-packages\keras\backend\theano_backend.py", line 7, in <module>
    import theano
  File "C:\Users\Ido\AppData\Local\conda\conda\envs\py36\lib\site-packages\theano\__init__.py", line 110, in <module>
    from theano.compile import (
  File "C:\Users\Ido\AppData\Local\conda\conda\envs\py36\lib\site-packages\theano\compile\__init__.py", line 12, in <module>
    from theano.compile.mode import *
  File "C:\Users\Ido\AppData\Local\conda\conda\envs\py36\lib\site-packages\theano\compile\mode.py", line 11, in <module>
    import theano.gof.vm
  File "C:\Users\Ido\AppData\Local\conda\conda\envs\py36\lib\site-packages\theano\gof\vm.py", line 674, in <module>
    from . import lazylinker_c
  File "C:\Users\Ido\AppData\Local\conda\conda\envs\py36\lib\site-packages\theano\gof\lazylinker_c.py", line 140, in <module>
    preargs=args)
  File "C:\Users\Ido\AppData\Local\conda\conda\envs\py36\lib\site-packages\theano\gof\cmodule.py", line 2396, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
. 

Process finished with exit code 1
```
OS: Windows 10
(base) anaconda version: 5.2.0 (run: `conda list anaconda$` thru anaconda prompt) 
(<my_environment_name>) anaconda version: "custom" (run: `conda list anaconda$` thru anaconda prompt) 
python: 3.6.8
tensorflow: 1.13.1
Keras: 2.2.4

*Note-  
If I set the `backend` in the file _.keras.json_ it works as expected in the python console of pycharm , but since I have 2 environments (one of python 2.7 and the other of python 3.6) I am looking for efficient approach to run projects on those different environments (one using theano and the other using tensorflow).

**Comment by PhilipMay** [comment]
I guess you are used something like conda. Then I guess you use a different environment when using pycharm compared to console. Solution: configure your env. in pycharm.
