### ISSUE TITLE
Unable to initialize ResNet50 with data_format='channels_first'

### ISSUE THREAD

**Issue by otacon94** [keras-team/keras#13202]
Hi! There's a problem with **ResNet50** (I think the same problem is present for the other ResNet implementations). I'm unable to use `channels_first` as data format. I tried to use `channels_last` and everything went well.

Here's the code:
```
from keras_applications.resnet import ResNet50

import keras
from keras.layers import Flatten, Dense
from keras.datasets import cifar10
from keras.models import Model
from keras.utils import to_categorical
import numpy as np


def abastufally():
    weights = 'imagenet'
    # weights = None

    channels = 'channels_first'
    # channels = 'channels_last'

    keras.backend.set_image_data_format(channels)

    (x_train, y_train), (_, _) = cifar10.load_data()

    # Get base model
    base_model = ResNet50(include_top=False, weights=None, layers=keras.layers, models=keras.models,
                          utils=keras.utils, input_shape=np.shape(x_train)[1:], backend=keras.backend)
    # Add final layers
    x = base_model.output
    x = Flatten()(x)
    predictions = Dense(10, activation='softmax', name='fc1000')(x)
    model = Model(input=base_model.input, output=predictions)
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    model.summary()
    model.fit(x_train, to_categorical(y_train), epochs=2)


if __name__ == '__main__':
    abastufally()

```

And here's the error:

```
C:\Users\alienware\webapps\Scripts\python.exe D:/DLQSK/webapps/testsKeras/test_res_standard.py
Using TensorFlow backend.
2019-08-08 12:14:14.857430: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-08-08 12:14:15.158034: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1392] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.695
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.63GiB
2019-08-08 12:14:15.158407: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1471] Adding visible gpu devices: 0
2019-08-08 12:14:15.816756: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-08 12:14:15.816977: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:958]      0 
2019-08-08 12:14:15.817125: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 0:   N 
2019-08-08 12:14:15.817388: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6399 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "C:\Users\alienware\webapps\lib\site-packages\tensorflow\python\framework\ops.py", line 1589, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 1 but is rank 0 for 'conv1_bn/cond/Reshape_4' (op: 'Reshape') with input shapes: [1,64,1,1], [].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/DLQSK/webapps/testsKeras/test_res_standard.py", line 36, in <module>
    abastufally()
  File "D:/DLQSK/webapps/testsKeras/test_res_standard.py", line 24, in abastufally
    utils=keras.utils, input_shape=np.shape(x_train)[1:], backend=keras.backend)
  File "C:\Users\alienware\webapps\lib\site-packages\keras_applications\resnet_common.py", line 435, in ResNet50
    **kwargs)
  File "C:\Users\alienware\webapps\lib\site-packages\keras_applications\resnet_common.py", line 367, in ResNet
    name='conv1_bn')(x)
  File "C:\Users\alienware\webapps\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\alienware\webapps\lib\site-packages\keras\layers\normalization.py", line 206, in call
    training=training)
  File "C:\Users\alienware\webapps\lib\site-packages\keras\backend\tensorflow_backend.py", line 3123, in in_train_phase
    x = switch(training, x, alt)
  File "C:\Users\alienware\webapps\lib\site-packages\keras\backend\tensorflow_backend.py", line 3058, in switch
    else_expression_fn)
  File "C:\Users\alienware\webapps\lib\site-packages\tensorflow\python\util\deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "C:\Users\alienware\webapps\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2049, in cond
    orig_res_f, res_f = context_f.BuildCondBranch(false_fn)
  File "C:\Users\alienware\webapps\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 1890, in BuildCondBranch
    original_result = fn()
  File "C:\Users\alienware\webapps\lib\site-packages\keras\layers\normalization.py", line 167, in normalize_inference
    epsilon=self.epsilon)
  File "C:\Users\alienware\webapps\lib\site-packages\keras\backend\tensorflow_backend.py", line 1908, in batch_normalization
    mean = tf.reshape(mean, (-1))
  File "C:\Users\alienware\webapps\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 7431, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "C:\Users\alienware\webapps\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\alienware\webapps\lib\site-packages\tensorflow\python\framework\ops.py", line 3414, in create_op
    op_def=op_def)
  File "C:\Users\alienware\webapps\lib\site-packages\tensorflow\python\framework\ops.py", line 1756, in __init__
    control_input_ops)
  File "C:\Users\alienware\webapps\lib\site-packages\tensorflow\python\framework\ops.py", line 1592, in _create_c_op
    raise ValueError(str(e))
ValueError: Shape must be rank 1 but is rank 0 for 'conv1_bn/cond/Reshape_4' (op: 'Reshape') with input shapes: [1,64,1,1], [].

Process finished with exit code 1

```

**Comment by taehoonlee** [comment]
@otacon94, It is a bug of the `BatchNormalization` layer (see #10648), and now has been resolved. Please keep the latest version of Keras with `pip install -U git+https://github.com/keras-team/keras`.

**Comment by otacon94** [comment]
> @otacon94, It is a bug of the `BatchNormalization` layer (see #10648), and now has been resolved. Please keep the latest version of Keras with `pip install -U git+https://github.com/keras-team/keras`.

Hi! Sorry for the late, and for not writing it into the description but I was using the 2.2.4 version of keras which was the latest version available at that moment. Tomorrow morning I will try to update to 2.2.5.

**Comment by otacon94** [comment]
With the version 2.2.5 everything is working fine! thanks for the help @taehoonlee
