### ISSUE TITLE
Thread-safe utils.Sequence generator is considered not thread-safe by Keras

### ISSUE THREAD

**Issue by svdHero** [keras-team/keras#13222]
**System information**  
- Windows 8.1
- CPU mode, no GPU
- Anaconda Version 2019.07
- Python 3.7
- Tensorflow 1.14.0 or alternatively Tensorflow 2.0.0-beta1
- Keras 2.2.4-tf

**Describe the current behavior**  
I want to use a custom generator with the `model.fit_generator()` method and multiple workers. As seen in many issues and Stackoverflow posts, this only works if the generator is thread-safe. The recommended way is to subclass `keras.utils.Sequence`.

However, when I do this and run my code with `workers=2`, I get an
```
ValueError: generator already executing
```
and an
```
RuntimeError: Your generator is NOT thread-safe. Keras requires a thread-safe generator when `use_multiprocessing=False, workers > 1`.
```
This happens although my generator code is thread-safe. The `__getitem__` method does not contain any side-effects, so in theory multiple threads should be able to access it without any race-conditions or deadlocks happening.

So what's wrong here? The full output is:
```
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 512)               401920
_________________________________________________________________
dense_1 (Dense)              (None, 512)               262656
_________________________________________________________________
dense_2 (Dense)              (None, 10)                5130
=================================================================
Total params: 669,706
Trainable params: 669,706
Non-trainable params: 0
_________________________________________________________________
Epoch 1/5
WARNING: Logging before flag parsing goes to stderr.
W0816 10:59:10.532689 10080 deprecation.py:323] From C:\Users\XXX\AppData\Local\Continuum\anaconda3\envs\tf-2-env\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.
<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
466/469 [============================>.] - ETA: 0s - loss: 0.2365 - accuracy: 0.9261Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Continuum\anaconda3\envs\tf-2-env\lib\site-packages\tensorflow\python\keras\utils\data_utils.py", line 894, in get
    inputs = self.queue.get(block=True).get()
  File "C:\Users\XXX\AppData\Local\Continuum\anaconda3\envs\tf-2-env\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
  File "C:\Users\XXX\AppData\Local\Continuum\anaconda3\envs\tf-2-env\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\XXX\AppData\Local\Continuum\anaconda3\envs\tf-2-env\lib\site-packages\tensorflow\python\keras\utils\data_utils.py", line 828, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
ValueError: generator already executing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "W:/GIT_WORKSPACES/MyProject/sequence_bug.py", line 51, in <module>
    workers=NUM_WORKERS)
  File "C:\Users\XXX\AppData\Local\Continuum\anaconda3\envs\tf-2-env\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1176, in fit_generator
    steps_name='steps_per_epoch')
  File "C:\Users\XXX\AppData\Local\Continuum\anaconda3\envs\tf-2-env\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 322, in model_iteration
    steps_name='validation_steps')
  File "C:\Users\XXX\AppData\Local\Continuum\anaconda3\envs\tf-2-env\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 220, in model_iteration
    batch_data = _get_next_batch(generator, mode)
  File "C:\Users\XXX\AppData\Local\Continuum\anaconda3\envs\tf-2-env\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 362, in _get_next_batch
    generator_output = next(generator)
  File "C:\Users\XXX\AppData\Local\Continuum\anaconda3\envs\tf-2-env\lib\site-packages\tensorflow\python\keras\utils\data_utils.py", line 915, in get
    'Your generator is NOT thread-safe. '
RuntimeError: Your generator is NOT thread-safe. Keras requires a thread-safe generator when `use_multiprocessing=False, workers > 1`.
```

**Describe the expected behavior**  
Run the code below without any errors.

**Code to reproduce the issue**  
```python
import numpy as np
from tensorflow import keras

# ===============================================================
# Change this:
# ===============================================================
NUM_WORKERS = 2
# ===============================================================
batch_size = 128
num_epochs = 5
# ===============================================================
class MyGenerator(keras.utils.Sequence):

    def __init__(self, x, y, bs):
        self.x = x.copy()
        self.y = y.copy()
        self.batch_size = bs

    def __len__(self):
        return int(np.ceil(self.x.shape[0] / self.batch_size))

    def __getitem__(self, index):
        x_batch = self.x[self.batch_size * index:self.batch_size * (index + 1), ...]
        y_batch = self.y[self.batch_size * index:self.batch_size * (index + 1), ...]
        return x_batch, y_batch
# ===============================================================
(x_train, y_train), (x_val, y_val) = keras.datasets.mnist.load_data()
# ===============================================================
num_classes = 10
x_train = x_train.reshape(60000, 28 * 28).astype('float32') / 255
x_val = x_val.reshape(10000, 28 * 28).astype('float32') / 255
y_train = keras.utils.to_categorical(y_train, num_classes)
y_val = keras.utils.to_categorical(y_val, num_classes)
# ===============================================================
model = keras.models.Sequential()
model.add(keras.layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
model.add(keras.layers.Dense(512, activation='relu'))
model.add(keras.layers.Dense(10, activation='softmax'))
model.summary()
model.compile(loss='categorical_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
# ===============================================================
train_gen = MyGenerator(x_train, y_train, batch_size)
steps_per_epoch = int(np.ceil(x_train.shape[0] / batch_size))
history = model.fit_generator(train_gen,
                              steps_per_epoch=steps_per_epoch,
                              epochs=num_epochs,
                              validation_data=(x_val, y_val),
                              use_multiprocessing=False,
                              workers=NUM_WORKERS)
# ===============================================================
score = model.evaluate(x_val, y_val, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])
```

**Comment by evrial** [comment]
Confirm fit_generator completely ruined on windows.

**Comment by payne911** [comment]
Apparently you're supposed to use `self.lock = threading.Lock()` in your `def __init__` (use `import threading`, of course).
Then, in your `def __getitem__(self, index)`, you should begin with `with self.lock:` before trying to `return` a batch.

For my part, I haven't fully worked it out yet, and I can confirm that updating my virtual-environment has made my Generator quite buggy.

**Comment by svdHero** [comment]
@payne911: Thanks for your answer. I know about the `lock` solution. However, that still does not explain why my generator is considered not thread-safe by Keras. Also, I do not want to lock my generator if it is not necessary. That would defeat the purpose of multithreading / parallelizing, wouldn't it. But then again, the GIL does too. :laughing:

**Comment by jon-chuang** [comment]
@svdHero Is this really true? I thought that compared to lazy evaluation like in a generator, in sequences the thread is only contending for a write to the queue and could be spending time preprocessing while another thread is busy writing?

**Comment by jon-chuang** [comment]
I can confirm I have the same issue but on ubuntu.

**Comment by jon-chuang** [comment]
Turns out my issue is solved because I passed a generator to the validation generator after editing my code to use `Sequence`. Hope this helps someone.

**Comment by yongzhuo** [comment]
me too.  @evrial @payne911 

### System information
```
Windows 10 or Ubuntu 16.04.5
CPU or GPU
Python 3.6
Tensorflow 1.15.0
Keras 2.3.1
```
### Describe the current behavior
    the first model is ok when training, but it is not work when training of 2th model in 5th epoch of validation_steps, I couldn't understand  why.

```
nets = []
    for network_type in network_types:
        for embed_type in embed_types:
            for token_type in token_types:
                net = [network_type, embed_type, token_type]
                if net not in nets:
                    nets.append(net)

    for [network_type, embed_type, token_type] in nets:
        # task, "TC", "SL", "RE"
        task = "TC"
        # dir
        path_model_dir = os.path.join(path_root, "data", "model", network_type + "_" + embed_type + "_" + token_type)
        # learning-rate
        lr = 1e-5 if embed_type in ["ROBERTA", "ELECTRA", "ALBERT", "XLNET", "NEZHA", "GPT2", "BERT"] else 1e-3
        # embed-size
        embed_size = 768 if embed_type in ["ROBERTA", "ELECTRA", "ALBERT", "XLNET", "NEZHA", "GPT2", "BERT"] else 300
        embed_size = 64 if token_type in ["NGRAM"] else embed_size
        # train start
        trainer(network_type=network_type, embed_type=embed_type, token_type=token_type, task=task...)
        mm = 0
```

### Error
```
Model: "model_5"
____________________________________________________________________________________________________________________________________
Layer (type)                               Output Shape                 Param #         Connected to
====================================================================================================================================
input_4 (InputLayer)                       [(None, 512)]                0
____________________________________________________________________________________________________________________________________
embedding_3 (Embedding)                    (None, 512, 300)             648900          input_4[0][0]
____________________________________________________________________________________________________________________________________
global_average_pooling1d_1 (GlobalAverageP (None, 300)                  0               embedding_3[0][0]
____________________________________________________________________________________________________________________________________
global_max_pooling1d_1 (GlobalMaxPooling1D (None, 300)                  0               embedding_3[0][0]
____________________________________________________________________________________________________________________________________
concatenate_1 (Concatenate)                (None, 600)                  0               global_average_pooling1d_1[0][0]
                                                                                        global_max_pooling1d_1[0][0]
____________________________________________________________________________________________________________________________________
dense_2 (Dense)                            (None, 128)                  76928           concatenate_1[0][0]
____________________________________________________________________________________________________________________________________
dropout_1 (Dropout)                        (None, 128)                  0               dense_2[0][0]
____________________________________________________________________________________________________________________________________
dense_3 (Dense)                            (None, 9)                    1161            dropout_1[0][0]
====================================================================================================================================
Total params: 726,989
Trainable params: 726,989
Non-trainable params: 0
____________________________________________________________________________________________________________________________________
2020-06-30 20:57:30,486 - t00_trainer.py[line:156] - INFO: 网络(network or graph)初始化完成
2020-06-30 20:57:30,486 - t00_trainer.py[line:157] - INFO: 开始训练:
Epoch 1/32
Epoch 1/32
1/1 [==============================] - 0s 380ms/step - loss: 2.2623 - acc: 0.1111

Epoch 00001: val_loss improved from inf to 2.26227, saving model to /Macadam/macadam/data/model/FastText_RANDOM_WORD/macadam.h5
1/1 [==============================] - 5s 5s/step - loss: 2.2274 - acc: 0.1111 - val_loss: 2.2623 - val_acc: 0.1111
Epoch 2/32
Epoch 1/32
1/1 [==============================] - 1s 529ms/step - loss: 2.2518 - acc: 0.1111

Epoch 00002: val_loss improved from 2.26227 to 2.25184, saving model to /Macadam/macadam/data/model/FastText_RANDOM_WORD/macadam.h5
1/1 [==============================] - 1s 1s/step - loss: 2.2043 - acc: 0.1111 - val_loss: 2.2518 - val_acc: 0.1111
Epoch 3/32
Epoch 1/32
1/1 [==============================] - 1s 539ms/step - loss: 2.2205 - acc: 0.1111

Epoch 00003: val_loss improved from 2.25184 to 2.22048, saving model to /Macadam/macadam/data/model/FastText_RANDOM_WORD/macadam.h5
1/1 [==============================] - 1s 921ms/step - loss: 2.1471 - acc: 0.1111 - val_loss: 2.2205 - val_acc: 0.1111
Epoch 4/32
Epoch 1/32
1/1 [==============================] - 1s 667ms/step - loss: 2.2275 - acc: 0.1111

Epoch 00004: val_loss did not improve from 2.22048
1/1 [==============================] - 1s 909ms/step - loss: 2.0707 - acc: 0.2222 - val_loss: 2.2275 - val_acc: 0.1111
Epoch 5/32
Epoch 1/32
Traceback (most recent call last):
  File "/anaconda3/envs/tf15/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/data_utils.py", line 898, in get
    inputs = self.queue.get(block=True).get()
  File "/anaconda3/envs/tf15/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/anaconda3/envs/tf15/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/anaconda3/envs/tf15/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/data_utils.py", line 832, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
ValueError: generator already executing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tet_all_baidu_2019.py", line 77, in <module>
    epochs=32, early_stop=6, rate=1)
  File "/Macadam/macadam/tc/t00_trainer.py", line 159, in trainer
    graph.fit(pxy, generator_xy, train_data, dev_data=dev_data, rate=rate)
  File "/Macadam/macadam/base/graph.py", line 120, in fit
    validation_steps=lg_dev.__len__() if lg_dev else None,
  File "/anaconda3/envs/tf15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 1296, in fit_generator
    steps_name='steps_per_epoch')
  File "/anaconda3/envs/tf15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 323, in model_iteration
    steps_name='validation_steps')
  File "/anaconda3/envs/tf15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 221, in model_iteration
    batch_data = _get_next_batch(generator)
  File "/anaconda3/envs/tf15/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 363, in _get_next_batch
    generator_output = next(generator)
  File "/anaconda3/envs/tf15/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/data_utils.py", line 919, in get
    'Your generator is NOT thread-safe. '
RuntimeError: Your generator is NOT thread-safe. Keras requires a thread-safe generator when `use_multiprocessing=False, workers > 1`.

```
