### ISSUE TITLE
Problems with saving model

### ISSUE THREAD

**Issue by volunL** [keras-team/keras#13237]
I get back this error message when I use the function "save" to save my model.

Traceback (most recent call last):
File "/Users/volun/Github/DigitRecognise/OwnTest.py", line 176, in 
model.save(mp)
File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/network.py", line 1090, in save
save_model(self, filepath, overwrite, include_optimizer)
File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/saving.py", line 382, in save_model
_serialize_model(model, f, include_optimizer)
File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/saving.py", line 132, in _serialize_model
'config': model.optimizer.get_config()
File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/optimizers.py", line 517, in get_config
config = {'lr': float(K.get_value(self.lr)),
File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2407, in get_value
return x.eval(session=get_session())
AttributeError: 'float' object has no attribute 'eval'

**Comment by hr21** [comment]
@volunL  can you describe what were you trying to do, in which IDE and your lines of code

**Comment by volunL** [comment]
I want to save my model I've trained on Keras in Pycharm.
Python version 3.6
Keras verison 2.2.4
tensorflow  version 1.14
Here is my  codes:



def get_cnn_model():
    model = Sequential([
        Lambda(standardize, input_shape=(28,28,1)),
     
        Convolution2D(32,(3,3), activation='relu'),
        Convolution2D(32,(3,3), activation='relu'),
      
        MaxPooling2D(),
       
        Convolution2D(64,(3,3), activation='relu'),
        Convolution2D(64,(3,3), activation='relu'),
     
        MaxPooling2D(),
   
        Flatten(),
    
        Dense(512, activation='relu'),
        Dense(10, activation='softmax')
        ])
    model.compile(Adam(), loss='categorical_crossentropy',
                  metrics=['accuracy'])
    return model


if __name__ == '__main__':
           model = get_cnn_model()
           
           #training process
            history = model.fit_generator(generator=batches, steps_per_epoch=batches.n, epochs=EPOCHS,validation_data=val_batches, validation_steps=val_batches.n)


           print("Saving model to disk \n")
           mp = "./digitRecg_model.h5"
           model.save(mp)      # It can't be saved. I don't know why.

**Comment by volunL** [comment]
> @volunL can you describe what were you trying to do, in which IDE and your lines of code

thanks
