### ISSUE TITLE
Passing TensorBoard callback to Model.fit() throws 'Sequential' object has no attribute 'run_eagerly' error

### ISSUE THREAD

**Issue by Kamaropoulos** [keras-team/keras#13251]
**System information**  
- OS Platform and Distribution:  Windows 10 Insider Preview 18965.1005
- TensorFlow backend (yes / no):  Yes
- TensorFlow version:  1.14.0
- Keras version:  2.2.5
- Python version:  3.7.3
- GPU model and memory:  NVIDIA GTX 1050 Ti 4GB

**Describe the current behavior**  
So I'm trying to get TensorBoard to work with a model. I create the model as follows:
```python
model = Sequential([
            Dense(fc1_dims, input_shape=(input_dims,)),
            Activation('relu'),
            Dense(fc2_dims),
            Activation('relu'),
            Dense(n_actions)])

model.compile(optimizer=Adam(lr=lr), loss='mse')
```

Then, when it comes to fitting, I do it as follows:
```python
model.fit(state, q_target, verbose=0)
```

This works fine.

Now, I want to add TensorBoard to it so I can see how things change over time.
I create the TensorBoard callback:
```python
from time import time
from tensorflow.python.keras.callbacks import TensorBoard
tensorboard = TensorBoard(log_dir="logs\{}".format(time()), histogram_freq=0)
```

and I pass it to the fit method, so instead of the previous fit call, I do:
```python
model.fit(state, q_target, verbose=0, callbacks=[tensorboard])
```

When I try to run the code this time, when it reaches the fit call, it throws the following error:
```
Traceback (most recent call last):
  File ".\main_keras.py", line 54, in <module>
    agent.learn(tensorboard_cb=tensorboard)
  File "C:\Projects\<PROJECT_DIR>\<FILENAME>.py", line 105, in learn
    _ = self.q_eval.fit(state, q_target, verbose=0, callbacks=[tensorboard_cb])
  File "C:\Users\<USER_DIR>\Anaconda3\lib\site-packages\keras\engine\training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "C:\Users\<USER_DIR>\Anaconda3\lib\site-packages\keras\engine\training_arrays.py", line 117, in fit_loop
    callbacks.set_model(callback_model)
  File "C:\Users\<USER_DIR>\Anaconda3\lib\site-packages\keras\callbacks.py", line 54, in set_model
    callback.set_model(model)
  File "C:\Users\<USER_DIR>\Anaconda3\lib\site-packages\tensorflow\python\keras\callbacks.py", line 1509, in set_model
    if not model.run_eagerly:
AttributeError: 'Sequential' object has no attribute 'run_eagerly'
```

If I go to `keras\callbacks.py` and modify the `set_model` method:
```python
  def set_model(self, model):
    """Sets Keras model and writes graph if specified."""
    self.model = model
    with context.eager_mode():
      self._close_writers()
      if self.write_graph:
        with self._get_writer(self._train_run_name).as_default():
          with summary_ops_v2.always_record_summaries():
            if not model.run_eagerly:
                summary_ops_v2.graph(K.get_graph(), step=0)

            summary_writable = (
                self.model._is_graph_network or  # pylint: disable=protected-access
                self.model.__class__.__name__ == 'Sequential')  # pylint: disable=protected-access
            if summary_writable:
              summary_ops_v2.keras_model('keras', self.model, step=0)

    if self.embeddings_freq:
      self._configure_embeddings()
```

to this:

```python
  def set_model(self, model):
    """Sets Keras model and writes graph if specified."""
    self.model = model
    with context.eager_mode():
      self._close_writers()
      if self.write_graph:
        with self._get_writer(self._train_run_name).as_default():
          with summary_ops_v2.always_record_summaries():
            # if not model.run_eagerly:
            summary_ops_v2.graph(K.get_graph(), step=0)

            summary_writable = (
                # self.model._is_graph_network or  # pylint: disable=protected-access
                self.model.__class__.__name__ == 'Sequential')  # pylint: disable=protected-access
            if summary_writable:
              summary_ops_v2.keras_model('keras', self.model, step=0)

    if self.embeddings_freq:
      self._configure_embeddings()
```

the callback works fine for my case.

Why is this happening though? Am I doing something wrong? Is there a better way to go for this? What are your thoughts and suggestions about it?

**Describe the expected behavior**  
Have the TensorBoard function properly without having to edit any of the internal Keras files.

**Code to reproduce the issue**  
Here's some bare minimum code that reproduces the above mentioned behavior:
```python
from keras.layers import Dense, Activation
from keras.models import Sequential, load_model
from keras.optimizers import Adam
import numpy as np

from time import time
from tensorflow.python.keras.callbacks import TensorBoard
tensorboard = TensorBoard(log_dir="logs\{}".format(time()), histogram_freq=0)

model = Sequential([
            Dense(256, input_shape=(8,)),
            Activation('relu'),
            Dense(256),
            Activation('relu'),
            Dense(4)])

model.compile(optimizer=Adam(lr=0.0005), loss='mse')

_ = model.fit(np.zeros((1000, 8)), model.predict(np.zeros((1000, 8))), verbose=0, callbacks=[tensorboard])
```

**Comment by Ian-Mint** [comment]
I have this same issue:
tensorflow 2.1.0
tensorboard 2.1.0
keras 2.3.1

My solution was the following change in `callbacks.py`:
```
-     self._log_write_dir = distributed_file_utils.write_dirpath(
-         self.log_dir, self.model._get_distribution_strategy())  # pylint: disable=protected-access
+    self._log_write_dir = self.log_dir
```

I'm not using a distributed file system, so this is no issue for me.

**Comment by NomadicCode** [comment]
Same issue with

```py
def create_network(network_input, n_vocab):
    model = keras.models.Sequential()

    print(network_input.shape)

    model.add(
        
        keras.layers.LSTM(512,
                          input_shape=(network_input),
                          recurrent_dropout=0.3,
                          return_sequences=True))

    model.add(
        keras.layers.LSTM(
            512,
            return_sequences=True,
            recurrent_dropout=0.3,
        ))

    model.add(keras.layers.LSTM(512))

    model.add(keras.layers.BatchNormalization())

    model.add(keras.layers.Dropout(0.3))

    model.add(keras.layers.Dense(256))

    model.add(keras.layers.Activation('relu'))

    model.add(keras.layers.BatchNormalization())

    model.add(keras.layers.Dense(n_vocab))

    model.add(keras.layers.Activation('softmax'))

    model.compile(loss="categorical_crossentropy", optimizer="rmsprop")

    return model
```
