### ISSUE TITLE
IndexError while loading weigths of nested models with frozen layers

### ISSUE THREAD

**Issue by GuillaumeGuebin** [keras-team/keras#13259]
**System information**  
- Have I written custom code (as opposed to using example directory):  Yes
- OS Platform and Distribution :  Windows
- TensorFlow backend (yes / no):  Yes
- TensorFlow version:  1.13.1
- Keras version:  2.2.5
- Python version:  '3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]'
- cuDNN version:  7.3.1, cuda 10.0_0, cuda_toolkit 10.0.130
- GPU model and memory:  GeForce GTX 1080 Ti 11GB

**Describe the current behavior**  
Get indexErrror when trying to load a trained model or its weights.

I tried to switch to tensorflow.python.keras as described in #10777  but it didn't work.
I don't get an error if the layers are Trainable.
I don't get an error if instead of using the base_network + meta_network, I used directly the ranking function. (The problem is then that my branches don't have the same weights of course.)

**So it seems that the problem come when using frozen layers in a nested model.**
 
**Code to reproduce the issue** 
```
def create_base_network(input_dim):
    """
    The main part of the network, the one who give scores to each pictures
    :param input_dim: Dimension of input pictures during training
    :return: keras object model
    """
    feature_extractor = VGG19(weights="imagenet", include_top=False, input_shape=input_dim)
    for layer in feature_extractor.layers[:17]:
        layer.trainable = False

    inp = Input(shape=input_dim, name='input_image')
    base = feature_extractor(inp)
    base = Flatten(name='Flatten')(base)
    base = Dense(64, activation='relu', name='Dense_1')(base)
    base = BatchNormalization(name='BN1')(base)
    base = Dropout(0.49, name='Drop_1')(base)
    base = Dense(1, name="Dense_Output")(base)

    base_network = Model(inp, base, name='Scoring_model')
    return base_network


def create_meta_network(input_dim):
    """
    Second network that teach the first how to rank pictures

    :param input_dim: dimensions of pictures
    :return: keras object model
    """
    input_left = Input(shape=input_dim, name='left_input')
    input_right = Input(shape=input_dim, name='right_input')

    base_network = create_base_network(input_dim)

    left_score = base_network(input_left)
    right_score = base_network(input_right)

    # Subtract scores
    diff = Subtract()([left_score, right_score])

    # Pass difference through sigmoid function.
    prob = Activation("sigmoid", name="Activation_sigmoid")(diff)
    model = Model(inputs=[input_left, input_right], outputs=prob, name="Meta_Model")
    sgd = SGD(lr=1e-5, decay=1e-6, momentum=0.393, nesterov=True)
    model.compile(optimizer=sgd, loss="binary_crossentropy", metrics=['accuracy'])

    return model

def ranking_network(input_dim):

    feature_extractor = VGG19(weights="imagenet", include_top=False, input_shape=input_dim)
    for layer in feature_extractor.layers[:17]:
        layer.trainable = False

    img_left = Input(shape=input_dim)
    base_left = feature_extractor(img_left)
    base_left = Flatten(name='Flatten_left')(base_left)
    base_left = Dense(64, activation='relu', name='Dense_1_left')(base_left)
    base_left = BatchNormalization(name='BN1_left')(base_left)
    base_left = Dropout(0.49, name='Drop_1_left')(base_left)
    base_left = Dense(1, name="Dense_Output_left")(base_left)

    img_right = Input(shape=input_dim)
    base_right = feature_extractor(img_right)
    base_right = Flatten(name='Flatten_right')(base_right)
    base_right = Dense(64, activation='relu', name='Dense_1_right')(base_right)
    base_right = BatchNormalization(name='BN1_right')(base_right)
    base_right = Dropout(0.49, name='Drop_1_right')(base_right)
    base_right = Dense(1, name="Dense_Output_right")(base_right)

    # Subtract scores
    diff = Subtract()([base_left, base_right])

    # Pass difference through sigmoid function.
    prob = Activation("sigmoid", name="Activ_sigmoid")(diff)
    model = Model(inputs=[img_left, img_right], outputs=prob)
    sgd = SGD(lr=1e-5, decay=1e-6, momentum=0.393, nesterov=True)
    model.compile(optimizer=sgd, loss="binary_crossentropy", metrics=['accuracy'])

    return model
``` 

**Other info / logs**  
```
Traceback (most recent call last):
  File "C:\Users\msawada\.conda\envs\deeplearning\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-18a3e434c8b8>", line 1, in <module>
    test = load_model(os.path.join(folder_path, 'fitted_model.h5'))
  File "C:\Users\msawada\.conda\envs\deeplearning\lib\site-packages\keras\engine\saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "C:\Users\msawada\.conda\envs\deeplearning\lib\site-packages\keras\engine\saving.py", line 274, in _deserialize_model
    reshape=False)
  File "C:\Users\msawada\.conda\envs\deeplearning\lib\site-packages\keras\engine\saving.py", line 682, in preprocess_weights_for_loading
    weights = convert_nested_model(weights)
  File "C:\Users\msawada\.conda\envs\deeplearning\lib\site-packages\keras\engine\saving.py", line 658, in convert_nested_model
    original_backend=original_backend))
  File "C:\Users\msawada\.conda\envs\deeplearning\lib\site-packages\keras\engine\saving.py", line 682, in preprocess_weights_for_loading
    weights = convert_nested_model(weights)
  File "C:\Users\msawada\.conda\envs\deeplearning\lib\site-packages\keras\engine\saving.py", line 670, in convert_nested_model
    original_backend=original_backend))
  File "C:\Users\msawada\.conda\envs\deeplearning\lib\site-packages\keras\engine\saving.py", line 800, in preprocess_weights_for_loading
    elif layer_weights_shape != weights[0].shape:
IndexError: list index out of range
```

**Comment by ysyyork** [comment]
Any progress on this? is there any workaround?
