### ISSUE TITLE
Update Keras 2.2.4 to Keras 2.3.0 cases Root errors.

### ISSUE THREAD

**Issue by kiflowb777** [keras-team/keras#13356]
**System information**  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.14.0
- Keras version:  2.3.0
- Python version:  3.6.1
- CUDA/cuDNN version:  10/7.5.0
- GPU model and memory:  RTX 2060 6GB

After updating Keras from 2.2.4 to 2.3.0 After the update I get the following error:

```
ERROR	2 root error(s) found.
  (0) Invalid argument: transpose expects a vector of size 3. But input(1) is a vector of size 4
	 [[{{node batch_normalization_1/FusedBatchNorm-0-TransposeNHWCToNCHW-LayoutOptimizer}}]]
	 [[final_fc/Softmax/_103]]
  (1) Invalid argument: transpose expects a vector of size 3. But input(1) is a vector of size 4
	 [[{{node batch_normalization_1/FusedBatchNorm-0-TransposeNHWCToNCHW-LayoutOptimizer}}]]
0 successful operations.
0 derived errors ignored.	__main__:173
Traceback (most recent call last):
  File "C:\Project\project.py", line 82, in test
    predictions = K.function([[image], 0.])[0]
  File "C:\python\lib\site-packages\tensorflow\python\keras\backend.py", line 3292, in __call__
    run_metadata=self.run_metadata)
  File "C:\python\lib\site-packages\tensorflow\python\client\session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: transpose expects a vector of size 3. But input(1) is a vector of size 4
	 [[{{node batch_normalization_1/FusedBatchNorm-0-TransposeNHWCToNCHW-LayoutOptimizer}}]]
	 [[final_fc/Softmax/_103]]
  (1) Invalid argument: transpose expects a vector of size 3. But input(1) is a vector of size 4
	 [[{{node batch_normalization_1/FusedBatchNorm-0-TransposeNHWCToNCHW-LayoutOptimizer}}]]
0 successful operations.
0 derived errors ignored.
```

K is `from keras import backend as K `
image is ndarray

**Comment by fchollet** [comment]
Thanks for the report, could you provide a code snippet to reproduce the issue?

Have you tried switching your code to tf.keras?

**Comment by kiflowb777** [comment]
My code works when I swich to tf.keras, but TensorFlow 1.14.0 uses Keras 2.2.4
```
>>>import tensorflow as tf
>>>keras_version = tf.keras.__version__
>>>keras_version
2.2.4-tf
```
