### ISSUE TITLE
Keras:  layer.outbound_nodes.append(self) AttributeError: 'LeakyReLU' object has no attribute 'outbound_nodes'

### ISSUE THREAD

**Issue by ShibaPrasad** [keras-team/keras#13394]
Hi,

I am getting below error:

layer.outbound_nodes.append(self)
AttributeError: 'LeakyReLU' object has no attribute 'outbound_nodes'
![image](https://user-images.githubusercontent.com/12077129/66236076-270bd000-e6b7-11e9-8b97-58902451404a.png)

**_Would you please help me on this?_**
--------------------------------------------
/user/iibi/skuanar/anaconda3/bin/python /user/iibi/skuanar/Downloads/Keras-GAN-master/cyclegan/cyclegan.py
Using TensorFlow backend.
WARNING:tensorflow:From /user/iibi/skuanar/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "/user/iibi/skuanar/Downloads/Keras-GAN-master/cyclegan/cyclegan.py", line 257, in <module>
    gan = CycleGAN()
  File "/user/iibi/skuanar/Downloads/Keras-GAN-master/cyclegan/cyclegan.py", line 53, in __init__
    self.d_A = self.build_discriminator()
  File "/user/iibi/skuanar/Downloads/Keras-GAN-master/cyclegan/cyclegan.py", line 153, in build_discriminator
    d2 = d_layer(d1, self.df*2)
  File "/user/iibi/skuanar/Downloads/Keras-GAN-master/cyclegan/cyclegan.py", line 147, in d_layer
    d = InstanceNormalization()(d)
  File "/user/iibi/skuanar/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 584, in __call__
    inputs, outputs, args, kwargs)
  File "/user/iibi/skuanar/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1416, in _set_connectivity_metadata_
    input_tensors=inputs, output_tensors=outputs, arguments=kwargs)
  File "/user/iibi/skuanar/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1524, in _add_inbound_node
    arguments=arguments)
  File "/user/iibi/skuanar/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1742, in __init__
    layer.outbound_nodes.append(self)
AttributeError: 'LeakyReLU' object has no attribute 'outbound_nodes'

**Comment by tuanzhangCS** [comment]
What's your version?
