### ISSUE TITLE
missing module error

### ISSUE THREAD

**Issue by kelvinwop** [keras-team/keras#13480]
**System information**  
- custom code 
- win 10
- TensorFlow backend: yes
- TensorFlow version:  `(__version__)` 2.0.0
- Keras version:  `(__version__)` 2.3.1
- Python version:  3.7.1
- CUDA/cuDNN version:  n/a
- GPU model and memory:  n/a

**Describe the current behavior**  
![image](https://user-images.githubusercontent.com/30770221/67238664-2c854c00-f413-11e9-9528-32265653e494.png)

**Describe the expected behavior**  
not that

**Code to reproduce the issue**  
```python
def cnn_gru_model(data):
    #input layer
    input_x = keras.Input(shape=(np.shape(data['x_train'])[1], 1), name="x_input")
    print(input_x)
    
    conv = (Conv1D(64, 1, activation='relu'))(input_x)
    conv = BatchNormalization()(conv)
    conv = (Conv1D(64, 2, activation='relu'))(conv)
    conv = BatchNormalization()(conv)
    
    gru = (CuDNNGRU(64, return_sequences=True))(conv)
    gru = (CuDNNGRU(32, return_sequences=True))(gru)
    gru = (CuDNNGRU(16, return_sequences=False))(gru)
    
    gru = layers.Dense(64, activation='sigmoid')(gru)
    gru = layers.Dense(32, activation='sigmoid')(gru)
    y = layers.Dense(1, activation='sigmoid')(gru)
    
    #model
    #classifier = Model([input_x, input_xd], y)

    classifier = Model([input_x], y)
    classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return classifier

def train_model(model, t_in, v_in, t_out, v_out, MODEL_NAME, class_weight=None):
    callbacks = [EarlyStopping(monitor='val_loss', patience=PATIENCE),
             ModelCheckpoint(filepath=MODEL_PATH+"/"+MODEL_NAME+".h5", monitor='val_loss', verbose=2, save_best_only=True)]
    model.summary()
    model.fit(x={"x_input": t_in}, y=t_out, shuffle=True, epochs=EPOCHS, callbacks=callbacks, batch_size=BATCH_SIZE,
              verbose=1, validation_data=([v_in], v_out), class_weight=class_weight)
    return model

network = cnn_gru_model({'x_train': t_in})
model = train_model(network)

```

**Other info / logs**  

more code at
https://github.com/kelvinwop/classifiers/blob/master/circles.ipynb

**Comment by kelvinwop** [comment]
I changed the CuDNN calls to the normal ones and it worked so I guess that was the problem 🤷‍♂

**Comment by momih** [comment]
I get the same when I upgraded to TF 2.0. I don't want to use the normal ones, what should be done about this?

```
Traceback (most recent call last):

  File "/home/momi/Documents/projects/c1/train.py", line 248, in rnn_model
    x = layer(x_in)

  File "/home/momi/anaconda3/lib/python3.7/site-packages/keras/layers/recurrent.py", line 541, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)

  File "/home/momi/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)

  File "/home/momi/anaconda3/lib/python3.7/site-packages/keras/engine/base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))

  File "/home/momi/anaconda3/lib/python3.7/site-packages/keras/layers/cudnn_recurrent.py", line 226, in build
    from tensorflow.contrib.cudnn_rnn.python.ops import cudnn_rnn_ops

ModuleNotFoundError: No module named 'tensorflow.contrib
```
