### ISSUE TITLE
Problem with Keras application model when used with ThreadPoolExecutor().

### ISSUE THREAD

**Issue by ismaeelnawaz** [keras-team/keras#13526]
**System information**  
- Have I written custom code (as opposed to using example directory):  yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  19.04
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  2.0
- Keras version:  2.3.1
- Python version: 3.7
- CUDA/cuDNN version:  N/A
- GPU model and memory:  N/A

**Describe the current behavior**  

I am trying to extract image features using Keras application models. For fast processing, I used this method with python ThreadPoolExexutor().

with ThreadPoolExecutor(1) as executor:
    results = executor.map(feat.feature_cnn, links)

when I tried to access results (Generator Type)

for result in results:
    print(result)

Output:

Traceback (most recent call last):
  File "test.py", line 34, in <module>
    for item in results:
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ismaeel/Desktop/DuplicationTool/DuplicationTool/Descriptor/Feature.py", line 26, in feature_cnn
    feat = self.model.predict(img)
  File "/home/ismaeel/Desktop/DuplicationTool/DuplicationTool/toolenv/lib/python3.7/site-packages/Keras-2.3.1-py3.7.egg/keras/engine/training.py", line 1452, in predict
    if self._uses_dynamic_learning_phase():
  File "/home/ismaeel/Desktop/DuplicationTool/DuplicationTool/toolenv/lib/python3.7/site-packages/Keras-2.3.1-py3.7.egg/keras/engine/training.py", line 382, in _uses_dynamic_learning_phase
    not isinstance(K.learning_phase(), int))
  File "/home/ismaeel/Desktop/DuplicationTool/DuplicationTool/toolenv/lib/python3.7/site-packages/Keras-2.3.1-py3.7.egg/keras/backend/tensorflow_backend.py", line 73, in symbolic_fn_wrapper
    if _SYMBOLIC_SCOPE.value:
AttributeError: '_thread._local' object has no attribute 'value'

**Describe the expected behavior**  

It should display the features of images

**Code to reproduce the issue**    

feature.py
```
import numpy as np
from numpy import linalg as LA
import urllib

from keras.applications.inception_v3 import InceptionV3
from keras.preprocessing.image import image
from keras.applications.inception_v3 import preprocess_input

class Feature:

    def __init__(self):

        self.input_shape = (224, 224, 3) # CNN Input 512 feature vector length
        self.weight = 'imagenet'
        self.pooling = 'max'
        self.model = InceptionV3(weights = self.weight, input_shape = (self.input_shape[0], 
                        self.input_shape[1], self.input_shape[2]), pooling = self.pooling, include_top = False)

    def feature_cnn(self, imagelink):
        
        img = image.load_img(imagelink, target_size=(self.input_shape[0], self.input_shape[1]))
        img = image.img_to_array(img)
        img = np.expand_dims(img, axis=0)
        img = preprocess_input(img)
        feat = self.model.predict(img)
        norm_feat = feat[0]/LA.norm(feat[0])
        return norm_feat


```
test.py

```
from concurrent.futures import ThreadPoolExecutor
from Descriptor.Feature import Feature

feat = Feature()

image = 'airplane.png'

links = [image, image, image, image, image, image, image, image, image, image, image, image, image, image, image]

with ThreadPoolExecutor(1) as executor:
    results = executor.map(feat.feature_cnn, links)

for item in results:
    print(item)
```

.

**Comment by wangyexiang** [comment]
Same issue. I am trying to train a model in QThread(multi-thread with PyQt5), and I got 
 ```
File "D:\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 73, in symbolic_fn_wrapper
    if _SYMBOLIC_SCOPE.value:
AttributeError: '_thread._local' object has no attribute 'value'
```
**If I downgrade tensorflow to 1.14, It works well.**

- TensorFlow backend (yes / no): yes
- TensorFlow version: 2.0(cpu)
- Keras version: 2.3.1
- Python version: 3.7

How to fix it?. @Dref360 @fchollet

**Comment by wangyexiang** [comment]
Dear sir, please do not close this issue. I think this issue still exist with tensorflow2.0 backend@ismaeelnawaz
