### ISSUE TITLE
Calling a simple Keras model inside a @tf.function concrete function produces error

### ISSUE THREAD

**Issue by tailsu** [keras-team/keras#13671]
**System information**  
- Have I written custom code (as opposed to using example directory):  yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  macOS Mojave
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  2.0.0
- Keras version:  2.3.1
- Python version:  3.7.5 x64
- CUDA/cuDNN version:  none
- GPU model and memory:  none

Tensorflow installed using `pip install tensorflow`; wheel came from `https://files.pythonhosted.org/packages/2c/72/6b3264aa2889b7dde7663464b99587d95cd6a5f3b9b30181f14d78a63e64/tensorflow-2.0.0-cp37-cp37m-macosx_10_11_x86_64.whl`

**Code to reproduce the issue**  
```python
import numpy as np
import tensorflow as tf

def build_model():
    from keras.layers import Input, Multiply
    from keras.models import Model
    
    inputs = x = Input(shape=(4, 4, 3), name='image')
    x = Multiply()([x, x])

    model = Model(inputs, x)
    return model

# Create an array of all two's
_input = np.full(shape=(1, 4, 4, 3), fill_value=2, dtype='float32')

_model = build_model()
print(_model.predict(_input))
# correctly prints [[[[4. 4. 4.] ....

# wrap model in a concrete function
@tf.function
def model_func(inputs):
    return _model(inputs)

print(model_func(_input))
```

**Describe the current behavior** 
The code above crashes when calling `model_func` with:

```
Traceback (most recent call last):
  File "/Users/stefan/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/Users/stefan/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/Users/stefan/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/stefan/Documents/dc-form-model/scratch.py", line 23, in <module>
    print(model_func(_input))
  File "/Users/stefan/.virtualenvs/dc-form-model/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/Users/stefan/.virtualenvs/dc-form-model/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 503, in _call
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "/Users/stefan/.virtualenvs/dc-form-model/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 408, in _initialize
    *args, **kwds))
  File "/Users/stefan/.virtualenvs/dc-form-model/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1848, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/Users/stefan/.virtualenvs/dc-form-model/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2150, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/stefan/.virtualenvs/dc-form-model/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2041, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/Users/stefan/.virtualenvs/dc-form-model/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/stefan/.virtualenvs/dc-form-model/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 358, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/stefan/.virtualenvs/dc-form-model/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 905, in wrapper
    raise e.ag_error_metadata.to_exception(e)
NameError: in converted code:

    /Users/stefan/Documents/dc-form-model/scratch.py:21 model_func  *
        return _model(inputs)
    /Users/stefan/.virtualenvs/dc-form-model/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:417 symbolic_fn_wrapper  *
        return func(*args, **kwargs)
    /Users/stefan/.virtualenvs/dc-form-model/lib/python3.7/site-packages/keras/engine/base_layer.py:506 __call__  *
        output_shape = self.compute_output_shape(input_shape)
    /Users/stefan/.virtualenvs/dc-form-model/lib/python3.7/site-packages/keras/engine/network.py:656 compute_output_shape  *
        output_shape = layer.compute_output_shape(
    /Users/stefan/.virtualenvs/dc-form-model/lib/python3.7/site-packages/keras/layers/merge.py:173 compute_output_shape  *
        output_shape = self._compute_elemwise_op_output_shape(output_shape,
    /Users/stefan/.virtualenvs/dc-form-model/lib/python3.7/site-packages/keras/layers/merge.py:50 _compute_elemwise_op_output_shape  *
        for i, j in zip(shape1[-len(shape2):], shape2):
    /Users/stefan/.virtualenvs/dc-form-model/lib/python3.7/site-packages/tensorflow_core/python/autograph/operators/control_flow.py:339 for_stmt
        return _py_for_stmt(iter_, extra_test, body, get_state, set_state, init_vars)
    /Users/stefan/.virtualenvs/dc-form-model/lib/python3.7/site-packages/tensorflow_core/python/autograph/operators/control_flow.py:348 _py_for_stmt
        if extra_test is not None and not extra_test(*state):
    /var/folders/b3/6jq1g5k137z_4_51s5xmmfx00000gp/T/tmpyfgvnk8n.py:158 extra_test
        return ag__.not_(do_return_2)

    NameError: free variable 'do_return_2' referenced before assignment in enclosing scope
```

**Describe the expected behavior**  
I expect the `model_func` call to produce exactly the same output as the `model.predict` call. 

Isn't this the exactly correct way to convert a keras model to a TF concrete function? My hope is to eventually be able to convert my entire keras model into a concrete function for export to TF Lite, but the way is mired with errors such as this one.

**Comment by xusky69** [comment]
I've noticed that running model.predict() inside a tf.function causes an error due to the fact that keras model.predict() returns a numpy array. Manually casting the predictions to tf inside the function has removed the error for me, but it has slowed down the execution by a factor of 8.

**Comment by xusky69** [comment]
Another minimal example that results into an error is the following (tf 2.1 rc1):

```
%tensorflow_version 2.x
import tensorflow as tf
import numpy as np
from tensorflow import keras

x = np.random.random((10,16))
model = keras.Sequential()
model.add(keras.layers.Dense(32, input_shape=(16,), activation = tf.nn.relu))
y = model.predict(x)

@tf.function
def test(model, x):

    y = model.predict(x, steps = 1)

    return y

y = test(model,x)
```

Which results in the following:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-28-f1d2df9dacd3> in <module>()
----> 1 y = test(model,x)

8 frames
/tensorflow-2.1.0/python3.6/tensorflow_core/python/framework/func_graph.py in wrapper(*args, **kwargs)
    966           except Exception as e:  # pylint:disable=broad-except
    967             if hasattr(e, "ag_error_metadata"):
--> 968               raise e.ag_error_metadata.to_exception(e)
    969             else:
    970               raise

ValueError: in converted code:

    <ipython-input-14-828393dea4e3>:4 test  *
        y = model.predict(x, steps = 1)
    /tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/engine/training.py:1013 predict
        use_multiprocessing=use_multiprocessing)
    /tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/engine/training_arrays.py:728 predict
        callbacks=callbacks)
    /tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/engine/training_arrays.py:189 model_iteration
        f = _make_execution_function(model, mode)
    /tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/engine/training_arrays.py:571 _make_execution_function
        return model._make_execution_function(mode)
    /tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/engine/training.py:2131 _make_execution_function
        self._make_predict_function()
    /tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/engine/training.py:2121 _make_predict_function
        **kwargs)
    /tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/backend.py:3760 function
        return EagerExecutionFunction(inputs, outputs, updates=updates, name=name)
    /tensorflow-2.1.0/python3.6/tensorflow_core/python/keras/backend.py:3644 __init__
        raise ValueError('Unknown graph. Aborting.')

    ValueError: Unknown graph. Aborting.
```

**Comment by thomasr96** [comment]
Did you ever get a workaround? I'm having this issue

**Comment by XXZhou25** [comment]
> I had the same error and switched `keras` to `tensorflow.keras` in the imports. That is when I run the bellow code, I get the following output.
> Code:
> 
> ```
> import numpy as np
> import tensorflow as tf
> 
> def build_model():
>     from tensorflow.keras.layers import Input, Multiply
>     from tensorflow.keras.models import Model
>     
>     inputs = x = Input(shape=(4, 4, 3), name='image')
>     x = Multiply()([x, x])
> 
>     model = Model(inputs, x)
>     return model
> 
> # Create an array of all two's
> _input = np.full(shape=(1, 4, 4, 3), fill_value=2, dtype='float32')
> 
> _model = build_model()
> print(_model.predict(_input))
> # correctly prints [[[[4. 4. 4.] ....
> 
> # wrap model in a concrete function
> @tf.function
> def model_func(inputs):
>     return _model(inputs)
> 
> print(model_func(_input))
> ```
> 
> Output:
> 
> ```
> [[[[4. 4. 4.]
>    [4. 4. 4.]
>    [4. 4. 4.]
>    [4. 4. 4.]]
> 
>   [[4. 4. 4.]
>    [4. 4. 4.]
>    [4. 4. 4.]
>    [4. 4. 4.]]
> 
>   [[4. 4. 4.]
>    [4. 4. 4.]
>    [4. 4. 4.]
>    [4. 4. 4.]]
> 
>   [[4. 4. 4.]
>    [4. 4. 4.]
>    [4. 4. 4.]
>    [4. 4. 4.]]]]
> tf.Tensor(
> [[[[4. 4. 4.]
>    [4. 4. 4.]
>    [4. 4. 4.]
>    [4. 4. 4.]]
> 
>   [[4. 4. 4.]
>    [4. 4. 4.]
>    [4. 4. 4.]
>    [4. 4. 4.]]
> 
>   [[4. 4. 4.]
>    [4. 4. 4.]
>    [4. 4. 4.]
>    [4. 4. 4.]]
> 
>   [[4. 4. 4.]
>    [4. 4. 4.]
>    [4. 4. 4.]
>    [4. 4. 4.]]]], shape=(1, 4, 4, 3), dtype=float32)
> ```

Still have the same error. I am so confused.

**Comment by FarisHijazi** [comment]
tensorflow 2.3.0 version explains this error:

```
RuntimeError: Detected a call to `Model.predict` inside a `tf.function`. `Model.predict is a high-level endpoint that manages its own `tf.function`. Please move the call to `Model.predict` outside of all enclosing `tf.function`s. Note that you can call a `Model` directly on `Tensor`s inside a `tf.function` like: `model(x)`.
```

But what if I really need to run a model inside a tf function? I'm using tf dataset api and I must use a model inside it

**Comment by markub3327** [comment]
@FarisHijazi 

  You must use model(x) calling instead of `model.predict(x)`, because `predict` is a part of high-level Keras API. In tf graphs can be used only tf funclions, but not Keras.

**Comment by zachmayer** [comment]
If I use `model(x)`, the result is a tf tensor.  How do I turn it into a numpy array?

How do I set batch size for predictions for `model(x)`?

**Comment by markub3327** [comment]
@zachmayer 

You can use `.numpy` to get only NumPy array from tf tensor.

To add a new batch axis you can use `tf.expand_dims(tensor, axis=0)` or `tf.reshape`.
