### ISSUE TITLE
Merge two models into one: cannot load from h5.

### ISSUE THREAD

**Issue by MoyanZitto** [keras-team/keras#13696]
**System information**  
- Have I written custom code (as opposed to using example directory):  No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  CentOS
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.14.0
- Keras version:  2.3.1
- Python version:  3.6
- CUDA/cuDNN version:   CUDA-10.0
- GPU model and memory: Not a problem.  
------------------------------------------------------------------------------------

modelA and modelB are two models with same structure.

modelA input shape: (None, dim1, dim2, None)
modelB input shape: (None, dim1, dim2, None)

the last dim is timestep so we can set it to None. 

To merge this two models into one, I'd like to run the following code:
```python
modelA = load_model(modelApath)
modelB = load_model(modelBpath)

new_input = Input((dim1,dim2,2000)) # I want a fixed timestep now, say 2000

## reset layer names to avoid name conflicts
for layer in modelA.layers:
    layer.name = "A_" + layer.name
for layer in modelB.layers:
    layer.name = "B_"+layer.name

modelA.name = "A"
mdoelB.name = "B"

out1 = modelA(new_input)
out2 = modelB(new_input)

new_model = Model([new_input], [out1,out2])

res = new_model.predict(feat) # will print correct result
new_model.save("new_model.h5") #save to local
```

Looks perfect.

But if I want to save the model to disk and reuse it, I'll get an error

```python
model = load_model("new_model.h5") # raise exception
model.summary()
```
Whole traceback

```traceback
Traceback (most recent call last):
  File "generate_new_model.py", line 75, in <module>
    model_new = load_model("new_model.h5")
  File "/data1/moyanzitto/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/data1/moyanzitto/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "/data1/moyanzitto/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py", line 274, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/data1/moyanzitto/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py", line 627, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/data1/moyanzitto/anaconda3/lib/python3.6/site-packages/keras/layers/__init__.py", line 168, in deserialize
    printable_module_name='layer')
  File "/data1/moyanzitto/anaconda3/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 147, in deserialize_keras_object
    list(custom_objects.items())))
  File "/data1/moyanzitto/anaconda3/lib/python3.6/site-packages/keras/engine/network.py", line 1075, in from_config
    process_node(layer, node_data)
  File "/data1/moyanzitto/anaconda3/lib/python3.6/site-packages/keras/engine/network.py", line 1025, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "/data1/moyanzitto/anaconda3/lib/python3.6/site-packages/keras/engine/base_layer.py", line 506, in __call__
    output_shape = self.compute_output_shape(input_shape)
  File "/data1/moyanzitto/anaconda3/lib/python3.6/site-packages/keras/engine/network.py", line 612, in compute_output_shape
    str(len(self._input_layers)) + ' tensor inputs.')
ValueError: Invalid input_shape argument (None, 1, 39, 2000): model has 0 tensor inputs.
```
I think it's a bug.

**Comment by MoyanZitto** [comment]
This bug is caused by renaming layer names.
If a layer name is reset, the "inbound_nodes" in successive layers will fail to locate it's previous layer. i.e:
Before rename:  'layer2' is connected to 'layer1'
Rename: 'layer1' --> 'rename_layer'
After rename: 'layer2' still want 'layer1' as it's previous layer, but there's no 'layer1' anymore, thus inbound_nodes in 'layer2' would be empty.
----------
Not sure if this should be fixed.
