### ISSUE TITLE
KerasClassifier with build_fn a class does not work with sklearn.model_selection.cross_val_score

### ISSUE THREAD

**Issue by quantitative-technologies** [keras-team/keras#13717]
**System information**  
- Have I written custom code (as opposed to using example directory):  
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  
Linux Ubuntu 19.10
- TensorFlow backend (yes / no):  
yes
- TensorFlow version:  
2.1.0
- Keras version:  
2.3.1
- Python version:  
3.7.5
- CUDA/cuDNN version:  
10.2/7
- GPU model and memory:  
GeForce GTX 1080

**Describe the current behavior**  
Exception thrown when making a call to `sklearn.model_selection.cross_val_score`

**Describe the expected behavior**  
No exception

**Code to reproduce the issue**  
Will create a MRE if you are interested in investigating further.

**Other info / logs**  
This is closely related to [#13586](https://github.com/keras-team/keras/issues/13586), as you can see from the traceback below, where it is failing to make a deepcopy. 

In fact, the only reason I am passing a class to `build_fn` is because #13586 is preventing me from passing arrays via `cross_val_score` to a function instead.

2020-01-21 19:45:19.793917: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.7
2020-01-21 19:45:19.794681: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.7
2020-01-21 19:45:21.296068: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-01-21 19:45:21.315098: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-21 19:45:21.315507: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1080 computeCapability: 6.1
coreClock: 1.847GHz coreCount: 20 deviceMemorySize: 7.90GiB deviceMemoryBandwidth: 298.32GiB/s
2020-01-21 19:45:21.315544: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
2020-01-21 19:45:21.315573: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-01-21 19:45:21.316801: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-01-21 19:45:21.317066: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-01-21 19:45:21.318438: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-01-21 19:45:21.319168: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-01-21 19:45:21.319292: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-01-21 19:45:21.319384: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-21 19:45:21.319671: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-21 19:45:21.319875: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-01-21 19:45:21.320230: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
2020-01-21 19:45:21.387150: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-21 19:45:21.387416: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x458acd0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-01-21 19:45:21.387428: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1080, Compute Capability 6.1
2020-01-21 19:45:21.387577: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-21 19:45:21.387751: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1080 computeCapability: 6.1
coreClock: 1.847GHz coreCount: 20 deviceMemorySize: 7.90GiB deviceMemoryBandwidth: 298.32GiB/s
2020-01-21 19:45:21.387774: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
2020-01-21 19:45:21.387781: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-01-21 19:45:21.387798: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-01-21 19:45:21.387807: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-01-21 19:45:21.387816: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-01-21 19:45:21.387825: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-01-21 19:45:21.387832: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-01-21 19:45:21.387875: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-21 19:45:21.388058: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-21 19:45:21.388209: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-01-21 19:45:21.388227: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
2020-01-21 19:45:21.640829: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-01-21 19:45:21.640852: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 
2020-01-21 19:45:21.640857: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N 
2020-01-21 19:45:21.641018: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-21 19:45:21.641245: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-21 19:45:21.641429: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1171 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
2020-01-21 19:45:21.661503: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 4200000000 Hz
2020-01-21 19:45:21.661774: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0xd698c60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-21 19:45:21.661787: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/joblib/parallel.py", line 797, in dispatch_one_batch
    tasks = self._ready_batches.get(block=False)
  File "/usr/lib/python3.7/queue.py", line 167, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/joblib/parallel.py", line 1004, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/joblib/parallel.py", line 808, in dispatch_one_batch
    islice = list(itertools.islice(iterator, big_batch_size))
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 236, in <genexpr>
    for train, test in cv.split(X, y, groups))
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/sklearn/base.py", line 71, in clone
    new_object_params[name] = clone(param, safe=False)
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/sklearn/base.py", line 59, in clone
    return estimator_type([clone(e, safe=safe) for e in estimator])
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/sklearn/base.py", line 59, in <listcomp>
    return estimator_type([clone(e, safe=safe) for e in estimator])
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/sklearn/base.py", line 59, in clone
    return estimator_type([clone(e, safe=safe) for e in estimator])
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/sklearn/base.py", line 59, in <listcomp>
    return estimator_type([clone(e, safe=safe) for e in estimator])
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/sklearn/base.py", line 71, in clone
    new_object_params[name] = clone(param, safe=False)
  File "/home/james/.virtualenvs/netraml/lib/python3.7/site-packages/sklearn/base.py", line 62, in clone
    return copy.deepcopy(estimator)
  File "/usr/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/usr/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/usr/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/usr/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.RLock objects

**Comment by edurenye** [comment]
I have the same problem

**Comment by sarahnguvt** [comment]
I have the same problem - could anyone kindly suggest about when this might be fixed? Thank you.

**Comment by jlehrer1** [comment]
Same problem. it should be easy to implement a `get_params` method

**Comment by akshit-agarwal-123** [comment]
facing the same issue. 
`estimator = KerasClassifier(build_fn=model, epochs=100, batch_size=10, verbose=0)
kfold = RepeatedKFold(n_splits=5, n_repeats=100)
results = cross_val_score(estimator, X, Y, cv=kfold)`

Error: TypeError: can't pickle _thread._local objects

**Comment by YannGarcia** [comment]
Hello,

Can any one suggest a work-around because I'm facing to the same issue: I wanted to pass a parameter (input_shape) to the KerasClassifier 'build_fn' and I got the following error:
`RuntimeError: Cannot clone object <tensorflow.python.keras.wrappers.scikit_learn.KerasClassifier object at 0x7ff2a5693550>, as the constructor either does not set or modifies parameter p_input_shape`

**Comment by sushreebarsa** [comment]
@quantitative-technologies 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
