### ISSUE TITLE
i tried to run my code , n theres error from keras packages, can u hlp me wth this

### ISSUE THREAD

**Issue by Aimannnhakim** [keras-team/keras#13890]
/home/aimannnhakim/PycharmProjects/MesoNet/venv/bin/python /home/aimannnhakim/PycharmProjects/project1/example.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/aimannnhakim/PycharmProjects/project1/example.py", line 2, in <module>
    from classifiers import *
  File "/home/aimannnhakim/PycharmProjects/project1/classifiers.py", line 3, in <module>
    from keras.models import Model as KerasModel
  File "/home/aimannnhakim/PycharmProjects/MesoNet/venv/lib/python3.5/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/aimannnhakim/PycharmProjects/MesoNet/venv/lib/python3.5/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/home/aimannnhakim/PycharmProjects/MesoNet/venv/lib/python3.5/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/home/aimannnhakim/PycharmProjects/MesoNet/venv/lib/python3.5/site-packages/keras/backend/__init__.py", line 81, in <module>
    from .tensorflow_backend import *
  File "/home/aimannnhakim/PycharmProjects/MesoNet/venv/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 514
    """Returns whether `x` is a placeholder.
             ^

**Comment by Saduf2019** [comment]
@Aimannnhakim 
Moving this issue to closed status as there has been no activity, in case you still face the error please create a new issue.
