### ISSUE TITLE
Keras Error in lambda Layer object 

### ISSUE THREAD

**Issue by kouroshD** [keras-team/keras#13914]
Hi,
I have written a custom code for training RNN network, but there was an error in it. I could manage to fix the problem, but still I do not understand why there was that error. In the following I provide the description of the problem, and the error log.

**Describe the current behavior**  
Here is the code:
```
                for t in range(self.Tx):
                    x = Lambda(lambda z: z[:, t, :])(X)
                    x = self.reshapor(x)
                    a, _, c = self.LSTM_cell(inputs=x, initial_state=[a, c])

                out = self.densor(a)
                x = Lambda(lambda z: z)(out)
                for t in range(self.Ty):
                    x = self.reshapor(x)
                    a, _, c = self.LSTM_cell(inputs=x, initial_state=[a, c])
                    out = self.densor(a)
                    outputs = outputs + [out]

```

and here is the error log:

```
Traceback (most recent call last):
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1619, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 9 of dimension 1 out of bounds. for 'model/lambda/strided_slice' (op: 'StridedSlice') with input shapes: [?,7,2], [3], [3], [3] and with computed input tensors: input[1] = <0 9 0>, input[2] = <0 10 0>, input[3] = <1 1 1>.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/.../code/src/main.py", line 90, in <module>
    epochs=epochs, plot_loss_value_obj=plot_losses, verbosity=verbosity)
  File "/.../code/src/RnnKeras.py", line 61, in fit_model
    verbose=verbosity) #, callbacks=[plot_loss_value_obj])
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 342, in fit
    total_epochs=epochs)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 128, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 98, in execution_function
    distributed_function(input_fn))
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 615, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 497, in _initialize
    *args, **kwds))
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 85, in distributed_function
    per_replica_function, args=args)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 763, in experimental_run_v2
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 1819, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 2164, in _call_for_each_replica
    return fn(*args, **kwargs)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 292, in wrapper
    return func(*args, **kwargs)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 433, in train_on_batch
    output_loss_metrics=model._output_loss_metrics)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 312, in train_on_batch
    output_loss_metrics=output_loss_metrics))
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 253, in _process_single_batch
    training=training))
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 127, in _model_loss
    outs = model(inputs, **kwargs)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 778, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 717, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 891, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 778, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/core.py", line 846, in call
    result = self.function(inputs, **kwargs)
  File "/.../code/src/RnnKeras.py", line 173, in <lambda>
    x = Lambda(lambda z: z[:, t, :])(X)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 898, in _slice_helper
    name=name)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 1064, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 9535, in strided_slice
    shrink_axis_mask=shrink_axis_mask, name=name)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 742, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 595, in _create_op_internal
    compute_device)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3322, in _create_op_internal
    op_def=op_def)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1786, in __init__
    control_input_ops)
  File "/.../code/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1622, in _create_c_op
    raise ValueError(str(e))
ValueError: slice index 9 of dimension 1 out of bounds. for 'model/lambda/strided_slice' (op: 'StridedSlice') with input shapes: [?,7,2], [3], [3], [3] and with computed input tensors: input[1] = <0 9 0>, input[2] = <0 10 0>, input[3] = <1 1 1>.
```

**Describe the expected behavior**  

When fitting the data by calling `self.model.fit(...)`, the error is happening in line `x = Lambda(lambda z: z[:, t, :])(X)` complaining that it has the value of `t` is not expected (high value) (since I was giving `Tx <Ty`). 
The question is:  `t` is assigned in the line before using `for t in range(self.Tx):`, therefore we should not face this problem related to passing by reference or the scope problem, since it has been assigned jut the line before.

**Describe the fix**
To fix the problem I have changed the variable names `t` as in the following:
```
                for tx in range(self.Tx):
                    x = Lambda(lambda z: z[:, tx, :])(X)
                    x = self.reshapor(x)
                    a, _, c = self.LSTM_cell(inputs=x, initial_state=[a, c])

                out = self.densor(a)
                x = Lambda(lambda z: z)(out)
                for ty in range(self.Ty):
                    x = self.reshapor(x)
                    a, _, c = self.LSTM_cell(inputs=x, initial_state=[a, c])
                    out = self.densor(a)
                    outputs = outputs + [out]
```

**System information**  
- Have I written custom code (as opposed to using example directory):  yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):   macOS Mojave 10.14.6
- TensorFlow backend (yes / no):   yes
- TensorFlow version:  2.1.0
- Keras version:  2.3.1
- Python version:  3.7
- CUDA/cuDNN version:  -
- GPU model and memory:  -, 16GB

**Comment by kouroshD** [comment]
@fchollet @farizrahman4u @taehoonlee @gabrieldemarmiesse @ozabluda @maxpumperla 
Can you please provide a feedback on this issue!?

**Comment by kumariko** [comment]
@kouroshD It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.6 and let us know if the issue still persists? Thanks!

**Comment by kouroshD** [comment]
> @kouroshD It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.6 and let us know if the issue still persists? Thanks!

@kumariko  Yes, it might be related to that. In any case, I have updated my implementations, and we may close this issue.
