### ISSUE TITLE
AttributeError: '_thread._local' object has no attribute 'value'

### ISSUE THREAD

**Issue by Parth38** [keras-team/keras#13959]
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.</em>  

**System information**  
- Have I written custom code (as opposed to using example directory):  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 19.04
- TensorFlow backend (yes / no):  yes
- TensorFlow version:   2.1.0 
- Keras version:  2.2.5
- Python version:  3.7.7
- CUDA/cuDNN version:  No
- GPU model and memory:  No

You can obtain the TensorFlow version with:  
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"  
You can obtain the Keras version with:  
python -c 'import keras as k; print(k.__version__)'  

**Describe the current behavior**  
The flask server deploying the model gets a "POST" request the image gets preprocessed
problem with model.predict function
**Describe the expected behavior**  
Prediction of the image by the model
**Code to reproduce the issue**  
Provide a reproducible test case that is the bare minimum necessary to generate the problem.  

**Other info / logs**  
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.  
* Debug mode: off
Using TensorFlow backend.
 * Loading Keras model ...:
2020-04-12 23:16:47.101350: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
2020-04-12 23:16:47.108044: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2494285000 Hz
2020-04-12 23:16:47.108419: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55ec981f3e30 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-12 23:16:47.108464: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-04-12 23:16:47.108591: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
WARNING:tensorflow:Large dropout rate: 0.7 (>0.5). In TensorFlow 2.x, dropout() uses dropout rate instead of keep_prob. Please ensure that this is intended.
 * Model loaded!
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [12/Apr/2020 23:19:34] "GET /static/predict.html HTTP/1.1" 304 -
Image decoded
Image processed
[2020-04-12 23:19:41,797] ERROR in app: Exception on /predict [POST]
Traceback (most recent call last):
  File "/home/user/anaconda2/envs/pd1/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/anaconda2/envs/pd1/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/anaconda2/envs/pd1/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/anaconda2/envs/pd1/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/anaconda2/envs/pd1/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/anaconda2/envs/pd1/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/flask_app/predict_app.py", line 51, in predict
    prediction = model.predict(test_data,batch_size=None)
  File "/home/user/anaconda2/envs/pd1/lib/python3.7/site-packages/keras/engine/training.py", line 1452, in predict
    if self._uses_dynamic_learning_phase():
  File "/home/user/anaconda2/envs/pd1/lib/python3.7/site-packages/keras/engine/training.py", line 382, in _uses_dynamic_learning_phase
    not isinstance(K.learning_phase(), int))
  File "/home/user/anaconda2/envs/pd1/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 73, in symbolic_fn_wrapper
    if _SYMBOLIC_SCOPE.value:
AttributeError: '_thread._local' object has no attribute 'value'
127.0.0.1 - - [12/Apr/2020 23:19:41] "POST /predict HTTP/1.1" 500 -

**Comment by Danielydsm** [comment]
I'm facing a similar problem. But I'm not using Flask. I just want to start Keras process on a different thread. 

class ConstructKeras():
    def fire_and_forget(f):
        def wrapped(self, patches_size):
            threading.Thread(target=f, args=(self,  patches_size)).start()

        return wrapped

    @fire_and_forget
    def run_code(self, patches_size):
        input_patch = Input( shape = (patches_size[0], patches_size[1], patches_size[2]), name = 'input' )
        
        flatten = Flatten( name = 'flatten' )( input_patch )
        
        encoder_1 = Dense( 256, activation = 'tanh', name='encoder_1' )( flatten )
        encoder_2 = Dense( 128, activation = 'tanh', name='encoder_2' )( encoder_1 )
        encoder_3 = Dense( 64, activation = 'tanh', name='encoder_3' )( encoder_2 )
        decoder_2 = Dense( 128, activation = 'tanh', name = 'decoder_2' )( encoder_3 )
        decoder_3 = Dense( 256, activation = 'tanh', name = 'decoder_3' )( decoder_2 )
        decoder_4 = Dense( 512, activation = 'linear', name = 'decoder_4' )( decoder_3 )
        
        reshape = Reshape( target_shape = ( patches_size[0], patches_size[1], patches_size[2] ), 
                           name = 'reshape' )( decoder_4 )
        
        model = Model( input_patch, reshape )

        model.compile( optimizer = 'adam', loss = 'mean_squared_error')
 
My error:

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/data_science/anaconda3/envs/web_api/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/data_science/anaconda3/envs/web_api/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-15-b2523eb62f77>", line 10, in run_code
    input_patch = Input( shape = (patches_size[0], patches_size[1], patches_size[2]), name = 'input' )
  File "/home/data_science/anaconda3/envs/web_api/lib/python3.7/site-packages/keras/engine/input_layer.py", line 178, in Input
    input_tensor=tensor)
  File "/home/data_science/anaconda3/envs/web_api/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/data_science/anaconda3/envs/web_api/lib/python3.7/site-packages/keras/engine/input_layer.py", line 87, in __init__
    name=self.name)
  File "/home/data_science/anaconda3/envs/web_api/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 73, in symbolic_fn_wrapper
    if _SYMBOLIC_SCOPE.value:
AttributeError: '_thread._local' object has no attribute 'value'

Can anyone help me?

**Comment by yanqishi1** [comment]
I met this problem when I use deploy my model in the flask server.
If I don't use flask server and just run it, It can work. However, when I post a image to flask backend to predict something, it happen.

The error message is as follows:
Traceback (most recent call last):
  File "D:\Program Files (x86)\anacoda\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Program Files (x86)\anacoda\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Program Files (x86)\anacoda\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\Program Files (x86)\anacoda\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Program Files (x86)\anacoda\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\Program Files (x86)\anacoda\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Program Files (x86)\anacoda\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Web\ai_demo_backend\app.py", line 58, in style_change
    result_img = convertStyle(file_path)
  File "E:\Web\ai_demo_backend\Style.py", line 107, in convertStyle
    combination_image = K.placeholder((1, img_height, img_width, 3)) #生成图像的占位符
  File "D:\Program Files (x86)\anacoda\lib\site-packages\keras\backend\tensorflow_backend.py", line 73, in symbolic_fn_wrapper
    if _SYMBOLIC_SCOPE.value:
AttributeError: '_thread._local' object has no attribute 'value'
127.0.0.1 - - [20/Oct/2020 16:03:02] "POST /api/style HTTP/1.1" 500 -

Can someone help me?

**Comment by tilakrayal** [comment]
@Parth38 ,
Can you please take a look at this [comment](https://github.com/keras-team/keras/issues/13353) from the issue with similar error.It helps.Thanks!
