### ISSUE TITLE
Python MNIST siamese example not working with PlaidML

### ISSUE THREAD

**Issue by MarviB16** [keras-team/keras#13957]
Hello,

I am currently trying to get [this](https://github.com/keras-team/keras/blob/master/examples/mnist_siamese.py) example to work. However, when I run it I get the following exception:

> Traceback (most recent call last):
>   File "DeepLearningTest.py", line 133, in <module>
>     model.compile(loss=contrastive_loss, optimizer=rms, metrics=[accuracy])
>   File "/opt/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 451, in compile
>     handle_metrics(output_metrics)
>   File "/opt/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 420, in handle_metrics
>     mask=masks[i])
>   File "/opt/anaconda3/lib/python3.7/site-packages/keras/engine/training_utils.py", line 404, in weighted
>     score_array = fn(y_true, y_pred)
>   File "DeepLearningTest.py", line 96, in accuracy
>     return K.mean(K.equal(y_true, K.cast(y_pred < 0.5, y_true.dtype)))
> AttributeError: 'Value' object has no attribute 'dtype'

I am using Python 3.7, keras-2.3.1, PlaidML 0.7.0 and Anaconda. I'm on a Mac using an AMD GPU. I'm not sure if it has something to do with PlaidML, but [this](https://github.com/keras-team/keras/blob/master/examples/cifar10_cnn.py) example worked perfectly fine.

**Comment by Saduf2019** [comment]
@MarviB16 

Moving this issue to closed status as there has been no activity, in case you still face the error please create a new issue.
