### ISSUE TITLE
JSON decode error 

### ISSUE THREAD

**Issue by Parth38** [keras-team/keras#13962]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [ y] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ y] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).
Traceback (most recent call last):
  File "/home/user/anaconda2/envs/pd1/etc/keras/load_config.py", line 14, in <module>
    backend = json.load(fh).get("backend", backend)
  File "/home/user/anaconda2/envs/pd1/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/user/anaconda2/envs/pd1/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/user/anaconda2/envs/pd1/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/user/anaconda2/envs/pd1/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Saduf2019** [comment]
@Parth38 
Moving this issue to closed status as there has been no activity, in case you still face the error please create a new issue.
