### ISSUE TITLE
GradientTape issue

### ISSUE THREAD

**Issue by lsorgi** [keras-team/keras#13997]
thanks in advance for support

************************************

**System information**  
- Windows 10 OS, NO GPU  
- TensorFlow backend
- TensorFlow version:  2.1.0 
- Keras version: 2.3.1 
- Python version:  3.6.10

***********************
Issue: 
I am trying to run customized training on a model updating only a subset of the weights.

***********************
Code: 
I made the sample code only to show the issue. variable names are functionality is meaningless.

[run_ExampleC.zip](https://github.com/keras-team/keras/files/4524063/run_ExampleC.zip)

*********************
Error message:

__________________________________________________________________________________________________
Traceback (most recent call last):
  File "run_ExampleC.py", line 101, in <module>
    run()
  File "run_ExampleC.py", line 97, in run
    controller.push(input_nd, output_nd, output_1d)
  File "run_ExampleC.py", line 68, in push
    self.train_function(input_nd[np.newaxis, :])
  File "run_ExampleC.py", line 54, in train_function
    grads = tape.gradient(learn_loss, self.model1.trainable_weights)
  File "C:\Users\sorgil\AppData\Local\Continuum\anaconda3\envs\p36_tf\lib\site-packages\tensorflow_core\python\eager\backprop.py", line
1029, in gradient
    unconnected_gradients=unconnected_gradients)
  File "C:\Users\sorgil\AppData\Local\Continuum\anaconda3\envs\p36_tf\lib\site-packages\tensorflow_core\python\eager\imperative_grad.py"
, line 77, in imperative_grad
    compat.as_str(unconnected_gradients.value))
  File "C:\Users\sorgil\AppData\Local\Continuum\anaconda3\envs\p36_tf\lib\site-packages\tensorflow_core\python\eager\backprop.py", line
141, in _gradient_function
    return grad_fn(mock_op, *out_grads)
  File "C:\Users\sorgil\AppData\Local\Continuum\anaconda3\envs\p36_tf\lib\site-packages\tensorflow_core\python\ops\array_grad.py", line
229, in _ConcatGradV2
    op, grad, start_value_index=0, end_value_index=-1, dim_index=-1)
  File "C:\Users\sorgil\AppData\Local\Continuum\anaconda3\envs\p36_tf\lib\site-packages\tensorflow_core\python\ops\array_grad.py", line
118, in _ConcatGradHelper
    concat_dim._numpy().item(0) % input_values[0]._rank())  # pylint: disable=protected-access
AttributeError: 'Tensor' object has no attribute '_numpy'

**Comment by yayaneath** [comment]
I think this is caused by Keras expecting a computational graph instead of the default eager mode of TensorFlow 2.0. Keras 2.3 does not support eager mode. It is recommended using `tensorflow.keras` in that case (https://github.com/keras-team/keras/releases). 

Once I change the imports statement in your code from `import keras` to  `from tensorflow import keras` this error is solved. Note, however, that this change also requires fixing the arguments passed to `Model`: instead of `input` and `output`, it expects `inputs` and `outputs`.

**Comment by tilakrayal** [comment]
@lsorgi ,
Can you please take a look at this links for similar error.It helps.[Link1](https://stackoverflow.com/questions/52357542/attributeerror-tensor-object-has-no-attribute-numpy),[Link2](https://github.com/tensorflow/tensorflow/issues/27519).Thanks
