### ISSUE TITLE
Regression in model.optimizer.get_gradients() with TF 2.2

### ISSUE THREAD

**Issue by philipperemy** [keras-team/keras#14066]
Latest: tensorflow master             2.2.0. It was working until 2.1.0 from what I remember.

**Regression in model.optimizer.get_gradients()**

```python
import numpy as np
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import Dense

i1 = Input(shape=(10,), name='i1')
a = Dense(1, name='fc1')(i1)
model = Model(inputs=[i1], outputs=[a])
model.summary()

model.compile(optimizer='adam', loss='mse')

x = np.random.uniform(size=(32, 10))

print(model.predict(x).shape)  # just check model can predict.

nodes = model.trainable_weights
nodes_names = [w.name for w in nodes]
print(nodes_names)
print(model.losses)
grads = model.optimizer.get_gradients(model.losses, nodes)
```

The error is:

```
['fc1/kernel:0', 'fc1/bias:0']
[]
Traceback (most recent call last):
  File "/Users/premy/PycharmProjects/keract/tests/gfd.py", line 20, in <module>
    grads = model.optimizer.get_gradients(model.losses, nodes)
  File "/Users/premy/PycharmProjects/keract/venv/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 428, in get_gradients
    "K.argmax, K.round, K.eval.".format(param))
ValueError: Variable <tf.Variable 'fc1/kernel:0' shape=(10, 1) dtype=float32> has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.
```

`fc1/kernel` has a well defined gradient. On top of this, why does `model.losses` appear to be empty? Before I had the loss tensor.

Thanks a lot.

It's impacting this project: https://github.com/philipperemy/keract

**Comment by philipperemy** [comment]
So seems like this only works when the eager mode is deactivated. Otherwise should use the obscure `GradientsTape` class.

**Comment by chunduriv** [comment]
@philipperemy, Can you please try in latest Tensorflow and Keras version and let us know if the issue still persists?

**Comment by philipperemy** [comment]
@chunduriv the issue still persists with the latest tensorflow 2.7.0.

@googlebot hey re-open this issue please.

**Comment by philipperemy** [comment]
```
pip list | grep tensorflow
tensorflow                   2.7.0
tensorflow-estimator         2.7.0
tensorflow-io-gcs-filesystem 0.21.0
```

```
['fc1/kernel:0', 'fc1/bias:0']
[]
Traceback (most recent call last):
  File "fff.py", line 20, in <module>
    grads = model.optimizer.get_gradients(model.losses, nodes)
  File "/private/tmp/ffffff/venv/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py", line 766, in get_gradients
    raise ValueError("Variable {} has `None` for gradient. "
ValueError: Variable <tf.Variable 'fc1/kernel:0' shape=(10, 1) dtype=float32> has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.
```

**Comment by gadagashwini** [comment]
@philipperemy,
Workaround for this issue on latest Tensorflow version ~2.8.0, use `tf.GradientTape()`.

```
import numpy as np
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import Dense
import tensorflow as tf

i1 = Input(shape=(10,), name='i1')
a = Dense(1, name='fc1')(i1)
model = Model(inputs=[i1], outputs=[a])
model.summary()

model.compile(optimizer='adam', loss='mse')

x = y = np.random.uniform(size=(32, 10))

model.train_on_batch(x, y)
with tf.GradientTape() as tape:
    # Doing the computation in the context of the gradient tape
    # For example computing loss
    pred = model(x)
    loss = tf.metrics.MSE(y,pred)

# Getting the gradient of weight w.r.t loss 
grad = tape.gradient(loss, model.trainable_weights) 
grad
```
**Output**
```
Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 i1 (InputLayer)             [(None, 10)]              0         
                                                                 
 fc1 (Dense)                 (None, 1)                 11        
                                                                 
=================================================================
Total params: 11
Trainable params: 11
Non-trainable params: 0
_________________________________________________________________
[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[21.312542 ],
        [18.93206  ],
        [21.455547 ],
        [20.61179  ],
        [23.195847 ],
        [17.875448 ],
        [17.175465 ],
        [15.8124695],
        [14.560739 ],
        [16.568796 ]], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([35.155563], dtype=float32)>]
```

**Comment by philipperemy** [comment]
@gadagashwini thanks for that!
