### ISSUE TITLE
Why I can't load mnist dataset using load_data() method?

### ISSUE THREAD

**Issue by MuongKimhong** [keras-team/keras#14089]
I used this line of code to load mnist dataset and I got it from tensorflow documentation
`(trainX, trainY), (testX, testY) = load_data(path='mnist.npz')`

But when I executed the file it gave me an error on  certificate 
here is the error i got
`Traceback (most recent call last):
  File "mnist_degit.py", line 18, in <module>
    (trainX, trainY), (testX, testY) = load_data(path='mnist.npz')
  File "/Users/muongkimhong/Desktop/ComputerVision_project/DigitRecognize/digit_recognize_env/lib/python3.7/site-packages/tensorflow/python/keras/datasets/mnist.py", line 62, in load_data
    '731c5ac602752760c8e48fbffcf8c3b850d9dc2a2aedcf2cc48468fc17b673d1')
  File "/Users/muongkimhong/Desktop/ComputerVision_project/DigitRecognize/digit_recognize_env/lib/python3.7/site-packages/tensorflow/python/keras/utils/data_utils.py", line 267, in get_file
    raise Exception(error_msg.format(origin, e.errno, e.reason))
Exception: URL fetch failure on https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz: None -- [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)`

Please help  Thanks

**Comment by goelharshit562** [comment]
you must install python certificates by writing this two scripts in macos :

Install Certificates.command
Update Shell Profile.command

Simply Run these two scripts and you wont have this issue any more

**Comment by MuongKimhong** [comment]
Thanks
