### ISSUE TITLE
MeanIoU as a metric

### ISSUE THREAD

**Issue by statcom** [keras-team/keras#14094]
**System information**  
- Have I written custom code (as opposed to using example directory):  Yes 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):   Windows 10
- TensorFlow backend (yes / no):  Yes
- TensorFlow version:  2.2.0
- Keras version:  2.3.1
- Python version:  3.7.7
- CUDA/cuDNN version:  CUDA 10.1/cuDNN 10.1 
- GPU model and memory:  2 GTX 1080s (8GB each)

**Describe the current behavior**  

While training U-Net, I am trying to compute Mean IOU with the following code

        model.compile(optimizer='adam', loss=dice_loss, metrics=['accuracy', 'MeanIoU'])  

But I got this error.  (without 'MeanIoU' item, there was no error)

```
  File "C:\XXX\XXX\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 537, in _disallow_in_graph_mode
    " this function with @tf.function.".format(task))
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.
```

There are full traceback messages below.

**Describe the expected behavior**  

No error.

**Code to reproduce the issue**  

        model.compile(optimizer='adam', loss=dice_loss, metrics=['accuracy', 'MeanIoU'])  

**Other info / logs**  

Traceback (most recent call last):
  File "seg_unet.py", line 204, in <module>
    trials=trials)
  File "C:\XXX\XXX\venv\lib\site-packages\hyperopt\fmin.py", line 482, in fmin
    show_progressbar=show_progressbar,
  File "C:\XXX\XXX\venv\lib\site-packages\hyperopt\base.py", line 686, in fmin
    show_progressbar=show_progressbar,
  File "C:\XXX\XXX\venv\lib\site-packages\hyperopt\fmin.py", line 509, in fmin
    rval.exhaust()
  File "C:\XXX\XXX\venv\lib\site-packages\hyperopt\fmin.py", line 330, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "C:\XXX\XXX\venv\lib\site-packages\hyperopt\fmin.py", line 286, in run
    self.serial_evaluate()
  File "C:\XXX\XXX\venv\lib\site-packages\hyperopt\fmin.py", line 165, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "C:\XXX\XXX\venv\lib\site-packages\hyperopt\base.py", line 894, in evaluate
    rval = self.fn(pyll_rval)
  File "seg_unet.py", line 171, in unet_fit
    model = unet_kang(image_height, image_width, 1)
  File "seg_unet.py", line 97, in unet_kang
    model.compile(optimizer='adam', loss=dice_loss, metrics=['accuracy', 'MeanIoU'])  # loss='binary_crossentropy' , 'MeanIoU'
  File "C:\XXX\XXX\venv\lib\site-packages\keras\backend\tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "C:\XXX\XXX\venv\lib\site-packages\keras\engine\training.py", line 222, in compile
    masks=masks)
  File "C:\XXX\XXX\venv\lib\site-packages\keras\engine\training.py", line 871, in _handle_metrics
    self._per_output_metrics[i], target, output, output_mask)
  File "C:\XXX\XXX\venv\lib\site-packages\keras\engine\training.py", line 842, in _handle_per_output_metrics
    metric_fn, y_true, y_pred, weights=weights, mask=mask)
  File "C:\XXX\XXX\venv\lib\site-packages\keras\engine\training_utils.py", line 1033, in call_metric_function
    update_ops = metric_fn.update_state(y_true, y_pred, sample_weight=weights)
  File "C:\XXX\XXX\venv\lib\site-packages\keras\utils\metrics_utils.py", line 42, in decorated
    update_op = update_state_fn(*args, **kwargs)
  File "C:\XXX\XXX\venv\lib\site-packages\keras\metrics.py", line 318, in update_state
    matches = self._fn(y_true, y_pred, **self._fn_kwargs)
  File "C:\XXX\XXX\venv\lib\site-packages\keras\metrics.py", line 1888, in __init__
    super(MeanIoU, self).__init__(num_classes, name=name, dtype=dtype)
  File "C:\XXX\XXX\venv\lib\site-packages\tensorflow\python\keras\metrics.py", line 2729, in __init__
    super(MeanIoU, self).__init__(name=name, dtype=dtype)
  File "C:\XXX\XXX\venv\lib\site-packages\tensorflow\python\keras\metrics.py", line 145, in __init__
    super(Metric, self).__init__(name=name, dtype=dtype, **kwargs)
  File "C:\XXX\XXX\venv\lib\site-packages\tensorflow\python\training\tracking\base.py", line 456, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\XXX\XXX\venv\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 315, in __init__
    self._init_set_name(name)
  File "C:\XXX\XXX\venv\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 2103, in _init_set_name
    if not name:
  File "C:\XXX\XXX\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 778, in __bool__
    self._disallow_bool_casting()
  File "C:\XXX\XXX\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 548, in _disallow_bool_casting
    self._disallow_in_graph_mode("using a `tf.Tensor` as a Python `bool`")
  File "C:\XXX\XXX\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 537, in _disallow_in_graph_mode
    " this function with @tf.function.".format(task))
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.

**Comment by Samriddhi-1998** [comment]
Can you assign it to me?

**Comment by jvishnuvardhan** [comment]
@statcom Sorry for the late response. Is this still an issue for you.

Can you please share a simple standalone code to reproduce the issue? Please check the examples list [here](https://www.tensorflow.org/api_docs/python/tf/keras/metrics/MeanIoU?version=nightly). Also, run your code with recent TF versions and let us know whether the issue still persists. Thanks!

**Comment by statcom** [comment]
> 
> 
> @statcom Sorry for the late response. Is this still an issue for you.
> 
> Can you please share a simple standalone code to reproduce the issue? Please check the examples list [here](https://www.tensorflow.org/api_docs/python/tf/keras/metrics/MeanIoU?version=nightly). Also, run your code with recent TF versions and let us know whether the issue still persists. Thanks!

I forgot about this report as well. I resolved the problem but barely remember how. Anyway, you can close this issue.

**Comment by innat** [comment]
@jvishnuvardhan is the `MeanIOU` meant to work with the **one-hot encoded** label and not the **integer coded**label in the segmentation task? For example: normally it gives an error if we place this metric on this segmentation [example](https://keras.io/examples/vision/oxford_pets_image_segmentation/). In this example, the label is not one hot encoded but simply integer coded. Is the error expected?

**Comment by innat** [comment]
cc. @LukeWood

**Comment by LukeWood** [comment]
@statcom can you link a jupyter notebook where you can reproduce this problem?
