### ISSUE TITLE
Model prediction works on CPU/i386 (and GPU), but errors out on CPU/x86_64

### ISSUE THREAD

**Issue by poke1024** [keras-team/keras#14091]
**System information**  
- Test code and sample model is available at https://www.dropbox.com/sh/nuy7b5ix8vex7q0/AAAiUqArIdywQTRn-8EtFgFoa?dl=0
- macOS and Linux (see details below)
- TensorFlow backend: yes
- TensorFlow version: 2.1.0
- Keras version: 2.3.1
- Python version: 3.7.7
- CUDA/cuDNN version: not applicable for described issue
- GPU model and memory:  not applicable for described issue

**Describe the current behavior**  

The following code (loading a model and predicting from it) works on one CPU platform (and one GPU platform). However, on a different CPU platform (x64_64), it raises an error during prediction inside `batchnorm/mul`. 

Both platforms load the binary identical model and use identical versions of TensorFlow (2.1.0), Keras (2.3.1) and Python (3.7.7).

Test code: see `main.py` and `model.h5` in linked Dropbox repo.

Here is the essential part:

```
model = load_model(model_path, compile=False)
pixels = np.zeros([128, 128, 3])  # some input.
pixels = np.expand_dims(pixels, axis=0)
model.predict(pixels)  # fails.
```

Output on problematic x64_64 platform:

```
Using TensorFlow backend.
Segmentation Models: using `keras` framework.
python 3.7.7 ('default', 'Mar 26 2020 15:48:22')
tf 2.1.0
keras 2.3.1
numpy 1.18.1
platform Linux-4.12.14-lp150.12.28-default-x86_64-with-glibc2.10
processor x86_64
2020-06-04 13:16:05.233775: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2020-06-04 13:16:05.244050: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200000000 Hz
2020-06-04 13:16:05.245512: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55daee4a7130 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-04 13:16:05.245540: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-06-04 13:16:05.245656: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2020-06-04 13:17:16.983190: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Invalid argument: Incompatible shapes: [3] vs. [32]
	 [[{{node model_1/stem_bn/batchnorm/mul}}]]
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    model.predict(pixels)
  File "/u/liebl/miniconda3/envs/origami/lib/python3.7/site-packages/keras/engine/training.py", line 1462, in predict
    callbacks=callbacks)
  File "/u/liebl/miniconda3/envs/origami/lib/python3.7/site-packages/keras/engine/training_arrays.py", line 324, in predict_loop
    batch_outs = f(ins_batch)
  File "/u/liebl/miniconda3/envs/origami/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py", line 3727, in __call__
    outputs = self._graph_fn(*converted_inputs)
  File "/u/liebl/miniconda3/envs/origami/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1551, in __call__
    return self._call_impl(args, kwargs)
  File "/u/liebl/miniconda3/envs/origami/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1591, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/u/liebl/miniconda3/envs/origami/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/u/liebl/miniconda3/envs/origami/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 545, in call
    ctx=ctx)
  File "/u/liebl/miniconda3/envs/origami/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Incompatible shapes: [3] vs. [32]
	 [[node model_1/stem_bn/batchnorm/mul (defined at /u/liebl/miniconda3/envs/origami/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3009) ]] [Op:__inference_keras_scratch_graph_57496]

Function call stack:
keras_scratch_graph
```

**Describe the expected behavior**  

x64_64 should produce the same good result as when run on i386 platform, which is:

```
Using TensorFlow backend.
Segmentation Models: using `keras` framework.
python 3.7.7 ('default', 'Mar 23 2020 17:31:31')
tf 2.1.0
keras 2.3.1
numpy 1.18.1
platform Darwin-19.5.0-x86_64-i386-64bit
processor i386
2020-06-04 13:14:41.047289: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-06-04 13:14:41.060244: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fc43fe86c00 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-04 13:14:41.060266: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
ok.
```

Note that the same model also loads and predicts without errors on a third GPU platform (RTX2080Ti/Linux).

**Code to reproduce the issue**  
https://www.dropbox.com/sh/nuy7b5ix8vex7q0/AAAiUqArIdywQTRn-8EtFgFoa?dl=0

**Other info / logs**  
Full output logs of both CPU platforms are attached.

[logs.zip](https://github.com/keras-team/keras/files/4729650/logs.zip)

**Comment by jvishnuvardhan** [comment]
@poke1024 Sorry for the late response. Is this still an issue for you?

Can you please check with recent `TF/Keras` versions and let us know whether it is still an issue with recent version. Thanks!
