### ISSUE TITLE
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 12, 12, 128), (None, 12, 12, 32), (None, 12, 12, 32), (None, 12, 12, 64)]

### ISSUE THREAD

**Issue by filzahamjad** [keras-team/keras#14346]
Using TensorFlow backend.
Saving cropped images in bin/output.
2021-01-05 14:45:26.134594: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-01-05 14:45:26.148613: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fc1f7241860 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-01-05 14:45:26.148674: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "bin/compare_faces.py", line 51, in <module>
    run(args.image_one, args.image_two, args.save_dest)
  File "bin/compare_faces.py", line 29, in run
    model = facenet_model(input_shape=(96, 96, 3))
  File "/usr/local/anaconda3/lib/python3.8/site-packages/face_compare/model.py", line 217, in facenet_model
    X = inception_block_4a(X)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/face_compare/model.py", line 62, in inception_block_4a
    return concatenate([X_3x3, X_5x5, X_pool, X_1x1], axis=1)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/layers/merge.py", line 931, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 925, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/usr/local/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1098, in _functional_construction_call
    self._maybe_build(inputs)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2643, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "/usr/local/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/utils/tf_utils.py", line 323, in wrapper
    output_shape = fn(instance, input_shape)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/layers/merge.py", line 519, in build
    raise ValueError(err_msg)
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 12, 12, 128), (None, 12, 12, 32), (None, 12, 12, 32), (None, 12, 12, 64)]Using TensorFlow backend.
Saving cropped images in bin/output.
2021-01-05 14:45:26.134594: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-01-05 14:45:26.148613: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fc1f7241860 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-01-05 14:45:26.148674: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "bin/compare_faces.py", line 51, in <module>
    run(args.image_one, args.image_two, args.save_dest)
  File "bin/compare_faces.py", line 29, in run
    model = facenet_model(input_shape=(96, 96, 3))
  File "/usr/local/anaconda3/lib/python3.8/site-packages/face_compare/model.py", line 217, in facenet_model
    X = inception_block_4a(X)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/face_compare/model.py", line 62, in inception_block_4a
    return concatenate([X_3x3, X_5x5, X_pool, X_1x1], axis=1)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/layers/merge.py", line 931, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 925, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/usr/local/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1098, in _functional_construction_call
    self._maybe_build(inputs)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2643, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "/usr/local/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/utils/tf_utils.py", line 323, in wrapper
    output_shape = fn(instance, input_shape)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/layers/merge.py", line 519, in build
    raise ValueError(err_msg)
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 12, 12, 128), (None, 12, 12, 32), (None, 12, 12, 32), (None, 12, 12, 64)]

**Comment by chunduriv** [comment]
@filzahamjad, Sorry for the late response. Is this still an issue for you?

Does [this](https://stackoverflow.com/questions/53343346/valueerror-a-concatenate-layer-requires-inputs-with-matching-shapes) reference help you? If not, can you please share a simple standalone code to reproduce the issue? Thanks!
