### ISSUE TITLE
Load_weights problem. NotFoundError: Key optimizer/iter/.ATTRIBUTES/VARIABLE_VALUE not found in checkpoint [Op:RestoreV2]

### ISSUE THREAD

**Issue by GrzegorzKrug** [keras-team/keras#14401]
In simple words I got class that loads params and weights. So everytime I recreate model, and load weights with method `load_weights()`. But sometimes or maybe every 2 runs, error pops up for no reason.

Get 2 questions about this. This most likely corelated with `save_weights`. Reason of error can be cause by model instantly saved after creating? or Ctrl+C is break some keras savings maybe? 

It does not matter if checkpoint file exists or not. Error still happens.
And I will mention that I am not using any TF checkpoint features, it all happend within keras

Windows 10 x64
```bash
C:\Users\Greg>python --version
Python 3.8.7

C:\Users\Greg>pip freeze
absl-py==0.11.0
astunparse==1.6.3
cachetools==4.2.0
certifi==2020.12.5
chardet==4.0.0
comtypes==1.1.8
cycler==0.10.0
flatbuffers==1.12
gast==0.3.3
google-auth==1.24.0
google-auth-oauthlib==0.4.2
google-pasta==0.2.0
graphviz==0.16
grpcio==1.32.0
h5py==2.10.0
idna==2.10
joblib==1.0.0
Keras==2.4.3
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
kiwisolver==1.3.1
Markdown==3.3.3
matplotlib==3.3.3
mouse==0.7.1
MouseInfo==0.1.3
numpy==1.19.5
oauthlib==3.1.0
opencv-python==4.5.1.48
opt-einsum==3.3.0
Pillow==8.1.0
protobuf==3.14.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
PyAutoGUI==0.9.52
pydot==1.4.1
pydot-ng==2.0.0
PyGetWindow==0.0.9
PyMsgBox==1.0.9
pynput==1.7.2
pyparsing==2.4.7
pyperclip==1.8.1
PyRect==0.1.4
PyScreeze==0.1.26
pytesseract==0.3.7
python-dateutil==2.8.1
PyTweening==1.0.3
pywin32==300
pywinauto==0.6.8
PyYAML==5.3.1
requests==2.25.1
requests-oauthlib==1.3.0
rsa==4.7
scikit-learn==0.24.0
scipy==1.6.0
six==1.15.0
sklearn==0.0
tensorboard==2.4.1
tensorboard-plugin-wit==1.7.0
tensorflow==2.4.0
tensorflow-estimator==2.4.0
termcolor==1.1.0
threadpoolctl==2.1.0
typing-extensions==3.7.4.3
urllib3==1.26.2
Werkzeug==1.0.1
wrapt==1.12.1
```

### Params preview
```py
NODE_SHAPES = [
        {'node': "conv2d", 'filters': 60,
         # 'kernel_size': (5, 5), 'strides': (3, 3), 'activation': 'relu',
         'kernel_size': (3, 3), 'activation': 'relu',
         'input_shape': (100, 100, 3,)},
        {'node': "maxpool", 'pool_size': (2, 2)},
        {'node': 'conv2d', 'filters': 60, 'kernel_size': (3, 3), 'activation': 'relu', 'padding': 'same'},
        {'node': 'maxpool', 'pool_size': (2, 2)},
        {'node': 'conv2d', 'filters': 60, 'kernel_size': (3, 3), 'activation': 'relu', 'padding': 'same'},
        {'node': 'maxpool', 'pool_size': (2, 2), 'padding': 'same'},
        {'node': 'conv2d', 'filters': 60, 'kernel_size': (3, 3), 'activation': 'relu', 'padding': 'same'},
        {'node': 'maxpool', 'pool_size': (2, 2), 'padding': 'same'},
        # {'node': 'conv2d', 'filters': 25, 'kernel_size': (1, 1), 'activation': 'relu'},
        # {'node': 'maxpool', 'pool_size': (3, 3)},
        {'node': 'flatten'},
        {'node': 'dense', 'args': (1000,), 'activation': 'relu'},
        {'node': "dropout", 'args': (0.05,)},
        {'node': 'dense', 'args': (1000,), 'activation': 'relu'},
        {'node': "dropout", 'args': (0.05,)},
        # {'node': 'dense', 'args': (100,), 'activation': 'relu'},
        # {'node': "dropout", 'args': (0.1,)},
        {'node': 'dense', 'args': (64 + 2,), 'activation': 'linear'},
]

COMPILER = {
        'optimizer': 'adam',
        'loss': 'log_cosh',
        'metrics': ['accuracy'],
}
```

### Actual Code
```py
    def load_model(self):
        print(f"Loading model {self.name}")
        self._load_params()  # load layar shapes and params
        self.make_model()  # create model instance
        self.load_model_weights()  # load weights
        self._load_memory()

    def make_model(self):
        print(f"Creating dqn model {self.name}")
        layers = []
        CFG = deepcopy(self.node_shapes)
        for cfg in CFG:
            node = cfg.pop('node', None)
            args = cfg.pop('args', ())
            kwargs = cfg

            if not node:
                raise ValueError("Empty node value")
            node = node.lower()
            print(f"Adding {node:>10}, Args: {args}, Kwargs: {kwargs}")

            if node == 'conv2d':
                lay = Conv2D(*args, **kwargs)
            elif node == 'dense':
                lay = Dense(*args, **kwargs)
            elif node == "maxpool":
                lay = MaxPool2D(*args, **kwargs)
            elif node == "dropout":
                lay = Dropout(*args, **kwargs)
            elif node == "input":
                lay = Input(*args, **kwargs)
            elif node == 'flatten':
                lay = Flatten()
            else:
                raise ValueError(f"Unknown layer type: {node}")

            layers.append(lay)

        model = Sequential(layers)
        model.compile(**self.compiler)
        self.model = model

    def load_model_weights(self):
        self._load_weights(self.model, self.path_model_weights)

    @staticmethod
    def _load_weights(mod, path):
        check_path = path + ".index"
        f1 = os.path.isfile(check_path)
        if f1:
            while True:
                try:
                    mod.load_weights(path)
                    print(f"Loaded weights: {path}")
                    break
                except OSError:
                    time.sleep(0.2)
        else:
            print(f"No weights: {path}")

    @staticmethod
    def _save_weights(mod, path):
        while True:
            try:
                mod.save_weights(path)
                print("Save weights")
                break
            except OSError:
                time.sleep(0.2)
            except AttributeError as err:
                print(f"Can not save weights: {err} to {path}")
                break
```

##### Full code here

[https://github.com/GrzegorzKrug/GymTrain/blob/a48df502361a45dd3dcdbe4670d6287d6ab83cd4/gym-train/rl/clickr/model.py](https://github.com/GrzegorzKrug/GymTrain/blob/a48df502361a45dd3dcdbe4670d6287d6ab83cd4/gym-train/rl/clickr/model.py)

### Traceback

```bash
2021-01-26 02:34:03.923247: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-01-26 02:34:03.923353: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Loading model model-13-logcos
Loading params D:\LocalPrograms\repos\GymTrain\gym-train\rl\clickr\model-13-logcos\model\params-model.npy
([{'node': 'conv2d', 'filters': 60, 'kernel_size': (3, 3), 'activation': 'relu', 'input_shape': (100, 100, 3)}, {'node': 'maxpool', 'pool_size': (2, 2)}, {'node': 'conv2d', 'filters': 60, 'kernel_size': (3, 3), 'activation': 'relu', 'padding': 'same'}, {'node': 'maxpool', 'pool_size': (2, 2)}, {'node': 'conv2d', 'filters': 60, 'kernel_size': (3, 3), 'activation': 'relu', 'padding': 'same'}, {'node': 'maxpool', 'pool_size': (2, 2), 'padding': 'same'}, {'node': 'conv2d', 'filters': 60, 'kernel_size': (3, 3), 'activation': 'relu', 'padding': 'same'}, {'node': 'maxpool', 'pool_size': (2, 2), 'padding': 'same'}, {'node': 'flatten'}, {'node': 'dense', 'args': (1000,), 'activation': 'relu'}, {'node': 'dropout', 'args': (0.05,)}, {'node': 'dense', 'args': (1000,), 'activation': 'relu'}, {'node': 'dropout', 'args': (0.05,)}, {'node': 'dense', 'args': (66,), 'activation': 'linear'}], {'optimizer': 'adam', 'loss': 'log_cosh', 'metrics': ['accuracy']})
Creating dqn model model-13-logcos
[{'node': 'conv2d', 'filters': 60, 'kernel_size': (3, 3), 'activation': 'relu', 'input_shape': (100, 100, 3)}, {'node': 'maxpool', 'pool_size': (2, 2)}, {'node': 'conv2d', 'filters': 60, 'kernel_size': (3, 3), 'activation': 'relu', 'padding': 'same'}, {'node': 'maxpool', 'pool_size': (2, 2)}, {'node': 'conv2d', 'filters': 60, 'kernel_size': (3, 3), 'activation': 'relu', 'padding': 'same'}, {'node': 'maxpool', 'pool_size': (2, 2), 'padding': 'same'}, {'node': 'conv2d', 'filters': 60, 'kernel_size': (3, 3), 'activation': 'relu', 'padding': 'same'}, {'node': 'maxpool', 'pool_size': (2, 2), 'padding': 'same'}, {'node': 'flatten'}, {'node': 'dense', 'args': (1000,), 'activation': 'relu'}, {'node': 'dropout', 'args': (0.05,)}, {'node': 'dense', 'args': (1000,), 'activation': 'relu'}, {'node': 'dropout', 'args': (0.05,)}, {'node': 'dense', 'args': (66,), 'activation': 'linear'}]
Adding     conv2d, Args: (), Kwargs: {'filters': 60, 'kernel_size': (3, 3), 'activation': 'relu', 'input_shape': (100, 100, 3)}
Adding    maxpool, Args: (), Kwargs: {'pool_size': (2, 2)}
Adding     conv2d, Args: (), Kwargs: {'filters': 60, 'kernel_size': (3, 3), 'activation': 'relu', 'padding': 'same'}
Adding    maxpool, Args: (), Kwargs: {'pool_size': (2, 2)}
Adding     conv2d, Args: (), Kwargs: {'filters': 60, 'kernel_size': (3, 3), 'activation': 'relu', 'padding': 'same'}
Adding    maxpool, Args: (), Kwargs: {'pool_size': (2, 2), 'padding': 'same'}
Adding     conv2d, Args: (), Kwargs: {'filters': 60, 'kernel_size': (3, 3), 'activation': 'relu', 'padding': 'same'}
Adding    maxpool, Args: (), Kwargs: {'pool_size': (2, 2), 'padding': 'same'}
Adding    flatten, Args: (), Kwargs: {}
Adding      dense, Args: (1000,), Kwargs: {'activation': 'relu'}
Adding    dropout, Args: (0.05,), Kwargs: {}
Adding      dense, Args: (1000,), Kwargs: {'activation': 'relu'}
Adding    dropout, Args: (0.05,), Kwargs: {}
Adding      dense, Args: (66,), Kwargs: {'activation': 'linear'}
2021-01-26 02:34:05.180200: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-01-26 02:34:05.180679: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2021-01-26 02:34:05.195031: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1070 computeCapability: 6.1
coreClock: 1.7845GHz coreCount: 15 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 238.66GiB/s
2021-01-26 02:34:05.195441: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-01-26 02:34:05.195762: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cublas64_11.dll'; dlerror: cublas64_11.dll not found
2021-01-26 02:34:05.196070: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cublasLt64_11.dll'; dlerror: cublasLt64_11.dll not found
2021-01-26 02:34:05.196377: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cufft64_10.dll'; dlerror: cufft64_10.dll not found
2021-01-26 02:34:05.196714: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'curand64_10.dll'; dlerror: curand64_10.dll not found
2021-01-26 02:34:05.197017: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cusolver64_10.dll'; dlerror: cusolver64_10.dll not found
2021-01-26 02:34:05.197320: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cusparse64_11.dll'; dlerror: cusparse64_11.dll not found
2021-01-26 02:34:05.197626: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudnn64_8.dll'; dlerror: cudnn64_8.dll not found
2021-01-26 02:34:05.197721: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1757] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2021-01-26 02:34:05.198268: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-01-26 02:34:05.198744: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-01-26 02:34:05.198833: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      
2021-01-26 02:34:05.198893: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Loaded weights: D:\LocalPrograms\repos\GymTrain\gym-train\rl\clickr\model-13-logcos\model\weights
Loaded memory: (3000, 4) -> 3000 samples
Loading memory D:\LocalPrograms\repos\GymTrain\gym-train\rl\clickr\model-13-logcos\model\memory.npy
Saving weights D:\LocalPrograms\repos\GymTrain\gym-train\rl\clickr\model-13-logcos\model\weights
Saving memory D:\LocalPrograms\repos\GymTrain\gym-train\rl\clickr\model-13-logcos\model\memory.npy, size: 3000
Saving params D:\LocalPrograms\repos\GymTrain\gym-train\rl\clickr\model-13-logcos\model\params-model.npy
Saved model
2021-01-26 02:34:07.763275: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-01-26 02:34:08.230884: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at save_restore_v2_ops.cc:205 : Not found: Key optimizer/iter/.ATTRIBUTES/VARIABLE_VALUE not found in checkpoint
Traceback (most recent call last):
  File "D:/LocalPrograms/repos/GymTrain/gym-train/rl/clickr/model.py", line 369, in <module>
    train_it()
  File "D:/LocalPrograms/repos/GymTrain/gym-train/rl/clickr/model.py", line 33, in wrapper
    out = func(*args, **kwargs)
  File "D:/LocalPrograms/repos/GymTrain/gym-train/rl/clickr/model.py", line 364, in train_it
    agent.train(n=10, batchsize=200)
  File "D:/LocalPrograms/repos/GymTrain/gym-train/rl/clickr/model.py", line 348, in train
    self.model.fit(states, preds, batch_size=batchsize, verbose=verbose)
  File "C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 871, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 725, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 3196, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\framework\func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\framework\func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.framework.errors_impl.NotFoundError: in user code:

    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\keras\engine\training.py:805 train_function  *
        return step_function(self, iterator)
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\keras\engine\training.py:795 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\keras\engine\training.py:788 run_step  **
        outputs = model.train_step(data)
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\keras\engine\training.py:757 train_step
        self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:498 minimize
        return self.apply_gradients(grads_and_vars, name=name)
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:604 apply_gradients
        self._create_all_weights(var_list)
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:781 _create_all_weights
        _ = self.iterations
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:788 __getattribute__
        return super(OptimizerV2, self).__getattribute__(name)
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:921 iterations
        self._iterations = self.add_weight(
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py:1122 add_weight
        variable = self._add_variable_with_custom_getter(
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\training\tracking\base.py:805 _add_variable_with_custom_getter
        new_variable = getter(
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\keras\engine\base_layer_utils.py:130 make_variable
        return tf_variables.VariableV1(
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\variables.py:260 __call__
        return cls._variable_v1_call(*args, **kwargs)
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\variables.py:206 _variable_v1_call
        return previous_getter(
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\variables.py:67 getter
        return captured_getter(captured_previous, **kwargs)
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:3332 creator
        return next_creator(**kwargs)
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\variables.py:67 getter
        return captured_getter(captured_previous, **kwargs)
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:3332 creator
        return next_creator(**kwargs)
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\variables.py:67 getter
        return captured_getter(captured_previous, **kwargs)
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:3332 creator
        return next_creator(**kwargs)
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\variables.py:67 getter
        return captured_getter(captured_previous, **kwargs)
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\def_function.py:712 variable_capturing_scope
        v = UnliftedInitializerVariable(
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\variables.py:264 __call__
        return super(VariableMetaclass, cls).__call__(*args, **kwargs)
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\def_function.py:227 __init__
        initial_value = initial_value()
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\training\tracking\base.py:81 __call__
        return CheckpointInitialValue(
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\training\tracking\base.py:112 __init__
        self.wrapped_value = checkpoint_position.value_tensors(
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\training\tracking\base.py:360 value_tensors
        value, = io_ops.restore_v2(
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\gen_io_ops.py:1496 restore_v2
        return restore_v2_eager_fallback(
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\gen_io_ops.py:1535 restore_v2_eager_fallback
        _result = _execute.execute(b"RestoreV2", len(dtypes), inputs=_inputs_flat,
    C:\Users\Greg\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\execute.py:59 quick_execute
        tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,

    NotFoundError: Key optimizer/iter/.ATTRIBUTES/VARIABLE_VALUE not found in checkpoint [Op:RestoreV2]


Process finished with exit code 1

```

**Comment by akloss** [comment]
I had a similar issue, however I'm working with a custom training loop and checkpoint.read/write instead of using the keras functions. 
My problem was that the optimizer weights are only created when apply_gradients is called for the first time. So creating a checkpoint object (where the saved weights are then restored to) before that will result in a checkpoint that does not contain the optimizer variables and thus runs into an error when restoring from a file that does. 

A workaround that seems to work for me is manually calling optimizer._create_all_weights(var_list) before restoring the checkpoint, where var_list is the trainable_weights of the model. 

Maybe adding a call of optimizer._create_all_weights() in the compile or in save_weights function of keras Models would ensure that the created checkpoint is always complete with respect to the optimizer?

**Comment by GrzegorzKrug** [comment]
@jvishnuvardhan sorry, not really, thats why I pust so broad description, it just points to specific state in github. I guess there is some problem with dependencies, did you used package versions from post above  maybe?

**Comment by jvishnuvardhan** [comment]
@GrzegorzKrug I tried to run your code with recent TF/keras versions. `settings` library is not getting imported. [Here](https://colab.research.google.com/gist/jvishnuvardhan/cf1e94fba6ee9280d6b37bad8b93e237/untitled1103.ipynb) is a gist for reference. Thanks!

**Comment by GrzegorzKrug** [comment]
Check my github link, its my module with parameters named `settings.py`

**Comment by jvishnuvardhan** [comment]
I ran your code (including `settings.py`) and I don't see any error as your are facing. [Here](https://colab.research.google.com/gist/jvishnuvardhan/3c0fafd3cba455f5a23fd22086c29372/untitled1103.ipynb) is a gist for reference. Thanks!
