### ISSUE TITLE
custom loss function when y_pred includes NAN

### ISSUE THREAD

**Issue by reyhanhgh** [keras-team/keras#14442]
I am writing a custom loss function to calculate `val_loss` (mean squared error) while ignoring NANs. My data is time series involving 3 features and 1 target (4 variables in total). My target in **validation set** has occasionally NAN over one or several consecutive time steps.There is no NANs in training set. I simply want to ignore these NAN validation time steps and calculate the summed squared error between y_pred and y_true, then calculate mean over non-NAN examples. So I wrote:

```
def mse_without_nan(y_true, y_pred):
    sqr = K.square(y_pred - y_true)
    num_nan = tf.reduce_sum(tf.cast(tf.math.is_nan(sqr), tf.int32))  # calculate number of NANs
    if K.get_value(num_nan) > 0: # if there is NAN
        sqr_without_nan = tf.where(tf.math.is_nan(sqr), tf.zeros_like(sqr), sqr)  # replace NANs by zero
        num_obs = tf.reduce_sum(1 - tf.cast(tf.math.is_nan(sqr), tf.float64)) # number of y_true excluding NANs
        num_obs = K.get_value(num_obs)
        sum_without_nan = tf.reduce_sum(sqr_without_nan, axis=-1)   # sum of squares excluding NANs
        mean_without_nan = sum_without_nan / num_obs # mse
    else:
        msq = K.mean(K.square(y_pred - y_true), axis=-1)
    return msq

```
my validation batches have the shape (batch_size=4, lookback=3,  variables=4) look like this:

```
array([[[-0.45923223,  1.17119141,  0.72568208,         nan],
        [-0.57971411,  1.64142424,  1.20655258,         nan],
        [ 0.4145762 ,  1.71979638,  1.28344684,         nan]],

       [[-0.57971411,  1.64142424,  1.20655258,         nan],
        [ 0.4145762 ,  1.71979638,  1.28344684,         nan],
        [-0.14868706,  1.17119141,  0.70355153,         nan]],

       [[ 0.4145762 ,  1.71979638,  1.28344684,         nan],
        [-0.14868706,  1.17119141,  0.70355153,         nan],
        [-0.12119032,  0.8052215 ,  0.34046055,         nan]],

       [[-0.14868706,  1.17119141,  0.70355153,         nan],
        [-0.12119032,  0.8052215 ,  0.34046055,         nan],
        [-0.57971411,  1.23696802,  0.81908048,         nan]]])
​
```

my target tensors look like this:
`array([-0.66808987, -0.68215659, -0.66808987, -0.63995642])`

My is as follows:
```
model = keras.Sequential(
    [
        layers.LSTM(units=16, input_shape=(None, data_array.shape[-1]), activation=None),
        layers.Dense(units=1),
    ]
)

model.compile(optimizer="Adagrad", loss="mse", metrics=[mse_without_nan])

early_stop = callbacks.EarlyStopping(monitor="val_mse_without_nan", patience=10, restore_best_weights=True, mode="min")

```

My code does not work as a custom Keras loss function and I got this error:
```
Epoch 1/20
Traceback (most recent call last):
  File "/home/username/PycharmProjects/pythonProject/local_lstm_jupyter.py", line 236, in <module>
  history = model.fit(gen_tr,
                      File "/home/username/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
                      tmp_logs = self.train_function(iterator)
                      File "/home/username/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
                      result = self._call(*args, **kwds)
                      File "/home/username/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 871, in _call
                      self._initialize(args, kwds, add_initializers_to=initializers)
                      File "/home/username/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 725, in _initialize
                      self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
                        File "/home/username/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
                        graph_function, _ = self._maybe_define_function(args, kwargs)
                        File "/home/username/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
                        graph_function = self._create_graph_function(args, kwargs)
                        File "/home/username/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3196, in _create_graph_function
                        func_graph_module.func_graph_from_py_func(
                          File "/home/username/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
                          func_outputs = python_func(*func_args, **func_kwargs)
                          File "/home/username/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
                          out = weak_wrapped_fn().__wrapped__(*args, **kwds)
                          File "/home/username/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 977, in wrapper
                          raise e.ag_error_metadata.to_exception(e)
                          AttributeError: in user code:
                            
                            /home/username/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:805 train_function  *
                            return step_function(self, iterator)
                          /home/username/PycharmProjects/pythonProject/local_lstm_jupyter.py:213 mse_sans_na  *
                            print(K.get_value(num_na))
                          /home/username/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/tensorflow/python/keras/backend.py:3624 get_value  **
                            return eval_in_eager_or_function(x)
                          /home/username/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/tensorflow/python/keras/backend.py:4038 eval_in_eager_or_function
                          [x._numpy() for x in outputs],  # pylint: disable=protected-access
                          /home/username/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/tensorflow/python/keras/backend.py:4038 <listcomp>
                            [x._numpy() for x in outputs],  # pylint: disable=protected-access
                          
                          AttributeError: 'Tensor' object has no attribute '_numpy'
```
                          

 what is wrong ? Many thanks in advance for your thoughts.

**Comment by ymodak** [comment]
You may want to consider masking values and learning as an alternative.
