### ISSUE TITLE
model.fit() infinite loop or exits application

### ISSUE THREAD

**Issue by MovEaxEax** [keras-team/keras#14523]
### Issue:
When calling model.fit() ont a LSTM network, the training starts, but after the 4th epoch it stops in progress for infinity. Sometimes the code breaks up and throws an exception.

### Reproduce:
The "S" model is called and gets feed with [501x4] double values as input, and [1x2] double value (true or false) as expected output
```
import sys
import array
from decimal import Decimal
import os.path
from os import path
import pathlib
import numpy as np
import math
from keras.models import Sequential
from keras.layers import Dense, LSTM, GRU
import keras

import tensorflow as tf
physical_devices = tf.config.list_physical_devices('GPU') 
tf.config.experimental.set_memory_growth(physical_devices[0], True)

# Get Arguments
obj = sys.argv[1]
frame = sys.argv[2]
model_type = sys.argv[3]

#Trainingsfile
current_dir = str(pathlib.Path(__file__).parent.absolute())
network_dir = current_dir + "\\Data\\" + obj + "\\" + frame + "\\Networks\\" + model_type + "\\"
if(model_type[0] == "L"):
    trainings_file_path = current_dir + "\\Data\\" + obj + "\\" + frame + "\\Dataset\\LongSignalData.txt"
elif(model_type[0] == "S"):
    trainings_file_path = current_dir + "\\Data\\" + obj + "\\" + frame + "\\Dataset\\ShortSignalData.txt"
trainings_file = open(trainings_file_path, "r")
trainings_file_size = path.getsize(trainings_file_path)

#Detect training lines at the end of file
trainings_file.seek(trainings_file_size - 9, 0)
trainings_file_lines = int(trainings_file.read(9))
print("Filesize: " + str(trainings_file_size))
print("Lines: " + str(trainings_file_lines) + "\n")

#Reset seek position
trainings_file.seek(0, 0)

#Create Numpy-Memmap for Trainingsdata
print("Initialize Memmap...")
if(model_type[1] == "S"):
    input_data_all = np.require(np.memmap("input_map.memmap", dtype='double', mode='r+', shape=(trainings_file_lines, 501, 4)),requirements=['O'])
    output_data_all = np.require(np.memmap("output_map.memmap", dtype='double', mode='r+', shape=(trainings_file_lines, 1, 2)),requirements=['O'])
elif(model_type[1] == "P"):
    input_data_all = np.require(np.memmap("input_map.memmap", dtype='double', mode='r+', shape=(1, 501, 4)),requirements=['O'])
    output_data_all = np.require(np.memmap("output_map.memmap", dtype='double', mode='r+', shape=(1, 1, 3000)),requirements=['O'])
elif(model_type[1] == "D"):
    input_data_all = np.require(np.memmap("input_map.memmap", dtype='double', mode='r+', shape=(1, 502, 4)),requirements=['O'])
    output_data_all = np.require(np.memmap("output_map.memmap", dtype='double', mode='r+', shape=(1, 1, 240)),requirements=['O'])
print("...Done!\n")

#Read File byte by byte
position = 0
index = 0
while(index < trainings_file_lines):
    #Bool for Profit and Distance network to grow array
    bool_P = False
    bool_D = False
    
    line = "A"
    while(not line[len(line)-1] == "#"):
        line = line + trainings_file.read(1)
        position += 1
    line = line[:-1]
    line = line[1:]
    splitted_line = line.split(";")

    #Get all input candles
    i_line = 0
    if(model_type[1] == "S"):
        while(i_line < 501):
            entry = splitted_line[i_line]
            input_data_all[index][i_line][0] = Decimal(entry.split(",")[0])
            input_data_all[index][i_line][1] = Decimal(entry.split(",")[1])
            input_data_all[index][i_line][2] = Decimal(entry.split(",")[2])
            input_data_all[index][i_line][3] = Decimal(entry.split(",")[3])
            i_line += 1
    elif(model_type[1] == "P"):
        if(int(splitted_line[501]) == 1):
            while(i_line < 501):
                entry = splitted_line[i_line]
                input_data_all[len(input_data_all) - 1][i_line][0] = Decimal(entry.split(",")[0])
                input_data_all[len(input_data_all) - 1][i_line][1] = Decimal(entry.split(",")[1])
                input_data_all[len(input_data_all) - 1][i_line][2] = Decimal(entry.split(",")[2])
                input_data_all[len(input_data_all) - 1][i_line][3] = Decimal(entry.split(",")[3])
                i_line += 1
            bool_P = True
            
    elif(model_type[1] == "D"):
        if(int(splitted_line[501]) == 1):
            while(i_line < 501):
                entry = splitted_line[i_line]
                input_data_all[len(input_data_all) - 1][i_line][0] = Decimal(entry.split(",")[0])
                input_data_all[len(input_data_all) - 1][i_line][1] = Decimal(entry.split(",")[1])
                input_data_all[len(input_data_all) - 1][i_line][2] = Decimal(entry.split(",")[2])
                input_data_all[len(input_data_all) - 1][i_line][3] = Decimal(entry.split(",")[3])
                i_line += 1
            input_data_all[len(input_data_all) - 1][501][0] = Decimal((Decimal(splitted_line[502]) + 1) / 100)
            input_data_all[len(input_data_all) - 1][501][1] = 0
            input_data_all[len(input_data_all) - 1][501][2] = 0
            input_data_all[len(input_data_all) - 1][501][3] = 0
            bool_D = True

    #Get output
    if(model_type[1] == "S"):
        output_data_all[index][0][0] = 0
        output_data_all[index][0][1] = 0
        output_data_all[index][0][int(splitted_line[501])] = 1

    elif(model_type[1] == "P"):
        if(bool_P == True):
            p_fill = 0
            while(p_fill < 3000):
                output_data_all[len(input_data_all) - 1][0][p_fill] = 0
                p_fill += 1
            output_data_all[len(output_data_all) - 1][0][int(splitted_line[502])] = 1

            #Resize Arrays
            input_data_all.resize((len(input_data_all) + 1, 501, 4))
            output_data_all.resize((len(output_data_all) + 1, 1, 3000))

    elif(model_type[1] == "D"):
        if(bool_D == True):
            d_fill = 0
            while(d_fill < 240):
                output_data_all[len(input_data_all) - 1][0][d_fill] = 0
                d_fill += 1
            output_data_all[len(output_data_all) - 1][0][int(splitted_line[503])] = 1
            
            #Resize Arrays
            input_data_all.resize((len(input_data_all) + 1, 502, 4))
            output_data_all.resize((len(output_data_all) + 1, 1, 240))

    if(index > 0 and index % math.floor(trainings_file_lines/100) == 0):
        prozent = (index / math.floor(trainings_file_lines/100))
        print("Parsed " + str(prozent) + "%...")
    index += 1
    
print("End...")

#Delete Array last entry for Profit and Distance
if(model_type[1] == "P"):
    input_data_all.resize((len(input_data_all) - 1, 501, 4))
    output_data_all.resize((len(output_data_all) - 1, 1, 3000))
elif(model_type[1] == "D"):
    input_data_all.resize((len(input_data_all) - 1, 502, 4))
    output_data_all.resize((len(output_data_all) - 1, 1, 240))



#Trainingsdata is ready!
print("\nModel: " + model_type)
print("Input array size: " + str(len(input_data_all)))
print("Output array size: " + str(len(output_data_all)))

print(input_data_all[0])
print(output_data_all[0])
print(output_data_all[1])
print(output_data_all[2])
print(output_data_all[3])
print(output_data_all[4])

#Start Network training
if(path.exists(network_dir + "saved_model.pb")):
    model = keras.models.load_model(network_dir)
else:
    if(model_type[1] == "S"):
        print("- Signal Network -")
        model = Sequential()
        model.add(LSTM(1500, input_shape=(501, 4), return_sequences=True))
        model.add(LSTM(1500))
        model.add(Dense(1,activation="sigmoid"))
        model.compile(loss='mae', optimizer='adam')
    elif(model_type[1] == "P"):
        print("- Profit Network -")
        model = Sequential()
        model.add(LSTM(1500, input_shape=(501, 4), return_sequences=True))
        model.add(LSTM(1500))
        model.add(Dense(3000))
        model.compile(loss='mae', optimizer='adam')
    elif(model_type[1] == "D"):
        print("- Distance Network -")
        model = Sequential()
        model.add(LSTM(1500, input_shape=(502, 4), return_sequences=True))
        model.add(LSTM(1500))
        model.add(Dense(240))
        model.compile(loss='mae', optimizer='adam')

print("Start training...")
model.fit(np.asarray(input_data_all).astype(np.double), np.asarray(output_data_all).astype(np.double), batch_size=1, epochs=100, verbose=1, steps_per_epoch=len(input_data_all))

input("Close Program...")
```

### Details:
Here is the exception it throws
```
4/920 [..............................] - ETA: 2:23 - loss: 0.50002021-03-12 20:23:07.575427: E tensorflow/stream_executor/dnn.cc:616] CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1972): 'cudnnRNNBackwardData( cudnn.handle(), rnn_desc.handle(), model_dims.max_seq_length, output_desc.handles(), output_data.opaque(), output_desc.handles(), output_backprop_data.opaque(), output_h_desc.handle(), output_h_backprop_data.opaque(), output_c_desc.handle(), output_c_backprop_data.opaque(), rnn_desc.params_handle(), params.opaque(), input_h_desc.handle(), input_h_data.opaque(), input_c_desc.handle(), input_c_data.opaque(), input_desc.handles(), input_backprop_data->opaque(), input_h_desc.handle(), input_h_backprop_data->opaque(), input_c_desc.handle(), input_c_backprop_data->opaque(), workspace.opaque(), workspace.size(), reserve_space_data->opaque(), reserve_space_data->size())'
2021-03-12 20:23:07.575618: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at cudnn_rnn_ops.cc:1926 : Internal: Failed to call ThenRnnBackward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 1500, 1500, 1, 501, 1, 1500]
Traceback (most recent call last):
  File "E:\Obj\AI\NetworkTrainer.py", line 187, in <module>
    model.fit(np.asarray(input_data_all).astype(np.double), np.asarray(output_data_all).astype(np.double), batch_size=1, epochs=100, verbose=1, steps_per_epoch=len(input_data_all))
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 855, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 555, in call
    outputs = execute.execute(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InternalError:    Failed to call ThenRnnBackward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 1500, 1500, 1, 501, 1, 1500]
         [[{{node gradients/CudnnRNN_grad/CudnnRNNBackprop}}]]
         [[Adam/gradients/PartitionedCall]] [Op:__inference_train_function_4508]

Function call stack:
train_function -> train_function -> train_function
```
The first four epochs it predicts the output [1, 0]. But on the 5th epoch, where it breaks up, it should predict [0, 1].

Side not, I renamed my `cusolver64_11.dll` in `cusolver64_10.dll` for RTX 3090 support.

**Comment by bguetarni** [comment]
From what I see the model "S" outputs only one value:
`model.add(Dense(1,activation="sigmoid"))`

**Comment by jvishnuvardhan** [comment]
@MovEaxEax Please share a simple standalone code to reproduce the issue.

As mentioned by @bguetarni , shape mismatch or loss selection or broadcasting may be affecting the training. 

Please check a tutorial https://machinelearningmastery.com/binary-classification-tutorial-with-the-keras-deep-learning-library/ that may help you. Thanks!
