### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by zhangjie1982** [keras-team/keras#14608]
Hello, I want to make a TextCNN model for text classification, and my code is below:
```python
def TextCNN_model_1(x_train, y_train, x_test, y_test):
    main_input = Input(shape=(140,), dtype='float64')
    embedder = Embedding(len(vocab_list)+1, 300, input_length=140, trainable=False, weights=[embeddings_matrix])
    embed = embedder(main_input)
    cnn1 = Conv1D(256, 3, padding='same', strides=1, activation='relu')(embed)
    cnn1 = MaxPooling1D(pool_size=48)(cnn1)
    cnn2 = Conv1D(256, 4, padding='same', strides=1, activation='relu')(embed)
    cnn2 = MaxPooling1D(pool_size=47)(cnn2)
    cnn3 = Conv1D(256, 5, padding='same', strides=1, activation='relu')(embed)
    cnn3 = MaxPooling1D(pool_size=46)(cnn3)
    cnn = concatenate([cnn1, cnn2, cnn3], axis=1)
    flat = Flatten()(cnn)
    drop = Dropout(0.2)(flat)
    main_output = Dense(2, activation='softmax')(drop)
    model = Model(inputs=main_input, outputs=main_output)
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    one_hot_labels = keras.utils.to_categorical(y_train, num_classes=2) 
    model.fit(x_train, one_hot_labels, batch_size=40, epochs=10)
    result = model.predict(x_test)  
    result_labels = np.argmax(result, axis=1)  
    y_predict = list(map(str, result_labels))
    print(keras.metrics.accuracy(y_test, y_predict))
```

Following is Trackback info:
```
Traceback (most recent call last):
  File "/home/songyuqiu/anaconda3/envs/portrait/lib/python3.6/site-packages/keras/engine/training.py", line 692, in _prepare_total_loss
    y_true, y_pred, sample_weight=sample_weight)
  File "/home/songyuqiu/anaconda3/envs/portrait/lib/python3.6/site-packages/keras/losses.py", line 73, in __call__
    losses, sample_weight, reduction=self.reduction)
  File "/home/songyuqiu/anaconda3/envs/portrait/lib/python3.6/site-packages/keras/utils/losses_utils.py", line 166, in compute_weighted_loss
    losses, None, sample_weight)
  File "/home/songyuqiu/anaconda3/envs/portrait/lib/python3.6/site-packages/keras/utils/losses_utils.py", line 76, in squeeze_or_expand_dimensions
    elif weights_rank - y_pred_rank == 1:
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
```

I've only recently started to come into contact with machine learning and deep learning, and a lot of knowledge is not quite understood. Hope to get your help, thanks a lot.

**Comment by sushreebarsa** [comment]
@zhangjie1982 Please refer to this[ link](https://www.tensorflow.org/tutorials/keras/text_classification) for your reference to text classification. In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by sushreebarsa** [comment]
Closing this issue due to lack of recent activity & assuming this issue as resolved .Please feel free to reopen if you still have concern.Thanks!
