### ISSUE TITLE
ValueError: You are trying to load a weight file containing 4 layers into a model with 3 layers.

### ISSUE THREAD

**Issue by vaibhav016** [keras-team/keras#14612]
I forked the code from [https://github.com/TensorSpeech/TensorFlowASR](url). Ran the training script and saved the model. On testing I am getting this error.   

    Use RNNT loss in TensorFlow
    Use characters ...
    Traceback (most recent call last):
      File "test.py", line 95, in <module>
        contextnet.load_weights(args.saved)
      File "/home/abrol/miniconda3/envs/tf2/lib/python3.8/site-packages/TensorFlowASR-1.0.0-py3.8.egg/tensorflow_asr/models/base_model.py", line 65, in load_weights
      File "/home/abrol/miniconda3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 2211, in load_weights
        hdf5_format.load_weights_from_hdf5_group(f, self.layers)
      File "/home/abrol/miniconda3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 683, in load_weights_from_hdf5_group
        raise ValueError('You are trying to load a weight file '
    ValueError: You are trying to load a weight file containing 4 layers into a model with 3 layers.

On further debugging, I opened the model-weights using the following code-  

        model = 'model_trained_01_v100_error_34layer.h5'
        f = h5py.File(model, 'r')
        for item in f.attrs.keys():
            print (item, f.attrs[item])
The output is -  

    backend b'tensorflow'
    keras_version b'2.4.0'
    layer_names [b'contextnet_encoder' b'contextnet_prediction' b'contextnet_joint'
     b'loss']

This extra loss key is added, which is causing problem. Please can you help how to remove this?

**Comment by jvishnuvardhan** [comment]
@vaibhav016 Can you please share a standalone code to reproduce the issue? Thanks!
