### ISSUE TITLE
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found

### ISSUE THREAD

**Issue by Niranjan2054** [keras-team/keras#14691]
`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1360, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1453, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: Could not find variable conv2d_96/kernel. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status=Not found: Container localhost does not exist. (Could not find resource: localhost/conv2d_96/kernel)
	 [[{{node conv2d_96/Conv2D/ReadVariableOp}}]]
	 [[_arg_keras_learning_phase_0_2/_4]]
  (1) Failed precondition: Could not find variable conv2d_96/kernel. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status=Not found: Container localhost does not exist. (Could not find resource: localhost/conv2d_96/kernel)
	 [[{{node conv2d_96/Conv2D/ReadVariableOp}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/VV/main.py", line 192, in <module>
    main.viewCam()
  File "/content/VV/main.py", line 105, in viewCam
    boxes, confidence, classes = self.yolo.detect_image(Image.fromarray(frame))
  File "/content/VV/yolo.py", line 104, in detect_image
    K.learning_phase(): 0
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 968, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1369, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: Could not find variable conv2d_96/kernel. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status=Not found: Container localhost does not exist. (Could not find resource: localhost/conv2d_96/kernel)
	 [[node conv2d_96/Conv2D/ReadVariableOp (defined at usr/local/lib/python3.7/dist-packages/keras/layers/convolutional.py:245) ]]
	 [[_arg_keras_learning_phase_0_2/_4]]
  (1) Failed precondition: Could not find variable conv2d_96/kernel. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status=Not found: Container localhost does not exist. (Could not find resource: localhost/conv2d_96/kernel)
	 [[node conv2d_96/Conv2D/ReadVariableOp (defined at usr/local/lib/python3.7/dist-packages/keras/layers/convolutional.py:245) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node conv2d_96/Conv2D/ReadVariableOp:
 conv2d_96/kernel (defined at usr/local/lib/python3.7/dist-packages/keras/engine/base_layer_utils.py:127)

Input Source operations connected to node conv2d_96/Conv2D/ReadVariableOp:
 conv2d_96/kernel (defined at usr/local/lib/python3.7/dist-packages/keras/engine/base_layer_utils.py:127)

Original stack trace for 'conv2d_96/Conv2D/ReadVariableOp':
  File "content/VV/main.py", line 191, in <module>
    main = App()
  File "content/VV/main.py", line 55, in __init__
    self.yolo = YOLO()
  File "content/VV/yolo.py", line 37, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "content/VV/yolo.py", line 58, in generate
    self.yolo_model = load_model(model_path, custom_objects={'Mish': Mish}, compile=False)
  File "usr/local/lib/python3.7/dist-packages/keras/saving/save.py", line 202, in load_model
    compile)
  File "usr/local/lib/python3.7/dist-packages/keras/saving/hdf5_format.py", line 181, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "usr/local/lib/python3.7/dist-packages/keras/saving/model_config.py", line 59, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "usr/local/lib/python3.7/dist-packages/keras/layers/serialization.py", line 163, in deserialize
    printable_module_name='layer')
  File "usr/local/lib/python3.7/dist-packages/keras/utils/generic_utils.py", line 672, in deserialize_keras_object
    list(custom_objects.items())))
  File "usr/local/lib/python3.7/dist-packages/keras/engine/functional.py", line 664, in from_config
    config, custom_objects)
  File "usr/local/lib/python3.7/dist-packages/keras/engine/functional.py", line 1284, in reconstruct_from_config
    process_node(layer, node_data)
  File "usr/local/lib/python3.7/dist-packages/keras/engine/functional.py", line 1232, in process_node
    output_tensors = layer(input_tensors, **kwargs)
  File "usr/local/lib/python3.7/dist-packages/keras/engine/base_layer_v1.py", line 765, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "usr/local/lib/python3.7/dist-packages/keras/layers/convolutional.py", line 245, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1019, in convolution_v2
    name=name)
  File "usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1149, in convolution_internal
    name=name)
  File "usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 2603, in _conv2d_expanded_batch
    name=name)
  File "usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 973, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 522, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "usr/local/lib/python3.7/dist-packages/tensorflow/python/profiler/trace.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 1566, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 2005, in _dense_var_to_tensor
    return var._dense_var_to_tensor(dtype=dtype, name=name, as_ref=as_ref)  # pylint: disable=protected-access
  File "usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 1403, in _dense_var_to_tensor
    return self.value()
  File "usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 575, in value
    return self._read_variable_op()
  File "usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 682, in _read_variable_op
    result = read_and_set_handle()
  File "usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 673, in read_and_set_handle
    self._handle, self._dtype)
  File "usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_resource_variable_ops.py", line 485, in read_variable_op
    "ReadVariableOp", resource=resource, dtype=dtype, name=name)
  File "usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 3565, in _create_op_internal
    op_def=op_def)
  File "usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)`

**Comment by rmothukuru** [comment]
@Niranjan2054,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by rmothukuru** [comment]
@Niranjan2054,
This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you.

**Comment by rmothukuru** [comment]
@Niranjan2054,
Please check if your issue can be resolved by trying, as suggested in [AI Pool Answer](https://ai-pool.com/d/tensorflow-python-framework-errors_impl-failedpreconditionerror--2-root-error-s--found). Thanks!

**Comment by rmothukuru** [comment]
Closing as stale. Please reopen if you'd like to work on this further.
