### ISSUE TITLE
Keras bisect and editable install

### ISSUE THREAD

**Issue by bhack** [keras-team/keras#14867]
**System information**.

TensorFlow version (you are using):
Are you willing to contribute it (Yes/No) :
Just if we have a clear path on what will be accepted in the repo
**Describe the feature and the current behavior/state**.

I want to use `git-bisect` on different Keras commits to execute third party library tests. 
This is hard to achieve currently as Keras doesn't support editable installs (e.g. `pip -e`) and we need to build and install the wheel on every single commit.

Describe the feature clearly here. Be sure to convey here why the requested feature is needed. Any brief description about the use-case would help.

I want to move between multiple Keras commits to execute third party library tests. 
To achieve this we need to have something like an editable Keras install `pip -e`

**Will this change the current api? How?**
No

**Who will benefit from this feature?**
All the developers and third party libraries that need to execute tests on multiple  Keras commits

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

/cc @qlzh727

**Comment by haifeng-jin** [comment]
@qlzh727 Would you please take a look at this issue?
I am not sure about the process for publishing to PyPI.

**Comment by qlzh727** [comment]
Took a quick look for development mode in https://setuptools.readthedocs.io/en/latest/userguide/quickstart.html?highlight=development-mode#development-mode. 

It seems that the requirement is to have the setup.py in the keras package root directory, and I had following try, which failed.

It seems that you will need to build the protobufs that are needed by save model to work, and you probably grab them either from the existing keras pip package, or build them from scratch. 
```
(keras-nightly) scottzhu-macbookpro2:keras scottzhu$ mv keras/tools/pip_package/setup.py .
(keras-nightly) scottzhu-macbookpro2:keras scottzhu$ pip install -e .
Obtaining file:///Users/scottzhu/keras/keras
Installing collected packages: keras
  Running setup.py develop for keras
Successfully installed keras
(keras-nightly) scottzhu-macbookpro2:keras scottzhu$ pip list
Package                 Version             Location                   
----------------------- ------------------- ---------------------------
absl-py                 0.12.0              
astunparse              1.6.3               
cached-property         1.5.2               
cachetools              4.2.1               
certifi                 2020.12.5           
chardet                 4.0.0               
clang                   5.0                 
flatbuffers             1.12                
gast                    0.4.0               
google-auth             1.28.0              
google-auth-oauthlib    0.4.4               
google-pasta            0.2.0               
grpcio                  1.37.0              
h5py                    3.1.0               
idna                    2.10                
importlib-metadata      3.10.0              
keras                   2.7.0               /Users/scottzhu/keras/keras
Keras-Preprocessing     1.1.2               
Markdown                3.3.4               
numpy                   1.19.5              
oauthlib                3.1.0               
opt-einsum              3.3.0               
pip                     18.1                
pip-licenses            3.4.0               
protobuf                3.15.7              
PTable                  0.9.2               
pyasn1                  0.4.8               
pyasn1-modules          0.2.8               
requests                2.25.1              
requests-oauthlib       1.3.0               
rsa                     4.7.2               
setuptools              54.2.0              
six                     1.15.0              
tb-nightly              2.6.0a20210427      
tensorboard-data-server 0.6.0               
tensorboard-plugin-wit  1.8.0               
termcolor               1.1.0               
tf-estimator-nightly    2.5.0.dev2021032601 
tf-nightly              2.6.0.dev20210619   
typing-extensions       3.7.4.3             
urllib3                 1.26.4              
Werkzeug                1.0.1               
wheel                   0.36.2              
wrapt                   1.12.1              
zipp                    3.4.1               
You are using pip version 18.1, however version 21.1.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(keras-nightly) scottzhu-macbookpro2:keras scottzhu$ python
Python 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras
2021-07-07 10:45:04.479581: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/core/saved_model/write/count
2021-07-07 10:45:04.479642: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/core/saved_model/read/count
2021-07-07 10:45:04.479655: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/core/saved_model/write/api
2021-07-07 10:45:04.479665: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/core/saved_model/read/api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/scottzhu/keras/keras/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/Users/scottzhu/keras/keras/keras/models.py", line 20, in <module>
    from keras import metrics as metrics_module
  File "/Users/scottzhu/keras/keras/keras/metrics.py", line 26, in <module>
    from keras import activations
  File "/Users/scottzhu/keras/keras/keras/activations.py", line 20, in <module>
    from keras.layers import advanced_activations
  File "/Users/scottzhu/keras/keras/keras/layers/__init__.py", line 24, in <module>
    from keras.engine.input_layer import Input
  File "/Users/scottzhu/keras/keras/keras/engine/input_layer.py", line 21, in <module>
    from keras.engine import base_layer
  File "/Users/scottzhu/keras/keras/keras/engine/base_layer.py", line 42, in <module>
    from keras.saving.saved_model import layer_serialization
  File "/Users/scottzhu/keras/keras/keras/saving/saved_model/layer_serialization.py", line 22, in <module>
    from keras.saving.saved_model import save_impl
  File "/Users/scottzhu/keras/keras/keras/saving/saved_model/save_impl.py", line 32, in <module>
    from keras.saving.saved_model import load as keras_load
  File "/Users/scottzhu/keras/keras/keras/saving/saved_model/load.py", line 28, in <module>
    from keras.protobuf import saved_metadata_pb2
ImportError: cannot import name 'saved_metadata_pb2'
>>> 
```

**Comment by qlzh727** [comment]
After copying the protobuf generated py files from existing distribution, the development mode works.

```
(tf-nightly) scottzhu-macbookpro2:~ scottzhu$ cp tf-nightly/lib/python3.6/site-packages/keras/protobuf/*.py keras/keras/keras/protobuf/
BUILD                   projector_config.proto  saved_metadata.proto    versions.proto          
(tf-nightly) scottzhu-macbookpro2:~ scottzhu$ cp tf-nightly/lib/python3.6/site-packages/keras/protobuf/*.py keras/keras/keras/protobuf/
(tf-nightly) scottzhu-macbookpro2:~ scottzhu$ ls keras
keras/           keras-hackathon/ keras-nightly/   keras-tuner/     
(tf-nightly) scottzhu-macbookpro2:~ scottzhu$ ls keras/keras/keras/protobuf/
BUILD			projector_config.proto	saved_metadata.proto	versions.proto
__init__.py		projector_config_pb2.py	saved_metadata_pb2.py	versions_pb2.py

scottzhu-macbookpro2:~ scottzhu$ source keras-nightly/bin/activate
(keras-nightly) scottzhu-macbookpro2:~ scottzhu$ python
Python 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras
2021-07-07 10:56:17.480611: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/core/saved_model/write/count
2021-07-07 10:56:17.480667: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/core/saved_model/read/count
2021-07-07 10:56:17.480706: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/core/saved_model/write/api
2021-07-07 10:56:17.480722: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/core/saved_model/read/api
>>> 

```

**Comment by qlzh727** [comment]
In summary, I think the walk around is to mv the setup.py to a package root, and copy the protobuf py from the existing distribution, which will then make the keras Git source tree work with PIP development mode.

**Comment by bhack** [comment]
@qlzh727 Not so quickly close an issue :wink: .. as I've already tried something like this before opening the ticketand it is still quite not practical to do all this manual steps if you need to move commit by commit as with git bisect. 

Also I think that we need need other manual steps for golden or not?

Have you tried to:
`import keras.api._v2` ?

**Comment by qlzh727** [comment]
Hum, good point for keras.api.*. They are the __init__ files that used to populate the tf.keras namespace (if you use `from tensorflow import keras`). Those files are included in the distribution, but not in the source code (since they are generated files via script, same as the protobuf py files).

It seems that we will need some small script that move and generate all the needed files from the source code, which I think is doable (since they should be generate via bazel). You can rerun the scripts after you checkout certain git commits to do bisect.

**Comment by bhack** [comment]
We can run two scripts with `git bisect` eg:

`git bisect run sh -c 'bootstrap_keras.sh  && bazel test -c opt keras:backend_test'`.

But I think that simply coping stuffs in `keras/keras/keras/protobuf/` as you suggest it will go to produce a git mess in the source code checkout:

E.g. the protobuf dir at checkout has already:
 `BUILD  projector_config.proto  saved_metadata.proto  versions.proto`

So I suppose that we need also something else to reach a working solution.

And now the 1 Billion dollar question:
When we move between Keras commits what we can do with the Tensorflow dependency? Can we move over nightly? Are we at least 1 day tf-nightly API compatible?

**Comment by qlzh727** [comment]
For the mess it creates, I guess the script need some post cleanup for any generated files, or make at least make git to untrack them (eg update the gitignore just for bisect). 

For TF dependency, I think we are at least 1 tf-nightly API compatible. I think seldomly make backward incomatible changes in tf.

**Comment by bhack** [comment]
> For the mess it creates, I guess the script need some post cleanup for any generated files, or at least make git to untrack them (eg update the gitignore just for bisect).

I don't know if in the end it could be clean enough or we need to change something else. I think it is not only bisect it simply also if a dev want to manually move between Keras commit and test a third_party library the depends on Keras.

> For TF dependency, I think we are at least 1 tf-nightly API compatible. I think seldomly make backward incomatible changes in tf.

Can we handle this more formally in:
https://github.com/keras-team/keras/blob/41bd035a19904118944ef271342562f65b90fd3c/requirements.txt#L6

E.g. `dev20210707` or a `>= <=` range so that the compatibility control is on the Keras team side. If I move between commits on a long range or simply on a longer then 1 day range I will know exactly on what specific TF version it was tested in the Keras CI the specific commit and so what TF version to install on my local setup/CI.

**Comment by qlzh727** [comment]
we could force a more strict tf-nightly version, but this will leave more maintainance issue since we have to update this often. So far we only change this file when least tf-nightly is broken, and we want to ping to an older nightly version. 

Could you also just make the update on your local workspace to achieve smaller range you want?

**Comment by bhack** [comment]
> Could you also just make the update on your local workspace to achieve smaller range you want?

I really don't know when the API is broken or not. 
I only know that you have runned tests on master with the tf-nightly version available at the datetime of the commit or at the CI job datetime that I  suppose are quite similar.

So what we are asking to developers? To install tf-nightly with the same datetime of the commit every time he move between commits? 
Does he need also to manually check  that the commit time crossed the new tf-nightly scheduled release in the same day? 
Does he need to calc timezones?

By the external developer point of view he really don't know when a specific Keras commit is not compatibile anymore with a new or old tf-nightly version as the dependency is generic.

**Comment by bhack** [comment]
I think that that the CI itself or copybara will need to update the tf-nightly version on the commit push if tested on a new nightly release.

Can we claim any other compatibility on the specific commit? I suppose not as we are not testing a tf-nightly matrix

**Comment by bhack** [comment]
If we are quite shure that we have stable TF API we could just soften the TF nightly version dependency with a `>=`.

**Comment by bhack** [comment]
@qlzh727 Just to make some step ahead with `pip install -e ` 

> Hum, good point for keras.api.*. They are the __init__ files that used to populate the tf.keras namespace (if you use from tensorflow import keras). Those files are included in the distribution, but not in the source code (since they are generated files via script, same as the protobuf py files).

Do we have any other candidate solution instead of moving manually all these file every time?

**Comment by qlzh727** [comment]
> @qlzh727 Just to make some step ahead with `pip install -e `
> 
> > Hum, good point for keras.api.*. They are the **init** files that used to populate the tf.keras namespace (if you use from tensorflow import keras). Those files are included in the distribution, but not in the source code (since they are generated files via script, same as the protobuf py files).
> 
> Do we have any other candidate solution instead of moving manually all these file every time?

So far I think either copying or regenerate those files will be the solution I recommend. Including the generated content in the Git repo will create more maintainance overhead since we need to keep them in sync with the original source.

**Comment by bhack** [comment]
> So far I think either copying or regenerate those files will be the solution I recommend. Including the generated content in the Git 
If will copy these file from `bazel-bin/` they will be monitored by  git

Also I cannot play with `PYTHONPATH=bazel-bin/` as the proto source  `.proto` and the expected gen has the same module/dir hierarchy.

Can we change in the repository `keras/protobuf/` with something like `keras/protobuf_defs/` or `protobuf_src` or as you like?

**Comment by bhack** [comment]
@qlzh727  As we claim now in the Readme:

`the nightly Keras releases are usually compatible with the corresponding version of the tf-nightly releases (e.g. keras-nightly==2.7.0.dev2021100607 should be used with tf-nightly==2.7.0.dev2021100607).` 

Can we just pin on the `tf-nightly` version on what we are running the test with the CI on master every day?

**Comment by qlzh727** [comment]
> @qlzh727 As we claim now in the Readme:
> 
> `the nightly Keras releases are usually compatible with the corresponding version of the tf-nightly releases (e.g. keras-nightly==2.7.0.dev2021100607 should be used with tf-nightly==2.7.0.dev2021100607).`
> 
> Can we just pin on the `tf-nightly` version on what we are running the test with the CI on master every day?

Sorry for the late reply. 

We could do that, (we sometimes pin to a old version on CI to avoid some breakage caused on TF side). This will involve some script to automatically update the requirements.txt at a certain time everyday, and it need to make sure the corresponding tf-nightly does exist.

Let me see if this is easer to do it internally or on github.

**Comment by bhack** [comment]
> This will involve some script to automatically update the requirements.txt at a certain time everyday, and it need to make sure the corresponding tf-nightly does exist.

Yes this is exactly what I meant. Probably we could handle this with a Github action directly (or your copybara).

**Comment by bhack** [comment]
@qlzh727 Do you know if this task is scheduled in your roadmap? As it seems that a similar logic is required in general when you have nightly (unversioned) dependecies.  E.g. See the recent ticket in Keras-cv https://github.com/keras-team/keras-cv/issues/195#issuecomment-1075723165
