### ISSUE TITLE
Possible circular import problem

### ISSUE THREAD

**Issue by suvadityamuk** [keras-team/keras#14868]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Home Single Language (10.0, Build 19043)
- TensorFlow installed from (source or binary): using Pip
- TensorFlow version (use command below): v1.12.1-59746-gf10f5080a3c 2.7.0-dev20210703
![image](https://user-images.githubusercontent.com/70141886/124365028-00e7db00-dc63-11eb-950c-bed1b4d7d9d0.png)

- Python version: 3.9
- GPU model and memory: NVIDIA GTX 1650Ti 4GB
- Exact command to reproduce: from keras.models import Sequential
- Keras version : 
![image](https://user-images.githubusercontent.com/70141886/124365020-f62d4600-dc62-11eb-8840-ddcfac2e20b8.png)

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

**Describe the problem**.
I have tried to run the following imports into my environment for a Python script, but it throws a circular import error.

**Describe the current behavior**.
It is returning a traceback of the same problem.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): No

**Standalone code to reproduce the issue**.
```
import numpy
import os
import pandas_datareader as web
import matplotlib.pyplot as plt
from matplotlib import style
import pandas as pd
import datetime as dt
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers import Dense
```

Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Source code / logs**.
![image](https://user-images.githubusercontent.com/70141886/124364973-b6665e80-dc62-11eb-8fcd-62ee31750498.png)

2021-07-04 00:45:44.885434: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
ot have a GPU set up on your machine.
Traceback (most recent call last):
  File ".\GoldLSTMTrial.py", line 16, in <module>
    from keras.models import Sequential
  File "C:\Users\suvad\Python Works\.venv\lib\site-packages\keras\__init__.py", line 25, in <module>
  File "C:\Users\suvad\Python Works\.venv\lib\site-packages\keras\models.py", line 20, in <module>
    from keras import metrics as metrics_module
  File "C:\Users\suvad\Python Works\.venv\lib\site-packages\keras\metrics.py", line 26, in <module>
  File "C:\Users\suvad\Python Works\.venv\lib\site-packages\keras\activations.py", line 20, in <module>
  File "C:\Users\suvad\Python Works\.venv\lib\site-packages\keras\layers\__init__.py", line 24, in <module>
    from keras.engine.input_layer import Input
  File "C:\Users\suvad\Python Works\.venv\lib\site-packages\keras\engine\input_layer.py", line 21, in <module>
    from keras.engine import base_layer
  File "C:\Users\suvad\Python Works\.venv\lib\site-packages\keras\engine\base_layer.py", line 40, in <module>
    from keras.mixed_precision import loss_scale_optimizer
  File "C:\Users\suvad\Python Works\.venv\lib\site-packages\keras\mixed_precision\loss_scale_optimizer.py", line 19, in <module>
    from keras import optimizers
  File "C:\Users\suvad\Python Works\.venv\lib\site-packages\keras\optimizers\__init__.py", line 1, in <module>
    from tensorflow.keras.optimizers import *
  File "C:\Users\suvad\Python Works\.venv\lib\site-packages\keras\api\_v2\keras\__init__.py", line 10, in <module>
    from keras import __version__
ImportError: cannot import name '__version__' from partially initialized module 'keras' (most likely due to a circular import) (C:\Users\suvad\Python Works\.venv\lib\site-packages\keras\__init__.py)

**Comment by haifeng-jin** [comment]
@suvadityamuk We are not using `import keras` or `from keras import ...` any more.
Would you please change them to `from tensorflow import keras` and try again?
