### ISSUE TITLE
Bad marshal when loading lambda model saved with different Python minor version

### ISSUE THREAD

**Issue by ZJaume** [keras-team/keras#14875]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.7 and 3.8

**Describe the problem**.
I've been having problems when loading models that contain lambda layers trained with a different version of Python. Then I ran tried the code of #7440 and realize that that issue also happens with different Python minor versions, like save with 3.8 and load with 3.7

**Describe the current behavior**.
Keras in Python 3.7 fails to load saved model that contains a lambda layer and has been saved with Python 3.8

**Describe the expected behavior**.
Keras loads it succesfully in both Python minor versions.

**Standalone code to reproduce the issue**.

```python
from tensorflow.keras.layers import Input, Lambda
from tensorflow.keras.models import load_model
from tensorflow.keras import Model
import sys

if sys.version_info > (3, 8):
    inp = Input(shape=(28,28,1))
    x = Lambda(lambda x: x + 1)(inp)
    model = Model(inp, x)
    model.save('lambdamodel.hdf5')
else:
    model = load_model('lambdamodel.hdf5') # Error here.
    model.summary()
```
Steps to reproduce with virtual environment
1. Run the script inside a Python 3.8 environment to generate the saved model.
2. Run the script inside a Python 3.7 environment to load the model and see the error.

**Source code / logs**.

```python
Traceback (most recent call last):
  File "lambda_serialize_test.py", line 12, in <module>
    model = load_model('lambdamodel.hdf5') # Error here.
  File "/work/user/test/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 202, in load_model
    compile)
  File "/work/user/test/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 181, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/work/user/test/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/model_config.py", line 59, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/work/user/test/venv/lib/python3.7/site-packages/tensorflow/python/keras/layers/serialization.py", line 163, in deserialize
    printable_module_name='layer')
  File "/work/user/test/venv/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 672, in deserialize_keras_object
    list(custom_objects.items())))
  File "/work/user/test/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py", line 669, in from_config
    config, custom_objects)
  File "/work/user/test/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py", line 1279, in reconstruct_from_config
    process_layer(layer_data)
  File "/work/user/test/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py", line 1261, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/work/user/test/venv/lib/python3.7/site-packages/tensorflow/python/keras/layers/serialization.py", line 163, in deserialize
    printable_module_name='layer')
  File "/work/user/test/venv/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 672, in deserialize_keras_object
    list(custom_objects.items())))
  File "/work/user/test/venv/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py", line 1022, in from_config
    config, custom_objects, 'function', 'module', 'function_type')
  File "/work/user/test/venv/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py", line 1074, in _parse_function_from_config
    config[func_attr_name], globs=globs)
  File "/work/user/test/venv/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 783, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)
```

**Comment by ZJaume** [comment]
Actually noticed that this also happens if you marshal a lambda python function, so it doesn't seem to be a problem of Keras.

Figured it out with this code:
```python
from types import FunctionType
import marshal
import sys

if sys.version_info > (3, 8):
    f = lambda x: x +1
    with open('lambda.func', 'wb+') as file_:
        file_.write(marshal.dumps(f.__code__))
    with open('lambda.func', 'rb') as file_:
        g = FunctionType(marshal.loads(file_.read()), globals())
        print("Func(3)", g(3))
else:
    with open('lambda.func', 'rb') as file_:
        g = FunctionType(marshal.loads(file_.read()), globals())
        print("Func(3)", g(3))
```

Closing
