### ISSUE TITLE
StringLookup with Supplied Vocab - AttributeError: 'MapDataset' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by DuncBegg** [keras-team/keras#14978]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Home Version 10.0.19043
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): v1.12.1-60646-gd027ec99f28 2.7.0-dev20210720
- Python version: 3.8.10
- Bazel version (if compiling from source): N/A
- GPU model and memory: 
- Exact command to reproduce: 

**Describe the problem**.

When using the tf.keras.layers.StringLookup with a vocab that i supply, when i pass my dataset to that layer i get the following error message: 

AttributeError: 'MapDataset' object has no attribute 'dtype'

Code snippet:

#Split off a feature column from larger dataset:
ds_symbol = ds.map(lambda x: x['01-Symbol'])

#Element spec of new dataset:
print(ds_symbol.element_spec) =>TensorSpec(shape=(), dtype=tf.string, name=None)

#Create keras preprocessing layer using a supplied vocab:
#Vocab list looks like this: ['AC8', 'BNO', 'BLD', 'ASL', 'AQI', 'EXL', 'ELO', 'FMG', 'EAR', 'EEG', 'AQD', 'GXY', 'LOM', 'MED', ...]
layer_vocab = tf.keras.layers.StringLookup(vocabulary=list(vocab),output_mode='int')

#Error thrown here:
ds_new = layer_vocab(ds_symbol) 

Traceback (most recent call last):
  File "z:\admin\Projects\Coding\Machine Learning\ASX Price Prediction\Project\analysis\Multi Symbol\data_loader.py", line 236, in <module>
    main()
  File "z:\admin\Projects\Coding\Machine Learning\ASX Price Prediction\Project\analysis\Multi Symbol\data_loader.py", line 227, in main
    ds,_,_ = get_dataset(data_files)
  File "z:\admin\Projects\Coding\Machine Learning\ASX Price Prediction\Project\analysis\Multi Symbol\data_loader.py", line 194, in get_dataset
    ds_new = layer_vocab(ds_symbol)
  File "C:\Users\dunca\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\engine\base_layer.py", line 1037, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "C:\Users\dunca\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\layers\preprocessing\index_lookup.py", line 603, in call
    inputs = self._standardize_inputs(inputs, self._key_dtype)
  File "C:\Users\dunca\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\layers\preprocessing\index_lookup.py", line 736, in _standardize_inputs
    if inputs.dtype != dtype:
AttributeError: 'MapDataset' object has no attribute 'dtype'

**Describe the current behavior**.
Error thrown when applying preprocessing layer to a dataset

**Describe the expected behavior**.
The dataset will be encoded to integer by the preprocessing layer

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): No

**Standalone code to reproduce the issue**.

**Source code / logs**.

See above

**Comment by DuncBegg** [comment]
Please ignore. 
I was preprocessing the data outside the model. 
For this i needed to use: ds_symbol = ds_symbol.map(lambda x: (layer_vocab(x)))
