### ISSUE TITLE
Problem with loss dictionary with generative VAE import example

### ISSUE THREAD

**Issue by luisArandas** [keras-team/keras#15019]
Hello all!

I am experiencing an error related to the generative VAE example provided in the official Keras documentation https://keras.io/examples/generative/vae/. This code works perfectly on a singular .py file and I'm even working with custom datasets at 512x512.

However I'm trying to integrate the image rendering in a realtime GUI and I can't run **exactly** the same code. I get the error:

```
<__main__.VAE object at 0x7fb3f043e850>
Found 101 images belonging to 3 classes.
Found 101 images belonging to 3 classes.
WARNING:tensorflow:Output output_1 missing from loss dictionary. We assume this was done on purpose. The fit and evaluate APIs will not be expecting any data to be passed to output_1.
Traceback (most recent call last):
  File "/home/luis/Desktop/keras/full/rt.py", line 690, in <module>
    main()
  File "/home/luis/Desktop/keras/full/rt.py", line 572, in main
    vae.fit(custom_, epochs=10, batch_size=32)
  File "/home/luis/anaconda3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/keras/engine/training_v1.py", line 795, in fit
    return func.fit(
  File "/home/luis/anaconda3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/keras/engine/training_arrays_v1.py", line 619, in fit
    x, y, sample_weights = model._standardize_user_data(
  File "/home/luis/anaconda3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/keras/engine/training_v1.py", line 2330, in _standardize_user_data
    self._compile_from_inputs(all_inputs, y_input, x, y)
  File "/home/luis/anaconda3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/keras/engine/training_v1.py", line 2580, in _compile_from_inputs
    self.compile(
  File "/home/luis/anaconda3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/training/tracking/base.py", line 522, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/luis/anaconda3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/keras/engine/training_v1.py", line 461, in compile
    self._compile_weights_loss_and_weighted_metrics()
  File "/home/luis/anaconda3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/training/tracking/base.py", line 522, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/luis/anaconda3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/keras/engine/training_v1.py", line 1549, in _compile_weights_loss_and_weighted_metrics
    self.total_loss = self._prepare_total_loss(masks)
  File "/home/luis/anaconda3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/keras/engine/training_v1.py", line 1644, in _prepare_total_loss
    raise ValueError('The model cannot be compiled '
ValueError: The model cannot be compiled because it has no loss to optimize.
```

It has exactly the same imports and is running on top of the page so nothing happens before this to create some kind of compatibility issues. When I run `vae.fit(custom_dataset, epochs=10, batch_size=32)` it gives me this error. Is it related with the custom training step and the class?

**System information**.

- OS Platform and Distribution: Linux Ubuntu 20.04
- Tensorflow and Tensorflow-gpu 2.5.0 in Conda
- Python version 3.9.5 (default, Jun  4 2021, 12:28:51) 
- GPU GeForce RTX 3070, 7981MiB, CUDA Version 11.2

Thanks!

**Comment by rmothukuru** [comment]
@luisArandas,
Can you provide more details on how you are rendering the Image using RealTime GUI? Is it through a Website?

**Comment by luisArandas** [comment]
Hello @rmothukuru! No it's all python, I'm just instantiating a port of the imgui library. The thing is, this is not mega relevant since I can import the VAE from other file (import the class, just as it is in the example, also with encoder and decoder) and then print it as you can see in the example above.` <__main__.VAE object at 0x7fb3f043e850>`. I just can't run the fit() command. I wonder if this is connected with the custom training step? I have no clue on how to solve this.

**Comment by rchao** [comment]
From the stack trace it is suggesting the V1 path is used. Can you try using TF2 and see if the problem is still there?

**Comment by luisArandas** [comment]
Hello @rchao, I am using TF2.5. Here I leave my conda env list:

```
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
absl-py                   0.12.0                   pypi_0    pypi
appdirs                   1.4.4                      py_0  
astunparse                1.6.3                      py_0  
attrs                     21.2.0             pyhd3eb1b0_0  
audioread                 2.1.9            py39hf3d152e_0    conda-forge
blosc                     1.21.0               h9c3ff4c_0    conda-forge
brotli                    1.0.9                h7f98852_5    conda-forge
brotli-bin                1.0.9                h7f98852_5    conda-forge
brotlipy                  0.7.0           py39h27cfd23_1003  
brunsli                   0.1                  h9c3ff4c_0    conda-forge
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.17.1               h27cfd23_0  
ca-certificates           2021.5.30            ha878542_0    conda-forge
cachetools                4.2.2                    pypi_0    pypi
certifi                   2021.5.30        py39hf3d152e_0    conda-forge
cffi                      1.14.5           py39h261ae71_0  
cfitsio                   3.470                h2e3daa1_7    conda-forge
chardet                   4.0.0           py39h06a4308_1003  
charls                    2.2.0                h9c3ff4c_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
cmake                     3.20.4               h8897547_0    conda-forge
cryptography              3.4.7            py39hd23ed53_0  
cudatoolkit               11.2.72              h2bc3f7f_0    nvidia
cudnn                     8.1.0.77             h90431f1_0    conda-forge
cycler                    0.10.0           py39h06a4308_0  
cytoolz                   0.11.0           py39h3811e60_3    conda-forge
dask-core                 2021.7.0           pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyh6d0b6a4_7  
decorator                 5.0.9              pyhd3eb1b0_0  
dill                      0.3.4              pyhd8ed1ab_0    conda-forge
expat                     2.4.1                h2531618_2  
ffmpeg                    1.4                      pypi_0    pypi
ffmpeg-python             0.2.0                    pypi_0    pypi
flatbuffers               1.12                     pypi_0    pypi
freetype                  2.10.4               h5ab3b9f_0  
fsspec                    2021.7.0           pyhd8ed1ab_0    conda-forge
future                    0.18.2           py39h06a4308_1  
gast                      0.4.0                    pypi_0    pypi
gettext                   0.21.0               hf68c758_0  
giflib                    5.2.1                h36c2ea0_2    conda-forge
glfw                      2.1.0                    pypi_0    pypi
gmp                       6.2.1                h2531618_2  
gnutls                    3.6.15               he1e5248_0  
google-auth               1.31.0                   pypi_0    pypi
google-auth-oauthlib      0.4.4                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.34.1                   pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
icu                       58.2                 he6710b0_3  
idna                      2.10               pyhd3eb1b0_0  
imagecodecs               2021.6.8         py39h44211f0_0    conda-forge
imageio                   2.9.0                      py_0    conda-forge
imageio-ffmpeg            0.4.4                    pypi_0    pypi
imgui                     1.3.0                    pypi_0    pypi
iniconfig                 1.1.1              pyhd3eb1b0_0  
intel-openmp              2021.2.0           h06a4308_610  
jbig                      2.1                  hdba287a_0  
joblib                    1.0.1              pyhd3eb1b0_0  
jpeg                      9d                   h36c2ea0_0    conda-forge
jxrlib                    1.1                  h7f98852_2    conda-forge
kaggle                    1.5.12                   pypi_0    pypi
keras-nightly             2.5.0.dev2021032900          pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.1            py39h2531618_0  
krb5                      1.19.1               h3535a68_0  
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.35.1               h7274673_9  
lerc                      2.2.1                h2531618_0  
libaec                    1.0.5                h9c3ff4c_0    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libbrotlicommon           1.0.9                h7f98852_5    conda-forge
libbrotlidec              1.0.9                h7f98852_5    conda-forge
libbrotlienc              1.0.9                h7f98852_5    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libcurl                   7.77.0               h2574ce0_0    conda-forge
libdeflate                1.7                  h27cfd23_5  
libedit                   3.1.20210216         h27cfd23_1  
libev                     4.33                 h7b6447c_0  
libffi                    3.3                  he6710b0_2  
libflac                   1.3.3                h9c3ff4c_1    conda-forge
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   9.3.0               h5101ec6_17  
libidn2                   2.3.1                h27cfd23_0  
liblapack                 3.8.0               17_openblas    conda-forge
libllvm10                 10.0.1               hbcb73fb_5  
libnghttp2                1.43.0               h812cca2_0    conda-forge
libogg                    1.3.5                h27cfd23_1  
libopenblas               0.3.10               h5a2b251_0  
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.37               hbc83047_0  
librosa                   0.8.1              pyhd8ed1ab_0    conda-forge
libsndfile                1.0.31               h9c3ff4c_1    conda-forge
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtasn1                  4.16.0               h27cfd23_0  
libtiff                   4.3.0                hf544144_1    conda-forge
libunistring              0.9.10               h27cfd23_0  
libuv                     1.40.0               h7b6447c_0  
libvorbis                 1.3.7                h7b6447c_0  
libvpx                    1.7.0                h439df22_0  
libwebp-base              1.2.0                h27cfd23_0  
libxcb                    1.13              h7f98852_1003    conda-forge
libxml2                   2.9.12               h03d6c58_0  
libzopfli                 1.0.3                h9c3ff4c_0    conda-forge
llvmlite                  0.36.0           py39h612dafd_4  
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.9.3                h2531618_0  
markdown                  3.3.4                    pypi_0    pypi
matplotlib-base           3.3.4            py39h62a2d02_0  
mkl                       2020.2                      256  
mkl-include               2021.2.0           h06a4308_296  
more-itertools            8.8.0              pyhd3eb1b0_0  
multiprocess              0.70.12.2        py39h3811e60_0    conda-forge
ncurses                   6.2                  he6710b0_1  
nettle                    3.7.3                hbbd107a_1  
networkx                  2.3                        py_0    conda-forge
ninja                     1.10.2               hff7bd54_1  
numba                     0.53.1           py39ha9443f7_0  
numpy                     1.18.5                   pypi_0    pypi
oauthlib                  3.1.1                    pypi_0    pypi
olefile                   0.46                       py_0  
openh264                  2.1.0                hd408876_0  
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 20.9               pyhd3eb1b0_0  
pandas                    1.2.4            py39h2531618_0  
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
perlin-numpy              0.0.0                    pypi_0    pypi
pillow                    8.2.0            py39he98fc37_0  
pip                       21.1.3           py39h06a4308_0  
pluggy                    0.13.1           py39h06a4308_0  
pooch                     1.4.0              pyhd3eb1b0_0  
portaudio                 19.6.0               h7b6447c_4  
protobuf                  3.17.3                   pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
py                        1.10.0             pyhd3eb1b0_0  
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pyaudio                   0.2.11           py39h27cfd23_2  
pycparser                 2.20                       py_2  
pyopengl                  3.1.5                      py_0    conda-forge
pyopenssl                 20.0.1             pyhd3eb1b0_1  
pyparsing                 2.4.7              pyhd3eb1b0_0  
pypn                      0.9                      pypi_0    pypi
pypng                     0.0.20                   pypi_0    pypi
pysocks                   1.7.1            py39h06a4308_0  
pysoundfile               0.10.3.post1       pyhd3deb0d_0    conda-forge
pytest                    6.2.4            py39h06a4308_2  
python                    3.9.5                h12debd9_4  
python-dateutil           2.8.1              pyhd3eb1b0_0  
python-mpv                0.5.2                    pypi_0    pypi
python-slugify            5.0.2                    pypi_0    pypi
python-sounddevice        0.4.1              pyh9f0ad1d_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.1             pyhd3eb1b0_0  
pywavelets                1.1.1            py39hce5d2b2_3    conda-forge
pyyaml                    5.4.1            py39h27cfd23_1  
readline                  8.1                  h27cfd23_0  
requests                  2.25.1             pyhd3eb1b0_0  
requests-oauthlib         1.3.0                    pypi_0    pypi
resampy                   0.2.2                      py_0    conda-forge
rhash                     1.4.1                h3c74f83_1  
rsa                       4.7.2                    pypi_0    pypi
scikit-image              0.18.2           py39hde0f152_0    conda-forge
scikit-learn              0.24.2           py39ha9443f7_0  
scipy                     1.5.3            py39hf3f25e7_0    conda-forge
setuptools                52.0.0           py39h06a4308_0  
six                       1.15.0                   pypi_0    pypi
snappy                    1.1.8                he1b5a44_3    conda-forge
sqlite                    3.36.0               hc218d9a_0  
tbb                       2020.3               hfd86e86_0  
tensorboard               2.5.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorflow                2.5.0                    pypi_0    pypi
tensorflow-estimator      2.5.0                    pypi_0    pypi
tensorflow-gpu            2.5.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
text-unidecode            1.3                      pypi_0    pypi
threadpoolctl             2.1.0              pyh5ca1d4c_0  
tifffile                  2021.7.2           pyhd8ed1ab_0    conda-forge
tk                        8.6.10               hbc83047_0  
toml                      0.10.2             pyhd3eb1b0_0  
toolz                     0.11.1                     py_0    conda-forge
torch                     1.10.0a0+git69b2bf7          pypi_0    pypi
tornado                   6.1              py39h27cfd23_0  
tqdm                      4.61.1                   pypi_0    pypi
typing_extensions         3.7.4.3            pyh06a4308_0  
tzdata                    2021a                h52ac0ba_0  
urllib3                   1.26.6             pyhd3eb1b0_1  
werkzeug                  2.0.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0  
wrapt                     1.12.1                   pypi_0    pypi
x264                      1!157.20191217       h7b6447c_0  
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxcursor           1.2.0                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxinerama          1.1.4             h9c3ff4c_1001    conda-forge
xorg-libxrandr            1.5.2                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-randrproto           1.5.0             h7f98852_1001    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
zfp                       0.5.5                h9c3ff4c_5    conda-forge
zlib                      1.2.11               h7b6447c_3  
zstd                      1.5.0                ha95c52a_0    conda-forge

```

**Comment by rchao** [comment]
Thanks, can you attempt to use `tf.compat.v1.enable_v2_behavior()` at the start of the program and see if it helps in any way?
