### ISSUE TITLE
Saving models with custom layers on GCS after training on Cloud TPUs

### ISSUE THREAD

**Issue by AdityaKane2001** [keras-team/keras#15041]
Does Keras support saving model with custom layers in .h5 format on GCS? I am training on Cloud TPUs, hence I am forced to use GCS. I am getting this error:
Implementation details omitted for brevity, but you can find the implementation [here](https://github.com/AdityaKane2001/regnety).
```
Traceback (most recent call last):
  File "./regnety/regnety/train.py", line 114, in <module>
    model.save(os.path.join(train_cfg.model_dir, model_name)) # model_name is something like "final.h5"
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2112, in save
    signatures, options, save_traces)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 147, in save_model
    model, filepath, overwrite, include_optimizer)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 103, in save_model_to_hdf5
    f = h5py.File(filepath, mode='w')
  File "/opt/conda/lib/python3.7/site-packages/h5py/_hl/files.py", line 427, in __init__
    swmr=swmr)
  File "/opt/conda/lib/python3.7/site-packages/h5py/_hl/files.py", line 196, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 116, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = 'gs://bucketname/final.h5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)
```

To save these custom layered models, I thought one can save it directly as h5, but needs a custom object dict while loading. Please correct me if I am wrong.

**Comment by AdityaKane2001** [comment]
@ymodak 

Could you please take a look at this one?

**Comment by rchao** [comment]
Can you try saving the h5 file locally, transfer that to GCS, and see if this works?

**Comment by AdityaKane2001** [comment]
@rchao 

I am training on a Cloud TPU. So IMO that's not possible.
