### ISSUE TITLE
TypeError: Cannot convert a symbolic Keras input/output to a numpy array by using a custom layer

### ISSUE THREAD

**Issue by sunw70** [keras-team/keras#15121]
**System information**

- OS Platform and Distribution: Linux Ubuntu 20.10
- TensorFlow installation: pip package
- Tensorflow version: 2.6.0rc1
- Python version: 3.8

I created a Keras custom layer which implements a custom causal Conv1D. To do it, I simply used the classes Conv and Conv1D (they are in tensorflow/python/keras/layers/convolutional.py) and modified Conv. I'll show you how I use this layer with a very silly example dataset, which is characterized by only two training samples (given an ordered sequence of numbers as a training sample, the model should predict its next sequence: for example, if I've [0, 1, 2] the output will be [3, 4, 5]). However I get the following error:

```
Traceback (most recent call last):
File "model.py", line 406, in <module>
model = build_model(x_train, y_train)
File "model.py", line 373, in build_model
r=Myconv1D(filters=1,kernel_size=3,padding='causal',dilation_rate=1,use_bias=False,name="MyConv")(inp)
File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1057, in __call__
outputs = call_fn(inputs, *args, **kwargs)
File "model.py", line 181, in call
z[0,4+i,0].assign(inputs[0,i,0])  
File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 1235, in assign
return var._strided_slice_assign(
File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1392, in   
_strided_slice_assign
value=ops.convert_to_tensor(value, dtype=self.dtype),
File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py", line 163, in wrapped
return func(*args, **kwargs)
File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1566, in convert_to_tensor
ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 346, in    
_constant_tensor_conversion_function
return constant(v, dtype=dtype, name=name)
File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 271, in constant
return _constant_impl(value, dtype, shape, name, verify_shape=False,
File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 283, in    
_constant_impl
return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 308, in   
_constant_eager_impl
t = convert_to_eager_tensor(value, ctx, dtype)
File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 106, in    
convert_to_eager_tensor
return ops.EagerTensor(value, ctx.device_name, dtype)
File "/home/es/venv/lib/python3.8/site-packages/keras/engine/keras_tensor.py", line 244, in __array__
raise TypeError(
TypeError: Cannot convert a symbolic Keras input/output to a numpy array. This error may indicate that you're trying to pass a     
symbolic value to a NumPy call, which is not supported. Or, you may be trying to pass Keras symbolic inputs/outputs to a TF    
API that does not register dispatching, preventing Keras from automatically converting the API call to a lambda layer in the     
Functional Model.


```
I attached the example code used to train the model:
[model.zip](https://github.com/keras-team/keras/files/6946481/model.zip)

**Comment by sunw70** [comment]
Is there news about this?

**Comment by tilakrayal** [comment]
@sunw70 ,
Could you please try as per the [comment](https://stackoverflow.com/questions/65366442/cannot-convert-a-symbolic-keras-input-output-to-a-numpy-array-typeerror-when-usi) above and let us know if this is still an issue ? Thanks!

**Comment by sunw70** [comment]
By using Tensorflow version 2.4.1 instead, I get this:
  
    Epoch 1/10
    WARNING:tensorflow:Gradients do not exist for variables ['MyConv/kernel:0'] when minimizing the loss.
    WARNING:tensorflow:Gradients do not exist for variables ['MyConv/kernel:0'] when minimizing the loss.
    2/2 [==============================] - 1s 1ms/step - loss: 113.0949 - accuracy: 1.0000
    Epoch 2/10
    2/2 [==============================] - 0s 1ms/step - loss: 117.4004 - accuracy: 1.0000
    Epoch 3/10
    2/2 [==============================] - 0s 1ms/step - loss: 124.0515 - accuracy: 1.0000
    Epoch 4/10
    2/2 [==============================] - 0s 994us/step - loss: 132.9754 - accuracy: 1.0000
    Epoch 5/10
    2/2 [==============================] - 0s 1ms/step - loss: 154.4105 - accuracy: 1.0000
    Epoch 6/10
    2/2 [==============================] - 0s 4ms/step - loss: 157.2047 - accuracy: 1.0000
    Epoch 7/10
    2/2 [==============================] - 0s 981us/step - loss: 184.0751 - accuracy: 1.0000
    Epoch 8/10
    2/2 [==============================] - 0s 902us/step - loss: 201.2888 - accuracy: 1.0000
    Epoch 9/10
    2/2 [==============================] - 0s 888us/step - loss: 219.6019 - accuracy: 1.0000
    Epoch 10/10
    2/2 [==============================] - 0s 5ms/step - loss: 238.6077 - accuracy: 1.0000

    ValueError: Input 0 of node model/MyConv/model/MyConv/strided_slice/_assign was passed float from 
    model/MyConv/ReadVariableOp/resource:0 incompatible with expected resource.
   
How to get rid of these warnings and the last error?

**Comment by sunw70** [comment]
Updates about this?

**Comment by tilakrayal** [comment]
@sunw70 ,
Can you please take a look at this [comment](https://forums.developer.nvidia.com/t/incompatible-with-expected-resource/72935/12) and [link](https://stackoverflow.com/questions/56580538/tf-keras-api-with-tf-dataset-problem-steps-per-epoch-argument-problem) for similar error.It helps.Thanks!

**Comment by sunw70** [comment]
@tilakrayal thanks for your reply: I tried to use `steps_per_epoch` in `model.fit`, but now I get this error:

    Model: "model"
    _________________________________________________________________
    Layer (type)                 Output Shape              Param #   
    =================================================================
    input_1 (InputLayer)         [(1, 7, 1)]               0         
    _________________________________________________________________
    flatten (Flatten)            (1, 7)                    0         
    _________________________________________________________________
    dense (Dense)                (1, 10)                   80        
    _________________________________________________________________
    dense_1 (Dense)              (1, 7)                    77        
    =================================================================
    Total params: 160
    Trainable params: 160
    Non-trainable params: 0
    _________________________________________________________________
    
    Traceback (most recent call last):
     File "model.py", line 409, in <module>
     model = build_model(x_train, y_train)
     File "model.py", line 384, in build_model
     model.fit(x_train, y_train, epochs=epochs, batch_size=batch_size, verbose=verbose, steps_per_epoch=10)
     File "/home/es/venv/lib/python3.8/site-packages/keras/engine/training_v1.py", line 777, in fit
     return func.fit(
     File "/home/es/venv/lib/python3.8/site-packages/keras/engine/training_arrays_v1.py", line 640, in fit
     return fit_loop(
     File "/home/es/venv/lib/python3.8/site-packages/keras/engine/training_arrays_v1.py", line 177, in model_iteration
     f = _make_execution_function(model, mode)
     File "/home/es/venv/lib/python3.8/site-packages/keras/engine/training_arrays_v1.py", line 547, in _make_execution_function
     return model._make_execution_function(mode)
     File "/home/es/venv/lib/python3.8/site-packages/keras/engine/training_v1.py", line 2079, in _make_execution_function
     self._make_train_function()
     File "/home/es/venv/lib/python3.8/site-packages/keras/engine/training_v1.py", line 2010, in _make_train_function
     updates = self.optimizer.get_updates(
     File "/home/es/venv/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py", line 759, in get_updates
     grads = self.get_gradients(loss, params)
     File "/home/es/venv/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py", line 751, in get_gradients
     raise ValueError("Variable {} has `None` for gradient. "
     ValueError: Variable <tf.Variable 'MyConv/kernel:0' shape=(3, 1, 1) dtype=float32> has `None` for gradient. Please make sure      
     that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.

I did some research: maybe the problem could be that the kernel weights have been defined, but some of them are not used. How could I make sure that all weights are used?

Thanks again for your support.

**Comment by AliSaeed86** [comment]
Anyone may help with this question asked by @sunw70, please.
I also stuck to this issue when i try to convert Conv2d layer (which is a tensor) to numpy to do some computations on the activation maps.

**Comment by tilakrayal** [comment]
@sunw70 ,
Are you trying in latest tensorflow version? If not, I request you please try to execute in latest stable version2.8.Thanks!
