### ISSUE TITLE
The documentation might not explain how to completely build Keras

### ISSUE THREAD

**Issue by ddrakard** [keras-team/keras#15241]
**URL(s) with the issue:**.

https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md

**Description of issue (what needs to be changed):**.

To the best of my knowledge, the information to build Keras is stored in `CONTRIBUTING.md`. This can be used to to create a working modified version of Keras. However some features which rely on protobuf appear not to work. Specifically `keras.models.load_model` fails with the exception trace given below. The `keras/protobuf` directory contains only `.proto` files, not `.py `files. Copying across equivalent built files from Tensorflow into the directory causes model loading to work correctly. It seems like the documentation might be missing a Bazel step to fully build the project.

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from keras.utils.vis_utils import plot_model
  File "/home/user/Downloads/keras-new/keras/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/home/user/Downloads/keras-new/keras/keras/models.py", line 20, in <module>
    from keras import metrics as metrics_module
  File "/home/user/Downloads/keras-new/keras/keras/metrics.py", line 26, in <module>
    from keras import activations
  File "/home/user/Downloads/keras-new/keras/keras/activations.py", line 20, in <module>
    from keras.layers import advanced_activations
  File "/home/user/Downloads/keras-new/keras/keras/layers/__init__.py", line 23, in <module>
    from keras.engine.input_layer import Input
  File "/home/user/Downloads/keras-new/keras/keras/engine/input_layer.py", line 21, in <module>
    from keras.engine import base_layer
  File "/home/user/Downloads/keras-new/keras/keras/engine/base_layer.py", line 45, in <module>
    from keras.saving.saved_model import layer_serialization
  File "/home/user/Downloads/keras-new/keras/keras/saving/saved_model/layer_serialization.py", line 20, in <module>
    from keras.saving.saved_model import save_impl
  File "/home/user/Downloads/keras-new/keras/keras/saving/saved_model/save_impl.py", line 31, in <module>
    from keras.saving.saved_model import load as keras_load
  File "/home/user/Downloads/keras-new/keras/keras/saving/saved_model/load.py", line 25, in <module>
    from keras.protobuf import saved_metadata_pb2
ImportError: cannot import name 'saved_metadata_pb2' from 'keras.protobuf' (unknown location)
```

**Comment by qlzh727** [comment]
What's the command to reproduce this error? 

Since the bazel build for the savemodel target contains the dependency to the proto generate target, the bazel build/test should generate the py from the proto file and make it work. Did I miss anything?

https://github.com/keras-team/keras/blob/8de906163ab14f404fa551c599b808ee856138cc/keras/saving/BUILD#L46

**Comment by ageron** [comment]
While using the docker image, after running the build instructions, I just ran `import keras` in a python shell, I got the same exception. After searching for a while, I found that the compiled protobuf files were located in /home/keras/bazel-bin/keras/protobuf` but not in `/home/keras/keras/protobuf`. So I just copied them there:

```bash
cp -f /home/keras/bazel-bin/keras/protobuf/*.py /home/keras/keras/protobuf/
```

If the compiled proto files don't exist yet for some reason, you can run the following commands to create them:

```bash
bazel build "//keras/protobuf:saved_metadata_proto_py_pb2"
bazel build "//keras/protobuf:projector_config_proto_py_pb2"
bazel build "//keras/protobuf:versions_proto_py_pb2"
```
