### ISSUE TITLE
[tf2.6] Loaded subclassed-Model fails to be retrained

### ISSUE THREAD

**Issue by OniReimu** [keras-team/keras#15261]
This has been posted in the [tensorflow repo](https://github.com/tensorflow/tensorflow/issues/51712).

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
-- Dockerfile: 
```
FROM python:3.8

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "./test.py" ]
```
-- requirements.txt:
```
numpy
tensorflow
```
and
`docker build -t python-docker .`

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Not tested
- TensorFlow installed from (source or binary): Docker on Mac mini (2018)
- TensorFlow version (use command below): TF2.6
- Python version: 3.8
- Bazel version (if compiling from source): Not tested, unlikely to be related to this issue
- GCC/Compiler version (if compiling from source): Not tested, unlikely to be related to this issue
- CUDA/cuDNN version: No CUDA on this Mac mini
- GPU model and memory: N/A

**Describe the current behavior**
Typing `docker run -it --rm -v "$PWD":/usr/src/app -w /usr/src/app python-docker python test.py` in my environment will end up getting the following error. More specifically, `predict(x, y)` works perfectly, however, `fit(x, y)` is the cause.

```
ValueError: No gradients provided for any variable: ['abs:0', 'non_distributional_model/dense_1/kernel:0', 'non_distributional_model/dense_1/bias:0', 'non_distributional_model/dense_2/kernel:0', 'non_distributional_model/dense_2/bias:0', 'non_distributional_model/output_layer/kernel:0', 'non_distributional_model/output_layer/bias:0'].
```

**Describe the expected behavior**
The loaded model should be retrainable.

**Standalone code to reproduce the issue**
```python
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Dense

BATCH_SIZE = 2
NUM_ACTION = 11
STATE_DIM = 1

"""Customer Loss functions."""
def _huber_loss(y_true, y_pred, max_grad=1.):
    a = tf.abs(y_true - y_pred)
    less_than_max = 0.5 * tf.square(a)
    greater_than_max = max_grad * (a - 0.5 * max_grad)
    return tf.where(a <= max_grad, x=less_than_max, y=greater_than_max)

@tf.keras.utils.register_keras_serializable()
class MeanHuberLoss(keras.losses.Loss):
    def __init__(self, name='mean_huber_loss', **kwargs):
        super(MeanHuberLoss, self).__init__(name=name, **kwargs)

    def call(self, y_true, y_pred):
        error = _huber_loss(y_true, y_pred)

        # The reduce_mean is automatically done as default
        return error

@tf.keras.utils.register_keras_serializable()
class DirectMappingForAbs(keras.metrics.Metric):
    def __init__(self, name='direct_map_for_abs', **kwargs):
        super(DirectMappingForAbs, self).__init__(name=name, **kwargs)
        self.output_value = tf.Variable(initial_value=[], name='abs', shape=(None, ), validate_shape=False, dtype=tf.float32)

    def update_state(self, values, sample_weight=None):
        self.output_value.assign(values)

    def result(self):
        return self.output_value

    def reset_state(self):
        self.output_value.assign([])

@tf.keras.utils.register_keras_serializable()
class NonDistributionalModel(keras.Model):
    def __init__(self, 
                 name="non_distributional_model",
                 num_output=None,
                 trainable=True):
        super(NonDistributionalModel, self).__init__(name=name)

        self.loss_tracker = keras.metrics.Mean(name="loss")
        self.abs_metric = DirectMappingForAbs(name="abs") # Returns a tensor with the same shape of the input tensors
        self.criterion = MeanHuberLoss()

        self.layer_1 = Dense(10, trainable=trainable, activation='relu', name="dense_1")  
        self.layer_2 = Dense(10, trainable=trainable, activation='relu', name="dense_2")
        self.output_layer = Dense(num_output, trainable=trainable, activation=None, name="output_layer")

    def call(self, inputs):
        inputs = tf.cast(inputs, tf.float32)
        layer_1 = self.layer_1(inputs)
        layer_2 = self.layer_2(layer_1)
        output = self.output_layer(layer_2)

        return output

    @tf.function
    def train_step(self, data):
        states, targets = data

        targets = tf.stop_gradient(targets)
        with tf.GradientTape() as tape:
            logits = self(states, training=True)  # Forward pass
            loss = self.criterion(targets, logits)

        trainable_vars = self.trainable_variables
        grads = tape.gradient(loss, trainable_vars)
        self.optimizer.apply_gradients(zip(grads, trainable_vars))

        self.loss_tracker.update_state(loss)
        self.abs_metric.update_state(tf.cast(tf.reduce_mean(tf.math.abs(targets - logits), axis=-1), tf.float32))
        
        return {"loss": self.loss_tracker.result(), "abs": self.abs_metric.result()}  

    @property
    def metrics(self):
        return [self.loss_tracker, self.abs_metric]   

class History(keras.callbacks.Callback):
    def on_train_begin(self, logs={}):
        self.losses = []
        self.abs = []

    def on_train_batch_end(self, batch, logs={}):
        self.losses.append(logs.get('loss'))
        self.abs.append(logs.get('abs'))

class _DQN_Model:
    def __init__(self, 
                 alpha, 
                 batch_size, 
                 num_output, 
                 trainable=True):
        self.alpha = alpha
        self.batch_size = batch_size
        self.num_output = num_output
        self.trainable = trainable

        self.model = self._build_model()

    def _build_model(self):
        lr_schedule = keras.optimizers.schedules.CosineDecayRestarts(initial_learning_rate=self.alpha,
                                                                       first_decay_steps=1000)

        model = NonDistributionalModel(num_output=self.num_output, trainable=self.trainable)
        model.compile(optimizer=Adam(lr_schedule))

        return model

    def predict(self, state):
        return self.model.predict(state)

    def train(self, states, targets):
        history = History()

        return self.model.fit(states, targets, batch_size=self.batch_size, epochs=1, verbose=0, callbacks=[history])

class Critic(object):
    def __init__(self, alpha, batch_size):
        self.alpha = alpha
        self.batch_size = batch_size

        self._eval_model = _DQN_Model(alpha=alpha, batch_size=batch_size, num_output=NUM_ACTION, trainable=True)

    def learn(self):
        x = np.random.random((self.batch_size, 1))
        y = np.random.random((self.batch_size, NUM_ACTION))
        history = self._eval_model.train(x, y)

        return tf.squeeze(history.history['loss'])


critic = Critic(alpha=0.1, batch_size=BATCH_SIZE)
critic.learn()

critic._eval_model.model.save("model_saved")
loaded_model = keras.models.load_model("model_saved")
print("Saved Model Weights: {}, Type: {}".format(len(critic._eval_model.model.get_weights()), type(critic._eval_model.model)))
print("Loaded Model Weights: {}, Type: {}".format(len(loaded_model.get_weights()), type(loaded_model)))

critic._eval_model.model.summary()
loaded_model.summary()

x=np.random.random((BATCH_SIZE, 1))
y=np.random.random((BATCH_SIZE, NUM_ACTION))

# Let's check:
np.testing.assert_allclose(
    critic._eval_model.predict(x), loaded_model.predict(x)
)

print("Continue to train the loaded model\n")
history = History()
result = loaded_model.fit(x, y, batch_size=BATCH_SIZE, epochs=1, verbose=0, callbacks=[history])

```

**Other info / logs** 
```
2021-08-27 12:28:38.619800: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-08-27 12:28:38.619860: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-08-27 12:28:40.667183: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-08-27 12:28:40.667238: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-08-27 12:28:40.667269: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (a3f95dfc3a77): /proc/driver/nvidia/version does not exist
2021-08-27 12:28:40.667437: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-08-27 12:28:40.722464: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
WARNING:tensorflow:Gradients do not exist for variables ['abs:0'] when minimizing the loss.
2021-08-27 12:28:41.133216: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Saved Model Weights: 9, Type: <class '__main__.NonDistributionalModel'>
Loaded Model Weights: 9, Type: <class 'keras.saving.saved_model.load.Custom>NonDistributionalModel'>
Model: "non_distributional_model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_1 (Dense)              multiple                  20
_________________________________________________________________
dense_2 (Dense)              multiple                  110
_________________________________________________________________
output_layer (Dense)         multiple                  121
=================================================================
Total params: 253
Trainable params: 251
Non-trainable params: 2
_________________________________________________________________
Model: "non_distributional_model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_1 (Dense)              multiple                  20
_________________________________________________________________
dense_2 (Dense)              multiple                  110
_________________________________________________________________
output_layer (Dense)         multiple                  121
=================================================================
Total params: 253
Trainable params: 251
Non-trainable params: 2
_________________________________________________________________
Continue to train the loaded model

Traceback (most recent call last):
  File "test2.py", line 182, in <module>
    result = loaded_model.fit(x, y, batch_size=BATCH_SIZE, epochs=1, verbose=0, callbacks=[history])
  File "/usr/local/lib/python3.8/site-packages/keras/engine/training.py", line 1184, in fit
    tmp_logs = self.train_function(iterator)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 759, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3066, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3463, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3298, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 1007, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 668, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 994, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /usr/local/lib/python3.8/site-packages/keras/engine/training.py:853 train_function  *
        return step_function(self, iterator)
    /usr/local/lib/python3.8/site-packages/keras/engine/training.py:842 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /usr/local/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:1286 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2849 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:3632 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/lib/python3.8/site-packages/keras/engine/training.py:835 run_step  **
        outputs = model.train_step(data)
    /usr/local/lib/python3.8/site-packages/keras/engine/training.py:791 train_step
        self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    /usr/local/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py:522 minimize
        return self.apply_gradients(grads_and_vars, name=name)
    /usr/local/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py:622 apply_gradients
        grads_and_vars = optimizer_utils.filter_empty_gradients(grads_and_vars)
    /usr/local/lib/python3.8/site-packages/keras/optimizer_v2/utils.py:72 filter_empty_gradients
        raise ValueError("No gradients provided for any variable: %s." %

    ValueError: No gradients provided for any variable: ['abs:0', 'non_distributional_model/dense_1/kernel:0', 'non_distributional_model/dense_1/bias:0', 'non_distributional_model/dense_2/kernel:0', 'non_distributional_model/dense_2/bias:0', 'non_distributional_model/output_layer/kernel:0', 'non_distributional_model/output_layer/bias:0'].
```

Thank you for your time.

**Comment by OniReimu** [comment]
Ok, I tried it out myself and here is what I found and hence the possible workaround.
**BOTH** `get_config` and `from_config` **MUST** be explicitly defined. 

If only `get_config` is defined will end up getting:
```
Traceback (most recent call last):
  File "test2.py", line 159, in <module>
    loaded_model = keras.models.load_model("model_saved")
  File "/usr/local/lib/python3.8/site-packages/keras/saving/save.py", line 205, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/usr/local/lib/python3.8/site-packages/keras/saving/saved_model/load.py", line 134, in load
    keras_loader.load_layers(compile=compile)
  File "/usr/local/lib/python3.8/site-packages/keras/saving/saved_model/load.py", line 394, in load_layers
    self.loaded_nodes[node_metadata.node_id] = self._load_layer(
  File "/usr/local/lib/python3.8/site-packages/keras/saving/saved_model/load.py", line 436, in _load_layer
    obj, setter = self._revive_from_config(identifier, metadata, node_id)
  File "/usr/local/lib/python3.8/site-packages/keras/saving/saved_model/load.py", line 454, in _revive_from_config
    self._revive_layer_or_model_from_config(metadata, node_id))
  File "/usr/local/lib/python3.8/site-packages/keras/saving/saved_model/load.py", line 518, in _revive_layer_or_model_from_config
    obj = layers_module.deserialize(
  File "/usr/local/lib/python3.8/site-packages/keras/layers/serialization.py", line 208, in deserialize
    return generic_utils.deserialize_keras_object(
  File "/usr/local/lib/python3.8/site-packages/keras/utils/generic_utils.py", line 674, in deserialize_keras_object
    deserialized_obj = cls.from_config(
  File "/usr/local/lib/python3.8/site-packages/keras/engine/training.py", line 2397, in from_config
    functional.reconstruct_from_config(config, custom_objects))
  File "/usr/local/lib/python3.8/site-packages/keras/engine/functional.py", line 1272, in reconstruct_from_config
    for layer_data in config['layers']:
KeyError: 'layers'
```

If only `from_config` is defined will end up getting the same error of:
```
    ValueError: No gradients provided for any variable: ['abs_output:0', 'non_distributional_model/dense_1/kernel:0', 'non_distributional_model/dense_1/bias:0', 'non_distributional_model/dense_2/kernel:0', 'non_distributional_model/dense_2/bias:0', 'non_distributional_model/output_layer/kernel:0', 'non_distributional_model/output_layer/bias:0'].
```

It works with both explicitly defined.

**Comment by kumariko** [comment]
@jvishnuvardhan Was able to reproduce the issue in TF v2.6 and  TF v2.5 . please find the gist [**`here`**](https://colab.research.google.com/gist/kumariko/477e8bc996a3e9e77dd33b0342138466/51241.ipynb#scrollTo=efebmgClichs).Thanks!

**Comment by gowthamkpr** [comment]
@OniReimu As mentioned above by @rhofour please define `from_config` function which will hadle your config explicitly. Please follow this guide [here](https://www.tensorflow.org/guide/keras/custom_layers_and_models). Thanks!

**Comment by OniReimu** [comment]
Thanks mates, will close the issue as it's been resolved by explicitly defining `from_config`.
