### ISSUE TITLE
json.decoder.JSONDecodeError when using keras.models.load_model

### ISSUE THREAD

**Issue by gitlabspy** [keras-team/keras#15653]
try reinstall tensorflow, don't work. But I tried with another machine, it works... I wonder what causes this issue.
- tensorflow 2.4.0
- python 3.6

It seems like `metadata = json_utils.decode(metadata)` is empty.

```Traceback (most recent call last):
  File "train.py", line 23, in <module>
    face_encoder = tf.keras.models.load_model("./checkpoints/face_encoder")
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 212, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 138, in load
    keras_loader.load_layers(compile=compile)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 376, in load_layers
    node_metadata.metadata)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 397, in _load_layer
    metadata = json_utils.decode(metadata)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/json_utils.py", line 69, in decode
    return json.loads(json_string, object_hook=_decode_helper)
  File "/usr/lib64/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by sanatmpa1** [comment]
@gitlabspy,

Can you share the complete standalone code or colab gist to reproduce the issue? Thanks!

**Comment by gitlabspy** [comment]
Just:
```
import tensorflow as tf
xx = tf.keras.models.load_model("xxx")
```
and failed.
It works on other machines and I tried create a new model and save it with my machine, and I can load this new model  with `tf.keras.models.load_model`...


```
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2021-11-16 13:21:36.990600: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
>>> face_encoder = tf.keras.models.load_model("./checkpoints/face_encoder")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 212, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 138, in load
    keras_loader.load_layers(compile=compile)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 376, in load_layers
    node_metadata.metadata)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 397, in _load_layer
    metadata = json_utils.decode(metadata)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/json_utils.py", line 69, in decode
    return json.loads(json_string, object_hook=_decode_helper)
  File "/usr/lib64/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>>> 
```

**Comment by sanatmpa1** [comment]
@gitlabspy,

As you said that it works fine in other system ,I doubt if its an issue from Keras end, Can you try updating TF to latest stable version and let us know if the issue persists? Thanks!
