### ISSUE TITLE
Pruning layer with ragged tensors

### ISSUE THREAD

**Issue by melecpetitpierre** [keras-team/keras#15738]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 21.04
- TensorFlow installed from (source or binary): pip install tensorflow
- TensorFlow version (use command below): v2.6.0-rc2-32-g919f693420e 2.6.0
- Python version: 3.9.7
- Bazel version (if compiling from source):
- GPU model and memory:
- Exact command to reproduce:

**Describe the problem**.
Pruning model with ragged tensors input is not working because of a failing conversion during tensor dot product. 

**Describe the current behavior**.
Get `TypeError: Failed to convert object of type <class 'tensorflow.python.ops.ragged.ragged_tensor.RaggedTensor'> to Tensor.` when a layer wrapped with pruning method is getting a ragged tensor.

**Describe the expected behavior**.
A pruned layer that accepts ragged tensor.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): yes
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing): Shouldn't the `convert_to_tensor` function in `ops.py` consider `RaggedTensors` like regular `Tensors` ?

**Standalone code to reproduce the issue**.
```
import tensorflow as tf
import tensorflow_model_optimization as tfmot

input = tf.keras.layers.Input(shape=(None, 10), ragged=True)
dense = tfmot.sparsity.keras.prune_low_magnitude(tf.keras.layers.Dense(units=5, activation="relu"))

x = dense(input)
```

**Source code / logs**.
```
Traceback (most recent call last):
  File "/home/melec/Documents/dev/force_estimation/pruning_test.py", line 7, in <module>
    x = dense(input)
  File "/home/melec/miniconda3/envs/force_estimation/lib/python3.9/site-packages/keras/engine/base_layer.py", line 976, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/home/melec/miniconda3/envs/force_estimation/lib/python3.9/site-packages/keras/engine/base_layer.py", line 1114, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "/home/melec/miniconda3/envs/force_estimation/lib/python3.9/site-packages/keras/engine/base_layer.py", line 848, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/home/melec/miniconda3/envs/force_estimation/lib/python3.9/site-packages/keras/engine/base_layer.py", line 888, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/melec/miniconda3/envs/force_estimation/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 695, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    /home/melec/miniconda3/envs/force_estimation/lib/python3.9/site-packages/tensorflow_model_optimization/python/core/sparsity/keras/pruning_wrapper.py:300 call  *
        return self.layer.call(inputs, **kwargs)
    /home/melec/miniconda3/envs/force_estimation/lib/python3.9/site-packages/keras/layers/core.py:1232 call  **
        outputs = tf.tensordot(inputs, self.kernel, [[rank - 1], [0]])
    /home/melec/miniconda3/envs/force_estimation/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py:206 wrapper
        return target(*args, **kwargs)
    /home/melec/miniconda3/envs/force_estimation/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:5036 tensordot
        a = ops.convert_to_tensor(a, name="a")
    /home/melec/miniconda3/envs/force_estimation/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py:163 wrapped
        return func(*args, **kwargs)
    /home/melec/miniconda3/envs/force_estimation/lib/python3.9/site-packages/tensorflow/python/framework/ops.py:1566 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    /home/melec/miniconda3/envs/force_estimation/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py:346 _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
    /home/melec/miniconda3/envs/force_estimation/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py:271 constant
        return _constant_impl(value, dtype, shape, name, verify_shape=False,
    /home/melec/miniconda3/envs/force_estimation/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py:288 _constant_impl
        tensor_util.make_tensor_proto(
    /home/melec/miniconda3/envs/force_estimation/lib/python3.9/site-packages/tensorflow/python/framework/tensor_util.py:551 make_tensor_proto
        raise TypeError("Failed to convert object of type %s to Tensor. "

    TypeError: Failed to convert object of type <class 'tensorflow.python.ops.ragged.ragged_tensor.RaggedTensor'> to Tensor. Contents: tf.RaggedTensor(values=Tensor("Placeholder:0", shape=(None, 10), dtype=float32), row_splits=Tensor("Placeholder_1:0", shape=(None,), dtype=int64)). Consider casting elements to a supported type.
```

**Comment by sanatmpa1** [comment]
@melecpetitpierre,

I can see that the code is working fine and it throws no errors in colab with `TF 2.7.0`. Please find the [gist here](https://colab.sandbox.google.com/gist/sanatmpa1/b652480fed995c5b3d0e9ef0b43b825d/15738.ipynb). Thanks!

**Comment by melecpetitpierre** [comment]
@sanatmpa1 thank you for your advice. Apparently pruning with ragged tensors is working fine with `TF 2.7.0`.
It solved also another problem linked to ragged tensors and sample weights.
