### ISSUE TITLE
NameError: name some_global is not defined when using a lambda layer

### ISSUE THREAD

**Issue by MarcelRobitaille** [keras-team/keras#15759]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.6.0-rc2-32-g919f693420e 2.6.0
- Python version: 3.9.9
- Bazel version (if compiling from source):
- GPU model and memory: Nvidia 1050 ti 4GB

**Describe the problem**.

This seems to be the same issue as  #4079. I am getting the same error message when my model uses a Lambda layer.

Since this layer is applying a user function, maybe this is indented behavior. I just wanted to add some more information to #4079.

**Describe the current behavior**.
I am getting:
```
NameError: name 'batch_size' is not defined
```

**Describe the expected behavior**.
The model should load without errors.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): no
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.

```python
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Bidirectional, GRU, Dense
from tensorflow.keras.models import load_model

filters = 128
kernel_size = 3
steps = 64
feature = 1
batch_size = 1000
points = 2
classes = 2

inputs = keras.layers.Input(
    [steps, feature],
    batch_size=batch_size,
    name='inputs',
)
x = Bidirectional(GRU(filters, return_sequences=True))(inputs)
x = Bidirectional(GRU(filters, return_sequences=False))(x)

out = Dense(
    points * classes * filters,
    activation='relu',
)(x)


def multi_output(x):
    x = tf.reshape(x, [batch_size, points, classes * filters])
    return x

out = keras.layers.Lambda(multi_output)(out)
outputs = keras.layers.Dense(1)(out)

model = keras.Model(inputs=inputs, outputs=outputs)
model.compile()
model.save('/tmp/model.h5')

del batch_size

load_model('/tmp/model.h5')
```

**Source code / logs**.

```
2021-12-06 21:14:57.902923: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-12-06 21:14:57.922014: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-12-06 21:14:57.922163: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-12-06 21:14:57.922435: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-12-06 21:14:57.922893: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-12-06 21:14:57.923022: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-12-06 21:14:57.923136: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-12-06 21:14:58.178672: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-12-06 21:14:58.178817: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-12-06 21:14:58.178926: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-12-06 21:14:58.179025: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 129 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1050 Ti, pci bus id: 0000:06:00.0, compute capability: 6.1
Traceback (most recent call last):
  File "/home/marcel/code/quin/CMOS_RTN/Lu/keras_minimal_example.py", line 41, in <module>
    load_model('/tmp/model.h5')
  File "/home/marcel/code/quin/CMOS_RTN/Lu/venv/lib/python3.9/site-packages/keras/saving/save.py", line 200, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects,
  File "/home/marcel/code/quin/CMOS_RTN/Lu/venv/lib/python3.9/site-packages/keras/saving/hdf5_format.py", line 180, in load_model_from_hdf5
    model = model_config_lib.model_from_config(model_config,
  File "/home/marcel/code/quin/CMOS_RTN/Lu/venv/lib/python3.9/site-packages/keras/saving/model_config.py", line 52, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/marcel/code/quin/CMOS_RTN/Lu/venv/lib/python3.9/site-packages/keras/layers/serialization.py", line 208, in deserialize
    return generic_utils.deserialize_keras_object(
  File "/home/marcel/code/quin/CMOS_RTN/Lu/venv/lib/python3.9/site-packages/keras/utils/generic_utils.py", line 674, in deserialize_keras_object
    deserialized_obj = cls.from_config(
  File "/home/marcel/code/quin/CMOS_RTN/Lu/venv/lib/python3.9/site-packages/keras/engine/functional.py", line 662, in from_config
    input_tensors, output_tensors, created_layers = reconstruct_from_config(
  File "/home/marcel/code/quin/CMOS_RTN/Lu/venv/lib/python3.9/site-packages/keras/engine/functional.py", line 1283, in reconstruct_from_config
    process_node(layer, node_data)
  File "/home/marcel/code/quin/CMOS_RTN/Lu/venv/lib/python3.9/site-packages/keras/engine/functional.py", line 1231, in process_node
    output_tensors = layer(input_tensors, **kwargs)
  File "/home/marcel/code/quin/CMOS_RTN/Lu/venv/lib/python3.9/site-packages/keras/engine/base_layer.py", line 976, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/home/marcel/code/quin/CMOS_RTN/Lu/venv/lib/python3.9/site-packages/keras/engine/base_layer.py", line 1114, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "/home/marcel/code/quin/CMOS_RTN/Lu/venv/lib/python3.9/site-packages/keras/engine/base_layer.py", line 848, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/home/marcel/code/quin/CMOS_RTN/Lu/venv/lib/python3.9/site-packages/keras/engine/base_layer.py", line 888, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/marcel/code/quin/CMOS_RTN/Lu/venv/lib/python3.9/site-packages/keras/layers/core.py", line 903, in call
    result = self.function(inputs, **kwargs)
  File "/home/marcel/code/quin/CMOS_RTN/Lu/keras_minimal_example.py", line 29, in multi_output
    x = tf.reshape(x, [batch_size, points, classes * filters])
NameError: name 'batch_size' is not defined
```

**Comment by chunduriv** [comment]
@MarcelRobitaille, Can you let us know whey are you deleting `batch_size`?

When I comment out line  `del batch_size`, I am able to run above code without any issues in TF2.7.0 and tf-nightly(2.8.0-dev20211208). Please find the [gist here](https://colab.research.google.com/gist/chunduriv/b399e8c2dbefa84939d587831c234c40/15759.ipynb) for reference.Thanks!

**Comment by MarcelRobitaille** [comment]
Hi @chunduriv.

> Can you let us know whey are you deleting batch_size?

The reason I opened this issue was that I was trying to refactor some code. Since `batch_size`, `points`, `classes`, `filters` are constants, I tried to rename them to their uppercase counterparts (basically `BATCH_SIZE=batch_size; del batch_size`, which is why I deleted it). But this is impossible so long as those variables are serialized in the model. I suspect something similar is happening in #4079.

In my mind `model.save` should serialize everything about the model. At the very least, I would expect that it depends on the function `multi_output`. It si very strange to me that it serialized that function but not the constant variables that it depends on.

**Comment by old-school-kid** [comment]
Hi @MarcelRobitaille 
You have to create a layer which inherits `keras.layers` and then declare `get_config` and `from_config` methods to save custom obects and architecture. I know it might be painful sometimes. A work around is writing up the architecture and just loading weights instead of whole architecture.
Hope this helps.

**Comment by MarcelRobitaille** [comment]
Ok thank you @old-school-kid. I think I will keep the setup code and recompile the model, and then load the weights from the save.
