### ISSUE TITLE
embedding_constraint does not work

### ISSUE THREAD

**Issue by davidsc-unity3d** [keras-team/keras#15818]
The `embedding_constraint` argument to the keras embedding layer does not work. Testing has been done on a macbook using tf 2.7 and tf-nightly from conda environments. With tf-nightly, the github version

```
tensorflow git version:  v1.12.1-69032-gfb972503145
```
the error ends with
```
    File "/Users/davidsc/miniconda3/envs/tfnightly/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 689, in apply_grad_to_update_var  **
        raise RuntimeError(

    RuntimeError: Cannot use a constraint function on a sparse variable. Received: grad=IndexedSlices(indices=Tensor("gradient_tape/model/embedding/embedding_lookup/Reshape_1:0", shape=(None,), dtype=int64), values=Tensor("gradient_tape/model/embedding/embedding_lookup/Reshape:0", shape=(None, 3), dtype=float32), dense_shape=Tensor("gradient_tape/model/embedding/embedding_lookup/Const:0", shape=(2,), dtype=int32)), var.constraint=<keras.constraints.MaxNorm object at 0x7fa0f10cc430>.
```

Likewise in tf 2.7, where the github version is 
```
tensorflow git version:  v2.7.0-rc1-69-gc256c071bb2
```
one gets 
```   File "/Users/davidsc/miniconda3/envs/tf2p7/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 694, in apply_grad_to_update_var  **
        raise RuntimeError(

    RuntimeError: Cannot use a constraint function on a sparse variable. Received: grad=IndexedSlices(indices=Tensor("gradient_tape/model/embedding/embedding_lookup/Reshape_1:0", shape=(None,), dtype=int64), values=Tensor("gradient_tape/model/embedding/embedding_lookup/Reshape:0", shape=(None, 3), dtype=float32), dense_shape=Tensor("gradient_tape/model/embedding/embedding_lookup/Const:0", shape=(2,), dtype=int32)), var.constraint=<keras.constraints.MaxNorm object at 0x7fb300cb8370>.
```

**System information**.
From the script `https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh` I have

```
== check os platform ===============================================
os: Darwin
os kernel version: Darwin Kernel Version 19.6.0: Tue Oct 12 18:34:05 PDT 2021; root:xnu-6153.141.43~1/RELEASE_X86_64
os release version: 19.6.0
os platform: Darwin-19.6.0-x86_64-i386-64bit
```

however it must not be using `which python` to find the python for the activated conda environments, similar information is
```
(tfnightly) davidsc@davidsc-409M code % pip list | grep "numpy\|proto\|tensorflow\|tf"
numpy                        1.21.5
protobuf                     3.19.1
tensorflow-io-gcs-filesystem 0.23.1
tf-estimator-nightly         2.8.0.dev2021122009
tf-nightly                   2.8.0.dev20211220
```
and
```
(tf2p7) davidsc@davidsc-409M code % pip list | grep "numpy\|proto\|tensorflow\|tf"
numpy                        1.21.5
protobuf                     3.19.1
tensorflow                   2.7.0
tensorflow-estimator         2.7.0
tensorflow-io-gcs-filesystem 0.23.1
```

**Describe the problem**.
Adding a embedding_constraint to the Keras embedding layer crashes - it is a bug. See https://github.com/tensorflow/tensorflow/issues/33755 for backgroun, and related stackoverflow https://stackoverflow.com/questions/63122880/tensorflow-2-runtimeerror-cannot-use-a-constraint-function-on-a-sparse-variabl

The feature is needed to provide greater control over the embedding matrix during training. 

**Describe the current behavior**.

crash

**Describe the expected behavior**.

works, constrains embedding matrix per parameters, rate, etc

- Do you want to contribute a PR? no

**Standalone code to reproduce the issue**.

```
import numpy as np
import tensorflow as tf


data = {
    'X': np.random.randint(0, 10, 10),
    'Y': np.random.randint(0, 2, 10)
}

def get_labels(features):
    labels = features.pop('Y')
    return features, labels

dset = tf.data.Dataset.from_tensor_slices(data).map(get_labels).batch(5)

inp = tf.keras.Input(shape=(1,), name='X', dtype='int64')

emb = tf.keras.layers.Embedding(
    10, 3, input_length=1,
    embeddings_initializer=tf.keras.initializers.RandomUniform(minval=-1.0, maxval=1.0),
    embeddings_constraint=tf.keras.constraints.MaxNorm(max_value=0.1)
)
emb_out = emb(inp)
out = tf.keras.layers.Dense(1)(emb_out)
model = tf.keras.Model(inputs=inp, outputs=out)
model.compile(optimizer='adam', loss=tf.keras.losses.binary_crossentropy)
model.fit(dset, epochs=10)
```

**Source code / logs**.

Here is an entire traceback
```
(tf2p7) davidsc@davidsc-409M code % python mz-ds-deep-learning/constrain_embedding.py 
tensorflow git version:  v2.7.0-rc1-69-gc256c071bb2
2021-12-20 11:14:44.803894: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Epoch 1/10
Traceback (most recent call last):
  File "/Users/davidsc/code/mz-ds-deep-learning/constrain_embedding.py", line 53, in <module>
    constrain_embeddings(use_keras=True)
  File "/Users/davidsc/code/mz-ds-deep-learning/constrain_embedding.py", line 48, in constrain_embeddings
    model.fit(dset, epochs=10, callbacks=callbacks)
  File "/Users/davidsc/miniconda3/envs/tf2p7/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/davidsc/miniconda3/envs/tf2p7/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py", line 1129, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
RuntimeError: in user code:

    File "/Users/davidsc/miniconda3/envs/tf2p7/lib/python3.9/site-packages/keras/engine/training.py", line 878, in train_function  *
        return step_function(self, iterator)
    File "/Users/davidsc/miniconda3/envs/tf2p7/lib/python3.9/site-packages/keras/engine/training.py", line 867, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/Users/davidsc/miniconda3/envs/tf2p7/lib/python3.9/site-packages/keras/engine/training.py", line 860, in run_step  **
        outputs = model.train_step(data)
    File "/Users/davidsc/miniconda3/envs/tf2p7/lib/python3.9/site-packages/keras/engine/training.py", line 816, in train_step
        self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/Users/davidsc/miniconda3/envs/tf2p7/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 532, in minimize
        return self.apply_gradients(grads_and_vars, name=name)
    File "/Users/davidsc/miniconda3/envs/tf2p7/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 672, in apply_gradients
        return self._distributed_apply(strategy, grads_and_vars, name,
    File "/Users/davidsc/miniconda3/envs/tf2p7/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 721, in _distributed_apply
        update_op = distribution.extended.update(
    File "/Users/davidsc/miniconda3/envs/tf2p7/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 694, in apply_grad_to_update_var  **
        raise RuntimeError(

    RuntimeError: Cannot use a constraint function on a sparse variable. Received: grad=IndexedSlices(indices=Tensor("gradient_tape/model/embedding/embedding_lookup/Reshape_1:0", shape=(None,), dtype=int64), values=Tensor("gradient_tape/model/embedding/embedding_lookup/Reshape:0", shape=(None, 3), dtype=float32), dense_shape=Tensor("gradient_tape/model/embedding/embedding_lookup/Const:0", shape=(2,), dtype=int32)), var.constraint=<keras.constraints.MaxNorm object at 0x7fb300cb8370>.
```

**Comment by davidsc-unity3d** [comment]
The application in mind is an embedding matrix with a skew distribution for entries, that is also being regularized. The regularization is applied to the whole matrix and can drive rare entries to zero, the constraint (assuming it is also applied to the whole matrix) provides control over this. One can try activity regularization, it may work for some use cases, but the constrain may work better for others.

**Comment by sushreebarsa** [comment]
@sachinprasadhs Was able to reproduce this issue in TF v2.7.0 and tf-nightly , please find the gist [here ](https://colab.sandbox.google.com/gist/sushreebarsa/39dcb248b3a8cbf30f8ca907b005b077/kerasgist15818.ipynb#scrollTo=U1RX0hMFeqxh)for reference.Thanks!

**Comment by chenmoneygithub** [comment]
this looks like a bug, I will take a closer look into it, thanks for reporting!

**Comment by chenmoneygithub** [comment]
It seems that this is an intended behavior: https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Optimizer#variable_constraints_2

Although it seems incorrect to not being able to have constraint on the embedding layer. Will need to try removing this check  and run some tests.
