### ISSUE TITLE
Error in tf.keras.models.load_model when using tf.constant

### ISSUE THREAD

**Issue by Chizkiyahu** [keras-team/keras#16006]
- OS Platform and Distribution: **Ubuntu 20.04.3 LTS**
- TensorFlow installed from **binary**
- TensorFlow version 
**v2.7.0-rc1-69-gc256c071bb2 2.7.0**
**tf-nightly 2.9.0.dev20220203 v1.12.1-70881-g7fdd40dab9a** 
- Python version: **3.8.11**
- GPU : **no GPU**
[**Colab code and errors** ](https://colab.research.google.com/drive/1YRsS_NQgD0CqUe5pcDelDMBA69Lnd3Bz?usp=sharing)

**Describe the problem**.
Before save the model.predict  is **ok**
After save error when using tf.keras.models.load_model when model have tf.constant

**Describe the current behavior**.
in file keras/engine/base_layer.py in line 1121 `inputs = tf.nest.map_structure(_convert_non_tensor, inputs)`
the loading of tf.constant  is return list of tensors with shape () 
![image](https://user-images.githubusercontent.com/37312901/152401209-20cdda96-b213-4748-a9fb-50e87a553285.png)
instens of shape (1,1,3)

**Describe the expected behavior**.
the line 1121 `inputs = tf.nest.map_structure(_convert_non_tensor, inputs)`
need to return the correct shape on tf. constant

**Standalone code to reproduce the issue**.

```
import numpy as np
import tensorflow as tf
x1 = tf.keras.layers.Input(shape=(1, 2, 3))
x2 = tf.constant(np.ones([1,1,3]))
x = tf.keras.layers.Add()([x1, x2])
model = tf.keras.Model(inputs=[x1], outputs=[x])
print(model.predict(np.random.rand(1, 1, 2, 3))) #work ok
model.save("model.h5")
model = tf.keras.models.load_model("model.h5") #error
```

**Source code / logs**

Traceback (most recent call last):
  File "/play.py", line 9, in <module>
    model = tf.keras.models.load_model("model.h5")
  File "/tf_ni/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/lib/python3.8/site-packages/keras/layers/merging/base_merge.py", line 91, in <setcomp>
    batch_sizes = {s[0] for s in input_shape if s} - {None}
TypeError: unhashable type: 'list'

when you change the code to `x = tf.keras.layers.Add()([x2, x1])`
Traceback (most recent call last):
  File "my_envlib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/my_env/lib/python3.8/site-packages/keras/layers/merging/base_merge.py", line 83, in build
    raise ValueError(
ValueError: A merge layer should be called on a list of inputs. Received: input_shape=[[[[()]]], (None, 1, 2, 3)] (not a list of shapes)

**Comment by jvishnuvardhan** [comment]
@Chizkiyahu Looks like this is an issue with saving in `h5` format. But, same works in `tf` format. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/b808acf86c204df487da8ecfdcf058dd/untitled.ipynb).

Also, note that the model was not compiled (model.compile). Loading a model without compiling will lead to some other issues. Thanks!

**Comment by Harshu467** [comment]
"unhashable type: 'list'"
	try:
            import tensorflow as tf
            loaded_model = tf.keras.models.load_model(
                '/home/harsh/Projects/customers/New folder (2)/New folder (10)/autism_new_/autism_new_KY/saved_model.pb')
            print("Loaded Model", loaded_model)
        except Exception as e:
            print("Error loading model", e)
        input_data = np.expand_dims(resized_frame, axis=0)
        prediction = loaded_model.predict(input_data)
        print("Prediction", prediction)
        
        W external/local_tsl/tsl/lib/monitoring/collection_registry.cc:81] Trying to register 2 metrics with the same name: /tensorflow/api/ops_eager_execution. The old value will be erased in order to register a new one. Please check if you link the metric more than once, or if the name is already used by other metrics.
2024-04-26 16:13:24.719147: W external/local_tsl/tsl/lib/monitoring/collection_registry.cc:81] Trying to register 2 metrics with the same name: /tensorflow/api/enable_control_flow_v2. The old value will be erased in order to register a new one. Please check if you link the metric more than once, or if the name is already used by other metrics.
2024-04-26 16:13:24.719156: W external/local_tsl/tsl/lib/monitoring/collection_registry.cc:81] Trying to register 2 metrics with the same name: /tensorflow/api/tf_function. The old value will be erased in order to register a new one. Please check if you link the metric more than once, or if the name is already used by other metrics.
Internal Server Error: /myapp/capture/
