### ISSUE TITLE
keras-io build failed on windows 10

### ISSUE THREAD

**Issue by Suzan009** [keras-team/keras#16053]
Posted [here](https://github.com/keras-team/keras-io/issues/797), no response. 

I tried to buikd keras-io on windows 10 machine. 

```
pip install -r requirements.txt
cd scripts
python autogen.py make
python autogen.py serve
```

But when I run `python autogen.py make`

```
Traceback (most recent call last):
  File "C:\Users\suz\anaconda3\lib\sre_parse.py", line 1039, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\m'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\suz\anaconda3\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\suz\Downloads\keras-io\scripts\autogen.py", line 659, in render_single_file
    md_content = re.sub(
  File "C:\Users\suz\anaconda3\lib\re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Users\suz\anaconda3\lib\re.py", line 327, in _subx
    template = _compile_repl(template, pattern)
  File "C:\Users\suz\anaconda3\lib\re.py", line 318, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "C:\Users\suz\anaconda3\lib\sre_parse.py", line 1042, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \m at position 11
"""

**Comment by Suzan009** [comment]
@sachinprasadhs In the keras-io read-me file, there is no mention of such things. Are you sure that a user needs to install tf from the source for that?
