### ISSUE TITLE
Random crash with error Graph execution error _resource_apply_dense       m_t_bar = (coefficients['one_minus_m_t'] * g_prime + Node: 'Nadam/Nadam/update_5/add_2' Incompatible shapes: [8] vs. [0]

### ISSUE THREAD

**Issue by partiallycomplex** [keras-team/keras#16160]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacBook Pro (14-inch, 2021) MacOs 12.2.1
- TensorFlow installed from (source or binary): binary tensorflow-macos
- TensorFlow version (use command below): 2.8.0
- Python version: 3.9.10
- Bazel version (if compiling from source):
- GPU model and memory: No used
- Exact command to reproduce: None

**Describe the problem**.

During hyperparameters search sometimes It randomly crashes with the following message after same hyperopt trial (usually 200-300)

**Describe the current behavior**.
Random may crash

**Describe the expected behavior**.
Run smoothly.
**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): No

**Source code / logs**.

job exception: Graph execution error
_resource_apply_dense
      m_t_bar = (coefficients['one_minus_m_t'] * g_prime +
Node: 'Nadam/Nadam/update_5/add_2'
Incompatible shapes: [8] vs. [0]

here the complete msg

Detected at node 'Nadam/Nadam/update_5/add_2' defined at (most recent call last):
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/bin/csm", line 5, in <module>
      main()
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
      return self.main(*args, **kwargs)
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
      rv = self.invoke(ctx)
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
      return __callback(*args, **kwargs)
    File "/Users/partiallycomplex/code/cr-autoencoder/src/cr_autoencoder/features/cli.py", line 110, in nace_transformer_hyperopt
      hyperparams_optimizer(descriptions, nace_transformer, dim, model_path, trials)
    File "/Users/partiallycomplex/code/cr-autoencoder/src/cr_autoencoder/models/textembedder.py", line 157, in hyperparams_optimizer
      best_hp, trials = hyperopt_fmin_wrapper(
    File "/Users/partiallycomplex/code/cr-autoencoder/src/cr_autoencoder/models/hyperparameter_optimization/utils.py", line 115, in hyperopt_fmin_wrapper
      result = hyperopt.fmin(
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/hyperopt/fmin.py", line 540, in fmin
      return trials.fmin(
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/hyperopt/base.py", line 671, in fmin
      return fmin(
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/hyperopt/fmin.py", line 586, in fmin
      rval.exhaust()
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/hyperopt/fmin.py", line 364, in exhaust
      self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/hyperopt/fmin.py", line 300, in run
      self.serial_evaluate()
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/hyperopt/fmin.py", line 178, in serial_evaluate
      result = self.domain.evaluate(spec, ctrl)
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/hyperopt/base.py", line 892, in evaluate
      rval = self.fn(pyll_rval)
    File "/Users/partiallycomplex/code/cr-autoencoder/src/cr_autoencoder/models/textembedder.py", line 139, in hyperopt_objective
      textembedder.fit(processed_data)
    File "/Users/partiallycomplex/code/cr-autoencoder/src/cr_autoencoder/models/textembedder.py", line 83, in fit
      self._history = self.autoencoder.fit(
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/keras/engine/training.py", line 1384, in fit
      tmp_logs = self.train_function(iterator)
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/keras/engine/training.py", line 1021, in train_function
      return step_function(self, iterator)
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/keras/engine/training.py", line 1010, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/keras/engine/training.py", line 1000, in run_step
      outputs = model.train_step(data)
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/keras/engine/training.py", line 863, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 532, in minimize
      return self.apply_gradients(grads_and_vars, name=name)
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 671, in apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 716, in _distributed_apply
      update_op = distribution.extended.update(
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 699, in apply_grad_to_update_var
      update_op = self._resource_apply_dense(grad, var, **apply_kwargs)
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/keras/optimizer_v2/nadam.py", line 158, in _resource_apply_dense
      m_t_bar = (coefficients['one_minus_m_t'] * g_prime +
Node: 'Nadam/Nadam/update_5/add_2'
Incompatible shapes: [8] vs. [0]
	 [[{{node Nadam/Nadam/update_5/add_2}}]] [Op:__inference_train_function_40987417]
 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████▍                       | 325/400 [30:02<1:30:07, 72.10s/trial, best loss: 0.01430231612175703]
Traceback (most recent call last):
  File "/Users/partiallycomplex/code/cr-autoencoder/.venv/bin/csm", line 5, in <module>
    main()
  File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/partiallycomplex/code/cr-autoencoder/src/cr_autoencoder/features/cli.py", line 110, in nace_transformer_hyperopt
    hyperparams_optimizer(descriptions, nace_transformer, dim, model_path, trials)
  File "/Users/partiallycomplex/code/cr-autoencoder/src/cr_autoencoder/models/textembedder.py", line 157, in hyperparams_optimizer
    best_hp, trials = hyperopt_fmin_wrapper(
  File "/Users/partiallycomplex/code/cr-autoencoder/src/cr_autoencoder/models/hyperparameter_optimization/utils.py", line 115, in hyperopt_fmin_wrapper
    result = hyperopt.fmin(
  File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/hyperopt/fmin.py", line 540, in fmin
    return trials.fmin(
  File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/hyperopt/base.py", line 671, in fmin
    return fmin(
  File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/hyperopt/fmin.py", line 586, in fmin
    rval.exhaust()
  File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/hyperopt/fmin.py", line 364, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/hyperopt/fmin.py", line 300, in run
    self.serial_evaluate()
  File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/hyperopt/fmin.py", line 178, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/hyperopt/base.py", line 892, in evaluate
    rval = self.fn(pyll_rval)
  File "/Users/partiallycomplex/code/cr-autoencoder/src/cr_autoencoder/models/textembedder.py", line 139, in hyperopt_objective
    textembedder.fit(processed_data)
  File "/Users/partiallycomplex/code/cr-autoencoder/src/cr_autoencoder/models/textembedder.py", line 83, in fit
    self._history = self.autoencoder.fit(
  File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'Nadam/Nadam/update_5/add_2' defined at (most recent call last):
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/bin/csm", line 5, in <module>
      main()
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
      return self.main(*args, **kwargs)
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
      rv = self.invoke(ctx)
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
      return __callback(*args, **kwargs)
    File "/Users/partiallycomplex/code/cr-autoencoder/src/cr_autoencoder/features/cli.py", line 110, in nace_transformer_hyperopt
      hyperparams_optimizer(descriptions, nace_transformer, dim, model_path, trials)
    File "/Users/partiallycomplex/code/cr-autoencoder/src/cr_autoencoder/models/textembedder.py", line 157, in hyperparams_optimizer
      best_hp, trials = hyperopt_fmin_wrapper(
    File "/Users/partiallycomplex/code/cr-autoencoder/src/cr_autoencoder/models/hyperparameter_optimization/utils.py", line 115, in hyperopt_fmin_wrapper
      result = hyperopt.fmin(
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/hyperopt/fmin.py", line 540, in fmin
      return trials.fmin(
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/hyperopt/base.py", line 671, in fmin
      return fmin(
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/hyperopt/fmin.py", line 586, in fmin
      rval.exhaust()
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/hyperopt/fmin.py", line 364, in exhaust
      self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/hyperopt/fmin.py", line 300, in run
      self.serial_evaluate()
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/hyperopt/fmin.py", line 178, in serial_evaluate
      result = self.domain.evaluate(spec, ctrl)
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/hyperopt/base.py", line 892, in evaluate
      rval = self.fn(pyll_rval)
    File "/Users/partiallycomplex/code/cr-autoencoder/src/cr_autoencoder/models/textembedder.py", line 139, in hyperopt_objective
      textembedder.fit(processed_data)
    File "/Users/partiallycomplex/code/cr-autoencoder/src/cr_autoencoder/models/textembedder.py", line 83, in fit
      self._history = self.autoencoder.fit(
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/keras/engine/training.py", line 1384, in fit
      tmp_logs = self.train_function(iterator)
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/keras/engine/training.py", line 1021, in train_function
      return step_function(self, iterator)
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/keras/engine/training.py", line 1010, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/keras/engine/training.py", line 1000, in run_step
      outputs = model.train_step(data)
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/keras/engine/training.py", line 863, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 532, in minimize
      return self.apply_gradients(grads_and_vars, name=name)
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 671, in apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 716, in _distributed_apply
      update_op = distribution.extended.update(
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 699, in apply_grad_to_update_var
      update_op = self._resource_apply_dense(grad, var, **apply_kwargs)
    File "/Users/partiallycomplex/code/cr-autoencoder/.venv/lib/python3.9/site-packages/keras/optimizer_v2/nadam.py", line 158, in _resource_apply_dense
      m_t_bar = (coefficients['one_minus_m_t'] * g_prime +
Node: 'Nadam/Nadam/update_5/add_2'
Incompatible shapes: [8] vs. [0]
	 [[{{node Nadam/Nadam/update_5/add_2}}]] [Op:__inference_train_function_40987417]

Thanks
g

**Comment by sushreebarsa** [comment]
@partiallycomplex 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by partiallycomplex** [comment]
Is not easy to cut the example, but  I try to extract part of it in the attached zip
It is a simple sequential model [encoder, decoder]  that is trained calling fit method in order to reduce the tf universal sentence encoder embedding of some text to a 5 dim vec. 
The problem arise sometime during the hyperopt params search as defined in the code
[snippet.py.zip](https://github.com/keras-team/keras/files/8179379/snippet.py.zip)

**Comment by sushreebarsa** [comment]
@partiallycomplex  Was able to replicate the issue on colab using TF v2.8.0 , could you please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/3c9a6d9722f9330807a3966d07008d97/kerasgist16160.ipynb) and confirm the same? Thanks!

**Comment by partiallycomplex** [comment]
Hello @sushreebarsa I updatated the code in order to make it work. Now it is fine. I did not see the same issue. I noticed just some error due to my extract from the main code without adapt the code. Now it runs, so you could run and see if the error. I had, during the last days every time an error (always on optimizers and different shape in some op) during the 1000 trials. Remeber OS Mac Catilina on M1, using tensorflow-macos
You can run the code I dont know if on linux+tensorflow "plain" works properly

**Comment by sushreebarsa** [comment]
@partiallycomplex Thank you for the update!
Please move this issue to closed status if it is resolved for you?Thanks!

**Comment by partiallycomplex** [comment]
The notebook is still running. Lets see if it outputs the error. What if it is just an error on tensorflow-macos? 
Moeover do you have any insight from the log I published in the first post?

**Comment by partiallycomplex** [comment]
The problem is not resolved. I cant see the output because the notebook timed-out. I cant monitor that. Please decide if you want to spot the bug or close the ticket, but I cant work on this. Thx!

**Comment by sachinprasadhs** [comment]
Could you please link the colab gist with the updated code, above linked gist is not producing the error which you have reported.

**Comment by partiallycomplex** [comment]
@sachinprasadhs here the gist. I upload same test file as well 
https://colab.research.google.com/gist/partiallycomplex/c393170f849f9389fae949a253aace99/kerasgist16160.ipynb

**Comment by partiallycomplex** [comment]
> Could you please link the colab gist with the updated code, above linked gist is not producing the error which you have reported.

I saved the gist last week but it expired

**Comment by sachinprasadhs** [comment]
Could you please save and attach the gist again. Thanks!

**Comment by partiallycomplex** [comment]
Hi @sachinprasadhs attached notebook with input file and cell output with the error
[notebook_data.zip](https://github.com/keras-team/keras/files/8261261/notebook_data.zip)
[notebook_data.zip](https://github.com/keras-team/keras/files/8261262/notebook_data.zip)

**Comment by partiallycomplex** [comment]
It seems that disable eager execution do not produce the crashes. @sachinprasadhs 
tf.compat.v1.disable_v2_behavior()

**Comment by sachinprasadhs** [comment]
If your issue is resolved by disabling eager execution, could you please move this issue to closed. Thanks!

**Comment by partiallycomplex** [comment]
> If your issue is resolved by disabling eager execution, could you please move this issue to closed. Thanks!

Why the issue should be closed? It is not the intended behavior. Anyway, any thought about that?

**Comment by loki4514** [comment]
i am finding the same error

**Comment by partiallycomplex** [comment]
> i am finding the same error

It also happens with some layers node as well: it shows always some kind of Incompatible shapes: [x] vs. [0]

**Comment by loki4514** [comment]
How to solve this error

**Comment by partiallycomplex** [comment]
Problem still random happens. Always incompatible shapes not just for optimiser but also layers ie Btchnorm.
Happens more frequently during hyper parameters optimisation. Smaller frequency disabling eager.
No support up to now from Kerr’s either apple. 
(bug only on M1 cpu)

**Comment by LukeWood** [comment]
> Problem still random happens. Always incompatible shapes not just for optimiser but also layers ie Btchnorm. Happens more frequently during hyper parameters optimisation. Smaller frequency disabling eager. No support up to now from Kerr’s either apple. (bug only on M1 cpu)

Is there a way to report the bug to the TensorFlow M1 distribution - I believe that Apple is actually currently maintaining this build and package.  If it is only on M1, it is likely a bug on that side:

//medical/endoscopy/experimental/surgical/tf_datasets/out_of_body:maple_based_dataset

**Comment by tilakrayal** [comment]
@partiallycomplex,
We don't officially support the tensorflow-macos releases. As it is failing only on tensorflow-macos, we request to raise the concern on the macos-apple [forum](https://developer.apple.com/forums/) for the quick resolution.  Also this  happens more frequently during hyper parameters optimization. Thank you!
