### ISSUE TITLE
keras-io build failed on windows 10

### ISSUE THREAD

**Issue by Suzan009** [keras-team/keras#16229]
Posted [here](https://github.com/keras-team/keras-io/issues/797), no response. 

I tried to buikd keras-io on windows 10 machine. 

```
pip install -r requirements.txt
cd scripts
python autogen.py make
python autogen.py serve
```

But when I run `python autogen.py make`

```
Traceback (most recent call last):
  File "C:\Users\suz\anaconda3\lib\sre_parse.py", line 1039, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\m'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\suz\anaconda3\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\suz\Downloads\keras-io\scripts\autogen.py", line 659, in render_single_file
    md_content = re.sub(
  File "C:\Users\suz\anaconda3\lib\re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Users\suz\anaconda3\lib\re.py", line 327, in _subx
    template = _compile_repl(template, pattern)
  File "C:\Users\suz\anaconda3\lib\re.py", line 318, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "C:\Users\suz\anaconda3\lib\sre_parse.py", line 1042, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \m at position 11
"""

Do I need to install TensorFlow from source to fix this issue ??

**Comment by Suzan009** [comment]
@tilakrayal I don't need to build keras itself but the keras-io, here is the repo. https://github.com/keras-team/keras-io

**Comment by tilakrayal** [comment]
@Suzan009 ,
Can you please take a look at this [link](https://github.com/keras-team/keras).Thanks!

**Comment by Suzan009** [comment]
@tilakrayal don't you understand the plain English text that I've written [here](https://github.com/keras-team/keras/issues/16229#issuecomment-1067132868)? Please assign someone else if you can't.

**Comment by gadagashwini** [comment]
@Suzan009,
To get the Keras-io, Install tensorflow `pip install tensorflow`.
[Keras-io](https://keras.io/) repository hosts the code used to generate the [keras.io](https://keras.io/) website. 
Keras-io internally calls keras.

```
!pip install tensorflow 
from tensorflow import keras
```

**Comment by Suzan009** [comment]
@gadagashwini I have already installed tensorflow. Sorry, why did you think that it might be a tensorflow issue like this? 

Here is the thing that I did 

```python
git clone https://github.com/keras-team/keras-io.git
activate tensorflow2.7 
pip install -r requirements.txt
cd scripts
python autogen.py make
```

Please follow the above commands. As I said when I run `python autogen.py make`, after some while the error occurs, mentioned [here](https://github.com/keras-team/keras/issues/16229#issue-1167202266).

**Comment by gadagashwini** [comment]
@Suzan009, 
Steps mentioned [here](https://github.com/keras-team/keras-io#generating-a-local-copy-of-the-website) are for generating Keras-io document. 

I tried the steps
```
#create python virtual environment 
python -m venv kerasio
#activate env 
source kerasio/bin/activate
#clone Keras-io repo
git clone https://github.com/keras-team/keras-io.git
#Move to Keras-io directory
cd keras-io
#Install requirements.txt
pip install requirements.txt
# Mov to script doc
cd scripts
#run the autogenerated py 
python autogen.py make
#Launch the Keras-io doc
python autogen.py serve
Serving on 0.0.0.0:8000   ## can see the Keras-io webpage at 8000 port

```
If you are looking for keras installation, 
you can use `pip install keras` or `pip install tensorflow`

> Traceback (most recent call last):
>   File "C:\Users\suz\anaconda3\lib\sre_parse.py", line 1039, in parse_template
>     this = chr(ESCAPES[this][1])
> KeyError: '\\m'

The above error looks more related to Anaconda. Try it on different virtual environment without Anaconda package.

**Comment by Suzan009** [comment]
I am on windows 10. Do you think it's related to OS? I also create a new and fresh environment, but when I ran the following command, I just faced the above-mentioned error. It looks like the windows path

```
python autogen.py make

....
re.error: bad escape \m at position 11
```

I will try again with your approach.

**Comment by gadagashwini** [comment]
@Suzan009,
It might be depends on OS platform. 
From the error its look like, Its failing to fetch required the path. 
Did you try steps mentioned in above comment. Thanks!

**Comment by Suzan009** [comment]
@gadagashwini unfortunately no. I am still facing that issue. I am using windows 10.  Python version 3.9 (also test on 3.7, 3.8). 

When I run the following script, it just gives the `re` package error, like below. 

```
python autogen.py make

....
re.error: bad escape \m at position 11
```

Searching the error took me these type of SO questions: https://stackoverflow.com/questions/58328587/python-3-7-4-re-error-bad-escape-s-at-position-0

**Comment by gadagashwini** [comment]
@Suzan009, I couldn’t reproduce the issue on MAC OS and Linux machine. 
May i know, why are you trying to launch Keras-io website from locally. Thanks!

**Comment by mitul01** [comment]
@Suzan009 I haven't tried personally setting up Keras-io in windows but I would suggest you to try using windows subsystem Linux (WSL) to setup Keras-io if you think it a windows OS issue. They have also provided the docker image and if you have docker installed in your system you can always use that which will help remove all the installation and setup headaches.

**Comment by Suzan009** [comment]
@mitul01 Even if I did use docker, I also need to run `python autogen.py` which would cause the same error. 

Using WSL is a good suggestion, but I really don't need it for any other stuff. So, I'm not willing to do that unless it's necessary to do so.

**Comment by Suzan009** [comment]
> @Suzan009, I couldn’t reproduce the issue on MAC OS and Linux machine. May i know, why are you trying to launch Keras-io website from locally. Thanks!

Just wanted to do a f*ng contribution in the code example. I would try another round to setup it up from fresh windows. If it goes well, fine. Otherwise, I'll close this issue.

**Comment by gadagashwini** [comment]
@Suzan009,
Did you get a chance to build fresh Keras-io on Windows.Thanks!

**Comment by Suzan009** [comment]
give up contributing to keras-io.

**Comment by satpalsr** [comment]
@mitul01 @gadagashwini Is it also not supposed to work on [Colab?](https://colab.research.google.com/drive/16O5x3jPZLzTy_yz9V-3OtNFs3E-GkMOX?usp=sharing)
