### ISSUE TITLE
Denormalization layer

### ISSUE THREAD

**Issue by markub3327** [keras-team/keras#16284]
Hello,

  you have implemented `tf.keras.layers.Normalization`, but if I want inverse transformation we don't have a `tf.keras.layers.Denormalization`.

Can I create PR?

Thanks.
Have a nice day.

**Comment by markub3327** [comment]
I can create PR on that. :)

**Comment by gadagashwini** [comment]
@markub3327, Welcome you to create PR

**Comment by markub3327** [comment]
@gadagashwini

I cannot run Keras unit tests, I get:
OS: Debian GNU/Linux 11 (bullseye)
Arch: x86_64

```shell
martin@server-01:~/Desktop/Projects/keras$ bazel test keras/optimizers/optimizer_experimental:optimizer_test
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [v2]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=111
INFO: Reading rc options for 'test' from /home/martin/Desktop/Projects/keras/.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --define open_source_build=true --define=use_fast_cpp_protos=false --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --config=short_logs --config=v2
INFO: Reading rc options for 'test' from /home/martin/Desktop/Projects/keras/.bazelrc:
  'test' options: --define open_source_build=true --define=use_fast_cpp_protos=false --config=v2
INFO: Found applicable config definition build:short_logs in file /home/martin/Desktop/Projects/keras/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/martin/Desktop/Projects/keras/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:v2 in file /home/martin/Desktop/Projects/keras/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Repository zlib instantiated at:
  /home/martin/Desktop/Projects/keras/WORKSPACE:39:14: in <toplevel>
  /home/martin/.cache/bazel/_bazel_martin/b46d382d358df92d258999df19e91943/external/com_google_protobuf/protobuf_deps.bzl:9:21: in protobuf_deps
Repository rule http_archive defined at:
  /home/martin/.cache/bazel/_bazel_martin/b46d382d358df92d258999df19e91943/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://zlib.net/zlib-1.2.11.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'zlib':
   Traceback (most recent call last):
	File "/home/martin/.cache/bazel/_bazel_martin/b46d382d358df92d258999df19e91943/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /home/martin/.cache/bazel/_bazel_martin/b46d382d358df92d258999df19e91943/external/zlib/temp14338963762586419969/zlib-1.2.11.tar.gz: GET returned 404 Not Found
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/home/martin/.cache/bazel/_bazel_martin/b46d382d358df92d258999df19e91943/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /home/martin/.cache/bazel/_bazel_martin/b46d382d358df92d258999df19e91943/external/zlib/temp14338963762586419969/zlib-1.2.11.tar.gz: GET returned 404 Not Found
INFO: Repository remote_coverage_tools instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:11:13: in <toplevel>
Repository rule http_archive defined at:
  /home/martin/.cache/bazel/_bazel_martin/b46d382d358df92d258999df19e91943/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: /home/martin/.cache/bazel/_bazel_martin/b46d382d358df92d258999df19e91943/external/com_google_protobuf/BUILD:154:11: @com_google_protobuf//:protobuf depends on @zlib//:zlib in repository @zlib which failed to fetch. no such package '@zlib//': java.io.IOException: Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /home/martin/.cache/bazel/_bazel_martin/b46d382d358df92d258999df19e91943/external/zlib/temp14338963762586419969/zlib-1.2.11.tar.gz: GET returned 404 Not Found
ERROR: Analysis of target '//keras/optimizers/optimizer_experimental:optimizer_test' failed; build aborted: Analysis failed
INFO: Elapsed time: 15.409s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (64 packages loaded, 687 targets configured)
FAILED: Build did NOT complete successfully (64 packages loaded, 687 targets configured)
martin@server-01:~/Desktop/Projects/keras$
```

**Comment by markub3327** [comment]
Ok.
