### ISSUE TITLE
bazel can't build keras 2.9 on MacBook Air M1 

### ISSUE THREAD

**Issue by snowuyl** [keras-team/keras#16548]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 12.3.1 (M1 ARM64 CPU)
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.9
- Python version:  3.9.12
- Bazel version (if compiling from source): 5.0.0
- GPU model and memory: no GPU used, memory: 16GB
- Exact command to reproduce: bazel build -c opt //keras/tools/pip_package:build_pip_package

**Describe the problem**.
git clone https://github.com/keras-team/keras keras-2.9.0_pip_package
cd keras-2.9.0_pip_package
git checkout r2.9
bazel build -c opt //keras/tools/pip_package:build_pip_package
Target //keras/tools/pip_package:build_pip_package failed to build

**Describe the current behavior**.
bazel can't build keras 2.9 on MacBook Air M1

**Describe the expected behavior**.
bazel can build keras 2.9 on MacBook Air M1

**Standalone code to reproduce the issue**.
bazel build -c opt //keras/tools/pip_package:build_pip_package

**Source code / logs**.
INFO: Found 1 target...
ERROR: /Users/andyueng/samba/workspace_TensorFlow2/keras-2.9.0_pip_package/keras/api/BUILD:160:19: Executing genrule //keras/api:keras_python_api_gen failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument skipped)
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_andyueng/4b992bed8f1471a8dd4099a36cff54c6/execroot/org_keras/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/keras/api/create_keras_api_1_keras_python_api_gen.runfiles/org_keras/keras/api/create_python_api_wrapper.py", line 26, in <module>
    import keras  # pylint: disable=unused-import
  File "/private/var/tmp/_bazel_andyueng/4b992bed8f1471a8dd4099a36cff54c6/execroot/org_keras/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/keras/api/create_keras_api_1_keras_python_api_gen.runfiles/org_keras/keras/__init__.py", line 21, in <module>
    from tensorflow.python import tf2
ImportError: cannot import name 'tf2' from 'tensorflow.python' (unknown location)
ERROR: /Users/andyueng/samba/workspace_TensorFlow2/keras-2.9.0_pip_package/keras/api/BUILD:187:19: Executing genrule //keras/api:keras_python_api_gen_compat_v2 failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument skipped)
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_andyueng/4b992bed8f1471a8dd4099a36cff54c6/execroot/org_keras/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/keras/api/create_keras_api_2_keras_python_api_gen_compat_v2.runfiles/org_keras/keras/api/create_python_api_wrapper.py", line 26, in <module>
    import keras  # pylint: disable=unused-import
  File "/private/var/tmp/_bazel_andyueng/4b992bed8f1471a8dd4099a36cff54c6/execroot/org_keras/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/keras/api/create_keras_api_2_keras_python_api_gen_compat_v2.runfiles/org_keras/keras/__init__.py", line 21, in <module>
    from tensorflow.python import tf2
ImportError: cannot import name 'tf2' from 'tensorflow.python' (unknown location)
ERROR: /Users/andyueng/samba/workspace_TensorFlow2/keras-2.9.0_pip_package/keras/api/BUILD:173:19: Executing genrule //keras/api:keras_python_api_gen_compat_v1 failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument skipped)
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_andyueng/4b992bed8f1471a8dd4099a36cff54c6/execroot/org_keras/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/keras/api/create_keras_api_1_keras_python_api_gen_compat_v1.runfiles/org_keras/keras/api/create_python_api_wrapper.py", line 26, in <module>
    import keras  # pylint: disable=unused-import
  File "/private/var/tmp/_bazel_andyueng/4b992bed8f1471a8dd4099a36cff54c6/execroot/org_keras/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/keras/api/create_keras_api_1_keras_python_api_gen_compat_v1.runfiles/org_keras/keras/__init__.py", line 21, in <module>
    from tensorflow.python import tf2
ImportError: cannot import name 'tf2' from 'tensorflow.python' (unknown location)
Target //keras/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /Users/andyueng/samba/workspace_TensorFlow2/keras-2.9.0_pip_package/keras/tools/pip_package/BUILD:39:10 Middleman _middlemen/keras_Stools_Spip_Upackage_Sbuild_Upip_Upackage-runfiles failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument skipped)
INFO: Elapsed time: 49.365s, Critical Path: 6.90s
INFO: 239 processes: 24 internal, 215 local.
FAILED: Build did NOT complete successfully
andyueng@jinkangdeMacBook-Air keras-2.9.0_pip_package % python3 
Python 3.9.12 (main, May  8 2022, 17:57:49) 
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from tensorflow.python import tf2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'tf2' from 'tensorflow.python' (unknown location)

**Comment by tilakrayal** [comment]
@snowuyl ,
Hello @snowuyl ,
For Apple M1 chip, you can install it through miniforge installers by following the guide [here](https://developer.apple.com/metal/tensorflow-plugin/).
Since, few of the mentioned packages in the above link are community build, could you wait for sometime to get the 2.9 dependencies.

**Comment by snowuyl** [comment]
% pip3 install tensorflow-macos==2.9.0
Successfully installed tensorflow-macos-2.9.0
% python3
Python 3.9.12 (main, May 8 2022, 17:57:49)
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

import tensorflow as tf
print(tf.version)
2.9.0
from tensorflow.keras import layers
