### ISSUE TITLE
tf.keras.initializers.TruncatedNormal is not available when using tf.keras.models.load_model 

### ISSUE THREAD

**Issue by ptarasiewiczNV** [keras-team/keras#16581]
### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

tensorflow/tensorflow Docker image

### Current Behaviour?

```shell
When using `tf.keras.initializers.TruncatedNormal` in a custom model, the model can be saved, but fails to load.
Adding `custom_objects={"TruncatedNormal": tf.keras.initializers.TruncatedNormal})` to `tf.keras.models.load_model` prevents the error.
I expected that passing TF classes as custom objects would not be necessary.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

@tf.keras.utils.register_keras_serializable()
class MyModel(tf.keras.Model):
    def __init__(self, initializer):
        self._config = {"initializer": initializer}
        super().__init__(inputs=[], outputs=[])
        
    def get_config(self):
        return self._config
    
    @classmethod
    def from_config(cls, config, custom_objects=None):
        return cls(**config)
    
mymodel = MyModel(initializer=tf.keras.initializers.TruncatedNormal())
tf.keras.models.save_model(mymodel, "mymodel.sm", overwrite=True)
loaded_mymodel = tf.keras.models.load_model("mymodel.sm")
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "tfbug.py", line 18, in <module>
    loaded_mymodel = tf.keras.models.load_model("mymodel.sm")
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None    
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/training/tracking/base.py", line 587, in _method_wrapper 
    result = method(self, *args, **kwargs)    
TypeError: __init__() missing 2 required positional arguments: 'inputs' and 'outputs'
```

**Comment by ptarasiewiczNV** [comment]
```python
import tensorflow as tf

@tf.keras.utils.register_keras_serializable()
class MyModel(tf.keras.Model):
    def __init__(self, initializer):
        self.initializer = initializer
        super().__init__(inputs=[], outputs=[])
        
    def get_config(self):
        return {"initializer": self.initializer}

mymodel = MyModel(initializer=tf.keras.initializers.TruncatedNormal())
tf.keras.models.save_model(mymodel, "mymodel.sm", overwrite=True)
loaded_mymodel = tf.keras.models.load_model("mymodel.sm")
```
Raises the same error. Without `@tf.keras.utils.register_keras_serializable()` it does not recognize custom model and without `tf.keras.models.load_model("mymodel.sm")` it does not load the model anyway.

**Comment by bhack** [comment]
I don't see a subsclassed model there and the initializer is used in a custom layer there. So how do you have derived your "minimal" subclassed  model gist? Also mine is minimal and derived just adapting the example in the official documentation.

**Comment by ptarasiewiczNV** [comment]
[This is](https://github.com/NVIDIA/DeepLearningExamples/blob/8c8f7ca4c340fd66efb0d096e893107b538fac3f/TensorFlow2/LanguageModeling/BERT/official/nlp/modeling/networks/bert_span_labeler.py#L28) a subclassed model. From there I have derived this example to reproduce this error. But I am not really sure how relevant this is.
Your code works fine, but it is a different code. Am I misusing TF and Keras in my initial example?

**Comment by bhack** [comment]
I suppose this is very similar to your initial post or not:
https://colab.research.google.com/gist/bhack/f15b04a8181774c72254a8f72485fc4f/untitled129.ipynb

**Comment by ptarasiewiczNV** [comment]
It is missing the `tf.keras.models.load_model("mymodel.sm")` line which is causing the error,

**Comment by bhack** [comment]
Yes it was just to understand your use case, but what I meant why you need to use `super().__init__(inputs=[], outputs=[])`?
As it is seems to me unrelated from the  ISSUE title "tf.keras.initializers.TruncatedNormal is not available ".

See also some model subclassing official examples:
https://www.tensorflow.org/guide/keras/custom_layers_and_models#the_model_class

**Comment by ptarasiewiczNV** [comment]
As I understand it there are two ways to define a subclassed keras model:

1:
```python
import tensorflow as tf

@tf.keras.utils.register_keras_serializable()
class MyModel(tf.keras.Model):
    def __init__(self, initializer):
        self.initializer = initializer

        inputs = tf.keras.layers.Input(shape=(5,))
        dense = tf.keras.layers.Dense(10, activation="relu", name="dense", kernel_initializer=self.initializer)
        outputs = dense(inputs)
        
        super().__init__(inputs=[inputs], outputs=[outputs])
        
    def get_config(self):
        return {"initializer": self.initializer}

mymodel = MyModel(initializer=tf.keras.initializers.TruncatedNormal())
mymodel(tf.random.normal((1, 5)))
tf.keras.models.save_model(mymodel, "mymodel.sm", overwrite=True)
tf.keras.models.load_model("mymodel.sm")
```

2:
```python
import tensorflow as tf

@tf.keras.utils.register_keras_serializable()
class MyModel(tf.keras.Model):
    def __init__(self, initializer):
        super().__init__()
        self.initializer = initializer
        self.dense = tf.keras.layers.Dense(10, activation="relu", name="dense", kernel_initializer=self.initializer)
        
    def call(self, inputs):
        return self.dense(inputs)

    def get_config(self):
        return {"initializer": self.initializer}

mymodel = MyModel(initializer=tf.keras.initializers.TruncatedNormal())
mymodel(tf.random.normal((1, 5)))
tf.keras.models.save_model(mymodel, "mymodel.sm", overwrite=True)
tf.keras.models.load_model("mymodel.sm")
```

Method nr 2 does not raise errors, but method nr 1 does (but only during the loading of a saved model). Is nr 1 a wrong way to define a Keras model? If not then why is the code failing on loading the model?

**Comment by bhack** [comment]
I think 1 run cause init accept kwargs.

But I don't find a subclassed model definition like your (1) also in tests:

https://github.com/keras-team/keras/blob/master/keras/tests/model_subclassing_test.py

**Comment by tilakrayal** [comment]
@gadagashwini ,
I was able to reproduce the issue in tensorflow v2.8, v2.9 and nightly. Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/8bf08dcb481c121f028ca01432bbb1ba/16581.ipynb).

**Comment by gadagashwini** [comment]
Hi @ptarasiewiczNV, 
Does[ Making new Layers and Models via subclassing](https://www.tensorflow.org/guide/keras/custom_layers_and_models) tutorial helps.Thank you!

**Comment by ptarasiewiczNV** [comment]
Hi @gadagashwini , I understand that there are better ways to create models. Just want to make sure that the way keras is used in my example is an incorrect way of using keras and this is not a bug. Can you confirm that?

**Comment by chenmoneygithub** [comment]
@k-w-w Kathy, mind taking a look at this issue? Thanks!
