### ISSUE TITLE
Error while training model

### ISSUE THREAD

**Issue by faysalhossain2007** [keras-team/keras#16678]
Tensorflow Version
2.6.2

Custom Code
No

OS Platform and Distribution
Linux Ubuntu 18.04

Mobile device
No response

Python version
3.8.11

Bazel version
No response

GCC/Compiler version
No response

CUDA/cuDNN version
No response

GPU model and memory
No response

Current Behaviour?
Sometimes my model works fine it goes up to 10 epochs without any problems. Sometimes it ends up by crashing the program. Even the crash occurred after a few epochs and sometimes in the middle of an epoch. My Model architecture looks like this-

Layer (type)                 Output Shape              Param #   
=================================================================
masking_2 (Masking)          (None, 200, 16)           0         
_________________________________________________________________
bidirectional_4 (Bidirection (None, 200, 512)          419328    
_________________________________________________________________
dropout_4 (Dropout)          (None, 200, 512)          0         
_________________________________________________________________
bidirectional_5 (Bidirection (None, 512)               1181184   
_________________________________________________________________
dropout_5 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 513       
=================================================================
Total params: 1,601,025
Trainable params: 1,601,025
Non-trainable params: 0
_________________________________________________________________

Here I am attaching one example where the program stops in the middle of an epoch:

1493/3750 [==========>...................] - ETA: 32:06 - loss: 2.2078 - true_positives_2: 550.0000 - false_positives_2: 2011.0000 - true_negatives_2: 7292.0000 - false_negatives_2: 2091.0000 - precision_2: 0.2148 - recall_2: 0.2083
1494/3750 [==========>...................] - ETA: 32:05 - loss: 2.2072 - true_positives_2: 550.0000 - false_positives_2: 2011.0000 - true_negatives_2: 7298.0000 - false_negatives_2: 2093.0000 - precision_2: 0.2148 - recall_2: 0.2081
1495/3750 [==========>...................] - ETA: 32:04 - loss: 2.2071 - true_positives_2: 550.0000 - false_positives_2: 2015.0000 - true_negatives_2: 7300.0000 - false_negatives_2: 2095.0000 - precision_2: 0.2144 - recall_2: 0.2079

Standalone code to reproduce the issue
https://colab.research.google.com/drive/1pSNyKx7jWimin-pFYVx4uiw_L5k4bDB8?usp=sharing 

```
### Relevant log output

```shell
Traceback (most recent call last):
  File "bgru_graph_grid_search.py", line 579, in <module>
    perform_grid_search()
  File "bgru_graph_grid_search.py", line 502, in perform_grid_search
    main(raw_dataset, labels, traindataSetPath, testdataSetPath, realtestdataSetPath, weightPath, resultPath,
  File "bgru_graph_grid_search.py", line 180, in main
    model.fit(train_generator, validation_steps=1, steps_per_epoch=steps_epoch, epochs=epoch, verbose=1, callbacks=[checkpoint])
  File "/home/faysal-gpu/anaconda3/envs/py37_maml/lib/python3.8/site-packages/keras/engine/training.py", line 1184, in fit
    tmp_logs = self.train_function(iterator)
  File "/home/faysal-gpu/anaconda3/envs/py37_maml/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/home/faysal-gpu/anaconda3/envs/py37_maml/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 917, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/home/faysal-gpu/anaconda3/envs/py37_maml/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3039, in __call__
    return graph_function._call_flat(
  File "/home/faysal-gpu/anaconda3/envs/py37_maml/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1963, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/faysal-gpu/anaconda3/envs/py37_maml/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 591, in call
    outputs = execute.execute(
  File "/home/faysal-gpu/anaconda3/envs/py37_maml/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  assertion failed: [predictions must be >= 0] [Condition x >= y did not hold element-wise:] [x (sequential_2/dense_2/Sigmoid:0) = ] [[nan][nan][nan]...] [y (Cast_3/x:0) = ] [0]
	 [[{{node assert_greater_equal/Assert/AssertGuard/else/_2663/assert_greater_equal/Assert/AssertGuard/Assert}}]]
	 [[assert_greater_equal_4/Assert/AssertGuard/pivot_f/_2745/_651]]
  (1) Invalid argument:  assertion failed: [predictions must be >= 0] [Condition x >= y did not hold element-wise:] [x (sequential_2/dense_2/Sigmoid:0) = ] [[nan][nan][nan]...] [y (Cast_3/x:0) = ] [0]
	 [[{{node assert_greater_equal/Assert/AssertGuard/else/_2663/assert_greater_equal/Assert/AssertGuard/Assert}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_16916]

Function call stack:
train_function -> train_function

2022-05-22 09:13:12.319808: W tensorflow/core/kernels/data/generator_dataset_op.cc:107] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
```

**Comment by qherm** [comment]
Can you provide an example from the training dataset?
e.g.: `print(list(train_dataset.take(1).as_numpy_iterator()))`

The model's predictions in error (0) and (1) are all showing NaN, which leads me to believe the input/output structure is incorrect for your training data. 

Also maybe post predictions from the model before fitting.

**Comment by sushreebarsa** [comment]
@faysalhossain2007 Could you refer to the [comment](https://github.com/keras-team/keras/issues/16678#issuecomment-1154268392) above and let us know if it helps?
Thank you!

**Comment by faysalhossain2007** [comment]
hi @sushreebarsa thanks for the tagging.
@qherm I provided the vectorization of my raw data to the model. Following is one such example-
```
[array([-2.4410748 , -7.036084  , -0.260834  , -1.8878677 , -5.6547184 ,
        1.239403  ,  2.432861  , -0.43844026,  1.356626  , -4.2364054 ,
        2.759785  , -6.3265915 , -0.6860079 , -4.310501  ,  0.76528406,
        2.4458761 ], dtype=float32), array([-8.23095  , -2.440325 , -3.4324706, -1.6135583,  3.1836433,
        3.2710671,  0.6691097,  7.075232 ,  1.2643552,  3.632681 ,
        2.7826624,  2.9414935, -2.729936 , -3.972074 ,  3.2305746,
        5.1327233], dtype=float32), array([ 0.22976479,  1.5932227 , -3.095042  , -3.3508677 , -0.9362112 ,
       -1.9563627 ,  1.0111499 , -0.11635169, -0.8390506 ,  0.8199928 ,
        0.12255799,  1.0578141 , -0.5978777 ,  4.1067834 , -3.9543886 ,
        0.7755627 ], dtype=float32), array([-6.1814737 , -1.1714957 ,  4.1898866 , -7.389282  ,  8.435141  ,
        2.962274  , -1.6662652 ,  4.1867833 ,  6.542118  ,  2.5723171 ,
       11.189238  ,  6.723832  , -0.75193447,  1.4799235 ,  1.739575  ,
        5.814503  ], dtype=float32), array([-2.2749949 , -4.715433  , -1.0171803 , -2.4407728 ,  2.7499979 ,
       -5.886449  , -1.0793504 , -3.9736736 ,  3.4497643 ,  0.01202778,
       -5.7547336 , -0.9896278 , -4.0494285 , -0.2831246 , -0.78259265,
        2.129125  ], dtype=float32), array([-6.5368927e-01, -3.3061509e+00, -1.5199324e+00, -8.2662363e+00,
        1.4671850e+00, -6.3459778e+00,  1.3871527e-01, -9.8475438e-01,
        2.7998927e+00, -2.0372493e+00, -1.2238214e+00, -1.1217413e+00,
       -2.7047187e-01,  2.1716359e+00,  3.9549014e-03,  1.9660964e+00],
      dtype=float32), array([-1.4342139 , -2.1596258 , -5.18211   , -1.990359  , -0.94903594,
        1.2130194 , -4.467531  ,  3.638181  ,  0.4146112 , -0.9076433 ,
        0.20927827,  1.091635  , -2.3539073 , -4.540105  , -4.7805142 ,
        1.9658401 ], dtype=float32), array([-0.8041734 ,  4.5399394 , -3.5566058 , -0.0773789 , -2.459625  ,
       -1.8820504 ,  0.2566677 ,  0.21865852, -3.1512177 ,  5.0737267 ,
       -1.6792638 , -0.24389264, -4.112286  ,  5.1340847 , -0.63389385,
       -0.07317136], dtype=float32), array([-2.4410748 , -7.036084  , -0.260834  , -1.8878677 , -5.6547184 ,
        1.239403  ,  2.432861  , -0.43844026,  1.356626  , -4.2364054 ,
        2.759785  , -6.3265915 , -0.6860079 , -4.310501  ,  0.76528406,
        2.4458761 ], dtype=float32), array([ 1.331649  , -0.20050651, -1.4400768 , -4.41005   , -0.99427843,
        0.41401705,  2.6619158 , -0.8515057 ,  2.4531188 , -0.15596889,
        1.3525937 ,  2.4866986 , -2.172435  , -1.669254  , -2.47086   ,
       -0.01155706], dtype=float32), array([-0.8041734 ,  4.5399394 , -3.5566058 , -0.0773789 , -2.459625  ,
       -1.8820504 ,  0.2566677 ,  0.21865852, -3.1512177 ,  5.0737267 ,
       -1.6792638 , -0.24389264, -4.112286  ,  5.1340847 , -0.63389385,
       -0.07317136], dtype=float32), array([-2.5036206,  0.3474965,  5.4719057, -6.0635796,  3.5009973,
       -5.803139 ,  3.5019424, -1.3159096,  5.6024942, -2.271839 ,
       -2.966759 ,  3.0256588, -3.8092031,  3.5159369,  0.5384896,
       -7.1363697], dtype=float32), array([-2.2749949 , -4.715433  , -1.0171803 , -2.4407728 ,  2.7499979 ,
       -5.886449  , -1.0793504 , -3.9736736 ,  3.4497643 ,  0.01202778,
       -5.7547336 , -0.9896278 , -4.0494285 , -0.2831246 , -0.78259265,
        2.129125  ], dtype=float32), array([-6.5368927e-01, -3.3061509e+00, -1.5199324e+00, -8.2662363e+00,
        1.4671850e+00, -6.3459778e+00,  1.3871527e-01, -9.8475438e-01,
        2.7998927e+00, -2.0372493e+00, -1.2238214e+00, -1.1217413e+00,
       -2.7047187e-01,  2.1716359e+00,  3.9549014e-03,  1.9660964e+00],
      dtype=float32), array([-0.7576191 , -4.1867213 , -2.2607234 , -0.6633982 ,  0.07318647,
       -0.5883166 , -0.12760168,  2.6613986 ,  0.21186355,  2.822268  ,
       -2.0115097 , -0.1853537 ,  1.4536544 , -2.738704  , -3.6947472 ,
        3.5244794 ], dtype=float32), array([ 0.0382089 ,  1.503925  , -2.294088  , -2.1815724 , -0.09158628,
       -1.6838557 ,  0.34845984,  0.44897333, -1.0271981 ,  1.3983697 ,
        0.40154693,  0.9622241 , -0.67672026,  3.9588773 , -3.4430373 ,
        1.0274647 ], dtype=float32), array([-2.4410748 , -7.036084  , -0.260834  , -1.8878677 , -5.6547184 ,
        1.239403  ,  2.432861  , -0.43844026,  1.356626  , -4.2364054 ,
        2.759785  , -6.3265915 , -0.6860079 , -4.310501  ,  0.76528406,
        2.4458761 ], dtype=float32), array([-0.43406725, -3.2547731 , -1.9502971 , -0.61113125, -0.03113229,
        0.04936428, -1.0148516 ,  2.922048  ,  0.51309043,  2.1059632 ,
       -1.1534024 , -0.3823554 ,  0.5290213 , -2.4603775 , -4.316388  ,
        2.7034712 ], dtype=float32), array([ 0.8673375 ,  0.31981596,  1.2055221 , -1.9897474 , -1.2329    ,
       -2.3448653 , -0.14327769, -0.14208671,  0.5255722 ,  0.4865796 ,
       -1.6236091 , -6.274632  , -1.6383896 ,  4.4438977 , -3.2867827 ,
       -0.14418675], dtype=float32), array([ 1.9232097 , -1.6170269 ,  0.4346286 , -1.7196033 , -3.5626693 ,
        0.1663949 , -3.3820963 , -0.63922834, -0.9495672 ,  2.9939148 ,
       -0.01807328,  0.7198213 ,  1.9370574 , -0.105718  , -2.8818903 ,
        0.17488542], dtype=float32), array([-0.9108493 ,  0.7892975 ,  2.665287  , -3.9641724 ,  0.2278021 ,
       -2.2233953 ,  0.06662396,  3.7210617 ,  1.5043509 ,  0.35968727,
        3.2404988 , -4.3443666 ,  0.9102807 ,  4.5979114 , -0.9937742 ,
        0.34853578], dtype=float32), array([ 2.369463  ,  3.8487184 , -0.5836681 ,  5.078963  , -3.009515  ,
       -1.3198047 ,  0.20393959,  2.500191  ,  1.6742587 ,  0.28429592,
        3.4293876 ,  1.1280032 ,  2.5528157 , -1.3490905 ,  6.4477415 ,
        0.1844484 ], dtype=float32), array([ 0.22976479,  1.5932227 , -3.095042  , -3.3508677 , -0.9362112 ,
       -1.9563627 ,  1.0111499 , -0.11635169, -0.8390506 ,  0.8199928 ,
        0.12255799,  1.0578141 , -0.5978777 ,  4.1067834 , -3.9543886 ,
        0.7755627 ], dtype=float32), array([-0.43406725, -3.2547731 , -1.9502971 , -0.61113125, -0.03113229,
        0.04936428, -1.0148516 ,  2.922048  ,  0.51309043,  2.1059632 ,
       -1.1534024 , -0.3823554 ,  0.5290213 , -2.4603775 , -4.316388  ,
        2.7034712 ], dtype=float32), array([-0.11706211, -2.240122  ,  2.6970487 , -2.8758512 , -4.0648274 ,
       -1.6238247 , -0.4351786 , -0.0519313 ,  3.596493  , -1.8543813 ,
        8.337867  , -5.0350995 ,  0.53382695,  5.9116755 , -5.7908363 ,
        2.3897238 ], dtype=float32), array([ 1.331649  , -0.20050651, -1.4400768 , -4.41005   , -0.99427843,
        0.41401705,  2.6619158 , -0.8515057 ,  2.4531188 , -0.15596889,
        1.3525937 ,  2.4866986 , -2.172435  , -1.669254  , -2.47086   ,
       -0.01155706], dtype=float32), array([ 3.0391965, -2.7323194, -3.6203413,  1.6010699, -8.549645 ,
        3.7195613, -6.1231847, -6.414715 ,  3.9941533, -1.468565 ,
        3.981151 , -2.5570242, -2.4177582, -3.3436074, -7.252008 ,
        4.5144114], dtype=float32), array([ -5.398432 , -11.90219  ,   2.8440225,  -5.178383 ,  12.574787 ,
        12.667113 , -15.287657 ,  12.131085 ,  10.249301 , -14.214728 ,
         6.0012045,  10.427062 ,  -7.70918  ,  -3.7735841,  -9.832107 ,
        -2.157581 ], dtype=float32), array([ 0.22976479,  1.5932227 , -3.095042  , -3.3508677 , -0.9362112 ,
       -1.9563627 ,  1.0111499 , -0.11635169, -0.8390506 ,  0.8199928 ,
        0.12255799,  1.0578141 , -0.5978777 ,  4.1067834 , -3.9543886 ,
        0.7755627 ], dtype=float32), array([-0.7576191 , -4.1867213 , -2.2607234 , -0.6633982 ,  0.07318647,
       -0.5883166 , -0.12760168,  2.6613986 ,  0.21186355,  2.822268  ,
       -2.0115097 , -0.1853537 ,  1.4536544 , -2.738704  , -3.6947472 ,
        3.5244794 ], dtype=float32), array([ 1.4165138 , -2.4190922 ,  2.9752576 , -2.0401785 , -3.359743  ,
       -2.7271028 , -4.1425147 ,  1.510121  , -0.96149015,  2.039356  ,
        0.7341554 , -4.187533  , -3.1279187 ,  4.6410155 , -7.2763796 ,
       -2.474819  ], dtype=float32), array([ 5.2550645, -5.358551 , -3.6287344, -3.4365196, -4.9681535,
        1.8872664, -1.4541926,  3.3215873, -1.3585929,  1.4102308,
       -0.6849086,  2.938055 , -3.75784  , -4.256866 , -7.6781807,
       -1.9874793], dtype=float32), array([-6.5368927e-01, -3.3061509e+00, -1.5199324e+00, -8.2662363e+00,
        1.4671850e+00, -6.3459778e+00,  1.3871527e-01, -9.8475438e-01,
        2.7998927e+00, -2.0372493e+00, -1.2238214e+00, -1.1217413e+00,
       -2.7047187e-01,  2.1716359e+00,  3.9549014e-03,  1.9660964e+00],
      dtype=float32), array([-0.43406725, -3.2547731 , -1.9502971 , -0.61113125, -0.03113229,
        0.04936428, -1.0148516 ,  2.922048  ,  0.51309043,  2.1059632 ,
       -1.1534024 , -0.3823554 ,  0.5290213 , -2.4603775 , -4.316388  ,
        2.7034712 ], dtype=float32), array([ 1.5286385 , -2.8429685 ,  3.3001099 , -0.57341415, -2.928202  ,
       -2.2331438 , -4.6439466 ,  1.1675051 , -1.0958089 ,  2.1561792 ,
        0.01507305, -4.07805   , -2.8770216 ,  3.0522425 , -6.7119813 ,
       -2.2745335 ], dtype=float32), array([ 0.0382089 ,  1.503925  , -2.294088  , -2.1815724 , -0.09158628,
       -1.6838557 ,  0.34845984,  0.44897333, -1.0271981 ,  1.3983697 ,
        0.40154693,  0.9622241 , -0.67672026,  3.9588773 , -3.4430373 ,
        1.0274647 ], dtype=float32), array([ 3.0391965, -2.7323194, -3.6203413,  1.6010699, -8.549645 ,
        3.7195613, -6.1231847, -6.414715 ,  3.9941533, -1.468565 ,
        3.981151 , -2.5570242, -2.4177582, -3.3436074, -7.252008 ,
        4.5144114], dtype=float32), array([ -5.398432 , -11.90219  ,   2.8440225,  -5.178383 ,  12.574787 ,
        12.667113 , -15.287657 ,  12.131085 ,  10.249301 , -14.214728 ,
         6.0012045,  10.427062 ,  -7.70918  ,  -3.7735841,  -9.832107 ,
        -2.157581 ], dtype=float32), array([ 0.22976479,  1.5932227 , -3.095042  , -3.3508677 , -0.9362112 ,
       -1.9563627 ,  1.0111499 , -0.11635169, -0.8390506 ,  0.8199928 ,
        0.12255799,  1.0578141 , -0.5978777 ,  4.1067834 , -3.9543886 ,
        0.7755627 ], dtype=float32), array([-0.7576191 , -4.1867213 , -2.2607234 , -0.6633982 ,  0.07318647,
       -0.5883166 , -0.12760168,  2.6613986 ,  0.21186355,  2.822268  ,
       -2.0115097 , -0.1853537 ,  1.4536544 , -2.738704  , -3.6947472 ,
        3.5244794 ], dtype=float32), array([ 1.4165138 , -2.4190922 ,  2.9752576 , -2.0401785 , -3.359743  ,
       -2.7271028 , -4.1425147 ,  1.510121  , -0.96149015,  2.039356  ,
        0.7341554 , -4.187533  , -3.1279187 ,  4.6410155 , -7.2763796 ,
       -2.474819  ], dtype=float32), array([ 5.2550645, -5.358551 , -3.6287344, -3.4365196, -4.9681535,
        1.8872664, -1.4541926,  3.3215873, -1.3585929,  1.4102308,
       -0.6849086,  2.938055 , -3.75784  , -4.256866 , -7.6781807,
       -1.9874793], dtype=float32), array([-6.5368927e-01, -3.3061509e+00, -1.5199324e+00, -8.2662363e+00,
        1.4671850e+00, -6.3459778e+00,  1.3871527e-01, -9.8475438e-01,
        2.7998927e+00, -2.0372493e+00, -1.2238214e+00, -1.1217413e+00,
       -2.7047187e-01,  2.1716359e+00,  3.9549014e-03,  1.9660964e+00],
      dtype=float32), array([-0.43406725, -3.2547731 , -1.9502971 , -0.61113125, -0.03113229,
        0.04936428, -1.0148516 ,  2.922048  ,  0.51309043,  2.1059632 ,
       -1.1534024 , -0.3823554 ,  0.5290213 , -2.4603775 , -4.316388  ,
        2.7034712 ], dtype=float32), array([-6.519976  , -4.908485  , -2.6603374 ,  0.14225224,  0.2656139 ,
       -4.5947237 , -3.1174624 , -0.9953963 , -3.0996277 , -0.9623849 ,
       -1.6563534 , -4.6108537 , -2.4957483 ,  3.6608365 , -5.020325  ,
        3.949374  ], dtype=float32), array([ 3.4069986 , -7.518667  ,  0.24704649, -1.9555767 , -2.7034035 ,
       -2.9849803 , -3.5518463 ,  0.5905668 , -2.0580575 ,  3.072783  ,
        0.5273199 ,  1.925994  ,  2.5761878 ,  0.8704351 , -7.340696  ,
        1.6276822 ], dtype=float32), array([ 1.5286385 , -2.8429685 ,  3.3001099 , -0.57341415, -2.928202  ,
       -2.2331438 , -4.6439466 ,  1.1675051 , -1.0958089 ,  2.1561792 ,
        0.01507305, -4.07805   , -2.8770216 ,  3.0522425 , -6.7119813 ,
       -2.2745335 ], dtype=float32), array([ 0.0382089 ,  1.503925  , -2.294088  , -2.1815724 , -0.09158628,
       -1.6838557 ,  0.34845984,  0.44897333, -1.0271981 ,  1.3983697 ,
        0.40154693,  0.9622241 , -0.67672026,  3.9588773 , -3.4430373 ,
        1.0274647 ], dtype=float32), array([ 0.0382089 ,  1.503925  , -2.294088  , -2.1815724 , -0.09158628,
       -1.6838557 ,  0.34845984,  0.44897333, -1.0271981 ,  1.3983697 ,
        0.40154693,  0.9622241 , -0.67672026,  3.9588773 , -3.4430373 ,
        1.0274647 ], dtype=float32), array([-3.8188258e-01, -3.3843307e+00,  1.9843504e-03, -2.0152144e+00,
        2.5018382e-01, -2.8664851e+00, -1.2161021e+00, -4.8345728e+00,
        2.5228910e+00,  3.6482400e-01, -2.9102852e+00, -3.4452574e+00,
       -1.4517084e+00,  7.2080439e-01, -3.3993393e-01,  3.5686345e+00],
      dtype=float32), array([-0.6572458 , -4.8549213 , -2.4102004 ,  0.06566047, -0.08031303,
       -0.16232479, -2.2213352 ,  2.2161353 , -0.33188576,  2.9706035 ,
       -2.4847577 ,  0.7765032 ,  0.47840843, -2.8201206 , -5.967195  ,
        2.9729013 ], dtype=float32), array([-0.9108493 ,  0.7892975 ,  2.665287  , -3.9641724 ,  0.2278021 ,
       -2.2233953 ,  0.06662396,  3.7210617 ,  1.5043509 ,  0.35968727,
        3.2404988 , -4.3443666 ,  0.9102807 ,  4.5979114 , -0.9937742 ,
        0.34853578], dtype=float32), array([-3.8944998 , -4.831711  , -4.817342  , -7.244232  ,  3.5361657 ,
        8.349915  , -5.5325875 ,  8.254896  , -0.13509688, -0.35191062,
        2.9378493 ,  5.434887  , -7.9925385 , -7.0738297 ,  1.5176282 ,
        2.354422  ], dtype=float32), array([ 0.22976479,  1.5932227 , -3.095042  , -3.3508677 , -0.9362112 ,
       -1.9563627 ,  1.0111499 , -0.11635169, -0.8390506 ,  0.8199928 ,
        0.12255799,  1.0578141 , -0.5978777 ,  4.1067834 , -3.9543886 ,
        0.7755627 ], dtype=float32), array([ 1.675881  ,  3.0038323 , -3.2926066 , -2.475192  , -2.6387274 ,
        1.5313997 ,  0.7879333 , -3.680658  , -1.3516712 ,  1.9658434 ,
       -0.7334595 , -0.15572721, -4.89263   ,  2.3795257 , -1.9436594 ,
        0.72579795], dtype=float32), array([-0.7576191 , -4.1867213 , -2.2607234 , -0.6633982 ,  0.07318647,
       -0.5883166 , -0.12760168,  2.6613986 ,  0.21186355,  2.822268  ,
       -2.0115097 , -0.1853537 ,  1.4536544 , -2.738704  , -3.6947472 ,
        3.5244794 ], dtype=float32), array([ 1.4165138 , -2.4190922 ,  2.9752576 , -2.0401785 , -3.359743  ,
       -2.7271028 , -4.1425147 ,  1.510121  , -0.96149015,  2.039356  ,
        0.7341554 , -4.187533  , -3.1279187 ,  4.6410155 , -7.2763796 ,
       -2.474819  ], dtype=float32), array([ 5.2550645, -5.358551 , -3.6287344, -3.4365196, -4.9681535,
        1.8872664, -1.4541926,  3.3215873, -1.3585929,  1.4102308,
       -0.6849086,  2.938055 , -3.75784  , -4.256866 , -7.6781807,
       -1.9874793], dtype=float32), array([-6.5368927e-01, -3.3061509e+00, -1.5199324e+00, -8.2662363e+00,
        1.4671850e+00, -6.3459778e+00,  1.3871527e-01, -9.8475438e-01,
        2.7998927e+00, -2.0372493e+00, -1.2238214e+00, -1.1217413e+00,
       -2.7047187e-01,  2.1716359e+00,  3.9549014e-03,  1.9660964e+00],
      dtype=float32), array([-0.43406725, -3.2547731 , -1.9502971 , -0.61113125, -0.03113229,
        0.04936428, -1.0148516 ,  2.922048  ,  0.51309043,  2.1059632 ,
       -1.1534024 , -0.3823554 ,  0.5290213 , -2.4603775 , -4.316388  ,
        2.7034712 ], dtype=float32), array([ 1.5286385 , -2.8429685 ,  3.3001099 , -0.57341415, -2.928202  ,
       -2.2331438 , -4.6439466 ,  1.1675051 , -1.0958089 ,  2.1561792 ,
        0.01507305, -4.07805   , -2.8770216 ,  3.0522425 , -6.7119813 ,
       -2.2745335 ], dtype=float32), array([-0.8041734 ,  4.5399394 , -3.5566058 , -0.0773789 , -2.459625  ,
       -1.8820504 ,  0.2566677 ,  0.21865852, -3.1512177 ,  5.0737267 ,
       -1.6792638 , -0.24389264, -4.112286  ,  5.1340847 , -0.63389385,
       -0.07317136], dtype=float32), array([ 0.06837384,  4.9352207 , -1.479335  ,  3.784014  , -1.1291261 ,
       -3.6243317 , -0.72565156,  7.013981  , -2.8286448 ,  2.9387317 ,
        1.3460965 ,  2.4483402 , -1.3678138 ,  2.265227  , -0.6005244 ,
       -3.43228   ], dtype=float32), array([ -2.6794224 ,  -0.20848231, -11.744877  ,   2.7911906 ,
        -7.9021754 ,  -6.7810807 ,  -4.697872  ,   9.278916  ,
        -8.960374  ,  -1.0114343 ,  -8.691238  ,  -7.4799814 ,
        -6.050734  ,  -6.179188  ,   6.0436263 ,  -2.7386198 ],
      dtype=float32), array([ 5.94508   , -8.898334  ,  8.496558  , -7.0175924 ,  6.8044744 ,
       24.004614  , -1.5860786 , 15.299874  , -6.708429  ,  9.111893  ,
       -0.42546713,  9.37081   , -1.5611526 , -5.6234035 ,  6.249767  ,
       -2.9955952 ], dtype=float32), array([ 0.06837384,  4.9352207 , -1.479335  ,  3.784014  , -1.1291261 ,
       -3.6243317 , -0.72565156,  7.013981  , -2.8286448 ,  2.9387317 ,
        1.3460965 ,  2.4483402 , -1.3678138 ,  2.265227  , -0.6005244 ,
       -3.43228   ], dtype=float32), array([-0.8041734 ,  4.5399394 , -3.5566058 , -0.0773789 , -2.459625  ,
       -1.8820504 ,  0.2566677 ,  0.21865852, -3.1512177 ,  5.0737267 ,
       -1.6792638 , -0.24389264, -4.112286  ,  5.1340847 , -0.63389385,
       -0.07317136], dtype=float32), array([ 1.675881  ,  3.0038323 , -3.2926066 , -2.475192  , -2.6387274 ,
        1.5313997 ,  0.7879333 , -3.680658  , -1.3516712 ,  1.9658434 ,
       -0.7334595 , -0.15572721, -4.89263   ,  2.3795257 , -1.9436594 ,
        0.72579795], dtype=float32), array([-0.6572458 , -4.8549213 , -2.4102004 ,  0.06566047, -0.08031303,
       -0.16232479, -2.2213352 ,  2.2161353 , -0.33188576,  2.9706035 ,
       -2.4847577 ,  0.7765032 ,  0.47840843, -2.8201206 , -5.967195  ,
        2.9729013 ], dtype=float32), array([ 0.0382089 ,  1.503925  , -2.294088  , -2.1815724 , -0.09158628,
       -1.6838557 ,  0.34845984,  0.44897333, -1.0271981 ,  1.3983697 ,
        0.40154693,  0.9622241 , -0.67672026,  3.9588773 , -3.4430373 ,
        1.0274647 ], dtype=float32), array([-0.9108493 ,  0.7892975 ,  2.665287  , -3.9641724 ,  0.2278021 ,
       -2.2233953 ,  0.06662396,  3.7210617 ,  1.5043509 ,  0.35968727,
        3.2404988 , -4.3443666 ,  0.9102807 ,  4.5979114 , -0.9937742 ,
        0.34853578], dtype=float32), array([-1.4342139 , -2.1596258 , -5.18211   , -1.990359  , -0.94903594,
        1.2130194 , -4.467531  ,  3.638181  ,  0.4146112 , -0.9076433 ,
        0.20927827,  1.091635  , -2.3539073 , -4.540105  , -4.7805142 ,
        1.9658401 ], dtype=float32), array([ 1.4165138 , -2.4190922 ,  2.9752576 , -2.0401785 , -3.359743  ,
       -2.7271028 , -4.1425147 ,  1.510121  , -0.96149015,  2.039356  ,
        0.7341554 , -4.187533  , -3.1279187 ,  4.6410155 , -7.2763796 ,
       -2.474819  ], dtype=float32), array([-0.43406725, -3.2547731 , -1.9502971 , -0.61113125, -0.03113229,
        0.04936428, -1.0148516 ,  2.922048  ,  0.51309043,  2.1059632 ,
       -1.1534024 , -0.3823554 ,  0.5290213 , -2.4603775 , -4.316388  ,
        2.7034712 ], dtype=float32), array([ 1.5286385 , -2.8429685 ,  3.3001099 , -0.57341415, -2.928202  ,
       -2.2331438 , -4.6439466 ,  1.1675051 , -1.0958089 ,  2.1561792 ,
        0.01507305, -4.07805   , -2.8770216 ,  3.0522425 , -6.7119813 ,
       -2.2745335 ], dtype=float32), array([ 0.8673375 ,  0.31981596,  1.2055221 , -1.9897474 , -1.2329    ,
       -2.3448653 , -0.14327769, -0.14208671,  0.5255722 ,  0.4865796 ,
       -1.6236091 , -6.274632  , -1.6383896 ,  4.4438977 , -3.2867827 ,
       -0.14418675], dtype=float32), array([ 0.22976479,  1.5932227 , -3.095042  , -3.3508677 , -0.9362112 ,
       -1.9563627 ,  1.0111499 , -0.11635169, -0.8390506 ,  0.8199928 ,
        0.12255799,  1.0578141 , -0.5978777 ,  4.1067834 , -3.9543886 ,
        0.7755627 ], dtype=float32), array([-6.1814737 , -1.1714957 ,  4.1898866 , -7.389282  ,  8.435141  ,
        2.962274  , -1.6662652 ,  4.1867833 ,  6.542118  ,  2.5723171 ,
       11.189238  ,  6.723832  , -0.75193447,  1.4799235 ,  1.739575  ,
        5.814503  ], dtype=float32), array([-2.2749949 , -4.715433  , -1.0171803 , -2.4407728 ,  2.7499979 ,
       -5.886449  , -1.0793504 , -3.9736736 ,  3.4497643 ,  0.01202778,
       -5.7547336 , -0.9896278 , -4.0494285 , -0.2831246 , -0.78259265,
        2.129125  ], dtype=float32), array([ 0.0382089 ,  1.503925  , -2.294088  , -2.1815724 , -0.09158628,
       -1.6838557 ,  0.34845984,  0.44897333, -1.0271981 ,  1.3983697 ,
        0.40154693,  0.9622241 , -0.67672026,  3.9588773 , -3.4430373 ,
        1.0274647 ], dtype=float32), array([-0.6572458 , -4.8549213 , -2.4102004 ,  0.06566047, -0.08031303,
       -0.16232479, -2.2213352 ,  2.2161353 , -0.33188576,  2.9706035 ,
       -2.4847577 ,  0.7765032 ,  0.47840843, -2.8201206 , -5.967195  ,
        2.9729013 ], dtype=float32), array([-0.9108493 ,  0.7892975 ,  2.665287  , -3.9641724 ,  0.2278021 ,
       -2.2233953 ,  0.06662396,  3.7210617 ,  1.5043509 ,  0.35968727,
        3.2404988 , -4.3443666 ,  0.9102807 ,  4.5979114 , -0.9937742 ,
        0.34853578], dtype=float32)]
```


I don't know how to produce post predictions from the model before fitting. Can you tell me how to get that so I can share that also with you.

**Comment by gadagashwini** [comment]
Hi @faysalhossain2007, Can you try the workaround mentioned on similar thread [here](https://github.com/tensorflow/tensorflow/issues/35100#issuecomment-671504721). Thank you!
