### ISSUE TITLE
tf.keras.layers.Bidirectional: Please initialize `Bidirectional` layer with a `tf.keras.layers.Layer` instance

### ISSUE THREAD

**Issue by Nafees-060** [keras-team/keras#16690]
Getting some strange error when using **bidirectional LSTM** in `tf.keras`. I have followed documentation of [bidriectional][1], but getting the error. 

**Here is the code:**
   

     rl = Reshape((-1, int(cnn_SE_featureMap.shape[2]) * int(cnn_SE_featureMap.shape[3])))(
            input) ####(type_spec=TensorSpec(shape=(None, 24, 9))
    # lstm_l6 = tf.keras.layers.LSTM(128, activation='tanh', recurrent_initializer=tf.keras.initializers.Orthogonal(seed=1), dropout=0.5, recurrent_dropout=0.25)(lstm_l5)
    lstm_l5 = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(128, activation='tanh',
                                   recurrent_initializer=tf.keras.initializers.Orthogonal(), dropout=0.5,
                                   recurrent_dropout=0.5, return_sequences=True)(rl)) 

**Error:**
Traceback (most recent call last):
  

    File "/home/anafees/.local/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3251, in run_code
        exec(code_obj, self.user_global_ns, self.user_ns)
      File "<ipython-input-11-721b57a9dbb6>", line 1, in <module>
        lstm_l5 = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(128, activation='tanh',
      File "/home/anafees/.local/lib/python3.9/site-packages/keras/layers/wrappers.py", line 453, in __init__
        raise ValueError(
    ValueError: Please initialize `Bidirectional` layer with a `tf.keras.layers.Layer` instance. Received: KerasTensor(type_spec=TensorSpec(shape=(None, 128), dtype=tf.float32, name=None), name='lstm_5/strided_slice_3:0', description="created by layer 'lstm_5'")
      
[1]: https://www.tensorflow.org/api_docs/python/tf/keras/layers/Bidirectional

**Comment by tilakrayal** [comment]
@Nafees-060,
To expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thank you!

**Comment by FrameMuse** [comment]
@Nafees-060 Could give some information about resolving this issue? I'm experiencing this too and I couldn't find any solution so far.

**Comment by Nafees-060** [comment]
@FrameMuse Might be. But now `bl = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64,dropout=0.5)(rl)` is working for me
