### ISSUE TITLE
ValueError: Quantizing a tf.keras Model inside another tf.keras Model is not supported.

### ISSUE THREAD

**Issue by zhenhao-huang** [keras-team/keras#16888]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras):y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu18
- TensorFlow installed from (source or binary):source 
- TensorFlow version (use command below):2.6.0
- Python version:3.6
- Bazel version (if compiling from source):
- GPU model and memory:
- Exact command to reproduce:

**Describe the problem**.

Quantization aware training in Keras incompatible with tf.keras.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no):
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.

    import tensorflow as tf
    from tensorflow.keras.models import Model
    
    
    class Mobilenet_v2():
        def __init__(self):
            self._base_model = tf.keras.applications.MobileNetV2(input_shape=(224, 224, 3), include_top=False, weights=None)
    
            _MOBILENET_V2_FPN_SKIP_LAYERS = ['block_2_add', 'block_5_add']
            self.skip_outputs = [
                self._base_model.get_layer(skip_layer_name).output
                for skip_layer_name in _MOBILENET_V2_FPN_SKIP_LAYERS
            ]
    
            self.conv_fpn_d = tf.keras.models.Sequential([
                tf.keras.layers.DepthwiseConv2D(
                    kernel_size=3, padding="same", activation=None),
                tf.keras.layers.Conv2D(
                    filters=24, kernel_size=1, activation=None),
                tf.keras.layers.BatchNormalization(),
                tf.keras.layers.ReLU(),
                tf.keras.layers.Conv2DTranspose(filters=24,
                                                kernel_size=3, padding="same", strides=(2, 2))
            ])
            self.conv_fpn_e = tf.keras.models.Sequential([
                tf.keras.layers.Conv2D(
                    filters=24, kernel_size=1, activation=None),
                tf.keras.layers.BatchNormalization(),
                tf.keras.layers.ReLU()
            ])
    
            self.conv_final = tf.keras.models.Sequential([
                tf.keras.layers.DepthwiseConv2D(
                    kernel_size=3, padding="same", activation=None),
                tf.keras.layers.Conv2D(
                    filters=24, kernel_size=1, activation=None),
                tf.keras.layers.BatchNormalization(),
                tf.keras.layers.ReLU(),
                tf.keras.layers.DepthwiseConv2D(
                    kernel_size=3, padding="same", activation=None)
            ])
    
        def build_model(self):
            fm64 = self.skip_outputs[0]
            fm32 = self.skip_outputs[1]
    
            decode_up = self.conv_fpn_d(fm32)
            encode = self.conv_fpn_e(fm64)
            fuse = encode + decode_up
    
            y = self.conv_final(fuse)
            sigmoid = tf.keras.layers.Activation("sigmoid")(y)
    
            return Model(inputs=self._base_model.input, outputs=sigmoid)
    
    
    if __name__ == '__main__':
        import tensorflow_model_optimization as tfmot
        model = Mobilenet_v2().build_model()
        print(model.summary())
        quantize_model = tfmot.quantization.keras.quantize_model
        q_aware_model = quantize_model(model)
        print(q_aware_model.summary())

**Source code / logs**.

    Traceback (most recent call last):
      File "train.py", line 31, in <module>
        trainer.train(config)
      File "/code/src/trainers/trainer_quant.py", line 161, in train
        q_aware_model = quantize_model(model)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow_model_optimization/python/core/quantization/keras/quantize.py", line 138, in quantize_model
        annotated_model = quantize_annotate_model(to_quantize)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow_model_optimization/python/core/quantization/keras/quantize.py", line 211, in quantize_annotate_model
        to_annotate, input_tensors=None, clone_function=_add_quant_wrapper)
      File "/usr/local/lib/python3.6/dist-packages/keras/models.py", line 452, in clone_model
        model, input_tensors=input_tensors, layer_fn=clone_function)
      File "/usr/local/lib/python3.6/dist-packages/keras/models.py", line 192, in _clone_functional_model
        model, new_input_layers, layer_fn)
      File "/usr/local/lib/python3.6/dist-packages/keras/models.py", line 245, in _clone_layers_and_model_config
        model, serialize_layer_fn=_copy_layer)
      File "/usr/local/lib/python3.6/dist-packages/keras/engine/functional.py", line 1349, in get_network_config
        layer_config = serialize_layer_fn(layer)
      File "/usr/local/lib/python3.6/dist-packages/keras/models.py", line 241, in _copy_layer
        created_layers[layer.name] = layer_fn(layer)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow_model_optimization/python/core/quantization/keras/quantize.py", line 205, in _add_quant_wrapper
        'Quantizing a tf.keras Model inside another tf.keras Model is not supported.'
    ValueError: Quantizing a tf.keras Model inside another tf.keras Model is not supported.

**Comment by tilakrayal** [comment]
@zhenhao-huang,
 Could you please try to modify your code as mentioned below and try to execute.

```
IMG_SHAPE = (224, 224, 3)
base_model = tf.keras.applications.MobileNetV2(input_shape=IMG_SHAPE,
                                                  include_top=False, 
                                                  weights='imagenet')
base_model.trainable = False
x = tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu')(base_model.output)
x = tf.keras.layers.Dropout(0.5)(x)
x = tf.keras.layers.MaxPool2D(pool_size=(2, 2))(x)
x = tf.keras.layers.Flatten()(x)
x = tf.keras.layers.Dense(units=2, activation='softmax')(x)

model = tf.keras.Model(base_model.input, x)
model.summary()
```


The model summary shows all of the layers including the base_model. Then please try to apply:

```
quantize_model = tfmot.quantization.keras.quantize_model
q_aware_model = quantize_model(model)
```

**Comment by zhenhao-huang** [comment]
I tried it, but there was a mistake.

    Traceback (most recent call last):
      File "C:/Users/laozhenyao/Desktop/code/src/models/mbn_v2_13_block.py", line 201, in <module>
        model = tfmot.quantization.keras.quantize_model(model)
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\tensorflow_model_optimization\python\core\quantization\keras\quantize.py", line 141, in quantize_model
        return quantize_apply(annotated_model)
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\tensorflow_model_optimization\python\core\keras\metrics.py", line 74, in inner
        raise error
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\tensorflow_model_optimization\python\core\keras\metrics.py", line 69, in inner
        results = func(*args, **kwargs)
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\tensorflow_model_optimization\python\core\quantization\keras\quantize.py", line 455, in quantize_apply
        requires_output_quantize) = _extract_original_model(model_copy)
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\tensorflow_model_optimization\python\core\quantization\keras\quantize.py", line 381, in _extract_original_model
        unwrapped_model = keras.models.clone_model(
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\keras\models.py", line 451, in clone_model
        return _clone_functional_model(
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\keras\models.py", line 195, in _clone_functional_model
        functional.reconstruct_from_config(model_configs,
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\keras\engine\functional.py", line 1283, in reconstruct_from_config
        process_node(layer, node_data)
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\keras\engine\functional.py", line 1231, in process_node
        output_tensors = layer(input_tensors, **kwargs)
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\keras\engine\base_layer.py", line 976, in __call__
        return self._functional_construction_call(inputs, args, kwargs,
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\keras\engine\base_layer.py", line 1114, in _functional_construction_call
        outputs = self._keras_tensor_symbolic_call(
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\keras\engine\base_layer.py", line 848, in _keras_tensor_symbolic_call
        return self._infer_output_signature(inputs, args, kwargs, input_masks)
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\keras\engine\base_layer.py", line 888, in _infer_output_signature
        outputs = call_fn(inputs, *args, **kwargs)
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\keras\layers\core.py", line 1350, in _call_wrapper
        return self._call_wrapper(*args, **kwargs)
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\keras\layers\core.py", line 1382, in _call_wrapper
        result = self.function(*args, **kwargs)
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\tensorflow\python\util\dispatch.py", line 206, in wrapper
        return target(*args, **kwargs)
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1697, in _add_dispatch
        if x.dtype == dtypes.string:
    AttributeError: 'list' object has no attribute 'dtype'

**Comment by zhenhao-huang** [comment]
tfmot don't support `+` sign，but support `tf.keras.layers.Add()`.
