### ISSUE TITLE
IntegerLookup fails for XLA

### ISSUE THREAD

**Issue by jeisinge** [keras-team/keras#17072]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.9.1
- Python version: 3.9.5
- Bazel version (if compiling from source):
- GPU model and memory: Nvidia A100, 16 GB
- Exact command to reproduce: 

```python3
def make_model():  
  vocabulary = list(range(1, 11))
  
  return keras.Sequential([
    keras.layers.IntegerLookup(vocabulary=vocabulary),

    keras.layers.Lambda(lambda x: tf.cast(x, tf.dtypes.float32), name="cast"),
    keras.layers.Reshape([1,]),

    # keras.layers.Embedding(len(vocabulary) + 2, 8, input_length=1),
    
    tf.keras.layers.Dense(1, activation='sigmoid')
  ])

xla_model = make_model()
xla_model.compile(
  loss=tf.losses.BinaryCrossentropy(),
  optimizer=opt,
  metrics=['AUC'],
  jit_compile=True
)

xla_model.fit(
  dataset,
  steps_per_epoch=100,
  epochs=2,
  verbose=1
)
```

**Describe the problem**.
XLA can dramatically improve train speed.  Lookup tables are useful for going from sparse indices to dense indices for embeddings.  However, this lookup fails when XLA is enabled.

**Describe the current behavior**.
`keras.layers.IntegerLookup` preprocessing layer fail when XLA is enabled:

**Describe the expected behavior**.
XLA supports Keras preprocessing and embedding layers.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): no
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.

For a runnable copy, see https://colab.research.google.com/gist/jeisinge/db516d15b0d7be31c098d9c83aeca235/integerlookup-xla.ipynb .

**Source code / logs**.
```python3
InvalidArgumentError                      Traceback (most recent call last)

[<ipython-input-8-2e968a73609f>](https://localhost:8080/#) in <module>
      3   steps_per_epoch=100,
      4   epochs=2,
----> 5   verbose=1
      6 )

1 frames

[/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py](https://localhost:8080/#) in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

[/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py](https://localhost:8080/#) in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     53     ctx.ensure_initialized()
     54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:
     57     if name is not None:

InvalidArgumentError: Graph execution error:

Detected at node 'StatefulPartitionedCall' defined at (most recent call last):
    File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "/usr/local/lib/python3.7/dist-packages/traitlets/config/application.py", line 846, in launch_instance
      app.start()
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelapp.py", line 612, in start
      self.io_loop.start()
    File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 132, in start
      self.asyncio_loop.run_forever()
    File "/usr/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
      self._run_once()
    File "/usr/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
      handle._run()
    File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
      self._context.run(self._callback, *self._args)
    File "/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py", line 758, in _run_callback
      ret = callback()
    File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1233, in inner
      self.run()
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1147, in run
      yielded = self.gen.send(value)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 381, in dispatch_queue
      yield self.process_one()
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 346, in wrapper
      runner = Runner(result, future, yielded)
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1080, in __init__
      self.run()
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1147, in run
      yielded = self.gen.send(value)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 365, in process_one
      yield gen.maybe_future(dispatch(*args))
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 326, in wrapper
      yielded = next(result)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell
      yield gen.maybe_future(handler(stream, idents, msg))
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 326, in wrapper
      yielded = next(result)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 545, in execute_request
      user_expressions, allow_stdin,
    File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 326, in wrapper
      yielded = next(result)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/ipkernel.py", line 306, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/zmqshell.py", line 536, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2855, in run_cell
      raw_cell, store_history, silent, shell_futures)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2881, in _run_cell
      return runner(coro)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
      coro.send(None)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3058, in run_cell_async
      interactivity=interactivity, compiler=compiler, result=result)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3249, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-8-2e968a73609f>", line 5, in <module>
      verbose=1
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1384, in fit
      tmp_logs = self.train_function(iterator)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1021, in train_function
      return step_function(self, iterator)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1010, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
Node: 'StatefulPartitionedCall'
Trying to access resource 1743 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
	 [[{{node StatefulPartitionedCall}}]] [Op:__inference_train_function_2676]
```

**See Also:**
 - https://github.com/tensorflow/tensorflow/issues/43687 - `Embdding` layer issues with TF 2.5 - 2.6
 - https://github.com/keras-team/keras/issues/15508 - `IntegerLookup` layer serialization issues
 - https://github.com/NVIDIA-Merlin/HugeCTR/tree/master/sparse_operation_kit - possible work around?

**Comment by tilakrayal** [comment]
@gowthamkpr ,
I was able to reproduce the issue on tensorflow [v2.8](https://colab.research.google.com/gist/tilakrayal/15c41adf46cdd76901c8806fb762004b/2-8.ipynb#scrollTo=FhIC9wJLk47h), [v2.9](https://colab.research.google.com/gist/tilakrayal/b94325a56f470b415622902032938a28/2-9.ipynb) and [nightly](https://colab.research.google.com/gist/tilakrayal/5d10172e883f25232e3a5b67fa196490/2-11.ipynb). Kindly find the gist of it here.

**Comment by divyashreepathihalli** [comment]
@tilakrayal unfortunately this is a known issue. We are working on resolving this bug. However, in the mean time you can use the integer lookup layer outside of your model in order to have an XLA compiled efficient model. No weights get trained in the lookup layer so, it should not affect anything else in your project.

**Comment by sachinprasadhs** [comment]
Issues facing similar error. https://github.com/keras-team/keras/issues/17148, https://github.com/keras-team/keras/issues/17187, https://github.com/keras-team/keras/issues/17368

**Comment by Nithanaroy** [comment]
Blocked with a similar issue. Voting the issue up :)

@divyashreepathihalli could you help rewrite @jeishinge's code with the approach you suggested?  I tried a few ways but doesn't seem work
