### ISSUE TITLE
Keras load LSTM/GRU model with constant mask/initial_state will raise error

### ISSUE THREAD

**Issue by RunnerZhong** [keras-team/keras#17173]
Issue Type
Bug

Source
binary

Tensorflow Version
TF 2.6.3

Custom Code
Yes

OS Platform and Distribution
RedHat 7

Mobile device
No response

Python version
3.8

Bazel version
No response

GCC/Compiler version
No response

CUDA/cuDNN version
No response

GPU model and memory
No response

Current Behaviour?
Traceback (most recent call last):
  File "/home/runner/work/sample_code/example.py", line 28, in <module>
    dd = tf.keras.models.load_model("./lstm.h5", compile=False, options=load_options)
  File "/home/runner/anaconda3/envs/latest_env/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/runner/anaconda3/envs/latest_env/lib/python3.8/site-packages/keras/backend.py", line 1470, in int_shape
    shape = x.shape
AttributeError: 'float' object has no attribute 'shape'
Standalone code to reproduce the issue
import numpy as np
import tensorflow as tf
import tensorflow.keras.backend as K

input_t = tf.keras.Input(shape=(28, 10), batch_size=2, dtype="float32")

rdm_value = np.ones([2, 28]).astype(np.float32)
rdm_value[:, 20:] = 0
mask_value = K.constant(np.array(rdm_value), dtype='bool')

m_state = tf.keras.initializers.GlorotUniform()(shape=[2, 6], dtype='float32')
c_state = tf.keras.initializers.GlorotUniform()(shape=[2, 6], dtype='float32')
init_state_value = [m_state, c_state]

# mask_value = tf.keras.Input(shape=(28), batch_size=2, dtype="bool")

lstm = tf.keras.layers.LSTM(6,
                            return_sequences=True,
                            return_state=True,
                            bias_initializer='random_uniform',
                            time_major=False)(inputs=input_t, mask=mask_value,
                                              training=False,
                                              initial_state=init_state_value)
keras_model = tf.keras.Model([input_t], lstm)
keras_model.save('./lstm.h5')

load_options = tf.saved_model.LoadOptions(allow_partial_checkpoint=True)
dd = tf.keras.models.load_model("./lstm.h5", compile=False, options=load_options)
print(dd.inputs)

**Comment by sushreebarsa** [comment]
@RunnerZhong Could you have a look at the gist [here](https://colab.research.google.com/gist/sushreebarsa/8d47eb86fb9347e955c108c866f57841/17173.ipynb#scrollTo=VMXJNT8_XgeT) and confirm the issue?
Thank you!

**Comment by RunnerZhong** [comment]
> 

yes, this is the issue that I met

**Comment by sachinprasadhs** [comment]
Could you try compiling the model and train it with some data to check if you are facing the same behavior as saving and loading non compiled model.
Now, as the warning suggested, the compiled metrics has not been built yet, this will be empty till you train or evaluate the model.

**Comment by RunnerZhong** [comment]
I added compiling and train before save the model, but this issue still can reproduce.
![image](https://user-images.githubusercontent.com/30307463/200995480-aba88722-a164-4f81-a2e3-2e6ac109790a.png)

![image](https://user-images.githubusercontent.com/30307463/200995595-9a9a5bba-e7d0-4e84-b175-407105089f63.png)

**Comment by RunnerZhong** [comment]
![image](https://user-images.githubusercontent.com/30307463/200995763-2cfb86fa-3144-4039-a21d-d3c0317d780d.png)

**Comment by RunnerZhong** [comment]
You can have a try too, thanks your reply~

**Comment by sachinprasadhs** [comment]
Could you please provide the reproducible code which you have used to compile the model with sample input. Thanks!

**Comment by RunnerZhong** [comment]
`import numpy as np
import tensorflow as tf
import tensorflow.keras.backend as K

input_t = tf.keras.Input(shape=(28, 10), batch_size=2, dtype="float32")

rdm_value = np.ones([2, 28]).astype(np.float32)
rdm_value[:, 20:] = 0
mask_value = K.constant(np.array(rdm_value), dtype='bool')

m_state = tf.keras.initializers.GlorotUniform()(shape=[2, 6], dtype='float32')
c_state = tf.keras.initializers.GlorotUniform()(shape=[2, 6], dtype='float32')
init_state_value = [m_state, c_state]

# mask_value = tf.keras.Input(shape=(28), batch_size=2, dtype="bool")

lstm = tf.keras.layers.LSTM(6,
                            return_sequences=True,
                            return_state=True,
                            bias_initializer='random_uniform',
                            time_major=False)(inputs=input_t, mask=mask_value,
                                              training=True,
                                              initial_state=init_state_value)
keras_model = tf.keras.Model([input_t], lstm)
keras_model.compile(optimizer="adam", loss="mean_squared_error")
test_input = np.random.random(input_t.shape)
test_target = [np.random.random((2, 28, 6)), np.random.random((2, 6)) ,np.random.random((2, 6))]
keras_model.fit(test_input, test_target)
keras_model.save('./lstm.h5')

load_options = tf.saved_model.LoadOptions(allow_partial_checkpoint=True)
dd = tf.keras.models.load_model("./lstm.h5", compile=True, options=load_options)
print(dd.inputs)`

**Comment by RunnerZhong** [comment]
You can reproduce issue with above sample, thanks.

**Comment by sachinprasadhs** [comment]
I was able to reproduce the behavior using Tf-Nightly(2.13), please find the Gist [here](https://colab.sandbox.google.com/gist/sachinprasadhs/945c49aef5d5bdbd6bc9ff79625c8265/17173.ipynb). Thanks!

**Comment by grasskin** [comment]
@nkovela1
