### ISSUE TITLE
InvalidArgumentError: Graph execution error

### ISSUE THREAD

**Issue by JayR7** [keras-team/keras#17258]
Greetings everyone,

I'm trying to build a NN for a multi-label text classification problem.
When fitting the model, i got the "InvalidArgumentError: Graph execution" error, i'm sure that's a problem related to the embedding shape. i've tried many tries to fix it, but everytime it ends up getting the same result.

Code:
```python
# get the dataset
def get_dataset():
    #Text embedding, then padding
    X= data
    #X=np.array(X)
    y=domain_df[['Domain1_Establishment','Domain2_Contributor','Domain3_Collection','Domain4_Technical','Domain_5_CRM','Domain6_OH']]
    y=np.array(y)
    return X, y

# get the model
def get_model(n_inputs, n_outputs):
	model = Sequential()
	model.add(Embedding((vocab_size+1),16))
	model.add(GlobalAveragePooling1D())
	model.add(Dense(16,input_dim=n_inputs, kernel_initializer='he_uniform', activation='relu'))
	model.add(Dense(n_outputs, activation='sigmoid'))
	model.compile(loss='sparse_categorical_crossentropy', optimizer='adam') #sparse_categorical_crossentropy
	print(model.summary()) 
	return model

# evaluate a model using repeated k-fold cross-validation
def evaluate_model(X, y):
	results = list()
	n_inputs, n_outputs = X.shape[1], y.shape[1]
	# define evaluation procedure
	cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
	# enumerate folds
	for train_ix, test_ix in cv.split(X):
		# prepare data
		X_train, X_test = X[train_ix], X[test_ix]
		y_train, y_test = y[train_ix], y[test_ix]
		# define model
		model = get_model(n_inputs, n_outputs)
		# fit model
		model.fit(X_train, y_train, batch_size=128,verbose=0, epochs=5)
		# make a prediction on the test set
		yhat = model.predict(X_test)
		# round probabilities to class labels
		yhat = yhat.round()
		# calculate accuracy
		acc = accuracy_score(y_test, yhat)
		# store result
		print('>%.3f' % acc)
		results.append(acc)
	return results

# load dataset
X, y = get_dataset()
print(X.shape)
# evaluate model
results = evaluate_model(X, y)
# summarize performance
print('Accuracy: %.3f (%.3f)' % (mean(results), std(results)))

```

Model Summary:
![image](https://user-images.githubusercontent.com/52196205/202845754-f27ddaf2-ebcc-4c92-83df-a1953f3e1bbd.png)

Error:

```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-334-ba4693bcad48> in <module>
      3 print(X.shape)
      4 # evaluate model
----> 5 results = evaluate_model(X, y)
      6 # summarize performance
      7 print('Accuracy: %.3f (%.3f)' % (mean(results), std(results)))

<ipython-input-333-74296c7ef385> in evaluate_model(X, y)
     33                 model = get_model(n_inputs, n_outputs)
     34                 # fit model
---> 35                 model.fit(X_train, y_train, batch_size=128,verbose=0, epochs=5)
     36                 # make a prediction on the test set
     37                 yhat = model.predict(X_test)

~/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)
     68             # To get the full stack trace, call:
     69             # `tf.debugging.disable_traceback_filtering()`
---> 70             raise e.with_traceback(filtered_tb) from None
     71         finally:
     72             del filtered_tb

~/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     52   try:
     53     ctx.ensure_initialized()
---> 54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:

InvalidArgumentError: Graph execution error:

Detected at node 'sequential_24/embedding_22/embedding_lookup' defined at (most recent call last):
:
:
in call out = tf.nn.embedding_lookup(self.embeddings, inputs)
Node: 'sequential_24/embedding_22/embedding_lookup'
indices[56,1] = 24819 is not in [0, 5598)
	 [[{{node sequential_24/embedding_22/embedding_lookup}}]] [Op:__inference_train_function_13411]
```

Appreciate the support!

**Comment by tilakrayal** [comment]
@JayR7,
I was facing a different error while executing the given code. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/9d93edc856b99a161f05f0023b110014/untitled769.ipynb) and provide the complete code.
 Also please try to execute the below code before importing the tensorflow.
**!apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2**
and try to set the below steps.
```
TF_ENABLE_ONEDNN_OPTS=0
TF_DISABLE_MKL=1
```

**Comment by bindu56** [comment]
I got an error as mentioned below



InvalidArgumentError                      Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_7212\2888220523.py in <module>
      1 # print model summary
      2 
----> 3 history = model.fit(x=X_train, validation_data=X_test,
      4                     epochs= epoch,
      5                     steps_per_epoch=X_train.samples//batch_size,

~\AppData\Roaming\Python\Python39\site-packages\keras\utils\traceback_utils.py in error_handler(*args, **kwargs)
     68             # To get the full stack trace, call:
     69             # `tf.debugging.disable_traceback_filtering()`
---> 70             raise e.with_traceback(filtered_tb) from None
     71         finally:
     72             del filtered_tb

~\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\eager\execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     50   try:
     51     ctx.ensure_initialized()
---> 52     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     53                                         inputs, attrs, num_outputs)
     54   except core._NotOkStatusException as e:

InvalidArgumentError: Graph execution error:

Detected at node 'categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):
    File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
      app.launch_new_instance()
    File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
      app.start()
    File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
      self.io_loop.start()
    File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
      self.asyncio_loop.run_forever()
    File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 601, in run_forever
      self._run_once()
    File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 1905, in _run_once
      handle._run()
    File "C:\ProgramData\Anaconda3\lib\asyncio\events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
      await self.process_one()
    File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
      await dispatch(*args)
    File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
      await result
    File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
      reply_content = await reply_content
    File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 390, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
      return super().run_cell(*args, **kwargs)
    File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2914, in run_cell
      result = self._run_cell(
    File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2960, in _run_cell
      return runner(coro)
    File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
      coro.send(None)
    File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3185, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3377, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3457, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\THADIBINDUMADHAVI\AppData\Local\Temp\ipykernel_7212\2888220523.py", line 3, in <module>
      history = model.fit(x=X_train, validation_data=X_test,
    File "C:\Users\THADIBINDUMADHAVI\AppData\Roaming\Python\Python39\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\THADIBINDUMADHAVI\AppData\Roaming\Python\Python39\site-packages\keras\engine\training.py", line 1650, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\THADIBINDUMADHAVI\AppData\Roaming\Python\Python39\site-packages\keras\engine\training.py", line 1249, in train_function
      return step_function(self, iterator)
    File "C:\Users\THADIBINDUMADHAVI\AppData\Roaming\Python\Python39\site-packages\keras\engine\training.py", line 1233, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\THADIBINDUMADHAVI\AppData\Roaming\Python\Python39\site-packages\keras\engine\training.py", line 1222, in run_step
      outputs = model.train_step(data)
    File "C:\Users\THADIBINDUMADHAVI\AppData\Roaming\Python\Python39\site-packages\keras\engine\training.py", line 1024, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "C:\Users\THADIBINDUMADHAVI\AppData\Roaming\Python\Python39\site-packages\keras\engine\training.py", line 1082, in compute_loss
      return self.compiled_loss(
    File "C:\Users\THADIBINDUMADHAVI\AppData\Roaming\Python\Python39\site-packages\keras\engine\compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "C:\Users\THADIBINDUMADHAVI\AppData\Roaming\Python\Python39\site-packages\keras\losses.py", line 152, in __call__
      losses = call_fn(y_true, y_pred)
    File "C:\Users\THADIBINDUMADHAVI\AppData\Roaming\Python\Python39\site-packages\keras\losses.py", line 284, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "C:\Users\THADIBINDUMADHAVI\AppData\Roaming\Python\Python39\site-packages\keras\losses.py", line 2004, in categorical_crossentropy
      return backend.categorical_crossentropy(
    File "C:\Users\THADIBINDUMADHAVI\AppData\Roaming\Python\Python39\site-packages\keras\backend.py", line 5538, in categorical_crossentropy
      return tf.nn.softmax_cross_entropy_with_logits(
Node: 'categorical_crossentropy/softmax_cross_entropy_with_logits'
logits and labels must be broadcastable: logits_size=[32,6] labels_size=[32,10]
	 [[{{node categorical_crossentropy/softmax_cross_entropy_with_logits}}]] [Op:__inference_train_function_4067]

​
