### ISSUE TITLE
Model.load_weights: NotFoundError if have brackets in name and no extension

### ISSUE THREAD

**Issue by jamesbraza** [keras-team/keras#17265]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Monterey version 12.6
- TensorFlow installed from (source or binary): `pip install tensorflow-macos`
- TensorFlow version (use command below): 1.10.0
- Python version: 3.10.8
- Bazel version (if compiling from source): n/a
- GPU model and memory: n/a
- Exact command to reproduce:

```python
import os

import tensorflow as tf

MODELS_DIR = os.path.join(os.path.dirname(__file__), "saved_models")
os.makedirs(MODELS_DIR, exist_ok=True)

model = tf.keras.applications.VGG16()

# Works (no brackets)
model.save_weights(os.path.join(MODELS_DIR, "weights.h5"))
model.load_weights(os.path.join(MODELS_DIR, "weights.h5"))

# Works (brackets with extension)
model.save_weights(os.path.join(MODELS_DIR, "[1].h5"))
model.load_weights(os.path.join(MODELS_DIR, "[1].h5"))

# Doesn't work (brackets without extension)
model.save_weights(os.path.join(MODELS_DIR, "[1]"))
# tensorflow.python.framework.errors_impl.NotFoundError:
# Unsuccessful TensorSliceReader constructor:
# Failed to find any matching files for saved_models/[1]
model.load_weights(os.path.join(MODELS_DIR, "[1]"))
```

**Describe the problem**.

If weights have brackets and no `.h5`, Keras can't load them in.

Also, see: https://stackoverflow.com/a/59426206

**Describe the current behavior**.

Keras can't see the weights file:

```python
Traceback (most recent call last):
  File "/path/to/play.py", line 14, in <module>
    model.load_weights(os.path.join("saved_models", "[1]"))
  File "/path/to/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/path/to/python3.10/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 31, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for saved_models/[1]
```

**Describe the expected behavior**.

I expect it to properly load in the weights, despite not having an extension.

**Standalone code to reproduce the issue**.

See above snippet.

**Comment by tilakrayal** [comment]
@gowthamkpr,
I was able to reproduce the issue on tensorflow v2.9, v2.11 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/e194dcc44dbf610487087dca2ca1ef8d/untitled772.ipynb).

**Comment by rchao** [comment]
Thanks for the report - there are projects being worked on to address a number of saving/loading issues and we should definitely keep this in mind. Unless there are community contributors interested in taking on this, I'm not seeing anything actionable by Keras other than what was mentioned above.
