### ISSUE TITLE
Adagrad: TypeError: Unexpected keyword argument passed to optimizer: weight_decay

### ISSUE THREAD

**Issue by gloglo17** [keras-team/keras#17633]
I am trying to load a saved model with the Adagrad optimizer WITH NO KEYWORD ARGUMENT PASSED but get this error:

```
import tensorflow as tf
from tensorflow.python import keras
from keras.optimizers import Adagrad
from SomeFile import MyLoss

modelName = "/some/path"
model = keras.models.load_model(modelName, custom_objects={'MyLoss': MyLoss, "Custom>Adagrad": Adagrad } )
```

Full:
```
Traceback (most recent call last):
  File "/aux/MakePredictions.py", line 105, in <module>
    LiveGames()
  File "/aux/MakePredictions.py", line 38, in LiveGames
    PredictionSmall (game)
  File "/aux/MakePredictions.py", line 56, in PredictionSmall
    model = keras.models.load_model(modelName, custom_objects={'MyLoss': MyLoss, "Custom>Adagrad": Adagrad } )
  File "/home/au/.local/lib/python3.10/site-packages/tensorflow/python/keras/saving/save.py", line 205, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/home/au/.local/lib/python3.10/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 168, in load
    model.compile(**saving_utils.compile_args_from_training_config(
  File "/home/au/.local/lib/python3.10/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 207, in compile_args_from_training_config
    optimizer = optimizers.deserialize(optimizer_config)
  File "/home/au/.local/lib/python3.10/site-packages/tensorflow/python/keras/optimizers.py", line 94, in deserialize
    return deserialize_keras_object(
  File "/home/au/.local/lib/python3.10/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 674, in deserialize_keras_object
    deserialized_obj = cls.from_config(
  File "/home/au/.local/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/adagrad.py", line 138, in from_config
    return cls(**config)
  File "/home/au/.local/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/adagrad.py", line 84, in __init__
    super().__init__(name, **kwargs)
  File "/home/au/.local/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 379, in __init__
    raise TypeError(
TypeError: Unexpected keyword argument passed to optimizer: weight_decay. Allowed kwargs are {'clipnorm', 'clipvalue', 'decay', 'lr', 'global_clipnorm'}.

```

Keras Version: 2.11.0
Python 3.10.7
Ubuntu 22.10

**Comment by tilakrayal** [comment]
@gloglo17,
I was facing a different issue/error while executing the mentioned code. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/7f39a24d293e75422ed275befe2ebb71/untitled1021.ipynb) and provide the inputs to debug the issue. Thank you!
