### ISSUE TITLE
tf.keras.mixed_precision causes error when using tf.custom_gradient

### ISSUE THREAD

**Issue by jianyizh** [keras-team/keras#18139]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 22.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.12.0
- Python version: 3.9
- Exact command to reproduce: python test.py

**Describe the problem**.

I implemented a custom keras layers with some custom gradient functions (`@tf.custom_gradient`). It works, but when keras mixed precision policy is set, it will fail with error `@tf.custom_gradient grad_fn must accept keyword argument 'variables', since function uses variables`. I think it may because mixed precision policy wraps Variable into AutoCastVariable.

**Describe the current behavior**.
Please run the attached py script. It's a toy example that I defined a custom dense layer, whose call function will call another tf custom gradient function. It will fail in eager mode because of the error I described above. It can pass if you delete `tf.keras.mixed_precision.set_global_policy(policy)`

**Describe the expected behavior**.
It should be no functionality issues when keras mixed precision is turned on.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no):
Yes, if I know how to fix.

**Standalone code to reproduce the issue**.

```
import tensorflow as tf
import numpy as np

@tf.custom_gradient
def custom_bmm(x, w):
  result = tf.raw_ops.BatchMatMulV2(x=x, y=w)
  def grad(upstream):
    dx = tf.raw_ops.BatchMatMulV2(x=upstream, y=w, adj_y=True)
    dy = tf.raw_ops.BatchMatMulV2(x=x, y=upstream, adj_x=True)
    dy = tf.math.reduce_sum(dy,axis=0)
    return dx, dy
  return result, grad

class custom_layer(tf.keras.layers.Layer):
  def __init__(self, num_outputs):
    super(custom_layer, self).__init__()
    self.num_outputs = num_outputs

  def build(self, input_shape):
    self.kernel = self.add_weight("kernel",
                                  shape=[int(input_shape[-1]),
                                  self.num_outputs])

  def call(self, inputs, training=None):
    return custom_bmm(inputs, self.kernel)



policy = tf.keras.mixed_precision.Policy('mixed_bfloat16')
tf.keras.mixed_precision.set_global_policy(policy)


inputs = tf.keras.Input(shape=(1,3,))
x = custom_layer(4)(inputs)
model = tf.keras.Model(inputs=inputs, outputs=x)

result = custom_layer(4)(np.array([[[1.,2.,3.]],[[4.,5.,6.]]]).astype(np.float32))
print(result)
result = model(np.array([[[1.,2.,3.]],[[4.,5.,6.]]]).astype(np.float32))
print(result)

```

**Source code / logs**.
2023-05-18 21:40:18.428090: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-18 21:40:18.456493: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-18 21:40:18.456768: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 AVX_VNNI AMX_TILE AMX_INT8 AMX_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-18 21:40:18.909846: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "test.py", line 37, in <module>
    result = custom_layer(4)(np.array([[[1.,2.,3.]],[[4.,5.,6.]]]).astype(np.float32))
  File "python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "test.py", line 25, in call
    return custom_bmm(inputs, self.kernel)
TypeError: Exception encountered when calling layer 'custom_layer_1' (type custom_layer).

@tf.custom_gradient grad_fn must accept keyword argument 'variables', since function uses variables: [<tf.Variable 'custom_layer_1/kernel:0' shape=(3, 4) dtype=float32, numpy=
array([[-0.57051015,  0.01343554, -0.798573  , -0.41828716],
       [-0.4713288 ,  0.35838473, -0.6395558 , -0.00528103],
       [ 0.7071755 , -0.44282293, -0.41892177, -0.65287685]],
      dtype=float32)>]

Call arguments received by layer 'custom_layer_1' (type custom_layer):
  • inputs=tf.Tensor(shape=(2, 1, 3), dtype=bfloat16)
  • training=None

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.12 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/4c85ac972c0678c3506576a33e787cd1/untitled1166.ipynb).

**Comment by grasskin** [comment]
Would you mind taking a look @reedwm? Thank you!

**Comment by reedwm** [comment]
As you mentioned, I think the issue is due to the fact `tf.custom_gradient` does not properly recognize AutoCastVariable as a variable. @rohan100jain, can you take a look here? But even if this were fixed, I think the example might still not work as AutoCastVariable is only casted inside `Layer.call`, and the custom gradient would not be executed inside `Layer.call` but instead when calling `GradientTape.gradient`. The error message would be much better though.

@grasskin as a workaround, you can avoid passing variables to the `tf.custom_gradient` by calling `read_value` on the variable to convert it to a tensor:

```python
  def call(self, inputs, training=None):
    return custom_bmm(inputs, self.kernel.read_value())
```
