### ISSUE TITLE
ModuleNotFoundError: No module named 'keras.engine' with TF2.13.0-rc0

### ISSUE THREAD

**Issue by cfRod** [keras-team/keras#18141]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 22.04.2 LTS
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.13.0rc0
- Python version: Python 3.10.6
- Bazel version (if compiling from source):bazel-6.2.0-linux-arm64
- GPU model and memory: No, I am on a AArch64 CPU
- Exact command to reproduce:     from keras.engine import data_adapter

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh
This script does not work on Arm systems.

You can obtain the TensorFlow version with:
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"

v2.13.0-rc0-2-g1e17a41ea93 2.13.0-rc0

**Describe the problem**.

Describe the problem clearly here. Be sure to convey here why it's a bug in Keras or why the requested feature is needed.

**Describe the current behavior**.
```
>>> from keras.engine import data_adapter
2023-05-19 13:13:06.132781: I tensorflow/core/util/port.cc:116] Experimental oneDNN custom operations are on. If you experience issues, please turn them off by setting the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'keras.engine'
```

- Do you want to contribute a PR? (yes/no): no

**Standalone code to reproduce the issue**.
```
from keras.engine import data_adapter
```

**Comment by cfRod** [comment]
I am posting the longer log: where I was using the pipeline module from Transformers package which I think depends on keras.engine?
```
from transformers import pipeline
generator = pipeline('text-generation', model=model_name)
```
The full trace is here:
```
Traceback (most recent call last):
  File "/home/ubuntu/python3-venv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1126, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/python3-venv/lib/python3.10/site-packages/transformers/models/gpt2/modeling_tf_gpt2.py", line 30, in <module>
    from ...modeling_tf_utils import (
  File "/home/ubuntu/python3-venv/lib/python3.10/site-packages/transformers/modeling_tf_utils.py", line 69, in <module>
    from keras.engine import data_adapter
ModuleNotFoundError: No module named 'keras.engine'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/text-generation.py", line 20, in <module>
    generator = pipeline('text-generation', model=model_name)
  File "/home/ubuntu/python3-venv/lib/python3.10/site-packages/transformers/pipelines/__init__.py", line 776, in pipeline
    framework, model = infer_framework_load_model(
  File "/home/ubuntu/python3-venv/lib/python3.10/site-packages/transformers/pipelines/base.py", line 238, in infer_framework_load_model
    _class = getattr(transformers_module, f"TF{architecture}", None)
  File "/home/ubuntu/python3-venv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1117, in __getattr__
    value = getattr(module, name)
  File "/home/ubuntu/python3-venv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1116, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/ubuntu/python3-venv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1128, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.gpt2.modeling_tf_gpt2 because of the following error (look up to see its traceback):
No module named 'keras.engine'
```

**Comment by sachinprasadhs** [comment]
Hi, data_adapter is not part of the public API.

It can be imported as below using private namespace.

```
import tensorflow

from tensorflow.python.keras.engine import data_adapter
```

**Comment by cfRod** [comment]
Unfortunately, this is the example code from huggingface's transformer package that is breaking and using the keras engine package.
