### ISSUE TITLE
Loading Models with Keras/Tensorflow into Android App with Chaquopy API

### ISSUE THREAD

**Issue by siddij3** [keras-team/keras#18237]
**System information**.
- OS Platform and Distribution: **Android 13**
- TensorFlow installed from: **Chaquopy**
- TensorFlow version: **tensorflow==2.1**
- Python version: **3.8**

**Describe the problem**.

I trained models then have saved and uploaded them as zip files into the cloud. In the Android App, I'm using a 3rd party API called chaquopy which interfaces python code in a Java app, facilitating the transition between prototyping and deployment.
In the app, I download the models from the cloud, unzip them, then when I try to load these models, an error is thrown.

**Describe the current behavior**.

The app crashes when I try to load the models. There were similar challenges with .h5 files as compiling them threw errors, but they were different errors.

**Describe the expected behavior**.

The model should be loaded, then be able to predict values based on outputs like in the standard documentation.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): **no**

**Standalone code to reproduce the issue**.

build.grade file
```
buildscript {
    repositories {
        jcenter()
        maven { url "https://chaquo.com/maven" }
        google()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.0.2'


        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
plugins {
    id 'com.chaquo.python' version '14.0.2' apply false
    id 'com.android.application' version '7.3.0' apply false
    id 'com.android.library' version '7.3.0' apply false
    id 'org.jetbrains.kotlin.android' version '1.7.21' apply false

}
```

**Source code / logs**.

```
def download_models():
    global optimal_NNs

    path = file_management.get_file_path()

    file_name = functions.get_model_folder_name()

    i = 0
    for filename in os.listdir(os.environ['HOME']):
        if "Model " in filename:
            optimal_NNs = load_model(os.path.join(os.environ['HOME'], f'{filename}'))
            return optimal_NNs.optimizer
```

```
Process: ca.mcmaster.waterqualitymonitor, PID: 28707
com.chaquo.python.PyException: NotFoundError: Op type not registered 'DisableCopyOnRead' in binary running on localhost. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) tf.contrib.resampler should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
at .tensorflow.python.framework.ops._get_op_def(ops.py:3712)
at .tensorflow.python.framework.function_def_to_graph.function_def_to_graph_def(function_def_to_graph.py:218)
at .tensorflow.python.framework.function_def_to_graph.function_def_to_graph(function_def_to_graph.py:58)
at .tensorflow.python.saved_model.function_deserialization.load_function_def_library(function_deserialization.py:312)
at .tensorflow.python.saved_model.load.init(load.py:113)
at .tensorflow.python.keras.saving.saved_model.load.init(load.py:118)
at .tensorflow.python.saved_model.load.load_internal(load.py:550)
at .tensorflow.python.keras.saving.saved_model.load.load(load.py:89)
at .tensorflow.python.keras.saving.save.load_model(save.py:150)
at .backend.download_models(backend.py:54)
at .chaquopy_java.call(chaquopy_java.pyx:354)
at .chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:326)
at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
at ca.mcmaster.testsuitecommon.SplashActivity$1.onClick(SplashActivity.java:99)
at android.view.View.performClick(View.java:7892)
at android.widget.TextView.performClick(TextView.java:16219)
at android.view.View.performClickInternal(View.java:7869)
at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
at android.view.View$PerformClick.run(View.java:30880)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8757)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by siddij3** [comment]
The latest stable keras doesn't provide any issues. It's a platform issue.

**Comment by tilakrayal** [comment]
@siddij3,
Glad the issue was resolved with the latest stable tensorflow version. Are you still looking for any further assistance from the Keras team? If not, Could you please feel free to move this issue to closed status. Thank you!
