### ISSUE TITLE
keras create/load model fails on Apple M2 cpu.  Same code works on Ryzen

### ISSUE THREAD

**Issue by drmatthewclark** [keras-team/keras#18278]
[tf_env.txt](https://github.com/keras-team/keras/files/11970574/tf_env.txt)

You can obtain the TensorFlow version with:
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
result:
v2.13.0-rc2-7-g1cb1a030a62 2.13.0

Can't load a keras model that I just created.  The issue is not specific to Adam; all of the optimizers have the same issue.

**Describe the problem**.

code:

      from tensorflow import keras
      
      
      optimizer = keras.optimizers.Adam()
      
      vh  = keras.Input(shape=(2,3), name = 'vh')
      v1  = keras.layers.Dense(512)(vh)
      
      output  = keras.layers.Dense(1, activation='softmax', name='prediction')(v1)
      
      model = keras.Model(inputs=vh, outputs=[output], name="antibody_model")
      
      model.compile(optimizer=optimizer )
      
      model.save('nn_model.keras')
      test = keras.models.load_model('nn_model.keras')

output:

the legacy Adam is missing the method  "build".  This same code works on non-mac platforms.

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING:absl:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.
Traceback (most recent call last):
  File "/Users/matthewclark/eclipse-workspace/antibody_classification/test/test.py", line 17, in <module>
    test = keras.models.load_model('nn_model.keras')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Shared/anaconda3/envs/ability/lib/python3.11/site-packages/keras/src/saving/saving_api.py", line 230, in load_model
    return saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Shared/anaconda3/envs/ability/lib/python3.11/site-packages/keras/src/saving/saving_lib.py", line 275, in load_model
    raise e
  File "/Users/Shared/anaconda3/envs/ability/lib/python3.11/site-packages/keras/src/saving/saving_lib.py", line 240, in load_model
    model = deserialize_keras_object(
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Shared/anaconda3/envs/ability/lib/python3.11/site-packages/keras/src/saving/serialization_lib.py", line 710, in deserialize_keras_object
    instance.compile_from_config(compile_config)
  File "/Users/Shared/anaconda3/envs/ability/lib/python3.11/site-packages/keras/src/engine/training.py", line 3582, in compile_from_config
    self.optimizer.build(self.trainable_variables)
    ^^^^^^^^^^^^^^^^^^^^
  File "/Users/Shared/anaconda3/envs/ability/lib/python3.11/site-packages/keras/src/optimizers/legacy/optimizer_v2.py", line 997, in __getattribute__
    raise e
  File "/Users/Shared/anaconda3/envs/ability/lib/python3.11/site-packages/keras/src/optimizers/legacy/optimizer_v2.py", line 987, in __getattribute__
    return super().__getattribute__(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Adam' object has no attribute 'build'

**Comment by tilakrayal** [comment]
@drmatthewclark,
I tried to execute the code on both tensorflow v2.12 and v2.13 and it was executed without any error/issue. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/a8443eefbff4cdaf03a432e99de79496/untitled1227.ipynb) and try to test your code in the virtual environment. Thank you!

**Comment by jtpotato** [comment]
Can confirm having the same issue (M1). Haven't had the chance to test on non-Apple Silicon hardware (that I own) yet, but it appears to be fine on Colab...

**Comment by bossebandowski** [comment]
Same here, on M1, python3.10, and tensorflow 2.13.0. Training, inference, and saving works fine. Loading fails.

Code extract:
```
train(model, train_ds, val_ds)
acc = model.evaluate(test_ds)[1]
print(f"test accuracy: {acc}")
model.save(MODEL_PATH)
test = tf.keras.models.load_model(MODEL_PATH)
print("successfully loaded model")
```
Output:
```
[...]
test accuracy: 0.9336022138595581
Traceback (most recent call last):
  File "[my_file]", line 252, in <module>
    test = tf.keras.models.load_model(MODEL_PATH)
  File "[my_venv]/site-packages/keras/src/saving/saving_api.py", line 230, in load_model
    return saving_lib.load_model(
  File "[my_venv]/site-packages/keras/src/saving/saving_lib.py", line 275, in load_model
    raise e
  File "[my_venv]/site-packages/keras/src/saving/saving_lib.py", line 240, in load_model
    model = deserialize_keras_object(
  File "[my_venv]/site-packages/keras/src/saving/serialization_lib.py", line 710, in deserialize_keras_object
    instance.compile_from_config(compile_config)
  File "[my_venv]/site-packages/keras/src/engine/training.py", line 3582, in compile_from_config
    self.optimizer.build(self.trainable_variables)
  File "[my_venv]/site-packages/keras/src/optimizers/legacy/optimizer_v2.py", line 997, in __getattribute__
    raise e
  File "[my_venv]/site-packages/keras/src/optimizers/legacy/optimizer_v2.py", line 987, in __getattribute__
    return super().__getattribute__(name)
AttributeError: 'Adam' object has no attribute 'build'
```

**Comment by tilakrayal** [comment]
@drmatthewclark,
I tried to execute the mentioned above code on both tensorflow v2.12 and tf-nighty(2.14.0-dev20230622), and it was executed without any issue/error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/a8443eefbff4cdaf03a432e99de79496/untitled1227.ipynb)
As it is failing only on tensorflow-macos, we request to raise the concern on the macos-apple [forum](https://developer.apple.com/forums/) for the quick resolution. Thank you!

**Comment by bossebandowski** [comment]
Hey @tilakrayal,

thank you for your input. I did a bit of digging because I found the issue too annoying and it is clearly a tensorflow problem and not a macos problem. So, here's what I found:

1. As you can easily see from the backtrace in my previous comment, loading a model on the M1/M2 macs causes the legacy optimizers to be loaded instead of the latest code. Sure enough, the [legacy code](https://github.com/keras-team/keras/blob/8d5e9b2163ec9b7d9f70920d1c7992b6df6820ec/keras/optimizers/legacy/optimizer_v2.py#L108) does not have a `build` method while the [latest code](https://github.com/keras-team/keras/blob/8d5e9b2163ec9b7d9f70920d1c7992b6df6820ec/keras/optimizers/optimizer.py#L881) does. So, why is the legacy code executed in the first place?
2. To get an optimizer, the `optimizers.get()` method is called which is defined [here](https://github.com/keras-team/keras/blob/b3ffea6602dbbb481e82312baa24fe657de83e11/keras/optimizers/__init__.py#L257) on the latest tag `v2.13.1`. Whenever we have a mac that runs on the new chips, keras falls back to the legacy optimizers which do not work.
3. As of commit 5ddf84a, this issue seems to be fixed on master, but I cannot find any releases that contain the fix. Is the solution to try and build from source or is there a more convenient way to get the updated code?

**Comment by tilakrayal** [comment]
There is an alternative workaround to make AdamW work on Apple Silicon with the latest version of tensorflow, tensorflow-addons.
All you need to do is to **import AdamW from tensorflow_addons.optimizers**. Could you please try and let us know if this works in your case.

**Comment by mbergwall2222** [comment]
Can confirm same issue on m2 max mac. nightly tensorflow builds don't work and neither does tensorflow-addons.

**Comment by tcivie** [comment]
> import AdamW from tensorflow_addons.optimizers

Also tried this and got the same result (M2 Mac):
`AttributeError: 'AdamW' object has no attribute 'build'`

Tried also the suggested solutions from [this thread](https://github.com/keras-team/keras/issues/18224) without any success

**Comment by norwend** [comment]
Same error with the SDG omptimizer. M1 Macbook Air.

> Traceback (most recent call last):
>   File "***", line 17, in <module>
>     model = keras.models.load_model(
>             ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/keras/src/saving/saving_api.py", line 230, in load_model
>     return saving_lib.load_model(
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/keras/src/saving/saving_lib.py", line 275, in load_model
>     raise e
>   File "/opt/homebrew/lib/python3.11/site-packages/keras/src/saving/saving_lib.py", line 240, in load_model
>     model = deserialize_keras_object(
>             ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/keras/src/saving/serialization_lib.py", line 710, in deserialize_keras_object
>     instance.compile_from_config(compile_config)
>   File "/opt/homebrew/lib/python3.11/site-packages/keras/src/engine/training.py", line 3582, in compile_from_config
>     self.optimizer.build(self.trainable_variables)
>     ^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/keras/src/optimizers/legacy/optimizer_v2.py", line 997, in __getattribute__
>     raise e
>   File "/opt/homebrew/lib/python3.11/site-packages/keras/src/optimizers/legacy/optimizer_v2.py", line 987, in __getattribute__
>     return super().__getattribute__(name)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'SGD' object has no attribute 'build'

**Comment by RobP-git** [comment]
same issue here also. M1 mac.
current workaround is to save and load using the legacy .h5 file extension.

**Comment by samhva** [comment]
Same issue here, fix plz.
M2 Pro

**Comment by ptn24** [comment]
Ditto. I am using TensorFlow 2.13 on macOS with M2.

**Comment by LiWangSH** [comment]
Same issue, using Tensorflow 2.13.0 and Python 3.10/13 on Mac M2.

**Comment by LiWangSH** [comment]
Saving the model to a different format (h5) solved the issue^ for me.
- Source: https://stackoverflow.com/questions/76311807/attributeerror-adam-object-has-no-attribute-build-during-unpickling/76311808#76311808

**Comment by palminha** [comment]
any news on this issue?
we are having the same problem here with tensorflow 2.13 in MacOS M1

**Comment by qlzh727** [comment]
Adding Neel for the saving issue.
