### ISSUE TITLE
Using TensorFlow backend with tensorflow-directml-plugin

### ISSUE THREAD

**Issue by Giszy** [keras-team/keras#18434]
Using TensorFlow backend
```python
Epoch 1/3
Traceback (most recent call last):
  File "E:\custom_train_step_in_tensorflow.py", line 131, in <module>
    model.fit(x, y, epochs=3)
  File "C:\Python_310\lib\site-packages\keras_core\src\utils\traceback_utils.py", line 123, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Python_310\lib\site-packages\tensorflow\python\eager\execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:

Detected at node 'StatefulPartitionedCall' defined at (most recent call last):
    File "E:\custom_train_step_in_tensorflow.py", line 131, in <module>
      model.fit(x, y, epochs=3)
    File "C:\Python_310\lib\site-packages\keras_core\src\utils\traceback_utils.py", line 118, in error_handler
      return fn(*args, **kwargs)
    File "C:\Python_310\lib\site-packages\keras_core\src\backend\tensorflow\trainer.py", line 307, in fit
      logs = self.train_function(iterator)
    File "C:\Python_310\lib\site-packages\keras_core\src\backend\tensorflow\trainer.py", line 112, in one_step_on_iterator
      outputs = self.distribute_strategy.run(
Node: 'StatefulPartitionedCall'
Could not find compiler for platform DML: NOT_FOUND: could not find registered compiler for platform DML -- was support for that platform linked in?
         [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_iterator_697]
```

The original code is at https://github.com/keras-team/keras-io/blob/master/guides/keras_core/custom_train_step_in_tensorflow.py.

**Comment by sachinprasadhs** [comment]
@Giszy , Could you please try again with the latest Tensorflow version with Keras 3 and let us know the outcome.

If you still face issue, more detail on the issue would be helpful. Thanks!
