### ISSUE TITLE
Selecting Metal (MPS) as the GPU in MacOS (torch backend)

### ISSUE THREAD

**Issue by dkgaraujo** [keras-team/keras#18437]
First off, congratulations on keras-core: keras is awesome, keras-core is awesomer!
Using a Mac, I was trying to manually set a keras-core more with torch backend to benefit from the Metal GPU acceleration, which works on both Apple silicon and AMD GPUs. I noted this was not possible due to:

- [`get_device()`](https://github.com/keras-team/keras-core/blob/62a74084d6ea68bab1c596aba9760722da7a8d92/keras_core/backend/torch/core.py#L43), which reads from a `threading` global state.
- [the default device is CUDA](https://github.com/keras-team/keras-core/blob/62a74084d6ea68bab1c596aba9760722da7a8d92/keras_core/backend/torch/core.py#L15C64-L15C64)

As can be seen [here](https://pytorch.org/docs/stable/notes/mps.html), in MacOS systems using the GPU can be as easy as setting the device to "mps". So I would like to ask if there would be an opportunity for a PR that implements some version of the snippet below that wouldn't fail on non-Apple machines:

```
# keras_core/backend/torch/core.py
if torch.cuda.is_available():
    DEFAULT_DEVICE = "cuda"
elif:
    if torch.backends.mps.is_available():
    DEFAULT_DEVICE = "mps"
else:
    DEFAULT_DEVICE = "cpu"
```

The goal is to have Keras-core seamlessly choose MPS as the default GPU in PyTorch backends, just as it already does for tensorflow implementations using the Metal pluggable device.

**Comment by sr5434** [comment]
What about for TensorFlow backends?

**Comment by SH2282000** [comment]
If you are like me and just look for the way to use GPUs with Tensorflow and/or Keras, just refer to [this official Apple documentation](https://developer.apple.com/metal/tensorflow-plugin/).

```shell
# Uninstall all tensorflow dependencies
# The only things to install are:

# Tensorflow
python -m pip install tensorflow

# IMPORTANT: The plugin of Tensorflow made to use mps capabilities
python -m pip install tensorflow-macos
```

Basically, when installing the normal `tensorflow` dependency, you still need to install the plugin which allows using your `mps` devices. This will be called `GPU` and you can verify it is correctly installed by typing:

```python
import tensorflow as tf

tf.config.list_physical_devices('GPU')
```

Which should now return something like:
```txt
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```

source: https://developer.apple.com/metal/tensorflow-plugin/

**Comment by ghsanti** [comment]
@mehtamansi29 

It seems this issue was completed here ? https://github.com/keras-team/keras-core/pull/750

**Comment by dhantule** [comment]
Hi @dkgaraujo, thanks for reporting this. Could you confirm if the issue is resolved for you?

**Comment by dkgaraujo** [comment]
> Hi [@dkgaraujo](https://github.com/dkgaraujo), thanks for reporting this. Could you confirm if the issue is resolved for you?

Sorry for the delay in responding, @dhantule. Apparently for me it works... but fails because of the limited support to MPS GPU on PyTorch's side:

```
Epoch 1/5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/venv_path/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/venv_path/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
NotImplementedError: The operator 'aten::_foreach_mul_.Scalar' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
```
