### ISSUE TITLE
Upsampling layer with bilinear interpolation fails in Torch 2.1.0

### ISSUE THREAD

**Issue by tarushbansal** [keras-team/keras#18578]
Hi, I installed the latest Torch version (2.1.0) and I noticed the Upsampling layer in Keras Core fails with the following error trace:
```
Traceback (most recent call last):
  File "/Users/tarban01/Desktop/SME-Hero/test.py", line 5, in <module>
    x = upsample_layer(torch.zeros((1, 1080, 1920, 3)))
  File "/Users/tarban01/Library/Python/3.9/lib/python/site-packages/keras_core/src/utils/traceback_utils.py", line 123, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/tarban01/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/tarban01/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/tarban01/Library/Python/3.9/lib/python/site-packages/torchvision/transforms/functional.py", line 492, in resize
    return F_t.resize(img, size=output_size, interpolation=interpolation.value, antialias=antialias)
  File "/Users/tarban01/Library/Python/3.9/lib/python/site-packages/torchvision/transforms/_functional_tensor.py", line 467, in resize
    img = interpolate(img, size=size, mode=interpolation, align_corners=align_corners, antialias=antialias)
  File "/Users/tarban01/Library/Python/3.9/lib/python/site-packages/torch/nn/functional.py", line 3924, in interpolate
    raise TypeError(
TypeError: Exception encountered when calling UpSampling2D.call().

expected size to be one of int or Tuple[int] or Tuple[int, int] or Tuple[int, int, int], but got size with types [<class 'numpy.int64'>, <class 'numpy.int64'>]
```

Code to reproduce:
```
import torch
from keras_core import layers

upsample_layer = layers.UpSampling2D(size=(2, 2), interpolation="bilinear")
x = upsample_layer(torch.zeros((1, 1080, 1920, 3)))
```

**Comment by sampathweb** [comment]
`torch` 2.10 doesn't accept tuple of numpy ints and want python ints.  This is already fixed in Master branch.  If you install from github via - 
```
pip uninstall -y keras
git clone https://github.com/keras-team/keras.git
pip install namex
python pip_build.py --install
```
Then use it as `keras` (its no longer `keras-core` in master).  We will release `keras-nightly` soon so you don't have to go through this build from github once the nightly is released.
