### ISSUE TITLE
ModuleNotFoundError: No module named 'keras.engine'

### ISSUE THREAD

**Issue by hyytest** [keras-team/keras#18593]
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 3369, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-656129af5974>", line 1, in <cell line: 1>
    runfile('E:/python/pythonProject/reptile/web13/nanoreview.py', wdir='E:/python/pythonProject/reptile/web13')
  File "D:\PyCharm 2021.3.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\PyCharm 2021.3.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/python/pythonProject/reptile/web13/nanoreview.py", line 10, in <module>
    import mrcnn.model as modellib
  File "D:\PyCharm 2021.3.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\Python39\lib\site-packages\mrcnn\model.py", line 24, in <module>
    import keras.engine as KE
  File "D:\PyCharm 2021.3.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'keras.engine'

**Comment by sampathweb** [comment]
Can you provide a Colab to reproduce the issue?

**Comment by fchollet** [comment]
> import keras.engine as KE

That's a private API (and it only exists in tf.keras <= 2.12). It's not something anyone should ever use. Remove all dependencies on it.
