### ISSUE TITLE
Shape error of `update_confusion_matrix_variables` with tensorflow

### ISSUE THREAD

**Issue by PatReis** [keras-team/keras#18620]
Hello, 
I encountered a problem when using sample weights in confusion metrics with `tensorflow`. I think the source of the error to be line 543 of `update_confusion_matrix_variables` in `metric_utils` :

```python
    if sample_weight is not None:
        sample_weight = ops.broadcast_to(
            ops.cast(sample_weight, dtype=y_pred.dtype), y_pred.shape
        )
```

which works if replaced by:

```python
    if sample_weight is not None:
        sample_weight = ops.broadcast_to(
            ops.cast(sample_weight, dtype=y_pred.dtype), ops.shape(y_pred)  # use of ops.shape()
        )
```

this would also match line 551-553 in the same function below:

```python
    if label_weights is not None and not multi_label:
        label_weights = ops.expand_dims(label_weights, 0)
        label_weights = ops.broadcast_to(label_weights, ops.shape(y_pred))   # uses also ops.shape
```

If this change is okay, I can make a pull request.

**Comment by fchollet** [comment]
Thanks for the report. What is the error stack trace?

The fix looks good to me, you can open a PR.

**Comment by PatReis** [comment]
The error would look like this

```bash
Epoch 1/50
Traceback (most recent call last):
  File ".\anaconda3\envs\cnn_keras\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2021.3.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2021.3.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "./train.py", line 151, in <module>
    hist = model.fit(
  File ".\anaconda3\envs\cnn_keras\lib\site-packages\keras_core\src\utils\traceback_utils.py", line 123, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File ".\metrics.py", line 219, in update_state
    return super(BalancedBinaryAccuracy, self).update_state(
ValueError: Cannot convert a partially known TensorShape (None, 12) to a Tensor.
```

**Comment by fchollet** [comment]
No, this is fine. The fix you proposed is correct for this issue. Thanks!
