### ISSUE TITLE
Argument `shuffle` is not supported for Python generator inputs

### ISSUE THREAD

**Issue by arthurflor23** [keras-team/keras#18637]
Hi,
Keras 3 gave me a big surprise about the Keras project recently and I started testing lots of small codes here, wonderful! However, I'm trying to run this code sample:

```
import os

#os.environ["KERAS_BACKEND"] = "jax"
#os.environ["KERAS_BACKEND"] = "tensorflow"
os.environ["KERAS_BACKEND"] = "torch"
os.environ["PYTORCH_ENABLE_MPS_FALLBACK"] = "1"

#import torch
import keras_core as keras
import numpy as np

# Commenting out TensorFlow-specific settings
# tf.config.set_visible_devices([], 'GPU')

def generate_data(num_samples, max_size):
    """Generate synthetic data of varying sizes"""
    data = []
    labels = []
    for _ in range(num_samples):
        size = np.random.randint(1, max_size+1)
        data.append(np.ones((size, size)) * 255)  # Example of image
        labels.append(np.random.randint(0, 2))  # binary classification for simplicity
    return data, labels

def data_generator(data, labels, batch_size):
    """Create a generator that returns batches of data"""
    num_samples = len(data)
    indices = np.arange(num_samples)
    while True:
        for i in range(0, num_samples, batch_size):
            batch_indices = indices[i:i+batch_size]
            # Not using tf.ragged.constant. Handling variable-sized data might be an issue.
            batch_data = [data[idx] for idx in batch_indices]
            batch_labels = np.array([labels[idx] for idx in batch_indices], dtype=np.float32)
            yield batch_data, batch_labels
        np.random.shuffle(indices)

class DynamicResizeModel(keras.Model):
    """A model that includes a resizing layer - but note that Resizing is TF specific"""
    def __init__(self, target_size):
        super().__init__()
        self.target_size = target_size
        self.expand_dims = keras.layers.Lambda(lambda x: keras.backend.expand_dims(x, -1))
        # Resizing layer is a TensorFlow specific layer. This will be an issue.
        self.resize = keras.layers.Resizing(*target_size)  
        self.flatten = keras.layers.Flatten()
        self.dense = keras.layers.Dense(1, activation='sigmoid')

    def call(self, inputs):
        x = self.expand_dims(inputs)
        x = self.resize(x)
        x = self.flatten(x)
        return self.dense(x)

# Generate training data
num_samples = 100  # Total number of samples in your dataset
max_size = 1024  # Maximum size of matrix
train_data, train_labels = generate_data(num_samples, max_size)

# Create and train the model
model = DynamicResizeModel(target_size=(1024, 128))  # resize all inputs to 1024, 128
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Set the parameters
batch_size = 8  # Number of samples per batch

# Create a generator
train_generator = data_generator(train_data, train_labels, batch_size)

# Use fit to train the model
model.fit(train_generator, steps_per_epoch=num_samples // batch_size, epochs=1000)
```

However, I'm getting this error:

```
Traceback (most recent call last):
  File "/Users/arthur/VSCode/keras/main5.py", line 72, in <module>
    model.fit(train_generator, steps_per_epoch=num_samples // batch_size, epochs=1000)
  File "/Users/arthur/VSCode/keras/.venv/lib/python3.9/site-packages/keras_core/src/utils/traceback_utils.py", line 123, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/arthur/VSCode/keras/.venv/lib/python3.9/site-packages/keras_core/src/trainers/epoch_iterator.py", line 140, in __init__
    raise ValueError(
ValueError: Argument `shuffle` is not supported for Python generator inputs. Received: shuffle=True
```

Is there any problem with the sample, or anything about the keras 3 ?

**Comment by fchollet** [comment]
Thanks for the report. The solution is to pass `shuffle=False` in `fit()`. However it would be more user-friendly to ignore the value `shuffle=True` (especially since that's the default) and possibly print a warning. This is now fixed at HEAD.
