### ISSUE TITLE
TypeError: copy() got an unexpected keyword argument 'overwrite'

### ISSUE THREAD

**Issue by colbybanbury** [keras-team/keras#18736]
load_model() in saving/saving_api.py calls file_utils.copy() with the argument 'overwrite', which does not exist in utils/file_utils.py

https://github.com/keras-team/keras/blob/master/keras/saving/saving_api.py#L165

[shutil copy overwrites by default](https://docs.python.org/3/library/shutil.html#shutil.copy)
[But gfile copy does not](https://www.tensorflow.org/api_docs/python/tf/io/gfile/copy)

Removing overwrite=True from the function call fixes the error and given that the file is copied to a tmp path, it actually probably does make sense to just always overwrite the file.

Full Error:

Traceback (most recent call last):
File "/home/colby/vww-2/cross_validate.py", line 17, in
vww_model = keras.saving.load_model("gs://wake-vision-storage/saved_models/2023_11_06-03_59_51_PM/vww_mobilenetv1.keras")
File "/home/colby/.local/lib/python3.10/site-packages/keras_core/src/saving/saving_api.py", line 169, in load_model
file_utils.copy(filepath, local_path, overwrite=True)
TypeError: copy() got an unexpected keyword argument 'overwrite'

**Comment by colbybanbury** [comment]
Fix: https://github.com/keras-team/keras/pull/18737#issue-1979821943
