### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow'

### ISSUE THREAD

**Issue by ktaro** [keras-team/keras#18888]
Traceback (most recent call last):
  File
    import keras
  File "C:\Users\...\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\__init__.py", line 8, in <module>
    from keras import _tf_keras
  File "C:\Users\...\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\_tf_keras\__init__.py", line 1, in <module>
    from keras._tf_keras import keras
  File "C:\Users\...\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\_tf_keras\keras\__init__.py", line 8, in <module>
    from keras import activations
  File "C:\Users\...\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\activations\__init__.py", line 8, in <module>
    from keras.src.activations import deserialize
  File "C:\Users\...\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\__init__.py", line 1, in <module>
    from keras.src import activations
  File "C:\Users\...\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\activations\__init__.py", line 3, in <module>
    from keras.src.activations.activations import elu
  File "C:\Users\...\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\activations\activations.py", line 1, in <module>
    from keras.src import backend
  File "C:\Users\...\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\backend\__init__.py", line 33, in <module>
    from keras.src.backend.tensorflow import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\backend\tensorflow\__init__.py", line 1, in <module>
    from keras.src.backend.tensorflow import core
  File "C:\Users\...\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\backend\tensorflow\core.py", line 4, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

Why?

**Comment by SuryanarayanaY** [comment]
Hi @ktaro ,

Keras3 is now supporting multi backend and user has to install his own backend like tensorflow or pytorch or Jax. 

May I know how you are installing Keras and which version etc?

**Comment by ktaro** [comment]
I installed Python 3.12 and installed keras with the command "pip install keras" in Python 3.12, overcoming errors related to dm-tree.
I did not install tensorflow, pytorch, or jax.
