### ISSUE TITLE
keras model crash when backend is theano, while work normally in tensorflow

### ISSUE THREAD

**Issue by cheyennee** [keras-team/keras#18894]
I have a [model](https://drive.google.com/file/d/1i7sJeZS1MgRGS2asxAvx4lW_dWd8q0ac/view?usp=drive_link). I run following code on tensorflow and theano backend. tensorflow backend outputs normally, while theano backend throws error.

repo code:
```
import keras
import numpy as np
from keras.datasets import mnist
(x_train,y_train),(x_test,y_test) = mnist.load_data()
model = keras.models.load_model('/content/289-tensorflow.h5')
input = np.random.rand(1, 28, 28, 1)
model.compile(loss='mean_squared_error', optimizer='adagrad')

history = model.fit(x_train, y_train)
model.predict(input)
```

theano error message:
```
D:\software\anaconda\anaconda\envs\env3.6-1\lib\site-packages\keras\engine\saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
Traceback (most recent call last):
  File "D:\software\anaconda\anaconda\envs\env3.6-1\lib\site-packages\theano\compile\pfunc.py", line 193, in rebuild_collect_shared
    allow_convert=False)
  File "D:\software\anaconda\anaconda\envs\env3.6-1\lib\site-packages\theano\tensor\type.py", line 234, in filter_variable
    self=self))
TypeError: Cannot convert Type TensorType(float32, (True, True, True, False)) (of Variable Elemwise{add,no_inplace}.0) into Type TensorType(float32, vector). You can try to manually convert Elemwise{add,no_inplace}.0 into a TensorType(float32, vector).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/study/bit/aaa/find_model_bug.py", line 18, in <module>
    history = model.fit(x, y,
  File "D:\software\anaconda\anaconda\envs\env3.6-1\lib\site-packages\keras\engine\training.py", line 1213, in fit
    self._make_train_function()
  File "D:\software\anaconda\anaconda\envs\env3.6-1\lib\site-packages\keras\engine\training.py", line 333, in _make_train_function
    **self._function_kwargs)
  File "D:\software\anaconda\anaconda\envs\env3.6-1\lib\site-packages\keras\backend\theano_backend.py", line 1454, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "D:\software\anaconda\anaconda\envs\env3.6-1\lib\site-packages\keras\backend\theano_backend.py", line 1421, in __init__
    **kwargs)
  File "D:\software\anaconda\anaconda\envs\env3.6-1\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "D:\software\anaconda\anaconda\envs\env3.6-1\lib\site-packages\theano\compile\pfunc.py", line 449, in pfunc
    no_default_updates=no_default_updates)
  File "D:\software\anaconda\anaconda\envs\env3.6-1\lib\site-packages\theano\compile\pfunc.py", line 208, in rebuild_collect_shared
    raise TypeError(err_msg, err_sug)
TypeError: ('An update must have the same type as the original shared variable (shared_var=10_batch_normalization/moving_mean, shared_var.type=TensorType(float32, vector), update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float32, (True, True, True, False))).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')
``

version:
python 3.6
theano 1.0.4
tensorflow 2.0.0

**Comment by SuryanarayanaY** [comment]
Hi @cheyennee ,

Theano is not a supported backend in Keras3. Keras3 supports tensorflow, torch,Jax and Numpy only.
