### ISSUE TITLE
layers.Discretization does not support input shape of rank > 2 [JAX Backend]

### ISSUE THREAD

**Issue by ixig** [keras-team/keras#18995]
The [docs](https://keras.io/api/layers/preprocessing_layers/numerical/discretization/) state that Input shape can be "Any array of dimension 2 or higher". However, an exception is raised if `output_mode='one_hot'` and the input rank is > 2.
```
>>> discret = layers.Discretization([1.0, 2.0, 3.0], output_mode='one_hot')
>>> discret(np.ones((2,3,4)))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    discret(np.ones((2,3,4))).shape
  File "/opt/homebrew/lib/python3.10/site-packages/keras/src/layers/preprocessing/tf_data_layer.py", line 46, in __call__
    return super().__call__(inputs, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 123, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/opt/homebrew/lib/python3.10/site-packages/keras/src/utils/numerical_utils.py", line 133, in encode_categorical_inputs
    f"which would result in output rank {inputs.shape.rank}."
AttributeError: Exception encountered when calling Discretization.call().
'tuple' object has no attribute 'rank'
```
1. The shape check in `numerical_utils.py:128` raises a ValueError with an explanatory message, but that message is not displayed because it references `{inputs.shape.rank}` which throw another exception.
2. Since [ops.one_hot()](https://keras.io/api/ops/nn/#onehot-function)'s input shape "can be arbitrary", is the limitation really necessary?

**Comment by dugujiujian1999** [comment]
Correct! 
After removing the limitation, the outcome is as follows: (torch backend)
```
tensor([[[[0., 1., 0., 0.],
          [0., 1., 0., 0.],
          [0., 1., 0., 0.],
          [0., 1., 0., 0.]],

         [[0., 1., 0., 0.],
          [0., 1., 0., 0.],
          [0., 1., 0., 0.],
          [0., 1., 0., 0.]],

         [[0., 1., 0., 0.],
          [0., 1., 0., 0.],
          [0., 1., 0., 0.],
          [0., 1., 0., 0.]]],


        [[[0., 1., 0., 0.],
          [0., 1., 0., 0.],
          [0., 1., 0., 0.],
          [0., 1., 0., 0.]],

         [[0., 1., 0., 0.],
          [0., 1., 0., 0.],
          [0., 1., 0., 0.],
          [0., 1., 0., 0.]],

         [[0., 1., 0., 0.],
          [0., 1., 0., 0.],
          [0., 1., 0., 0.],
          [0., 1., 0., 0.]]]])
```

**Comment by mattdangerw** [comment]
Yes thanks! Right on both counts.

We should use `len(ops.shape(...))` instead of `inputs.shape.rank` when raising the error.

It would be great to remove the rank 2 limitation. I believe the limitation was there in Keras 2 just because of the tf bincount functions we were using, but as long as the `keras.ops` we care about handle higher ranks it is fine to add. We should make sure to test all output modes (`count`, `one_hot`, `multi_hot`) against all backends. It's possible we will need some workarounds for the ops layer on the TensorFlow backend if the rank two limitation still exist for some TensorFlow functions we are using.

This is open for contributions if anyone would like to take it on.

**Comment by dugujiujian1999** [comment]
I am sorry for referencing your issue multiple times.  It appears that GitHub retains it even after rebasing.
