### ISSUE TITLE
[Tensorflow] jit_compile failed with tf.distribute

### ISSUE THREAD

**Issue by qlzh727** [keras-team/keras#19005]
When using `jit_compile=True` with tf.distribute strategies, the `model.fit` failed with following error messages. It seems that there are some variable placement issue. So far we have disable the jit_compile when running with tf distribution strategy in https://github.com/keras-team/keras/commit/791bda8ed798f2d3232e5d19bce57439526dda19

```
iterator = <tensorflow.python.distribute.input_lib.DistributedIterator object at 0x1445c5840>

    @tf.autograph.experimental.do_not_convert
    def one_step_on_iterator(iterator):
        """Runs a single training step given a Dataset iterator."""
        data = next(iterator)
>       outputs = self.distribute_strategy.run(
            one_step_on_data, args=(data,)
        )
E       tensorflow.python.framework.errors_impl.UnimplementedError: We failed to lift variable creations out of this tf.function, so this tf.function cannot be run on XLA. A possible workaround is to move variable creation outside of the XLA compiled function.

keras/backend/tensorflow/trainer.py:117: UnimplementedError
```

**Comment by qlzh727** [comment]
Based on the error message we got from tf.function, all the unlifted variable creation are from the optimizer and the learning rate scheduler. I think we are missing the tf.init_scope() for all the variable creation of tf based optimizer.

```
['[loss_scale_optimizer/step_counter:0](https://cs.corp.google.com/piper///depot/google3/loss_scale_optimizer/step_counter?ws=scottzhu/9496&snapshot=324)', '[loss_scale_optimizer/step_counter/replica_1:0](https://cs.corp.google.com/piper///depot/google3/loss_scale_optimizer/step_counter/replica_1?ws=scottzhu/9496&snapshot=324)', '[loss_scale_optimizer/dynamic_scale:0](https://cs.corp.google.com/piper///depot/google3/loss_scale_optimizer/dynamic_scale?ws=scottzhu/9496&snapshot=324)', '[loss_scale_optimizer/dynamic_scale/replica_1:0](https://cs.corp.google.com/piper///depot/google3/loss_scale_optimizer/dynamic_scale/replica_1?ws=scottzhu/9496&snapshot=324)', '[loss_scale_optimizer/SGD/dense_kernel_momentum:0](https://cs.corp.google.com/piper///depot/google3/loss_scale_optimizer/SGD/dense_kernel_momentum?ws=scottzhu/9496&snapshot=324)', '[loss_scale_optimizer/SGD/dense_kernel_momentum/replica_1:0](https://cs.corp.google.com/piper///depot/google3/loss_scale_optimizer/SGD/dense_kernel_momentum/replica_1?ws=scottzhu/9496&snapshot=324)', '[loss_scale_optimizer/SGD_1/dense_bias_momentum:0](https://cs.corp.google.com/piper///depot/google3/loss_scale_optimizer/SGD_1/dense_bias_momentum?ws=scottzhu/9496&snapshot=324)', '[loss_scale_optimizer/SGD_1/dense_bias_momentum/replica_1:0](https://cs.corp.google.com/piper///depot/google3/loss_scale_optimizer/SGD_1/dense_bias_momentum/replica_1?ws=scottzhu/9496&snapshot=324)', '[loss_scale_optimizer/SGD_2/dense_1_kernel_momentum:0](https://cs.corp.google.com/piper///depot/google3/loss_scale_optimizer/SGD_2/dense_1_kernel_momentum?ws=scottzhu/9496&snapshot=324)', '[loss_scale_optimizer/SGD_2/dense_1_kernel_momentum/replica_1:0](https://cs.corp.google.com/piper///depot/google3/loss_scale_optimizer/SGD_2/dense_1_kernel_momentum/replica_1?ws=scottzhu/9496&snapshot=324)', '[loss_scale_optimizer/SGD_3/dense_1_bias_momentum:0](https://cs.corp.google.com/piper///depot/google3/loss_scale_optimizer/SGD_3/dense_1_bias_momentum?ws=scottzhu/9496&snapshot=324)', '[loss_scale_optimizer/SGD_3/dense_1_bias_momentum/replica_1:0](https://cs.corp.google.com/piper///depot/google3/loss_scale_optimizer/SGD_3/dense_1_bias_momentum/replica_1?ws=scottzhu/9496&snapshot=324)', '[loss_scale_optimizer/SGD_4/dense_2_kernel_momentum:0](https://cs.corp.google.com/piper///depot/google3/loss_scale_optimizer/SGD_4/dense_2_kernel_momentum?ws=scottzhu/9496&snapshot=324)', '[loss_scale_optimizer/SGD_4/dense_2_kernel_momentum/replica_1:0](https://cs.corp.google.com/piper///depot/google3/loss_scale_optimizer/SGD_4/dense_2_kernel_momentum/replica_1?ws=scottzhu/9496&snapshot=324)', '[loss_scale_optimizer/SGD_5/dense_2_bias_momentum:0](https://cs.corp.google.com/piper///depot/google3/loss_scale_optimizer/SGD_5/dense_2_bias_momentum?ws=scottzhu/9496&snapshot=324)', '[loss_scale_optimizer/SGD_5/dense_2_bias_momentum/replica_1:0](https://cs.corp.google.com/piper///depot/google3/loss_scale_optimizer/SGD_5/dense_2_bias_momentum/replica_1?ws=scottzhu/9496&snapshot=324)', '[loss_scale_optimizer/SGD_6/batch_normalization_gamma_momentum:0](https://cs.corp.google.com/piper///depot/google3/loss_scale_optimizer/SGD_6/batch_normalization_gamma_momentum?ws=scottzhu/9496&snapshot=324)', '[loss_scale_optimizer/SGD_6/batch_normalization_gamma_momentum/replica_1:0](https://cs.corp.google.com/piper///depot/google3/loss_scale_optimizer/SGD_6/batch_normalization_gamma_momentum/replica_1?ws=scottzhu/9496&snapshot=324)', '[loss_scale_optimizer/SGD_7/batch_normalization_beta_momentum:0](https://cs.corp.google.com/piper///depot/google3/loss_scale_optimizer/SGD_7/batch_normalization_beta_momentum?ws=scottzhu/9496&snapshot=324)', '[loss_scale_optimizer/SGD_7/batch_normalization_beta_momentum/replica_1:0](https://cs.corp.google.com/piper///depot/google3/loss_scale_optimizer/SGD_7/batch_normalization_beta_momentum/replica_1?ws=scottzhu/9496&snapshot=324)', '[loss_scale_optimizer/SGD_8/dense_3_kernel_momentum:0](https://cs.corp.google.com/piper///depot/google3/loss_scale_optimizer/SGD_8/dense_3_kernel_momentum?ws=scottzhu/9496&snapshot=324)', '[loss_scale_optimizer/SGD_8/dense_3_kernel_momentum/replica_1:0](https://cs.corp.google.com/piper///depot/google3/loss_scale_optimizer/SGD_8/dense_3_kernel_momentum/replica_1?ws=scottzhu/9496&snapshot=324)', '[loss_scale_optimizer/SGD_9/dense_3_bias_momentum:0](https://cs.corp.google.com/piper///depot/google3/loss_scale_optimizer/SGD_9/dense_3_bias_momentum?ws=scottzhu/9496&snapshot=324)', '[loss_scale_optimizer/SGD_9/dense_3_bias_momentum/replica_1:0](https://cs.corp.google.com/piper///depot/google3/loss_scale_optimizer/SGD_9/dense_3_bias_momentum/replica_1?ws=scottzhu/9496&snapshot=324)']
```

**Comment by qlzh727** [comment]
With #19006, I am error like below. This is bit weird since my same change in g3 (cl/594812271) are passing correctly. Need to dig more and see why we have a behavior difference between g3 and OSS.

```
2024-01-01 00:13:47.061736: W tensorflow/core/framework/dataset.cc:959] Input of GeneratorDatasetOp::Dataset will not be optimized because the dataset does not implement the AsGraphDefInternal() method needed to apply optimizations.
2024-01-01 00:13:48.240597: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at xla_ops.cc:514 : INVALID_ARGUMENT: Trying to access resource dense/kernel/replica_1/3 (defined @ /home/runner/work/keras/keras/keras/backend/tensorflow/core.py:31) located in device /job:localhost/replica:0/task:0/device:CPU:1 from device /job:localhost/replica:0/task:0/device:CPU:0
 Cf. https://www.tensorflow.org/xla/known_issues#tfvariable_on_a_different_device
2024-01-01 00:13:48.240647: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: INVALID_ARGUMENT: Trying to access resource dense/kernel/replica_1/3 (defined @ /home/runner/work/keras/keras/keras/backend/tensorflow/core.py:31) located in device /job:localhost/replica:0/task:0/device:CPU:1 from device /job:localhost/replica:0/task:0/device:CPU:0
 Cf. https://www.tensorflow.org/xla/known_issues#tfvariable_on_a_different_device
	 [[{{node StatefulPartitionedCall}}]]
Traceback (most recent call last):
  File "/home/runner/work/keras/keras/integration_tests/tf_distribute_training_test.py", line 77, in <module>
    test_model_fit()
  File "/home/runner/work/keras/keras/integration_tests/tf_distribute_training_test.py", line 54, in test_model_fit
    history = model.fit(
  File "/home/runner/work/keras/keras/keras/utils/traceback_utils.py", line 123, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node StatefulPartitionedCall defined at (most recent call last):
  File "/home/runner/work/keras/keras/integration_tests/tf_distribute_training_test.py", line 77, in <module>

  File "/home/runner/work/keras/keras/integration_tests/tf_distribute_training_test.py", line 54, in test_model_fit

  File "/home/runner/work/keras/keras/keras/utils/traceback_utils.py", line 118, in error_handler

  File "/home/runner/work/keras/keras/keras/backend/tensorflow/trainer.py", line 323, in fit

  File "/home/runner/work/keras/keras/keras/backend/tensorflow/trainer.py", line 117, in one_step_on_iterator

Trying to access resource dense/kernel/replica_1/3 (defined @ /home/runner/work/keras/keras/keras/backend/tensorflow/core.py:31) located in device /job:localhost/replica:0/task:0/device:CPU:1 from device /job:localhost/replica:0/task:0/device:CPU:0
 Cf. https://www.tensorflow.org/xla/known_issues#tfvariable_on_a_different_device
	 [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_iterator_2[53](https://github.com/keras-team/keras/actions/runs/7373481912/job/20062739282?pr=19006#step:11:54)2]
Error: Process completed with exit code 1.
```

**Comment by qlzh727** [comment]
It seems that there is a long standing issue for XLA + distribution since https://github.com/tensorflow/tensorflow/issues/53140, and it seems to be a distribution issue for device placement. For now, let's disable the XLA when using distribution.
