### ISSUE TITLE
Error with keras.random torch backend

### ISSUE THREAD

**Issue by sunilkmaurya** [keras-team/keras#19053]
Keras version: 3.0.2
Following code works ok with tensorflow and jax backend, but the torch backend gives an error.
```
import keras
import keras.ops as ops
shape_a = ops.convert_to_tensor([2,3])
a = keras.random.uniform(shape=shape_a, minval=0.0, maxval=1.0)
print(a)
```
Error is as follows

```
Traceback (most recent call last):
  File "/home/sunil/Documents/code/error_reproduce/test.py", line 7, in <module>
    a = keras.random.uniform(shape=shape_a, minval=0.0, maxval=1.0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sunil/miniconda3/envs/keras_torch/lib/python3.11/site-packages/keras/src/random/random.py", line 111, in uniform
    return backend.random.uniform(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sunil/miniconda3/envs/keras_torch/lib/python3.11/site-packages/keras/src/backend/torch/random.py", line 78, in uniform
    rand_tensor = torch.rand(
                  ^^^^^^^^^^^
TypeError: rand() received an invalid combination of arguments - got (device=str, dtype=torch.dtype, generator=torch._C.Generator, size=Tensor, ), but expected one of:
 * (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
```

The error goes away when using ```shape_a = [2,3]```. Similar error also occurs with ```keras.random.normal```. I have not checked other available random operations.
Thanks for the help.

**Comment by nkovela1** [comment]
Hi @sunilkmaurya , this API requires a tuple of ints for the shape, as shown in the error trace. Please try this instead of passing a Torch tensor. Thanks!

**Comment by sunilkmaurya** [comment]
Thanks for the reply. I will be using list/tuple of integers to define the shape. However, I have encountered cases where the shape is calculated based on a previous operation that results in a tensor. I had raised the issue as the behavior is not consistent for keras.random for all backends. If no further action is planned/needed, the issue can be closed. Thanks.
