### ISSUE TITLE
dataloader issue in "Text classification from scratch": Invalid dtype: object

### ISSUE THREAD

**Issue by rbelew** [keras-team/keras#19251]
Starting with the basic [Text classification from scratch](https://keras.io/examples/nlp/text_classification_from_scratch/) 

[keras issue#18468, converting examples ](https://github.com/keras-team/keras/issues/18468) shows this example as having been converted from keras2->keras3

It all runs fine, until `end_to_end_model.evaluate(raw_test_ds)`  bumps into some dataloader issue?

> 
> Traceback (most recent call last):
> File ".../torch-kerasNLP.py", line 190, in <module>
> main()
> File ".../torch-kerasNLP.py", line 187, in main
> end_to_end_model.evaluate(raw_test_ds)
> File ".../keras/src/utils/traceback_utils.py", line 123, in error_handler
> raise e.with_traceback(filtered_tb) from None
> File ".../torch/utils/data/dataloader.py", line 631, in __next__
> data = self._next_data()
> ^^^^^^^^^^^^^^^^^
> File ".../torch/utils/data/dataloader.py", line 675, in _next_data
> data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File ".../torch/utils/data/_utils/fetch.py", line 41, in fetch
> data = next(self.dataset_iter)
> ^^^^^^^^^^^^^^^^^^^^^^^
> File ".../tree/__init__.py", line 435, in map_structure
> [func(*args) for args in zip(*map(flatten, structures))])
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File ".../tree/__init__.py", line 435, in <listcomp>
> [func(*args) for args in zip(*map(flatten, structures))])
> ^^^^^^^^^^^
> ValueError: Invalid dtype: object

**Comment by sachinprasadhs** [comment]
Hi, Thanks for reporting the issue.
I was able to run the example without any issues, make sure you upgrade the Keras version to the latest.

Here is the working Gist [![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.sandbox.google.com/gist/sachinprasadhs/c745cee5440c8d97d7f0eedaf2eb7a67/text_classification_from_scratch.ipynb) for reference.
