### ISSUE TITLE
How to install Keras on arm architecture with only pytorch installed(without tensorflow or jax)

### ISSUE THREAD

**Issue by baominghelly** [keras-team/keras#19253]
Hi,

I'd like to install Keras 3.0 on ARM architecture machine with only pytorch installed. I use comand of `Local installation` with some small changes in `requirements.txt`  and set `export KERAS_BACKEND="torch"` but I get the following issue:
```
[root@ares keras]# python pip_build.py --install
Generating files for package 'keras' from sources found in 'keras/src'.
Traceback (most recent call last):
  File "pip_build.py", line 196, in build
    run_namex_conversion()
  File "pip_build.py", line 58, in run_namex_conversion
    namex.generate_api_files(package, code_directory="src", verbose=True)
  File "/root/archiconda3/envs/python38_torch201/lib/python3.8/site-packages/namex/generate.py", line 65, in generate_api_files
    mod = importlib.import_module(entry_point, package=".")
  File "/root/archiconda3/envs/python38_torch201/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/workspace/workplace/keras/tmp_build_dir/keras/src/backend/numpy/__init__.py", line 2, in <module>
    from keras.src.backend.numpy import image
  File "/root/archiconda3/envs/python38_torch201/lib/python3.8/site-packages/xpytorch_import_hook.py", line 45, in _custom_import
    module = builtins.__origin__import__(
  File "/workspace/workplace/keras/tmp_build_dir/keras/src/backend/numpy/image.py", line 1, in <module>
    import jax
  File "/root/archiconda3/envs/python38_torch201/lib/python3.8/site-packages/xpytorch_import_hook.py", line 45, in _custom_import
    module = builtins.__origin__import__(
ModuleNotFoundError: No module named 'jax'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pip_build.py", line 231, in <module>
    whl_path = build(root_path, args.nightly, args.rc)
  File "pip_build.py", line 204, in build
    shutil.rmtree(build_directory)
  File "/root/archiconda3/envs/python38_torch201/lib/python3.8/shutil.py", line 709, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/root/archiconda3/envs/python38_torch201/lib/python3.8/shutil.py", line 707, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: 'tmp_build_dir'

```

Seems that the issue is caused by no jax installed. If I only use pytorch, how could I skip tensorflow and jax with Keras installed? Any help will be appreciated!

**Comment by fchollet** [comment]
To build Keras from sources, you need all dependencies. But for running Keras, you only need the backend you will use. The solution is use an existing build, e.g. from `pip`. Keras is a pure Python package so the "build" is really just a set of Python file.

Basically: just use `pip install keras` or conda.

**Comment by baominghelly** [comment]
Thanks for your response!!

I know basically I should use pip or conda, but I can't get Keras 3.0 from pip or conda because my python version is 3.8.
I can't upgrade python version, because my AI accelerator only support pytorch on python 3.8, not on python3.9, if I change python version, pytorch is not supported after the change.

So I'd like to change Keras source code and build from source code to make keras work in my machine, do you think it's possible?
If it's possible, which part of source code should I change generallty?

**Comment by sampathweb** [comment]
You can try clonign Keras Repo from GitHub.  Update the setup.py to say `>=3.8` - https://github.com/keras-team/keras/blob/master/setup.py#L51

Then run, `python pip_build.py --install`.  Make sure you have `virtualenv` installed in the python env.

**Comment by sampathweb** [comment]
Please reopen the issue if this doesn't resolve the issue.

**Comment by baominghelly** [comment]
Thanks, I think I still need other change in Keras Repo, because I can't install tensorflow nor jax in my machine, I run `python pip_build.py --install` will encounter tensorflow or jax not installed issue. Please refer the error log in my first comment. 

Do you have any idea about where I still need to change? Just general idea is enough!

**Comment by baominghelly** [comment]
Please help reopen this issue, I can't reopen it myself.

**Comment by sampathweb** [comment]
Would you be able to install Python 3.9 on your ARM device? Or use `miniconda` to create a Python 3.9 env? These issues would go away if you use Python 3.9 and you could just use pip install for everything without having to build.

Python 3.8 EoL is coming soon - https://devguide.python.org/versions/ and many packages incl, Numpy and others have dropped it a while back.
