### ISSUE TITLE
The errors that may occur when using LoRA on the JAX backend.

### ISSUE THREAD

**Issue by pass-lin** [keras-team/keras#19325]
code is
```python
 import os
os.environ["KERAS_BACKEND"] = "jax"
import keras

x = keras.layers.Input([None])
z = keras.layers.Embedding(32128,16)(x)
z = keras.layers.Dense(16)(z)
y = keras.layers.Dense(16)(z)
model = keras.Model(x,y)
model.summary()
for t in model.layers[1:]:
    t.enable_lora(True)

```

find a error 

```python
Traceback (most recent call last):
  File "/home/xby00008312/train_misaka/test_jax_lora.py", line 12, in <module>
    t.enable_lora(True)
  File "/home/xby00008312/miniconda3/envs/keras-jax/lib/python3.10/site-packages/keras/src/layers/core/embedding.py", line 147, in enable_lora
    self.lora_embeddings_a = self.add_weight(
  File "/home/xby00008312/miniconda3/envs/keras-jax/lib/python3.10/site-packages/keras/src/layers/layer.py", line 499, in add_weight
    variable = backend.Variable(
  File "/home/xby00008312/miniconda3/envs/keras-jax/lib/python3.10/site-packages/keras/src/backend/common/variables.py", line 74, in __init__
    shape = self._validate_shape(shape)
  File "/home/xby00008312/miniconda3/envs/keras-jax/lib/python3.10/site-packages/keras/src/backend/common/variables.py", line 97, in _validate_shape
    shape = standardize_shape(shape)
  File "/home/xby00008312/miniconda3/envs/keras-jax/lib/python3.10/site-packages/keras/src/backend/common/variables.py", line 426, in standardize_shape
    raise ValueError(
ValueError: Cannot convert '(32128, True)' to a shape. Found invalid entry 'True' of type '<class 'bool'>'.

```

**Comment by sachinprasadhs** [comment]
Hi, 


You need to pass `rank` to the `enable_lora` function instead of passing boolean. 

```
def enable_lora(
        self, rank, a_initializer="he_uniform", b_initializer="zeros"
    ):
```
