### ISSUE TITLE
IndexError when loading a model with shared sub-models

### ISSUE THREAD

**Issue by torzdf** [keras-team/keras#19326]
Keras Version: 3.0.5 (PyPi latest)

When loading a model with 2 inputs and 3 sub-models (1 shared between 2 inputs, then 2 separate models to process each output from the shared model),, an IndexError is raised.

The model compiles, trains and saves fine, but the issue comes when trying to load the model back in.

The error occurs with both legacy `.h5` format and new `.keras` format.

This kind of structure works in Keras 2.

Reproducible example (and [gist](https://colab.research.google.com/drive/1dEoNnBQTUR-UwLhbQySrDLfiZG8LUcfg?usp=sharing)):

```py
from keras import Input, Model
from keras.models import load_model
from keras.layers import Dense

def shared():
    """ Shared model """
    inputs = Input(shape=(64, ))
    outputs = Dense(32)((inputs))
    return Model(inputs, outputs=outputs)


def split():
    """ Seperate models """
    inputs  = Input(shape=(32, ))
    outputs = Dense(32)(inputs)
    return Model(inputs, outputs=outputs)


# Bring them together
inputs = [Input((64, )), Input((64, ))]

shared_model = shared()  # Single instance of the shared model
shared_a = shared_model(inputs[0])
shared_b = shared_model(inputs[1])

out_a = split()(shared_a)  # instance 1 of the split model
out_b = split()(shared_b)  # instance 2 of the split model

# Full model
model = Model(inputs, outputs=[out_a, out_b])

print(model.summary())
model.save("test.keras")
test = load_model("test.keras")  # Fails with index out of range error
```

Model summary:

```
Model: "functional_7"
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                  ┃ Output Shape              ┃         Param # ┃ Connected to               ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)      │ (None, 64)                │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ input_layer_1 (InputLayer)    │ (None, 64)                │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ functional_1 (Functional)     │ (None, 32)                │           2,080 │ input_layer[0][0],         │
│                               │                           │                 │ input_layer_1[0][0]        │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ functional_3 (Functional)     │ (None, 32)                │           1,056 │ functional_1[0][0]         │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ functional_5 (Functional)     │ (None, 32)                │           1,056 │ functional_1[1][0]         │
└───────────────────────────────┴───────────────────────────┴─────────────────┴────────────────────────────┘
 Total params: 4,192 (16.38 KB)
 Trainable params: 4,192 (16.38 KB)
 Non-trainable params: 0 (0.00 B)
```

Error output:
```
Traceback (most recent call last):
  File "/project/model_bug.py", line 34, in <module>
    test = load_model("test.keras")  # Fails with index out of range error
  File "/env/lib/python3.10/site-packages/keras/src/saving/saving_api.py", line 176, in load_model
    return saving_lib.load_model(
  File "/env/lib/python3.10/site-packages/keras/src/saving/saving_lib.py", line 155, in load_model
    model = deserialize_keras_object(
  File "/env/lib/python3.10/site-packages/keras/src/saving/serialization_lib.py", line 711, in deserialize_keras_object
    instance = cls.from_config(inner_config)
  File "/env/lib/python3.10/site-packages/keras/src/models/model.py", line 492, in from_config
    return functional_from_config(
  File "/env/lib/python3.10/site-packages/keras/src/models/functional.py", line 555, in functional_from_config
    output_tensors = map_tensors(config["output_layers"])
  File "/env/lib/python3.10/site-packages/keras/src/models/functional.py", line 552, in map_tensors
    return [get_tensor(*v) for v in tensors]
  File "/env/lib/python3.10/site-packages/keras/src/models/functional.py", line 552, in <listcomp>
    return [get_tensor(*v) for v in tensors]
  File "/env/lib/python3.10/site-packages/keras/src/models/functional.py", line 545, in get_tensor
    layer_output_tensors = layer._inbound_nodes[node_index].output_tensors
IndexError: list index out of range
```

**Comment by SuryanarayanaY** [comment]
Hi @torzdf ,

I have replicated the issue with Keras3 and keras2 works fine. Attached reference [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/f47f0b604ea8bc9da804b1f7fd900ed4/19326.ipynb).
