### ISSUE TITLE
Keras deserialization Object  Error -  from keras.saving.legacy.serialization import deserialize_keras_object ImportError: cannot import name 'deserialize_keras_object' from 

### ISSUE THREAD

**Issue by akramIOT** [keras-team/keras#19426]
(DS) akram_personal@AKRAMs-MacBook-Pro DS_2024 % 
(DS) akram_personal@AKRAMs-MacBook-Pro DS_2024 % python -V
Python 3.11.5
(DS) akram_personal@AKRAMs-MacBook-Pro DS_2024 % 
(DS) akram_personal@AKRAMs-MacBook-Pro DS_2024 % 
(DS) akram_personal@AKRAMs-MacBook-Pro DS_2024 % 
(DS) akram_personal@AKRAMs-MacBook-Pro DS_2024 % pip list | grep keras
keras                        2.12.0
(DS) akram_personal@AKRAMs-MacBook-Pro DS_2024 % 
(DS) akram_personal@AKRAMs-MacBook-Pro DS_2024 % pip list | grep tensor
tensorboard                  2.16.2
tensorboard-data-server      0.7.0
tensorboard-plugin-wit       1.8.1
tensorflow                   2.12.0
tensorflow-datasets          4.9.4
tensorflow-estimator         2.12.0
tensorflow-io-gcs-filesystem 0.36.0
tensorflow-metadata          1.14.0
(DS) akram_personal@AKRAMs-MacBook-Pro DS_2024 % 

(DS) akram_personal@AKRAMs-MacBook-Pro DS_2024 % python CNN_WordVec.py             
Traceback (most recent call last):
  File "/Users/akram_personal/AKRAM_CODE_FOLDER/DS_EXERCISES/DS_2024/CNN_WordVec.py", line 8, in <module>
    from tensorflow.keras.preprocessing.text import Tokenizer
  File "/opt/anaconda3/envs/DS/lib/python3.11/site-packages/keras/api/_v2/keras/__init__.py", line 12, in <module>
    from keras import __version__
  File "/opt/anaconda3/envs/DS/lib/python3.11/site-packages/keras/__init__.py", line 21, in <module>
    from keras import models
  File "/opt/anaconda3/envs/DS/lib/python3.11/site-packages/keras/models/__init__.py", line 18, in <module>
    from keras.engine.functional import Functional
  File "/opt/anaconda3/envs/DS/lib/python3.11/site-packages/keras/engine/functional.py", line 27, in <module>
    from keras.dtensor import layout_map as layout_map_lib
  File "/opt/anaconda3/envs/DS/lib/python3.11/site-packages/keras/dtensor/layout_map.py", line 27, in <module>
    from keras.engine import base_layer
  File "/opt/anaconda3/envs/DS/lib/python3.11/site-packages/keras/engine/base_layer.py", line 33, in <module>
    from keras import initializers
  File "/opt/anaconda3/envs/DS/lib/python3.11/site-packages/keras/initializers/__init__.py", line 23, in <module>
    from keras.saving.legacy import serialization as legacy_serialization
  File "/opt/anaconda3/envs/DS/lib/python3.11/site-packages/keras/saving/legacy/serialization.py", line 22, in <module>
    from keras.utils import tf_contextlib
  File "/opt/anaconda3/envs/DS/lib/python3.11/site-packages/keras/utils/__init__.py", line 20, in <module>
    from keras.saving.legacy.serialization import deserialize_keras_object
ImportError: cannot import name 'deserialize_keras_object' from partially initialized module 'keras.saving.legacy.serialization' (most likely due to a circular import) (/opt/anaconda3/envs/DS/lib/python3.11/site-packages/keras/saving/legacy/serialization.py)

===================== PFA  the Code for this example =========
import pandas as pd
import numpy as np
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from gensim.models import Word2Vec
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding, Conv1D, MaxPooling1D, Flatten, Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split

# Load the data
data = pd.read_csv('movie_reviews.csv')
X_train, X_test, y_train, y_test = train_test_split(data['review'], data['sentiment'], test_size=0.2, random_state=42)

# Preprocess the text data
stop_words = set(stopwords.words('english'))
def preprocess(text):
    text = text.lower()
    text = ''.join([word for word in text if word not in string.punctuation])
    tokens = word_tokenize(text)
    tokens = [word for word in tokens if word not in stop_words]
    return ' '.join(tokens)

X_train = X_train.apply(preprocess)
X_test = X_test.apply(preprocess)

# Tokenize the text data
tokenizer = Tokenizer()
tokenizer.fit_on_texts(X_train)

X_train = tokenizer.texts_to_sequences(X_train)
X_test = tokenizer.texts_to_sequences(X_test)

vocab_size = len(tokenizer.word_index) + 1

# Pad the sequences to a fixed length
max_length = 100
X_train = pad_sequences(X_train, maxlen=max_length, padding='post')
X_test = pad_sequences(X_test, maxlen=max_length, padding='post')

# Train the Word2Vec model
sentences = [sentence.split() for sentence in X_train]
w2v_model = Word2Vec(sentences, size=100, window=5, min_count=5, workers=4)

# Create a weight matrix for the embedding layer
embedding_matrix = np.zeros((vocab_size, 100))
for word, i in tokenizer.word_index.items():
    if word in w2v_model.wv:
        embedding_matrix[i] = w2v_model.wv[word]

# Define the CNN model
model = Sequential()
model.add(Embedding(vocab_size, 100, weights=[embedding_matrix], input_length=max_length, trainable=False))
model.add(Conv1D(128, 5, activation='relu'))
model.add(MaxPooling1D(5))
model.add(Conv1D(128, 5, activation='relu'))
model.add(MaxPooling1D(5))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

**Comment by SuryanarayanaY** [comment]
Hi @akramIOT ,

It seems you are using Keras 2.12 version. Could you test with latest keras and update ?

**Comment by akramIOT** [comment]
@SuryanarayanaY : Did that and now the Tokenizer error . Is this upgraded keras version compatible with the  Tensorflow version  below  ?

(DS) akram_personal@AKRAMs-MacBook-Pro DS_2024 % python CNN_WordVec.py
Traceback (most recent call last):
  File "/Users/akram_personal/AKRAM_CODE_FOLDER/DS_EXERCISES/DS_2024/CNN_WordVec.py", line 33, in <module>
    tokenizer = Tokenizer()
                ^^^^^^^^^
NameError: name 'Tokenizer' is not defined
(DS) akram_personal@AKRAMs-MacBook-Pro DS_2024 % 
(DS) akram_personal@AKRAMs-MacBook-Pro DS_2024 % 
(DS) akram_personal@AKRAMs-MacBook-Pro DS_2024 % 
(DS) akram_personal@AKRAMs-MacBook-Pro DS_2024 % 
(DS) akram_personal@AKRAMs-MacBook-Pro DS_2024 % python CNN_WordVec.py
Traceback (most recent call last):
  File "/Users/akram_personal/AKRAM_CODE_FOLDER/DS_EXERCISES/DS_2024/CNN_WordVec.py", line 10, in <module>
    from tensorflow.keras.preprocessing.text import Tokenizer
ModuleNotFoundError: No module named 'tensorflow.keras'
(DS) akram_personal@AKRAMs-MacBook-Pro DS_2024 % 
(DS) akram_personal@AKRAMs-MacBook-Pro DS_2024 % pip list | grep tensorflow                      
tensorflow                   2.12.0
tensorflow-datasets          4.9.4
tensorflow-estimator         2.12.0
tensorflow-io-gcs-filesystem 0.36.0
tensorflow-metadata          1.14.0
(DS) akram_personal@AKRAMs-MacBook-Pro DS_2024 % 
(DS) akram_personal@AKRAMs-MacBook-Pro DS_2024 % pip list | grep keras     
keras                        3.1.1
(DS) akram_personal@AKRAMs-MacBook-Pro DS_2024 %

**Comment by akramIOT** [comment]
Followed this  Thread   https://discuss.tensorflow.org/t/modulenotfounderror-no-module-named-tensorflow-keras/21203   but still the  same issue

**Comment by SuryanarayanaY** [comment]
> @SuryanarayanaY : Did that and now the Tokenizer error . Is this upgraded keras version compatible with the Tensorflow version below ?

It seems you are using TF2.12v which is not compatible with Keras3.1.1. Please upgrade TF version to 2.16v.

With TF2.16 onwards tf.keras will be point to Keras3 which is not the case with TF<=2.15 versions.

**Comment by isheriff123** [comment]
@SuryanarayanaY : I am good for now. Close this case.

**Comment by dhantule** [comment]
Hi @akramIOT, thanks for reporting this. You can upgrade to keras 3 by using `!pip install -Uq keras `and try implementing your code. Please close this issue, if it won't reproduce anymore. Thanks!
