### ISSUE TITLE
cannot load fine-tuned model

### ISSUE THREAD

**Issue by lwind18** [keras-team/keras#19518]
I train the model from a scratch and name it as modelA. Then use the new training data to train this trained model (modelA). The training process looks good. Then when I load the model using tf.keras.models.load_model, I ran into this issue:
TypeError: Layer input_spec must be an instance of InputSpec. Got: <keras.initializers.initializers_v2.GlorotUniform object at 0x7f6c285f0130>
Does anyone can help me out with this issue? Where is wrong with this fine-tuned model? I remembered that I didn't use GlorotUniform when I built the model.
Thanks!

**Comment by SuryanarayanaY** [comment]
Hi @lwind18 ,

For me it seems the issue is with version mismatch. Could you please provide more details like on which Keras version earlier model was trained and which version you are trying to reload? Right now Keras3 designed to support multiple backends there might be design changes.

**Comment by lwind18** [comment]
The model trained with keras 2.6 an also tensorflow 2.6. Then I tried load this model under keras 2.6 and tensorflow 2.6, and  I tried 2.8, 2.9, 2.10, 2.11 and they ended with the same error. 
So you suggestion is to update keras and tensorflow to 2.13 or later, and train the model again. Then it shouldn't have this issue?

**Comment by SuryanarayanaY** [comment]
> The model trained with keras 2.6 an also tensorflow 2.6. Then I tried load this model under keras 2.6 and tensorflow 2.6, and I tried 2.8, 2.9, 2.10, 2.11 and they ended with the same error.

If you have trained and loading the model in same version then it should load without any error. If there are versions mismatches wrt training and reloading the model then such problem may arise.

Please double check your environment details while reloading the model its pointing to correct version of TF/Keras that the model trained. Please submit a minimal code snippet for reproduction.

**Comment by lwind18** [comment]
> > The model trained with keras 2.6 an also tensorflow 2.6. Then I tried load this model under keras 2.6 and tensorflow 2.6, and I tried 2.8, 2.9, 2.10, 2.11 and they ended with the same error.
> 
> If you have trained and loading the model in same version then it should load without any error. If there are versions mismatches wrt training and reloading the model then such problem may arise.
> 
> Please double check your environment details while reloading the model its pointing to correct version of TF/Keras that the model trained. Please submit a minimal code snippet for reproduction.

I used the newer tensorflow version (higher than v2.11) to train the model and load it. It gave me the same error.
Here is the snippet of code:
model_path = './trained_model.model'
traind_model = tf.keras.models.load_model(model_path, compile= False)
loss = myloss.multiclass_weighted_cross_entropy(num_classes, class_weights=weights,is_logits=True)
metrics = [tf.keras.metrics.SparseCategoricalAccuracy()] 
learning_rate = 0.0001
optimizer=tf.keras.optimizers.RMSprop(learning_rate=learning_rate, rho=momentum    )
model.compile(optimizer=optimizer, loss=loss, metrics=['accuracy'])
model_history = traind_model.fit(train_dataset, validation_data=validation_dataset, epochs=EPOCHS, verbose=2)                                     
model.save(model_name)
ERROR message:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./python/3.11/envs/rasteriobak/lib/python3.11/site-packages/keras/src/saving/saving_api.py", line 262, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./python/3.11/envs/rasteriobak/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "./python/3.11/envs/rasteriobak/lib/python3.11/site-packages/keras/src/engine/base_layer.py", line 1295, in input_spec
    raise TypeError(
TypeError: Layer input_spec must be an instance of InputSpec. Got: <keras.src.initializers.initializers.GlorotUniform object at 0x1553943ab610>
Thanks.

**Comment by dhantule** [comment]
Hi @lwind18, Thanks for reporting this. You can try upgrading to keras 3 using `!pip install -Uq keras ` and try saving the model with`.keras` extention. Please provide a sample model to reproduce. Thanks.

> model_path = './trained_model.model'
> traind_model = tf.keras.models.load_model(model_path, compile= False)
> loss = myloss.multiclass_weighted_cross_entropy(num_classes, class_weights=weights,is_logits=True)
> metrics = [tf.keras.metrics.SparseCategoricalAccuracy()]
> learning_rate = 0.0001
> optimizer=tf.keras.optimizers.RMSprop(learning_rate=learning_rate, rho=momentum )
> model.compile(optimizer=optimizer, loss=loss, metrics=['accuracy'])
> model_history = traind_model.fit(train_dataset, validation_data=validation_dataset, epochs=EPOCHS, verbose=2)
> model.save(model_name)

**Comment by kborsos** [comment]
Was there a solution found for this issue? I am facing the same problem: I load a model, retrain and then save the model but then cannot load the retrained model with the error `TypeError: Layer input_spec must be an instance of InputSpec. Got: <keras.initializers.initializers_v2.Zeros object at 0x7fdb152fa920>`. I am using TF 2.10, I've tried with 2.11 and 2.12 but face the same problem. In fact, I also have the same issue when I simply load and resave the model (ie. no retraining and no recompiling) for example:  

`model = tf.keras.models.load_model(old_model_path) # model loads fine`
`model.save_model(new_model_path)`
`new_model = tf.keras.models.load_model(new_model_path) # Error 
` 

My current workaround is to just save the weights (since for my purposes the architecture is unchanged) and then load the old model with the new weights but this is obviously not ideal. Any additional ideas would be appreciated, thanks!
