### ISSUE TITLE
Unknown reference at progbar.py

### ISSUE THREAD

**Issue by PiCoPress** [keras-team/keras#19795]
https://github.com/keras-team/keras/blob/26f438edd5516bf02504a5a0e13a20ceec69cb29/keras/src/utils/progbar.py#L162
https://github.com/keras-team/keras/blob/26f438edd5516bf02504a5a0e13a20ceec69cb29/keras/src/utils/progbar.py#L194

```py
...
>>> model.fit(xtr,ytr,epochs=5, batch_size=64, validation_data=(xte, yte))
Epoch 1/5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/progbar.py", line 162, in update
    avg = backend.convert_to_numpy(
AttributeError: module 'keras.src.backend' has no attribute 'convert_to_numpy'
>>> keras.__version__
'3.3.3'
```

**Comment by sachinprasadhs** [comment]
Could you please provide sample reproducible code to replicate the reported behavior. Thanks
