### ISSUE TITLE
keras-nightly: cannot import name '_tf_keras' from 'keras.api'

### ISSUE THREAD

**Issue by lutzroeder** [keras-team/keras#19875]
Repro steps:
```bash
~: pip install --upgrade keras-nightly
Requirement already satisfied: keras-nightly in ./.local/lib/python3.12/lib/python3.12/site-packages (3.3.3.dev2024061803)
~: pip install --upgrade tensorflow
Requirement already satisfied: tensorflow in ./.local/lib/python3.12/lib/python3.12/site-packages (2.16.1)
~: python
Python 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
>>> import keras
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.local/lib/python3.12/lib/python3.12/site-packages/keras/__init__.py", line 23, in <module>
    from keras.api import _tf_keras
ImportError: cannot import name '_tf_keras' from 'keras.api' (~/.local/lib/python3.12/lib/python3.12/site-packages/keras/api/__init__.py)
```

#19864

**Comment by fchollet** [comment]
I cannot reproduce; it's likely an environment conflict on your end. Try first uninstalling all `keras` / `tensorflow` packages:

```
pip uninstall keras keras-nightly tensorflow tf-nightly -y
```

**Comment by lutzroeder** [comment]
```
~: pip uninstall keras keras-nightly tensorflow tf-nightly -y
WARNING: Skipping keras as it is not installed.
WARNING: Skipping keras-nightly as it is not installed.
WARNING: Skipping tensorflow as it is not installed.
WARNING: Skipping tf-nightly as it is not installed.
~: pip install keras-nightly tf-nightly
Collecting keras-nightly
  Downloading keras_nightly-3.3.3.dev2024061803-py3-none-any.whl.metadata (5.8 kB)
Collecting tf-nightly
  Downloading tf_nightly-2.18.0.dev20240617-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
~: python
Python 3.12.3 [GCC 13.2.0] on linux
>>> import keras
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.local/lib/python3.12/lib/python3.12/site-packages/keras/__init__.py", line 23, in <module>
    from keras.api import _tf_keras
ImportError: cannot import name '_tf_keras' from 'keras.api' (/home/lutzroeder/.local/lib/python3.12/lib/python3.12/site-packages/keras/api/__init__.py)
```

**Comment by fchollet** [comment]
I can repro now, I think I was hitting a cache previously. Will fix it, it's a simple issue.
