### ISSUE TITLE
Bug in Keras 3.4.0: Loading model error 'No such file or directory: 'model.weights.h5'

### ISSUE THREAD

**Issue by WeichenXu123** [keras-team/keras#19921]
### Environment:

Ubuntu 22.04
Tensorflow 2.16.1
Keras 3.4.0

### Reproducing steps

(1) Create the following python script `tf-save.py` to generate model file:

```
import os.path

import pandas as pd
import numpy as np
from sklearn import datasets
from tensorflow.keras.layers import Concatenate, Dense, Input, Lambda
from tensorflow.keras.saving import register_keras_serializable
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.optimizers import SGD
import cloudpickle
import sys

save_path = sys.argv[1]

iris = datasets.load_iris()
data = pd.DataFrame(
    data=np.c_[iris["data"], iris["target"]], columns=iris["feature_names"] + ["target"]
)
y = data["target"]
x = data.drop("target", axis=1)

input_a = Input(shape=(2, 3), name="a")
input_b = Input(shape=(2, 5), name="b")


@register_keras_serializable(name="f2")
def f2(z):
    from tensorflow.keras import backend as K

    return K.mean(z, axis=2)


input_a_sum = Lambda(f2)(input_a)
input_b_sum = Lambda(f2)(input_b)

output = Dense(1)(Dense(3, input_dim=4)(Concatenate()([input_a_sum, input_b_sum])))
model = Model(inputs=[input_a, input_b], outputs=output)
model.compile(loss="mean_squared_error", optimizer=SGD())
model.fit(
    [
        np.repeat(x.values[:, :2, np.newaxis], 3, axis=2),
        np.repeat(x.values[:, -2:, np.newaxis], 5, axis=2),
    ],
    y,
)

from tensorflow.keras.saving import get_custom_objects

global_custom_objects = get_custom_objects()

with open(os.path.join(save_path, "global_custom_objects.cloudpickle"), "wb") as out_f:
    cloudpickle.dump(global_custom_objects, out_f)

model_file_path = f"{save_path}/model.keras"
model.save(model_file_path)

```
then run shell command:

```
python tf-save.py .
```

It generates the following files in current directory:

```
global_custom_objects.cloudpickle  model.keras  model.weights.h5
```
One strange thing is it shouldn't generate `model.weights.h5` file. We only save model weights to `model.keras` file

then create a `tf-load.py` file containing:
```
import os.path
import sys
import cloudpickle
import tensorflow.keras

model_path = sys.argv[1]

custom_obj_path = os.path.join(model_path, "global_custom_objects.cloudpickle")
with open(custom_obj_path, "rb") as f:
    custom_objects = cloudpickle.load(f)

model_file_path = os.path.join(model_path, "model.keras")
tensorflow.keras.models.load_model(model_file_path, custom_objects=custom_objects)
```

then create a bash script `run.sh` like:

```
python tf-load.py . &
python tf-load.py . &
python tf-load.py . &
python tf-load.py . &

wait
```

then execute shell command
```
. run.sh 
```

error occurs:
```
Traceback (most recent call last):
  File "/tmp/tfm2/tf-load.py", line 13, in <module>
    tensorflow.keras.models.load_model(model_file_path, custom_objects=custom_objects)
  File "/home/weichen.xu/miniconda3/envs/mlflow/lib/python3.9/site-packages/keras/src/saving/saving_api.py", line 182, in load_model
    return saving_lib.load_model(
  File "/home/weichen.xu/miniconda3/envs/mlflow/lib/python3.9/site-packages/keras/src/saving/saving_lib.py", line 229, in load_model
    return _load_model_from_fileobj(
  File "/home/weichen.xu/miniconda3/envs/mlflow/lib/python3.9/site-packages/keras/src/saving/saving_lib.py", line 353, in _load_model_from_fileobj
    weights_file_path.unlink()
  File "/home/weichen.xu/miniconda3/envs/mlflow/lib/python3.9/pathlib.py", line 1354, in unlink
    self._accessor.unlink(self)
FileNotFoundError: [Errno 2] No such file or directory: 'model.weights.h5'
```
and we found after executing `run.sh`, the `model.weights.h5` file is deleted.

**Comment by WeichenXu123** [comment]
We have confirmed this issue is not Tensorflow issue but bug introduced in Keras 3.4.0
https://github.com/tensorflow/tensorflow/issues/70273#issuecomment-2191371907

**Comment by WeichenXu123** [comment]
Our MLflow CI starting to fail since yesterday due to the same reason (becaus yesterday Keras 3.4.0 was released)
https://github.com/mlflow-automation/mlflow/actions/runs/9663216609/job/26667289602#step:12:4059

**Comment by sachinprasadhs** [comment]
Could you please try replicating the reported behavior with direct `Keras` usage to identify if the issue is from Keras.

**Comment by hugobettmach** [comment]
We faced the exact same error in our project, in our instance it happens when we try to load a tensorlfow model using `mlflow.tensorflow.load_model`. Below is the traceback:

```python
Traceback (most recent call last):
  File "/opt/miniconda/envs/test-env/lib/python3.11/site-packages/keras/src/saving/saving_lib.py", line 318, in _load_model_from_fileobj
    zf.extract(_VARS_FNAME_H5, working_dir)
  File "/opt/miniconda/envs/test-env/lib/python3.11/zipfile.py", line 1676, in extract
    return self._extract_member(member, path, pwd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda/envs/test-env/lib/python3.11/zipfile.py", line 1747, in _extract_member
    open(targetpath, "wb") as target:
    ^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/mnt/azureml/cr/j/a1496fd7cb8f4ca58fb4df4257aafda5/cap/data-capability/wd/INPUT_trained_model/data/model.weights.h5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/azureml/cr/j/a1496fd7cb8f4ca58fb4df4257aafda5/exe/wd/component.py", line 180, in <module>
    predict_component(
  File "/mnt/azureml/cr/j/a1496fd7cb8f4ca58fb4df4257aafda5/exe/wd/component.py", line 130, in predict_component
    model = mlflow.tensorflow.load_model(model_uri=trained_model)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda/envs/test-env/lib/python3.11/site-packages/mlflow/tensorflow/__init__.py", line 628, in load_model
    return _load_keras_model(
           ^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda/envs/test-env/lib/python3.11/site-packages/mlflow/tensorflow/__init__.py", line 562, in _load_keras_model
    return keras_models.load_model(model_path, custom_objects=custom_objects, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda/envs/test-env/lib/python3.11/site-packages/keras/src/saving/saving_api.py", line 182, in load_model
    return saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda/envs/test-env/lib/python3.11/site-packages/keras/src/saving/saving_lib.py", line 229, in load_model
    return _load_model_from_fileobj(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda/envs/test-env/lib/python3.11/site-packages/keras/src/saving/saving_lib.py", line 349, in _load_model_from_fileobj
    weights_store.close()
    ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'weights_store' where it is not associated with a value
```

**Comment by fchollet** [comment]
Thanks for the report. We'll do a 3.4.1 release to fix this today.

**Comment by WeichenXu123** [comment]
@fchollet The bug persists in Keras 3.4.1
We reran our CI with keras 3.4.1, but the same error https://github.com/mlflow/mlflow/actions/runs/9689225161/job/26737143702#step:12:5555
