### ISSUE TITLE
'Functional API' guide broken with Keras 3.4.1

### ISSUE THREAD

**Issue by t-kalinowski** [keras-team/keras#19951]
Instructions to reproduce (with latest Keras and TF already installed):

```bash
wget https://raw.githubusercontent.com/keras-team/keras-io/master/guides/functional_api.py
python function_api.py
```

outputs:
```python
<...omitted...>
Epoch 1/2
Traceback (most recent call last):
  File "/home/tomasz/github/rstudio/keras3/functional_api.py", line 413, in <module>
    model.fit(
  File "/home/tomasz/.virtualenvs/r-keras/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/tomasz/.virtualenvs/r-keras/lib/python3.11/site-packages/keras/src/layers/input_spec.py", line 227, in assert_input_compatibility
    raise ValueError(
ValueError: Exception encountered when calling Functional.call().

Input 0 of layer "priority" is incompatible with the layer: expected axis -1 of input shape to have value 172, but received input with shape (32, 170)

Arguments received by Functional.call():
  • inputs={'title': 'tf.Tensor(shape=(32, 10), dtype=int64)', 'body': 'tf.Tensor(shape=(32, 100), dtype=int64)', 'tags': 'tf.Tensor(shape=(32, 12), dtype=float32)'}
  • training=True
  • mask={'title': 'None', 'body': 'None', 'tags': 'None'}
```

**Comment by fchollet** [comment]
Thanks for the report. This is due to the code in the guide being incorrect/inconsistent. The latest version of Keras is stricter about input checks in this situation.

The `title` input is declared as shape `(None, 12)` but then data of shape `(batch_size, 10)` is provided. Will fix on keras.io.

**Comment by fchollet** [comment]
This is done.
