### ISSUE TITLE
A local file was found, but it seems to be incomplete or outdated because the auto file hash does not match the original value of ...

### ISSUE THREAD

**Issue by edge7Lux** [keras-team/keras#20271]
Hi,

using Keras 3.5 and just running the following:

```
import keras

keras.applications.ConvNeXtSmall(
    include_preprocessing=True,
    input_tensor=None,
    weights="imagenet",
    input_shape=(224, 320, 3),
    include_top=False,
    pooling=None,
    name="convnext_large",
).summary()
```
I get:

> A local file was found, but it seems to be incomplete or outdated because the auto file hash does not match the original value of 6fc8009faa2f00c1c1dfce59feea9b0745eb260a7dd11bee65c8e20843da6eab so we will re-download the data.
> Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/convnext/convnext_large_notop.h5
> 785596384/785596384 ━━━━━━━━━━━━━━━━━━━━ 19s 0us/step
> Traceback (most recent call last):
>   File "/home/edge7/Desktop/projects/ing_edurso/wharfree-net/main_test.py", line 3, in <module>
>     keras.applications.ConvNeXtSmall(
>   File "/home/edge7/.cache/pypoetry/virtualenvs/wharfree-net-IECYI3Oq-py3.10/lib/python3.10/site-packages/keras/src/applications/convnext.py", line 603, in ConvNeXtSmall
>     return ConvNeXt(
>   File "/home/edge7/.cache/pypoetry/virtualenvs/wharfree-net-IECYI3Oq-py3.10/lib/python3.10/site-packages/keras/src/applications/convnext.py", line 534, in ConvNeXt
>     weights_path = file_utils.get_file(
>   File "/home/edge7/.cache/pypoetry/virtualenvs/wharfree-net-IECYI3Oq-py3.10/lib/python3.10/site-packages/keras/src/utils/file_utils.py", line 306, in get_file
>     raise ValueError(
> ValueError: Incomplete or corrupted file detected. The auto file hash does not match the provided value of 6fc8009faa2f00c1c1dfce59feea9b0745eb260a7dd11bee65c8e20843da6eab.

**Comment by harshaljanjani** [comment]
Hello @edge7Lux, thanks for bringing this issue to light! The issue is with the fact that you're loading the ImageNet weights of an incompatible model, `ConvNeXtLarge`, into `ConvNeXtSmall`, although I do believe the error can be improved before requesting the API for the model weights, which is why I'll raise a PR soon that'll change the error message to make it much more apt to the situation for all models that subclass from ConvNeXt.

**Original Error Message:**

```
Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/convnext/convnext_large_notop.h5
785596384/785596384
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    convnext.ConvNextSmall(
  File "keras/applications/convnext.py", line 627, in ConvNeXtSmall
    return ConvNext(
  File "keras/applications/convnext.py", line 558, in ConvNeXt
    weights_path = file_utils.get_file(
  File "keras/utils/file_utils.py", line 328, in get_file
    raise ValueError(
ValueError: Incomplete or corrupted file detected. The auto file hash does not match the provided value of 6fc8009faa2f00c1c1dfce59feea9b0745eb260a7dd11bee65c8e20843da6eab.
```

**New Error Message:**

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    convnext.ConvNextSmall(
  File "keras/applications/convnext.py", line 627, in ConvNeXtSmall
    return ConvNext(
  File "keras/applications/convnext.py", line 543, in ConvNeXt
    raise ValueError(
ValueError: Model name "convnext_large" does not match weights variant "convnext_small". When using imagenet weights, the model name must contain the weights variant (e.g., "convnext_small").
```
