### ISSUE TITLE
Loading weights into custom LSTM layer fails: Layer 'lstm_cell' expected 3 variables, but received 0 variables during loading. Expected: ['kernel', 'recurrent_kernel', 'bias']

### ISSUE THREAD

**Issue by lbortolotti** [keras-team/keras#20322]
I'm using the official TF 2.17 container (**tensorflow/tensorflow:2.17.0-gpu-jupyter**) + **keras==3.5.0**.

The following code saves a model which contains a (dummy) custom LSTM layer, then inits a new copy of the model (with a vanilla LSTM) and tries to load the weights from the first model into the second.

Code:

```
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

import keras
from keras import layers

# An extremely uninteresting custom layer
@keras.saving.register_keras_serializable()
class MyCustomLSTM(keras.layers.LSTM):
    def __init__(self, units, **kwargs):
        super().__init__(units, **kwargs)

def make_model(
    use_custom_lstm=True,
):
    inputs = layers.Input(shape=(None, 4), name="inputs")

    if use_custom_lstm:
        lstm = MyCustomLSTM
    else:
        lstm = layers.LSTM

    outputs = lstm(
        units=8,
        return_sequences=True,
        name="my_LSTM",
    )(inputs)

    model = keras.models.Model(inputs=inputs, outputs=outputs)

    return model


weights_file = "this_is_a_test.weights.h5"
if os.path.exists(weights_file):
    os.remove(weights_file)

model = make_model(use_custom_lstm=True)
model.compile()
model.save_weights(weights_file)

new_model = make_model(use_custom_lstm=False)
new_model.load_weights(weights_file)

```

Output:

```
Traceback (most recent call last):
  File "scratch_1.py", line 45, in <module>
    new_model.load_weights(weights_file)
  File "venv/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "venv/lib/python3.11/site-packages/keras/src/saving/saving_lib.py", line 593, in _raise_loading_failure
    raise ValueError(msg)
ValueError: A total of 1 objects could not be loaded. Example error message for object <LSTMCell name=lstm_cell, built=True>:

Layer 'lstm_cell' expected 3 variables, but received 0 variables during loading. Expected: ['kernel', 'recurrent_kernel', 'bias']

List of objects that could not be loaded:
[<LSTMCell name=lstm_cell, built=True>]
```

Considering that the custom layer in this case is doing absolutely nothing of interest, I assume this is a bug.  If not, please let me know how one is meant to wrap a LSTM layer to avoid this issue.

Thanks!

**Comment by mehtamansi29** [comment]
Hi @lbortolotti -

Thanks for reporting the issue. Here as per your code while saving the model weights you used `use_custom_lstm=True` in this line  `model = make_model(use_custom_lstm=True)`. But while loading the model used `use_custom_lstm=False`, because of this facing an  error.

By taking `model.summary()` while saving weights will gives better idea which layers and paramters are used for model creation. 

Using below changes will resolve the error. 
```
new_model = make_model(use_custom_lstm=True)
new_model.load_weights(weights_file)
```

Attached [gist](https://colab.sandbox.google.com/gist/mehtamansi29/ed7e845ffb3a6ee5c3d6b07cd2b5a613/20322-loading-weights-into-custom-lstm-layer-fails-layer-lstm_cell-expected-3-variables-but-received-0-variables-during-loading-expected-kernel-recurrent_kernel-bias.ipynb) for your reference as well.

**Comment by lbortolotti** [comment]
Hi.  I'm perfectly aware that the model I'm loading the weights into has a "different" lstm layer.  However, the models have 1) identical weight structure/dimensions and 2) identically named layers.  In this situation, keras has always supported loading weights, even if the layer class has changed.  This is something I've used all the time, and continues to work with tf-keras.

My example is particularly extreme as MyCustomLSTM is absolutely identical to a vanilla LSTM layer - normally I'd have some custom logic in there (but nothing that affects the weight structure).

The official doc confirms that my example should work, I think, as it says _Weights are loaded based on the network's topology._ :

https://keras.io/api/models/model_saving_apis/weights_saving_and_loading/#loadweights-method

**Comment by lbortolotti** [comment]
Interesting.  I've dug a bit deeper, and have found that to restore model loading functionality I have to change the file name from <name>.weights.h5 to <name>.h5.  Literally just removing the ".weights." suffix (which is now a strict requirement in TF 2.17, as far as I can tell) resolves it, and I can transfer weights as I always have.

To replicate, you just need to take your last gist, save the weights as `weights_file = "this_is_a_test.h5"`, and you'll find that they then load correctly.

Which behaviour is the expected behaviour?  I was definitely using the functionality...

**Comment by lbortolotti** [comment]
Hi.  Specifying use_custom_lstm=True at both save and load time sidesteps the entire bug I was reporting.

The entire premise of this issue is that weight loading should work even if I change the use_custom_lstm kwargs between model save and model load.  It should work because the model remains topologically identical.

The documentation is not helpful, and does not clearly state if my scenario is supported or not.  All I know is that it was definitely supported with tf-keras.

Quoting the documentation, for what it's worth:

> Weights are loaded based on the network's topology. This means the architecture should be the same as when the weights were saved. Note that layers that don't have weights are not taken into account in the topological ordering, so adding or removing layers is fine as long as they don't have weights.
> 
> Partial weight loading
> 
> If you have modified your model, for instance by adding a new layer (with weights) or by changing the shape of the weights of a layer, you can choose to ignore errors and continue loading by setting skip_mismatch=True. In this case any layer with mismatching weights will be skipped. A warning will be displayed for each skipped layer.

For me, this reads like my scenario should work, as:
1) The model remains topologically identical, regardless of the use_custom_lstm flag value and
2) "not substantial" model changes are clearly supported (for instance the addition of extra layers which do not contain weights)

**Comment by hertschuh** [comment]
To clarify one thing:
- `test.h5` is the "legacy" format from earlier versions of Keras 2, it contains both the weights and the model
- `test.weights.h5` is the new "weights only" format

But their structure is different, so you may get different results.

In terms of what you're doing, this is not a supported flow the way it is written in your example. Keras has no way to know that `MyCustomLSTM` has the same weights and structure as the `LSTM` layer. You could use `skip_mismatch=True`, but this will result in `MyCustomLSTM` being skipped entirely (not restored).

There are however, supported flows:
- The easiest for your use case is [`clone_model`](https://keras.io/api/models/model_saving_apis/model_config_serialization/#clonemodel-function), which allows you to add / remove / change any layer you want, change the class, change the config, take or not take the weights or tweak them, etc.
- Another one is [`FileEditor`](https://keras.io/api/models/model_saving_apis/keras_file_editor/) which allows you to change weights in a keras weights file

**Comment by hertschuh** [comment]
Closing per my previous comment, this is not a supported flow.
