### ISSUE TITLE
KerasFileEditor Exception with simple Sequential model

### ISSUE THREAD

**Issue by t-kalinowski** [keras-team/keras#20372]
Attempting to write a simple R unit-test/example for `KerasFileEditor`, I encountered an exception.

```python
import keras
from keras import Sequential, Input
from keras.layers import Dense
import numpy as np

# Create a simple model, save it
model = Sequential(name="my_sequential")
model.add(Input(shape=(1,), name="my_input"))
model.add(Dense(1, activation="sigmoid", name="my_dense"))
model.compile(optimizer="adam", loss="mse", metrics=["mae"])
model.fit(np.array([[1]]), np.array([[1]]), verbose=0)
model.save("model.keras")
model.save_weights("model.weights.h5")

model_editor = keras.saving.KerasFileEditor("model.keras")

model_weights_editor = keras.saving.KerasFileEditor("model.weights.h5")
```
I see:

```
>>> model_editor = keras.saving.KerasFileEditor("model.keras")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tomasz/.virtualenvs/r-keras/lib/python3.11/site-packages/keras/src/saving/file_editor.py", line 99, in __init__
    weights_dict, object_metadata = self._extract_weights_from_store(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomasz/.virtualenvs/r-keras/lib/python3.11/site-packages/keras/src/saving/file_editor.py", line 475, in _extract_weights_from_store
    result[key], metadata = self._extract_weights_from_store(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomasz/.virtualenvs/r-keras/lib/python3.11/site-packages/keras/src/saving/file_editor.py", line 483, in _extract_weights_from_store
    result[key] = value[:]
                  ~~~~~^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/tomasz/.virtualenvs/r-keras/lib/python3.11/site-packages/h5py/_hl/dataset.py", line 840, in __getitem__
    selection = sel2.select_read(fspace, args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomasz/.virtualenvs/r-keras/lib/python3.11/site-packages/h5py/_hl/selections2.py", line 101, in select_read
    return ScalarReadSelection(fspace, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomasz/.virtualenvs/r-keras/lib/python3.11/site-packages/h5py/_hl/selections2.py", line 86, in __init__
    raise ValueError("Illegal slicing argument for scalar dataspace")
ValueError: Illegal slicing argument for scalar dataspace
>>> 
>>> model_weights_editor = keras.saving.KerasFileEditor("model.weights.h5")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tomasz/.virtualenvs/r-keras/lib/python3.11/site-packages/keras/src/saving/file_editor.py", line 99, in __init__
    weights_dict, object_metadata = self._extract_weights_from_store(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomasz/.virtualenvs/r-keras/lib/python3.11/site-packages/keras/src/saving/file_editor.py", line 475, in _extract_weights_from_store
    result[key], metadata = self._extract_weights_from_store(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomasz/.virtualenvs/r-keras/lib/python3.11/site-packages/keras/src/saving/file_editor.py", line 483, in _extract_weights_from_store
    result[key] = value[:]
                  ~~~~~^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/tomasz/.virtualenvs/r-keras/lib/python3.11/site-packages/h5py/_hl/dataset.py", line 840, in __getitem__
    selection = sel2.select_read(fspace, args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomasz/.virtualenvs/r-keras/lib/python3.11/site-packages/h5py/_hl/selections2.py", line 101, in select_read
    return ScalarReadSelection(fspace, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomasz/.virtualenvs/r-keras/lib/python3.11/site-packages/h5py/_hl/selections2.py", line 86, in __init__
    raise ValueError("Illegal slicing argument for scalar dataspace")
ValueError: Illegal slicing argument for scalar dataspace
```

**Comment by fchollet** [comment]
Thanks for the report, this is now fixed.
