### ISSUE TITLE
UnboundLocalError: cannot access local variable 'weights_store' where it is not associated with a value

### ISSUE THREAD

**Issue by johnlockejrr** [keras-team/keras#20381]
```
System: Ubuntu 22.04.5 LTS on WSL 2
CUDA Version: 12.7
Driver Version: 565.90
tf_nightly                   2.19.0.dev20241017
keras-nightly                3.6.0.dev2024101603
```

Hi! I want to interfere with a `tensorflow` and `keras` ytained model but I get this error I cannot find anywhere:

```
(sbb_pixelwise_segmentation-py3.11) incognito@DESKTOP-H1BS9PO:~/eynollah/sbb_pixelwise_segmentation$ python inference.py -m output/model_3/ -i newtestamentinsy0000unse_g7r6_0013.jpg -s out.jpg
2024-10-18 20:42:09.783662: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-10-18 20:42:09.794621: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1729273329.807413   65984 cuda_dnn.cc:8498] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1729273329.811519   65984 cuda_blas.cc:1410] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-10-18 20:42:09.822880: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0000 00:00:1729273331.457233   65984 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9711 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060, pci bus id: 0000:04:00.0, compute capability: 8.6
Traceback (most recent call last):
  File "/home/incognito/eynollah/sbb_pixelwise_segmentation/sbb_pixelwise_segmentation-py3.11/lib/python3.11/site-packages/keras/src/saving/saving_lib.py", line 389, in _load_model_from_dir
    raise ValueError(
ValueError: Expected a model.weights.h5 or model.weights.npz file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/incognito/eynollah/sbb_pixelwise_segmentation/inference.py", line 639, in <module>
    main()
  File "/home/incognito/eynollah/sbb_pixelwise_segmentation/sbb_pixelwise_segmentation-py3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/incognito/eynollah/sbb_pixelwise_segmentation/sbb_pixelwise_segmentation-py3.11/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/incognito/eynollah/sbb_pixelwise_segmentation/sbb_pixelwise_segmentation-py3.11/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/incognito/eynollah/sbb_pixelwise_segmentation/sbb_pixelwise_segmentation-py3.11/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/incognito/eynollah/sbb_pixelwise_segmentation/inference.py", line 636, in main
    x.run()
  File "/home/incognito/eynollah/sbb_pixelwise_segmentation/inference.py", line 559, in run
    res=self.predict()
        ^^^^^^^^^^^^^^
  File "/home/incognito/eynollah/sbb_pixelwise_segmentation/inference.py", line 227, in predict
    self.start_new_session_and_model()
  File "/home/incognito/eynollah/sbb_pixelwise_segmentation/inference.py", line 163, in start_new_session_and_model
    self.model = load_model(self.model_dir , compile=False,custom_objects = {"PatchEncoder": PatchEncoder, "Patches": Patches})
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/incognito/eynollah/sbb_pixelwise_segmentation/sbb_pixelwise_segmentation-py3.11/lib/python3.11/site-packages/keras/src/saving/saving_api.py", line 189, in load_model
    return saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/incognito/eynollah/sbb_pixelwise_segmentation/sbb_pixelwise_segmentation-py3.11/lib/python3.11/site-packages/keras/src/saving/saving_lib.py", line 357, in load_model
    return _load_model_from_dir(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/incognito/eynollah/sbb_pixelwise_segmentation/sbb_pixelwise_segmentation-py3.11/lib/python3.11/site-packages/keras/src/saving/saving_lib.py", line 413, in _load_model_from_dir
    weights_store.close()
    ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'weights_store' where it is not associated with a value
```

**Comment by mehtamansi29** [comment]
Hi @johnlockejrr -

Can you help me with the sample code for reproduce this issue ?

**Comment by johnlockejrr** [comment]
Thank you so much! I already solved the problem, there was trying to use Keras v3 on Keras v2 model

**Comment by XiongHaocheng** [comment]
Hello @johnlockejrr : 
I also encountered the same error. I was using a model from pyapetnet and executed the command 'pyapetnet_predict_from_icom osem_dcm_dir t1_decm_ir S2_osem-b10_fdg_pe2i -- show'. The error message was' Expected a model. weights. h5 or model. weights. npz file. '. How did you solve it?
