### ISSUE TITLE
Does Keras 3 work with `tf.distribute.MultiWorkerMirroredStrategy`?

### ISSUE THREAD

**Issue by justinvyu** [keras-team/keras#20585]
This user guide shows Keras 3 usage with `tf.distribute.MirroredStrategy`, which is only useful for single-node multi-GPU data parallel training.

However, `tf.distribute.MultiWorkerMirroredStrategy` is required for **multi-node** data parallel training.

[This example on Tensorflow's docs](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras) does not work with `keras-nightly-3.7.0.dev2024120303`, `tf-nightly-2.19.0.dev20241203`, though this problem has been around for a few releases of tensorflow (since `tensorflow==2.16` when the default Keras version got bumped to Keras 3; see https://github.com/tensorflow/tensorflow/issues/72388).

**Question: Does Keras 3 support `tf.distribute.MultiWorkerMirroredStrategy` for TF distributed training, or does it only support `tf.distribute.MirroredStrategy`?**

## Reproduction

Try running this example as a colab notebook: https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras

You will encounter this error:

```
%%bash
python main.py

Traceback (most recent call last):
  File "/content/main.py", line 22, in <module>
    multi_worker_model.fit(multi_worker_dataset, epochs=3, steps_per_epoch=70)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/constant_op.py", line 108, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Attempt to convert a value (PerReplica:{
  0: <tf.Tensor: shape=(64, 28, 28), dtype=float32, numpy=
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]], dtype=float32)>
}) with an unsupported type (<class 'tensorflow.python.distribute.values.PerReplica'>) to a Tensor.
```

**Comment by dryglicki** [comment]
Welcome to the party, pal: https://github.com/keras-team/keras/issues/20329

**Comment by dhantule** [comment]
Hi @justinvyu, 

Thanks for reporting this. You can use `tf.distribute.MirroredStrategy` to implement data parallelism, it seems `tf.distribute.MultiWorkerMirroredStrategy` is not supported with keras 3 yet as mentioned in this [documentation](https://keras.io/keras_tuner/guides/distributed_tuning/#data-parallelism-with-tfdistribute). You can read more about data parallelism [here.](https://keras.io/examples/nlp/data_parallel_training_with_keras_nlp)

**Comment by justinvyu** [comment]
Thanks @dhantule. Do you know when the `tf.distribute.MultiWorkerMirroredStrategy` support is slated on the roadmap? Is there somewhere that I can read about the roadmap?

**Comment by dhantule** [comment]
Hi @justinvyu, data parallelism and distributed tuning can be combined, we can run multiple trials of training and leverage data parallelism to speed up the training process. If you have 8 workers with 2 GPUs on each worker, you can run 8 parallel trials with each trial training on 2 GPUs by using `tf.distribute.MirroredStrategy`.

**Comment by richardliaw** [comment]
hi @dhantule we need to be able to train a single model across multiple nodes still, even without distributed tuning.

**Comment by fchollet** [comment]
Keras 3 does not work with `tf.distribute.MultiWorkerMirroredStrategy`.

Whether support with be added is a question for the Keras team at Google to answer. @jeffcarp, do you know?

Here's what I know:

- PSS training was a very niche feature. My impression was that it was only used internally at Google, mostly for legacy reasons (it used to be the only realistic way to do massive multi GPU training on Borg). But I guess I was wrong? This is the first time I hear about it being used outside Google. PSS is basically never the right idea, even if you have multiple machines.
- Users of PSS training at Google are all using Keras 2 + TF at this time.
- There is work underway for PSS training with Keras 3 on JAX. I believe it involves a custom callback.
- Not sure if that's also true for TF.

My overall take is, you should probably not be using PSS. Even at Google where some people use it, I have never seen a valid use case for it. If you problem is, "I have many machines, each with 1 or more GPUs, and I want to train a single model on all of them", then the answer is Keras 3 + JAX + the `keras.distribution.ModelParallel` API. It will do a much better job at utilizing your devices. And it works in multi-node settings, to be clear.

**Comment by gianlucasama** [comment]
Any update on this? I think it's one of those major features that can't really be missing.

**Comment by vinhdiesal-ai** [comment]
I am using tensorflow 2.20 with keras 3.12 with cuda and confirmed that `tf.distribute.MultiWorkerMirroredStrategy()` works.

**Comment by vinhdiesal-ai** [comment]
Is there any update on this because I have the same issues with using  `tensorflow 2.21` with `keras 3` to train datasets using `tf.distribute.MultiWorkerMirroredStrategy`. I tried JAX with keras as mentioned in this issue, but it gets stuck.

**Comment by jeffcarp** [comment]
> I tried JAX with keras as mentioned in this issue, but it gets stuck.

Where does JAX get stuck, do you have a repro?
