### ISSUE TITLE
Keras 3.7.0 breaks PyDataset with Tensorflow on GPU

### ISSUE THREAD

**Issue by dryglicki** [keras-team/keras#20600]
As the title says.

Situation: Trying to read HDF5 files via PyDataset. Creating a dictionary of arrays (tensors) for the inputs; just an array/tensor for the outputs. This is confirmed to work on Keras 3.5.0.

Same as all my other tickets, PyDataset loader:

```!/usr/bin/env python3
import os ; import sys
from pathlib import Path

import keras.ops as kops
import keras as K
import tensorflow as tf

import numpy as np
import h5py
import math
import random

class HDFDataset(K.utils.PyDataset):
    def __init__(self,
            file_list: list | tuple | set,
            batch_size: int,
            shuffle_data: bool = False,
            lons_lats: bool = False,
            subsample: bool = False,
            output_times: int | None = None,
            seed: int = 42,
            add_terrain: bool = False,
            add_model: bool = False,
            input_name: str = 'priors',
            output_name: str = 'forecasts',
            **kwargs):
        super(HDFDataset, self).__init__(**kwargs)
        self.shuffle_data = shuffle_data
        self.lons_lats = lons_lats
        self.file_list = file_list
        if self.shuffle_data: random.shuffle(self.file_list) # In-place shuffle

        self.batch_size = batch_size
        self.tmplen = len(self.file_list)

        self.subsample = subsample
        if self.subsample: self.rng = np.random.default_rng(seed=seed)

        self.output_times = output_times

        self.add_model = add_model
        self.add_terrain = add_terrain

        self.input_name = input_name
        self.output_name = output_name

        with h5py.File(self.file_list[0], 'r') as h5:
            print("Input Shape: ", h5.get("priors").shape)
            print("Output Shape: ", h5.get(self.output_name).shape)

    def __len__(self):
        '''
        Returns the number of batches in the dataset
        '''
        # else - not autoregressive
        return self.tmplen // self.batch_size

    def _extract_data_from_hdf5(self, file_list, sequence : tuple = None):
        '''
        Extracts the relevant data from a list of HDF5 files.

        Parameters
        ----------
        file_list: list
            List of HDF5 files to extract data from.
        sequence : tuple = None
            If autoregressive, the start and end indices of the sequence to return this step

        Returns
        -------
        inputs_dict: dict
            Dictionary with the same keys as the input_list, where the values are
            numpy arrays of shape (n_samples, n_timesteps, n_y, n_x, n_channels).
        outputs: numpy array
            Numpy array of shape (n_samples, n_timesteps, n_y, n_x, n_channels).

        '''

        input_list = [self.input_name]
        output_list = [self.output_name]

        if self.add_terrain: input_list.append('terrain')
        if self.add_model: input_list.append('model')

        # Preparing input dictionary
        inputs_dict = {}
        for name in input_list:
            new_var = f'input_{name}'
            inputs_dict[new_var] = []

        outputs = []

        for f in file_list:
            ys, xs = 0, 0
            ye = 256 ; xe = 256
            if self.subsample: # will use rng to find starting point, take 1/2 subsample
                ys, xs = self.rng.integers(low=0, high=128, size=(2), endpoint=False)
                ye = ys + 128 ; xe = xs + 128

            yslice = slice(ys,ye)
            xslice = slice(xs,xe)

            with h5py.File(f, 'r') as h5:

                for k in input_list:

                    # Check if requested data exists in the file
                    if h5.get(k) is None:
                        raise ValueError(f"Input {k} does not exist in file {f}")

                    new_var = f'input_{k}' # e.g. "input_priors", "input_terrain", "input_model"
                    if k == 'terrain':
                        # All time steps of the input are used?
                        if self.subsample:
                            inputs_dict[new_var].append(np.expand_dims(h5.get(k)[yslice, xslice],-1))
                        else:
                            inputs_dict[new_var].append(np.expand_dims(h5.get(k)[...],-1))
                    else:
                        if self.subsample:
                            inputs_dict[new_var].append(h5.get(k)[:, yslice, xslice, :])
                        else:
                            inputs_dict[new_var].append(h5.get(k)[...])
                for k in output_list:
                    if self.subsample and self.output_times is not None:
                        outputs.append(h5.get(k)[:self.output_times, yslice, xslice, :])
                    elif not self.subsample and self.output_times is not None:
                        outputs.append(h5.get(k)[:self.output_times, ...])
                    elif self.subsample and self.output_times is None:
                        outputs.append(h5.get(k)[:, yslice, xslice, :])
                    else:
                        outputs.append(h5.get(k)[...])
        for k in input_list:
            nv = f'input_{k}'
            inputs_dict[nv] = np.stack(inputs_dict[nv], axis = 0)
#           inputs_dict[nv] = kops.convert_to_tensor(np.stack(inputs_dict[nv], axis = 0), 'float32')
#           inputs_dict[nv] = tf.convert_to_tensor(np.stack(inputs_dict[nv], axis = 0), tf.float32)

        outputs = np.stack(outputs, axis = 0)
#       outputs = kops.convert_to_tensor(np.stack(outputs, axis = 0), 'float32')
#       outputs = tf.convert_to_tensor(np.stack(outputs, axis = 0), tf.float32)

        return inputs_dict, outputs

    def __getitem__(self,
            idx: int):

        if idx >= self.__len__(): raise StopIteration

        # Idx will be per file
        self.low = idx * self.batch_size
        self.high = min(self.low + self.batch_size, self.tmplen)

        # Batch of files for each "step" in the training
        inputs, outputs = self._extract_data_from_hdf5(self.file_list[self.low:self.high])

        return [inputs, outputs]

    def on_epoch_end(self):
        '''
        Method called at the end of every epoch.
        
        If shuffle_data is True, we shuffle the list of files we are iterating over.
        '''
        if self.shuffle_data: random.shuffle(self.file_list) # In-place shuffle
```

This loader works just fine on Keras 3.5.0. On Keras 3.7.0, I get this error inside `model.fit()`:

```
2024-12-05 13:23:18.204130: W tensorflow/core/framework/op_kernel.cc:1828] INVALID_ARGUMENT: TypeError: `generator` yielded an element that did not match the expected structure. The expected structure was ({'input_priors': tf.float32, 'input_model': tf.float32}, tf.float32), but the yielded element was [{'input_priors': <tf.Tensor: shape=(8, 6, 128, 128, 9), dtype=float32, numpy=
array([[[[[0.5653472 , 0.49902982, 0.43419117, ..., 0.25120723,
           0.26915392, 0.36413574],
          [0.5664465 , 0.49950194, 0.43444967, ..., 0.24900298,
           0.2681829 , 0.36413574],
          [0.567183  , 0.49997506, 0.43419117, ..., 0.24607508,
           0.26643804, 0.36413574],
          ...,
```

...and it goes on like that. As you can see, I tried manually forcing the tensor conversion to `tf.float32`, but this was unsuccessful.

Buried within a longer error (https://gist.github.com/dryglicki/97998da4427d160fddd723c6356bc581), I see this line:

```Traceback (most recent call last):

  File "/ssd0/miniforge3_2024-04/envs/tensorflow_2d17_py3d11/lib/python3.11/site-packages/tensorflow/python/data/ops/from_generator_op.py", line 204, in generator_py_func
    flattened_values = nest.flatten_up_to(output_types, values)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/ssd0/miniforge3_2024-04/envs/tensorflow_2d17_py3d11/lib/python3.11/site-packages/tensorflow/python/data/util/nest.py", line 237, in flatten_up_to
    return nest_util.flatten_up_to(
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/ssd0/miniforge3_2024-04/envs/tensorflow_2d17_py3d11/lib/python3.11/site-packages/tensorflow/python/util/nest_util.py", line 1541, in flatten_up_to
    return _tf_data_flatten_up_to(shallow_tree, input_tree)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/ssd0/miniforge3_2024-04/envs/tensorflow_2d17_py3d11/lib/python3.11/site-packages/tensorflow/python/util/nest_util.py", line 1570, in _tf_data_flatten_up_to
    _tf_data_assert_shallow_structure(shallow_tree, input_tree)

  File "/ssd0/miniforge3_2024-04/envs/tensorflow_2d17_py3d11/lib/python3.11/site-packages/tensorflow/python/util/nest_util.py", line 1414, in _tf_data_assert_shallow_structure
    raise TypeError(

TypeError: If shallow structure is a sequence, input must also be a sequence. Input has type: 'list'.


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/ssd0/miniforge3_2024-04/envs/tensorflow_2d17_py3d11/lib/python3.11/site-packages/tensorflow/python/ops/script_ops.py", line 270, in __call__
    ret = func(*args)
          ^^^^^^^^^^^

  File "/ssd0/miniforge3_2024-04/envs/tensorflow_2d17_py3d11/lib/python3.11/site-packages/tensorflow/python/autograph/impl/api.py", line 643, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

  File "/ssd0/miniforge3_2024-04/envs/tensorflow_2d17_py3d11/lib/python3.11/site-packages/tensorflow/python/data/ops/from_generator_op.py", line 206, in generator_py_func
    raise TypeError(

TypeError: `generator` yielded an element that did not match the expected structure. The expected structure was ({'input_priors': tf.float32, 'input_model': tf.float32}, tf.float32), but the yielded element was [{'input_priors': <tf.Tensor: shape=(4, 6, 128, 128, 9), dtype=float32, numpy=
array([[[[[0.7865028 , 0.7921322 , 0.790888  , ..., 0.79560995,```

**Comment by dryglicki** [comment]
All right, so I figured it out. It's the list coming out of `__getitem__` but uh... that was a nasty surprise.
