### ISSUE TITLE
ValueError: Error when checking model input: expected convolution2d_input_1 to have shape (None, 96, 128, 1) but got array with shape (0, 1, 96, 128)

### ISSUE THREAD

**Issue by monajalal** [keras-team/keras#5145]
Can you please help me figure this, the code previously worked with Theano but now has problem with TF.
@fchollet 
```

mona@pascal:~/computer_vision/kaggle_distracted_driver$ python run_keras_simple.py 
/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so.5.0 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so.8.0 locally
Read train images
Load folder c0
Load folder c1
Load folder c2
Load folder c3
Load folder c4
Load folder c5
Load folder c6
Load folder c7
Load folder c8
Load folder c9
Directory doesnt exists
('Train shape:', (0, 1, 96, 128))
(0, 'train samples')
('Split train: ', 0)
('Split valid: ', 0)
('Split holdout: ', 0)
Traceback (most recent call last):
  File "run_keras_simple.py", line 210, in <module>
    validation_data=(X_test, Y_test), verbose=1)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 672, in fit
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1117, in fit
    batch_size=batch_size)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1030, in _standardize_user_data
    exception_prefix='model input')
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 124, in standardize_input_data
    str(array.shape))
ValueError: Error when checking model input: expected convolution2d_input_1 to have shape (None, 96, 128, 1) but got array with shape (0, 1, 96, 128)
```
code:

```
# -*- coding: utf-8 -*-

import numpy as np
np.random.seed(2016)

import os
import glob
import cv2
import math
import pickle
import datetime
import pandas as pd

from sklearn.cross_validation import train_test_split
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.convolutional import Convolution2D, MaxPooling2D
from keras.utils import np_utils
from keras.models import model_from_json
from sklearn.metrics import log_loss


def get_im(path):
    # Load as grayscale
    img = cv2.imread(path, 0)
    # Reduce size
    resized = cv2.resize(img, (128, 96))
    return resized


def load_train():
    X_train = []
    y_train = []
    print('Read train images')
    for j in range(10):
        print('Load folder c{}'.format(j))
        path = os.path.join('..', 'input', 'imgs', 'train', 'c' + str(j), '*.jpg')
        files = glob.glob(path)
        for fl in files:
            img = get_im(fl)
            X_train.append(img)
            y_train.append(j)

    return X_train, y_train


def load_test():
    print('Read test images')
    path = os.path.join('..', 'input', 'imgs', 'test', '*.jpg')
    files = glob.glob(path)
    X_test = []
    X_test_id = []
    total = 0
    thr = math.floor(len(files)/10)
    for fl in files:
        flbase = os.path.basename(fl)
        img = get_im(fl)
        X_test.append(img)
        X_test_id.append(flbase)
        total += 1
        if total%thr == 0:
            print('Read {} images from {}'.format(total, len(files)))

    return X_test, X_test_id


def cache_data(data, path):
    if os.path.isdir(os.path.dirname(path)):
        file = open(path, 'wb')
        pickle.dump(data, file)
        file.close()
    else:
        print('Directory doesnt exists')


def restore_data(path):
    data = dict()
    if os.path.isfile(path):
        file = open(path, 'rb')
        data = pickle.load(file)
    return data


def save_model(model):
    json_string = model.to_json()
    if not os.path.isdir('cache'):
        os.mkdir('cache')
    open(os.path.join('cache', 'architecture.json'), 'w').write(json_string)
    model.save_weights(os.path.join('cache', 'model_weights.h5'), overwrite=True)


def read_model():
    model = model_from_json(open(os.path.join('cache', 'architecture.json')).read())
    model.load_weights(os.path.join('cache', 'model_weights.h5'))
    return model


def split_validation_set(train, target, test_size):
    random_state = 51
    X_train, X_test, y_train, y_test = train_test_split(train, target, test_size=test_size, random_state=random_state)
    return X_train, X_test, y_train, y_test


def split_validation_set_with_hold_out(train, target, test_size):
    random_state = 51
    train, X_test, target, y_test = train_test_split(train, target, test_size=test_size, random_state=random_state)
    X_train, X_holdout, y_train, y_holdout = train_test_split(train, target, test_size=test_size, random_state=random_state)
    return X_train, X_test, X_holdout, y_train, y_test, y_holdout


def create_submission(predictions, test_id, loss):
    result1 = pd.DataFrame(predictions, columns=['c0', 'c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9'])
    result1.loc[:, 'img'] = pd.Series(test_id, index=result1.index)
    now = datetime.datetime.now()
    if not os.path.isdir('subm'):
        os.mkdir('subm')
    suffix = str(round(loss, 6)) + '_' + str(now.strftime("%Y-%m-%d-%H-%M"))
    sub_file = os.path.join('subm', 'submission_' + suffix + '.csv')
    result1.to_csv(sub_file, index=False)


# The same as log_loss
def mlogloss(target, pred):
    score = 0.0
    for i in range(len(pred)):
        pp = pred[i]
        for j in range(len(pp)):
            prob = pp[j]
            if prob < 1e-15:
                prob = 1e-15
            score += target[i][j] * math.log(prob)
    return -score/len(pred)


def validate_holdout(model, holdout, target):
    predictions = model.predict(holdout, batch_size=128, verbose=1)
    score = log_loss(target, predictions)
    print('Score log_loss: ', score)
    # score = model.evaluate(holdout, target, show_accuracy=True, verbose=0)
    # print('Score holdout: ', score)
    # score = mlogloss(target, predictions)
    # print('Score : mlogloss', score)
    return score


cache_path = os.path.join('cache', 'train.dat')
if not os.path.isfile(cache_path):
    train_data, train_target = load_train()
    cache_data((train_data, train_target), cache_path)
else:
    print('Restore train from cache!')
    (train_data, train_target) = restore_data(cache_path)

batch_size = 64
nb_classes = 10
nb_epoch = 2
# input image dimensions
img_rows, img_cols = 96, 128
# number of convolutional filters to use
nb_filters = 32
# size of pooling area for max pooling
nb_pool = 2
# convolution kernel size
nb_conv = 3

train_data = np.array(train_data, dtype=np.uint8)
train_target = np.array(train_target, dtype=np.uint8)
train_data = train_data.reshape(train_data.shape[0], 1, img_rows, img_cols)
# train_data = train_data.transpose((0, 3, 1, 2))
train_target = np_utils.to_categorical(train_target, nb_classes)
train_data = train_data.astype('float32')
train_data /= 255
print('Train shape:', train_data.shape)
print(train_data.shape[0], 'train samples')

X_train, X_test, X_holdout, Y_train, Y_test, Y_holdout = split_validation_set_with_hold_out(train_data, train_target, 0.2)
print('Split train: ', len(X_train))
print('Split valid: ', len(X_test))
print('Split holdout: ', len(X_holdout))


model_from_cache = 0
if model_from_cache == 1:
    model = read_model()
else:
    model = Sequential()
    model.add(Convolution2D(nb_filters, nb_conv, nb_conv,
                            border_mode='valid',
                            input_shape=(img_rows, img_cols, 1)))
    model.add(Activation('relu'))
    model.add(Convolution2D(nb_filters, nb_conv, nb_conv))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(nb_pool, nb_pool)))
    model.add(Dropout(0.25))

    model.add(Flatten())
    model.add(Dense(128))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(Dense(nb_classes))
    model.add(Activation('softmax'))

    model.compile(loss='categorical_crossentropy', optimizer='adadelta', metrics=["accuracy"])

    '''
    model.fit(train_data, train_target, batch_size=batch_size, nb_epoch=nb_epoch,
              show_accuracy=True, verbose=1, validation_split=0.1)
    '''
    model.fit(X_train, Y_train, batch_size=batch_size, nb_epoch=nb_epoch,
            validation_data=(X_test, Y_test), verbose=1)

score = model.evaluate(X_test, Y_test, show_accuracy=True, verbose=0)
print('Score: ', score)
score = model.evaluate(X_holdout, Y_holdout, show_accuracy=True, verbose=0)
print('Score holdout: ', score)
validate_holdout(model, X_holdout, Y_holdout)
save_model(model)

cache_path = os.path.join('cache', 'test.dat')
if not os.path.isfile(cache_path):
    test_data, test_id = load_test()
    cache_data((test_data, test_id), cache_path)
else:
    print('Restore test from cache!')
    (test_data, test_id) = restore_data(cache_path)

test_data = np.array(test_data, dtype=np.uint8)
test_data = test_data.reshape(test_data.shape[0], 1, img_rows, img_cols)
# test_data = test_data.transpose((0, 3, 1, 2))
test_data = test_data.astype('float32')
test_data /= 255
print('Test shape:', test_data.shape)
print(test_data.shape[0], 'test samples')
predictions = model.predict(test_data, batch_size=128, verbose=1)

create_submission(predictions, test_id, score[0])

```

**Comment by gvtulder** [comment]
The first problem might be that your `X_train` is empty. Is that intentional?
```
('Train shape:', (0, 1, 96, 128))
```

The second problem might be that you're mixing the Theano and TensorFlow `image_dim_ordering`. What setting did you use in your Keras config?

This looks like Theano ordering (channels, rows, cols):
```
('Train shape:', (0, 1, 96, 128))
```
while this looks like TensorFlow ordering (rows, cols, channels):
```python
    model.add(Convolution2D(nb_filters, nb_conv, nb_conv,
                            border_mode='valid',
                            input_shape=(img_rows, img_cols, 1)))
```
Both orderings should work, as long as you set `image_dim_ordering` correctly and consistently use the same ordering in all your inputs and shapes.

**Comment by bxwhl** [comment]
u need check the train data's and the target data's format

**Comment by DGaffney** [comment]
@bxwhl this is a bad comment that doesn't help humans.

**Comment by lazarillo** [comment]
@monajalal Did you ever resolve this?  I'm having a similar problem (although I never converted from Theano), where I need to create a "None" dimension.

Here are some details:

 - Using Anaconda as my virtual environment
 - Keras version 2.0.6
 - TensorFlow version 1.1.0

I am creating an example fairly closely following [this tutorial](https://github.com/mineshmathew/char_rnn_karpathy_keras/blob/master/char_rnn_of_karpathy_keras.py).

And here are the relevant snippets of code:

    from keras.models import Sequential
    from keras.layers import Dense, Activation, Dropout
    from keras.layers import LSTM,TimeDistributed,SimpleRNN
    from keras.utils.data_utils import get_file
    import numpy as np
    from time import sleep
    import random
    import sys

...

    X = np.zeros((len(sentences), maxlen, len(chars)), dtype=np.bool)
    y = np.zeros((len(sentences),maxlen, len(chars)), dtype=np.bool) # y is also a sequence , or  a seq of 1 hot vectors
    for i, sentence in enumerate(sentences):
        for t, char in enumerate(sentence):
            X[i, t, char_indices[char]] = 1

    for i, sentence in enumerate(next_chars):
        for t, char in enumerate(sentence):
            y[i, t, char_indices[char]] = 1

...

    model = Sequential()
    model.add(LSTM(512, return_sequences=True, input_shape=(maxlen, len(chars))))  # original one
    model.add(LSTM(512, return_sequences=True)) #- original
    model.add(Dropout(0.2))
    model.add(TimeDistributed(Dense(len(chars))))
    model.add(Activation('softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='rmsprop')

...

    history=model.fit(X, y, batch_size=128, nb_epoch=1,verbose=0)

...

    seed_string="brutus:\nbeing so moved, he will not spare"
    x=np.zeros((1, len(seed_string), len(chars)))
    for t, char in enumerate(seed_string):
        x[0, t, char_indices[char]] = 1.
    preds = model.predict(x, verbose=0)[0]

At this last line, it errors out, with the following error:

    ValueError: Error when checking : expected lstm_13_input to have shape (None, 40, 39) but got array with shape (1, 39, 39)

I have played with the **dimensionality of the `seed_string` and the `x` generated from it**, but no matter how I try to adjust them, I have some sort of mis-match, always due to this requirement of `None`.

I looked at [`Reshape`'s code](https://github.com/fchollet/keras/blob/master/keras/layers/core.py#L294) and an [example of how to use it](https://keras.io/layers/core/), but since Keras' `Reshape` is meant for ***model layers***, I don't even understand how I could use it to reshape the input to the prediction, and Numpy has no way to reshape creating a `None` dimension (at least not to my knowledge).

**Comment by puyangsky** [comment]
@lazarillo I came across the same problem, and I don't understand how to make the None shape

**Comment by TeemuKoivisto** [comment]
Okey I seemed to have used input_shape (256,256,3) for my CNN which resulted in my model requiring (None, 256, 256, 3) shapes for single value prediction.

So what I did was create an array: `nop = np.array([None])`

And then append to it the shape: `img = np.append(nop, resized_img)`

**Comment by akrsrivastava** [comment]
I was getting this error in my softmax layer. I found out that I had not done to_categorical() on my labels.

**Comment by zbokaee** [comment]
Hi, I'm working on a sentiment analysis project in python with keras using CNN and word2vec as an embedding method.
according to my code, I set my input shape, 15 and 512 so when I want to predict the polarity of a new sentence say:"I am so sorry" for example, with the length: 4 - I face this error:

**

> expected conv1d_1_input to have shape (15, 512) but got array with shape (4, 512)

**
``
and this is a part of my code:

   

>  model = Sequential()
>     model.add(Conv1D(32, kernel_size=3, activation='elu', padding='same', 
>     input_shape=(max_tweet_length, vector_size)))
>     model.add(Conv1D(32, kernel_size=3, activation='elu', padding='same'))
>     model.add(Conv1D(32, kernel_size=3, activation='elu', padding='same'))
>     model.add(Conv1D(32, kernel_size=3, activation='elu', padding='same'))
>     model.add(Dropout(0.25))
>     model.add(Conv1D(32, kernel_size=2, activation='elu', padding='same'))
>     model.add(Conv1D(32, kernel_size=2, activation='elu', padding='same'))
>     model.add(Conv1D(32, kernel_size=2, activation='elu', padding='same'))
>     model.add(Conv1D(32, kernel_size=2, activation='elu', padding='same'))
>     model.add(Dropout(0.25))
>     model.add(Dense(256, activation='relu')
>     model.add(Dense(256, activation='relu'))
>     model.add(Dropout(0.5))
>     model.add(Flatten())
>     model.add(Dense(2, activation='softmax'))
> 

all I can do is making new python file and load all my related models such as word2vec ... and change the input shape on it like this:

   ```
 model111 = Sequential()
    model111.add(Conv1D(32, kernel_size=3, activation='elu', padding='same', 
    input_shape=(len(final), 512)))
    model111.add(Dense(256, activation='relu'))
    model111.add(Dense(256, activation='relu'))
    model111.add(Dropout(0.5))
    model111.add(Flatten())
    model111.add(Dense(2, activation='softmax'))

```
I wanna know whether this method is ok or not?? any efficient solution would be really appreciated
