### ISSUE TITLE
Share stateful LSTM layers

### ISSUE THREAD

**Issue by cinhcet** [keras-team/keras#6501]
Hi,

if I want to reuse stateful LSTM layers in a separate model like in the code below (very simplified version)
```python
from keras.layers import Input, LSTM, Dense, Reshape
from keras.models import Model

import numpy as np

batch_size = 1
N = 10
M = 2

input = Input(batch_shape=(batch_size,N,))

lstm = Reshape((1,N))(input)
lstm = LSTM(100, stateful=True, return_sequences=False, name='lstm')(lstm)
output = Dense(M, name='lstmDense')(lstm)

model = Model(inputs=input, outputs=output)

print(model.predict(np.array([[10,10,10,10,10,10,10,10,10,10]])))

input2 = Input(batch_shape=(batch_size,N,))
layer = model.get_layer('lstmDense')(model.get_layer('lstm')(Reshape((1,N))(input2)))
otherModel = Model(input2, layer)

print(model.predict(np.array([[10,10,10,10,10,10,10,10,10,10]])))
print(otherModel.predict(np.array([[10,10,10,10,10,10,10,10,10,10]])))
```
I get the following error when calling otherModel.predict(...)
```
2017-05-04 12:51:43.601816: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [1,10]
	 [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[1,10], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Traceback (most recent call last):
  File "/home/userName/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1039, in _do_call
    return fn(*args)
  File "/home/userName/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1021, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/userName/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [1,10]
	 [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[1,10], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/userName/git/kerasTests/testBug.py", line 25, in <module>
    print(otherModel.predict(np.array([[10,10,10,10,10,10,10,10,10,10]])))
  File "/home/userName/.local/lib/python3.5/site-packages/keras/engine/training.py", line 1573, in predict
    batch_size=batch_size, verbose=verbose)
  File "/home/userName/.local/lib/python3.5/site-packages/keras/engine/training.py", line 1203, in _predict_loop
    batch_outs = f(ins_batch)
  File "/home/userName/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2103, in __call__
    feed_dict=feed_dict)
  File "/home/userName/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/home/userName/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/home/userName/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/home/userName/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [1,10]
	 [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[1,10], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'input_1', defined at:
  File "/home/userName/git/kerasTests/testBug.py", line 10, in <module>
    input = Input(batch_shape=(batch_size,N,))
  File "/home/userName/.local/lib/python3.5/site-packages/keras/engine/topology.py", line 1392, in Input
    input_tensor=tensor)
  File "/home/userName/.local/lib/python3.5/site-packages/keras/engine/topology.py", line 1303, in __init__
    name=self.name)
  File "/home/userName/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 351, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
  File "/home/userName/.local/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1507, in placeholder
    name=name)
  File "/home/userName/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1997, in _placeholder
    name=name)
  File "/home/userName/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/userName/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/userName/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'input_1' with dtype float and shape [1,10]
	 [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[1,10], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
```

whereas if I set stateful to False, everything works.
ubuntu 16.04, python 3.5.2, tensorflow 1.1.0

**Comment by ThomasJanssoone** [comment]
I have the same issue, did you find why ?

**Comment by cinhcet** [comment]
@ThomasJanssoone no, but I haven't looked at it for a while..

**Comment by visionscaper** [comment]
I have the same issue. When you would remove the `stateful=True` (so when the model is not stateful anymore) the problem disappears. Any new insights, @ThomasJanssoone, @cinhcet?

**Comment by DeepWolf90** [comment]
me too having the same issue @visionscaper . Any updates!!

**Comment by visionscaper** [comment]
No @DeepWolf90, also checkout issue #9084. Any recognition for that issue too? Please comment there if you do.

**Comment by craymichael** [comment]
I too have this issue attempting to share layers of a stateful model. Even though the placeholder for the batched input is not used in the new model, it is still expected that the placeholder is filled regardless of its use. Filling it with an arbitrary value and including it as another `Input` to the new model resolves the issue, but leads to very convoluted code.
