### ISSUE TITLE
AttributeError: 'module' object has no attribute 'convolution'

### ISSUE THREAD

**Issue by akshaylamba** [keras-team/keras#7204]
Running in train_frcnn.py with below code ( Using Tensorflow-GPU Version 0.11.0rc0 & Keras 2.0.4) for Python 2.7

```
```Traceback (most recent call last):
  File "train_frcnn.py", line 121, in <module>
    shared_layers = nn.nn_base(img_input, trainable=True)
  File "/home/ubuntu/notebooks/keras/FasterRCNN_KERAS/keras_frcnn/resnet.py", line 160, in nn_base
    x = Convolution2D(64, (7, 7), strides=(2, 2), name='conv1', trainable = trainable)(x)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 585, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 164, in call
    dilation_rate=self.dilation_rate)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 3089, in conv2d
    x = tf.nn.convolution(
AttributeError: 'module' object has no attribute 'convolution'
```

**Comment by abrad1212** [comment]
Details?

**Comment by abrad1212** [comment]
Ok, because you need to use the Keras 2 API for example
`from keras.layers import Conv2D`

**Comment by MajorChina** [comment]
This issue also happens in my computer. When I just run [keras/examples/mnist_cnn.py](https://github.com/fchollet/keras/blob/master/examples/mnist_cnn.py)
And I got

```
x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-f504139de7f0> in <module>()
     47 model.add(Conv2D(32, kernel_size=(3, 3),
     48                  activation='relu',
---> 49                  input_shape=input_shape))
     50 model.add(Conv2D(64, (3, 3), activation='relu'))
     51 model.add(MaxPooling2D(pool_size=(2, 2)))

/home/member/meijie/anaconda3/lib/python3.5/site-packages/keras/models.py in add(self, layer)
    434                 # and create the node connecting the current layer
    435                 # to the input layer we just created.
--> 436                 layer(x)
    437 
    438             if len(layer.inbound_nodes) != 1:

/home/member/meijie/anaconda3/lib/python3.5/site-packages/keras/engine/topology.py in __call__(self, inputs, **kwargs)
    594 
    595             # Actually call the layer, collecting output(s), mask(s), and shape(s).
--> 596             output = self.call(inputs, **kwargs)
    597             output_mask = self.compute_mask(inputs, previous_mask)
    598 

/home/member/meijie/anaconda3/lib/python3.5/site-packages/keras/layers/convolutional.py in call(self, inputs)
    162                 padding=self.padding,
    163                 data_format=self.data_format,
--> 164                 dilation_rate=self.dilation_rate)
    165         if self.rank == 3:
    166             outputs = K.conv3d(

/home/member/meijie/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py in conv2d(x, kernel, strides, padding, data_format, dilation_rate)
   3148     x = _preprocess_conv2d_input(x, data_format)
   3149     padding = _preprocess_padding(padding)
-> 3150     x = tf.nn.convolution(
   3151         input=x,
   3152         filter=kernel,

AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'convolution'
```

The keras is up to date
```
meefly@lthpc:~$ pip3 install keras
Requirement already satisfied: keras in ./anaconda3/lib/python3.5/site-packages
Requirement already satisfied: theano in ./anaconda3/lib/python3.5/site-packages (from keras)
Requirement already satisfied: pyyaml in ./anaconda3/lib/python3.5/site-packages (from keras)
Requirement already satisfied: six in ./anaconda3/lib/python3.5/site-packages (from keras)
Requirement already satisfied: numpy>=1.7.1 in ./anaconda3/lib/python3.5/site-packages (from theano->keras)
Requirement already satisfied: scipy>=0.11 in ./anaconda3/lib/python3.5/site-packages (from theano->keras)

meefly@lthpc:~$ pip3 install keras --upgrade
Requirement already up-to-date: keras in ./anaconda3/lib/python3.5/site-packages
Requirement already up-to-date: theano in ./anaconda3/lib/python3.5/site-packages (from keras)
Requirement already up-to-date: pyyaml in ./anaconda3/lib/python3.5/site-packages (from keras)
Requirement already up-to-date: six in ./anaconda3/lib/python3.5/site-packages (from keras)
Requirement already up-to-date: scipy>=0.14 in ./anaconda3/lib/python3.5/site-packages (from theano->keras)
Requirement already up-to-date: numpy>=1.9.1 in ./anaconda3/lib/python3.5/site-packages (from theano->keras)
```

Also the tensorflow
```
meefly@lthpc:~$ pip3 install --upgrade tensorflow-gpu
Collecting tensorflow-gpu
  Using cached tensorflow_gpu-1.2.1-cp35-cp35m-manylinux1_x86_64.whl
Requirement already up-to-date: bleach==1.5.0 in ./anaconda3/lib/python3.5/site-packages (from tensorflow-gpu)
Collecting protobuf>=3.2.0 (from tensorflow-gpu)
  Using cached protobuf-3.3.0-cp35-cp35m-manylinux1_x86_64.whl
Requirement already up-to-date: six>=1.10.0 in ./anaconda3/lib/python3.5/site-packages (from tensorflow-gpu)
Requirement already up-to-date: backports.weakref==1.0rc1 in ./anaconda3/lib/python3.5/site-packages (from tensorflow-gpu)
Requirement already up-to-date: html5lib==0.9999999 in ./anaconda3/lib/python3.5/site-packages (from tensorflow-gpu)
Requirement already up-to-date: werkzeug>=0.11.10 in ./anaconda3/lib/python3.5/site-packages (from tensorflow-gpu)
Requirement already up-to-date: numpy>=1.11.0 in ./anaconda3/lib/python3.5/site-packages (from tensorflow-gpu)
Requirement already up-to-date: markdown>=2.6.8 in ./anaconda3/lib/python3.5/site-packages (from tensorflow-gpu)
Requirement already up-to-date: wheel>=0.26 in ./anaconda3/lib/python3.5/site-packages (from tensorflow-gpu)
Requirement already up-to-date: setuptools in ./anaconda3/lib/python3.5/site-packages (from protobuf>=3.2.0->tensorflow-gpu)
Installing collected packages: protobuf, tensorflow-gpu
  Found existing installation: protobuf 3.0.0
    Uninstalling protobuf-3.0.0:
      Successfully uninstalled protobuf-3.0.0
  Found existing installation: tensorflow-gpu 0.12.1
    Uninstalling tensorflow-gpu-0.12.1:
      Successfully uninstalled tensorflow-gpu-0.12.1
Successfully installed protobuf-3.3.0 tensorflow-gpu-1.2.1
meefly@lthpc:~$ pip install --upgrade tensorflow-gpu
Requirement already up-to-date: tensorflow-gpu in ./anaconda3/lib/python3.5/site-packages
Requirement already up-to-date: markdown>=2.6.8 in ./anaconda3/lib/python3.5/site-packages (from tensorflow-gpu)
Requirement already up-to-date: wheel>=0.26 in ./anaconda3/lib/python3.5/site-packages (from tensorflow-gpu)
Requirement already up-to-date: protobuf>=3.2.0 in ./anaconda3/lib/python3.5/site-packages (from tensorflow-gpu)
Requirement already up-to-date: werkzeug>=0.11.10 in ./anaconda3/lib/python3.5/site-packages (from tensorflow-gpu)
Requirement already up-to-date: html5lib==0.9999999 in ./anaconda3/lib/python3.5/site-packages (from tensorflow-gpu)
Requirement already up-to-date: six>=1.10.0 in ./anaconda3/lib/python3.5/site-packages (from tensorflow-gpu)
Requirement already up-to-date: bleach==1.5.0 in ./anaconda3/lib/python3.5/site-packages (from tensorflow-gpu)
Requirement already up-to-date: numpy>=1.11.0 in ./anaconda3/lib/python3.5/site-packages (from tensorflow-gpu)
Requirement already up-to-date: backports.weakref==1.0rc1 in ./anaconda3/lib/python3.5/site-packages (from tensorflow-gpu)
Requirement already up-to-date: setuptools in ./anaconda3/lib/python3.5/site-packages (from protobuf>=3.2.0->tensorflow-gpu)
```

**Comment by abrad1212** [comment]
@MajorChina How are you running the script? are you doing `python3 mnist_cnn.py` or `python mnist_cnn.py
