### ISSUE TITLE
Dimension passed instead of Integer in training.py: AttributeError: 'Dimension' object has no attribute 'ceil'

### ISSUE THREAD

**Issue by phobrain** [keras-team/keras#7684]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

==> Script loads an imgur image, but hoping a quick code-read will suffice. 

```
In training.py _predict_loop:
        if ins and hasattr(ins[0], 'shape'):
            samples = ins[0].shape[0]
            print('SAMP ' + str(ins[0].shape)) # => SAMP (?, 224, 224, 3)
```

Filing as a bug since it seems a more friendly error could at least be generated - the one I get doesn't turn up in a web search. Likely it's a simple type error in my python-novice conversion of siamese/mnist to a general-purpose jpg evaluator. Original:

  https://github.com/fchollet/keras/blob/master/examples/mnist_siamese_graph.py

Simple predict() on directly-converted file works fine, so user-level problem is likely in the create_pairs() code that adds to the pairs array passed to Input, or in how I'm defining the Input.

-- OSX Darwin
% python -c "import keras; print keras.__version__"
Using TensorFlow backend.
2.0.6
%  python -c 'import tensorflow as tf; print(tf.__version__)'
1.3.0

{
    "image_data_format": "channels_last",
    "image_dim_ordering": "tf",
    "epsilon": 1e-07,
    "floatx": "float32",
    "backend": "tensorflow"
}

Traceback (most recent call last):
  File "min_siam.py", line 63, in <module>
    processed_a = base_network.predict(input_a)
  File "/Users/priot/tensorflow/lib/python2.7/site-packages/keras/engine/training.py", line 1653, in predict
    verbose=verbose)
  File "/Users/priot/tensorflow/lib/python2.7/site-packages/keras/engine/training.py", line 1236, in _predict_loop
    batches = _make_batches(samples, batch_size)
File "/Users/priot/tensorflow/lib/python2.7/site-packages/keras/engine/training.py", line 374, in _make_batches
    num_batches = int(np.ceil(size / float(batch_size)))
AttributeError: 'Dimension' object has no attribute 'ceil'

-------------- min_siam.py

```
from __future__ import absolute_import
from __future__ import print_function
import numpy as np

import requests
from PIL import Image
from io import BytesIO

from keras.applications.vgg16 import VGG16
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
from keras.models import Model
from keras.layers import Input, Lambda
from keras.optimizers import RMSprop
from keras import backend as K

def create_pairs(pic_dir, pr_type, input_dim):
    pairs = []
    labels = []

    # same result:
    #im1 = image.load_img('prun224/1/img1021a.jpg', target_size=input_dim)
    response = requests.get('http://i.imgur.com/wpxMwsR.jpg')
    im1 = Image.open(BytesIO(response.content))
    if im1.size != input_dim:
        im1 = im1.resize(input_dim)
    x = image.img_to_array(im1)
    x = np.expand_dims(x, axis=0)
    x = preprocess_input(x)
    print('SH ' + str(x.shape)) # => 1, 224, 224, 3

    pairs += [[x, x]]
    labels += [1]
    return np.array(pairs), np.array(labels)

def euclidean_distance(vects):
    x, y = vects
    return K.sqrt(K.maximum(K.sum(K.square(x - y), axis=1, keepdims=True), K.epsilon()))

def eucl_dist_output_shape(shapes):
    shape1, shape2 = shapes
    return (shape1[0], 1)

def contrastive_loss(y_true, y_pred):
    '''Contrastive loss from Hadsell-et-al.'06
    http://yann.lecun.com/exdb/publis/pdf/hadsell-chopra-lecun-06.pdf
    '''
    margin = 1
    return K.mean(y_true * K.square(y_pred) +
                  (1 - y_true) * K.square(K.maximum(margin - y_pred, 0)))

base_network = VGG16(weights='imagenet', include_top=False)
input_dim = (224, 224)
pic_dir = 'prun224'

tr_pairs, tr_y = create_pairs(pic_dir, 'train', input_dim)
te_pairs, te_y = create_pairs(pic_dir, 'test', input_dim)

input_a = Input(shape=(input_dim[0], input_dim[1], 3))
input_b = Input(shape=(input_dim[0], input_dim[1], 3))

processed_a = base_network.predict(input_a)  # USING predict() IS A DIFF FROM mnist example
processed_b = base_network.predict(input_b)

distance = Lambda(euclidean_distance,
                  output_shape=eucl_dist_output_shape)([processed_a, processed_b])

model = Model([input_a, input_b], distance)

rms = RMSprop()
model.compile(loss=contrastive_loss, optimizer=rms)
model.fit([tr_pairs[:, 0], tr_pairs[:, 1]], tr_y,
          batch_size=128,  # same with batch_size=1
          epochs=1,
          validation_data=([te_pairs[:, 0], te_pairs[:, 1]], te_y))
```

**Comment by phobrain** [comment]
It might be relevant that when I hack past that problem by setting samples to 1, the next thing I get is 
...
  File "/Users/priot/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/Users/priot/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1074, in _run
    raise TypeError('The value of a feed cannot be a tf.Tensor object. '
TypeError: The value of a feed cannot be a tf.Tensor object. Acceptable feed values include Python scalars, strings, lists, numpy ndarrays, or TensorHandles.

**Comment by phobrain** [comment]
If I remove the predict() from my base_network call, I move on to a complaint about an extra dimension in the input:

File "/Users/priot/tensorflow/lib/python2.7/site-packages/keras/engine/training.py", line 134, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking input: expected input_2 to have 4 dimensions, but got array with shape (2, 1, 224, 224, 3)

**Comment by phobrain** [comment]
Thanks to kirk on slack, I flattened my multidimensional features to match the mnist example, 

`x = x.reshape(-1, 224*224*3)[0]`

and

`input_a = Input(shape=(224*224*3,))`

which gets to another dimensional error, perhaps another topic:

>     processed_a = base_network(input_a)
>     ...
>   File "/Users/pp/tensorflow/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 3146, in conv2d
>     data_format='NHWC')
>   File "/Users/pp/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 641, in convolution
>     input_channels_dim = input.get_shape()[num_spatial_dims + 1]
>   File "/Users/pp/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 505, in __getitem__
>     return self._dims[key]
> IndexError: list index out of range

**Comment by phobrain** [comment]
Further progress at the link below, leaving this page.

    https://groups.google.com/forum/#!topic/keras-users/q4g8hDThfsE
