### ISSUE TITLE
Strange reshaping in TimeDistributed

### ISSUE THREAD

**Issue by AlexeySorokin** [keras-team/keras#7726]
I am trying to implement sequence-to-sequence transduction using both characters of the sequence and feature vector standing for entire sequence. I want to append that vector to all the elements of the sequence. My strategy is:
1) create a Lambda layer with concatenate function where the second argument is fixed:
    first = kl.Input(shape=(10, 5))
    second = kl.Input(shape=(None,))
    inputs = [first, second]
    join_func = kl.Lambda(concat, arguments={'y': second}, output_shape=(6,)) 
2) use this Lambda layer inside TimeDistributed:
    joint = kl.TimeDistributed(join_func)(first)
I _do not want_ to apply RepeatVector since my sequences could be of different length and I want to use bucketing, not pad all the sequences to the same length.

However, even a toy example does not work.

**The code is below:**

import numpy as np

import keras.backend as kb
import keras.layers as kl
import keras.models as km

def concat(x, y):
    return kb.concatenate([x, y])

if __name__ == "__main__":
    X1 = np.random.randint(0, 10, size=(200, 10, 5))
    X2 = np.random.randint(2, 12, size=(200, 1))
    y = (np.max(X1, axis=2) > X2).astype(int)
    first = kl.Input(shape=(10, 5))
    second = kl.Input(shape=(None,))
    inputs = [first, second]
    join_func = kl.Lambda(concat, arguments={'y': second}, output_shape=(6,))
    joint = kl.TimeDistributed(join_func)(first)
    hidden = kl.GRU(5, return_sequences=True)(joint)
    outputs = kl.TimeDistributed(kl.Dense(1, activation="sigmoid"))(hidden)
    outputs = kl.Flatten()(outputs)
    model = km.Model(inputs, outputs)
    model.compile(optimizer="sgd", loss="binary_crossentropy", metrics=["accuracy"])
    print(model.summary())
    model.fit([X1, X2], y, validation_split=0.2, epochs=50, verbose=1)

**The runtime error is:**

Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\theano\compile\function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
  File "pygpu\gpuarray.pyx", line 1501, in pygpu.gpuarray.pygpu_concatenate
  File "pygpu\gpuarray.pyx", line 427, in pygpu.gpuarray.array_concatenate
ValueError: b'Dimension mismatch. as[1]->dimensions[0] = 32, as[0]->dimensions[0] = 320'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Programming/test/test_theano/test_concatenate.py", line 27, in <module>
    model.fit([X1, X2], y, validation_split=0.2, epochs=50, verbose=1)
  File "C:\Miniconda3\lib\site-packages\keras\engine\training.py", line 1430, in fit
    initial_epoch=initial_epoch)
  File "C:\Miniconda3\lib\site-packages\keras\engine\training.py", line 1079, in _fit_loop
    outs = f(ins_batch)
  File "C:\Miniconda3\lib\site-packages\keras\backend\theano_backend.py", line 1197, in __call__
    return self.function(*inputs)
  File "C:\Miniconda3\lib\site-packages\theano\compile\function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "C:\Miniconda3\lib\site-packages\theano\gof\link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "C:\Miniconda3\lib\site-packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Miniconda3\lib\site-packages\theano\compile\function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
  File "pygpu\gpuarray.pyx", line 1501, in pygpu.gpuarray.pygpu_concatenate
  File "pygpu\gpuarray.pyx", line 427, in pygpu.gpuarray.array_concatenate
ValueError: b'Dimension mismatch. as[1]->dimensions[0] = 32, as[0]->dimensions[0] = 320'
Apply node that caused the error: GpuJoin(TensorConstant{1}, GpuReshape{2}.0, GpuFromHost<None>.0)
Toposort index: 58
Inputs types: [TensorType(int8, scalar), GpuArrayType<None>(float32, (False, False)), GpuArrayType<None>(float32, (False, False))]
Inputs shapes: [(), (320, 5), (32, 1)]
Inputs strides: [(), (20, 4), (4, 4)]
Inputs values: [array(1, dtype=int8), 'not shown', 'not shown']
Outputs clients: [[GpuReshape{2}(GpuJoin.0, TensorConstant{[-1  6]})]]

It seems that TimeDistributed reshapes a 3D tensor to 2D (320 is the multiple of sequence length and batch size), however, I cannot figure out for what reason it happens. Is it a bug or a feature and how to achieve the desired behaviour?

**Comment by AlexeySorokin** [comment]
It is possible to do what I want by defining

```python
def repeat_(x, k):
    return kb.repeat_elements(x[:,None,:], k, 1)
```

and replacing 
```python
join_func = kl.Lambda(concat, arguments={'y': second}, output_shape=(6,))
joint = kl.TimeDistributed(join_func)(first)
```

by
```python
second_rep = kl.Lambda(repeat_, arguments={"k": first.shape[1]}, output_shape=(None, 1))(second)
joint = kl.Concatenate()([first, second_rep])
```
