### ISSUE TITLE
Error while running Seq2seq model in Tensorflow version 1.3 and keras version 1.2.0

### ISSUE THREAD

**Issue by dcabz** [keras-team/keras#7945]
Traceback (most recent call last):
  File "seq2seq.py", line 90, in <module>
    Seq2seq.train_seq2seq()
  File "seq2seq.py", line 74, in train_seq2seq
    model = s2s.seq2seq_plain()
  File "/home/david/Downloads/Seq2Seq-master/seq2seq/model.py", line 28, in seq2seq_plain
    model.add(RNN(self.hidden_dim, return_sequences=True))#, input_shape=(100, 128)))
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 327, in add
    output_tensor = layer(self.outputs[0])
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 543, in __call__
    self.build(input_shapes[0])
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.py", line 763, in build
    self.W = K.concatenate([self.W_i, self.W_f, self.W_c, self.W_o])
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 1222, in concatenate
    return tf.concat(axis, [to_dense(x) for x in tensors])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1061, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 611, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 676, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 121, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 376, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got <tf.Variable 'lstm_1_W_i:0' shape=(100, 200) dtype=float32_ref> of type 'Variable' instead.
`

**Comment by kelly-tlz** [comment]
have you tackled this problem? I meet this problem today

**Comment by dcabz** [comment]
@kelly-tlz  yeah upgraded the version.Issue solved
