### ISSUE TITLE
backwad RNN with CNTK backend and not specified sequence length

### ISSUE THREAD

**Issue by MPiecuch** [keras-team/keras#7983]
Hi, below is a code sample which runs on tensorflow and theano backend but not with CNTK. Is it a problem with CNTK framework itself?
```python
input_l = Input(batch_shape=(2, None, 3))
gru_l = GRU(units=5, go_backwards=True)(input_l)
model = Model(input_l, gru_l)
```
Here is error message

> /usr/local/lib/python2.7/dist-packages/keras/backend/cntk_backend.py:1076: UserWarning: Warning: CNTK backend does not support collapse of batch axis with inferred dimension. The reshape did not take place.
  'Warning: CNTK backend does not support '
Traceback (most recent call last):
  File "cntk_reverse.py", line 7, in <module>
    gru_l = GRU(units=5, go_backwards=True)(input_l)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.py", line 268, in __call__
    return super(Recurrent, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 602, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.py", line 348, in call
    input_length=timesteps)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/cntk_backend.py", line 1333, in rnn
    inputs = reverse(inputs, 1)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/cntk_backend.py", line 2249, in reverse
    return C.slice(x, cntk_axes, begin_index, end_index, strides)
  File "/usr/local/lib/python2.7/dist-packages/cntk/internal/swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/cntk/ops/__init__.py", line 2137, in slice
    return slice(x, axis, begin_index, end_index, strides, name)
RuntimeError: Function 'Slice: Output('Splice100_Output_0', [#], [? x 15]) -> Unknown': Slice operation index range [0,0), interpreted as [0,-1), is invalid for input 'Output('Splice100_Output_0', [#], [? x 15])' shape '[? x 15]'.
[CALL STACK]
[0x7f9764c6274c]                                                       + 0x69274c
[0x7f9764c9fc8d]    CNTK::PrimitiveFunction::  InferOutputs  (std::vector<CNTK::Variable,std::allocator<CNTK::Variable>>&) + 0x51ed
[0x7f9764c6af9f]                                                       + 0x69af9f
[0x7f977fdcfa99]                                                       + 0xea99
[0x7f9764c6527e]    CNTK::Function::  InitOutputs  ()                  + 0x5e
[0x7f9764cd8441]    CNTK::CompositeFunction::  InferOutputs  (std::vector<CNTK::Variable,std::allocator<CNTK::Variable>>&) + 0x11
[0x7f9764c6af9f]                                                       + 0x69af9f
[0x7f977fdcfa99]                                                       + 0xea99
[0x7f9764c6527e]    CNTK::Function::  InitOutputs  ()                  + 0x5e
[0x7f9764c6b7c8]    CNTK::  AsComposite  (std::shared_ptr<CNTK::Function> const&,  std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> const&) + 0x2a8
[0x7f9764c6eeea]    CNTK::  UnaryOp  (CNTK::PrimitiveOpType,  CNTK::Variable const&,  CNTK::Dictionary&&,  std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> const&) + 0x12a
[0x7f9764c71953]    CNTK::Internal::  Slice  (CNTK::Variable const&,  std::vector<CNTK::Axis,std::allocator<CNTK::Axis>> const&,  std::vector<int,std::allocator<int>> const&,  std::vector<int,std::allocator<int>> const&,  std::vector<int,std::allocator<int>> const&,  std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> const&) + 0x243
[0x7f9764c71ee9]    CNTK::  Slice  (CNTK::Variable const&,  std::vector<CNTK::Axis,std::allocator<CNTK::Axis>> const&,  std::vector<int,std::allocator<int>> const&,  std::vector<int,std::allocator<int>> const&,  std::vector<int,std::allocator<int>> const&,  std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> const&) + 0x399
[0x7f97657c6aed]                                                       + 0x2a0aed
[0x7f97657c80e8]                                                       + 0x2a20e8
[0x4c468a]          PyEval_EvalFrameEx                                 + 0x68a
[0x4c2765]          PyEval_EvalCodeEx                                  + 0x255
[0x4de8b8]                                                            
[0x4b0cb3]          PyObject_Call                                      + 0x43
[0x4c6ad1]          PyEval_EvalFrameEx                                 + 0x2ad1
[0x4c2765]          PyEval_EvalCodeEx                                  + 0x255
[0x4ca8d1]          PyEval_EvalFrameEx                                 + 0x68d1
[0x4c2765]          PyEval_EvalCodeEx                                  + 0x255
[0x4ca8d1]          PyEval_EvalFrameEx                                 + 0x68d1
[0x4c2765]          PyEval_EvalCodeEx                                  + 0x255
[0x4ca099]          PyEval_EvalFrameEx                                 + 0x6099
[0x4c2765]          PyEval_EvalCodeEx                                  + 0x255
[0x4de8b8]                                                            
[0x4b0cb3]          PyObject_Call                                      + 0x43
[0x4c6ad1]          PyEval_EvalFrameEx                                 + 0x2ad1
[0x4c2765]          PyEval_EvalCodeEx                                  + 0x255
[0x4de8b8]                                                            
[0x4b0cb3]          PyObject_Call                                      + 0x43
[0x4c6ad1]          PyEval_EvalFrameEx                                 + 0x2ad1
[0x4c2765]          PyEval_EvalCodeEx                                  + 0x255
[0x4de6fe]                                                            
[0x4b0cb3]          PyObject_Call                                      + 0x43
[0x4f492e]                                                            
[0x4b0cb3]          PyObject_Call                                      + 0x43
[0x553187]                                                            
[0x4b0cb3]          PyObject_Call                                      + 0x43
[0x4c9faf]          PyEval_EvalFrameEx                                 + 0x5faf
[0x4c2765]          PyEval_EvalCodeEx                                  + 0x255
[0x4c2509]          PyEval_EvalCode                                    + 0x19
[0x4f1def]                                                            
[0x4ec652]          PyRun_FileExFlags                                  + 0x82
[0x4eae31]          PyRun_SimpleFileExFlags                            + 0x191
[0x49e14a]          Py_Main                                            + 0x68a
[0x7f977fa17830]    __libc_start_main                                  + 0xf0
[0x49d9d9]          _start                                             + 0x29

Keras v2.0.8
CNTK v2.2

**Comment by souptc** [comment]
Thanks for reporting this. This is a bug in CNTK v2.2 when we add support with non-specified length axis. I will fix it in next CNTK release.

**Comment by devinbost** [comment]
What's the workaround?

**Comment by souptc** [comment]
could you try specify the input with fixed length?

**Comment by devinbost** [comment]
Wow, thanks for the quick response!

My model is currently specified as:
```
model = Sequential()
model.add(LSTM(500, return_sequences=True, activation='tanh', input_shape=(None, numberOfColumns)))
model.add(LSTM(480, return_sequences=True, activation='tanh'))
model.add(LSTM(450, return_sequences=True, activation='tanh'))
model.add(TimeDistributed(Dense(numberOfColumns, activation='linear')))
```

Is the solution to replace ```None``` with the actual batch_size?

**Comment by souptc** [comment]
My understanding is to replace the "None" with size of your time_step dimension.

**Comment by devinbost** [comment]
That works!
The only issue now is that due to the inference not working, I can't run a pretraining step like this:
```
for i in range(1, days):
  print('Pretraining: Length: ', 2**i)
  x, y, y_dir = createSequences(data, 2**i)
  model.fit(x, y, batch_size=batch_size, nb_epoch=1, shuffle=False)
```
If I try that, it blows up as expected:

> Pretraining: Length:  2
> Epoch 1/1
>  600/2609 [=====>........................] - ETA: 0s - loss: 1.0950
> 2609/2609 [==============================] - 0s - loss: 0.5105     
> Pretraining: Length:  4
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-86-eaf52ef812ea> in <module>()
>       2   print('Pretraining: Length: ', 2**i)
>       3   x, y, y_dir = createSequences(train_data_norm_filtered.values, 2**i)
> ----> 4   model.fit(x, y, batch_size=batch_size, epochs=1, shuffle=False)
> 
> C:\Anaconda3\lib\site-packages\keras\models.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, **kwargs)
>     865                               class_weight=class_weight,
>     866                               sample_weight=sample_weight,
> --> 867                               initial_epoch=initial_epoch)
>     868 
>     869     def evaluate(self, x, y, batch_size=32, verbose=1,
> 
> C:\Anaconda3\lib\site-packages\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
>    1520             class_weight=class_weight,
>    1521             check_batch_axis=False,
> -> 1522             batch_size=batch_size)
>    1523         # Prepare validation data.
>    1524         do_validation = False
> 
> C:\Anaconda3\lib\site-packages\keras\engine\training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, check_batch_axis, batch_size)
>    1376                                     self._feed_input_shapes,
>    1377                                     check_batch_axis=False,
> -> 1378                                     exception_prefix='input')
>    1379         y = _standardize_input_data(y, self._feed_output_names,
>    1380                                     output_shapes,
> 
> C:\Anaconda3\lib\site-packages\keras\engine\training.py in _standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
>     142                             ' to have shape ' + str(shapes[i]) +
>     143                             ' but got array with shape ' +
> --> 144                             str(array.shape))
>     145     return arrays
>     146 
> 
> ValueError: Error when checking input: expected lstm_13_input to have shape (None, 2, 5) but got array with shape (2607, 4, 5)

**Comment by souptc** [comment]
Yes, that need the time step axis with non-specified length, I have submit the fix to CNTK, will available in next month.
