### ISSUE TITLE
Errors while trying "python pretrained_word_embeddings.py" 

### ISSUE THREAD

**Issue by tthtlc** [keras-team/keras#8006]
While running pretrained_word_embeddings.py, I got the following errors:

```
2017-09-28 20:06:36.115269: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2017-09-28 20:06:36.115276: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2017-09-28 20:06:36.115287: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:0c:00.0)
Traceback (most recent call last):
  File "pretrained_word_embeddings.py", line 130, in <module>
    embedded_sequences = embedding_layer(sequence_input)
  File "/home/tthtlc/anaconda3/lib/python3.6/site-packages/Keras-2.0.8-py3.6.egg/keras/engine/topology.py", line 582, in __call__
  File "/home/tthtlc/anaconda3/lib/python3.6/site-packages/Keras-2.0.8-py3.6.egg/keras/engine/topology.py", line 1200, in set_weights
ValueError: Layer weight shape (20000, 100) not compatible with provided weight shape (20001, 100)

```
The error is corrected by the following patch:

```
diff --git a/examples/pretrained_word_embeddings.py b/examples/pretrained_word_embeddings.py
index 7ef75b3..99074af 100644
--- a/examples/pretrained_word_embeddings.py
+++ b/examples/pretrained_word_embeddings.py
@@ -106,7 +106,7 @@ print('Preparing embedding matrix.')
 
 # prepare embedding matrix
 num_words = min(MAX_NB_WORDS, len(word_index))
-embedding_matrix = np.zeros((num_words + 1, EMBEDDING_DIM))
+embedding_matrix = np.zeros((num_words, EMBEDDING_DIM))
 for word, i in word_index.items():
     if i >= MAX_NB_WORDS:
         continue
```

**Comment by sleeplessTLV** [comment]
Indeed, this correction makes the code 'run', yet the results are quite disappointing. I got a prediction score of 15% on the test set, which makes me suspect there is a deeper issue here.
