### ISSUE TITLE
How to convert TimeDistributed model to online batch by batch training?

### ISSUE THREAD

**Issue by bbogart** [keras-team/keras#8012]
I have working code using timeDistributed() to model a very high dimensional sequence (27,000 features over 500 time-steps). My data is organized such that rows are timesteps (samples) and cols are features in the wholeSequence array. Here are the key parts of my working code:

```
# Input sequence
wholeSequence = np.load("clusterProbability_18879-19379_1000clusters.npy")

# Preprocess Data:
data = wholeSequence[:-1] # all but last
target = wholeSequence[1:] # all but first

# Data Params
totalSamples = data.shape[0]
numDims = data.shape[1]
numBatches = 1
numSamples = totalSamples/numBatches

# Reshape training data for Keras LSTM model
# The training data needs to be (batchIndex, timeStepIndex, dimentionIndex)
data = data.reshape((numBatches, numSamples, numDims))
target = target.reshape((numBatches, numSamples, numDims))

# Build model with LSTM and autoencoder layers
model = Sequential()  
model.add(LSTM(256, input_shape=(numSamples, numDims), return_sequences=True))
model.add(TimeDistributed(Dense(numDims)))
model.compile(loss='mean_squared_error', optimizer='adam')
history = model.fit(data, target, nb_epoch=10000, batch_size=numSamples, verbose=2)
```

I want to be able to predict the next time-step for the current time-step. Right now I can only predict the whole sequence due to timeDistributed. So I'm trying to adapt Solution 3 from [this tutorial](https://machinelearningmastery.com/use-different-batch-sizes-training-predicting-python-keras/) where I train using a network with one batch size, but predict using another network using the same weights using a different batch size.

I think I have training working:
```
# Input sequence
wholeSequence = np.load("clusterProbability_18879-19379_1000clusters.npy")

# Preprocess Data:
data = wholeSequence[:-1] # all but last
target = wholeSequence[1:] # all but first

# Data Params
totalSamples = data.shape[0]
numDims = data.shape[1]
numBatches = 1
numSamples = totalSamples/numBatches

# Reshape training data for Keras LSTM model
# The training data needs to be (batchIndex, timeStepIndex, dimentionIndex)
data = data.reshape((numBatches, numSamples, numDims))
target = target.reshape((numBatches, numSamples, numDims))

# Build model with LSTM without timeDistributed (batch by batch training)
model = Sequential()
model.add(LSTM(256, batch_input_shape=(numBatches, numSamples, numDims), stateful=True, return_sequences=True))
model.add(Dense(numDims))
model.compile(loss='mean_squared_error', optimizer='adam')
for i in range(7000):
    model.fit(data, target, nb_epoch=1, batch_size=numBatches, verbose=2)
    model.reset_states()
    print(i)
```

But I'm stuck on prediction using a single timestep:

```
seedVector = data[0].reshape((1, numDims)) # First vector in batch.

# Construct new model for step by step predictions with one batch.
model = Sequential()
model.add(LSTM(256, batch_input_shape=(1, numSamples, numDims), stateful=True))
model.add(Dense(numDims))

# Copy Weights from original model to new model.
oldWeights = modelOrig.get_weights()
model.set_weights(oldWeights)

# Compile new model
model.compile(loss='mean_squared_error', optimizer='adam')

# Do one prediction
model.predict(seedVector, batch_size=1)
```

But model.predict() throws an error using my single timestep seedVector:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.2.0-py2.7.egg/keras/models.py", line 723, in predict
    return self.model.predict(x, batch_size=batch_size, verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.2.0-py2.7.egg/keras/engine/training.py", line 1202, in predict
    check_batch_dim=False)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.2.0-py2.7.egg/keras/engine/training.py", line 101, in standardize_input_data
    str(array.shape))
ValueError: Error when checking : expected lstm_input_3 to have 3 dimensions, but got array with shape (1, 27000)
```

I also tried using this (`seedVector = data[0].reshape((1, 1, numDims))`) but I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.2.0-py2.7.egg/keras/models.py", line 723, in predict
    return self.model.predict(x, batch_size=batch_size, verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.2.0-py2.7.egg/keras/engine/training.py", line 1202, in predict
    check_batch_dim=False)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.2.0-py2.7.egg/keras/engine/training.py", line 113, in standardize_input_data
    str(array.shape))
ValueError: Error when checking : expected lstm_input_3 to have shape (1, 500, 27000) but got array with shape (1, 1, 27000)
```

Any suggestions? I suspect I'm still not understanding shape of data in Keras.

**Comment by farizrahman4u** [comment]
In prediction model:
```python
model.add(LSTM(256, batch_input_shape=(1, 1, numDims), stateful=True, return_sequences=True))
```

**Comment by bbogart** [comment]
Thanks @farizrahman4u! Not sure now I missed that.

It just occurred to me that I may be able to use the same approach where I train using timeDistributed but then use those weights in a second network for sample by sample prediction. Is this possible?

**Comment by ylubg** [comment]
> Thanks @farizrahman4u! Not sure now I missed that.
> 
> It just occurred to me that I may be able to use the same approach where I train using timeDistributed but then use those weights in a second network for sample by sample prediction. Is this possible?

Hi, I run into the same problem. Could you please let me know how to solve it?
