### ISSUE TITLE
Model trained in AWS fails in Win10 machine(Both AWS/WIN10 has same Keras/TF versions)

### ISSUE THREAD

**Issue by bhatabhijithn** [keras-team/keras#8079]
I am training a model in AWS and while using the saved model from AWS to WIN10 simulator, i am getting this error. The same clone.py runs without issues in WIN10 model.
Please can you help.
```
C:\Users\abhijith.bhat\OneDrive - Accenture\UdacityDLND\CarND\CarND-Behavioral-Cloning-P3>python drive.py model.h5
Using TensorFlow backend.
Traceback (most recent call last):
  File "drive.py", line 122, in <module>
    model = load_model(args.model)
  File "C:\Users\abhijith.bhat\AppData\Local\Continuum\Anaconda3\lib\site-packages\keras\models.py", line 239, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Users\abhijith.bhat\AppData\Local\Continuum\Anaconda3\lib\site-packages\keras\models.py", line 313, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "C:\Users\abhijith.bhat\AppData\Local\Continuum\Anaconda3\lib\site-packages\keras\layers\__init__.py", line 54, in deserialize
    printable_module_name='layer')
  File "C:\Users\abhijith.bhat\AppData\Local\Continuum\Anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 139, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Users\abhijith.bhat\AppData\Local\Continuum\Anaconda3\lib\site-packages\keras\models.py", line 1214, in from_config
    model.add(layer)
  File "C:\Users\abhijith.bhat\AppData\Local\Continuum\Anaconda3\lib\site-packages\keras\models.py", line 442, in add
    layer(x)
  File "C:\Users\abhijith.bhat\AppData\Local\Continuum\Anaconda3\lib\site-packages\keras\engine\topology.py", line 602, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\abhijith.bhat\AppData\Local\Continuum\Anaconda3\lib\site-packages\keras\layers\core.py", line 650, in call
    return self.function(inputs, **arguments)
  File "clone.py", line 42, in <lambda>
    model.add(Lambda(lambda x: (x / 255.0)-0.5 , input_shape=(160,320,3)))
IndexError: tuple index out of range
```

- https://github.com/bhatabhijithn/Car-Behaviour-Cloning

If you get to know the issue, please let me know

**Comment by HereIsPatrick** [comment]
I have same issue, do you have any idea?

**Comment by byildiz** [comment]
I had the same issue. In my case, I found that the error occurs because of python version inconsistency. My local python version was 3.5.5 and the remote was 3.6.3. After installing same python version with the remote the model can be loaded without any error.
