### ISSUE TITLE
keras 并发load_model报错

### ISSUE THREAD

**Issue by zhaoxin0123** [keras-team/keras#8264]
我通过web代码实时加载模型进行预测，但报如下错误
Traceback (most recent call last):
File "/root/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1997, in call
return self.wsgi_app(environ, start_response)
File "/root/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
response = self.handle_exception(e)
File "/root/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
reraise(exc_type, exc_value, tb)
File "/root/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/root/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/root/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/root/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/root/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/root/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/root/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functionsrule.endpoint
File "/root/anaconda3/code/App.py", line 41, in predict
model=load_model(root_path+model_name)
File "/root/anaconda3/lib/python3.6/site-packages/keras/models.py", line 249, in load_model
topology.load_weights_from_hdf5_group(f['model_weights'], model.layers)
File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 3008, in load_weights_from_hdf5_group
K.batch_set_value(weight_value_tuples)
File "/root/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2189, in batch_set_value
get_session().run(assign_ops, feed_dict=feed_dict)
File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
run_metadata_ptr)
File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1071, in _run

e.args[0])
TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("Placeholder:0", shape=(1, 16), dtype=float32) is not an element of this graph.

**Comment by shichengcn** [comment]
虽然我也是新手，不知道你的错误怎么改。
不过我知道一个js版本的深度学习框架，把你在服务器上训练参数导出来，按照js版本格式加载到模型里，在浏览器里做预测，感觉可行。
https://github.com/karpathy/convnetjs

**Comment by kinni** [comment]
我發現你不能在 @app.route('/predict', methods=['POST']) 埋面加載 model，要在外面才行。

So I found that it is not able to load model inside the request handler, i.e. inside method with annotation @app.route('/predict', methods=['POST']); you have to load it out side. I think this is something related to threading, can't find a perfect solution yet.

**Comment by zhaoxin0123** [comment]
@kinni thank you ,i have tried this way, is ok . but i want on the basis of request params to load model. i have a lot of model , on the outside is very slow .so i  have no means.

**Comment by FrancisYizhang** [comment]
@zhaoxin0123 
Did you solve the problem?

**Comment by NCTUyoung** [comment]
I have the same problem , I use restful api to load model.
You have to ` tf.keras.backend.clear_session()` everytime you reload model
