### ISSUE TITLE
Import Error with Tensorflow Backend

### ISSUE THREAD

**Issue by bharathgs** [keras-team/keras#8288]
when I try to import keras with tensorflow backend I end up with `AttributeError: module 'pandas.core.computation' has no attribute 'expressions' `I tried the solutions as discussed in #6545 but it did not help.

note:  
1. **tensorflow : 1.3.0**
2. **keras: 2.0.8**
3. **dask: 0.15.4**
4. **pandas: 0.21.0**

```python 
import keras
Using TensorFlow backend.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xenomorph/applications/anaconda3/lib/python3.6/site-packages/keras/__init__.py", line 4, in <module>
    from . import activations
  File "/home/xenomorph/applications/anaconda3/lib/python3.6/site-packages/keras/activations.py", line 6, in <module>
    from .engine import Layer
  File "/home/xenomorph/applications/anaconda3/lib/python3.6/site-packages/keras/engine/__init__.py", line 8, in <module>
    from .training import Model
  File "/home/xenomorph/applications/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 25, in <module>
    from .. import callbacks as cbks
  File "/home/xenomorph/applications/anaconda3/lib/python3.6/site-packages/keras/callbacks.py", line 26, in <module>
    from tensorflow.contrib.tensorboard.plugins import projector
  File "/home/xenomorph/applications/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/__init__.py", line 31, in <module>
    from tensorflow.contrib import factorization
  File "/home/xenomorph/applications/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/factorization/__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "/home/xenomorph/applications/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/factorization/python/ops/gmm.py", line 27, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/xenomorph/applications/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/__init__.py", line 88, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/xenomorph/applications/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/xenomorph/applications/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/home/xenomorph/applications/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 297, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/home/xenomorph/applications/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/home/xenomorph/applications/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 31, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/xenomorph/applications/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 49, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/home/xenomorph/applications/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/home/xenomorph/applications/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 26, in <module>
    import dask.dataframe as dd
  File "/home/xenomorph/applications/anaconda3/lib/python3.6/site-packages/dask/dataframe/__init__.py", line 3, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/home/xenomorph/applications/anaconda3/lib/python3.6/site-packages/dask/dataframe/core.py", line 40, in <module>
    pd.core.computation.expressions.set_use_numexpr(False)
AttributeError: module 'pandas.core.computation' has no attribute 'expressions'
```

**Comment by AndrasEros** [comment]
Are you on Windows or Linux? Anaconda 3.5 works fine for me on Windows. Never upgrade unless you run into bugs.

**Comment by bharathgs** [comment]
@AndrasEros I'm on Linux (Ubuntu 16.04)

**Comment by AndrasEros** [comment]
Well, 

> pd.core.computation.expressions.set_use_numexpr(False)

is a valid call, see line 34 here:
https://github.com/pandas-dev/pandas/blob/master/pandas/core/computation/expressions.py

This looks like a damaged pandas installation. Try to reinstall 
`conda install -f pandas`
Also you may check pandas manually, it should be on you comuter:

> /home/xenomorph/applications/anaconda3/lib/python3.6/site-packages/pandas/core/computation/expressions.py

I don't think that this is caused by Keras, the error is issued when importing dask. To confirm try in a separate project:
`Import dask`

**Comment by stared** [comment]
Upgrading pandas (from `0.20.1` to `0.20.3`) helped, thanks.

**Comment by VanitarNordic** [comment]
You can use  `conda install -c hesi_m keras ` to install the latest version of Keras (2.1.6) and Tensorflow(1.8) for you.

**Comment by Interstella12** [comment]
have you solved this problem? @bharathgs

**Comment by ymodak** [comment]
@bharathgs Please use the latest version of TensorFlow and build again. Feel free to open a new issue if it still persists. Thanks!
