### ISSUE TITLE
ValueError: Dimension 2 in both shapes must be equal, but are 320 and 16 for 'Assign' (op: 'Assign') with input shapes: [8,8,320,16], [8,8,16,3]

### ISSUE THREAD

**Issue by RohanSaphal** [keras-team/keras#8294]
### Thanks in advance!!

Traceback (most recent call last):
  File "/home/rohan/PycharmProjects/Comma.ai/train_steering_model.py", line 68, in <module>
    model.load_weights('/home/rohan/PycharmProjects/Comma.ai/outputs/steering_model/steering_angle.keras')
  File "/home/rohan/anaconda2/lib/python2.7/site-packages/keras/models.py", line 727, in load_weights
    topology.load_weights_from_hdf5_group(f, layers)
  File "/home/rohan/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 3008, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/home/rohan/anaconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2184, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "/home/rohan/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 512, in assign
    return state_ops.assign(self._variable, value, use_locking=use_locking)
  File "/home/rohan/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/state_ops.py", line 270, in assign
    validate_shape=validate_shape)
  File "/home/rohan/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 47, in assign
    use_locking=use_locking, name=name)
  File "/home/rohan/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/rohan/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2338, in create_op
    set_shapes_for_outputs(ret)
  File "/home/rohan/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1719, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/rohan/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1669, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/rohan/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/home/rohan/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension 2 in both shapes must be equal, but are 320 and 16 for 'Assign' (op: 'Assign') with input shapes: [8,8,320,16], [8,8,16,3].

## Please find a small portion of the code below:
`
def get_model(time_len=1):
  ch, row, col = 3, 160, 320  # camera format

  model = Sequential()

  model.add(Lambda(lambda x: x/127.5 - 1.,
            input_shape=(ch, row, col),
            output_shape=(ch, row, col)))
  model.add(Convolution2D(16, 8, 8, subsample=(4, 4), border_mode="same"))
  model.add(ELU())
  model.add(Convolution2D(32, 5, 5, subsample=(2, 2), border_mode="same"))
  model.add(ELU())
  model.add(Convolution2D(64, 5, 5, subsample=(2, 2), border_mode="same"))
  model.add(Flatten())
  model.add(Dropout(.2))
  model.add(ELU())
  model.add(Dense(512))
  model.add(Dropout(.5))
  model.add(ELU())
  model.add(Dense(1))

  model.compile(optimizer="adam", loss="mse")

  return model

if __name__ == "__main__":
  parser = argparse.ArgumentParser(description='Steering angle model trainer')
  parser.add_argument('--host', type=str, default="localhost", help='Data server ip address.')
  parser.add_argument('--port', type=int, default=5557, help='Port of server.')
  parser.add_argument('--val_port', type=int, default=5556, help='Port of server for validation dataset.')
  parser.add_argument('--batch', type=int, default=64, help='Batch size.')
  parser.add_argument('--epoch', type=int, default=20, help='Number of epochs.')
  parser.add_argument('--epochsize', type=int, default=10000, help='How many frames per epoch.')
  parser.add_argument('--skipvalidate', dest='skipvalidate', action='store_true', help='Multiple path output.')
  parser.set_defaults(skipvalidate=False)
  parser.set_defaults(loadweights=False)
  args = parser.parse_args()

  model = get_model()
  **model.load_weights('/home/rohan/PycharmProjects/Comma.ai/outputs/steering_model/steering_angle.keras')**

  model.fit_generator(
    gen(20, args.host, port=args.port),
    samples_per_epoch=1000,
    nb_epoch=args.epoch,
    validation_data=gen(20, args.host, port=args.val_port),
    nb_val_samples=1000
  )

  if not os.path.exists("./outputs/steering_model"):
      os.makedirs("./outputs/steering_model")

  with open('./outputs/steering_model/steering_angle.json', 'w') as outfile:
    json.dump(model.to_json(), outfile)`

**Comment by yuuuumi** [comment]
hi, I can the same error when I tried to load the weights. Did you solve this problem?

**Comment by adrian-botta** [comment]
Hey @RohanSaphal 

2 things worth trying: 

- Since your input has the channels first, try setting your data_format in the Convolution2D function to "channels_first"

- Also, if you're running keras 2.0 or < you may want to try specifying kernel_size = (8,8) instead of just typing in the integers as the function arguments. I had a similar issue when running keras 2.1 on some code that was written for an earlier version of keras. My dimensions were swapped in the same way. But you're running the older version of keras, the first suggestion should fix the issue.

Let everyone know if it worked!
