### ISSUE TITLE
StopIteration: Tensor [...] is not an element of this graph.

### ISSUE THREAD

**Issue by olalonde** [keras-team/keras#8331]
I have recently started getting `StopIteration: Tensor Tensor("l2_norm/l2_normalize:0", shape=(?, 2048), dtype=float32) is not an element of this graph` errors when running my training `fit_generator` (it's a bit confusing because because this wasn't happening before and I'm not sure what code introduced the issue).

I believe it's a thread related issue (I'm using the model that I am training from inside my training data generator). I was wondering if there's a way to use the model I'm training from inside my generator while avoiding this issue.

Full stack trace:

```python
Epoch 1/30
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/dir/lib/python3.6/site-packages/keras/utils/data_utils.py", line 505, in get
    inputs = self.queue.get(block=True).get()
  File "/home/ubuntu/.pyenv/versions/3.6.2/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/ubuntu/.pyenv/versions/3.6.2/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ubuntu/.pyenv/versions/dir/lib/python3.6/site-packages/keras/utils/data_utils.py", line 371, in get_index
    return ds[i]
  File "/home/ubuntu/code/dir/dir/datagen.py", line 148, in __getitem__
    negatives = self.generate_negatives(anchors, paths)
  File "/home/ubuntu/code/dir/dir/datagen.py", line 127, in generate_negatives
    return self.generate_hard_negatives(images, paths)
  File "/home/ubuntu/code/dir/dir/datagen.py", line 103, in generate_hard_negatives
    vectors = self.model.predict(images)
  File "/home/ubuntu/.pyenv/versions/dir/lib/python3.6/site-packages/keras/engine/training.py", line 1710, in predict
    self._make_predict_function()
  File "/home/ubuntu/.pyenv/versions/dir/lib/python3.6/site-packages/keras/engine/training.py", line 999, in _make_predict_function
    **kwargs)
  File "/home/ubuntu/.pyenv/versions/dir/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2297, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/home/ubuntu/.pyenv/versions/dir/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2246, in __init__
    with tf.control_dependencies(self.outputs):
  File "/home/ubuntu/.pyenv/versions/dir/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3936, in control_dependencies
    return get_default_graph().control_dependencies(control_inputs)
  File "/home/ubuntu/.pyenv/versions/dir/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3665, in control_dependencies
    c = self.as_graph_element(c)
  File "/home/ubuntu/.pyenv/versions/dir/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2708, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/ubuntu/.pyenv/versions/dir/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2787, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("l2_norm/l2_normalize:0", shape=(?, 2048), dtype=float32) is not an element of this graph.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./scripts/train", line 197, in <module>
    train(**vars(parser.parse_args()))
  File "./scripts/train", line 117, in train
    initial_epoch=initial_epoch,
  File "/home/ubuntu/.pyenv/versions/dir/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/.pyenv/versions/dir/lib/python3.6/site-packages/keras/engine/training.py", line 2011, in fit_generator
    generator_output = next(output_generator)
  File "/home/ubuntu/.pyenv/versions/dir/lib/python3.6/site-packages/keras/utils/data_utils.py", line 510, in get
    raise StopIteration(e)
StopIteration: Tensor Tensor("l2_norm/l2_normalize:0", shape=(?, 2048), dtype=float32) is not an element of this graph.
```

Related: https://github.com/fchollet/keras/issues/6462 https://github.com/fchollet/keras/issues/5511 https://github.com/fchollet/keras/issues/2397

**Comment by olalonde** [comment]
Calling `model._make_predict_function()` after loading/creating the model seemed to work.
