### ISSUE TITLE
Error when using dropout and initial_state in gru layer

### ISSUE THREAD

**Issue by ha2emnomer** [keras-team/keras#8407]
my code is:
`_costs_embd = TimeDistributed(
        Dense(costs_embd_size, kernel_initializer=RandomUniform(-0.08, 0.08)))(costs)
    _search_1 = GRU(h_search, return_sequences=True, kernel_initializer=RandomUniform(-0.08, 0.08),
                    dropout=dropout)(_costs_embd, initial_state=[state_h])`
The error shown is: 
`Traceback (most recent call last):
  File "main.py", line 21, in <module>
    dropout=0.2)
  File "/home/hazem/PycharmProjects/optimizer-memory-network/optimzernet.py", line 50, in build_agent
    _costs_embd, initial_state=[state_h])
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.py", line 519, in __call__
    output = super(RNN, self).__call__(full_input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 603, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.py", line 1503, in call
    self.cell._generate_dropout_mask(inputs, training=training)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.py", line 1268, in _generate_dropout_mask
    ones = K.ones_like(K.squeeze(inputs[:, 0:1, :], axis=1))
TypeError: list indices must be integers, not tuple
`
Removing dropout or initial_state argument seems to solve the problem but you can't use them both
Any help on this issue ?

**Comment by muximus3** [comment]
get the same issue, when implements seq2seq,
```
        decoder_outputs, decoder_state_h, decoder_state_c = LSTM(self.lstm_unit, name='decoder', return_sequences=True,
                                                                 return_state=True,
                                                                 dropout=self.drop_out)(d, initial_state=encoder_states)
```

**Comment by LitleCarl** [comment]
face the same issue, as far as I know this should be a bug.

**Comment by LitleCarl** [comment]
As a simple workaround, go ahead to pip package source and make the change:
**"............../site-packages/keras/layers/recurrent.py"**
In method:
 `_generate_recurrent_dropout_mask`
`_generate_dropout_mask`

Insert the code into the first line of the methods:
```
if type(inputs) is list:
            inputs = inputs[0]
```
When you specify initial_state, the actual input becomes (`samples`, `state_1`, `state_2`....), but we only need the first element representing train data here.

**Comment by baregawi** [comment]
Thank you very much @LitleCarl . The above worked for me.

As a note for others there is set of those methods for each recurrent model so make sure you augment all the ones you need or all of them.

**Comment by yudazilian** [comment]
I face the same problem when I use lstm...
```
decoder_fw_0 = LSTM(latent_dim, return_sequences=True, return_state=True, dropout=0.2)
decoder_fw_0_outputs, _, _ = decoder_fw_0(decoder_inputs, initial_state=encoder_f_states_0)
```

Error message is as below:
```
 File "seq2seq_ntm_bi_2.py", line 154, in <module>
    decoder_fw_0_outputs, _, _ = decoder_fw_0(decoder_inputs, initial_state=encoder_f_states_0)
  File "/Users/yudelin/.pyenv/versions/keras2/lib/python2.7/site-packages/keras/layers/recurrent.py", line 518, in __call__
    output = super(RNN, self).__call__(full_input, **kwargs)
  File "/Users/yudelin/.pyenv/versions/keras2/lib/python2.7/site-packages/keras/engine/topology.py", line 603, in __call__
    output = self.call(inputs, **kwargs)
  File "/Users/yudelin/.pyenv/versions/keras2/lib/python2.7/site-packages/keras/layers/recurrent.py", line 2019, in call
    self.cell._generate_recurrent_dropout_mask(inputs, training=training)
  File "/Users/yudelin/.pyenv/versions/keras2/lib/python2.7/site-packages/keras/layers/recurrent.py", line 1781, in _generate_recurrent_dropout_mask
    ones = K.ones_like(K.reshape(inputs[:, 0, 0], (-1, 1)))
```

**Comment by arkgithubforyou** [comment]
this happens to GRU with linux keras=2.1.2, tf-gpu=1.4.0
while on a windows laptop all worked fine.

**Comment by beatrizalbiero** [comment]
Hi @LitleCarl, how can i change the keras source code? 
I tried but when I ran my code again (after restarting my kernel) it seemed to me that my changes were inefficient.
