### ISSUE TITLE
Missing CONTRIBUTING.md file from PyPI distribution

### ISSUE THREAD

**Issue by radarsat1** [keras-team/keras#8433]
It seems the PyPI download is missing CONTRIBUTING.md:

```
$ wget 'https://pypi.python.org/packages/74/73/e92890cc968906427e51c2b687438702541200e9564992b6d1b37fc8275a/Keras-2.0.9.tar.gz#md5=df23e822e5292feaff704cb751d8fe61'
$ tar -xzf Keras-2.0.9.tar.gz
$ cd Keras-2.0.9/docs
$ PYTHONPATH=.. python autogen.py 
Using Theano backend.
Cleaning up existing sources directory.
Populating sources directory with templates.
Starting autogeneration.
...inserting autogenerated content into template: sources/models/sequential.md
...inserting autogenerated content into template: sources/models/model.md
...creating new page with autogenerated content: sources/layers/core.md
...creating new page with autogenerated content: sources/layers/convolutional.md
...creating new page with autogenerated content: sources/layers/pooling.md
...creating new page with autogenerated content: sources/layers/local.md
...creating new page with autogenerated content: sources/layers/recurrent.md
...creating new page with autogenerated content: sources/layers/embeddings.md
...creating new page with autogenerated content: sources/layers/normalization.md
...creating new page with autogenerated content: sources/layers/advanced-activations.md
...creating new page with autogenerated content: sources/layers/noise.md
...creating new page with autogenerated content: sources/layers/merge.md
...creating new page with autogenerated content: sources/layers/wrappers.md
...inserting autogenerated content into template: sources/metrics.md
...inserting autogenerated content into template: sources/losses.md
...inserting autogenerated content into template: sources/initializers.md
...inserting autogenerated content into template: sources/optimizers.md
...inserting autogenerated content into template: sources/callbacks.md
...inserting autogenerated content into template: sources/activations.md
...inserting autogenerated content into template: sources/backend.md
...creating new page with autogenerated content: sources/utils.md
Traceback (most recent call last):
  File "autogen.py", line 577, in <module>
    shutil.copyfile('../CONTRIBUTING.md', 'sources/contributing.md')
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'../CONTRIBUTING.md'
$ touch ../CONTRIBUTING.md
$ PYTHONPATH=.. python autogen.py 
Using Theano backend.
Cleaning up existing sources directory.
Populating sources directory with templates.
Starting autogeneration.
...inserting autogenerated content into template: sources/models/sequential.md
...inserting autogenerated content into template: sources/models/model.md
...creating new page with autogenerated content: sources/layers/core.md
...creating new page with autogenerated content: sources/layers/convolutional.md
...creating new page with autogenerated content: sources/layers/pooling.md
...creating new page with autogenerated content: sources/layers/local.md
...creating new page with autogenerated content: sources/layers/recurrent.md
...creating new page with autogenerated content: sources/layers/embeddings.md
...creating new page with autogenerated content: sources/layers/normalization.md
...creating new page with autogenerated content: sources/layers/advanced-activations.md
...creating new page with autogenerated content: sources/layers/noise.md
...creating new page with autogenerated content: sources/layers/merge.md
...creating new page with autogenerated content: sources/layers/wrappers.md
...inserting autogenerated content into template: sources/metrics.md
...inserting autogenerated content into template: sources/losses.md
...inserting autogenerated content into template: sources/initializers.md
...inserting autogenerated content into template: sources/optimizers.md
...inserting autogenerated content into template: sources/callbacks.md
...inserting autogenerated content into template: sources/activations.md
...inserting autogenerated content into template: sources/backend.md
...creating new page with autogenerated content: sources/utils.md
$
```

Would it be possible to include it in the next release to make it possible to completely build Keras and docs from the PyPI distro?

**Comment by radarsat1** [comment]
Thanks :)
