### ISSUE TITLE
VGG16 weights not downloadable

### ISSUE THREAD

**Issue by rish-16** [keras-team/keras#8548]
I am new to Keras and was learning about the application of the VGG16 model. I wrote the following code straight from the docs:

```
from keras.applications.vgg16 import VGG16
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
import numpy as np

model = VGG16(weights='imagenet', include_top=False)

img_path = 'elephant.jpg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

features = model.predict(x)
```

I tried to download the imagenet weights from the github repo. I always run into this error:

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "IV3.py", line 6, in <module>
    model = VGG16(weights='imagenet', include_top=False)
  File "/usr/local/lib/python3.6/site-packages/keras/applications/vgg16.py", line 169, in VGG16
    model.load_weights(weights_path)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/topology.py", line 2532, in load_weights
    f = h5py.File(filepath, mode='r')
  File "/usr/local/lib/python3.6/site-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python3.6/site-packages/h5py/_hl/files.py", line 101, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-gkjbrkhs-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-gkjbrkhs-build/h5py/_objects.c:2798)
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-gkjbrkhs-build/h5py/h5f.c:2117)
OSError: Unable to open file (Truncated file: eof = 1458176, sblock->base_addr = 0, stored_eoa = 58889256)
```

**Comment by GKalliatakis** [comment]
Have a look at issue https://github.com/fchollet/keras/issues/6221

**Comment by rish-16** [comment]
Just saw the message @GKalliatakis Thank you! I'm able to download the weights for the VGG16 model now.
