### ISSUE TITLE
Cannot restore model when Lambda is added by python method

### ISSUE THREAD

**Issue by christian-rauch** [keras-team/keras#8599]
I am running with Keras 2.1.1 + TensoFlow 1.4.

This example program saves and loads a simple model with lambda functions to/from json:

```
#!/usr/bin/env python
import keras.backend as K
from keras.models import Model
from keras.layers import Input, Lambda
from keras.layers.merge import Concatenate
from keras.models import model_from_json
import tensorflow as tf
import json


def remove_slice(tensor, index):
    lower_slices = Lambda(lambda x: x[:, :, :, :index])(tensor)
    upper_slices = Lambda(lambda x: x[:, :, :, (index+1):])(tensor)
    x = Concatenate(name="slice_"+str(index))([lower_slices] + [upper_slices])
    return x


if __name__ == '__main__':
    w=320
    h=240
    nprobs=18+1

    probs_in = Input(shape=(h, w, nprobs))

    slices = []
    for i in range(nprobs):
        # throws: "TypeError: arg 5 (closure) must be None or tuple"
        slice_i = remove_slice(tensor=probs_in, index=i)

        # OK
        # lower_slices = Lambda(lambda x, i: x[:, :, :, :i], arguments={'i':i})(probs_in)
        # upper_slices = Lambda(lambda x, i: x[:, :, :, (i+1):], arguments={'i':i})(probs_in)
        # slice_i = Concatenate(name="slice_"+str(i))([lower_slices] + [upper_slices])
        
        x = Lambda(K.sum, arguments={'axis':-1, 'keepdims':True})(slice_i)
        slices.append(x)

    x = Concatenate(name="concat_all")(slices)

    model = Model(inputs=probs_in, outputs=x, name="slice_test")

    # save and load
    with open("test2.json", 'w') as f:
        f.write(model.to_json(indent=4))

    with open("test2.json", 'r') as f:
        model2 = model_from_json(f.read(), custom_objects={'tf':tf})

```

Restoring the model with `model_from_json` fails with (keras master):
```
Traceback (most recent call last):
  File "./slice_test2.py", line 52, in <module>
    model2 = model_from_json(f.read(), custom_objects={'tf':tf})
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 346, in model_from_json
  File "build/bdist.linux-x86_64/egg/keras/layers/__init__.py", line 55, in deserialize
  File "build/bdist.linux-x86_64/egg/keras/utils/generic_utils.py", line 140, in deserialize_keras_object
  File "build/bdist.linux-x86_64/egg/keras/engine/topology.py", line 2490, in from_config
  File "build/bdist.linux-x86_64/egg/keras/engine/topology.py", line 2476, in process_layer
  File "build/bdist.linux-x86_64/egg/keras/layers/__init__.py", line 55, in deserialize
  File "build/bdist.linux-x86_64/egg/keras/utils/generic_utils.py", line 140, in deserialize_keras_object
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 699, in from_config
  File "build/bdist.linux-x86_64/egg/keras/utils/generic_utils.py", line 209, in func_load
TypeError: arg 5 (closure) must be None or tuple
```

and on keras stable 2.1.1 in ipython respectively:
```
<ipython-input-12-b3a9a7af6c69> in <module>()
----> 1 m = model_from_json(open( "/disk/scratch_big/cr_results/pwp3_jheat_sigma5_save2/pwp_model.json" ).read())

/disk/scratch_ssd/christian/lib/python2.7/site-packages/keras/models.pyc in model_from_json(json_string, custom_objects)
    344     """
    345     config = json.loads(json_string)
--> 346     return layer_module.deserialize(config, custom_objects=custom_objects)
    347 
    348 

/disk/scratch_ssd/christian/lib/python2.7/site-packages/keras/layers/__init__.pyc in deserialize(config, custom_objects)
     53                                     module_objects=globs,
     54                                     custom_objects=custom_objects,
---> 55                                     printable_module_name='layer')

/disk/scratch_ssd/christian/lib/python2.7/site-packages/keras/utils/generic_utils.pyc in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    137                 return cls.from_config(config['config'],
    138                                        custom_objects=dict(list(_GLOBAL_CUSTOM_OBJECTS.items()) +
--> 139                                                            list(custom_objects.items())))
    140             with CustomObjectScope(custom_objects):
    141                 return cls.from_config(config['config'])

/disk/scratch_ssd/christian/lib/python2.7/site-packages/keras/engine/topology.pyc in from_config(cls, config, custom_objects)
   2488         # First, we create all layers and enqueue nodes to be processed
   2489         for layer_data in config['layers']:
-> 2490             process_layer(layer_data)
   2491         # Then we process nodes in order of layer depth.
   2492         # Nodes that cannot yet be processed (if the inbound node

/disk/scratch_ssd/christian/lib/python2.7/site-packages/keras/engine/topology.pyc in process_layer(layer_data)
   2474 
   2475             layer = deserialize_layer(layer_data,
-> 2476                                       custom_objects=custom_objects)
   2477             created_layers[layer_name] = layer
   2478 

/disk/scratch_ssd/christian/lib/python2.7/site-packages/keras/layers/__init__.pyc in deserialize(config, custom_objects)
     53                                     module_objects=globs,
     54                                     custom_objects=custom_objects,
---> 55                                     printable_module_name='layer')

/disk/scratch_ssd/christian/lib/python2.7/site-packages/keras/utils/generic_utils.pyc in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    137                 return cls.from_config(config['config'],
    138                                        custom_objects=dict(list(_GLOBAL_CUSTOM_OBJECTS.items()) +
--> 139                                                            list(custom_objects.items())))
    140             with CustomObjectScope(custom_objects):
    141                 return cls.from_config(config['config'])

/disk/scratch_ssd/christian/lib/python2.7/site-packages/keras/layers/core.pyc in from_config(cls, config, custom_objects)
    697         elif function_type == 'lambda':
    698             # Unsafe deserialization from bytecode
--> 699             function = func_load(config['function'], globs=globs)
    700         else:
    701             raise TypeError('Unknown function type:', function_type)

/disk/scratch_ssd/christian/lib/python2.7/site-packages/keras/utils/generic_utils.pyc in func_load(code, defaults, closure, globs)
    204                                      name=code.co_name,
    205                                      argdefs=defaults,
--> 206                                      closure=closure)
    207 
    208 

TypeError: arg 5 (closure) must be None or tuple
```

If I do the slicing directly (see comments in the code) without calling `remove_slice`, the storing/loading works as expected.

I am wondering why this happens, since `remove_slice` is actually not a layer or lambda function, it just adds additional layers, i.e. it is not part of the model.

**Comment by christian-rauch** [comment]
If you define the Lambda in `remove_slice` properly like this (e.g. with arguments):
```
def remove_slice(tensor, index):
    lower_slices = Lambda(lambda x, i: x[:, :, :, :i], arguments={'i':index})(tensor)
    upper_slices = Lambda(lambda x, i: x[:, :, :, (i+1):], arguments={'i':index})(tensor)
    x = Concatenate(name="slice_"+str(index))([lower_slices] + [tensor])
    return x
```
the restoring also works. The issue is actually the definition of the `Lambda` with/without `arguments`.

However, using `Lambda` without `arguments` worked before for me.

Can we have an error or at least warning, if you attempt to store a model with Lambdas that cannot be restored?
