### ISSUE TITLE
TypeError: unhashable type: 'Dimension'

### ISSUE THREAD

**Issue by ghost** [keras-team/keras#8608]
I want to do style change of photos,but I got an Error like the title

`import numpy as np
from keras.applications.imagenet_utils import preprocess_input
from keras.applications.vgg16 import VGG16
from keras.models import Model, Sequential
from keras.layers import Dense
import reader
from keras.optimizers import SGD
from PIL import Image
import keras.backend as K

def get_content_loss(A, B):
    content_loss = K.sum(K.square(A - B) / 2 / 512 / 14 / 14 / 256 / 256)
    return content_loss

def get_style_loss(a, f):
    a_reshape = K.reshape(a, [512, 14 * 14])
    f_reshape = K.reshape(f, [512, 14 * 14])
    e_a = K.dot(a_reshape, K.transpose(a_reshape))
    e_f = K.dot(f_reshape, K.transpose(f_reshape))
    e_l = K.sum((K.square(e_a - e_f))) / 4 / 14 / 14 / 512 / 512
    return e_l

def show_image(image_arr, step):
    r = Image.fromarray(image_arr[0], "L")
    g = Image.fromarray(image_arr[1], "L")
    b = Image.fromarray(image_arr[2], "L")
    image_save = Image.merge("RGB", (r, g, b))
    # image.show()
    image_save.save("./image/" + str(step) + ".png")

def get_nontrainable_model(name, model_origin):
    nontrainable_model = Model(inputs=model_origin.input, outputs=model_origin.get_layer(name).output)
    nontrainable_model.trainable = False
    return nontrainable_model

def loss(y, y_mean):
    print(y)
    print(y_mean)
    # y = 1,512 * 14 * 14
    y_predict = block5_conv1(K.reshape(y, shape=[1, 224, 224, 3]))
    y_predict = K.transpose(K.reshape(y_predict, shape=[14 * 14, 512]))  # 512,14*14
    loss_sum = get_content_loss(y_predict, origin_predict) + get_style_loss(y_predict, style_predict)
    return loss_sum

# read data
input_origin = reader.load_img(r"./data/dog.png")  # 1,224,224,3
input_style = reader.load_img(r"./data/style.png")  # 1,224,224,3
input_origin_img_arr = K.constant(input_origin)
input_style_img_arr = K.constant(input_style)

# cnn predict
model_vgg = VGG16(weights='imagenet')
block5_conv1 = get_nontrainable_model("block5_conv1", model_vgg)
origin_predict = block5_conv1(input_origin_img_arr)  # 1,14,14,512
origin_predict = K.transpose(K.reshape(origin_predict, shape=[14 * 14, 512]))  # 512,114*14
style_predict = block5_conv1(input_style_img_arr)  # 1,14,14,512
style_predict = K.transpose(K.reshape(style_predict, shape=[14 * 14, 512]))  # 512,114*14

# model
model = Sequential()  # model input None,150528
model.add(Dense(150528, input_shape=[150528], activation='relu'))
sgd = SGD(lr=0.01, decay=1e-4, momentum=0.9, nesterov=True)
model.compile(loss=loss, optimizer=sgd)

x_train = K.reshape(input_origin_img_arr, shape=[1, 150528])
for i in range(0, 100):
    model.fit(x=x_train, y=x_train, batch_size=1, epochs=1)
    model.save("./model/keras_model.h5", overwrite=True, include_optimizer=True)
`

And the error log below:
`Traceback (most recent call last):
  File "C:/Users/XXX/Desktop/03_python/image_style_transfer/test.py", line 75, in <module>
    model.fit(x=x_train, y=x_train, batch_size=1, epochs=1)
  File "C:\Program Files\Python36\lib\site-packages\keras\models.py", line 960, in fit
    validation_steps=validation_steps)
  File "C:\Program Files\Python36\lib\site-packages\keras\engine\training.py", line 1574, in fit
    batch_size=batch_size)
  File "C:\Program Files\Python36\lib\site-packages\keras\engine\training.py", line 1419, in _standardize_user_data
    _check_array_lengths(x, y, sample_weights)
  File "C:\Program Files\Python36\lib\site-packages\keras\engine\training.py", line 235, in _check_array_lengths
    set_x = set_of_lengths(inputs)
  File "C:\Program Files\Python36\lib\site-packages\keras\engine\training.py", line 233, in set_of_lengths
    return set([0 if y is None else y.shape[0] for y in x])
TypeError: unhashable type: 'Dimension'`

Is there anybody can help me or got the same

**Comment by wangzhenhui1992** [comment]
I have seen that  fit() can not work well on tensor
I use np.array target to do,but got another error

`
import numpy as np
from keras.applications.imagenet_utils import preprocess_input
from keras.applications.vgg16 import VGG16
from keras.models import Model, Sequential
from keras.layers import Dense
import reader
from keras.optimizers import SGD
from PIL import Image
import keras.backend as K


def get_content_loss(A, B):
    content_loss = K.sum(K.square(A - B) / 2 / 512 / 14 / 14 / 256 / 256)
    return content_loss


def get_style_loss(a, f):
    a_reshape = K.reshape(a, [512, 14 * 14])
    f_reshape = K.reshape(f, [512, 14 * 14])
    e_a = K.dot(a_reshape, K.transpose(a_reshape))
    e_f = K.dot(f_reshape, K.transpose(f_reshape))
    e_l = K.sum((K.square(e_a - e_f))) / 4 / 14 / 14 / 512 / 512
    return e_l


def show_image(image_arr, step):
    r = Image.fromarray(image_arr[0], "L")
    g = Image.fromarray(image_arr[1], "L")
    b = Image.fromarray(image_arr[2], "L")
    image_save = Image.merge("RGB", (r, g, b))
    # image.show()
    image_save.save("./image/" + str(step) + ".png")


def get_nontrainable_model(name, model_origin):
    nontrainable_model = Model(inputs=model_origin.input, outputs=model_origin.get_layer(name).output)
    nontrainable_model.trainable = False
    return nontrainable_model


def loss(y, y_mean):
    print(y)
    print(y_mean)
    # y = 1,512 * 14 * 14
    y_predict = block5_conv1(K.reshape(y, shape=[1, 224, 224, 3]))
    y_predict = K.transpose(K.reshape(y_predict, shape=[14 * 14, 512]))  # 512,14*14
    loss_sum = get_content_loss(y_predict, K.constant(origin_predict)) + get_style_loss(y_predict, K.constant(style_predict))
    return loss_sum


# read data
input_origin = reader.load_img(r"./data/dog.png")  # 1,224,224,3
input_style = reader.load_img(r"./data/style.png")  # 1,224,224,3

# cnn model
model_vgg = VGG16(weights='imagenet')
block5_conv1 = get_nontrainable_model("block5_conv1", model_vgg)

# cnn predict
origin_predict = block5_conv1.predict(input_origin).reshape([14 * 14, 512]).T  # 1,14,14,512
style_predict = block5_conv1.predict(input_style).reshape([14 * 14, 512]).T  # 1,14,14,512

# model
model = Sequential()  # model input None,150528
model.add(Dense(150528, input_shape=[150528], activation='relu'))
sgd = SGD(lr=0.01, decay=1e-4, momentum=0.9, nesterov=True)
model.compile(loss=loss, optimizer=sgd)

x_train = np.reshape(input_origin, [1, 150528])
for i in range(0, 100):
    model.fit(x=x_train, y=x_train, batch_size=1, epochs=1)
    model.save("./model/keras_model.h5", overwrite=True, include_optimizer=True)
`


`Traceback (most recent call last):
  File "C:/Users/Desktop/03_python/image_style_transfer/test.py", line 73, in <module>
    model.fit(x=x_train, y=x_train, batch_size=1, epochs=1)
  File "C:\Program Files\Python36\lib\site-packages\keras\models.py", line 960, in fit
    validation_steps=validation_steps)
  File "C:\Program Files\Python36\lib\site-packages\keras\engine\training.py", line 1627, in fit
    self._make_train_function()
  File "C:\Program Files\Python36\lib\site-packages\keras\engine\training.py", line 990, in _make_train_function
    loss=self.total_loss)
  File "C:\Program Files\Python36\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\keras\optimizers.py", line 168, in get_updates
    v = self.momentum * m - lr * g  # velocity
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\math_ops.py", line 885, in binary_op_wrapper
    y = ops.convert_to_tensor(y, dtype=x.dtype.base_dtype, name="y")
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 836, in convert_to_tensor
    as_ref=False)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 926, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\constant_op.py", line 229, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\constant_op.py", line 208, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 371, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.`

**Comment by wangzhenhui1992** [comment]
It may be caused by my loss function,I should use y_mean but not y.
I fixed it but i went with another error

`Epoch 1/1
2017-11-28 16:06:14.300467: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\framework\op_kernel.cc:1182] Invalid argument: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 150528
  }
  dim {
    size: 150528
  }
}
float_val: 0

2017-11-28 16:06:14.301467: E C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\common_runtime\executor.cc:643] Executor failed to create kernel. Invalid argument: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 150528
  }
  dim {
    size: 150528
  }
}
float_val: 0

	 [[Node: training/SGD/Const = Const[dtype=DT_FLOAT, value=<Invalid TensorProto: dtype: DT_FLOAT tensor_shape { dim { size: 150528 } dim { size: 150528 } } float_val: 0>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
2017-11-28 16:06:14.303467: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\framework\op_kernel.cc:1182] Invalid argument: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 150528
  }
  dim {
    size: 150528
  }
}
float_val: 0

2017-11-28 16:06:14.304467: E C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\common_runtime\executor.cc:643] Executor failed to create kernel. Invalid argument: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 150528
  }
  dim {
    size: 150528
  }
}
float_val: 0

	 [[Node: training/SGD/Const = Const[dtype=DT_FLOAT, value=<Invalid TensorProto: dtype: DT_FLOAT tensor_shape { dim { size: 150528 } dim { size: 150528 } } float_val: 0>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1323, in _do_call
    return fn(*args)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1302, in _run_fn
    status, run_metadata)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 150528
  }
  dim {
    size: 150528
  }
}
float_val: 0

	 [[Node: training/SGD/Const = Const[dtype=DT_FLOAT, value=<Invalid TensorProto: dtype: DT_FLOAT tensor_shape { dim { size: 150528 } dim { size: 150528 } } float_val: 0>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/03_python/image_style_transfer/test.py", line 73, in <module>
    model.fit(x=x_train, y=x_train, batch_size=1, epochs=1)
  File "C:\Program Files\Python36\lib\site-packages\keras\models.py", line 960, in fit
    validation_steps=validation_steps)
  File "C:\Program Files\Python36\lib\site-packages\keras\engine\training.py", line 1650, in fit
    validation_steps=validation_steps)
  File "C:\Program Files\Python36\lib\site-packages\keras\engine\training.py", line 1213, in _fit_loop
    outs = f(ins_batch)
  File "C:\Program Files\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 2350, in __call__
    session = get_session()
  File "C:\Program Files\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 188, in get_session
    session.run(tf.variables_initializer(uninitialized_vars))
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
    run_metadata_ptr)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1317, in _do_run
    options, run_metadata)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 150528
  }
  dim {
    size: 150528
  }
}
float_val: 0

	 [[Node: training/SGD/Const = Const[dtype=DT_FLOAT, value=<Invalid TensorProto: dtype: DT_FLOAT tensor_shape { dim { size: 150528 } dim { size: 150528 } } float_val: 0>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'training/SGD/Const', defined at:
  File "C:/03_python/image_style_transfer/test.py", line 73, in <module>
    model.fit(x=x_train, y=x_train, batch_size=1, epochs=1)
  File "C:\Program Files\Python36\lib\site-packages\keras\models.py", line 960, in fit
    validation_steps=validation_steps)
  File "C:\Program Files\Python36\lib\site-packages\keras\engine\training.py", line 1627, in fit
    self._make_train_function()
  File "C:\Program Files\Python36\lib\site-packages\keras\engine\training.py", line 990, in _make_train_function
    loss=self.total_loss)
  File "C:\Program Files\Python36\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\keras\optimizers.py", line 165, in get_updates
    moments = [K.zeros(shape) for shape in shapes]
  File "C:\Program Files\Python36\lib\site-packages\keras\optimizers.py", line 165, in <listcomp>
    moments = [K.zeros(shape) for shape in shapes]
  File "C:\Program Files\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 675, in zeros
    return variable(tf.constant_initializer(0., dtype=tf_dtype)(shape),
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\init_ops.py", line 200, in __call__
    self.value, dtype=dtype, shape=shape, verify_shape=verify_shape)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\constant_op.py", line 214, in constant
    name=name).outputs[0]
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 150528
  }
  dim {
    size: 150528
  }
}
float_val: 0

	 [[Node: training/SGD/Const = Const[dtype=DT_FLOAT, value=<Invalid TensorProto: dtype: DT_FLOAT tensor_shape { dim { size: 150528 } dim { size: 150528 } } float_val: 0>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

`



and is this a bugger
