### ISSUE TITLE
upcast to float64 in theano_backend.truncated_normal

### ISSUE THREAD

**Issue by ascripter** [keras-team/keras#8709]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).
-------------------
When using one of lecun_normal, he_normal or glorot_normal **initializers**, theano upcasts to float64. The error is raised (with theano.config.warn_float64=raise) in the subject's function. The problem however is the functions stddev which originates in initialiers.VarianceScaling lin 206: stddev = np.sqrt(scale). np.sqrt returns type np.float64, and this seems to trigger theano to upcast everything after it also to float 64. By changing the line to: stddev = float(np.sqrt(scale)) the issue is solved.

Example code to trigger the error:
```
import keras, theano
print "Keras version %s" %keras.__version__
print "Theano version %s" %theano.__version__

theano.config.warn_float64 = "raise"
theano.config.floatX = "float32"
model = keras.models.Sequential()
model.add(
    keras.layers.core.Dense(
        100,
        kernel_initializer="he_normal",        
        input_dim=25
    )
)
```
And the traceback:
```
Using Theano backend.
Keras version 2.1.2
Theano version 1.0.0
Traceback (most recent call last):
  File "/home/andreas/untitled0.py", line 18, in <module>
    input_dim=25
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 464, in add
    layer(x)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 576, in __call__
    self.build(input_shapes[0])
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 830, in build
    constraint=self.kernel_constraint)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 397, in add_weight
    weight = K.variable(initializer(shape),
  File "/usr/local/lib/python2.7/dist-packages/keras/initializers.py", line 208, in __call__
    dtype=dtype, seed=self.seed)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 2267, in truncated_normal
    normal_tensor = rng.normal(size=shape, avg=mean, std=stddev, dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/rng_mrg.py", line 1071, in normal
    std = undefined_grad(as_tensor_variable(std))
  File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 2130, in undefined_grad
    return undefined_grad_(x)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/ops.py", line 56, in make_node
    return gof.Apply(self, [x], [x.type()])
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/type.py", line 419, in __call__
    return utils.add_tag_trace(self.make_variable(name))
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/type.py", line 352, in make_variable
    return self.Variable(self, name=name)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/var.py", line 852, in __init__
    raise Exception(msg)
Exception: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}.
```

**Comment by ascripter** [comment]
For the xxx_uniform the same problem exists, but it can also be solved by changing initializers.VarianceScaling from:
```
210: limit = np.sqrt(3. * scale)
```
in
```
210: limit = float(np.sqrt(3. * scale))
```
