### ISSUE TITLE
Unicode error when loading old model

### ISSUE THREAD

**Issue by tstandley** [keras-team/keras#8738]
the code:

```
import keras
keras.models.load_model('models/shape_aware.h5')
```

fails with the following error in keras 2.1.2. Works fine in keras 2.1.1

Here's a google drive link to the actual file so you can reproduce:
https://drive.google.com/open?id=1s3_LyNh1lrN4U2iCYEHzXEwNNH5SP0-b

The model was trained with 2.0.5 if that helps.
Thanks!
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 240, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 314, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/generic_utils.py", line 140, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 2490, in from_config
    process_layer(layer_data)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 2476, in process_layer
    custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/generic_utils.py", line 140, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/core.py", line 699, in from_config
    function = func_load(config['function'], globs=globs)
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/generic_utils.py", line 224, in func_load
    raw_code = codecs.decode(code.encode('ascii'), 'base64')
UnicodeEncodeError: 'ascii' codec can't encode character '\xe3' in position 0: ordinal not in range(128)

```

**Comment by cdhimmel** [comment]
I am also having the issue with keras 2.1.2, with Python 3.6.

**Comment by fchollet** [comment]
This is likely solved by: https://github.com/fchollet/keras/pull/8762

Please pull master, reinstall and retry.

**Comment by ozgurshn** [comment]
I'm using Keras 2.2.5 in Colab and encountered this issue when I try to load [old OpenFace](https://github.com/ozgurshn/Keras-OpenFace/blob/master/model/nn4.small2.v1.h5) model.
<img width="1293" alt="Screen Shot 2020-02-19 at 16 35 50" src="https://user-images.githubusercontent.com/2404074/74839204-efd04f80-5335-11ea-836d-96657537509c.png">
