### ISSUE TITLE
the InvalidArgumentError of the tensorboard

### ISSUE THREAD

**Issue by williamli186** [keras-team/keras#8808]
Hi:
  I want to record the change of the lost use the "tf.summary.scalar",  but there is a InvalidArgumentError, I cann't find the reason
![1](https://user-images.githubusercontent.com/31270354/34066038-ffd25640-e243-11e7-8bcc-182aca8e388e.PNG)
                                                                                  **figure 1**
![2](https://user-images.githubusercontent.com/31270354/34066114-1d0303b2-e245-11e7-9bab-401b490746a4.PNG)
                                                                                  **figure 2**
**thank you very much!**

The tensorflow code:
```
import tensorflow as tf

x = tf.placeholder(tf.float32)
W = tf.Variable(0 , dtype = tf.float32)
b = tf.Variable(0 , dtype = tf.float32)
y_ = tf.placeholder(tf.float32)

y = W * x + b

lost = tf.reduce_mean(tf.square(y_ - y))
    
optimizer = tf.train.GradientDescentOptimizer(0.01)
train_step = optimizer.minimize(lost)

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

tf.summary.scalar('lost' , lost)
merged = tf.summary.merge_all()
writer = tf.summary.FileWriter("./logs", graph=tf.get_default_graph())

steps = 1000
for i in range(steps):
    xs = 1
    ys = 3
    feed = { x: xs, y_: ys }
    sess.run(train_step , feed_dict=feed)
    xs = 2
    ys = 5
    feed = { x: xs, y_: ys }

    _ , rs = sess.run([train_step , merged] , feed_dict=feed)    
    writer.add_summary(rs, i)
    
print("W: %f" % sess.run(W))
print("b: %f" % sess.run(b))
```
the result of compiling:
```
Traceback (most recent call last):

  File "<ipython-input-11-66eb2d566452>", line 1, in <module>
    runfile('C:/Users/Administrator/.spyder-py3/temp.py', wdir='C:/Users/Administrator/.spyder-py3')

  File "C:\Program Files\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Program Files\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Administrator/.spyder-py3/temp.py", line 37, in <module>
    _ , rs = sess.run([train_step , merged] , feed_dict=feed)

  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)

  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)

  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    options, run_metadata)

  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_17' with dtype float
	 [[Node: Placeholder_17 = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'Placeholder_17', defined at:
  File "C:\Program Files\Anaconda3\lib\site-packages\spyder\utils\ipython\start_kernel.py", line 223, in <module>
    main()
  File "C:\Program Files\Anaconda3\lib\site-packages\spyder\utils\ipython\start_kernel.py", line 219, in main
    kernel.start()
  File "C:\Program Files\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "C:\Program Files\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 162, in start
    super(ZMQIOLoop, self).start()
  File "C:\Program Files\Anaconda3\lib\site-packages\tornado\ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "C:\Program Files\Anaconda3\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "C:\Program Files\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Program Files\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Program Files\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Program Files\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "C:\Program Files\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Program Files\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Program Files\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2827, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Program Files\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-66eb2d566452>", line 1, in <module>
    runfile('C:/Users/Administrator/.spyder-py3/temp.py', wdir='C:/Users/Administrator/.spyder-py3')
  File "C:\Program Files\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)
  File "C:\Program Files\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "C:/Users/Administrator/.spyder-py3/temp.py", line 10, in <module>
    y_ = tf.placeholder(tf.float32)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1548, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 2094, in _placeholder
    name=name)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder_17' with dtype float
	 [[Node: Placeholder_17 = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
```

**Comment by gabrieldemarmiesse** [comment]
Hi!
I think this issue is more related to Tensorflow than Keras. Maybe you'll have more success if you close this issue here and open the same one in the Tensorflow repository?
Cheers.

**Comment by williamli186** [comment]
Hi:
  my code compiler of tensorflow is Anaconda spyder, and the code is ok when start the spyder for the first compilation(the tensorboard is ok also) ,  a second compilation will result this error.
  I'm very confused about that ，and I couldn't find the cause

thank you!

**Comment by gabrieldemarmiesse** [comment]
Hi,

Well, neither of your compilations mention keras, just Tensorflow. So you'll have more luck on the Tensorflow repository. Here, users are used to use the tensorboard keras callback. Since you're not using keras function, you should file this issue in the Tensorflow repo where people are used to deal with tensorboard directly. For my part, I don't know how to use tensorboard like you do. I use the keras callback. I'm just telling you where to look for help. Because this isn't the right place, I'm sorry about that.

Cheers.

**Comment by williamli186** [comment]
I get it, thank you very much!

**Comment by gabrieldemarmiesse** [comment]
Glad to help! Can you close this issue?

Thank you!

**Comment by williamli186** [comment]
OK!
