### ISSUE TITLE
Reshaping in custom loss causes error:  "Incompatible shapes: [8] vs. [16]"

### ISSUE THREAD

**Issue by bbenligiray** [keras-team/keras#8813]
I want to write a loss function that compares the outputs of example pairs in a batch. I feed the inputs and labels as 1D arrays, then reshape in the loss function and apply softmax. This gives the following error:

```
InvalidArgumentError (see above for traceback): Incompatible shapes: [8] vs. [16]
	 [[Node: mul_1 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](Mean, _arg_dense_1_sample_weights_0_0/_7)]]
	 [[Node: mul_2/_27 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_345_mul_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
```

There is a minimal example below. It would be great if someone could take a look.

```
import numpy as np
import keras
import keras.backend as K


def custom_loss(y_true, y_pred):
	y_true = K.reshape(y_true, [-1, 2])
	y_pred = K.reshape(y_pred, [-1, 2])
	y_pred = keras.layers.Activation('softmax')(y_pred)
	return keras.losses.categorical_crossentropy(y_true, y_pred)


y = np.zeros((16),dtype=np.float32)
y[::2] = 1
x = (y + np.random.rand((16))).astype(np.float32)

a = keras.layers.Input(shape = (1,))
b = keras.layers.Dense(1)(a)
model = keras.models.Model(inputs=a, outputs=b)

model.compile(optimizer='sgd', loss=custom_loss)
model.fit(x, y)
```

Traceback:

```
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    model.fit(x, y)
  File "/home/burak/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 1430, in fit
    initial_epoch=initial_epoch)
  File "/home/burak/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 1079, in _fit_loop
    outs = f(ins_batch)
  File "/home/burak/anaconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2268, in __call__
    **self.session_kwargs)
  File "/home/burak/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/burak/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/burak/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/burak/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [8] vs. [16]
	 [[Node: mul_1 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](Mean, _arg_dense_1_sample_weights_0_0/_7)]]
	 [[Node: mul_2/_27 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_345_mul_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'mul_1', defined at:
  File "test.py", line 21, in <module>
    model.compile(optimizer='sgd', loss=custom_loss)
  File "/home/burak/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 840, in compile
    sample_weight, mask)
  File "/home/burak/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 462, in weighted
    score_array *= weights
  File "/home/burak/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 838, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/burak/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 1061, in _mul_dispatch
    return gen_math_ops._mul(x, y, name=name)
  File "/home/burak/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1377, in _mul
    result = _op_def_lib.apply_op("Mul", x=x, y=y, name=name)
  File "/home/burak/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/burak/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/burak/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()
```

**Comment by bbenligiray** [comment]
There seems to be a restriction that prevents us from changing `y_true` and `y_pred`'s first axis size (kind of similar to #4781). I worked around this by updating the loss function as such:

```
def custom_loss(y_true, y_pred):
	y_true = K.reshape(y_true, [-1, 2])
	y_true = K.concatenate([y_true, y_true], axis=0)

	y_pred = K.reshape(y_pred, [-1, 2])
	y_pred = keras.layers.Activation('softmax')(y_pred)
	y_pred = K.concatenate([y_pred, y_pred], axis=0)

	return keras.losses.categorical_crossentropy(y_true, y_pred)
```

**Comment by qysnn** [comment]
Since this is the first result when you google the error, I want to leave a hint for whoever is having the same problem. When you write and test your custom loss function, please note that Tensorflow/Keras will feed batch data into it. For example, say that your ypred/ytrue is a 3 element vector, during runtime the actual data's shape will be [?,3] where ? is your batch size. So you need to make sure that your custom loss function handle it correctly.
