### ISSUE TITLE
[Logic Error] About the model.save()

### ISSUE THREAD

**Issue by liuguiyangnwpu** [keras-team/keras#8832]
Hi,
I found a question about saving the model's weights?
If the layer01.name = "fire05", layer02.name = "fire05_bn". In this case, keras can't save the weights successfully.
I guess the "fire05" is the prefix of the "fire05_bn". 
The Error Information is:
```
input_1
lambda1
conv1
pool1
fire2/squeeze1x1
fire2/expand1x1
fire2/expand3x3
fire2
Traceback (most recent call last):
  File "ssd_squeezenet_trainer.py", line 72, in <module>
    model.save("sfdsf.h5")
  File "/usr/local/lib/python3.6/site-packages/keras/engine/topology.py", line 2556, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/usr/local/lib/python3.6/site-packages/keras/models.py", line 116, in save_model
    topology.save_weights_to_hdf5_group(model_weights_group, model_layers)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/topology.py", line 2851, in save_weights_to_hdf5_group
    g = f.create_group(layer.name)
  File "/usr/local/lib/python3.6/site-packages/h5py/_hl/group.py", line 50, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 151, in h5py.h5g.create
ValueError: Unable to create group (name already exists)
```

**Comment by haolidong** [comment]
I has same problem as you.   Do you know how to solve this?
I build a model fusion with ResNet50 and DenseNet121，raise the same Error with you when save model.
```
        img_input = Input(shape=input_shape)

        densenet = app.DenseNet121(
            include_top=False,
            input_tensor=img_input,
            input_shape=input_shape,
            weights=base_weights)
        resnet = app.ResNet50(
            include_top=False,
            input_tensor=img_input,
            input_shape=input_shape,
            weights=base_weights)
        x1 = densenet.output
        x1 = GlobalAveragePooling2D(name='dn_gap_last')(x1)
        x2 = resnet.output
        x2 = Flatten()(x2)
        x = concatenate([x1, x2], axis=-1)
        # x = GlobalAveragePooling2D()(x)
        predictions = Dense(len(class_names), activation="sigmoid", name="predictions")(x)
        model = Model(inputs=img_input, outputs=predictions)
```
raise error when saving model
```
Epoch 00001: val_loss improved from inf to 0.72018, saving model to ./experiments/8/weights.h5
Traceback (most recent call last):
  File "train.py", line 229, in <module>
    main()
  File "train.py", line 212, in main
    shuffle=False,
  File "/home/hqt/project/code/venv/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/hqt/project/code/venv/lib/python3.6/site-packages/keras/engine/training.py", line 2280, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/hqt/project/code/venv/lib/python3.6/site-packages/keras/callbacks.py", line 77, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/hqt/project/code/venv/lib/python3.6/site-packages/keras/callbacks.py", line 445, in on_epoch_end
    self.model.save_weights(filepath, overwrite=True)
  File "/home/hqt/project/code/venv/lib/python3.6/site-packages/keras/engine/topology.py", line 2607, in save_weights
    save_weights_to_hdf5_group(f, self.layers)
  File "/home/hqt/project/code/venv/lib/python3.6/site-packages/keras/engine/topology.py", line 2878, in save_weights_to_hdf5_group
    g = f.create_group(layer.name)
  File "/home/hqt/project/code/venv/lib/python3.6/site-packages/h5py/_hl/group.py", line 50, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 151, in h5py.h5g.create
ValueError: Unable to create group (name already exists)
```
