### ISSUE TITLE
FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated.

### ISSUE THREAD

**Issue by trDjango** [keras-team/keras#8989]
When I import the KERAS module, I get this warning.What can i do?
```
from keras.models import Sequential
/usr/local/lib/python3.6/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
```
thanks for helps

**Comment by trDjango** [comment]
topic moved here
[](https://github.com/h5py/h5py/pull/926)

**Comment by burakekincioglu** [comment]
can you solve this problem

**Comment by trDjango** [comment]
Hi burakekincioglu;
you should update with the following command:
`sudo python3.6 -m pip install git+https://github.com/h5py/h5py.git --upgrade`
or 
`sudo python2.7 -m pip install git+https://github.com/h5py/h5py.git --upgrade`
or
`sudo python3.5 -m pip install git+https://github.com/h5py/h5py.git --upgrade`

**Comment by Baaz-sb** [comment]
while doing so for [](sudo python3.5 -m pip install git+https://github.com/h5py/h5py.git --upgrade) 
I am getting the following error:

[Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.5/dist-packages/pip/__init__.py", line 26, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/usr/local/lib/python3.5/dist-packages/pip/utils/__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3018, in <module>
    @_call_aside
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3004, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3046, in _initialize_master_working_set
    dist.activate(replace=False)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2578, in activate
    declare_namespace(pkg)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2152, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2092, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2121, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
](url)

**Comment by EvaWang1224** [comment]
Have you solved the problem please? I've met the same error but I didn't know how to fix it. I've tried to update the python but it doesn't work.

**Comment by MahathiVavilala** [comment]
FutureWarnings can be ignored in this way:

import warnings as w
w.simplefilter(action = 'ignore', category = FutureWarning)

Try this and import the necessary module and  don't forget to reset the warnigs :

w.resetwarnings()

**Comment by devinhee** [comment]
I tried command: sudo python3.6 -m pip install git+https://github.com/h5py/h5py.git --upgrade
couldn't fit it.
ignore might be a good way
