### ISSUE TITLE
DenseNet cannot work correctly while other models (such as Inception-ResNetv2) works

### ISSUE THREAD

**Issue by xiaoyongzhu** [keras-team/keras#9041]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [Yes] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [Yes] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

Hi,

I am using the latest master branch in Keras and is trying to use the DenseNet implementation on a particular dataset. However, when training on the dataset, it throws the errors below:

```
Traceback (most recent call last):
  File "train_georgetest.py", line 233, in <module>
    validation_data=DataGenSequence(labels, partition['valid'], current_stat                                                                                    e='validation')
  File "/datadrive/xiaoyzhu/python3forvalidation/lib/python3.5/site-packages                                                                                    /keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/datadrive/xiaoyzhu/python3forvalidation/lib/python3.5/site-packages                                                                                    /keras/engine/training.py", line 2164, in fit_generator
    class_weight=class_weight)
  File "/datadrive/xiaoyzhu/python3forvalidation/lib/python3.5/site-packages                                                                                    /keras/engine/training.py", line 1836, in train_on_batch
    outputs = self.train_function(ins)
  File "/datadrive/xiaoyzhu/python3forvalidation/lib/python3.5/site-packages                                                                                    /keras/backend/tensorflow_backend.py", line 2475, in __call__
    **self.session_kwargs)
  File "/datadrive/xiaoyzhu/python3forvalidation/lib/python3.5/site-packages                                                                                    /tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/datadrive/xiaoyzhu/python3forvalidation/lib/python3.5/site-packages                                                                                    /tensorflow/python/client/session.py", line 1096, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (16, 14) for Tensor 'dense_1_target:0                                                                                    ', which has shape '(?, ?, ?, ?)'
```

and my model is built with the code below:
```
def build_model():
    """

    Returns: a model with specified weights

    """
    # define the model, use pre-trained weights for image_net
    base_model = DenseNet121(input_shape=(224, 224, 3),
                             weights='imagenet',
                             include_top=False,
                             pooling='avg')

    x = base_model.output
    predictions = Dense(14, activation='sigmoid')(x)
    model = Model(inputs=base_model.input, outputs=predictions)
    return model
```
However, if I change the `base_model` to a different one, such as Inception-ResNetv2, it works fine (at least start training process).

I suspect there might some implementation error in the newly committed DenseNet? The same code also works fine for the DenseNet in Keras_contrib (https://github.com/keras-team/keras-contrib/tree/master/keras_contrib/applications).

I am using Tensorflow 1.4.1, Keras from master branch, and Ubuntu 16.04.

**Comment by xiaoyongzhu** [comment]
cc @taehoonlee

**Comment by taehoonlee** [comment]
Would you please elaborate on the issue or share your whole codes @xiaoyongzhu? I tested the following codes on both Python 2.7 and 3.6 without any errors.

```python
import numpy as np
from keras.models import Model
from keras.layers import Dense
from keras.applications.densenet import DenseNet121

base_model = DenseNet121(input_shape=(224, 224, 3),
                         weights='imagenet',
                         include_top=False,
                         pooling='avg')

x = base_model.output
predictions = Dense(14, activation='sigmoid')(x)
model = Model(inputs=base_model.input, outputs=predictions)
print(model.predict(np.random.random((10, 224, 224, 3))))
```

**Comment by fchollet** [comment]
@xiaoyongzhu could you provide a standalone code snippet to reproduce the issue?

**Comment by xiaoyongzhu** [comment]
Thanks for taking a look! Below is the program (it's still a bit redundant though), and attached are the two required files (two pickle files). You can use either CPU or single/multiple GPU, they should all reproduce the problems.

```
import os

os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"  # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"] = ""

import keras.backend as K
from keras.optimizers import Adam
from keras.callbacks import ReduceLROnPlateau, Callback, ModelCheckpoint
import numpy as np
import pickle
from keras.applications.densenet import DenseNet121
from keras.layers import Dense
from keras.models import Model
from keras.utils import multi_gpu_model
from tensorflow.python.client import device_lib
import random
import warnings
from keras.utils import Sequence
import tensorflow as tf

# global variables
data_path = "/datadrive/xiaoyzhu/Data/ChestXRay/"
weights_dir = 'weights_tmpdir/'

initial_lr = 0.001
resized_height = 224
resized_width = 224
num_channel = 3
num_classes = 14
epochs = 200


num_gpu = 1

# keras multi_gpu_model slices the data to different GPUs. see https://keras.io/utils/#multi_gpu_model for more details.
batch_size = 16 * num_gpu


# use Keras multi-gpu model, so we need to make sure the batch_size is divisible by num_gpu.

# generator for train and validation data
class DataGenSequence(Sequence):
    def __init__(self, labels, npy_file_index, current_state):
        self.batch_size = batch_size
        self.labels = labels
        self.npy_file_index = npy_file_index
        self.current_state = current_state
        self.len = len(self.npy_file_index) // self.batch_size
        print("for DataGenSequence", current_state, "total rows are:", len(self.npy_file_index), ", len is", self.len)

    def __len__(self):
        return self.len

    def __getitem__(self, idx):
        # print("loading data segmentation", idx)
        # make sure each batch size has the same amount of data
        current_batch = self.npy_file_index[idx * self.batch_size: (idx + 1) * self.batch_size]
        X = np.empty((self.batch_size, resized_height, resized_width, num_channel))
        y = np.empty((self.batch_size, num_classes))

        for i, npy_name in enumerate(current_batch):
            # only do random flipping in training status
            if (random.randint(0, 9) < 5) and self.current_state == 'train':
                X[i, :, :, :] = np.random.random((224,224,3))
            else:
                X[i, :, :, :] = np.random.random((224,224,3))
            y[i, :] = labels[npy_name]

        return X, y


# loss function
def unweighted_binary_crossentropy(y_true, y_pred):
    """
    Args:
        y_true: true labels
        y_pred: predicted labels

    Returns: the sum of binary cross entropy loss across all the classes

    """
    return K.sum(K.binary_crossentropy(y_true, y_pred))


def build_model():
    """

    Returns: a model with specified weights

    """
    # define the model, use pre-trained weights for image_net
    base_model = DenseNet121(input_shape=(224, 224, 3),
                                     weights='imagenet',
                                     include_top=False,
                                     pooling='avg')

    x = base_model.output
    predictions = Dense(14, activation='sigmoid')(x)
    model = Model(inputs=base_model.input, outputs=predictions)
    return model



print("using single GPU")
model_multi_gpu = build_model()
model_checkpoint = ModelCheckpoint(
    weights_dir + 'chexnet_14_weights_712split_epoch_{epoch:03d}_val_loss_{val_loss:.4f}.hdf5',
    monitor='val_loss', save_weights_only=False)

model_multi_gpu.compile(optimizer=Adam(lr=initial_lr), loss=unweighted_binary_crossentropy)

reduce_lr_on_plateau = ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=5, verbose=1, min_lr=1e-7)

callbacks = [model_checkpoint, reduce_lr_on_plateau]

with open(data_path + 'labels14.pickle', 'rb') as f:
    labels = pickle.load(f)

with open(data_path + 'partition14.pickle', 'rb') as f:
    partition = pickle.load(f)


model_multi_gpu.fit_generator(generator=DataGenSequence(labels, partition['train'], current_state='train'),
                              epochs=epochs,
                              verbose=1,
                              callbacks=callbacks,
                              workers=32,
                              # shuffle=False,
                              validation_data=DataGenSequence(labels, partition['valid'], current_state='validation')
                              # validation_steps=1
                              )
```
[Desktop.zip](https://github.com/keras-team/keras/files/1627040/Desktop.zip)

**Comment by myutwo150** [comment]
I think the difference is that `DenseNet121(pooling='avg')` uses `AveragePooling2D` at the end, but the one in keras-contrib (and Inception-ResNet v2) uses `GlobalAveragePooling2D`.

The former implementation gives you an output shape `(None, 1, 1, 1024)`, while the latter gives `(None, 1024)`. If you take a look at `model.summary()`, you'll see that your final `Dense` layer has an output shape `(None, 1, 1, 14)`.

Changing the line `x = base_model.output` into `x = GlobalAveragePooling2D()(base_model.output)` should solve the issue.

**Comment by taehoonlee** [comment]
@xiaoyongzhu, you should add `Flatten`.
(e.g.,
```python
x = Dense(14, activation='sigmoid')(x)
predictions = Flatten()(x)
```
)

**Comment by taehoonlee** [comment]
@myutwo150 you are right. Alternatively, @xiaoyongzhu can use `Flatten`.
(e.g.,
```python
x = Flatten()(base_model.output)
x = Dense(14, activation='sigmoid')(x)
```
)

**Comment by xiaoyongzhu** [comment]
Thanks @myutwo150 - you are right. I didn't pay attention here, since the original paper (https://arxiv.org/pdf/1608.06993.pdf) was doing global average pooling, so I assume that applies for all the implementations. 

Just out of curiosity, @taehoonlee , why are we using average pooling layers instead of global average pooling (which is more often used in transfer learning case, IMO)?

**Comment by taehoonlee** [comment]
@xiaoyongzhu, the choice is up to you.
- `GlobalAveragePooling2D` is useful for classification of various input sizes.
- `AveragePooling2D` is useful for object detection.

**Comment by xiaoyongzhu** [comment]
That makes sense... Thanks for the clarification!

**Comment by NdodaEnde** [comment]
> @myutwo150 you are right. Alternatively, @xiaoyongzhu can use `Flatten`.
> (e.g.,
> 
> ```python
> x = Flatten()(base_model.output)
> x = Dense(14, activation='sigmoid')(x)
> ```
> 
> )

am curious what will happen if you add new classifier layers like this:
```flat_layer = Flatten()(model.layers[-1].output)
x = GlobalAveragePooling2D(flat_layer)
classifier = Dense(128, activation = 'relu', kernel_initializer = 'he_uniform')(x)
```
