### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'loss'

### ISSUE THREAD

**Issue by vinayakumarr** [keras-team/keras#9091]
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
import keras
import keras.preprocessing.text
import itertools
from keras.callbacks import CSVLogger
from keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau, CSVLogger
from keras import callbacks
from keras.layers import LSTM, SimpleRNN, GRU
from keras.preprocessing import sequence
from keras.utils.np_utils import to_categorical
from keras.layers import Dense, Dropout, Activation, Embedding

trainlabels = pd.read_csv('data/famFinal.csv', header=None)
trainlabel = trainlabels.iloc[:,0]
seed = 7
train = pd.read_csv('data/seqFinal.csv', header=None)

X = train.values.tolist()
X = list(itertools.chain(*X))

 # Generate a dictionary of valid characters
valid_chars = {x:idx+1 for idx, x in enumerate(set(''.join(X)))}

max_features = len(valid_chars) + 1
maxlen = np.max([len(x) for x in X])
print(maxlen)

maxlen=1000
# Convert characters to int and pad
X = [[valid_chars[y] for y in x] for x in X]

X_train = sequence.pad_sequences(X, maxlen=maxlen)

y_train1 = np.array(trainlabel)
y_train= to_categorical(y_train1)

embedding_vecor_length = 26
def create_model():
       print("called")
       model = Sequential()
       model.add(Embedding(max_features, embedding_vecor_length, input_length=maxlen))
       model.add(SimpleRNN(64))
       model.add(Dropout(0.001))
       model.add(Dense(500))
       model.add(Activation('softmax'))
       model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
       print(model.summary())
  
estimator = KerasClassifier(build_fn=create_model, epochs=200, batch_size=1024, verbose=0)
kfold = KFold(n_splits=5, shuffle=True, random_state=seed)
results = cross_val_score(estimator, X_train, y_train, cv=kfold)
print(results)
print("Baseline: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

**The above program giving the below error.**

Traceback (most recent call last):
  File "lstm.py", line 118, in <module>
    results = cross_val_score(estimator, X_train, y_train, cv=kfold)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/model_selection/_validation.py", line 140, in cross_val_score
    for train, test in cv.split(X, y, groups))
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py", line 758, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py", line 608, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py", line 571, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/_parallel_backends.py", line 109, in apply_async
    result = ImmediateResult(func)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/_parallel_backends.py", line 322, in __init__
    self.results = batch()
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/usr/local/lib/python2.7/dist-packages/sklearn/model_selection/_validation.py", line 238, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python2.7/dist-packages/keras/wrappers/scikit_learn.py", line 203, in fit
    return super(KerasClassifier, self).fit(x, y, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/wrappers/scikit_learn.py", line 138, in fit
    loss_name = self.model.loss
AttributeError: 'NoneType' object has no attribute 'loss'

**Comment by vinayakumarr** [comment]
The above error can be corrected by using

return model after print(model.summary())

**Comment by LamzZ2** [comment]
The above error can be corrected by using

return model after print(model.summary())   It can't  solve this problem!!

**Comment by HQuality** [comment]
> The above error can be corrected by using
> 
> return model after print(model.summary())

actually solved. Thanks!
