### ISSUE TITLE
Unable to save and load model.

### ISSUE THREAD

**Issue by ayush1999** [keras-team/keras#9162]
Running:
```
from sklearn import datasets
from keras.models import Sequential
from keras.layers import Dense

iris = datasets.load_iris()

x = iris.data
y = iris.target

model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
			  optimizer='adam', metrics=['accuracy'])
model.fit(x, y, batch_size=15, epochs=150)
scores = model.evaluate(x, y)
model.save('modd.hdf5')

```
and then(running it in the same directory):
```
>>> from keras.models import load_model
       Using TensorFlow backend.
>>> model = load_model('modd.hdf5')

```
Gives: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ayush99/anaconda3/lib/python3.6/site-packages/keras/models.py", line 227, in load_model
    with h5py.File(filepath, mode='r') as f:
  File "/home/ayush99/anaconda3/lib/python3.6/site-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/ayush99/anaconda3/lib/python3.6/site-packages/h5py/_hl/files.py", line 101, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028290543/work/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028290543/work/h5py/_objects.c:2804)
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open (/home/ilan/minonda/conda-bld/h5py_1490028290543/work/h5py/h5f.c:2123)
OSError: Unable to open file (Unable to open file: name = 'model.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)
>>> model = load_model('modd.h5')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ayush99/anaconda3/lib/python3.6/site-packages/keras/models.py", line 227, in load_model
    with h5py.File(filepath, mode='r') as f:
  File "/home/ayush99/anaconda3/lib/python3.6/site-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/ayush99/anaconda3/lib/python3.6/site-packages/h5py/_hl/files.py", line 101, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028290543/work/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028290543/work/h5py/_objects.c:2804)
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open (/home/ilan/minonda/conda-bld/h5py_1490028290543/work/h5py/h5f.c:2123)
OSError: Unable to open file (Unable to open file: name = 'modd.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)
>>> 

```

Can someone tell me why is this happening? Also, whenever I say `model.save('model.hdf5')` , where does this HDF5 file get stored?

**Comment by anj-s** [comment]
I am unable to reproduce this issue. The file should be saved in the same directory from where you are running your model(since you are not specifying a path). Can you specify an explicit path to save your model such as "/tmp/modd.h5"? You can then verify the existence of the file, the right permissions for access and load the model if the previous two checks pass.

**Comment by Dref360** [comment]
From your output : 
`(Unable to open file: name = 'modd.h5'`
You do not provide the same name

**Comment by ayush1999** [comment]
@anj-s Whenever I save a model in the current directory, I should be able to see a modd.hdf5 file right? But no such file is created.

**Comment by ayush1999** [comment]
@Dref360 I'm saving the model as modd.hdf5 and then loading the same model. Why is this leading to a model not found error?

**Comment by AndreyGurevich** [comment]
Hi all!

I had issue with load_model() when path was containing tilda symbol: ~

Path with tilda, error:
`(fastai) amber4eg@fast-ai:~/sp-society-camera-model-identification$ python train.py -g 1 -t -m "~/sp-society-camera-model-identification/models/ResNet50_kf_do0.3_doc0.0_avg-epoch092-val_acc0.446875.hdf5"
Using TensorFlow backend.
Loading model ~/sp-society-camera-model-identification/models/ResNet50_kf_do0.3_doc0.0_avg-epoch092-val_acc0.446875.hdf5
Traceback (most recent call last):
  File "train.py", line 452, in <module>
    model = load_model(args.model, compile=False)
  File "/home/amber4eg/anaconda3/envs/fastai/lib/python3.6/site-packages/keras/models.py", line 237, in load_model
    with h5py.File(filepath, mode='r') as f:
  File "/home/amber4eg/anaconda3/envs/fastai/lib/python3.6/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/amber4eg/anaconda3/envs/fastai/lib/python3.6/site-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '~/sp-society-camera-model-identification/models/ResNet50_kf_do0.3_doc0.0_avg-epoch092-val_acc0.446875.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)`

Check the path, use path withour tilda. No error:
`(fastai) amber4eg@fast-ai:~/sp-society-camera-model-identification$ ls ~/sp-society-camera-model-identification/models/ResNet50_kf_do0.3_doc0.0_avg-epoch092-val_acc0.446875.hdf5
/home/amber4eg/sp-society-camera-model-identification/models/ResNet50_kf_do0.3_doc0.0_avg-epoch092-val_acc0.446875.hdf5
(fastai) amber4eg@fast-ai:~/sp-society-camera-model-identification$ python train.py -g 1 -t -m /home/amber4eg/sp-society-camera-model-identification/models/ResNet50_kf_do0.3_doc0.0_avg-epoch092-val_acc0.446875.hdf5
Using TensorFlow backend.
Loading model /home/amber4eg/sp-society-camera-model-identification/models/ResNet50_kf_do0.3_doc0.0_avg-epoch092-val_acc0.446875.hdf5
2018-01-31 11:58:44.534249: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
2018-01-31 11:58:44.646460: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-01-31 11:58:44.646741: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:00:04.0
totalMemory: 15.90GiB freeMemory: 15.51GiB
2018-01-31 11:58:44.646763: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0)
Overriding classifier: ResNet50 and crop size: 299`

**Comment by Jeayea** [comment]
In my case, I  just wrote a wrong path name.

**Comment by akshay-kap** [comment]
Hi, I am facing the same issue, it would be of great help if someone can explain it clearly
