### ISSUE TITLE
When I use multi_gpu_model, it can't work. (If the network has "batch_normalization")

### ISSUE THREAD

**Issue by Bonsen** [keras-team/keras#9165]
When I use multi_gpu_model, it can't work. (If the network has "batch_normalization")

  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 664, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable batch_normalization_1/moving_mean/biased already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "/usr/lib64/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1001, in moving_average_update
    x, value, momentum, zero_debias=True)
  File "/usr/lib64/python2.7/site-packages/keras/layers/normalization.py", line 185, in call
    self.momentum),
  File "/usr/lib64/python2.7/site-packages/keras/engine/topology.py", line 617, in __call__
    output = self.call(inputs, **kwargs)

**Comment by kodrzywolek** [comment]
I had similar problem yesterday. Try to upgrade tensorflow to version 1.4.

**Comment by anj-s** [comment]
Is this still an issue? Can you share the model that you are running using a code snippet? Thanks!

**Comment by Bonsen** [comment]
@kodrzywolek I try but It can't work.

**Comment by anj-s** [comment]
Can you share your model code? I want to try and reproduce the error. Thanks.

**Comment by Bonsen** [comment]
@anj-s 
```
from keras.utils import multi_gpu_model

def A_Net(n_ch,patch_height,patch_width):
    inputs = Input((n_ch, patch_height, patch_width))
    conv = Conv2D(size, (3, 3), padding='same')(inputs)
    conv = BatchNormalization(axis=axis)(conv)
....
....
....
    model = Model(input=inputs, output=conv_final)
    return model
...
model = multi_gpu_model(model, gpus=8)

```

**Comment by tRosenflanz** [comment]
try to pin model to CPU first via 
```
with tf.device('/cpu:0'):
                # define the serial model.
```
and only then convert it to multi-gpu. I had a similar issue with another [multi-gpu package](https://github.com/avolkov1/keras_experiments) before

**Comment by anj-s** [comment]
I am unable to reproduce this issue. I am able to successfully call the model using the code snippet above (I had to set a few of the variables). I did not have to pin the model to CPU first either.
Couple of questions:
- What version of Keras are you using?
- have you tried the multi_gpu_model without BatchNorm?
- can you paste the entire stack trace? 
Thanks.

**Comment by anj-s** [comment]
Found another user who has a stack trace similar to the one above: #9126

**Comment by Bonsen** [comment]
@tRosenflanz it doesn't work...

**Comment by Bonsen** [comment]
@anj-s  Yes, it's the same problem.
I think my version is 2.1.x, and the old version just give warning rather than errors.
So I use the old version finally.
PS：If the model doesn't have any BN layer, everything will be fine.

**Comment by anj-s** [comment]
What is the tensorflow-gpu version that you are using? I am able to reproduce this on version 1.3 but don't see this issue once I update tensorflow-gpu package to version 1.4. Can you try updating the tensorflow package version? Do you still see an error?

**Comment by Bonsen** [comment]
@anj-s  I found tf 1.4 can solve the problem.. thanks

**Comment by ShenggaoZhu** [comment]
a temporary hack: change `multi_gpu_model()` source code, line 156, from 

`with tf.name_scope('replica_%d' % gpu_id):`

to 

`with tf.variable_scope('replica_%d' % gpu_id):`

**Comment by nicolefinnie** [comment]
@ShenggaoZhu 

This hack doesn't work for me. If I have to use tensorflow 1.2.1, is there any way to work around this problem?


```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pointnet_seg.py", line 307, in <module>
    history = gpu_model.fit(x=x_train, y=y_train, validation_data=(x_val, y_val), batch_size=BATCH_SIZE,epochs=EPOCHS, shuffle = True)
  File "/gpfs/home/nilin/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1669, in fit
    validation_steps=validation_steps)
  File "/gpfs/home/nilin/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1206, in _fit_loop
    outs = f(ins_batch)
  File "/gpfs/home/nilin/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2475, in __call__
    **self.session_kwargs)
  File "/gpfs/home/nilin/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/gpfs/home/nilin/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/gpfs/home/nilin/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/gpfs/home/nilin/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: In[0].dim(0) and In[1].dim(0) must be the same: [4,20,3] vs [16,3,3]
	 [[Node: replica_2/model_1/lambda_1/MatMul = BatchMatMul[T=DT_FLOAT, adj_x=false, adj_y=false, _device="/job:localhost/replica:0/task:0/gpu:2"](replica_2/lambda_6/Slice, reshape_1/Reshape/_1949)]]

Caused by op 'replica_2/model_1/lambda_1/MatMul', defined at:
  File "pointnet_seg.py", line 303, in <module>
    model, gpu_model = build_model(input_shape = (x_train.shape[1], x_train.shape[2]), output_categories = (y_train.shape[2]), optimizer=opt, given_model=None )
  File "pointnet_seg.py", line 279, in build_model
    gpu_model = multi_gpu_model(model, GPU)
  File "/gpfs/home/nilin/anaconda3/lib/python3.6/site-packages/keras/utils/training_utils.py", line 170, in multi_gpu_model
    outputs = model(inputs)
  File "/gpfs/home/nilin/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 617, in __call__
    output = self.call(inputs, **kwargs)
  File "/gpfs/home/nilin/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 2078, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "/gpfs/home/nilin/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 2229, in run_internal_graph
    output_tensors = _to_list(layer.call(computed_tensor, **kwargs))
  File "/gpfs/home/nilin/anaconda3/lib/python3.6/site-packages/keras/layers/core.py", line 663, in call
    return self.function(inputs, **arguments)
  File "pointnet_seg.py", line 202, in mat_mul
    return tf.matmul(A, B)
  File "/gpfs/home/nilin/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1786, in matmul
    a, b, adj_x=adjoint_a, adj_y=adjoint_b, name=name)
  File "/gpfs/home/nilin/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 290, in _batch_mat_mul
    adj_y=adj_y, name=name)
  File "/gpfs/home/nilin/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/gpfs/home/nilin/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/gpfs/home/nilin/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): In[0].dim(0) and In[1].dim(0) must be the same: [4,20,3] vs [16,3,3]
	 [[Node: replica_2/model_1/lambda_1/MatMul = BatchMatMul[T=DT_FLOAT, adj_x=false, adj_y=false, _device="/job:localhost/replica:0/task:0/gpu:2"](replica_2/lambda_6/Slice, reshape_1/Reshape/_1949)]]

```
