### ISSUE TITLE
TypeError: string indices must be integers when using model config

### ISSUE THREAD

**Issue by phanphuong6** [keras-team/keras#9194]
Hi, I used config = model.get_config() to get model config and insert it into a mysql table. When I select it from mysql table I can get and print it out as a list (inside is dictionary format). However, when I tried to re-instantiate it using model = Model.from_config(config) or model = Sequential.from_config(config). I got error as below.

Traceback (most recent call last):
  File "testcallmodel.py", line 48, in <module>
    model_id=args.mi,
  File "testcallmodel.py", line 32, in call
    model = Sequential.from_config(config)
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 1348, in from_config
    return cls.legacy_from_config(config)
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 1416, in legacy_from_config
    first_layer = normalize_legacy_config(first_layer)
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 1397, in normalize_legacy_config
    class_name = conf['name']
TypeError: string indices must be integers

While the config that I can print out look like this. Sorry that I did not show all the config here. But I think you can figure out if it is a bug or not. 

config: [{'class_name': 'LSTM', 'config': {'kernel_initializer': {'class_name': 'VarianceScaling',  ..........................................'bias_constraint': None, 'use_bias': True, 'kernel_constraint': None, 'activity_regularizer': None, 'trainable': True, 'name': 'dense_2', 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'bias_regularizer': None}}]

Many thanks!

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by phanphuong6** [comment]
Hi, never mind, i succeeded to make it using to_json.
Thank you very much.
