### ISSUE TITLE
multi-gpu with checkpointer is not safe when save model

### ISSUE THREAD

**Issue by Bonsen** [keras-team/keras#9277]
after Epoch 00001 val set, it gives as following:
keras :'2.1.3'
tf-gpu:'1,4,1'
```
Traceback (most recent call last):
  File "./src/train_all.py", line 654, in <module>
    parallel_model.fit(patches_imgs_train, [patches_masks_train,patches_masks_train2], nb_epoch=n_epochs, batch_size=batch_size, verbose=1, shuffle=True, validation_split=0.2, callbacks=[checkpointer])
  File "/usr/lib64/python2.7/site-packages/keras/engine/training.py", line 1669, in fit
    validation_steps=validation_steps)
  File "/usr/lib64/python2.7/site-packages/keras/engine/training.py", line 1226, in _fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/lib64/python2.7/site-packages/keras/callbacks.py", line 76, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/lib64/python2.7/site-packages/keras/callbacks.py", line 418, in on_epoch_end
    self.model.save(filepath, overwrite=True)
  File "/usr/lib64/python2.7/site-packages/keras/engine/topology.py", line 2573, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/usr/lib64/python2.7/site-packages/keras/models.py", line 111, in save_model
    'config': model.get_config()
  File "/usr/lib64/python2.7/site-packages/keras/engine/topology.py", line 2414, in get_config
    return copy.deepcopy(config)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 230, in _deepcopy_list
....
....
....
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.7/copy.py", line 329, in _reconstruct
    y = callable(*args)
  File "/usr/lib64/python2.7/copy_reg.py", line 93, in __newobj__
    return cls.__new__(cls, *args)
TypeError: object.__new__(NotImplementedType) is not safe, use NotImplementedType.__new__()
```
If I use one gpu, everything is ok.

I see in website:
To save the multi-gpu model, use .save(fname) or .save_weights(fname) with the template model (the argument you passed to multi_gpu_model), rather than the model returned by multi_gpu_model.

But I can't see where to set old model in 
checkpointer = ModelCheckpoint(filepath='./src/model/'+'best_weights.h5', monitor='val_loss',verbose=1, mode='auto', save_best_only=True) 
 parallel_model.fit(patches_imgs_train, [patches_masks_train,patches_masks_train2], nb_epoch=n_epochs, batch_size=batch_size, verbose=1, shuffle=True, validation_split=0.2, callbacks=[checkpointer])

Can't  I use checkpointer and multi-gpu together?

**Comment by alexdonchuk** [comment]
The same for me in deepcopy

**Comment by DexterLei** [comment]
You have to define a new callback function, like this:
[ParallelModelCheckpoint](https://github.com/keras-team/keras/issues/10218)
