### ISSUE TITLE
IndexError: list/tuple index out of range

### ISSUE THREAD

**Issue by DariusAlexander** [keras-team/keras#9299]
Spent a while checking over this - <s>hopefully it's a legit bug and I'm not just being a no0b</s> pretty sure it's a bug.

Below is a simple script that should reproduce the issue.

```
import tensorflow as tf
from tensorflow import keras
from keras.models import Model
from keras.layers import *

def make_model():	
	x = [None] * 2
	x[0] = Input(shape=(1, 16))
	x[1] = Input(shape=(1, 16))
	
	concat = Concatenate(axis=1)(x) #shape(?, 2, 16)
	conv = Conv1D(16, 2, padding='valid')(concat) #shape(?, 1, 16) ERROR?
		
	model = Model(inputs=x, outputs=conv)
	model.compile(optimizer='adam', loss='mse')
	return model

def main():
	model = make_model()
	model.summary()
	
	array = tf.zeros([1,16], dtype='float32')
	
	foo = model([array, array]) #ERROR

if __name__ == "__main__":
	main()
```

Error
```
Traceback (most recent call last):
  File "1dconvtest.py", line 32, in <module>
    main()
  File "1dconvtest.py", line 28, in main
    foo = model([array, array]) #ERROR
  File "build/bdist.macosx-10.12-intel/egg/keras/engine/topology.py", line 617, in __call__
  File "build/bdist.macosx-10.12-intel/egg/keras/engine/topology.py", line 2078, in call
  File "build/bdist.macosx-10.12-intel/egg/keras/engine/topology.py", line 2229, in run_internal_graph
  File "build/bdist.macosx-10.12-intel/egg/keras/layers/convolutional.py", line 160, in call
  File "build/bdist.macosx-10.12-intel/egg/keras/backend/tensorflow_backend.py", line 3294, in conv1d
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 762, in convolution
    name=name, data_format=data_format)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 808, in __init__
    input_channels_dim = input_shape[num_spatial_dims + 1]
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 521, in __getitem__
    return self._dims[key]
IndexError: list index out of range
```

**Comment by DariusAlexander** [comment]
Still not sure what's really going on here, but sometimes the keras backend is processing with strange shapes - such as an additional dimension in input_shape, shaped -2. eg (None, x, y, ...) turns to (None, -2, x, y, ...)

Discovered in convolutional.py, line 188
