### ISSUE TITLE
NASNet ValueError

### ISSUE THREAD

**Issue by zhudaoruyi** [keras-team/keras#9355]
Below is the demo 
`
    base_model = NASNetMobile(weights='imagenet', include_top=False, input_shape=(width, height, 3))
    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    x = Dense(1024, activation='relu')(x)
    x = BatchNormalization()(x)
    x = Dropout(0.5)(x)
    predictions = Dense(16, activation='softmax')(x)

    for layer in base_model.layers:
        layer.trainable = True

    model = Model(inputs=base_model.input, outputs=predictions)
    model.compile(optimizer=SGD(lr=0.01, momentum=0.9, nesterov=True), loss=['categorical_crossentropy'], metrics=['accuracy'])
    model.fit_generator(data_generator,
                        steps_per_epoch=100,
                        epochs=epochs,
                        validation_data=data_generator(train=False),
                        validation_steps=20,
                        verbose=1)
`

But,after executing ,
`
Traceback (most recent call last):

  File "/home/pzw/keras_train/train_ir_01.py", line 33, in get_model
    base_model = NASNetMobile(weights='imagenet', include_top=False, input_shape=(width, height, 3))
  File "/home/pzw/venv2/local/lib/python2.7/site-packages/keras/applications/nasnet.py", line 432, in NASNetMobile
    default_size=224)
  File "/home/pzw/venv2/local/lib/python2.7/site-packages/keras/applications/nasnet.py", line 220, in NASNet
    block_id='stem_1')
  File "/home/pzw/venv2/local/lib/python2.7/site-packages/keras/applications/nasnet.py", line 625, in _reduction_a_cell
    block_id='reduction_1_%s' % block_id)
  File "/home/pzw/venv2/local/lib/python2.7/site-packages/keras/applications/nasnet.py", line 458, in _separable_conv_block
    kernel_initializer='he_normal')(x)
  File "/home/pzw/venv2/local/lib/python2.7/site-packages/keras/engine/topology.py", line 617, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/pzw/venv2/local/lib/python2.7/site-packages/keras/layers/convolutional.py", line 1231, in call
    dilation_rate=self.dilation_rate)
  File "/home/pzw/venv2/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 3478, in separable_conv2d
    data_format=tf_data_format)
  File "/home/pzw/venv2/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_impl.py", line 486, in separable_conv2d
    channel_multiplier * in_channels, out_channels))
ValueError: Refusing to perform an overparameterized separable convolution: channel_multiplier * in_channels = 1 * 32 = 32 > 11 = out_channels
`

**Comment by ankitraj7217** [comment]
Try installing higher version of tensorflow.. Probably above 1.5.. I have installed 1.12 and it worked out for me..

**Comment by BlackHandguy** [comment]
I also have the  question,did you solve it,how

**Comment by BlackHandguy** [comment]
> 尝试安装更高版本的tensorflow ..可能高于1.5 ..我已经安装了1.12，它为我工作..
 I have installed 1.13 , but it doesn't work out for me,  the same question
