### ISSUE TITLE
Function works in a session but not as Keras loss function

### ISSUE THREAD

**Issue by DanielBonanno** [keras-team/keras#9371]
I am writing a custom loss function in keras.

```
def custom_loss(y_true, y_pred):
        c1 = (0.01 ** 2)
        c2 = (0.03 ** 2)

	y_true = tf.transpose(y_true, [0, 2, 3, 1])
	y_pred = tf.transpose(y_pred, [0, 2, 3, 1])

      	patches_true = tf.extract_image_patches(y_true, [1, 8, 8, 1], [1, 8, 8, 1], [1, 1, 1, 1], "SAME")
        patches_pred = tf.extract_image_patches(y_pred, [1, 8, 8, 1], [1, 8, 8, 1], [1, 1, 1, 1], "SAME")

        # Get mean
        u_true = K.mean(patches_true, axis=-1)
        u_pred = K.mean(patches_pred, axis=-1)
        # Get variance
        var_true = K.var(patches_true, axis=-1)
        var_pred = K.var(patches_pred, axis=-1)
        # Get std dev
        std_true = K.sqrt(var_true)
        std_pred = K.sqrt(var_pred)
	covar_true_pred = std_pred * std_true

        ssim = (2 * u_true * u_pred + c1) * (2 * covar_true_pred + c2)
        denom = (K.square(u_true) + K.square(u_pred) + c1) * (var_pred + var_true + c2)
        ssim /= denom  

	return K.mean((1.0 - ssim) / 2.0)

```
Running it as follows:

    test =  custom_loss(test_1, test_2)
    init_op = tf.initialize_all_variables()
    
    with tf.Session() as sess:
        sess.run(init_op) #execute init_op
        print (sess.run(test))

works correctly, where test_1 and test_2 are test variables I created.

However, when I set that function as a custom loss for a Keras Model, I get an error:

    Traceback (most recent call last):
      File "kerasmodel_const_init_customloss.py", line 434, in <module>
        model.fit(x=[np.array(training_data_LR), np.array(training_data_MC)], y=[np.array(training_data_HR)], batch_size=128, epochs=2, verbose=1, validation_data=([np.array(validation_data_LR), np.array(validation_data_MC)], np.array(validation_data_HR)), shuffle=True, callbacks=[log_callback, checkpoint_callback])
      File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 965, in fit
        validation_steps=validation_steps)
      File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1646, in fit
        self._make_train_function()
      File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 970, in _make_train_function
        loss=self.total_loss)
      File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
        return func(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/keras/optimizers.py", line 162, in get_updates
        grads = self.get_gradients(loss, params)
      File "/usr/local/lib/python2.7/dist-packages/keras/optimizers.py", line 78, in get_gradients
        grads = K.gradients(loss, params)
      File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 2512, in gradients
        return tf.gradients(loss, variables, colocate_gradients_with_ops=True)
      File "/home/joe/.local/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 609, in gradients
        grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
      File "/home/joe/.local/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 375, in _MaybeCompile
        return grad_fn()  # Exit early
      File "/home/joe/.local/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 609, in <lambda>
        grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
      File "/home/joe/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_grad.py", line 733, in _ExtractImagePatchesGrad
        rows_out = int(ceil(rows_in / stride_r))
    TypeError: unsupported operand type(s) for /: 'NoneType' and 'long'

Is this some error in Keras or my bad? What is the problem?

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by hiteshn97** [comment]
Did you find the cause? I am having the same error. My loss is Binary_crossentropy

**Comment by DanielBonanno** [comment]
Hi! More of a work around really. Apparently, the final layer's size is not determined automatically (hence the NoneType). To make it work, I added a reshape layer at the end, for training purposes. Would be interesting to know if the same solution works for you, please do share if it works for you too!
