### ISSUE TITLE
VAE example vae.fit() gives noneType error

### ISSUE THREAD

**Issue by kraglemylego** [keras-team/keras#9378]
Hi I am running the example for VAE in https://github.com/keras-team/keras/blob/master/examples/variational_autoencoder.py and it yields the following error.

x_train is the example MNIST data.

>>> vae.fit(x_train,
...         shuffle=True,
...         epochs=epochs,
...         batch_size=batch_size,
...         validation_data=(x_test, None))
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 1593, in fit
    batch_size=batch_size)
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 1437, in _standardize_user_data
    in zip(y, sample_weights, class_weights, self._feed_sample_weight_modes)]
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 1436, in <listcomp>
    for (ref, sw, cw, mode)
  File "D:\Anaconda\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 537, in _standardize_weights
    return np.ones((y.shape[0],), dtype=K.floatx())
AttributeError: 'NoneType' object has no attribute 'shape'
>>>

**Comment by yaobofd** [comment]
I met the same problem when I set "vae.compile(optimizer='rmsprop', loss='binary_crossentropy')".
Try to set "vae.compile(optimizer='rmsprop', loss='')" as described in https://github.com/keras-team/keras/pull/9344.
