### ISSUE TITLE
Error with multiprocessing on Sequence in fit_generator()

### ISSUE THREAD

**Issue by elcombato** [keras-team/keras#9434]
I'm trying to use a `Sequence` as the generator for `model.fit_generator()`.

With `use_multiprocessing=False` it works fine, but with `use_multiprocessing=True` an error is produced.

**Minimal working example:**
```python
from keras.utils import Sequence
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
import numpy as np

class DummySequence(Sequence):
    
    def __init__(self, x_set, y_set, batch_size):
        self.x, self.y = x_set, y_set
        self.batch_size = batch_size

    def __len__(self):
        return int(np.ceil(len(self.x) / float(self.batch_size)))

    def __getitem__(self, idx):
        batch_x = self.x[idx * self.batch_size:(idx + 1) * self.batch_size]
        batch_y = self.y[idx * self.batch_size:(idx + 1) * self.batch_size]

        return np.array(batch_x), np.array(batch_y)

if __name__ == '__main__':

    x = np.random.random((100, 3))
    y = to_categorical(np.random.random(100) > .5).astype(int)

    seq = DummySequence(x, y, 10)

    model = Sequential()
    model.add(Dense(32, input_dim=3))
    model.add(Dense(2, activation='softmax'))
    model.compile(optimizer='rmsprop',
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

    model.fit_generator(generator=seq, workers=2, use_multiprocessing=True)
```
**Error:**
```
Traceback (most recent call last):
  File "C:\Users\elcombato\AppData\Local\Continuum\Anaconda3\envs\ml\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\elcombato\AppData\Local\Continuum\Anaconda3\envs\ml\lib\site-packages\keras\utils\data_utils.py", line 392, in get_index
    return _SHARED_SEQUENCES[uid][i]
KeyError: 0
```

**Setup**
Windows 10
Python 3.6.4
Keras 2.1.3
Tensorflow 1.2.1

**Comment by Dref360** [comment]
I think that because on Windows, python has to spawn instead of forking, it may cause a mis-representation on the shared Variable. I'll work on it and try to test it on Windows.

**Comment by Dref360** [comment]
If you have time, could you try again with this branch while I try to find a pc with Windows? Would be awesome!
https://github.com/Dref360/keras/tree/mp_windows

**Comment by elcombato** [comment]
Yes that branch is working with multiprocessing!

**Comment by Dref360** [comment]
Okay, I'll try something to guarantee that we test all multiprocessing tests on Windows. (At least on python3) and then I'll submit a PR
