### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'Dot' when plot_model

### ISSUE THREAD

**Issue by forhonourlx** [keras-team/keras#9458]
Traceback (most recent call last):
  File "C:\Users\simon\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\utils\vis_utils.py", line 27, in _check_p
ydot
    pydot.Dot.create(pydot.Dot())
AttributeError: 'NoneType' object has no attribute 'Dot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "StrategyDQN_Multi-Instrument_0123.py", line 1935, in <module>
    RunSingleAgentExperiment()
  File "StrategyDQN_Multi-Instrument_0123.py", line 1459, in RunSingleAgentExperiment
    tmp_entity = Entity([comb_agent_arg], entity_args)
  File "StrategyDQN_Multi-Instrument_0123.py", line 1167, in __init__
    epsilon_annealing_steps=args["epsilon_annealing_steps"])
  File "StrategyDQN_Multi-Instrument_0123.py", line 420, in __init__
    self.target_network = self.create_network(architecture=architecture, algorithm=algorithm)
  File "StrategyDQN_Multi-Instrument_0123.py", line 604, in create_network
    plot_model(model,to_file='./models/LSTM_DDQN.png')#FileNotFoundError: [WinError 2] FileNotFoundError: [WinError 2] "dot.exe
" not found in path. ImportError: Failed to import pydot. You must install pydot and graphviz for `pydotprint` to work.
  File "C:\Users\simon\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\utils\vis_utils.py", line 135, in plot_mo
del
    dot = model_to_dot(model, show_shapes, show_layer_names, rankdir)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\utils\vis_utils.py", line 56, in model_to
_dot
    _check_pydot()
  File "C:\Users\simon\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\utils\vis_utils.py", line 31, in _check_p
ydot
    raise ImportError('Failed to import pydot. You must install pydot'
ImportError: Failed to import pydot. You must install pydot and graphviz for `pydotprint` to work.

Could anybody give me a hand?
Thanks

**Comment by Dref360** [comment]
In your stack trace : 
`Failed to import pydot. You must install pydot and graphviz for pydotprin`
