### ISSUE TITLE
How can I train the model if the input layer is larger than output layer?

### ISSUE THREAD

**Issue by ggsf13** [keras-team/keras#9663]
The output layer is cropped by cropping layer as (1328,2560,1) and the input layer is (1339,2560,1). So here comes the error: 

Fitting model...
unet.py:153: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  model.fit(imgs_train, imgs_mask_train, batch_size=2, nb_epoch=20, verbose=1,validation_split=0.2, shuffle=True, callbacks=[model_checkpoint])
Traceback (most recent call last):
  File "unet.py", line 169, in <module>
    myunet.train()
  File "unet.py", line 153, in train
    model.fit(imgs_train, imgs_mask_train, batch_size=2, nb_epoch=20, verbose=1,validation_split=0.2, shuffle=True, callbacks=[model_checkpoint])
  File "D:\softwares\Annoconda3\lib\site-packages\keras\engine\training.py", line 1637, in fit
    batch_size=batch_size)
  File "D:\softwares\Annoconda3\lib\site-packages\keras\engine\training.py", line 1487, in _standardize_user_data
    exception_prefix='target')
  File "D:\softwares\Annoconda3\lib\site-packages\keras\engine\training.py", line 123, in _standardize_input_data
    str(data_shape))
ValueError: Error when checking target: expected conv2d_29 to have shape (1328, 2560, 1) but got array with shape (1339, 2560, 1)

Can anyone tell me how to deal with it? I'm a rookie to keras.

**Comment by ggsf13** [comment]
I tried cropping the input layer and I get 
Input layers to a `Model` must be `InputLayer` objects.
