### ISSUE TITLE
tensorflow-gpu causes ImportError: cannot import name np_utils

### ISSUE THREAD

**Issue by jagiella** [keras-team/keras#9725]
I wanted to switch from theano to tensorflow. Using the default tensorflow module (CPU only) worked flawlessly, but rather slow. So I tried to install/use the GPU version instead:
**1. Complete removal of modules:**
```bash
$sudo pip2 uninstall tensorflow
$sudo pip2 uninstall tensorflow-gpu
```
**2. Installation of tensorflow-gpu**
```
$sudo pip2 install tensorflow-gpu
```
**Now already importing keras is failing with the following error message:**
```python
Traceback (most recent call last):
  File "example.py", line 69, in fit
    from keras.models import Sequential, load_model, save_model
  File "/usr/local/lib/python2.7/dist-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/__init__.py", line 2, in <module>
    from . import np_utils
ImportError: cannot import name np_utils
```

**Comment by galfaroi** [comment]
The same issue using Google Colab
