### ISSUE TITLE
Issue with using CNN + LSTM using Timedistributed()

### ISSUE THREAD

**Issue by kathanvyas** [keras-team/keras#9788]
I am currently trying to solve an issue using LRCN model which uses a combination of CNN and LSTM. I have followed issues on Github raised and was able to use the timeDistributed() for having time steps that would allow me to use LSTM after CNN. Here is the partial code where I have created the model:

```
K.set_image_dim_ordering('tf')
#inputs = Input(shape=(225, 225,3))
model = Sequential()
model.add(TimeDistributed(Conv2D(96, (11, 11),strides = (4,4), activation = 'relu'), input_shape=(10, 225, 225, 3)))
model.add(TimeDistributed(MaxPooling2D((3, 3), strides = (2,2))))
model.add(TimeDistributed(BatchNormalization()))
model.add(TimeDistributed(ZeroPadding2D(padding = (2,2))))
model.add(TimeDistributed(Conv2D(128, (5, 5), activation='relu')))
model.add(TimeDistributed(MaxPooling2D((3, 3), strides = (2,2))))
model.add(TimeDistributed(BatchNormalization()))
model.add(TimeDistributed(ZeroPadding2D(padding = (1,1))))


model.add(TimeDistributed(layers.Conv2D(384, (3, 3), activation='relu')))
model.add(TimeDistributed(ZeroPadding2D(padding = (1,1))))

#model.add(layers.MaxPooling2D((2, 2)))
model.add(TimeDistributed(Conv2D(192, (3, 3), activation='relu')))
model.add(TimeDistributed(ZeroPadding2D(padding = (1,1))))

model.add(TimeDistributed(Conv2D(128, (3, 3), activation='relu')))
model.add(TimeDistributed(MaxPooling2D((3, 3), strides = (2,2))))

#model.add(layers.MaxPooling2D((2, 2)))
model.add(TimeDistributed(Flatten()))
model.add(TimeDistributed(Dense(4096, activation='relu')))

model.add(LSTM(256, return_sequences = True))

model.add(TimeDistributed(Dense(4096, activation='relu')))
model.add(TimeDistributed(Dropout(0.5)))

model.add(LSTM(256, return_sequences = True))

model.add(layers.Dense(101, activation='relu'))
model.add(layers.Dropout(0.5))

model.add(layers.Dense(1, activation='sigmoid'))

#prediction = Activation('softmax', name='softmax')(dense_4)
#model = Model(input=inputs, output=prediction)
model.summary()    
    
    
    
    
opt = keras.optimizers.rmsprop(lr=1e-4, decay=1e-6)

    # Compling the model with the given optimizer
model.compile(loss='binary_crossentropy',
                  optimizer=opt,
                  metrics=['accuracy'])

train_datagen = ImageDataGenerator(rescale=1. / 255,
                                       shear_range=0.2,
                                       zoom_range=0.2,
                                       featurewise_center=False,  # set input mean to 0 over the dataset
                                       samplewise_center=False,  # set each sample mean to 0
                                       featurewise_std_normalization=False,  # divide inputs by std of the dataset
                                       samplewise_std_normalization=False,  # divide each input by its std
                                       zca_whitening=False,  # apply ZCA whitening
                                       rotation_range=0,  # randomly rotate images in the range (degrees, 0 to 180)
                                       width_shift_range=0.1,
                                       # randomly shift images horizontally (fraction of total width)
                                       height_shift_range=0.1,
                                       # randomly shift images vertically (fraction of total height)
                                       horizontal_flip=True,  # randomly flip images
                                       vertical_flip=False)

    # For testign we use only scaling data augmentation
test_datagen = ImageDataGenerator(rescale=1. / 255)

    # change the shape that needed to be resized
train_dir = 'C:/Users/Kathan/Desktop/Projectx/examples/frames/Data_Dir/train_dir'
train_generator = train_datagen.flow_from_directory(
        train_dir,
        target_size=(10,225, 225),
        batch_size=128,
        class_mode='binary')

test_dir = 'C:/Users/Kathan/Desktop/Projectx/examples/frames/Data_Dir/test_dir'
test_generator = test_datagen.flow_from_directory(
        test_dir,
        target_size=(10,225, 225),
        batch_size=128,
        class_mode='binary')


history = model.fit_generator(
          train_generator,
          steps_per_epoch=100,
          epochs=30,
          validation_data=test_generator,
          validation_steps=50)

print(history,model)
```

Hwoever even following solutions provided in the other issues, I am having teh following error:

```
> 
> Epoch 1/30
> Traceback (most recent call last):
>   File "/home/ec2-user/.local/lib/python3.6/site-packages/keras/utils/data_utils.py", line 578, in get
>     inputs = self.queue.get(block=True).get()
>   File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/pool.py", line 644, in get
>     raise self._value
>   File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/multiprocessing/pool.py", line 119, in worker
>     result = (True, func(*args, **kwds))
>   File "/home/ec2-user/.local/lib/python3.6/site-packages/keras/utils/data_utils.py", line 401, in get_index
>     return _SHARED_SEQUENCES[uid][i]
>   File "/home/ec2-user/.local/lib/python3.6/site-packages/keras/preprocessing/image.py", line 827, in __getitem__
>     return self._get_batches_of_transformed_samples(index_array)
>   File "/home/ec2-user/.local/lib/python3.6/site-packages/keras/preprocessing/image.py", line 1235, in _get_batches_of_transformed_samples
>     batch_x[i] = x
> ValueError: could not broadcast input array from shape (10,225,3) into shape (10,225,225,3)
>  
> The above exception was the direct cause of the following exception:
>  
> Traceback (most recent call last):
>   File "kathanAshModel.py", line 129, in <module>
>     validation_steps=50)
>   File "/home/ec2-user/.local/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
>     return func(*args, **kwargs)
>   File "/home/ec2-user/.local/lib/python3.6/site-packages/keras/models.py", line 1276, in fit_generator
>     initial_epoch=initial_epoch)
>   File "/home/ec2-user/.local/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
>     return func(*args, **kwargs)
>   File "/home/ec2-user/.local/lib/python3.6/site-packages/keras/engine/training.py", line 2192, in fit_generator
>     generator_output = next(output_generator)
>   File "/home/ec2-user/.local/lib/python3.6/site-packages/keras/utils/data_utils.py", line 584, in get
>     six.raise_from(StopIteration(e), e)
>   File "<string>", line 3, in raise_from
> StopIteration: could not broadcast input array from shape (10,225,3) into shape (10,225,225,3)
> 

```

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by kenkyusha** [comment]
I reimplemented what you display here with randomly generated data and everything runs fine here:

```
model = Sequential()
model.add(TimeDistributed(Conv2D(96, (11, 11),strides = (4,4), activation = 'relu'), input_shape=(10, 225, 225, 3)))
model.add(TimeDistributed(MaxPooling2D((3, 3), strides = (2,2))))
model.add(TimeDistributed(BatchNormalization()))
model.add(TimeDistributed(ZeroPadding2D(padding = (2,2))))
model.add(TimeDistributed(Conv2D(128, (5, 5), activation='relu')))
model.add(TimeDistributed(MaxPooling2D((3, 3), strides = (2,2))))
model.add(TimeDistributed(BatchNormalization()))
model.add(TimeDistributed(ZeroPadding2D(padding = (1,1))))


model.add(TimeDistributed(Conv2D(384, (3, 3), activation='relu')))
model.add(TimeDistributed(ZeroPadding2D(padding = (1,1))))

#model.add(layers.MaxPooling2D((2, 2)))
model.add(TimeDistributed(Conv2D(192, (3, 3), activation='relu')))
model.add(TimeDistributed(ZeroPadding2D(padding = (1,1))))

model.add(TimeDistributed(Conv2D(128, (3, 3), activation='relu')))
model.add(TimeDistributed(MaxPooling2D((3, 3), strides = (2,2))))

#model.add(layers.MaxPooling2D((2, 2)))
model.add(TimeDistributed(Flatten()))
model.add(TimeDistributed(Dense(4096, activation='relu')))

model.add(LSTM(256, return_sequences = True))

model.add(TimeDistributed(Dense(4096, activation='relu')))
model.add(TimeDistributed(Dropout(0.5)))

model.add(LSTM(256, return_sequences = True))

model.add(Dense(101, activation='relu'))
model.add(Dropout(0.5))

model.add(Dense(1, activation='sigmoid'))

#prediction = Activation('softmax', name='softmax')(dense_4)
#model = Model(input=inputs, output=prediction)
model.summary()
opt = keras.optimizers.rmsprop(lr=1e-4, decay=1e-6)
 # Compling the model with the given optimizer
model.compile(loss='binary_crossentropy',
                  optimizer=opt,
                  metrics=['accuracy'])

model.fit(X_train, y_train,
          batch_size=batch_size,
          epochs=1)
 ```

Looking at your code it seems like you copied a bunch of layers and put them together without understanding whats going on there?
Did it work out in the end?

**Comment by tawsinDOTuddin** [comment]
ValueError: Error when checking input: expected time_distributed_27_input to have 5 dimensions, but got array with shape (64, 99, 99, 1)

**Comment by kamleshkhaliya** [comment]
Actually the input to time distributed layer is 5D (batch size, time steps, width, height, chennels). but the imagedatagenerator is not taking care of time steps. 
In this case you need TimeDistributedImageDataGenerator.
