### ISSUE TITLE
Already have fed  a proper shape and dtype value for  placeholder , why it raised  an Invalid ArgumentError  error ?

### ISSUE THREAD

**Issue by Iamshg** [keras-team/keras#9804]
I need to tune parameter for a CNN at the first layer ,So what i did is **made a circulation ,and each step changed hyper parameter (the parameter is the number of kernel and the size of kernel )* .then output the result to local file,including the *acc* and *loss* ,so on .
Frame is :
```python 
for  kernel_number , kernel_size  in   combination of all allowed kernel_numbers and kernel_size :
          make  a  CNN model 
          train model  and  write the result to local file 
```
But when i ran the program , I got an unexpected  wrong ,so  amazing .
The core code is 
```python 
print(Y_train.shape)
#the result is (2200,11)
print(X_train.shape)
#the result is (2200,2,128,1)
for number , size in number_size:
    #model 
    inputs = Input(shape=(2, 128, 1), name='input_layer')
    inner = Convolution2D(number, size, padding='same', activation="relu", name="conv1",
                          kernel_initializer='glorot_uniform')(inputs)
    inner = Dropout(rate=0.5, name='drop_layer1')(inner)
    inner = Convolution2D(16, (2, 3), padding="same", activation="relu", name="conv2",
                          kernel_initializer='glorot_uniform')(inner)
    inner = Dropout(rate=0.5, name='dropout_layer2')(inner)
    inner = Flatten(name='flatten_layer')(inner)
    inner = Dense(256, kernel_initializer="he_normal", activation="relu", name="dense1")(inner)
    inner = Dropout(rate=0.5)(inner)
    Y_preds = Dense(11, kernel_initializer='he_normal', activation='softmax', name="dense2")(inner)
    model = Model(inputs, Y_preds, name='model')
    model.compile(optimizer='adam', loss=loss_out,metrics=[metrics.categorical_accuracy])
    model.summary()
    #end model 
    #make dir 
    os.mkdir(dirpath.format(str(size[1]),str(number)))
    os.chdir(dirpath.format(str(size[1]),str(number)))
    os.mkdir('loss')
    os.mkdir('acc')
    os.mkdir('tensorboard')
    #make dir end 
    model.fit(X_train,Y_train,
              batch_size=batch_size,
              epochs=epochs,
              verbose=1,
              validation_split=0.2,
              callbacks = [
                    keras.callbacks.ModelCheckpoint(
                  
                        '{val_categorical_accuracy:.4f}.hdf5',
                        monitor='val_categorical_accuracy', verbose=0, save_best_only=True, mode='auto'
                    ),
                    keras.callbacks.EarlyStopping(monitor='val_categorical_accuracy', patience=5, verbose=0, mode='auto'),
                    keras.callbacks.TensorBoard('/TensorBoard/tb.log',
                          write_images=True,write_grads=True,write_graph=False,histogram_freq=1
                    )
              ]
    )
    #return original dir
    os.chdir('..')

```
The log and  error were:
```
Using TensorFlow backend.
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_layer (InputLayer)     (None, 2, 128, 1)         0
_________________________________________________________________
conv1 (Conv2D)               (None, 2, 128, 10)        50
_________________________________________________________________
drop_layer1 (Dropout)        (None, 2, 128, 10)        0
_________________________________________________________________
conv2 (Conv2D)               (None, 2, 128, 16)        976
_________________________________________________________________
dropout_layer2 (Dropout)     (None, 2, 128, 16)        0
_________________________________________________________________
flatten_layer (Flatten)      (None, 4096)              0
_________________________________________________________________
dense1 (Dense)               (None, 256)               1048832
_________________________________________________________________
dropout_1 (Dropout)          (None, 256)               0
_________________________________________________________________
dense2 (Dense)               (None, 11)                2827
=================================================================
Total params: 1,052,685
Trainable params: 1,052,685
Non-trainable params: 0
_________________________________________________________________
Train on 1760 samples, validate on 440 samples
Epoch 1/1
1760/1760 [==============================] - 6s 4ms/step - loss: 2.3977 - categorical_accuracy: 0.0966 - val_loss: 2.3969 - val_categorical_accuracy: 0.1250
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_layer (InputLayer)     (None, 2, 128, 1)         0
_________________________________________________________________
conv1 (Conv2D)               (None, 2, 128, 10)        90
_________________________________________________________________
drop_layer1 (Dropout)        (None, 2, 128, 10)        0
_________________________________________________________________
conv2 (Conv2D)               (None, 2, 128, 16)        976
_________________________________________________________________
dropout_layer2 (Dropout)     (None, 2, 128, 16)        0
_________________________________________________________________
flatten_layer (Flatten)      (None, 4096)              0
_________________________________________________________________
dense1 (Dense)               (None, 256)               1048832
_________________________________________________________________
dropout_2 (Dropout)          (None, 256)               0
_________________________________________________________________
dense2 (Dense)               (None, 11)                2827
=================================================================
Total params: 1,052,725
Trainable params: 1,052,725
Non-trainable params: 0
_________________________________________________________________
Train on 1760 samples, validate on 440 samples
Epoch 1/1
1024/1760 [================>.............] - ETA: 1s - loss: 2.3980 - categorical_accuracy: 0.0723Traceback (most recent call last):
  File "D:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1323, in _do_call
    return fn(*args)
  File "D:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1302, in _run_fn
    status, run_metadata)
  File "D:\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'dense2_target' with dtype float and shape [?,?]
         [[Node: dense2_target = Placeholder[dtype=DT_FLOAT, shape=[?,?], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "trian_cnn_conv1.py", line 136, in <module>
    write_images=True,write_grads=True,write_graph=False,histogram_freq=1
  File "D:\Python35\lib\site-packages\keras\engine\training.py", line 1657, in fit
    validation_steps=validation_steps)
  File "D:\Python35\lib\site-packages\keras\engine\training.py", line 1233, in _fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "D:\Python35\lib\site-packages\keras\callbacks.py", line 73, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "D:\Python35\lib\site-packages\keras\callbacks.py", line 778, in on_epoch_end
    result = self.sess.run([self.merged], feed_dict=feed_dict)
  File "D:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
    run_metadata_ptr)
  File "D:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1317, in _do_run
    options, run_metadata)
  File "D:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'dense2_target' with dtype float and shape [?,?]
         [[Node: dense2_target = Placeholder[dtype=DT_FLOAT, shape=[?,?], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'dense2_target', defined at:
  File "trian_cnn_conv1.py", line 112, in <module>
    model.compile(optimizer='adam', loss=loss_out,metrics=[metrics.categorical_accuracy])
  File "D:\Python35\lib\site-packages\keras\engine\training.py", line 755, in compile
    dtype=K.dtype(self.outputs[i]))
  File "D:\Python35\lib\site-packages\keras\backend\tensorflow_backend.py", line 497, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
  File "D:\Python35\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1599, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "D:\Python35\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 3090, in _placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "D:\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "D:\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'dense2_target' with dtype float and shape [?,?]
         [[Node: dense2_target = Placeholder[dtype=DT_FLOAT, shape=[?,?], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```
The most import information is the last line and was that 
```
InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'dense2_target' with dtype float and shape [?,?]
         [[Node: dense2_target = Placeholder[dtype=DT_FLOAT, shape=[?,?], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```
The keras and the TensorFlow i was using now is 
```
In [9]: keras.__version__
Out[9]: '2.1.2'
In [10]: import tensorflow
In [12]: tensorflow.__version__
Out[12]: '1.4.0'
```
I have three  question .
- one is what caused the error ,from the information , it said that *we must feed a Tensor with shape [?,?] to dense2_target  layer*, it is no *dense2_target*,where is the dense2_layer ?
- two is ,if  the *dense2_target* is my output layer in my model .The data which is feed to is Y_train and the shape is (2200，11),it is a shape with two axis ,,so what is wrong ?
- three is that ,if the code is wrong ,why the error triggered at the second cycle ,not the first cycle .

Additionally,the way i used to tuned the parameter is a bad way .The bad is that i must  to initialize a new model to run the network at each cycle .I ever tried to make the code easy because I know the frame of this network is same but the hyper parameter  but failed .If anyone have idea to do with it ,it also put a suggestion to me .I am very glod to see your reply .

**Comment by gabrieldemarmiesse** [comment]
Can you try with doing `K.clear_session()` at the end of the loop and report if it works then?

**Comment by gabrieldemarmiesse** [comment]
This error:
```
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x0000007F6C6D8240>>
Traceback (most recent call last):
  File "D:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 712, in __del__
  File "D:\Python35\lib\site-packages\tensorflow\python\framework\c_api_util.py", line 31, in __init__
TypeError: 'NoneType' object is not callable
```

Is nothing to be worried about. The exception was ignored, and I must admit it append to me quite a few times, but everything works fine.

I don't really understand what you mean by:

> The case I annotated keras.backend.clear_session()

Do you mean that you commented `keras.backend.clear_session()`?

**Comment by gabrieldemarmiesse** [comment]
In any way, `clear_session` destroys all tensorflow nodes and tensors. It's good practice to use it when you don't need the model anymore. Otherwise you might not free the ram taken by the model (when a keras model goes out of scope, the tensorflow graph isn't destroyed, you have to call clear_session manually or terminate the python process).
