### ISSUE TITLE
Inaccurate initialization for PReLU layer

### ISSUE THREAD

**Issue by arsenyinfo** [keras-team/keras#9810]
A current implementation of `PReLU` layer uses zero initialization for the `alpha` parameter. 

At the same time, initial research was based on `alpha = .25`, see https://arxiv.org/pdf/1502.01852.pdf / 2.1. Parametric Rectifiers / Optimization. As far as I understand (and observe for my networks), it may lead to less effective learning.

**Comment by gabrieldemarmiesse** [comment]
The initialization can be changed if you think it's going to result in a better learning. From the documentation:

`keras.layers.PReLU(alpha_initializer='zeros', alpha_regularizer=None, alpha_constraint=None, shared_axes=None)`

alpha_initializer: initializer function for the weights.

I admit that it's not very explicit and a PR on the docs to explain what should the initializer function do 
is more than welcome.

**Comment by arsenyinfo** [comment]
Hi @gabrieldemarmiesse, 
I'd suggest making .25 a default value - do you think it worth a PR?

**Comment by gabrieldemarmiesse** [comment]
I garantee 100% that it's going to be refused. You can't change the behaviour of previously written code without doing a major release (keras 3.0). So, sorry, it's quite possible that the default value is bad, but you won't be able to do anything about it unless the keras team decides to make another major release.

**Comment by arsenyinfo** [comment]
It's fair enough - I will just make a small comment for the docs.

**Comment by gabrieldemarmiesse** [comment]
That's a good idea! I support this option.

**Comment by yao-ying** [comment]
@arsenyinfo  Hi，my keras is 2.2.0,I use     def __init__(self, alpha_initializer={'class_name': 'Constant', 'config': {'value': .25}},
             alpha_regularizer=None,
             alpha_constraint=None,
             shared_axes=[1, 2],
             **kwargs): 
It is fine to train the model.But when I use model.get_layer('p_re_lu_1').get_weights() to get the parameter.It go wrong.
runfile('C:/Users/y/.spyder-py3/temptest.py', wdir='C:/Users/y/.spyder-py3')
Traceback (most recent call last):

  File "<ipython-input-5-c0e1ef49846d>", line 1, in <module>
    runfile('C:/Users/y/.spyder-py3/temptest.py', wdir='C:/Users/y/.spyder-py3')

  File "C:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 678, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 106, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/y/.spyder-py3/temptest.py", line 33, in <module>
    model = load_model('cifar10_ResNetPRelu20v1_model.001.h5')

  File "C:\Anaconda3\lib\site-packages\keras\engine\saving.py", line 261, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)

  File "C:\Anaconda3\lib\site-packages\keras\engine\saving.py", line 335, in model_from_config
    return deserialize(config, custom_objects=custom_objects)

  File "C:\Anaconda3\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')

  File "C:\Anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))

  File "C:\Anaconda3\lib\site-packages\keras\engine\network.py", line 1036, in from_config
    process_layer(layer_data)

  File "C:\Anaconda3\lib\site-packages\keras\engine\network.py", line 1022, in process_layer
    custom_objects=custom_objects)

  File "C:\Anaconda3\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')

  File "C:\Anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 147, in deserialize_keras_object
    return cls.from_config(config['config'])

  File "C:\Anaconda3\lib\site-packages\keras\engine\base_layer.py", line 1124, in from_config
    return cls(**config)

  File "C:\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "C:\Anaconda3\lib\site-packages\keras\layers\advanced_activations.py", line 112, in __init__
    **kwargs):

TypeError: super(type, obj): obj must be an instance or subtype of type

**Comment by yao-ying** [comment]
@arsenyinfo  I use     
def __init__(self, 
         alpha_initializer=initializers.Constant(value=0.25),
         alpha_regularizer=None,
         alpha_constraint=None,
         shared_axes=[1, 2],
         **kwargs):
It appear the same question.Can train but cann't got the parameter.

**Comment by yao-ying** [comment]
Hi everyone.It shound be note,If you use alpha_initializer={'class_name': 'Constant', 'config': {'value': 0.25}},after you change the code,you'd better restart your ide.If you donn't restart,Maybe your cann't use model.get_layer('p_re_lu_1').get_weights() to get the parameter.
