### ISSUE TITLE
Unable to import :- from keras.preprocessing.image import ImageDataGenerator 

### ISSUE THREAD

**Issue by Saini-96** [keras-team/keras#9973]
from keras.preprocessing.image import ImageDataGenerator
Traceback (most recent call last):

  File "<ipython-input-26-fe6240451925>", line 1, in <module>
    from keras.preprocessing.image import ImageDataGenerator

  File "C:\Program Files\Anaconda3\lib\site-packages\keras\preprocessing\image.py", line 13, in <module>
    import scipy.ndimage as ndi

  File "C:\Program Files\Anaconda3\lib\site-packages\scipy\ndimage\__init__.py", line 161, in <module>
    from .filters import *

  File "C:\Program Files\Anaconda3\lib\site-packages\scipy\ndimage\filters.py", line 37, in <module>
    from scipy.misc import doccer

  File "C:\Program Files\Anaconda3\lib\site-packages\scipy\misc\__init__.py", line 53, in <module>
    from scipy.interpolate._pade import pade

  File "C:\Program Files\Anaconda3\lib\site-packages\scipy\interpolate\__init__.py", line 176, in <module>
    from .interpolate import *

  File "C:\Program Files\Anaconda3\lib\site-packages\scipy\interpolate\interpolate.py", line 21, in <module>
    import scipy.special as spec

  File "C:\Program Files\Anaconda3\lib\site-packages\scipy\special\__init__.py", line 640, in <module>
    from ._ufuncs import *

ImportError: DLL load failed: The specified module could not be found.

**Comment by gabrieldemarmiesse** [comment]
As the traceback says, this is likely an issue with your installation of scipy. So this isn't really a keras issue.
