### ISSUE TITLE
CNN Regression with LSTM transfer learning error

### ISSUE THREAD

**Issue by bsundheimer** [keras-team/keras#9976]
I'm trying to train a model on grayscale infrared imagery time series, so I'm first building a model to detect a level in an image and then doing transfer learning to add on an LSTM onto the end to help smooth out the results and use data from multiple images to improve the results.  The initial model is created by the following, with the image_size being (360,240,1):

def create_model():
    nb_filters = 8
    nb_conv = 5

    model = Sequential()
    model.add(Convolution2D(nb_filters, (nb_conv, nb_conv),
                            border_mode='valid',
                            input_shape=image_size, dim_ordering="tf") )
    model.add(Activation('relu'))

    model.add(MaxPooling2D(pool_size=(2,2)))

    model.add(Convolution2D(nb_filters, (nb_conv, nb_conv)))
    model.add(Activation('relu'))

    model.add(Convolution2D(nb_filters, (nb_conv, nb_conv)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))

    model.add(Convolution2D(nb_filters, (nb_conv, nb_conv)))
    model.add(Activation('relu'))
    model.add(Dropout(0.25))

    model.add(Convolution2D(nb_filters*2, (nb_conv, nb_conv)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))

    model.add(Convolution2D(nb_filters*2, (nb_conv, nb_conv)))
    model.add(Activation('relu'))

    model.add(Convolution2D(nb_filters*2, (nb_conv, nb_conv)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Convolution2D(nb_filters*2, (nb_conv, nb_conv)))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))

    model.add(Flatten())
    model.add(Dense(256))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))

    model.add(Dense(128))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))

    model.add(Dense(1))
    model.add(Activation('linear'))
    model.compile(loss='mean_squared_error', optimizer=Adadelta())
    return model

And then  the LSTM on top of that to be:

def multiImageModel(modelFileName):
    input = Input(shape=image_size)

    model2 = load_model(modelFileName)
    for layer in model2.layers[:15]:
        layer.trainable = False

    for i in range(0,5):
        model2.pop()
    model = Sequential();

    model.add(TimeDistributed(model2)(input))
    model.add(LSTM(32))
    model.add(Dense(1))
    model.add(Activation('linear'))

    model.compile(loss='mean_squared_error', optimizer=Adadelta())
    return model

However, I get the following error with this implementation:
Traceback (most recent call last):
  File "deepLearningTest.py", line 177, in <module>
    model = train_model(n_epoch = 50)
  File "deepLearningTest.py", line 134, in train_model
    model = multiImageModel()#create_model()
  File "deepLearningTest.py", line 116, in multiImageModel
    model.add(TimeDistributed(model2)(input))
  File "/usr/local/lib/python3.6/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keras/layers/wrappers.py", line 213, in call
    y = self.layer.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keras/models.py", line 579, in call
    return self.model.call(inputs, mask)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/topology.py", line 2085, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/topology.py", line 2235, in run_internal_graph
    output_tensors = _to_list(layer.call(computed_tensor, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/keras/layers/convolutional.py", line 168, in call
    dilation_rate=self.dilation_rate)
  File "/usr/local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 3341, in conv2d
    data_format=tf_data_format)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 781, in convolution
    data_format=data_format)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 830, in __init__
    input_channels_dim = input_shape[num_spatial_dims + 1]
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 532, in __getitem__
    return self._dims[key]
IndexError: list index out of range

How can I get around this error?

**Comment by franciskim** [comment]
@bsundheimer did you have any luck with this?
